### ISSUE TITLE
translate directive messes with buttons

### ISSUE THREAD

**Issue by lverre** [angular-translate/angular-translate#1006]
Hi,

I have issues when using the translate directive with buttons, in particular when I use ng-show/hide and translate: some buttons are shown / hidden as they should but others don't.

This is clearly related to angular-translate because when I remove the translate directive, it works as expected.

Using filters instead of a directive works, but angular's website states that it's better to use the directive...

Here's an example that shows my issue: http://jsfiddle.net/nxrhpxuy/2/

Note that I had this problem on my website which uses angular 1.3.14 and angular-translate 2.6.1.

Thanks,

Laurian

**Comment by knalli** [comment]
btw: this fiddle is using Angular JS 1.2

**Comment by lverre** [comment]
That's because fiddle doesn't allow me to use a newer version. But I have the issue on my website as well and it uses angular 1.3.14.

**Comment by knalli** [comment]
You can inject your own JS, do not have to use the predefined ones. I've migrated it already to a plunkr, it's okay.

**Comment by tspaeth** [comment]
@lverre please you have the following choices for it to work correctly - it's more an issue of the combination / scope-creation for angular-translate and the ng-click-handling...:

prefix the scope variables with a model var and initialize it beforehand

```
<button ng-hide="mainmodel.isEditingName" type="button" class="btn btn-primary" ng-click="mainmodel.isEditingName = true" translate="SHARED_EDIT">Edit</button>
```

and in the controller, init it

```
var mainmodel = {};
```

Or, beginning from AngularJS 1.3, the controllerAs syntax 

```
<div ng-controller="EditCtrl as editCtl">
...
	<button ng-show="editCtl.edit" type="button" class="btn btn-primary" ng-click="save();" translate="SHARED_SAVE">Save</button>
	<button ng-show="editCtl.edit" type="button" class="btn btn-default" data-translate="SHARED_CANCEL">Cancel</button>
	<button ng-hide="editCtl.edit" type="button" class="btn btn-primary" ng-click="editCtl.edit = true" translate="SHARED_EDIT">Edit</button>

```
And also don't forget to update / change the corresponding variable name in the save - function :-)

Hope that helps...

**Comment by knalli** [comment]
And just for the reference, the [plnkr](http://plnkr.co/edit/nQGKmtS3UFB9yNbmPD0Z?p=info).

**Comment by lverre** [comment]
Thanks!
