### ISSUE TITLE
Using translate in controllers

### ISSUE THREAD

**Issue by bl4de** [angular-translate/angular-translate#1008]
Hello,

First of all - thanks for great work, angular-translate is very useful piece of code :)

I'm using this in quite typical way - application bases on Angular 1.3.x currently, I've got languages files and simply call {{'KEY' | translate }} in my HTML templates, however I have to provide translation directly in controller - there's $notify service calling from controller and displaying various messages to the user, for example:

```javascript
FilterService.setResults(false);
  $ionicLoading.hide();
  notify({
    message: 'Something goes wrong :/',    // <--- provide message in selected language here
    position: 'right',
    classes: 'notification  notification-warning',
    duration: 3000
});
$timeout(function () {
  notify.closeAll();
}, 3000);
```
I don't want to modify original HTML template of $notify and one more reason is that currently I am not able to predict if there won't be any other situations where this particular option (translate in controller) will have to be used.

First thing that came to my mind was to simply add some method(s) to provide this functionality directly in angular-translate code - but first of all, I don't want to modify its code (as I update all additional components via Bower and first update will destroy my code :) )
and second - I think this option might be useful not only for me, so it would be nice, if provided code will be well tested and follow best practices.

**Comment by knalli** [comment]
Easily use the service itself:

```js
$translate('yourkey').then(function (translation) {
	FilterService.setResults(false);
	  $ionicLoading.hide();
	  notify({
	    message: translation,    // <--- provide message in selected language here
	    position: 'right',
	    classes: 'notification  notification-warning',
	    duration: 3000
	});
	$timeout(function () {
	  notify.closeAll();
	}, 3000);
})
```

Or another level of wrapping depending on the need of ui state.

**Comment by knalli** [comment]
If you have one specific language only (in the app, no live changes of the translation at this point), you could use 

```js
      notify({
        message: $translation.instant('yourkey'),    // <--- provide message in selected language here
        position: 'right',
        classes: 'notification  notification-warning',
        duration: 3000
    });
```

**Comment by bl4de** [comment]
@knalli :
Thank you for such quick response, I've just found this in doc (I don't know how I missed it earlier, shame on me :P )

```javascript
$translate('HEADLINE').then(function (headline) {
    $scope.headline = headline;
  });
```

but I'd rather do something like this:

```javascript
  message: $translate.translate('ERROR')
```

But I see as $translate service returns a promise - it's the only option right now, am I right?

**Comment by DWand** [comment]
Also, it seems that with `notify` you can create your own templates. So, probably, you can translate your messages directly in the template.

**Comment by bl4de** [comment]
@knalli 
>  no live changes of the translation at this point

Unfortunately I have to handle more than one language and have to provide language switch option.

**Comment by knalli** [comment]
Then go with the first example I've given you. What is the problem with that? Promises will not hurt. ;)

**Comment by bl4de** [comment]
@knalli 

Of course they won't :) Just looking as simple way to do this as possible :) And it seems this migth be the solution I've been looking for.

@DWand 
This is also good solution, however I'm trying to do this directly in controller as I do not want to create/modify anything but this one single line of code (where I should provide translated message).

Thanks guys for your help.

**Comment by bl4de** [comment]
@knalli 

Yep, solution with $translate('KEY').then( /* show notify stuff */) works perfect.
Once again thank you.
