### ISSUE TITLE
Messageformat demo is broken (also was trying to set it up following the docs - no luck)

### ISSUE THREAD

**Issue by dmitryevseev** [angular-translate/angular-translate#1009]
To reproduce you can see docs page: http://angular-translate.github.io/docs/#/guide/14_pluralization

Demo at the bottom is broken and there are errors in the console.

Also I was trying to set up messageformat with angular-translate and it fails without any reason (angular application do not bootstrap on a page at all). Message format library and plugin loaded, stop happens after calling `$translateProvider.useMessageFormatInterpolation();` or `$translateProvider.useMessageFormatInterpolation();`

**Comment by DWand** [comment]
Hello, @dmitryevseev.

Probably, this issues is related to #952

**Comment by dmitryevseev** [comment]
@DWand Oh, yes, thank you. It's the exact duplicate. I'll close mine
