### ISSUE TITLE
Translate filter: how to translate only specific words in a different language?

### ISSUE THREAD

**Issue by LeleDev** [angular-translate/angular-translate#1011]
How can I instruct angular translate $filter to translate specific words in a certain language, without switching the current language for all the app using $translate.use()?

**Comment by DWand** [comment]
Hello, @LeleDev.
It looks like this issue is related to #500.

**Comment by knalli** [comment]
Yes, please follow #500. I'll close this as a duplicate.

**Comment by knalli** [comment]
But: I don't think the filter will gain that feature due technical limitations. Perhaps only available for directive/service.

**Comment by LeleDev** [comment]
Thank you
