### ISSUE TITLE
JSHint configuration actually broken

### ISSUE THREAD

**Issue by knalli** [angular-translate/angular-translate#1015]
```diff
-        eqeqeq: true,
-        globals: {
-          angular: true
-        }
+        jshintrc: true
```

And the .jshintrc will be used again actually. Big big issue.. I have just wondered why some stylings would be not rejected.

Additionally we can upgrade from 0.4 to latest 0.11.

**Comment by DWand** [comment]
As I know, there are some breaking changes in new versions of jshint. We can use [jscs](https://github.com/jscs-dev/node-jscs) together with jshint.

**Comment by knalli** [comment]
Updated to 0.11.2
