### ISSUE TITLE
Partial loader: Provide a simple way to set a needed structure of the loader

### ISSUE THREAD

**Issue by DWand** [angular-translate/angular-translate#1016]
The idea is to provide a simple way to set a needed structure of the partial loader. This feature may be used together with a router.

For example, imagine that there is a route called 'contacts'. When the user navigates to this route the loader has to have such parts as 'ui', 'common' and 'contacts'. Now the user has to delete previously registered parts and add needed parts manually in every route of the application. It looks like this situation can be solved somehow.

I see the following ways to solve the issue:

1) Create some sort of a wrapper (or a configurator) for ui-router (or any other router). This is not very flexible, each router has to have its own wrapper, it depends on the router's API. This thing may be created in another repository.

2) Create some helper service which can be called from a `resolve` method of a router. This way is more flexible and can be implemented either here or in its own repository.

3) Add a new method to the partial loader. Something like `setStructure([parts...])`. This way is pretty straight forward. But also it may be less flexible than the previous one according to limitations of loader functionality. This thing has to be implemented inside the loader.

Actually, there is at least one similar issue somewhere. But I can not find it. The user has provided a simple helper function which can be called from the router's `resolve` method to solve this task.

**Comment by knalli** [comment]
If I get this correctly, this would be actually a (probably) a promise based convenient helper managing `removeParts`, `addPart` and the afterwards `refresh` with the missing parts. Such a helper could be part of the partial loader, i.e. as a spec:

```js
// only the router knows the state and the state transition deciding which parts could be removed
{
  "resolve": $translatePartialLoader.getPartialUpdateResolver({
    add: ['ui', 'contacts', function () {return custom-array-or-string}],
    remove: 'or-just-a-static-defined-one'
  })
}
```

**Comment by DWand** [comment]
Hm... Yes, something like that. But, I think, it will be impossible to implement the refresh feature inside the helper if it is a method of the loader (because of a circular dependency).

As a method it could look like this:
```js
{
  "resolve": function routeResolveFn($translatePartialLoader, $translate) {
    $translatePartialLoader.setStructure(['ui', 'contacts'. 'common']);
    return $translate.refresh();
  }
```

or, in case of external helper, like this:
```js
{
  "resolve": function routeResolveFn($translatePartialHelper) {
    return $translatePartialHelper.setStructure(['ui', 'contacts'. 'common']);
  }
```

It may be something like this:
```
function setStructure(neededParts:String[]):Void
{
  parts = getRegisteredParts();

  foreach (parts as part)
    removePart(part)

  foreach (neededParts as part)
    addPart(part)
}
```

**Comment by knalli** [comment]
> But, I think, it will be impossible to implement the refresh feature inside the helper if it is a method of the loader (because of a circular dependency).

There is always being a way.

```js

// impl
$translatePartialLoader.refresh(config) {
  // apply the parts
  return $injector.get('$translate').refresh();
};

// usage
{
  "resolve": function routeResolveFn($translatePartialLoader) {
    return $translatePartialLoader.refresh({
      parts: ['ui', 'contacts', 'common']
    });
  }
}
```

**Comment by DWand** [comment]
Yes, there is a way with `$injector.get('$translate')`, but it look pretty hacky and I'd like to avoid its usage.

**Comment by DWand** [comment]
Hm... It looks like this issue is similar to #613.
I'm closing this issue as a duplicate.
