### ISSUE TITLE
$translate.use(lang) for Chrome and Firefox

### ISSUE THREAD

**Issue by Clempops** [angular-translate/angular-translate#1017]
I'm switching language with a fonction looking on a var ddSelectSelected. This is working on Safari, but not on Chrome and Firefox. When ddSelectSelected changes, I call changeLanguage. consol.log shows that everything should work fine. On Chrome, french is well displayed, but for english, only the alias is displayed ( {{'TITLE' | 'title'}}, here TITLE would be displayed). For FireFox, only french is displayed, on ddSelectSelected change, nothing changes.
```
$scope.changeLanguage = function() {
  if ($scope.ddSelectSelected.value == 'fr') {
    $translate.use('fr');
    console.log('fr_used');
  } else {
    $translate.use('en');
    console.log('en_used');
  }
}
```

**Comment by DWand** [comment]
Hello, @Clempops. Can you create plunker to show a problem in the correct context?

**Comment by Clempops** [comment]
I fixed the problem, it wasn't linked with angular-translate
