### ISSUE TITLE
translatePartialLoader getPart function to return translations for a specific part

### ISSUE THREAD

**Issue by davmelmeggeo** [angular-translate/angular-translate#1022]
For the current setup the following process is involved to load translation for particular part.

			$translateProvider.preferredLanguage('en');
			$translatePartialLoaderProvider.addPart('startup');
			$translateProvider.useLoader('$translatePartialLoader', {
				urlTemplate: namespace + '/API/Translations/?part={part}&lang={lang}'
			});
			$translate.refresh().then(function () {
				//Now we need to tell the $translate function which keys we want to fetch, 
				//even if we want to fetch ALL keys for a given .
				var laTranslationKeys = [				
					"part_translation_key1",
					"part_translation_key2",
					"part_translation_key3"
				];
				$translate(laTranslationKeys).then(function (translations) {
					//Assign scope translations - loaded in resolve of route.
					$scope.translations = translations;
				});
			});

It would be useful if there was a function getPart which would allow us to access the translations loaded for a particular part and language - something like this:

				service.getPart = function (name, lang) {
					if (angular.isDefined(parts[name]) && angular.isDefined(parts[name].tables[lang])) {
						return parts[name].tables[lang];
					}
				};
Then the translations keys would not need to be explicitly listed front end. We could load the part fully like this:

			$translateProvider.preferredLanguage('en');
			$translatePartialLoaderProvider.addPart('startup');
			$translateProvider.useLoader('$translatePartialLoader', {
				urlTemplate: namespace + '/API/Translations/?part={part}&lang={lang}'
			});

			//A function to return all translations for a given part would be useful so that we can then extract the keys
			//as shown below. Then we don't need to explicitly list all translation codes front end to load them.
			var loPartTranslations = $translatePartialLoaderProvider.getPart('startup');
			var laTranslationKeys = Object.keys(loPartTranslations);
			$translate.refresh().then(function () {
				$translate(loPartTranslations).then(function (translations) {
					//Assign scope translations - loaded in resolve of route.
					$scope.translations = translations;
				});
			});

**Comment by davmelmeggeo** [comment]
Then the translations keys would not need to be explicitly listed front end. We could load the part fully like this:

			$translateProvider.preferredLanguage('en');
			$translatePartialLoaderProvider.addPart('startup');
			$translateProvider.useLoader('$translatePartialLoader', {
				urlTemplate: namespace + '/API/Translations/?part={part}&lang={lang}'
			});

			//A function to return all translations for a given part would be useful so that we can then extract the keys
			//as shown below. Then we don't need to explicitly list all translation codes front end to load them.
			var loPartTranslations = $translatePartialLoaderProvider.getPart('startup');
			var laTranslationKeys = Object.keys(loPartTranslations);
			$translate.refresh().then(function () {
				$translate(loPartTranslations).then(function (translations) {
					//Assign scope translations - loaded in resolve of route.
					$scope.translations = translations;
				});
			});

**Comment by knalli** [comment]
Hi @davmelmeggeo,

it would "violate" the rest of the idea of the module when a loader itself expose its loaded content. Currently, only the service (and via the service also filters and directives) can manage, query or even manipulate this data. The loader does not know anything about interpolation, fallbacks and other mechanisms around the actual key-value-pattern (translation text by translation id).

Exposing its loaded keys would be okay, however, it will leave the question about the _value_ of that information regarding the additional features of angular-translate. And in addition to it, there is no static/direct way for getting the translations loaded by one part. That's because of two main reasons:

1. `addPart` is asynchronous and hiding the actual loading process. At the moment, you don't know when the part is available (option: listen to the loaded events).
2. At the moment the information (which translations belongs to which part) is only well-known during the load and merge process.

Following this, the data is being merged. That's the cause why deleting a part only removes the usage of the part and would skip that particular part if the next refresh/load. But content which was already being loaded will stay.

**Comment by knalli** [comment]
@DWand, master of partial loader, what do you think?

**Comment by davmelmeggeo** [comment]
Hm, good points.

Exposing the keys loaded with a given part would be useful. If not in a seperate function, then maybe another option would be that the keys could be added as a second (optional) parameter on the $translatePartialLoaderStructureChanged event?

**Comment by DWand** [comment]
Hello, @davmelmeggeo, @knalli.

I'm not sure that I understand the question correctly. There are some strange things in the provided code pieces, when providers are combined with services. But, however...

According to the given code pieces, what should this function return in case the part was not loaded yet? Or what should it return if the loader is loading data at the moment? Also, should it return a translation table or a list of keys? Should it return a real translation table or its copy?

As for events:
It is impossible to return keys with the `$translatePartialLoaderStructureChanged` event. It indicates that some part was added or deleted from the structure, not that the part is loaded. The loader fetches parts only if they are actually needed - when you call `use` or `refresh` methods of the `$translate` service, or when you directly call the loader. Also, it might be useless to add another event to indicate that the part is loaded from the server because parts may beset manually with the `setPart` method.

I agree with @knalli - the only practical result of this method is to get a list of translation keys. You might still need to translate them with the `$translate` service to get interpolation, fallbacks, error handling and other features.

Also keep in mind that the partial loader merges parts together according to their priority. So there is no guaranty that a "foo" translation key from part "A" will not be overridden by the same translation key from part "B" in the resulting translation table.

**Comment by DWand** [comment]
One more question: is this feature needed only for the partial loader or for all loaders?

**Comment by DWand** [comment]
Also, what should the method do in case the part is undefined?

**Comment by davmelmeggeo** [comment]
@DWand, @knalli - firstly thanks for your help. 

On the event front, I see now that its impossible, I hadn't checked, sorry. 

So it looks like a function to fetch the keys for a given part and language would be the best way to go. The function already seems to be in place to check if a part is loaded (isPartLoaded) so the user can check if the part is loaded before trying this 'getKeys' function - so if the part is missing, undefined, or not yet loaded the function could just return an error? 

I guess this feature could be useful for other loaders too.

**Comment by knalli** [comment]
>Also keep in mind that the partial loader merges parts together according to their priority. So there is no guaranty that a "foo" translation key from part "A" will not be overridden by the same translation key from part "B" in the resulting translation table.

Ah, @DWand , thank your for that piece. Not thought about this.

> But this does not handle nested keys. So Object.keys(parts[name].tables[lang]); would need to be replaced with a function that fetches all the keys in nested object as dot notation namespaces. (if i read the docs correctly)

@davmelmeggeo Well, it is actually not the concern of the loader knowing this process or structure. I'm really not happy adding such things into the library which must be maintained in future. It's very special and limited, but need work.

**Comment by davmelmeggeo** [comment]
OK, lets start back at the original problem and see if we can find the best solution. I only started using this library recently so am probably not in the best position to suggest the solution.

The problem:

Server side we split the translation list up into 'parts', each containing the translations necassary for a particular area of the software front end. This is useful because 'parts' can be loaded only when needed.

At present, we need to double up the list, all the keys need to be listed backend for the translation definitions AND then also frontend in order to fetch them with $translate(keys).

This requirement to explicitly list the keys is not good - one could argue that all translations are somewhere front-end anyway becuase that is where they are used, but all the different keys are used/encountered asyncronously (especially when loading translations dynamically from data). 

Because of this an option to load and translate ALL translations for a given part when loading an area of the software would be very useful. 

Possible solutions:

1) Have access to the keys loaded in a given part through the partial loader.
--- discussed above.

2) Have a $translate function that can fetch translations for a part instead of an explicit list of keys
--- obvious point here is that the $translate module shouldn't know anything about 'parts'

3) I can't think of any more - but maybe you have some suggestions for alternative solutions?

**Comment by knalli** [comment]
Ok, restart the issue ;)

Why do you want to fetch all translations ahead? Why do you not using the directive and filters in templates instead?

**Comment by davmelmeggeo** [comment]
Yep, maybe I am missing something and there is an easy solution.

First situation:
Some translations are bound directly to the template via a scope variable. So

The template contains things like this:

<label ng-bind="translations.translation_key"></label>

And the scope needs things like this:

$scope.translations.translation_key

And we load translations into the scope like this:

$translatePartialLoader.addPart(tcPart); //Adds all translations for this section of the software
					$translate.refresh().then(function () {
						$translate(laTranslationKeys).then(function (translations) {
							//Assign all translations used in this section to the scope
							toScope.translations = translations;
						});
					});

laTranslations currently needs to be defined, it can't be built from detecting the use of the translations in the template because the template is loaded asynchronously and so we need to list all the translations used in the template explicitly before calling $translate.


Second situation:

Some data is loaded later into the controller after initialization, maybe due to user interaction like a search and translations are built from the returned data

e.g.
1) We fetch data from the server which contains a field 'name'
2) We want these 'name's to be displayed differently depending on country
3) So you generate translation keys from this data ('translation_key_name_1', 'translation_key_name_2' ect...)
4) These translation keys are all defined backend and so are added with the part in the $translatePartialLoader.addPart(tcPart); 
5) Problem - these translation are not available front end until after we call $translate on them. 

On load there is no way of knowing that these will be used later so they can't be loaded by any method of 'first detect what translation keys are used then call $translate for these keys'. 

It seems to me that the only solution to these problems would be if I could call $translate on ALL the translation keys in the part. Then they are all available to use. 

This would also be a tidy solution as it allows for a standardized loading of all traslations in a given section at the start of loading that section.

Have I missed something that means these 2 things wouldn't require a definitive list of the translation keys?

**Comment by DWand** [comment]
@davmelmeggeo, most probably you miss something.

The only thing which comes to my mind that might require a complete list of translation keys in a part is building some kind of abstract translation tool. The list is required to build a table like this:

Language: ___en___. Part: ___common___.

| Translation key | Translation |
|---------------------|----------------|
| foo                    | Foo translation |
| bar                   | Bar translation is present  |
| buz                   | Buz translation is also here |

In this example you don't know what translations are present in the part, but you want to show all contents of it: both translation keys and their translation. In this case you'll probably need to create a special tool to achieve this task.

However, in a common application you actually know what translations are situated in every part. In this case the workflow is a bit different:

1) You get to some part of the application which uses a set of translations (for example, it could be a route in ui-router)
2) You add this part to the loader and call the `refresh` method (angular-translate will fetch all added parts from the server and merge them together)
3) You can freely use angular-translate's service, directive or filter to translate any translation key which you have in the view or wherever in this part of the application. angular-translate will automatically find these keys and return their translations.

In this example you don't need a complete list of translation keys, you don't need to translate them all on your own. You just add a part to the loader, refresh the module and ask it to translate those keys which you need at the moment.

Have you read our [guide](http://angular-translate.github.io/docs/#/guide)? Isn't it possible to achieve what you need using approaches and examples shown there?

**Comment by davmelmeggeo** [comment]
OK, I see now. It seems I had not understood some things as well as I should have before opening an issue.  

Sorry for wasting your time. But thank you very much for your help.
