### ISSUE TITLE
Translating Objectdata from a Service

### ISSUE THREAD

**Issue by iCymiCy** [angular-translate/angular-translate#1023]
Im trying to figure out how to declare translations for my object data from a service.
I could provide a key/value pair for each language, but then id have to filter my data in the controller..
My current approach is to just store the constant name as a string and then in my view get the translation from my predefined translation constants. however that is not working, here is my data:

	$localStorage.myData = [{
				ID:				1,
				title:			'ID1_TITLE',
				description:	'ID1_DESC',
				imgFolder:		'img',
		}, {
				ID:				2,
				title:			'ID2_TITLE',
				description:	'ID2_DESC',
				imgFolder:		'img',
                }];

and my view:

    <div ng-repeat="element in myData">{{ '{{element.title}}' | translate }}
    {{ '{{element.description}}' | translate }}</div>

Is this even possible? maybe there is even a simpler cleaner way of doing this?

**Comment by knalli** [comment]
Is  ```html
<div ng-repeat="element in myData">{{ element.title | translate }}
{{ element.description | translate }}</div>
```
not working for you ? :)

**Comment by iCymiCy** [comment]
right.. dont know what drove me there :-)
