### ISSUE TITLE
FOUC issues with partial loader

### ISSUE THREAD

**Issue by Discmt** [angular-translate/angular-translate#1026]
Hi guys, I'm having trouble with my setup in that I get lots of FOUC using the partial loader. I'm wondering what mechanisms I can put in place to maybe output empty string when the content is loaded. I've tried various things and am now open to suggestions.

**Comment by knalli** [comment]
@Discmt Do you have already taken a look into the documentation and guide chapters? Especially [this lines](http://angular-translate.github.io/docs/#/guide/12_asynchronous-loading#asynchronous-loading_fouc---flash-of-untranslated-content)...

**Comment by Discmt** [comment]
Is preloading a language the only way to remedy the issue? I was of the opinion there might be a way to just output blank strings until the translations complete.

**Comment by knalli** [comment]
I think we have explained the solutions already. Unstyled content will be displayed only using filters and not using a cloak. Both can be handled.
