### ISSUE TITLE
Promise returned $translate.refresh() never gets rejected in case of XHR failure

### ISSUE THREAD

**Issue by BonsaiDen** [angular-translate/angular-translate#1028]
https://github.com/angular-translate/angular-translate/blob/1aaab980760f8863551598ed748d200f1f03d9c6/src/service/translate.js#L1805 does not handle the case when `$q.all()` gets rejected.

I'm loading translation files lazily in the UI Router, so any missing unavailable / translation files will freeze the UI as the promise never gets rejected and the dependency does not get resolved in any way.

Would be great if `refresh()` would correctly reject the promise in case `$.all()` fails, this way one could at least implement a error message or implement other fallback logic.

**Comment by DWand** [comment]
It looks like this code was broken in this commit https://github.com/angular-translate/angular-translate/commit/aa5f5c979410f22bc821f88cfd3ec4a7938475f6. So we, probably, have to add tests for this case.

**Comment by tspaeth** [comment]
We should do something - maybe a pluggable solution / handler is indeed the best solution as the handling will differ from case to case (esp. with fallbacks missing...). 
But I'm wondering, that it will freeze on missing files? (404 case)

**Comment by BonsaiDen** [comment]
@tspaeth `$translate` itself doesn't freeze, but anything that expects `$translate.refresh()` to eventually get resolved / rejected will (in this case it's `ui-router` where the state change will never finish and the App gets hung up after clicking on a link etc.).

I initially ran into the 404 problem when I was trying to both give `$translate` a list of known language and then let it figure out the preferred language of the user. It ended up adding two languages to the internal fallback list, trying to request both and since one of them didn't exist, it never resolved `$translate.refresh()`, again freezing `ui-router`. 

While `$translate` will use one of known

**Comment by knalli** [comment]
Right, a catch case is missing here.

**Comment by DWand** [comment]
There was an event emitting in the old version of the code. Do we have to restore it as well?

**Comment by knalli** [comment]
Missing `reject`  applied in  5a85a64
