### ISSUE TITLE
Improve cross-browser testing by means of Saucelabs

### ISSUE THREAD

**Issue by evilaliv3** [angular-translate/angular-translate#1031]
While testing the integration with [GlobaLeaks](github.com/globaleaks/GlobaLeaks) i've found that angular-translate does not integrate any cross-browser compatibility testing on commit; 
This can be easily done by means of [Sauce](saucelabs.com) and  [karma-sauce-launcher](https://github.com/karma-runner/karma-sauce-launcher).

Here you can examples of an easy integration with Mocha: https://github.com/dchest/scrypt-async-js/pull/12

While here you can see the various results:
- Saucelabs output: https://saucelabs.com/u/globaleaks
- An example of Readme.md exposing all the results of coverage and cross-compatibility testing: https://github.com/globaleaks/GlobaLeaks/tree/devel

**Comment by knalli** [comment]
Hi, thanks for the advice, like this.   The new possibilities using Sauce (open source projects) are very cool. And it is on the loooong list of my todos :(

Anyone who is willing to help is welcome.
