### ISSUE TITLE
Demo Examples Outdated?

### ISSUE THREAD

**Issue by chakkimatti** [angular-translate/angular-translate#1033]
I git cloned the repo and linked to src/translate.js. After getting unknow porvider $translateProvider, I started looking at examples in the demo folder and they seem to link to dist folder . 'src' renamed? Should I be linking to some other translate.js file?

**Comment by knalli** [comment]
Demo is used to be working in the stable release which contains the folder `dist/`. That one is created by using `grunt build`.
