### ISSUE TITLE
Executing JS code in a translate directive

### ISSUE THREAD

**Issue by greckin** [angular-translate/angular-translate#1036]
Hi,

I wanted to implement a generic page that displays different errors depending on passed parameter (error code). Original example was using ui-router to extract part of url and then used one of defined translations corresponding to a different error codes.

So, error screen used last part of url e.g. for `somepage.com/#/error/500` it was extracting `500` and then it used it to build a translation key. In this example it would be something like `error.500`. Then this key was added to $scope and used in template as follows:
`<h1 translate>{{ errorKey }}</h1>`

However, using this approach I was able to open following url: `somepage.com/#/error/x%22%3E%3CIMG%20SRC=x%20onerror=alert(document.location)%3E`
and execute JavaScript code.

When I changed my template to:
`<h1>{{ errorKey }}</h1>`
it would not execute JavaScript code at all but simply displayed a string.

So only when using an expression then passing result of expression to a translation I was able to execute injected JS code. So my assumptions is that it is something that angular-translate does. Maybe that is a risky design and it could be prevented by having parameter that matches certain regexp etc. but still I expected translation to fail because it was not able to find mentioned translation not execute a translation key :)

Currently, my solution uses $translate in a controller and attach to $scope already translated message.

     $translate(messageCode).then(function(message) {
	   $scope.errorMessage = message;
     });

In this case my assumption is correct. For a risky URL $translate rejects a promise because it cannot find a matching translation key and no JavaScript code is executed. I believe that directive should behave the same?

Please find plunker below with a simplified example: 
http://plnkr.co/edit/Y7wHURcq1yGP6oIDzYHV?p=preview
It should execute console.log and display location service on a console.

**Comment by knalli** [comment]
Ehm, seriously: http://www.addletters.com/pictures/bart-simpson-generator/bart-simpson-generator.php?line=I+will+not+execute+JavaScript+code+by+external+parameter :)

You can try to use a (custom) sanitization strategy (see [here](https://github.com/angular-translate/angular-translate/blob/4615363502b9c3a6331ddc23a59288cee685f7ee/src/service/sanitization.js#L93)).. but please, do not use such unsure ways. Just don't.

**Comment by greckin** [comment]
Somehow I missed the obvious fact that it has to be applied as HTML. Mea culpa, I do not know what I was thinking.

Anyway, could you explain why a key that is missing is still applied? Is it for any other reason than to be clearly visible for user that translation is missing?
When I was inspecting code I have noticed "translate-default" attribute for translate directive. Now I wonder would it be beneficial to allow  setting a global "translate-default" using $translateProvider? This would allow to have some custom message in case of missing translation or even could be useful for automation tests that could try to locate that particular text on a screen?

**Comment by tspaeth** [comment]
@greckin you're looking for error handling I would say:

http://angular-translate.github.io/docs/#/guide/16_error-handling

or customized
http://angular-translate.github.io/docs/#/guide/17_custom-error-handler

**Comment by greckin** [comment]
Perfect, you guys thought of everything. Cheers
