### ISSUE TITLE
$injector.has is not a function

### ISSUE THREAD

**Issue by chakkimatti** [angular-translate/angular-translate#1037]
I have downloaded version v2.7.0 and did bower install
I have it linked on my index.html like so:
		`<script src="pkg/angular/js/angular.js"></script>`
		`<script src="pkg/app/js/app.js"></script>`
		`<script src="pkg/app/js/services.js"></script>`
		`<script src="pkg/app/js/filters.js"></script>`
		`<script src="pkg/app/js/directives.js"></script>`
		`<script src="pkg/app/js/controllers.js"></script>`
		`<script src="pkg/angular-translate/angular-translate.js"></script>`
		`<script src="pkg/angular-phrase/angular-phrase.js"></script>`
and on my app.js like so:
        `angular.module('App', ['pascalprecht.translate','LocalStorageModule']).`
	`config(['$locationProvider', function($location) {`
		`$location.hashPrefix('!');`
	`}])`
	`.config(['$translateProvider', function ($translateProvider) {`
		`$translateProvider.translations('en', {'message' : 'hello'});`
	`}]);`

I get error $injector.has is not a function
if ($injector.has('$Sanitize')) line 229 angular-translate.js

I've tried linking to cdnjs also but the same.

**Comment by tspaeth** [comment]
Which version of Angular are you using?

**Comment by chakkimatti** [comment]
Angular v1.1.4

**Comment by tspaeth** [comment]
You should definitely upgrade... $injector.has was introduced in 1.1.5 and 1.1.4 is more than slightly deprecated :-)

**Comment by chakkimatti** [comment]
Thanks.. A mans gota do whata mans gota do.
