### ISSUE TITLE
Not able to change language at runtime for a custom directive with attributes

### ISSUE THREAD

**Issue by dreamweaver1231** [angular-translate/angular-translate#1039]
Hi i have a custom directive as shown below
<header-nav heading="{{'HEADING' | translate}}" link-heading="{{'LINK_HEADING' | translate}}" link="#"></header-nav>
but when i am switching language the string does not change to the new language and still shows the strings from preferred language.

**Comment by dreamweaver1231** [comment]
Hi,

Found the issue..
Was using one way binding in the directive template hence it was not getting updated on language change

**Comment by hendricius** [comment]
Could you elaborate a bit more on how you were able to fix this? Did you pass the translations directly to the directive?
