### ISSUE TITLE
Date translate

### ISSUE THREAD

**Issue by furyscript** [angular-translate/angular-translate#1040]
I need to translate
```
dateFilter(new Date(), "EEEE");
```
How can I make them??

**Comment by tspaeth** [comment]
Please have a look at https://docs.angularjs.org/api/ng/filter/date and https://code.angularjs.org/1.3.15/docs/guide/i18n first since date parsing is more localization and not translation.

**Comment by furyscript** [comment]
Yes but there isn't translate of date @tspaeth

**Comment by knalli** [comment]
@furyscript Of course, that's part of AngularJS' _ngLocale_. And again: localization/formatting is not part of translation.

**Comment by furyscript** [comment]
I use angular-i18n for translate date, but a lot of translation don't have the capital letter, and I use bower to install.

Also I need to load dinamicly change language and with Grunt file is not possible, because you must preload the JS file. I think that this function can help in angular-translate...

**Comment by tspaeth** [comment]
@furyscript Sorry, I don't understand what you meant with your last comment.

**Comment by furyscript** [comment]
up

**Comment by knalli** [comment]
@furyscript You do not have to push this thread until you can give us more details about your issues. Just as @tspaeth  said: We do not understand this with given information.

**Comment by furyscript** [comment]
I update the comment see now.

**Comment by tspaeth** [comment]
Which comment, @furyscript? I can't remember how it looked before... sorry :-)

**Comment by furyscript** [comment]
Now I'm using "angular-i18n" translator for the dates, and I use bower to install it.
https://github.com/angular/bower-angular-i18n

I need that the users can change that language in application, but with this translator can not because it is loaded with Grunt so I must preload the JS file.

There is a function that translates dates according to local?? @tspaeth

**Comment by tspaeth** [comment]
Not in angular-translate. It's still localization and not part of this project here.

**Comment by furyscript** [comment]
Ok! I think you close. Maybe you know how to set dynamic localization?

**Comment by tspaeth** [comment]
Well, just googled around... find an approach like mentioned here 
http://blog.novanet.no/creating-multilingual-support-using-angularjs/

or here... 

http://www.mattzabriskie.com/blog/i18n-with-angular
