### ISSUE TITLE
Make $STORAGE_KEY constant configurable

### ISSUE THREAD

**Issue by pmoelgaard** [angular-translate/angular-translate#1042]
It would be convenient to be able to add a pre-fix to isolate namespaces or perhaps just even customise for the sake of aligning naming of resources with existing guidelines, or basically just be able to decide what variable name should be used to save to the localStorage.

Specifically this line here (line 2377):
```javascript
angular.module('pascalprecht.translate').constant('$STORAGE_KEY', 'NG_TRANSLATE_LANG_KEY');
```

**Comment by DWand** [comment]
@pmoelgaard, use can change a storage key by calling `$translateProvider.storageKey` and `$translateProvider.storagePrefix` methods.

**Comment by pmoelgaard** [comment]
So I can, excellent, thanks, couldn't find it mentioned in the document, but see it now in the code !
