### ISSUE TITLE
A way to get translation table in run block

### ISSUE THREAD

**Issue by Guria** [angular-translate/angular-translate#1046]
I need a way to get in `.run` block:
- all translations for current language as object
- the same but also with keys from fallback language(s)
- scoped ('NAMESPACE') translations for current language as object
- the same but also with keys from fallback language(s)

Couldn't find way to do any of this in documentation.

**Comment by knalli** [comment]
In the `run` phase, you will have the ability to inject the `$translate` service just like in other services incl. directives, filters and controllers. Said that, you will obviously handle this asynchronously as the translation module have to load all required languages.

In a nutshell: Use the service. Does that help you?

**Comment by Guria** [comment]
I want to get all available translation keys for language or for just one namespace. With $translate service  I have to provide certain translation keys only.

**Comment by knalli** [comment]
-> 40f9e35
