### ISSUE TITLE
what happened to $translate.uses() ??

### ISSUE THREAD

**Issue by mikila85** [angular-translate/angular-translate#1047]
in wiki page:
https://github.com/angular-translate/angular-translate/wiki/Asynchronous-loading
your example:
http://plnkr.co/edit/Hw4iMz?p=preview

shows that it is possible to: "To lazy load another translation file at runtime, simply invoke $translate.uses() with a specific language key."

The example is not working and i cant get it to work on my code either :(

how then can i lazy load more languages?

please help.

**Comment by knalli** [comment]
Short: It's `$translate.use()`.

Long: Please do not use the wiki, but https://angular-translate.github.com

Thank you.

**Comment by mikila85** [comment]
$translate.use()
changes the language being viewed!
i want to "pre-download" another .json language.

**Comment by mikila85** [comment]
works thx :)

**Comment by mikila85** [comment]
can see in:

https://angular-translate.github.io/docs/#/api/pascalprecht.translate.$translate

that you gave me to use says:
"""
Tells angular-translate which language to use by given language key. This method is used to change language at runtime. It also takes care of storing the language key in a configured store to let your app remember the choosed language.

When trying to 'use' a language which isn't available it tries to load it asynchronously with registered loaders."""

**Comment by mikila85** [comment]
@knalli please help

**Comment by knalli** [comment]
> @knalli please help

Come on. You are waiting for 12 hours only (for me night) and already trying to bug is? Really?

What do you want actually?

In your first post you requested using `uses()`, but that has been renamed long time ago into `use()`. Sorry about the wrong documentations which are still available and are messing up the Google index. We have to clean this.

As the documentation already described, `use()` will switch (and implicitly load) a language's translations. Nothing else.

There is and was never a preload mechanism in our feature set. However, you can archive something similar with the concept of "fallback languages".

Alternatively, you can write your own custom loader implementation which can do all this fancy stuff like preloading.

**Comment by mikila85** [comment]
I'm sorry didnt mean to nagg i just was not sure if you can see my note after you closed the ticket so i memo'ed ur name.

my problem was with $translate.instant, not being able to get the new language after use is fired untill the json is downloaded.

i solved it by waiting for the broadcase of
$translateChangeSuccess
and then doing my logic.

thanks :)

**Comment by mikila85** [comment]
btw did you ever encounter a problem when changing language then refreshing the page the angular starts twice (reaches after app.run().. refresh page by it self and run angular again) ?
or should i investigated more in my code?

only does that when changing language, if default is not changed everything works great.

**Comment by tspaeth** [comment]
What does "run angular again/twice" mean in detail? Is your app.run - block executed twice? 

But this totally looks more like an application design problem than an angular-translate module problem.

**Comment by knalli** [comment]
In the world of (browser's) javascript and data, almost everything is more or less asynchronous except locally available in memory. `$translate.instant()` cannot be used in `run()` (or any other component's construction phase) because no translations would be available. Said this, we highly recommend to use the standard async service `$translate()` and control an visual interface for waiting/initializing. Alternatively, register an internal default language.

**Comment by mikila85** [comment]
might be, i checked your simple demo files and it does not do this behavior.
not only that the app.run - block executed twice, the whole page refreshes and reloads everything.
this happens ONLY if i change the language.

steps (working well):
1. load app
2. refresh page
3. app loads

steps: (problem)
1. load app
2. change language (with $translate.use and useStaticFilesLoader)
2. refresh page
3. app half loads -> page refresh mid load (as if i pressed refresh again) -> app loads again completely

**Comment by tspaeth** [comment]
I'm just a little bit unsure still... what do you mean by refresh page "manually"?

**Comment by mikila85** [comment]
press F5 ..

just realized this only happends when "Cache killer"(chrome extention) is enabled.
still strange why it reacts to angular-translate like this but i can live with that.
