### ISSUE TITLE
Remove all deprecated wiki pages (excluding chore)

### ISSUE THREAD

**Issue by knalli** [angular-translate/angular-translate#1048]
@PascalPrecht @tspaeth  @DWand 

Anyone having a veto?

The Google index still refers to them. We can update each of them with a short notice, but they are actually out of date.

Latest problem in #1047

**Comment by tspaeth** [comment]
I'm fine with that. Actually thought that also several times...

**Comment by DWand** [comment]
It looks like it is better to have docs in one place.

**Comment by tspaeth** [comment]
So .... *pushing up*

**Comment by knalli** [comment]
Done.
