### ISSUE TITLE
Include src folder in npm distribution

### ISSUE THREAD

**Issue by jzorn** [angular-translate/angular-translate#1049]
I am using NPM to manage my front end dependencies as well. The excluded src folder stops me from using angular-translate as an npm dependency. Could you add the src folder?

**Comment by knalli** [comment]
We do not provide any support for bundling the files yourself.. right order and existence of specific files must be correct. This is planned for the next major release..

Why do you not use the dist files?

**Comment by jzorn** [comment]
Oh. I missed that. Never mind, thank you very much!

**Comment by knalli** [comment]
@jzorn  Does that mean the corresponding PR is obsolete now?

**Comment by jzorn** [comment]
Yeah, I forgot about that! Thanks, I closed it!

**Comment by knalli** [comment]
No problem, I wanted to be sure not ignoring relevant issues ;)
