### ISSUE TITLE
Merge sync and async translations

### ISSUE THREAD

**Issue by acourtiol** [angular-translate/angular-translate#1051]
Hello,

We use two different way to declare translations in our apps.
First, in the common components, we use $translateProvider.translation like this : 

```
component.config(function ($translateProvider) {
  $translateProvider.translations('en', {
    TITLE: 'Hello',
    FOO: 'This is a paragraph.',
  });
  $translateProvider.translations('de', {
    TITLE: 'Hallo',
    FOO: 'Dies ist ein Paragraph.',
  });
});
```

Second, in the application using the common components, we use the static file loader like this : 

```
application.config(function ($translateProvider) {
  $translateProvider.useStaticFilesLoader({
    prefix: 'locale-',
    suffix: '.json'
  });
});
```

The problem is that the static files are not loaded when the common components translations are present in the application.

Any ideas how to aggregate both sources of translations ?

Thanks for your help.

**Comment by knalli** [comment]
Short: Use fallbackLanguage or have a look at the partial loader.

**Comment by acourtiol** [comment]
Thanks for your answer. We already use fallbackLanguage (as our application is partially translated in 25+ languages we often fallback to english on missing translations) and partial loader don't answer our needs.

I checked angular-translate code and found the two culprits lines: 
- https://github.com/angular-translate/angular-translate/blob/master/src/service/translate.js#L1666
- https://github.com/angular-translate/angular-translate/blob/master/src/service/translate.js#L1964

If we already loaded translations using the `$translationProvider.translations` for a certain language key the async loader will not be called.

**Comment by knalli** [comment]
We have adjusted this due #981

**Comment by acourtiol** [comment]
I just linked a pull request, I will look at the #981 issue. Thanks for the help.

**Comment by acourtiol** [comment]
I just looked at the #981 issue. It's different to mine as he tried to load, through async loader, different languages that weren't already declared using `$translationProvider.translations`.

To detail a little more our situation, we want to use `$translationProvider.translations` to declare common translations to all our applications, and then complete them with specific application translations loaded through async static loader.

To give you an example extracted from one of our application, we declare in our core components: 

```
$translateProvider.translations('en', {
    feedback.hover.title: 'Give us your feedback'
    feedback.hover.text: 'Feedback'
});
```

And then, in our application, we try to load, using the async static file loader, the current locale-en.json which contains translations that needs to be merged with the already declared translations in our core components: 

```
{
  "error": "Error",
  "service.unavailable": "Service is temporary unavailable",
  "unauthorized": "You're no more authenticated and will be redirected to the login page",
  "demo.title": "Components",
  "success.label": "It is a success"
}
```

**Comment by DWand** [comment]
Hello, @acourtiol. Are you sure that partialLoader doesn't feet your needs? It looks like it does exactly what you want.

With the partial loader you can introduce 2 parts (for example). one part may be set manually (instead of $translateProvider.translation()) and the other part will be loaded from the server asynchronously (instead of the static files loader). The loader will merge these parts together on its own.

**Comment by knalli** [comment]
Solution picked as bdee77f, up coming 2.7.1
