### ISSUE TITLE
Not compatible with angular 1.4

### ISSUE THREAD

**Issue by atd** [angular-translate/angular-translate#1052]
angular-translate bower package is compatible with `angular#>=1.2.26 <=1.4`

I am using it with angular 1.4 and didn't notice any problems.

Is this a conservative setting, or there are real issues?

**Comment by knalli** [comment]
We do not know this. We cannot ship a compatibility spec without checking this. And AJS has been released yesterday...

**Comment by knalli** [comment]
To clarify: We have already have an active scope running all tests against an AJS 1.4 RC branch. But because AJS breaks things even in RCs... ;)

**Comment by atd** [comment]
@knalli thank you for your quick response!

Please, let me know if I can give a helping hand

**Comment by knalli** [comment]
If everything is working, we can extend the range with the next patch.

**Comment by knalli** [comment]
Released 2.7.1 which extends the valid range including 1.4 GA.
