### ISSUE TITLE
Async loading leads to wrong language

### ISSUE THREAD

**Issue by richtmat** [angular-translate/angular-translate#1055]
When running my page in a browser and logging in, the users preferred language is set with $translate.use(lang). But in many cases this does not work.

I'm configuring angular-translate like this:
```
$translateProvider.useStaticFilesLoader({
      prefix: '/api/test/',
      suffix: '.json'
    });

  $translateProvider.registerAvailableLanguageKeys(['en', 'de'], {
    'en_US': 'en',
    'en_UK': 'en',
    'de_DE': 'de',
    'de_CH': 'de'
    })
  .determinePreferredLanguage();
});
```

Now two files en.json and de.json are being loaded.

In an `angular.module('app').run` I have the users preferred language available and start a service which uses `$translate.use(usersLang)` to set the users preferred language:

```
angular.module('app').run(function(I18nService, $rootScope, $log) {

  $rootScope.$on('$translateChangeStart', function(data) {
    $log.info("$translateChangeStart: '" + angular.toJson(data) + "'");
  })
  $rootScope.$on('$translateChangeEnd', function(data) {
    $log.info("$translateChangeEnd: '" + angular.toJson(data) + "'");
  })

  I18nService.useUserLang();
});
```

In the I18nService I have:
```
$log.info("setting language to '" + langCode + "'");
$translate.use(langCode).then(function(params) {
  $log.info("$translate.use: '" + $translate.use() + "'");
  $log.info("success: '" + angular.toJson(params) + "'");
});
$log.info("$translate.use2: '" + $translate.use() + "'");
```

Now my OS and browser are set to locale EN and the user I'm logging in prefers DE.
That is the chrome output:
```
setting language to 'de'
angular.js:11598 $translateChangeStart: '{"name":"$translateChangeStart","targetScope":"$SCOPE","defaultPrevented":false,"currentScope":"$SCOPE"}'
angular.js:11598 $translate.use2: 'undefined'
angular.js:11598 $translateChangeEnd: '{"name":"$translateChangeEnd","targetScope":"$SCOPE","defaultPrevented":false,"currentScope":"$SCOPE"}'
angular.js:11598 $translate.use: 'de'
angular.js:11598 success '"de"'
angular.js:11598 $translateChangeEnd: '{"name":"$translateChangeEnd","targetScope":"$SCOPE","defaultPrevented":false,"currentScope":"$SCOPE"}'
```

The page is now displayed in english. This happens quite often but not all the time. If the page is in german, only one `$translateChangeEnd` is shown.

My guess is that $translateProvider gets the files and waits for all language promises to be resolved. In that time $translate.use(lang) is called and tries to use a language not loaded yet. The promises from the first calls resolve after $translate.use(lang) is resolved and the language from `determinePreferredLanguage` is used. Any ideas on that one?

**Comment by knalli** [comment]
I'm not sure what you want. In which situation what exactly is wrong?

**Comment by richtmat** [comment]
@knalli when the application starts up, the language files are loaded as expected. But if I use `$translate.use(lang)` to early (i.e. languages are not completely loaded), `$translate.use(lang)` is useless because finally, when the languages are loaded, the determined preferred language is used.

**Comment by knalli** [comment]
Hm, must be a special corner case. Because the situation you are describing should be covered by this [spec](https://github.com/angular-translate/angular-translate/blob/4615363502b9c3a6331ddc23a59288cee685f7ee/test/unit/service/translate.spec.js#L427-L518). The only difference I'm seeing is: booting phase vs. after-run phase...

**Comment by tandibar** [comment]
Hi, we got this behavior again. And as I understand your [spec](https://github.com/angular-translate/angular-translate/blob/4615363502b9c3a6331ddc23a59288cee685f7ee/test/unit/service/translate.spec.js#L427-L518) it is another case. Our case is:
while preferred language is still loading,
another language will be requested and
is returning **after** the preferred one
In this case the unprefered language will be used.

**Comment by tandibar** [comment]
To be precise we are configuring (`.config`) the `$translateProvider` with available languages (de and en) and prefered language (de) and then in a `.run` block we load the language from the local storage and try to use it via `$translate.use(loadedLang)`. If it is let's say 'de' we will sometimes get 'en' because 'en' was loaded slower.

**Comment by knalli** [comment]
I've added an additional test case. That is what you are talking about?

**Comment by tandibar** [comment]
Yes, i think that is our case. So did you fix anything to get your spec working or did it just work? I other words: did you find the reason why it did not work for us?

**Comment by knalli** [comment]
No, I had added a test case only. Perhaps you isolate your problem in a small demo. Either you find the issue yourself, or at least we are able to have a look.

**Comment by MGMsystems** [comment]
We have the same/similar issue.
We set a language via url but the preferred one is used.

Scenario:
We set preferred language 'en' in the app`.config`.
```
 $translateProvider.useSanitizeValueStrategy('sanitize');
 $translateProvider.useStaticFilesLoader({
            prefix: 'languages/',
            suffix: '.json'
        });
$translateProvider.preferredLanguage('en');
```

Another config sets the routing.
In that routing the resolve of the main state we do `$translate.use($stateParams.locale);`
Looks like this:
```
$stateProvider.state('main', {
            abstract: true,
            url: '/{locale}',
            templateUrl: 'main/main.html',
            controller: 'MainController',
            controllerAs: 'main',
            resolve: {
                setLanguage: ['$stateParams', '$translate', function($stateParams, $translate) {
                    $translate.use($stateParams.locale);
                }]
            }
        })
```

In this case we set /nl/ in the url
80% of the times we see that 'nl' is loaded correctly. In other cases 'en' is set as the language.
Even when the url is /nl/
On the network tracking we see a request for 'en.json' and 'nl.json'.
There we see that if nl.json is done loading before en.json the language is set in 'en'
But if nl.json is done loading after en.json it is correct and uses the url language.
You can clearly see this when you throttle the network.
![image](https://cloud.githubusercontent.com/assets/4438834/12613208/6864ab88-c4f8-11e5-85b9-90f73dec4f4c.png)



@knalli Hope this help clarify the issue and you can look into this.
@richtmat does this describe your issue as well?

**Comment by knalli** [comment]
The preferred language will be loaded as soon as possible (that's why it is loaded actually). The $state service will look at the url at a later point of time, which results automatically into an additional request.

**Comment by MGMsystems** [comment]
@knalli I understand, but sometimes the preferred language is used and not the later set language.
This because the preferred language json took longer to load.
I expect the url language to be used.

**Comment by neilyoung2013** [comment]
I am also having the same issue with this. In my configuration block I have:

`$translatePartialLoaderProvider.addPart('home');
    $translateProvider.preferredLanguage('gb');
    $translateProvider.fallbackLanguage('gb');
    $translateProvider.useSanitizeValueStrategy('escapeParameters');
    $translateProvider.useLoader('$translatePartialLoader', {
      urlTemplate: '/app/data/lang/{part}/{lang}.json'
    });`


I run the following code in my resolve functionality to refresh the locale translation:

`translate: ['$route', '$rootScope', '$translatePartialLoader', '$translate', '$q', '$timeout', function ($route, $rootScope, $translatePartialLoader, $translate, $q, $timeout) {
                if ( !$route.current.params.locale ){
                  var locale = 'gb';
                }
                else{
                  var locale = $route.current.params.locale;
                }

                var deffered = $q.defer();

                $rootScope.locale = locale; 

                console.log('Route resolve. Lang to use is: ' + locale);

                $translate.use( locale ).then(function(){
                  console.log('Route resolve. Lang is: ' + $translate.use());
                  deffered.resolve();
                });
                
                return $translate.refresh();
            }]`

When I load the first time using /gb the translation displays correctly. I then change to /es and it loads in spanish but when I revert back to /gb it still displays the spanish version and use still tries to load the spanish translation.

**Comment by tspaeth** [comment]
@neilyoung2013 / @richtmat Please check or stay tuned until next release. Perhaps #1419 is gonna fix this...

**Comment by tspaeth** [comment]
@MGMsystems / @neilyoung2013 please check if 2.10.0 fixes your issue(s).

**Comment by neilyoung2013** [comment]
This seems to work. Many thanks for your quick resolution.
