### ISSUE TITLE
select group by grouping-variable not translateable

### ISSUE THREAD

**Issue by geonom** [angular-translate/angular-translate#1058]
When using a dropdown select box using something like (abbreviated)
```
<select ng-options="category.id as (item.name | translate) group by item.group for item in item">
```
the items are correctly translated. However I am having a hard time translating the group names.

Created a jsbin to show the issue:
[http://jsbin.com/fesikibobu/1/] (http://jsbin.com/fesikibobu/1/)

Did not find anything relevant on the web yet, any solution would be appreciated :)

Best regards!

**Comment by knalli** [comment]
Well, the group by clause will not support an additional alias functionality you are requesting.

I would translate everything into the internal da structure. That could be done as a dedicated custom select directive: input is the translations and the directive itself can be refreshed watching for the translate change event.

**Comment by geonom** [comment]
Thanks a lot! Already good to know that it is not going to work that way :+1: 

Tried to change the internal data structure directly after each language change, but somehow only the first change works, any subsequent language change will not change the group translation anymore - updated the jsbin:
http://jsbin.com/cobeyucopo/4/edit?html,js,console,output

The same happens in my own application, so probably a case of me misunderstanding either javascript or angular - not an issue of angular-translate anymore :)

**Comment by knalli** [comment]
Here we go: http://jsbin.com/desogiquwi/1/

I'll close this in forward.

**Comment by geonom** [comment]
Thank you very much!
