### ISSUE TITLE
$translate.proposedLanguage() returns undefined

### ISSUE THREAD

**Issue by vmontane** [angular-translate/angular-translate#106]
I have an application that uses angular-translate, local storage, etc..
Everything works fine exept I can't get the currently used language in a var.
The method $translate.proposedLanguage() alwayes returns "undefined".

I'm using angular-translate v1.0.1 with angular v1.0.7
Here's my controller :

angular.module('App')
    .controller('MainCtrl', function ($scope, $http, $translate) {
        var lang = $translate.proposedLanguage();
        alert(lang);
      });

**Comment by laoyipay** [comment]
I had same problem, I solved it by using window.localStorage.getItem('NG_TRANSLATE_LANG_KEY') to get cached language directly from localStorage
