### ISSUE TITLE
Fallback isn't working

### ISSUE THREAD

**Issue by sigismondm** [angular-translate/angular-translate#1060]
I have the following code in my config and I set my browser's language to 'ro' . I expected it to use English instead but thats not the case. Am I missing something?

    $translateProvider.useUrlLoader('/locale/data?format=mf')
      .useCookieStorage()
      .registerAvailableLanguageKeys(['en'])
      .determinePreferredLanguage()
      .fallbackLanguage('en');

**Comment by knalli** [comment]
@sigismondm  Please provide a simple test case. Thank you.

**Comment by sigismondm** [comment]
In the snippet below I reach out to an endpoint that retrieves appropriate translation file. I ran an experiment by changing the language in the browser to see if it will fallback to english. 
````  
.config(['$translateProvider', function($translateProvider) {
    $translateProvider.useUrlLoader('/locale/data?format=mf')
      .useCookieStorage()
      .registerAvailableLanguageKeys(['en'])
      .determinePreferredLanguage()
      .fallbackLanguage('en');
  }])
````
In my controller I did a  ````console.log( $translate.proposedLanguage())```` and the output was the same as the language I set my browser to. I expected that it would've been english.

Am I doing something wrong or this is an issue? Thanks.

**Comment by knalli** [comment]
It would be nice if you make this as a runnable demo?  You can use http://plnkr.co/edit/LewAdjfYkzwpBBaG1xDz as a base..

**Comment by hartmannj** [comment]
The same happens in my project as well.

    $translateProvider
	.useSanitizeValueStrategy(null)
	.useStaticFilesLoader({
	    prefix: '/assets/landing/translations/locale-',
	    suffix: '.json'
	})
	.registerAvailableLanguageKeys(['en', 'zh-HK', 'zh-CN'], {
		'en*': 'en',
		'zh': 'zh-HK',
	    'zh-TW': 'zh-HK',
	    'zh-Hant': 'zh-HK',
	    'zh-Hans': 'zh-CN'
	})
	.fallbackLanguage('en')
	.determinePreferredLanguage()
	.useCookieStorage();

If I set my browser language to German, the script tries to download the German language file, fails and shows the placeholders instead of using 'en' as fallback.

Right now I fix the problem by putting following code snippet into the run method:

    if(['en', 'zh-HK', 'zh-CN'].indexOf($translate.use()) < 0) {
		$translate.use('en');
	}

**Comment by knalli** [comment]
Closed due inactivity. We still need a running demo.
