### ISSUE TITLE
Change to using $cookies

### ISSUE THREAD

**Issue by knalli** [angular-translate/angular-translate#1061]
Reference pr #1038

Perhaps we have to add a diagnostic adapter handling all supported AJS versions...

**Comment by mchambaud** [comment]
Hey @knalli, I need this feature done quickly. I could do it and send you a PR but it would be a breaking change prior to V3. 

Will you approve it, or should I just go custom for now?

**Comment by tspaeth** [comment]
Either we introduce a version switcher or just a second storage-cookie - adapter? How does this sound? Then it is not breaking but more feature toggle.

**Comment by mchambaud** [comment]
$translateProvider.useSuperCookieStorage()?

**Comment by tspaeth** [comment]
this.useNewCookieStorage .. ? sounds a bit better ;-)

**Comment by tspaeth** [comment]
But honestly - it might be the better approach to make it setter-based

```
this.useCookieStorage = function (storage) {
    if (storage) {
      ...
    } else {
      return this.useStorage('$translateCookieStorage');
    } 
  };

```

or so ...

**Comment by knalli** [comment]
As already mentioned: we can also go with a diagnostic multi adapter. It is possible to use $injector checking about the existence...

**Comment by tspaeth** [comment]
yup. I'm also fine with that. @mchambaud how about these approaches to hand in a PR? :smiley:

**Comment by mchambaud** [comment]
https://github.com/angular-translate/angular-translate/pull/1441

**Comment by mchambaud** [comment]
#1441

**Comment by mchambaud** [comment]
I just realized angular uses $cookies in the background if it's available. We can set cookie options using defaults.

**Comment by mchambaud** [comment]
👍
