### ISSUE TITLE
Slow when there is lot's of translations

### ISSUE THREAD

**Issue by seemsindie** [angular-translate/angular-translate#1062]
Hello,

I would like to ask you do you have any tips on improving performance when there is a huge amount of translations? We have more then 1100+ keys in each translation.

Thanks, Ivan.

**Comment by tspaeth** [comment]
Without further knowledge of your whole application, this is .. .erm... hard to answer without being totally unspecific...

**Comment by seemsindie** [comment]
What do you need to know, all i can tell you is i have a huge list of translations. And a lot's are displayed on the page of the app. When i open angular batarang i see a really big list of watchers that watch for translations that take a long time [Image](http://i.imgur.com/jbTuznL.png)

**Comment by RyanQuackenbush** [comment]
If you do not expect to change the language on the fly (possibly without app refresh), look into [one-time bindings](https://docs.angularjs.org/guide/expression) in the Angular docs (scroll down / find 'One-time'). Still will be slow the first time.

**Comment by seemsindie** [comment]
@RyanQuackenbush Thanks man.
