### ISSUE TITLE
Elegant way to sort ng-options by translation

### ISSUE THREAD

**Issue by sclausen** [angular-translate/angular-translate#1064]
I've got an array of strings which have to be the value of a select box. This values should be translated and ordered by this translation.

I've got a working example, http://jsfiddle.net/urk9nkog/ but is there a more elegant way to sort by the translated value, than making a function doing it?

**Comment by knalli** [comment]
@sclausen , could you please update your code using 

a) an appropriate current version of AngluarJS (that's 1.0?)
b) an appropriate current version angular-translate (looks to be very, very old)

.. and than: again: what is the problem with the filter or the directive?

**Comment by sclausen** [comment]
Sorry, I already made an appropriate version, but lost the version number while pasting the fiddle :-[ Sorry!
It's here: http://jsfiddle.net/urk9nkog/2/ 

The Problem with the filter or the directive is as I asked: Is there a more elegant way than coding my own filter to sort by translation?

**Comment by knalli** [comment]
That is at least not relevant to translate.

Well, I would not change the values (and translate) in the sorting filter.

What about this? http://jsfiddle.net/mut5yycn/1/

**Comment by ruw8279** [comment]
The easiest way is to apply the _translate_ filter inside the _order by_ filter:

```
    <select name="comboBox"
  ng-options="object.id as object.name | translate for object in ArrayOfObjects | orderBy:'name | translate'">
```
