### ISSUE TITLE
translate-attr-* doesn't work with tooltips

### ISSUE THREAD

**Issue by TheHacker66** [angular-translate/angular-translate#1066]
Hi, I was looking for a simple module that could handle tranlations in different languages easily, and found this one.

I have managed to translate the entire site in different languages except tooltips. They are plain html5 tooltips that use the title attribute as the tooltip text. When using the translate-attr-title attribute, it doesn't work, I don't see anything in the title attribute.

You can see the issue here:

http://myweblobby.tk/AngularTube/

Search for a video and click on it. The views, likes and dislikes icons should show a tooltip. The text in the title attribute is there, but it is certainly set after angular bootstrap ui kicks in.

Change to comments tab and scroll down. The scroll to top button should have a tooltip too.

If i use the filter method it only works for the first (default) language, it doesn't change.

**Comment by knalli** [comment]
@TheHacker66 .. it looks like it is working everything? Where is the problem?

Sidenote: I'm seeing several permanent flashes in text areas in your application. That does not look fine... ![](http://g.recordit.co/gw9b8OGgzO.gif)

**Comment by TheHacker66** [comment]
It should look like this (the one you see is the browser's tooltip, not the bootstrap one).

![tooltip](https://cloud.githubusercontent.com/assets/641140/8007021/ffe662b8-0b98-11e5-9a27-ccc1c247453a.png)

That behaviour is indeed wrong. I was using marquee tags and forgot to remove them. Now titles and authors should scroll on hover only.

**Comment by knalli** [comment]
Ah, missed that one.

Well, that's a limitation by bootstrap which does not look for changes in the attribute (regardless by translate or you). You can try to use a filter explicitly (`<span title="{{'key' | translate}}">XYZ</span>`). Otherwise you have to wrap or enrich the directive in question (in that case the bootstrap titler).

**Comment by TheHacker66** [comment]
If i use the filter method it only works for the first (default) language, it doesn't change when i switch languages (you can try yourself, I have reverted changes).

I will look into the bootstrap directive, thanks.

**Comment by joris-lambrechts** [comment]
I can confirm that using Angular UI Bootstrap it is possible to do so as @knalli described: 

```
<div tooltip="{{'KEY' | translate}}">Hover for tooltip</div>
```

PS: Why are you using both Angular UI Bootstrap and the default Bootstrap + jQuery? I think it's better to use just one (preferably the Angular version)
