### ISSUE TITLE
interpolation-messageformat depends on global MessageFormat

### ISSUE THREAD

**Issue by kentcdodds** [angular-translate/angular-translate#1068]
Even though the module is exposed using UMD (yay) it is actually using the global `MessageFormat` object [here](https://github.com/angular-translate/angular-translate/blob/master/src/service/messageformat-interpolation.js#L38). This is forcing me to either expose `MessageFormat` onto `window` (which I would prefer not to do), or make a workaround with webpack (which is also cumbersome). The real solution is to use UMD correctly and not depend on globals but rather require things correctly.

Here's what the UMD format looks like now:

```javascript
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module unless amdModuleId is set
    define([], function () {
      return (factory());
    });
  } else if (typeof exports === 'object') {
    // Node. Does not work with strict CommonJS, but
    // only CommonJS-like environments that support module.exports,
    // like Node.
    module.exports = factory();
  } else {
    factory();
  }
}(this, function () {

// interpolation-messageformat code that uses the global MessageFormat variable

}));
```

Here's what it should look like:

```javascript
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module unless amdModuleId is set
    define(['messageformat'], function (MessageFormat) { // <-- changed line
      return (factory(MessageFormat)); // <-- changed line
    });
  } else if (typeof exports === 'object') {
    // Node. Does not work with strict CommonJS, but
    // only CommonJS-like environments that support module.exports,
    // like Node.
    module.exports = factory(require('messageformat')); // <-- changed line
  } else {
    factory(root.MessageFormat); // <-- changed line
  }
}(this, function (MessageFormat) { // <-- changed line

// interpolation-messageformat code that uses the global MessageFormat variable

}));
```

Thanks!

**Comment by knalli** [comment]
@kentcdodds Thanks for the hint. We accidentally didn't care about this.

Do we know that AMD and CJS modules' name would be `messageformat` and not `MessageFormat`?

**Comment by kentcdodds** [comment]
I know that for CommonJS it is `messageformat`, with AMD, I checked and it is not exposed with a name. So people would have to shim it themselves. You would essentially be deciding the shim for people, but that's better than not providing anything at all (like the current scenario). Thanks for being willing to fix this issue :-)

**Comment by knalli** [comment]
Okay, that will be the new one:
```js
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module unless amdModuleId is set
    define(["messageformat"], function (a0) {
      return (factory(a0));
    });
  } else if (typeof exports === 'object') {
    // Node. Does not work with strict CommonJS, but
    // only CommonJS-like environments that support module.exports,
    // like Node.
    module.exports = factory(require("messageformat"));
  } else {
    factory(MessageFormat);
  }
}(this, function (MessageFormat) {
```

**Comment by knalli** [comment]
Added in f5e039c - thank you.

**Comment by kentcdodds** [comment]
Thanks for your fast response and all of your work on this library :-)

**Comment by kentcdodds** [comment]
Do you mind letting me know when this gets released so I know when I can pull out my workaround? Thanks!

**Comment by PascalPrecht** [comment]
@kentcdodds I recommend following @knalli on twitter, I'm sure he'll send a tweet about it :)

**Comment by kentcdodds** [comment]
:+1:
