### ISSUE TITLE
Is there a way to use placeholders in a translation id?

### ISSUE THREAD

**Issue by pselden** [angular-translate/angular-translate#1069]
I'm using https://github.com/angular-translate/grunt-angular-translate to pull my translations out automatically so I can use it sort of like gettext. I'm trying to figure out how to use placeholders directly in my translation id so I can have the default text directly in my markup, but I'm having a bit of trouble.

```html
<span>{{ 'Showing {{pageStart}} - {{pageEnd}} of {{total}}' | translate:{ pageStart: vm.getPageStart(), pageEnd: vm.getPageEnd(), total: vm.getTotal() } }}</span>
```

Results in Error: [$parse:lexerr] Lexer Error: Unterminated quote at columns 0-20 ['Showing {{pageStart] in expression ['Showing {{pageStart].

When I pull the key into my controller

```html
<span>{{ vm.key | translate:{ pageStart: vm.getPageStart(), pageEnd: vm.getPageEnd(), total: vm.getTotal() } }}</span>
```

It just spits the key back out without interpolating.

Is it possible to use interpolated values like that as a key in my html like that?

**Comment by knalli** [comment]
Well, you are trying to use nested interpolations.. that is not possible. Only one pair of interpolation wrappers (`{{` and `}}`) are possible.

**Comment by pselden** [comment]
Is it that the angular interpolation conflicts with the translate interpolation? Would changing the interpolation markers fix things?

I also tried escaping the {{}} internally but that just spits out the key as well:

```html
<span>{{ 'Showing \{\{pageStart\}\} - \{\{pageEnd\}\} of \{\{total\}\}' | translate:{pageStart:vm.getPageStart(), pageEnd: vm.getPageEnd(), total: vm.getTotal()} }}</span>
```

Results in: Showing {{pageStart}} - {{pageEnd}} of {{total}}

**Comment by knalli** [comment]
That's AngularJS.. and the error is in the AJS expression parser code, not in angular-translate. You simply cannot do this. If you really want to re-parse and re-evaulate expressions, you have to create a directive which explicit takes care of that.

**Comment by knalli** [comment]
Additionally, there is no support for expression in keys. Everything is evaluated by the corresponding parser in the element scope of question.

**Comment by pselden** [comment]
Thank you for the help, I'll explore alternatives.

I really didn't want "expressions" in my keys, just placeholders that could be pulled out and used by the angular-translate formatter.

I was hoping that 'Showing {{ pageStart}}' could be used in my html and be used as if it were were the translation id directly -- same as if using "Showing {{ pageStart }}": "Showing {{ pageStart }}" in my translations file.

Potentially if there was a way to set the intepolation markers of the angular-translate interpolaters to something else so I could use: "Showing {pageStart}" instead, but alas.
