### ISSUE TITLE
Dynamic translation value {{value}} don't work

### ISSUE THREAD

**Issue by m-assaf** [angular-translate/angular-translate#1071]
Hello everybody,
I use angular-translate module Pascal Precht v. 2.7.2. I need to use dynamic value inside my JSON files like this:
This is one of my partial JSON files:
{
    " settings " :{
             "WITH_VALUES": "The following value is dynamic: {{value}}"
      }
}
But this don't work.
Does dynamic value must work as default in angular-translate ? or we need to add some plugin or some configurations?
Any helps will be appreciated.

**Comment by tspaeth** [comment]
How do you call the translation module? Service? Directive? Filter? And how do you set in the corresponding value?

**Comment by m-assaf** [comment]
I call it from my config.js file like this:
 function configLang($translateProvider, $translatePartialLoaderProvider, moment) {       
        $translateProvider.useLoader('$translatePartialLoader', {    
            urlTemplate: 'app/{part}/lang/{part}.lang.{lang}.json'
        });
    $translatePartialLoaderProvider.addPart('settings');
    $translateProvider.useMessageFormatInterpolation();
    $translateProvider.preferredLanguage('en');
}

In my core.module.js file i do the following:
(function () {
    'use strict';
    angular.module('app.core', [
        'ngAnimate', 'ngSanitize',
        'blocks.exception', 'blocks.logger', 'blocks.router',
        'ui.router', 'ngplus',
        'mm.foundation',
        'pascalprecht.translate',
        'angular-data.DSCacheFactory'
    ]);
})();

In my controller i do:
(function() {
    'use strict';
    angular
        .module('app.settings')
        .controller('UserController', UserController);
    UserController.$inject = ['$translate', '$filter', '$scope', 'DSCacheFactory', 'authenticationservice', 'user', '$q',
        'dataservice.companies'];

    function UserController($translate, $filter, $scope, DSCacheFactory, auth, user, $q, companies) {
    //Here is my content
       $scope.translationId = 'TRANSLATION_ID';
        $scope.values = {
            value: 78
        };
}})();

In my JSON file i have :
{
 "settings": {
        "TRANSLATION_ID": "Hello there!",
        "WITH_VALUES": "The following value is dynamic: {{value}}"
}}

In my view i have:
<pre>{{ 'settings.TRANSLATION_ID' | translate }}</pre>  => output: Hello there!
 <pre>{{ 'settings.translationId' | translate }}</pre>             => output: settings.translationId
 <pre>{{ 'settings.WITH_VALUES' | translate:{value: 5} }}</pre> => output: {{ 'settings.WITH_VALUES' | translate:{value: 5} }}
 <pre>{{ 'settings.WITH_VALUES' | translate:values }}</pre> => output: {{ 'settings.WITH_VALUES' | translate:values }}

**Comment by tspaeth** [comment]
Have you read http://angular-translate.github.io/docs/#/guide/06_variable-replacement ?

**Comment by tspaeth** [comment]
Based on knallis template, I have made some modifications that show the working filter with values:

http://plnkr.co/edit/Kw4xr7U4UuQ1OZ3KwVoj?p=preview

So your issue must be somewhere else in your configuration I guess.

**Comment by m-assaf** [comment]
The last 2 lines don't work for me:
<p translate="VARIABLE_REPLACEMENT" translate-values="{ name: 'PascalPrecht'}"></p>
<p translate="VARIABLE_REPLACEMENT" translate-value-name="PascalPrecht"></p>

**Comment by m-assaf** [comment]
<p translate="settings.VARIABLE_REPLACEMENT" translate-values="{ name: 'PascalPrecht'}"></p>
 <p translate="settings.VARIABLE_REPLACEMENT" translate-value-name="PascalPrecht"></p>

**Comment by m-assaf** [comment]
Here my console log, he don't like the face that we have {{}} inside my JSON file:
![console_error](https://cloud.githubusercontent.com/assets/7976588/8060999/aa9c0136-0ec8-11e5-8490-8e529637fcc6.jpg)

**Comment by tspaeth** [comment]
Probably 'value' is not a good key?

See here  - ingeneral it works after renaming it:

http://plnkr.co/edit/rFyd4z4sA3jXAzLFMkz5?p=preview

**Comment by m-assaf** [comment]
I have always the same error (angular dont like my brackets inside the JSON):
![1](https://cloud.githubusercontent.com/assets/7976588/8062221/dd1945d2-0ece-11e5-9dbd-95213dea6659.png)

**Comment by tspaeth** [comment]
Could you upload / configure it in the plunkr I've provided?
Maybe also your file encoding is wrong, or you're mixing " and ' ... so many options :)

**Comment by m-assaf** [comment]
Ok, i never use Plunker, i will try to upload exactly the same files and tell you when i finish it. 
Thank you @tspaeth.

**Comment by knalli** [comment]
Closing due inactivity.
