### ISSUE TITLE
Common sense available language keys

### ISSUE THREAD

**Issue by atd** [angular-translate/angular-translate#1072]
I find registerAvailableLanguageKeys too laborious. I just want that every `es_*` key (`es_ES`, `es_MX`, `es_AR` and whatever `es_FOO` is out there) just uses `es`.

I couldn't found anything in doc. Is there any way to do this?

**Comment by tspaeth** [comment]
Should work - see https://github.com/angular-translate/angular-translate/issues/932

I guess it's still missing in the docs - unfortunately. 
Please check if it works and close the ticket afterwards. thanks.

**Comment by atd** [comment]
Perfect! 

I'll send a pull request for the docs

**Comment by atd** [comment]
https://github.com/angular-translate/docs/pull/4
