### ISSUE TITLE
Unknown provider: $translateCookieStorageProvider

### ISSUE THREAD

**Issue by sochka** [angular-translate/angular-translate#1073]
Hi, I'm trying to use session storage as described in the docs but get this error:

```
Uncaught Error: [$injector:unpr] Unknown provider: $translateCookieStorageProvider <- $translateCookieStorage <- $translateLocalStorage <- $translate
```

I included ngCookies module as docs ask to.

Any ideas?

**Comment by tspaeth** [comment]
Maybe this helps:

https://github.com/angular-translate/angular-translate/issues/951

**Comment by sochka** [comment]
Thanks, that helped.
