### ISSUE TITLE
Is there any to update locale without executing translate

### ISSUE THREAD

**Issue by ChrisFan** [angular-translate/angular-translate#1074]
1. I have a language select directive on the page
2. I'd like select a language and refresh the page

Here is my code:
```javascript
  // app.config
  $translateProvider.useMissingTranslationHandlerLog();
  $translateProvider.useStaticFilesLoader({
      prefix: 'resources/locale-',                      // path to translations files
      suffix: '.json'                                   // suffix, currently- extension of the translations
  });

  $translateProvider.registerAvailableLanguageKeys(
      ['zh_CN', 'en_US'],
      {
          'en*': 'en_US',
          'zh*': 'zh_CN',
          '*'  : 'en_US'
      }
  );
  $translateProvider.fallbackLanguage('en_US');
  $translateProvider.determinePreferredLanguage();
  $translateProvider.useLocalStorage();

  tmhDynamicLocaleProvider.localeLocationPattern('bower_components/angular-i18n/angular-locale_{{locale}}.js');
```

```javascript
// on language selected
this.changeLanguage = function(locale) {
  ...
  $translate.use(locale).then(function() {
    // refresh current state(ui-router)
    $state.transitionTo($state.current, $stateParams, { reload: true });
  })
}
```

* What happens is all the text get translated first and then the page get refreshed. This is not good for user experience.
* Since `$state.transitionTo` doesn't reboot the angular app, I can't just update the 'storage' and do the transition

> btw, I'd like to reload the page because I have to fetch all the data from backend by language

Any ideas for this?

Thanks a lot.

**Comment by tspaeth** [comment]
But that is exactly what you coded so far. You first change the locale texts and then go for a transition to the next (same) state with forced reload.

**Comment by ChrisFan** [comment]
Well, as you mentioned, yes, in my code I first change the locale texts and then go for a transition...
That's just because I didn't find a better solution.

I'm wondering if there's something like this.
```
this.changeLanguage = function(locale) {
  ...
  $translate.set(locale); // something like this, only set locale, and it would take effect after the transition
  $state.transitionTo($state.current, $stateParams, { reload: true });
}
```

I'd tried to update the localStorge, but it only work after I refresh the page.
