### ISSUE TITLE
fallbackLanguage() invocation changes breaks useLocalStorage

### ISSUE THREAD

**Issue by sochka** [angular-translate/angular-translate#1075]
Hi, I've got a problem (or maybe this is a bug). The config is the following:

```
  $translateProvider
    .useSanitizeValueStrategy('escape')
    .registerAvailableLanguageKeys(['en', 'uk'], {
      'en*': 'en',
      'uk*': 'uk'
    })
    .useStaticFilesLoader({
      prefix: '/translations/',
      suffix: '.json'
    })
    .determinePreferredLanguage()
    .useLocalStorage()
    .fallbackLanguage(['en', 'uk']);
```

Steps:
1. Load this page - english is correctly detected as my preferred language.
2. Run `$translateProvider.use('uk')`. Interface, as expected, switched to ukrainian. In local storage I see `NG_TRANSLATE_LANG_KEY` set to be `uk`.
3. Bug here: when I hit F5 the page is reloaded but interface is shown in english. 

Any ideas?

**Comment by tspaeth** [comment]
Yes, when you make browser based detection with preferredLanguage, it has a higher priority than the stored one in local storage currently.

**Comment by sochka** [comment]
Ok, but how do I make the following:

1) first time user goes to the website systems uses `determinePreferredLanguage`
2) After this point it remembers the last used language, even if it was changed manually?

**Comment by sochka** [comment]
And how this example works then? http://angular-translate.github.io/docs/#/guide/10_storages  If preferredLanguage has higher priority than language in storage, why after hitting f5 my language is saved?

**Comment by sochka** [comment]
I think I found the problem. Almost sure this is a bug.

I have 'uk' language saved in my local storage. If I run app with this code ukrainian is used.
```
  $translateProvider
    .useSanitizeValueStrategy('escape')
    .registerAvailableLanguageKeys(['en', 'uk'], {
      'en*': 'en',
      'uk*': 'uk'
    })
    .useStaticFilesLoader({
      prefix: '/translations/',
      suffix: '.json'
    })
    .determinePreferredLanguage()
    .useLocalStorage();
```

If I add `fallbackLanguage` like in the original code:
```
  $translateProvider
    .useSanitizeValueStrategy('escape')
    .registerAvailableLanguageKeys(['en', 'uk'], {
      'en*': 'en',
      'uk*': 'uk'
    })
    .useStaticFilesLoader({
      prefix: '/translations/',
      suffix: '.json'
    })
    .determinePreferredLanguage()
    .useLocalStorage()
    .fallbackLanguage(['en', 'uk']);
```

And run the app - english is used. Why fallbackLanguage should have influence on that?

Any ideas?

**Comment by tspaeth** [comment]
What is your browsers primary language? UK?

**Comment by sochka** [comment]
en_US.

**Comment by sochka** [comment]
As a temporary solution I'm doing something like that:
app.config(($translateProvider) =>
  $translateProvider
    .useSanitizeValueStrategy('escape')
    .registerAvailableLanguageKeys(['en', 'uk'], {
      'en*': 'en',
      'uk*': 'uk'
    })
    .useStaticFilesLoader({
      prefix: '/translations/',
      suffix: '.json'
    })
    .determinePreferredLanguage()
    .useLocalStorage()
).run(($translate) => 
  $translate.fallbackLanguage(['en', 'uk'])
);

This - works. (just by moving fallbackLanguage invocation from `$translateProvider` in config phase to `$translate` in run phase.

**Comment by senthilakr88** [comment]
is determinePreferredLanguage() works for Internet Explorer?  for me its not working in IE. It works fine in firefox and chrome. did anybody else had the same issue?

**Comment by knalli** [comment]
@senthilakr88 see #1094

**Comment by knalli** [comment]
@sochka I've made a demo here: http://plnkr.co/edit/tQJOfMR1LmljfmTi6s2c?p=preview (standalone http://embed.plnkr.co/tQJOfMR1LmljfmTi6s2c/preview).

What's wrong?

**Comment by sochka** [comment]
I can't repro this on your plunkr but don't have time to test it on my code now. Will write a comment here if  I have this issue again (currently I'm using some workaround).

**Comment by sochka** [comment]
Hi @knalli , I just came back to this issue. Here is a demo: http://wdc-app-develop.herokuapp.com/ . If you click ukrainian - it won't change the language but after hitting F5 - the language finally changes. All the relevant setup code is here: https://github.com/kpi-wdc/wdc/blob/master/assets/js/i18n.js , in other files there is only asage of $translate service, filter and directives. Could you have a look at this please? This is really annoying that I can't find a problem, I even tried debugging your code a bit -- no luck.

**Comment by sochka** [comment]
Or maybe other project contributors (@DWand ?) have some idea what's going on?

**Comment by sochka** [comment]
Oh, I just noticed something really interesting. Replacing `$translate.use(...)` with `$translate.use(...); $translate.refresh()` fixes the problem, at least in cases I tested. Are you supposed to manually call refresh?

**Comment by DWand** [comment]
Hi, @sochka. Unfortunately, I'm busy at the moment and cannot suggest anything. Probably, I'll have some spare time to look at this issue in a couple of weeks.

**Comment by tspaeth** [comment]
Hm. Did you try (not the cleanest way, I know) using something like this (blind guess without code test) in the config section additionally at the end:

```
$translateProvider.use($translateProvider.preferredLanguage());
```

**Comment by sochka** [comment]
@tspaeth , No, I tried and it doesn't matter. The problem happens when changing the language, not when setting up the configs.

**Comment by knalli** [comment]
Getting this fixed we have to tackle down the bug correctly. We must know the differences between my plnkr and your app.

**Comment by knalli** [comment]
Any updates here?

**Comment by tspaeth** [comment]
Maybe #1433 helps also here? *blind-guess* Could somebody check? @sochka ?

**Comment by joshvito** [comment]
I cannot get .useLocalStorage to work as described in the documentation.

The application loads with the English translation files as expected. I can interact with the page to switch the language as expected. THe last selected language key is stored in local storage in my browser as expected.

However, when I refresh the page, it always loads in English. This happens even when the language key is set to another such as 'ja';

Please advise, it seems I am missing something or my configuration is set incorrectly.

```
var app = angular.module('ybWeb', ['ngRoute', 'ngCookies', 'pascalprecht.translate']);

app.config(['$translateProvider', '$translatePartialLoaderProvider', '$locationProvider', function($translateProvider, $translatePartialLoaderProvider, $locationProvider) {
	//main app config
	$translateProvider.useSanitizeValueStrategy('escape');

	$translateProvider.preferredLanguage('en');
	$translateProvider.fallbackLanguage('en');
	$translateProvider.useLocalStorage();

	$translateProvider.useLoader('$translatePartialLoader', {
		urlTemplate: '/m/src/i18n/{part}.{lang}.json'
	});

	$locationProvider.html5Mode({
		enabled: true,
		requireBase: false
	});

}]);

app.controller('translateCtrl', ['$translate', '$scope', '$location', '$translatePartialLoader', 'getReturnDataSvc', function ($translate, $scope, $location, $translatePartialLoader, getReturnDataSvc) {

	$scope.languages = [
		{code:"en",
			name: "COMMON.LABEL.ENGLISH"},
		{code:"ja",
			name: "COMMON.LABEL.JAPANESE"}
	];
	console.log($translate.versionInfo()); //2.11.0
	console.log($translate.storage().get());//logs last selected language on refresh

	$scope.selectedLang = $scope.languages[0];

	$scope.changeLanguage = function (language) {
		$translate.use(language.code);
		$scope.refreshTranslation();
	};

	$scope.refreshTranslation = function(){
		$translate.refresh();
	};

	function getTranslationPath(locationPath){
		//ToDo: move to svc
		//generates a period separated path string for passing to $translationPartialLoaderProvider
		var path = locationPath.replace(/\//g, ".");
		var pathArr = path.split(".");
		var extension = pathArr.pop();
		var leading = pathArr.shift();
		return pathArr.join(".");
	}

	$translatePartialLoader.addPart(getTranslationPath($location.path()));

}]);

app.run(['$rootScope', '$translate', function ($rootScope, $translate) {
		$rootScope.$on('$translatePartialLoaderStructureChanged', function () {
			//this forces a translation refresh every time we change the object assigned to the $translatePartialLoader
			//we can use $translatePartialLoader.addPart(<partStr>) in our controllers and not have to manually call $translate.refresh()
			$translate.refresh();
		});
	}]
);
```

**Comment by sainath168** [comment]
Any update on this?

I faced some problem too. I made some temporary fix like this in the controller init function where it comes after login or when refresh/F5 did,

`var storageKey = $translate.use();
if (storageKey !== "en-US") {
       $translate.use(storedKey);
       $translate.refresh();
}
`

But why it is not considering language key "NG_TRANSLATE_LANG_KEY " that is stored in cookies by default. Reason for angular translate taking preferredLanguage with higher priority than on that is stored in cookies?

**Comment by knalli** [comment]
I think we have not a real progress because we still have no working demo showing the issue.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
