### ISSUE TITLE
Bug accentuation in "useSanitizeValueStrategy"

### ISSUE THREAD

**Issue by marlonmleite** [angular-translate/angular-translate#1081]
By enabling useSanitizeValueStrategy ('sanitize'), caused one accent mistake in my translations and styles as example does not work.

See: http://plnkr.co/edit/2MNtBKOkHeG5QJlDRdiJ?p=preview

This is my configuration error or a problem?

**Comment by nioe** [comment]
Same problem here...
When using the filter to translate values like ``{{ VALUE | translate }}`` and ``$translateProvider.useSanitizeValueStrategy('sanitize');`` the output result is for example ``&amp;`` instead of ``&``...

**Comment by knalli** [comment]
Hm.. can have a look later. Perhaps you can elaborate this a bit using AJS' `$sce` directly?

**Comment by nioe** [comment]
I investigated a bit on this issue... I don't think anymore that it is a problem with the filter.
If I use for example ``<p ng-bind-html="'TRANSLATION_KEY' | translate"></p>`` it works fine. On the other hand if I define a sanitized variable in my controller like ``$scope.sanitizedText = $sanitize('&');`` and bind it with a binding expression in my template like ``<p>Test {{ sanitizedText }}`` the output is ``Test &amp;`` as well...

The issue only appears if a binding expression (``{{ }}``) is used, not with a directive...

**Comment by marlonmleite** [comment]
Yes, it seems that the problem happens only with {{ 'ANY' | translate }}.

Plunk updated.

**Comment by nioe** [comment]
I created a very minimal example to reproduce the Issue with ``AngularJS 1.4.0`` and ``angular-translate 2.7.2``: https://jsfiddle.net/xzrbLrce/. Feel free to play arround with it.

**Comment by dweremeichik** [comment]
Per https://docs.angularjs.org/api/ngSanitize/service/$sanitize ng-bind automatically escapes.
Which is why we are seeing the following functionality break: 
```
<p>{{ 'TEST' | translate }}</p>
<p ng-bind="'TEST' | translate"></p>
```
A double sanitation is occurring. When you debug it in you browser, it appears fine at first, but if you "Edit as html" you find that what you are seeing is actually:
```
<p class="ng-binding">This is a test with &amp;lt; &amp;gt; &amp;amp; &amp;#228; &amp;#246; &amp;#252;</p>
```
Which means that it is taking the initial escape of 
```
&lt; &gt; &amp; &#228; &#246; &#252;
```
and escaping it again.

**Comment by parkmap** [comment]
Is it okay to use not "$translateProvider.useSanitizeValueStrategy('sanitize');";

if not use it alerts security message on the console.

**Comment by knalli** [comment]
Link to #1101

**Comment by samal84** [comment]
@dweremeichik I am not seeing any double escaping when inspecting OPs plunker.

**Comment by dweremeichik** [comment]
I saw it when using Google chrome. Pop open the developer console. Inspect
the html, then right click and edit as html, you should be able to see what
I am talking about.

**Comment by eggyknap** [comment]
One place the above workarounds don't work, at least as far as I can see, is in "placeholder" attributes in <input> elements -- and presumably anywhere else you need to set an attribute to a translated value, instead of setting an element's contents.

**Comment by tonystar** [comment]
+1

**Comment by jmcollin78** [comment]
+1 same pb for me.

**Comment by jmcollin78** [comment]
It seems that option "escapeParameters" resolve the case. It can be a valuable workaround.

**Comment by DaAwesomeP** [comment]
I have this problem too. @angular-translate How far off is this fix?

**Comment by knalli** [comment]
Duplicate #1101 -- see also solutions and workarounds.

**Comment by 99sono** [comment]
"If I use for example <p ng-bind-html="'TRANSLATION_KEY' | translate"></p> it works fine."

Good work around, thanks.

**Comment by rodneicouto** [comment]
My workaround was: 

`app.filter('cbTranslate', ['$translate', function($translate) {
        return function(input) {
             return $('<div/>').html($translate.instant(input)).text();
        }
    }]);`

After i use in html 

`{{'user.shared.search' | cbTranslate }}`

**Comment by ashraful-robin** [comment]
<span ng-bind-html="'TRANSLATION_KEY' | translate"</span>
It's working fine for me :smile:

**Comment by edenworky** [comment]
Is this nearing a fix?

**Comment by knalli** [comment]
=> See comment of 13.09. last year. => #1101 is showing the progress and the current problems. Ideas are welcome.
