### ISSUE TITLE
Support translation-ids as parameters for dynamic translation

### ISSUE THREAD

**Issue by AlexSchuetz** [angular-translate/angular-translate#1082]
It would be nice to have the possibility to use translation-ids as parameters for dynamic translations.

Example:

```javascript
TYPE_COMPLETED: 'All issues of type {{type}} are completed.',
TYPE_BUG: 'bug',
TYPE_FEATURE: 'feature',
...

$translate('TYPE_COMPLETED', {type: 'TYPE_BUG'}); // 'All issues of type bug are completed.'

**Comment by knalli** [comment]
Please have a look at the `translate` directive, especially the attribute `translate-compile`. This allows you using expressions (including filters) in the translation.
