### ISSUE TITLE
Translate not working with ngDialog

### ISSUE THREAD

**Issue by qazqwertish** [angular-translate/angular-translate#1083]
Hello,

I have an SPA with one controller. I show some PopUps with ngDialog and the translation did not work inside the PopUps.

They throw this error:
>Error: [$injector:unpr] http://errors.angularjs.org/1.3.16/$injector/unpr?p0=translationFilterProvider%20%3C-%20translationFilter

When the ngDialog is opened, it uses the same $scope as the main controller. Of course I have added all that I need to make it work (in fact, it is working in the SPA, It does not work only in the dialog).

>var mbApp = angular.module('controllers-module', ['ui.bootstrap', 'xeditable', 'ngDialog', 'pascalprecht.translate']);

>controllers.MainBoardController = function ($scope, mbFactory, $window, ngDialog, $translate) {...}

In the dialog I have: 
> {{ 'PHONE' | translation }}

And in the controller I have configured the translateProvider:
>$translateProvider.translations('en', translationLabels.en);
>$translateProvider.translations('es', translationLabels.es);
>$translateProvider.preferredLanguage('en');

And when I change the language I execute:
>$scope.PHONE = $translate.instant("PHONE");

Thank you in advance.

**Comment by tspaeth** [comment]
The filter is called "translate" and not "translation"!

See http://angular-translate.github.io/docs/#/guide/04_using-translate-filter

**Comment by qazqwertish** [comment]
I had translate on all the rest of the Application. My fault.

Thank you so much! Sometimes you are so focused that you don't see the obvious.
