### ISSUE TITLE
Using translation outside controller and not in directive

### ISSUE THREAD

**Issue by m-assaf** [angular-translate/angular-translate#1084]
Hello everybody,
In my project i have a module wich called 'settings', it's composed from settings.html, settings.module.js, settings.controllers.js and settings.route.js.
I need ti translate title inside my 'settings.route.js':
```
'use strict';
    angular
        .module('app.settings')
        .run(appRun);
ppRun.$inject = [ '$translate', 'routerHelper', 'logger', '$state'];

function appRun($translate, routerHelper, logger, $state) {
        routerHelper.configureStates(getStates());
    }
function getStates($translate) {
var translated_title = $translate('settings.TITLE');
return [
            {
                state: 'settings',
                config: {
                    url: '/settings',
                    templateUrl: 'app/settings/settings.html',
                    controller: 'SettingsController',
                    controllerAs: 'vm',
                    title: translated_title,
                    settings: {
                        nav: 5,
                        i18n: 'SETTINGS',
                        content: '<i class="fa fa-cogs"></i>'
                    }}} ]
}
```
But it not work i have the following errror:
Uncaught ReferenceError: $translate is not a function.

Do someone know what's the error ?
Thank you.

**Comment by knalli** [comment]
It's your JavaScript. ;)

Definition of `function getStates($translate)`, but invoking `getStates()`. 

That's the error message.

**Comment by knalli** [comment]
Ehm.. but `$translate('settings.TITLE')` won't work, it's a promise.

**Comment by m-assaf** [comment]
I have ID in my JSON language file, this ID is called TITLE, i try to retrieved with this:
var translated_title = $translate('settings.TITLE');

Now i pass my arguments as you said : getStates(translate), i dont have the error, but i can't retrive the value of my ID. Now in my console i have the following value [ retrived with console.log(translated_title); ] : Promise {$$state: Object}

**Comment by m-assaf** [comment]
I change to the following :  
function appRun($translate, $filter, $q, routerHelper, logger, $state) {
        routerHelper.configureStates(getStates($translate, $filter, logger));
    }

function getStates($translate, $filter, logger) {
      var test1 = $translate('settings.USER_DATA');
      var test2= $translate('settings.USER_DATA').then(function(translation) {
                            logger.error(translation); });
       var $translate = $filter('translate');
       var test3 = $translate('settings.USER_DATA');
        console.log(test1);
        console.log(test2);
        console.log(test3);
    // Here is my other code....
}


For console.log(test3) i have the following:
In my console i have : 
Error: User Information / Undefined
(anonymous function) @ angular.js:11699
error @ logger.js:33
(anonymous function) @ settings.route.js:40
processQueue @ angular.js:13292
(anonymous function) @ angular.js:13308
$get.Scope.$eval @ angular.js:14547
$get.Scope.$digest @ angular.js:14363
$get.Scope.$apply @ angular.js:14652
done @ angular.js:9734
completeRequest @ angular.js:9924
requestLoaded @ angular.js:9865

User Information is the right answer because in my JSON file i have the following:
{
    "settings": {
        "USER_DATA": "User Information"
    }}
In my view (at the title of the page) it show me taht : settings.USER_DATA

Why can't retrieve the right translation in my view ?
What i do it wrong?
Thank you

**Comment by tspaeth** [comment]
test3 is also a promise!

**Comment by m-assaf** [comment]
Didn't work with promise ?
How can i do it ?

**Comment by tspaeth** [comment]
Have you worked through the documentation a bit on how to work with the service stuff?
Look here: http://angular-translate.github.io/docs/#/guide/03_using-translate-service

And if you really want to be instant - see chapter "instant" or use the filter - http://angular-translate.github.io/docs/#/guide/04_using-translate-filter

**Comment by m-assaf** [comment]
Hello,
I always don't know how can i do translate inside inside my 'route' module, any idea ?

**Comment by knalli** [comment]
@m-assaf  Do you have read the guide? And what is your problem exactly? Your code posted above was already commented by us, did you see that?

**Comment by m-assaf** [comment]
Yes i read the article... I have module 'settings' wich is composed from 'settings.html', 'settings.controller.js', 'settings.module.js' and 'settings.route.js' and languages JSON files (lang/settings.lang.en.json, lang/settings.lang.de.json, lang/settings.lang.fr.json and lang/settings.lang.it.json). The code aboce is inside 'settings.route.js''.
What i need is to translate 'title' inside this file.

**Comment by knalli** [comment]
Please provide your issue in a demo code, i.e. plnkr.co
