### ISSUE TITLE
Filter vs Directive

### ISSUE THREAD

**Issue by aedenj** [angular-translate/angular-translate#1085]
Are there performance implications to using the filter or directive approach in a large scale app?

**Comment by eeiswerth** [comment]
What did you find? I just did a simple test with a 1000 messages. One page translated using filters and another page translated using the directive approach.  Using Chrome's timeline tool I found the directives approach took twice as long (959.9ms vs 402ms for the filter approach). To calculate those numbers I summed loading, scripting, rendering, paint, and other times. I did not include idle time. I also found the heap size was ~24320352 vs ~16878484 when comparing directive vs filter approach, respectively.  This was just a very simple test, but it seems to be contrary to what the docs say.

My tiny little test seems to show the filter approach performs better. At least right now.

**Comment by knalli** [comment]
It depends on the version of angular-translate as well AngularJS. Starting with AJS 1.3, filters' results will be cached more aggressively. Also your test directive vs. filter will not test the same: A directive loads the translation asynchronously (paying attention to all languages, fallbacks and so on), a filter will directly return the value which is at-the-moment available. If the filter is being invoked while loading the initial data, it will return null.

**Comment by borisbsu** [comment]
Per [Using translate directive](https://angular-translate.github.io/docs/#/guide/05_using-translate-directive) guide, the preffered way is to use translate directive:

> Another way to translate contents within the view layer is to use the translate directive. Using translate filter is great, but **using translate directive is better**. It turned out that **having too many filters in a view sets up too many watch expressions**, which is why angular-translate also provides a directive to translate your contents in view layer.
