### ISSUE TITLE
translate guide into Spanish

### ISSUE THREAD

**Issue by gonzalo-roberto-diaz** [angular-translate/angular-translate#1086]
Provide a Spanish translation for the guide.

**Comment by knalli** [comment]
@gonzalo-roberto-diaz Thank you for contribution! Do you want to translate the complete guide into Spanish?

**Comment by PascalPrecht** [comment]
@gonzalo-roberto-diaz great you got it started!

**Comment by gdiazblc** [comment]
Yes I will. I am already working on a fork here:
https://github.com/gonzalo-roberto-diaz/angular-translate
going page by page, unless you have a better idea. It won't take long.

**Comment by knalli** [comment]
landed -- closing this duplicate
