### ISSUE TITLE
Locale "de" could not be loaded

### ISSUE THREAD

**Issue by Zhouzi** [angular-translate/angular-translate#1087]
1. Go to http://angular-translate.github.io/docs/#/guide/14_pluralization
2. Scroll to the demo at the bottom of the page
3. Open browser's console
4. Switch to "german"

The error `Locale de could not be loaded: require is not defined` should appear. The demo still work as expected unless you set the preferred language to "de" (`$translateProvider.preferredLanguage('de');`).  It causes the error to be thrown on the application's bootstrapping and breaks everything. In fact it seems to happen when setting the preferred language to something else than "en".

Also, the documentation don't mention that you need to include the `$translateMessageFormatInterpolation` factory and the note about MessageFormat's locales is a bit unclear. I can't find any locale files in their [GitHub repo](https://github.com/SlexAxton/messageformat.js).

Hope it helps :)

**Comment by knalli** [comment]
> Also, the documentation don't mention that you need to include the $translateMessageFormatInterpolation

Sure it does. [useMessageFormatInterpolation()](https://github.com/angular-translate/angular-translate/blob/92bc9551279fc2f5bc7daaedebc87adede8b3713/src/service/translate.js#L327-L329) is a shortcut. It depends whether you are want to use MessageFormat always or in specific situations only.

Regarding the actual error and locales: Well, you have to look how messageformat.js handles its loading of locales. That's not out our part.

**Comment by knalli** [comment]
Sorry..  the issue with the locale is not "correct".

**Comment by knalli** [comment]
@tspaeth  Do you see a problem? http://plnkr.co/edit/CI29TNviKizHEhdfxvCB?p=preview is a copy.

**Comment by Zhouzi** [comment]
Ok sorry guys, my bad. The documentation is actually pretty clear! Apart from the remaining error on the missing locale, which is related to messageformat.js, everything is fine so I guess you can safely close this issue. Thanks and keep up the good work! :)

**Comment by tspaeth** [comment]
@knalli We could dive in the messageformat issue, starting point would be  https://github.com/SlexAxton/messageformat.js/pull/71 - I'm just wondering, why 2.2 doesn't work correctly as the ticket is older than 2.2...

**Comment by binbinan** [comment]
@knalli I am experiencing the same issue with the Web site (and with our own application) when trying to use pluralization and angular-translate.  I am loading the `locales/{lang}.js` file along with `messageformat.js` and `angular-translate-interpolation-messsageformat.js`

Also when opening the plnkr.co URL you provided I get an error in the console.  It functionally works, but it throws an error every time the language is switched to German.

Our app works after the translation buttons are pressed a few times, but still throws an error in the console every time.

More seriously, if the preferred language is set to anything other than English it refuses to load at all, as Zhouzi said.
