### ISSUE TITLE
translate directive doesn 't output everywhere in my dom 

### ISSUE THREAD

**Issue by gustavekossi** [angular-translate/angular-translate#1088]
I'm using introjs framework in order to explain my view.I also integrated angular translate in order to dynamicaly change current language. The problem my translation appear in the dom but never in the introjs box.
Here is the the sources:

This doesn't work :-1: : 
![image](https://cloud.githubusercontent.com/assets/4416249/8250935/59f9406a-1678-11e5-9951-0ee705de573a.png)
this in the dom :+1: : 
![image2](https://cloud.githubusercontent.com/assets/4416249/8250963/afc97974-1678-11e5-9391-ea8d2b566fc4.png)

![image3](https://cloud.githubusercontent.com/assets/4416249/8250965/b9c86782-1678-11e5-867d-038df8f2e8b1.png)

![image4](https://cloud.githubusercontent.com/assets/4416249/8250968/bd8dda0a-1678-11e5-9bc9-1d5c294e57ca.png)

![image5](https://cloud.githubusercontent.com/assets/4416249/8250970/c3782f06-1678-11e5-8492-15c9bf66c200.png)

![image6](https://cloud.githubusercontent.com/assets/4416249/8250972/c763f80c-1678-11e5-9d85-6650c8a05323.png)

Thanks i really expect to have help

**Comment by gustavekossi** [comment]
I have try this without translate it works but i can't use internationalization  
![image7](https://cloud.githubusercontent.com/assets/4416249/8251127/2c3bddca-167a-11e5-94a8-f56e9b36983a.png)
![image8](https://cloud.githubusercontent.com/assets/4416249/8251130/2f89c80c-167a-11e5-95db-8d8eaf92cd49.png)

**Comment by gustavekossi** [comment]
I have also try this,still doesn't work!
![image10](https://cloud.githubusercontent.com/assets/4416249/8251217/f5666e72-167a-11e5-9883-8f6532ae1349.png)
![image9](https://cloud.githubusercontent.com/assets/4416249/8251219/f7de785c-167a-11e5-811a-ded14c95aacb.png)

**Comment by knalli** [comment]
@gustavekossi  Last one clearly shows you AngularJS app is not configured or you are in an non AJS aware context. If you see a non compiled expression, that's not a specific angular-translate issue but a general AJS one.

=> You should fix your setup, specifically the template rendering in your app or used plugin (introjs).

**Comment by gustavekossi** [comment]
Thanks for your answer but the problem is i'm calling exactly the same expression {{'HEADLINE' | translate}} which display Hello there! both use the same controller
![image11](https://cloud.githubusercontent.com/assets/4416249/8251393/87a771ae-167c-11e5-963d-010771b18cad.png)

**Comment by tspaeth** [comment]
Before we really start a ping-pong analysis game or dig in the dirt - if you would put up a small Plunker, it would making support really much more simpler!
(btw: the bracket syntax in the directive looks a bit suspicous)

**Comment by knalli** [comment]
> Thanks for your answer but the problem is i'm calling exactly the same expression {{'HEADLINE' | translate}} which display Hello there! both use the same controller

Again: It looks like the context in question (your dom within "ng-step") is not aware of or controlled by AJS.

**Comment by gustavekossi** [comment]
Finally i solved this issue by surrounding the function which calls my json translations by a setTimeout() with a delay of 1000ms
I'm not sure it's the best to solve this issue but anyway it works now.
Thank you guys
