### ISSUE TITLE
Translation IDs with underscores don't work in directive? e.g. STOCK.STOCK_ON_HAND

### ISSUE THREAD

**Issue by whodafly** [angular-translate/angular-translate#1089]
angular-translate - v2.7.2 - 2015-06-01

When I try to use translation IDs with underscores and the "translate" directive, nothing happens. I installed angular-translate-handler-log, but that didn't show anything. If I simply remove the underscores, everything works perfectly.

Here's the relevant parts extracted from my code.

en.json:
```json
{
  "STOCK": {
    "STOCK_ON_HAND": "Stock on hand"
  }
}
```

app.js:
```javascript
var app = angular.module("app", []);
app.config(["$translateProvider", function ($translateProvider) {
  $translateProvider.useSanitizeValueStrategy('sanitize');
  $translateProvider.useStaticFilesLoader({
    prefix: '/static/i18n/',
    suffix: '.json'
  });
  $translateProvider.preferredLanguage('en');
  $translateProvider.fallbackLanguage('en');
});
```

stock.html:
```html
<div ng-controller="StockController as stockCtrl">
  <header role="heading">
    <h2><strong translate>STOCK.STOCK_ON_HAND</strong></h2>
  </header>
</div>
```

**Comment by knalli** [comment]
That sounds strange. Please make a small demo.

**Comment by whodafly** [comment]
I've just set this up on Plunker, and I seem to have figured out what the problem is. As per http://angular-translate.github.io/docs/#/guide/19_security I set the sanitation policy to "sanitize". As soon as I set it to that, translation seems to break. If I change that to "escape" then translation works fine.

http://plnkr.co/edit/bzHZYcSkUTzZ3FS5YZwh?p=preview

**Comment by knalli** [comment]
Are you sure you have `angular-sanitize.js` and the module `ngSanitize` included?

**Comment by whodafly** [comment]
On my code at work where I'm experiencing the problem, yes. Oh, and when I changed to "escape" it didn't help.

Is there any way I can get angular-translate to output MORE logging? I'm unable to troubleshoot this effectively because it fails silently.

Side note: The documentation wasn't very explicit about including ngSanitize.

**Comment by knalli** [comment]
Here: It works for me. http://plnkr.co/edit/Hz2x85SnK9PATCHRZ74N?p=preview

> Is there any way I can get angular-translate to output MORE logging? I'm unable to troubleshoot this effectively because it fails silently.

Currently: no.

> Side note: The documentation wasn't very explicit about including ngSanitize.

Because of you module structure that is not possible at the moment, also we still support AJS 1.2.

Do you want to add such a hint in a PR? :)

**Comment by whodafly** [comment]
P.S. Even with sanitize installed correctly, this is still happening. There must be a conflict somewhere, just a pity I can't debug it.

**Comment by knalli** [comment]
What is still happening?

**Comment by whodafly** [comment]
I have to use translation IDs without underscores.

**Comment by knalli** [comment]
See my plnkr again:

> Here: It works for me. http://plnkr.co/edit/Hz2x85SnK9PATCHRZ74N?p=preview

Please show up the difference between this one and and yours.

**Comment by whodafly** [comment]
The problem is that I have many other dependencies and a rather complicated application which I can't just dump out here for all to see. Without proper debugging I cannot narrow down the problem, so I have just resigned myself to having to live without underscores.

**Comment by knalli** [comment]
But you see the link above with a working app containing underscores?

**Comment by whodafly** [comment]
Yes, your example works. My application still doesn't despite angular-translate being set up *exactly* the same way as your example.

**Comment by knalli** [comment]
> Yes, your example works.

Good.

Ok. I'll close this right now. Reopen or file again if you have a working demo. Otherwise we cannot help you, sorry.

**Comment by whodafly** [comment]
I'd really appreciate more debugging. Is there not *some* way I can step through what angular-translate is doing? It's clearly some sort of interference from another AngularJS module, but I can't track anything down.

**Comment by knalli** [comment]
No, it does not make sense some keys are working and others not.

Regarding debugging: You can try the [conditional console.log debug pattern](http://rhumaric.com/2014/02/quick-tip-console-logs-with-conditional-breakpoints/) if you mind.

**Comment by whodafly** [comment]
Thanks, I haven't seen that before. I'll give it a try.

**Comment by whodafly** [comment]
Ah, I found out what was causing the problem. We have a transformResponse hook, and it was interfering with the language files being loaded from the server. Thanks for the help.
