### ISSUE TITLE
Wait for Cordova 

### ISSUE THREAD

**Issue by zeeshanjan82** [angular-translate/angular-translate#1090]
I have a requirement to implement the multiple language support in my angularJS application based on the default language of the android device.

Inside my app.js file which is the main file where I define my angularJS module, I have the following code:
         navigator.globalization.getPreferredLanguage(
                 function (language) {    
                 $translateProvider.preferredLanguage(language.value);
                 },
                 function () {
                  alert('Error getting language\n');
                 })
        }

My problem is that I need to wait for the function(language) to return the preferred language and then load my angular application using that language. But what I find is that the application loads without waiting for the function(language) to return the preferred language and hence the default language is English and not the language of the android phone.

**Comment by knalli** [comment]
I don't get your code and your issue. That's without any context.

Anyway: You only have to setup the preferred language (i.e. `$translateProvider.preferredLanguage()` or `$translateProvider.determinePreferredLanguage()`) right in the config phase. If you call this asynchronously and out of AJS' config phase, that will probably not working any more.

**Comment by zeeshanjan82** [comment]
thanks @knalli let me elaborate more on the issue and I am sure there is a solution to it. 

Actually I am using Cordova and AngualrJS together to create an android application and I have a requirement where the application should determine the default language of the android device and then load the appropriate language json file which is also shipped with my angular app.

The issue comes when I am using navigator.globalization.getPreferredLanguage method of Cordova to find the default language when bootstrapping my angularjs application, at that time as its promise based It taken some miliseconds to determine the language but till then I have my main thread executing and going with a default language, so what I am doing now is , I use $translate service in my main controller to change the language in its init function but I would like angular-translate to wait for the cordova to return the default language and then use that when bootstrapping the application.

**Comment by knalli** [comment]
You cannot "wait" as angular-translate requires the information about the preferred language as soon as possible. Unless `determinePreferredLanguage()` really does not fit your need (check it again!), you will have to reset the language at a point later. And this will result into the situation you have been posted at the top. As a bad workaround, you can defer the angular bootstrap, but.. I would stick with the deferred language change.
