### ISSUE TITLE
Uppercase language name

### ISSUE THREAD

**Issue by gonzalo-roberto-diaz** [angular-translate/angular-translate#1091]
English, German, etc, as language names should be capitalized. Massively change them in the English docs.

**Comment by knalli** [comment]
@gonzalo-roberto-diaz Is there still a TODO at your side?

**Comment by gonzalo-roberto-diaz** [comment]
@knalli no, I don't think so. Language names have been capitalized already.

**Comment by knalli** [comment]
Fine!
