### ISSUE TITLE
Built in support for static translations

### ISSUE THREAD

**Issue by mobinni** [angular-translate/angular-translate#1093]
It would be nice to have the possibility to statically translate Keys in the HTML. An angular-translate build task for Grunt and Gulp if you may. If you need a reference as to what Im talking about:
https://mobinni.io/2015/06/21/quickfire-compiling-angularjs-with-static-translations/

**Comment by knalli** [comment]
Something like https://github.com/angular-translate/grunt-angular-translate ?

**Comment by mobinni** [comment]
I think so after a short glance at the library. Quick question, does it search for all the translations in HTML for instance and generate static HTML, for instance:
```
locales
- nl.json
- en.json
```
After task
```
dist
- views (en views)
- nl
  - views (nl views)
```
This so you have base routes to certain translated views?

**Comment by knalli** [comment]
Sorry for the delay.. please restart the question in this repo. Hopefully, the (sub) maintainer can answer this more precisely. I'm not aware of all features of the grunt task.. Ok?

**Comment by mobinni** [comment]
No problem I will!
