### ISSUE TITLE
translateProvider.determinePreferredLanguage() not giving correct locale in Internet Explorer

### ISSUE THREAD

**Issue by senthilakr88** [angular-translate/angular-translate#1094]
Hi I'm trying localize my app. but the determinePreferredLanguage not giving correct locale lang for IE. but it works well for firefox and chrome

**Comment by tspaeth** [comment]
Which version of IE do you use?

**Comment by senthilakr88** [comment]
I use IE 10

**Comment by knalli** [comment]
Could you please being more specific about what is not working? Do you have an error message?

**Comment by senthilakr88** [comment]
Hi knali,
    I'm trying to use localize my app. so by using determinePreferredLanguage() i'm letting angular decide my browser language. when i use that function for firefox it works fine and when the browser language changes. but for IE it is always en-US. it is not capturing the browser language change on my app start


here is my code 

angular.module('hp.wcm.estudio.localization', ['pascalprecht.translate', 'ngCookies'])
    .config(['$translateProvider', '$httpProvider', function($translateProvider, $httpProvider) {
       
   
 
      
        $translateProvider
            .useStaticFilesLoader({
                prefix: 'assets/messages/messages-', 
                suffix: '.json'
            })
            .registerAvailableLanguageKeys(['en', 'de','es', 'fr', 'it', 'ja', 'ko', 'zh', 'zh_CN', 'zh_TW'], {
                 'en*': 'en',
                 'de*': 'de',
                 'es*': 'es',
                 'fr*': 'fr',
                 'it*': 'it',
                 'ja*': 'ja',
                 'ko*': 'ko'
             })
            .determinePreferredLanguage();
     
    }]
);


There is no error message. simply it doesn't compute the browser language . it is always en-US

**Comment by tspaeth** [comment]
You're right. 
If your system is running en-US and Internet Explorer is changed to a stack e.g. 
1. German (de-DE)
2. English (en-US)

it will still respond with en-US on querying 
```
window.navigator.browserLanguage
window.navigator.userLanguage
window.navigator.systemLanguage
```

Honestly, then we don't have a client based solution for IE10 currently I guess :-(
The best approach is still to query a "dummy" serverresource and check the response to the Accept-Language headers (and for example return them as JSON)...

**Comment by knalli** [comment]
I'm still not getting the issue.. IE10 is responding the wrong locale using window.navigator.*Language? Really? What is about IE9, IE11, and so on?

**Comment by tspaeth** [comment]
They really don't do better somehow :)

Tried in IE11: 
```
javascript:alert(window.navigator.userLanguage);
```

This was the language order setting in IE:
![image](https://cloud.githubusercontent.com/assets/5180973/8405352/1acedac4-1e54-11e5-8384-b4908059d55e.png)

userLanguage -> de-DE
browserLanguage -> de-DE
systemLanguage ->de-DE

Does it need more than a quit? MAybe a reboot?

window.navigator.language IS supported since IE11, but not before.

**Comment by artdias90** [comment]
what's the status on this issue?

**Comment by knalli** [comment]
I will try to have a look at an IE10 in the next days.

As I am understanding this, the `window.navigator.(user|browser|system)Language` is not correct? Well, what should we do else?

**Comment by knalli** [comment]
Found this here: http://stackoverflow.com/a/2678437/525238

If this is really true, there will be no alternative for using server side determination.

**Comment by artdias90** [comment]
Basically I registered a wildcard '*' as a fallback, and before the wildcard I set all other rules, this seems to work for me. IE 11 is getting the default Windows language.

**Comment by tspaeth** [comment]
There is no good and clean solution for IE10 downwards. And maybe IE11 will or is behaving a bit better, but in general still "use a server based detection" is the only reliable suggestion for all browsers here.

@knalli do we have any task open in this ticket?

**Comment by knalli** [comment]
Yeah, I've checked out and verified this in my IE10 VM (by modern.ie, which means it is an English installed system). Although I've configured German at top, the `browserLanguage`, `userLanguage`, `systemLanguage` are still returning the English one.

Therefor, I'll close this with *Won't fix*. If the browser is lying to us, we cannot fix this.

**Comment by knalli** [comment]
If someone comes up with an alternative for server side (which I would prefer anyway): feel free to share it.

**Comment by szukaiLee** [comment]
http://stackoverflow.com/questions/1043339/javascript-for-detecting-browser-language-preference

Use the return HTTP 'Accept-Language' header can determine the preferred language.
please try to implement this to support IE.

**Comment by tspaeth** [comment]
How shall we implement this as a general solution in this module if we don't know what and where the server lives and how it is configured to give appropriate response?

But in general, your suggestion is the general fool-safe preferred approach and somewhere in the old tickets we've suggested that. If you implement it as a small custom function matching your needs, it'll work also.
