### ISSUE TITLE
Plural Function not found for locale: ru

### ISSUE THREAD

**Issue by akatasonov** [angular-translate/angular-translate#1095]
Getting an error message "Plural Function not found for locale: ru"
I have looked into the repo of messageformat.js but can't find any plural functions for various locales there. Do I have to create one myself? Is there an example I can base it on?
Thanks!

**Comment by knalli** [comment]
@akatasonov  Does this question related to angular-translate, or are you faced with this issue with MessageFormat.js only? :)

**Comment by akatasonov** [comment]
I'm trying to make angular-translate work, so yes - this question is related to angular-translate :)

**Comment by knalli** [comment]
Well, we only support a bridge into MessageFormat.js which you have to configure on your own.

See more details [here](http://angular-translate.github.io/docs/#/guide/14_pluralization).

**Comment by akatasonov** [comment]
That's what this question is about. From the doc `Note: Please make sure to embed a corresponding locale file provided by MessageFormat. These files provide locale rules for a specific locale this is required to get proper pluralization!`
Please look into the repo of MessageFormat. There are no locale files provided, as far as I can see.
Does the documentation need to be updated? Am I supposed to write that local file myself?
Thank you.

**Comment by knalli** [comment]
Hm, looks like they have changed something vor 0.3. In 0.2 there was a subfolder `locale/`.

**Comment by tspaeth** [comment]
@knalli yup, looks like that... they're changing the module more often than I change some other things in life... *d'oh*

Please use the latest stable I would suggest... instead of the 0.3 non-stable...  https://github.com/SlexAxton/messageformat.js/tree/0.2.2/locale

**Comment by akatasonov** [comment]
@tspaeth Thanks! I will give it a try
