### ISSUE TITLE
Feature request: comments to and from localizers

### ISSUE THREAD

**Issue by innerpeace0** [angular-translate/angular-translate#1096]
Established internationalization and localization tools have the ability for authors to leave comments for localizers. For example, if a button says "File," authors can comment as to whether they mean a noun or a verb, and whether they are referring to a folder of papers or the digital equivalent or a tool or process for smoothing objects. 

This feature could be hacked in under the existing angular-translate structure by using something like `TRANSLATION_ID.COMMENT`. However, it might make more sense to build it into angular-translate. 

While the established internationalization tools have a place for comments from the original author, why not allow comments from localizers, too. These may give feedback to the author and to other localizers. They might be especially helpful to localizers who are localizing based on a localization one or more localizations removed from the original.

If this feature is already included, please change this to a request for direction to documentation. Thank you for your great work.

**Comment by knalli** [comment]
@innerpeace0  We have such a idea some time ago, but this would require a (meta) change of the translation tables (better: the loader).

Anyway: You can define such a layout on your own already today; you only have to build a small custom loader filtering the translation texts correctly.

**Comment by innerpeace0** [comment]
Other than your statement that this would require a meta change, I don't understand much of your reply @knalli, but I do think it would be quite simple to implement it by my idea of using something like TRANSLATION-ID._COMMENT_ or TRANSLATION-ID.SUB-ID._COMMENT_, etc. Authors can easily put them into their translation tables, but they won't put them into the actual app. For the most part, localizers won't need to translate them (except, perhaps, when the original language is something other than Engish), but will see them when they go to localize the strings.

Perhaps your team could agree on some kind of convention so that there will be a consistency. The master plan that I see is being able to automate things so much that localizers will need to know no code in order to localize apps. 

I nominate "._COMMENT_" (always in English) as the convention for this purpose.

**Comment by knalli** [comment]
But this *is* a change, too. Until now this would be valid translation key. After all, that's a breaking change.

We had also the idea of changing the meta structure of translations: For each translation there would be not a string, but an object containing a value (the translation), and comment and something else we don't know yet.

But again (my last sentence): This is logic being part of the loader. And everyone have the control to use a custom, selfmade loader which also means you can transform easily any existing structure into one which is required by angular-translate. In your case, it would skip all keys ending with `._COMMENT_`.

**Comment by innerpeace0** [comment]
As I understand it, angular-translate wouldn't even have to skip the keys in the translation table with .\_COMMENT\_ if the author didn't put anything with that into the markup itself. They would just sit there in the translation tables and never be seen by the users. When automating the localizations, they would show up right under their parent keys.

I like the ideas of going to an object and providing for comments within the object. I noticed that other users have a need for objects, not just strings. Is there a timetable for implementing this?

**Comment by knalli** [comment]
> They would just sit there in the translation tables 

Yep, and allocating space (ideally much more than the actual translation text) and will be never used. I don't like this, regarding memory consumption concerns.

>  I noticed that other users have a need for objects, not just strings.

No, that's not the same. I've only spoken regarding the format of translations which will be processed.. but not how they are stored internally nor be available. 

I'm repeating myself: The loader can make such processes already today. You have to differentiate between translation texts loaded (i.e. by a server/JSON resource) and translation stored and being available internally in angular-translate.

**Comment by innerpeace0** [comment]
I agree that having a way to filter out the comments so that they don't get loaded where they are not needed is a good idea. That's one reason why I was hoping that you'd come up with some kind of standard convention for them. It sounds like this is already on the drawing boards for future enhancements. Add my vote to it. Thanks.

**Comment by knalli** [comment]
As I said already.. that standard applies only for the loaders we are adding. But you can build your own loader (which is very tiny! and actually only one function) or your own http response transformer handling a JSON structure of your own choice.

We also would put that kind of logic into the loader or a post processor (i.e. http response transformer)

Regardless at which time and which result we decide doing something related to your question, you can use something you want. Don't wait for us. ;)
