### ISSUE TITLE
feature request: ability to not translate variables

### ISSUE THREAD

**Issue by innerpeace0** [angular-translate/angular-translate#1098]
Using the example from the developer guide, as I understand it, where: 

  TRANSLATION_ID: "{{username}} is logged in."

angular-translate would not only want to translate "is logged in.", but would also want to translate {{username}}. 

The way I envision my apps, any {{variable}} would be either translated elsewhere or, in the case of some variables such as {{username}}, input by the users and in no need of translation.  

So, I'd like the option to not translate the variables. Ideally, this could be done globally, with an override option. 

If this feature is already part of angular-translate, please let me know. Thanks for your great work.

**Comment by knalli** [comment]
`{{username}}` will not be translated but used as variable for dynamic content. Indeed, if you want translating you have to use `translate-compile` and a sub template...

**Comment by innerpeace0** [comment]
Great. That's just what I wanted to hear. 

I must have misunderstood the docs. Perhaps a clarification might help others to not have similar misunderstandings.

Thanks.
