### ISSUE TITLE
any solution for translation of big texts ?

### ISSUE THREAD

**Issue by eeesebio** [angular-translate/angular-translate#1100]
Hi,
How would you deal with i18n of big blocks of text, as "Terms and Conditions" ? Keeping them in javascript key/value pairs seems not the best way... Any other idea ? Switching between whole HTML pages ?
Thanks

**Comment by innerpeace0** [comment]
How do you eat an elephant? I'm planning on doing mine at most, one sentence at a time. In some places, such as where I use some strings repeatedly, or where the sentences are long, I'm even breaking the sentences into smaller chunks. 

I forsee my code looking something like:

    <p><TRANSACTION_ID_0>. <TRANSACTION_ID_1> <TRANSACTION_ID_2>.
    <TRANSACTION_ID_3>. <TRANSACTION_ID_1> <TRANSACTION_ID_4>.</p>

    ... (with transaction id's being meaningful names rather than numbered)

Thanks for posting the question. I'd like to hear from the experts if I'm on the right track before I go too far.

**Comment by knalli** [comment]
It depends.

You have both mentioned the options:

1. Split the text into parts. I would prefer a complete sentence as the smallest possible part, however.
2. One key = one string. If you configure sanitization and/or compiling, you could even translate a complete HTML output.
3. Do not translate long static texts with angular-translate at all (=> server side translate), but only the dynamic parts.

There is no "best" way, but a solution which fits your (personal) need.

**Comment by innerpeace0** [comment]
Duh!!! Of course complete sentences would be the smallest unit for something like terms and conditions, @knalli. A structure like `<ADJECTIVE_ID> <SUBJECT_ID> <VERB_ID>.`  would not work in many languages.

What was I thinking? DRY. This is a good example of how developers need to put aside their DRY orientation when it comes to i18n. 

Thanks for that clarification.
