### ISSUE TITLE
Prevent $translate.instant from compiling my string

### ISSUE THREAD

**Issue by toben** [angular-translate/angular-translate#1102]
Hello,

Let's say we have a string with the key MY_STRING for "en" with the content : "<b>{{obj.a}} {{obj.b}}</b>.".

If I do :

$translate.instant("MY_STRING")

The result will be "<b></b>" because it compiles the string...How can I avoid that ?

Thanks.

**Comment by tspaeth** [comment]
Yeah, but that is intentional. See here http://angular-translate.github.io/docs/#/guide/06_variable-replacement

**Comment by knalli** [comment]
Because of variable replacement, you will have to escape the interpolation markers with `\`. See [here](http://plnkr.co/edit/Ym00KgUlioTjAEJqE1ie?p=preview).
