### ISSUE TITLE
Static translations

### ISSUE THREAD

**Issue by mobinni** [angular-translate/angular-translate#1103]
It would be nice to have the possibility to statically translate Keys in the HTML. An angular-translate build task for Grunt and Gulp if you may. If you need a reference as to what Im talking about:
https://mobinni.io/2015/06/21/quickfire-compiling-angularjs-with-static-translations/
I think so after a short glance at the library. Quick question, does it search for all the translations in HTML

 for instance and generate static HTML, for instance:
```
locales
- nl.json
- en.json
```
After task
```
dist
     - views (en views)
     - nl
        - views (nl views)
```
This so you have base routes to certain translated views?

**Comment by knalli** [comment]
Well.. I was thinking restarting it at the grunt task's repo. :)

I've created it for you: https://github.com/angular-translate/grunt-angular-translate/issues/50
