### ISSUE TITLE
Matching Translations to Versions

### ISSUE THREAD

**Issue by innerpeace0** [angular-translate/angular-translate#1105]
I'm updating a lot of JS SPA's. I want to update them in such a way that they are easy to localize. This is so important to me that I have started my planning from that perspective and am working backwards. So far, out of everything I have seen, I am most impressed with angular-translate.

I've also been thinking about how to match versions and translations sometime down the road as I do further updates. For example, suppose the main app was in en-US at version 2.4, the localized translation for fr-FR was current to version 2.3, and the one for it-IT for was current to version 2.2. My first thought was to serve up the version of the app that matched the latest translation for the user's locale. 

Then, when I saw how angular-translate has the abiity to use a fallback language, I saw (and liked) the option of serving up the latest version of the app and letting the fallback fill in the gaps. However, using this approach, key:value pairs can't always be edited from one version to the next. Here's an example of what could happen when the value of a key is edited from one version to the next in a way that makes a significant change, but local translations from prior versions are used with the later version of the app.

Version < 2.4

    MY_PET: 'dog'

Version 2.4

    MY_PET: 'cat'

If the edit were just a clarification, such as `MY_PET:'beagle'`, it would often be fine to use the old key. Eventually, the local translation files would catch up. Meanwhile, the translation of the old value is workable enough.

The problem comes when there's a major change, such as in the featured example. Serving up the old version of the app doesn't solve this, either. Users would still get the old dog instead of the new cat. 

To me, this is another reason to use angular-translate's fallback language approach. By changing the key to something like `MY_NEW_PET:'cat'`, users with older translations will not have a translation for `MY_NEW_PET`, so they will get the fallback of 'cat' in English. They can either look it up or ignore it, but at least they are not getting something that is incorrect.

What thoughts and solutions do others have regarding the matching of app versions with translations?

Thank you for your help.

**Comment by tspaeth** [comment]
App Versions and Translation versions usually go together on releases and (continuous) builds. 
And if you're doing right with caching, you'll not run into any issues. 
So yes, if you miss to translate your files all at once, fallbacks might help here. But if you update translations content and you forget to do this in all langauges, well, that's not technically solvable besides your idea of renamed keys. 

But I'd more suggest to use other tools that could help here in building diff's of PO-files / translation files etc., so you see your changes before rolling out / deploying.

**Comment by innerpeace0** [comment]
They way I envision it on my open source projects, I'd do the original in en-US, and volunteers in various locales would do the localizations. So, there would be a time lag, and not all translations would always be as current as the main version, particularly right after the release of an update.

The other advantage I like about angular-translate is where there isn't a translation for something, and the fallback language shows up, users can submit suggestions for translations of that key. That will also help keep the translations more current with the main version. 

You folks have done a lot of things right. I am looking forward to using your app, now and as it evolves. Thank you for your great work so far.

**Comment by knalli** [comment]
My recommendation would be putting the information "version" into the special loader (i.e. an extend of a standard url loader) which using this to fetch translations for a specific versions.

Although you would still have the unsolved problem of incompatible versions (solved by the server?!), I do not see any other option. I do not think "fallbackLanguages" would be correct tooling.
