### ISSUE TITLE
angular-translate loads text labels before loading actual translations

### ISSUE THREAD

**Issue by pjindal612** [angular-translate/angular-translate#1108]
Hi,

I am using angular-translate for externalizing the strings. This translation is happening fine but the only issue is there is some delay in translations. I could see text labels before the actual values. This is happening even for default locale. Any updates on this?

My code looks like this:

http://plnkr.co/edit/eT1irYcZraFRYrNfj0RP?p=catalogue

**Comment by tspaeth** [comment]
Hi!
Have a look at the "FOUC" chapter here: http://angular-translate.github.io/docs/#/guide/12_asynchronous-loading

and also at the translate-cloak which is similar to what ng-cloak could provide but translate-specific... maybe that helps on hiding the elements first : https://angular-translate.github.io/docs/#/api/pascalprecht.translate.directive:translateCloak

**Comment by pjindal612** [comment]
Hi,
I looked into FOUC chapter at http://angular-translate.github.io/docs/#/guide/12_asynchronous-loading and added default translations using .translations(), But I didn't work for me. It is still flickering before displaying actual content. Since, I am using static files loader for different languages, I have to force asynchronous reloading. When I added .forceAsyncReload(true), I got below error:

Uncaught Error: [$injector:modulerr] Failed to instantiate module ULC due to:
TypeError: $translateProvider.forceAsyncReload is not a function
    at http://localhost:3000/app/index.js:138:24
    at Object.invoke (http://localhost:3000/bower_components/angular/angular.js:4203:17)
    at runInvokeQueue (http://localhost:3000/bower_components/angular/angular.js:4109:35)
    at http://localhost:3000/bower_components/angular/angular.js:4118:11
    at forEach (http://localhost:3000/bower_components/angular/angular.js:323:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4099:5)
    at createInjector (http://localhost:3000/bower_components/angular/angular.js:4025:11)
    at doBootstrap (http://localhost:3000/bower_components/angular/angular.js:1452:20)
    at bootstrap (http://localhost:3000/bower_components/angular/angular.js:1473:12)
    at angularInit (http://localhost:3000/bower_components/angular/angular.js:1367:5)
http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=ULC&p1=TypeError%3…2F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.js%3A1367%3A5)

**Comment by tspaeth** [comment]
Which version are you using? You'll need at least 2.7.1 - see here: https://github.com/angular-translate/angular-translate/releases :-)

**Comment by pjindal612** [comment]
I was using 2.7.0. Now I upgraded version to 2.7.2 ans I am not getting above error any more. Also, translations seems to be working fine for most of the places. Currently, I am getting this flickering issue for placeholder. My code looks like:
<li class="mainSearchField">
              <label for="searchBox" translate="ulc.index.label.search"></label>
              <input name="searchBox" required id="searchBox" ng-model="uvm.searchService.searchTerm" placeholder="{{'ulc.index.textfield.placeholder.search'|translate}}" type="search" />
            </li>

Any idea about this?

**Comment by innerpeace0** [comment]
No flicker in Pale Moon (Firefox derivitive) on an old old laptop running LxPup 15.05.

**Comment by knalli** [comment]
I'll close this in advance as it was solved by updating to 2.7.2.

@pjindal612 You latest plnkr is w/o translate, but only AngularJS (1.4). If you have FOUC issues, you probably should have a look at AngularJS https://docs.angularjs.org/api/ng/directive/ngCloak -- I guess that's the thing you are looking for.
