### ISSUE TITLE
translate placeholder text

### ISSUE THREAD

**Issue by erceth** [angular-translate/angular-translate#1109]
I'm trying to translated placeholder string but all I get is `"Stra&#223;e 1"` instead of "Straße 1".  The ß keeps turning into `&#223;`
<input type="text" ng-model="order.shipping.address.street1" placeholder="{{'street_1' | translate}}" />

If I have `<translate>street_1</translate>` it translates to "Straße 1" fine.  

This logs incorrectly:
$translate("street_1").then(function(t) {
		console.log(t); //`"Stra&#223;e 1"`
	});

How can I get this placeholder text to output correctly?

**Comment by crshumate** [comment]
bump

**Comment by bmichaelis** [comment]
This is the exact same problem I'm trying to solve.

**Comment by tspaeth** [comment]
Hm, I've just forked the plunker template... I don't see an issue here: http://plnkr.co/edit/rFyd4z4sA3jXAzLFMkz5?p=preview

Do you use any different setup with sanitize?

**Comment by crshumate** [comment]
My issue is with the placeholder attribute value for a text input. If I translate it in an html element it displays fine. However placeholder value does not. I forked your plunker to show what I mean. 
http://plnkr.co/edit/JBbsdcd7YpUolfDyc5Yc?p=preview

As you can see it is working correctly. I checked my versions with yours. 

Angular 1.4.0
Angular Sanitize 1.4.0
Angular Translate 2.7.2
Angular Translate Loader Static Files 2.7.2 (we don't use partial loader)

Could the different versions be causing the issue?

**Comment by tspaeth** [comment]
Could you setup a not-working version please - so it is better to understand what goes wrong? :-) 
But it'll be related to sanitize I guess..

**Comment by crshumate** [comment]
Ok I found the issue:

$translateProvider.useSanitizeValueStrategy('sanitize');

When I change it to the less strict:
$translateProvider.useSanitizeValueStrategy();

It works just fine. 

Resource: http://angular-translate.github.io/docs/#/guide/19_security

**Comment by knalli** [comment]
It's not less strict, it is called `escape`. And this looks like #1101

**Comment by tspaeth** [comment]
Then I'd close this as duplicate and if you're interested, follow the progress in #1101.
