### ISSUE TITLE
$translateProvider.use() always returns empty string 

### ISSUE THREAD

**Issue by badpenguin** [angular-translate/angular-translate#1110]
I use localstorage and it work perfectly but whatever i do i need to know the current selected language
the call to $translateProvider.use() always returns undefined
any idea?

**Comment by tspaeth** [comment]
Are you using it in the bootstrap/config of your app? Or why calling $translateProvider?

A Plnkr usually helps getting things easier for us.

**Comment by badpenguin** [comment]
I wish to know wich language useLocalStorage() and detect language have to find out in .config
Of cource $translate.use() its working in my home controller 
but, if possibile, i wish to know the language that's going to be used a little earlier.

**Comment by tspaeth** [comment]
a) could you please post a complete setup?
b) Well, the thing is, that the variable given back by asking use() is only set in one of these cases:
- $translateProvider.use(<ID>) or $translate.use(<ID>) is explicitly called
- refresh is called

Maybe I missed some.
But it's also depending on some asyncloaders responding or resolving.

So it also means in total, that you'll probably not get a reliable result in the config section. Maybe you'll get a result if you call it at the end of the config section, but preferrable I'd check if your logic can't be in the run section?

**Comment by badpenguin** [comment]
i've a few other settings that are based on the locale choosed, i will try to read them from localStorage directly or by moving to the run/ready section

thanks :)
