### ISSUE TITLE
coding style conventions for translation tables

### ISSUE THREAD

**Issue by innerpeace0** [angular-translate/angular-translate#1111]
Mostly because of how much I like angular-translate, I have decided to use AngularJS and angular-translate for my upgraded apps, but I'm new to them both. I'm starting with a translation table, and I want to use the best format, one that will be most familiar to others who have used the module. While I'm only writing the apps in one language, I want to make it easy for people in various locales to translate my apps. 

In looking at the guide, I notice that the translation tables in the examples are formatted as:

    var translationsEN = {
      KEY_0: 'enValue-0',
      KEY_1: 'enValue-1'
      ...
    };

    var translationsDE = {
      KEY_0: 'deValue-0',
      KEY_1: 'deValue-1'
      ...
    };

    var translations...

Before I proceed with this format, I have several questions:

1. My understanding is that one of the AngularJS theories is to keep the global namespace as clean as possible and use as few global variables as possible. `translationsEN` etc. look like they would all be global variables. Elsewhere in the guide, there is another example that uses an object: `$translateProvider.translations` and has all various language translations as part of that object. Which is the current preferred way? 

2. With or without the $ prefix? The [AngularJS API docs] (https://docs.angularjs.org/api) have a prominent notice at the top that says **"Please do not use the $ or $$ prefix in your code."**

3.  As I understand it, [Google's JSON style guide] (https://google-styleguide.googlecode.com/svn/trunk/jsoncstyleguide.xml#Double_Quotes) would recommend `"KEY_0": "Value-0"` (using double quotes around both the key name and the value) over `KEY_0: 'Value-0'`. There might be reasons to do a translation table differently. Suggestions? 

4. All the angular-translate example code seems to have in indent level of 2 spaces, all the examples in [John Papa's Angular style guide] (https://github.com/johnpapa/angular-styleguide#single-responsibility) intent 4 spaces (or one tab set at 4 spaces), but I didn't find a recommended indent level in either. Google coding

5. I'm aware that angular-translate is most focused on translations and not localizations. However, even with translations, there are some differences between locales. For example, there are a lot of spelling differences between en-US and en-UK, and, while my main apps will all be written in en-US, I'm expecting that they will all eventually have en-UK translations. (I believe that some other languages, such as sp, have some different translations depending upon locale.) I'm aware that, for general writing, the most common convention (there seem to be quite a few) is to put the two letter code for the language in lower case, followed by a dash, followed by the two letter country code in upper case. However, this will clash with naming conventions for code, particularly since js does not allow a dash in a variable name, and I've seen angular-translate use two letter upper case for language names. What convention do you recommend for this now?

6. Is it still important to keep all lines in translation tables to an 80 character length, or are enough of us now at the point to have auto wrap in our text editors? [Google's coding style guide] (http://google-styleguide.googlecode.com/svn/trunk/cppguide.html#Line_Length) (the formatting section of the C++ style guide included in the JS style guide by reference) still recommends an 80 character limit, but makes an exception for text literals, which would seem to include translation strings. 

If the answers are in the docs, I missed them, so links would be appreciated.

Thanks for your help.

**Comment by knalli** [comment]
@ 1 (global variables?)
These are examples and will probably not exist in production code. Furthermore, I think most usages will be a loader (like url loader, static files loader).

However: If you need to apply additional language texts outside of a loader (why?! :)), `$translateProvider.translations()` would be your api.

@ 2 (usage of the $ prefix)
Well, these decisions has been made by the original author years ago. I think @PascalPrecht would not made this again, but that's the situation we have now. 

You are right: the prefix is not recommended for modules mentioned by AJS itself. IMHO Do not use that prefix.

@ 3 (json style)
IMHO the JSON style guide is irrelevant when speaking about translation texts. We should not mix JSON content like APIs requests and responses with things like translations. But: It's up to you as a developer.

There are also people wishing they could use natural english (like default text) as translation keys. Speaking generally about JSON, I would follow the Google Guide. Definitely. IMHO the rules are fluent "correct" after using JavaScript for some years..

@ 4 (indent)
Well, in fact we are using [2 spaces for source code](https://github.com/angular-translate/angular-translate/blob/92bc9551279fc2f5bc7daaedebc87adede8b3713/.editorconfig). But again: It's up to you. Developing for angular-translate (the project) requires that style, but for all other things you can decide whatever you want. Globally speaking, that would be either 2 oder 4 spaces. Papa's style is fine (and very large).

@5 (localization vs. region/locale)
`en-US` means English (USA), `en-UK` means English (Great Britain). Both settings do not say something about the localization. However, you can deduce the localization mostly using the region.

We have to decide to handle one part: the translations. The other part localization is already covered by AngularJS itself (data) and by other plugins (runtime changing, i.e. https://github.com/lgalfaso/angular-dynamic-locale). It's up to you deciding having one language (`en`) or multiples derivations (`en-US`, `en-UK`, ...). We are concentrating on translating, just the name of the library.

If you have to handle everything, I would recommend a custom internationalization plugin. This one have to control and listen to translate, locales, your custom session information, locale information retrieval and what else. If you think of a reusable component, you can share this as independent angular plugin. AFAIK that does not exist.

@ 6 (line limit)
It's up to you.

IMHO I would stick with a recommendation rule: Try to write the code being under the limit of 80. But I also have projects (Java) with a limit of 120+. 

A fixed rule will result into bad exceptions.. but again: This decision is yours. It is only about readability. Sometimes a line of 100 characters is more readable than a forced split 2/3 liner.
