### ISSUE TITLE
FOUC problems with ASync Loader

### ISSUE THREAD

**Issue by M21B8** [angular-translate/angular-translate#1112]
I'm having some problems getting a fallback language to work alongside an asynchronous loader.
I have provided some default translations provided for english, which is set as the fallback language.
I then have a custom asynchronous loader to load the remaining resources. This will update one of the translations provided in the initial config.

If I set the browser to match the fallback language, everything works fine. If i set it to something else, then the default translations from the fallback language don't display until the Asynchronous calls have completed. Check this Plunkr, and change you language between english, and something else.

http://plnkr.co/edit/GIvCDI6dbNdqI9bwe97x?p=preview

**Comment by tspaeth** [comment]
@knalli should that feature "forceAsyncReload" and the other stuff around it "lead" to this way of loading?
As I was not much involved, I'm not sure if that mechanism would work during "bootstrapping" already when initially loading up the whole infrastructure so you'll see the "in memory" translationtable before replacing it by the async version...

In general, sounds like a nice approach, but @M21B8 you could also try to use default texts initially until we've aligned the "what should work, what not"...  :-)

**Comment by knalli** [comment]
@M21B8 

Switch this lines

```js
  $translateProvider.determinePreferredLanguage();
  $translateProvider.fallbackLanguage('en');
```

@tspaeth We have to look into this why this order has such a priority.

**Comment by tspaeth** [comment]
@knalli Definately. Still the old problematic "friend" in that structure...

I guess, I'll paint a flow diagram on that soon, so that we'll implement it correctly.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
