### ISSUE TITLE
async translating not working on IE11

### ISSUE THREAD

**Issue by thecyberd3m0n** [angular-translate/angular-translate#1113]
my code:
```
                        $translate('ERRORS.translationString')
                            .then(function (translatedValue) {
                                notify({
                                    message: translatedValue || ERRORS.tooManyCategories,
                                    duration: NOTIFY_CONFIG.duration
                                });
                            });
                    });
```
unfortunately in IE11 promise returned by $translate service was not resolved, and notification is never shown. It works perfectly on Chrome and Firefox.

**Comment by tspaeth** [comment]
The issue must be somewhere else, because in my projects, we're excessively making use of IE11 also... 
I've tested this here in IE11 and it works fine: http://plnkr.co/edit/WIPNqu8O3Ax6ofp2JiTJ?p=preview

To figure out what goes wrong, we'll need further setup or better a plunker - you can use mine as a base.

**Comment by thecyberd3m0n** [comment]
maybe that's something wrong with my configuration

$translateProvider
                .useStaticFilesLoader({
                    prefix: 'i18n/LJPromApp/locale-',
                    suffix: '.json'
                })
                .determinePreferredLanguage()
                .fallbackLanguage('en')
                .useSanitizeValueStrategy('escaped');

**Comment by thecyberd3m0n** [comment]
http://plnkr.co/edit/RxUwdwblWfoNIHjqFRMA?p=preview

I tried with my configuration, and it's works too on IE. You're right, it's something in my code

**Comment by thecyberd3m0n** [comment]
I'm sorry, I was using old version 2.6.1. After upgrade to 2.7.2 the problem disapeared
