### ISSUE TITLE
Translating issues for app name

### ISSUE THREAD

**Issue by innerpeace0** [angular-translate/angular-translate#1114]
One of the first translation issues that comes to mind is the name of my apps. How do other developers handle this? 

1. The first question is, do I translate the app name at all, or just use its English name everywhere?

2. If I were to translate the app name, would I just translate it once (perhaps in the heading) so users in other locales know what it means, but continue to use the English name throughout the app, or should I translate it throughout the app? (Both the app and the help files use the app name in various places.) 

3. If I were to translate the app name throughout I'd still want to put its English name in the heading. That brings up the question of the best way to provide a conditional subheading if the user uses another language other than English. Let's take the name of my primary app as an example, Inner Peace. If I were to do something like:

    `<h1>Inner Peace</h1>`
    `<h2 translate>INNER_PEACE</h2>`

I was thinking of using something like `ng-hide` to hide the `h2` element if the user were using English. Is there a better way?

**Comment by knalli** [comment]
@innerpeace0 At first: Thank you for giving us such great input and ideas. Honestly, this is great. Do not get me wrong, but that is not the correct board for that.

Why? This support place is actually not a place of a angular-translate "community" at all. We do love community support (in both directions), but we actually have no such place here. People talking about support (bugs, issues, features), but nothing more. That's the current situation, and not my opinion at all.

Although, we have to distinguish issues at this place. At the moment, we have serious problems to maintain the regular support in an optimum responsive manner (I'm not happy with the current situation). Yes, there is place for some meta discussions. But especially  that kind of discussion would be a great meta discussion point for Stackoverflow (or other global groups) involving people of other (translating) tools. 

If someone have something to share with us, he/she is welcome to write a comment here. But in favor for our regular support overview, I'll close this.

I'll give you my answer: I have no idea, and I think it depends more on marketing that actual "translating".
