### ISSUE TITLE
angularjs issue with setTimeout and link function directive

### ISSUE THREAD

**Issue by gustavekossi** [angular-translate/angular-translate#1116]
![timeout](https://cloud.githubusercontent.com/assets/4416249/8480261/08b82ca6-20dd-11e5-9d35-fd570f292483.png)

Hi all, i'm facing this issue.Trying to catch my translation from "intro" l.65 actually everything work fine
but the problem is using setTimeout to wait 1s is not the best. I'm  supposed to use link in the directive below but i don't know how after reading the docs i still not understand. Your help will be great. Thanks
![timeout2](https://cloud.githubusercontent.com/assets/4416249/8480410/b5c98962-20dd-11e5-831f-4c000c93d24c.png)

**Comment by tspaeth** [comment]
Sorry, but I don't get it. Where is the angular-translate code?

**Comment by gustavekossi** [comment]
yes exactly pour everything is working perfectly when i put the setTimeout from l.60 to 68 and wait 1s.it seems that link function is executed at the end of directive but i don't know how to remove the setTimeout and use link function instead

**Comment by tspaeth** [comment]
Could you setup a Plunker where some angular-translate code / calls are visible or used? Otherwise I don't know what we should/could help here...  or I'm just not getting it... :-)

**Comment by gustavekossi** [comment]
![timeout3](https://cloud.githubusercontent.com/assets/4416249/8487666/d1808ee6-210d-11e5-9979-b41072f027f1.png)
![timeout4](https://cloud.githubusercontent.com/assets/4416249/8487670/d5f45cdc-210d-11e5-975f-38c1ea1f22d7.png)

the project is too big, but you can see here my module the directive i created to handle my translations normally i should be more clear. i'm using introjs framework to describe my webpage  and translations appear in the tooltip when i put the setTimeout it's working but not when i remove it

**Comment by gustavekossi** [comment]
![timeout6](https://cloud.githubusercontent.com/assets/4416249/8488038/560f70c6-2110-11e5-9acc-834960811029.png)
this is my angular translate. i'm calling an api to retrieve dynamically the current language
it's work pour the problem is i'm obliged to delay my function in order to see my translation 

![timeout5](https://cloud.githubusercontent.com/assets/4416249/8488170/0637f16c-2111-11e5-9679-af53b1843d0d.png)

here 's my translation

**Comment by knalli** [comment]
I'm also not getting it. However, when working with `setTimeout()` or DOM directly you will have issues with AngularJS always. That's because no implicit `$scope.$apply()`will be performed (AngularJS basics). Ideally, you would use `$timeout()` instead of `setTimeout()`.

**Comment by knalli** [comment]
Closed due inactivity.
