### ISSUE TITLE
False warning about missing translation

### ISSUE THREAD

**Issue by HEm3R** [angular-translate/angular-translate#1119]
False warning about missing translation is logged for all supported languages when `preferredLanguage` and `fallbackLanguage` are not the same:

```javascript
$translateProvider.useMissingTranslationHandlerLog();
$translateProvider.preferredLanguage('en');
$translateProvider.fallbackLanguage('cs');
```

In second case, false warning about missing translation is logged for other languages not specified as `preferredLanguage` and `fallbackLanguage`.

```javascript
$translateProvider.useMissingTranslationHandlerLog();
$translateProvider.preferredLanguage('en');
$translateProvider.fallbackLanguage('en');
```

In my case, warning for __cs__ language are shown.

The issue was already created and closed: https://github.com/angular-translate/angular-translate/issues/669

**Comment by knalli** [comment]
As usual, a demo would be nice.

I've prepared one and cannot see an issue. http://plnkr.co/edit/842ObscafZdQy8keWZyq?p=preview

What's your setup?
