### ISSUE TITLE
Documentation: Gulp plugin for FOUC issues

### ISSUE THREAD

**Issue by sscovil** [angular-translate/angular-translate#1121]
I put together a Gulp plugin for dealing with FOUC issues, which takes a different approach than [grunt-replace](https://github.com/outaTiME/grunt-replace) (introduced in #921) but solves the same problem.

Please take a look at [gulp-ng-lang2js](https://www.npmjs.com/package/gulp-ng-lang2js) and, if you feel it would be helpful to others, share a link to it in your documentation. It's usage is outlined in great detail in the README file.

Cheers!

**Comment by knalli** [comment]
Well, that has taken some time.....

@sscovil : Thank you, I have added the link.
