### ISSUE TITLE
Difficulty in using angular-translate for translating select dropdown options

### ISSUE THREAD

**Issue by mukulgupta2507** [angular-translate/angular-translate#1122]
Hi,

Though I have posted this issue on the actual project but since it's related to angular-translate, I think asking community over here makes sense.

Actual issue link:
https://github.com/jseppi/angular-dropdowns/issues/56

Can anone please give me some idea of how to get it done ?

Thanks

**Comment by tspaeth** [comment]
Some basic suggestions as I don'T know the complete setup of your app and I'm in a hurry:

- try shifting the whole  $scope.ddSelectOptions to the "then..." block of the async response
- check if $translate.instant might help depending on your translation language setup / loader setup

**Comment by mukulgupta2507** [comment]
$translate.instant worked like a charm. Just want to confirm, there is no issue in using $translate.instant in place of regular $translate which return a promise. Is there any situation where I should avoid using $translate.instant() ?

Thanks

**Comment by knalli** [comment]
`$translate.instant(key)` returns the current information (regardless it's correct), but `$translate(key)` returns a promise proxy which waits for the correct key for the current situation (see for fallbacks, current loading translations, ...)

**Comment by knalli** [comment]
I'll close this in forward, the issue was solved I think. Ok?
