### ISSUE TITLE
Apply translate attribute on dynamically created element does not work

### ISSUE THREAD

**Issue by amfg** [angular-translate/angular-translate#1124]
Here's my problem: I am dynamically creating graphs using one modified pure-js library. The function for creating it also creates div element as an overlay, which contains some text. This text needs to be translated.
I tried to solve this by adding translate attribute to the element after it was created, however, it does not work (meaning no errors, but the text won't get translated).
I thought it might be some trivial mistake so I tried generating a simple div, added attribute translate=key and also inserted identical div into html code by hand. The second div gets translated, the first will not.
Is there a workaround for this?

**Comment by tspaeth** [comment]
how do you add the dom elements to the tree? Are you compiling them with angularjs or just add them?
A code example / Plunker would make life easier for us to support you.

**Comment by amfg** [comment]
Hello, sorry for the late response.
The library creates new element via document.createElement and then it appends to another DOM.
I have actually solved the issue by passing translating function instead of the string, now it works properly.

**Comment by amaalej** [comment]
@amfg  could you please share a snippet of your code?
