### ISSUE TITLE
Can I mix loaders?

### ISSUE THREAD

**Issue by juristr** [angular-translate/angular-translate#1125]
Hi,

what I'd like to do is to mix loaders, like in one module use the static file loader or partial loader

```javascript
.config(function translationConfig($translateProvider) {
    // $translateProvider.useLoader('$translatePartialLoader', {
    //   urlTemplate: 'locale-{lang}.json'
    // });
    $translateProvider.useStaticFilesLoader({
      prefix: 'locale-',
      suffix: '.json'
    });

    $translateProvider.use('de');
  })
```

and instead, in another module **add further keys** by directly registering them on the $translateProvider.

```javascript
.config(function($translateProvider) {
    $translateProvider
      .translations('de', {
        "anotherMessage": "Hallo dort!"
      })
      .translations('en', {
        "anotherMessage": "Hey there!"
      });
  })
```
Tried to reproduce my issue on this Plunkr here: http://plnkr.co/edit/5VeB1Sl8pHSrfT7WnijB?p=preview

I wasn't able to get the `$translatePartialLoader` to run (not sure what's the issue), but anyway, the problem reproduces also with the static file loader. I just get either the translations from the static file loader or those directly registered on the $translateProvider.

Is there any good strategy on how to solve this?? Especially in a modularized Angular app?

**Comment by juristr** [comment]
The point is that within my angular widget I embed translations using the `$translateProvider`. But now, when I embed that widget within another application that uses `$translatePartialLoader`, translations break...

**Comment by knalli** [comment]
@juristr  I've a demo at http://plnkr.co/edit/F9bsLhIOKCNpkPR6Xbrc?p=info showing a custom loader which uses another loader (in this case demonstrating a delay).

Because the loader is actually only a function returning a promise, you can provide a fully custom solution. If this built-in loaders do not fit your needs, you can use an completely selfmade one.

You could even think of creating a pluggable CustomLoaderDelegator at which your modules could register their own loader configurations. This is up to you -- you only have to match the loaders signature and returns.

**Comment by juristr** [comment]
@knalli Awesome, thx for the hint. I'll give it a go

**Comment by juristr** [comment]
@knalli Ok, I came up with this 1st draft of a pluggable loader delegator: http://plnkr.co/edit/ygaMvPBxYN3VWXEesWto?p=preview

Would be cool if you could give it a look and provide me some feedback on potential issues/improvements. I'd then like to create a package out of it s.t. it can be reused by others.

thx!

**Comment by knalli** [comment]
Well, delegating the requests: check.

Unless I've not overseen it I would suggest rethinking the requests and processings of your translation resolvings, but yes, something like this.

It does not make any sense to hold the translations in the loader (as you did). Only for the process of combining/merging this would be required eventually (within the function returned by $get, but not outside).

**Comment by juristr** [comment]
> Unless I've not overseen it I would suggest rethinking the requests and processings of your translation resolvings, but yes, something like this.

Sorry, didn't quite get it. :smile:  What do u mean by that?

> It does not make any sense to hold the translations in the loader (as you did). Only for the process of combining/merging this would be required eventually (within the function returned by $get, but not outside).

Well the probl here was that initially I delegated the static translations directly to the `$translate.translations` function, in order to avoid having to deal with them in my loader (just as you said). The probl is that in that case my `$get` of the loader won't be invoked. I assume this is because then the `$translate` service assumes to be used as the holder of the translations and ignores any other loaders. :question: 
Not sure whether that's right, but it was also one reason why I started to build this loader. Once you provide the translations like `$translationProvider.translations('de', {...})`, other loades like the static file loader etc are ignored.

**Comment by juristr** [comment]
(meanwhile I extracted the functionality in a dedicated library: https://github.com/juristr/angular-translate-loader-pluggable)

**Comment by knalli** [comment]
@juristr  Well, your work looks great! :+1:  I'm only curious about the loaded translations state (internally in your loader). I'd still not enough time yet looking into it, but think there could be a conflict / not determined  state of loaded translations while loading and requesting/returning translations. I would revisit the request and response behavior, as well as parallel request and response activities. 

I'll try to look into this end of the week.

**Comment by juristr** [comment]
@knalli Awesome, would be cool if u report me any kind of improvements directly on my repo: https://github.com/juristr/angular-translate-loader-pluggable/issues. That'd be great.

I'm still not sure I fully understood your doubts. Maybe I can help u if you provide indicate the line of code where there could be some potential conflicts. Note that [I only keep the translates internally](https://github.com/juristr/angular-translate-loader-pluggable/blob/master/src/angular-translate-loader-pluggable.js#L21) for those that are passed directly to my loader with the `translate(...)` function (as described further above). Would like to delegate that to the core angular-translate logic as well, but that didn't work out.

Meanwhile, thx!
