### ISSUE TITLE
Translate to service, translations from ajax call

### ISSUE THREAD

**Issue by sipeti** [angular-translate/angular-translate#1126]
Hello!

Now, I'm working on a project, with Angular, jQuery, and RequireJS.

The loading of the app is based on Require, I've managed to load the translate with Require. 

The main structure:

app
- controllers
|-- some controllers here
- directives
|-- some directives here
- services
|-- dataService.service

In the dataService, I have a simple get call for a json file. This contains the data, what the app manipulates, and this json contains the translation informations.

How could I hook up the translate for this project?

**Comment by tspaeth** [comment]
Did you read the general documentation? See here: https://angular-translate.github.io

If you don't know what goes wrong - please post a Plunker. Thanks.
