### ISSUE TITLE
Variable replacement with other translations

### ISSUE THREAD

**Issue by M21B8** [angular-translate/angular-translate#1127]
Not sure if i've just missed this in the documentation, but here goes.

I have the following translations:

LABEL_USERNAME: User Name
LABEL_PASSWORD: Password
ERROR_REQUIRED_FIELD: Please provide a value for {{field}}

What i need to do, is replace the variable, with another translation, e.g. Please provide a value for User Name.

I've managed to get round this, by loading the translations in my controller, and spitting it back out this way:
    
    <div translate="ERROR_REQUIRED_FIELD"
         translate-values="{ field: loginCtrl.labels.username }">
    </div>

but this means I have to watch for the translations changed even, and reload the translations, to get the values to update.

What I'm kind of after is: 

    <div translate="ERROR_REQUIRED_FIELD"
         translate-keys="{ field: "LABEL_USERNAME" }">
    </div>

or 

    <div translate="ERROR_REQUIRED_FIELD"
         translate-key-field="LABEL_USERNAME">
    </div>

Any help is greatly appreciated, thanks

**Comment by tspaeth** [comment]
Your graphics / images or code blocks are missing.

**Comment by M21B8** [comment]
Damnit, sorry, have put them back in.

**Comment by knalli** [comment]
Yes, this is possible with the flag [translate-compile](http://angular-translate.github.io/docs/#/guide/05_using-translate-directive#using-translate-directive_post-compiling), corresponding examples in the [tests](https://github.com/angular-translate/angular-translate/blob/92bc9551279fc2f5bc7daaedebc87adede8b3713/test/unit/directive/translate.spec.js#L549-L569).
