### ISSUE TITLE
Using $translate(): passing variable that contains translate key

### ISSUE THREAD

**Issue by vaneshmali** [angular-translate/angular-translate#1128]
I am using $translate in angular controller as:

$http.post("some_url", {'a':'myvalue'})
		.success(function(data, status, headers, config) {
				console.log(data.msg); //output my_response   (my_response   is translate key)
				var message=$translate(data.msg); 
				console.log(message);
 // output  contains $$state, catch, finally, then, __proto__
				// $$state contains : status:1 value: translated value	
			}

So, want to use that translated value. Simply using alert(message), but its object, so i can't. Whats the solution?

**Comment by tspaeth** [comment]
Please read the documentation for using $translate - service @ http://angular-translate.github.io/docs/#/guide/03_using-translate-service

$translate(<key>) returns a promise, so you must add the then block.

**Comment by vaneshmali** [comment]
Solved, Thanks.
