### ISSUE TITLE
serious security implications

### ISSUE THREAD

**Issue by madhurangaonbit** [angular-translate/angular-translate#1129]
Hi guyz,

After configure angular-translate on my app im getting below notification on Firefox.

"pascalprecht.translate.$translateSanitization: No sanitization strategy has been configured. This can have serious security implications. See http://angular-translate.github.io/docs/#/guide/19_security for details."

Is this the serious issue ??

**Comment by tspaeth** [comment]
Hi!

Have you read through the referenced link? There is also a link to the OWASP site referencing more information. 
If you have any questions left, feel free to ask here a bit more specific. Thanks.
