### ISSUE TITLE
Cannot include '&' sign in json with translations?

### ISSUE THREAD

**Issue by kotfilemon** [angular-translate/angular-translate#1130]
Hello,

We have used angular-translate with static-files-loader as follows in configuration:

```
(function () {
    'use strict';

    angular.module('kotek.language')
        .config(function ($translateProvider) {
            $translateProvider
                .useStaticFilesLoader({
                    'prefix' : 'assets/i18n/lang-',
                    'suffix' : '.json'
                })
                .registerAvailableLanguageKeys(['pl', 'en'], {
                    'en_US' : 'en',
                    'en_UK' : 'en'
                })
                .determinePreferredLanguage()
                .fallbackLanguage('en')
                .useCookieStorage()
                .useSanitizeValueStrategy('escape');
        });
})();
```

the file with translation looks like

```
{
    "navigation": {
        "title": "Pixy&Dixy",
    }
}

the title of the app has to include &. I have tried '&', '&amp;', unicode, and always had failed. it prints Pixy&amp;Dixy.

**Comment by knalli** [comment]
@kotfilemon If possible, provide a working demo. Thank you. I've setup one http://plnkr.co/edit/dRTcD83mvuCI4WmFN9kS?p=preview

You have configured "escape" which means all outputs will be escaped. That one is doing exactly what it should do.

You have following options:

1. Perform the translation on you own (by calling the service directly and inject the result in your own directive)
2. Switch the strategy to some less radical one. For example: If you have the translations under your control (and you know they are not containing (bad) HTML), you can use `escapeParameters` which will only escape the dynamic interpolated values but not the whole translation result.

**Comment by kotfilemon** [comment]
@knalli as I wrote, we use your static-files-loader, so our translations are in json files. your demo works, but our case still does not. please, check it out with static files.

**Comment by knalli** [comment]
It does not matter what the origin of translation will be. Whatever you are doing, each process of translations are the same regardless which loader will be used (or even using statics).
