### ISSUE TITLE
Encoding errors using sanitize strategy

### ISSUE THREAD

**Issue by hdn8** [angular-translate/angular-translate#1131]
Files are encoded in utf-8, but still outputs accents with errors.  Adding some log tracing:

[angular-translate.js from line 1786]
```js
...
     var determineTranslationInstant = function (translationId, interpolateParams, interpolationId) {

        var result, table = $uses ? $translationTable[$uses] : $translationTable,
            Interpolator = defaultInterpolator;

        console.log( table ); 
```

outputs: 
```
general: Object
     configuration: "Configuració"
```
correct!  Contains accented character, so the table is loading correctly.  

Next trace in [angular-translate from line 1797]:
```js
// if the translation id exists, we can just interpolate it
        if (table && Object.prototype.hasOwnProperty.call(table, translationId)) {
          
          var translation = table[translationId];
          console.log( translation );
          // If using link, rerun $translate with linked translationId and return it
          if (translation.substr(0, 2) === '@:') {
            result = determineTranslationInstant(translation.substr(2), interpolateParams, interpolationId);
          } else {
            result = Interpolator.interpolate(translation, interpolateParams);
          }
          console.log( result );
```
outputs: 
```
Configuració
Configuraci&#243;
```

In the interpolation is it somehow losing the utf-8 encoding?

**Comment by Ins87** [comment]
I just faced this problem
+1

**Comment by GenisDiaz** [comment]
I had the same problem and I could fix it removing the next line in my code:

<code>$translateProvider.useSanitizeValueStrategy('sanitize');</code>

**Comment by hdn8** [comment]
Worked!  But this creates a security issue I suppose...

**Comment by GenisDiaz** [comment]
Yep, but is the one form I found to fix it. I will be alert to possible fixes.

**Comment by hdn8** [comment]
It seems to work with sanitizeParameters or escape, only with sanitize it causes the error

**Comment by tspaeth** [comment]
As we're simply using the $sanitize underneath for the several options on valueStrategy, it  might be worth while to have a look at these AngularJS discussions:

- http://stackoverflow.com/questions/22994026/emoji-and-other-unicode-characters-not-appearing-correctly-in-angular
- http://stackoverflow.com/questions/23230680/angularjs-displaying-html-unicode

**Comment by luschinK** [comment]
Damm,

I spent so many hours to find this solution. Thank you so much !

**Comment by knalli** [comment]
Duplicate #1101 -- see also solutions and workarounds.

**Comment by JOELJOSEPHCHALAKUDY** [comment]
You have two options:

 1. Use the strategy sanitizeParameters which will only sanitize the dynamic parameters, but not the actual translation (template). If you have the translation under control (but not the dynamic values), this will work.
 2. Use the strategy escape (or escapeParameters) which does not use sanitization but escaping.

For me the  problem with hebrew and   was solved when i set SanitizeValueStrategy  to null

   ` $translateProvider.useSanitizeValueStrategy(null);`
