### ISSUE TITLE
RequireJS issue

### ISSUE THREAD

**Issue by ZoeyYoung** [angular-translate/angular-translate#1133]
I'm new to **requirejs**.

It takes me some time to figure out that I need to add "shim" in my **main.js** file to make this component work with **requirejs**.

```
require.config({
    paths: {
        ...
        angular: 'bower_components/angular/angular.min',
        angularTranslateLoaderStaticFiles: 'bower_components/angular-translate-loader-static-files/angular-translate-loader-static-files.min',
        angularTranslate: 'bower_components/angular-translate/angular-translate.min',
        ...
    },
    shim: {
        ...
        angular: {
            exports: 'angular'
        },
        angularTranslate: ['angular'],
        angularTranslateLoaderStaticFiles: ['angularTranslate'],
        ...
    },
    priority: [
        "angular"
    ],
    ...
});
```

But I could hardly find any documents to refer to .
Is there any document which mention this?

Thanks.

**Comment by knalli** [comment]
Sorry for the confusion.

> I'm new to requirejs.
> [...]
> Is there any document which mention this?

Honestly, these kind of configuration is well known (actually a sad situation) when using module loaders in browsers, especially in the context of browser javascript plugins and many not-amd-ready-plugins. Said this, nobody has missed this until today. Do not get me wrong: Your question is fine.

> But I could hardly find any documents to refer to .

Simply: We rely on the knowledge a developer has when using a module system.

Although it is obvious a plugin will depend on its core, we can add a paragraph about this in general. Feel free to add this in the docs, I would suggest at the end of chapter 0?

I'll close this in forward.

**Comment by ZoeyYoung** [comment]
Thank you for your answer..

I think I know why I confused.

Because I used the jqueryUI first. I look into the jqueryUI source code, and found:

in **datepicker-ja.js**:

```
define([ "../datepicker" ], factory );
```

then in **datepicker.js**:

```
define([
   "jquery",
   "./core"
], factory );
```

So I thought maybe you forgot to write the deps...Then I  figure out I should write the deps by myself....

(Sorry for my poor English.)

**Comment by ZoeyYoung** [comment]
In [http://requirejs.org/docs/api.html#config-shim](http://requirejs.org/docs/api.html#config-shim)

I found the comment below:

```
    //Remember: only use shim config for non-AMD scripts,
    //scripts that do not already call define(). The shim
    //config will not work correctly if used on AMD scripts,
    //in particular, the exports and init config will not
    //be triggered, and the deps config will be confusing
    //for those cases.
```

Does it mean that you don't need to call define in the module, if you didn't add the deps?

**Comment by ZoeyYoung** [comment]
@knalli 

In http://requirejs.org/docs/api.html#config-shim

I found the comment below:

    //Remember: only use shim config for non-AMD scripts,
    //scripts that do not already call define(). The shim
    //config will not work correctly if used on AMD scripts,
    //in particular, the exports and init config will not
    //be triggered, and the deps config will be confusing
    //for those cases.

Does it mean that you don't need to call define in the module, if you didn't add any deps?
