### ISSUE TITLE
Problem with $translate messageformat

### ISSUE THREAD

**Issue by robhicks** [angular-translate/angular-translate#1134]
I need help trying to hook up messageformat pluralization. 
I have everything loaded and configured. 
```javascript
$translateProvider
    .useLoader('$translatePartialLoader', { urlTemplate: fs.appPath + '/locales/{part}_{lang}.json' })
    .preferredLanguage(fs.simpleLocale())
    .useSanitizeValueStrategy('sanitizeParameters')
    .addInterpolation('$translateMessageFormatInterpolation');
```
I'm trying to inject count using the $translate service:
```json
"text_delete_modal_header": "Delete {COUNT, plural, one{Template}, other{Templates}}",
"text_delete_modal_content": "Are you sure you want to delete the selected {COUNT, plural, one {template}, other {templates}}?"
```
```javascript
var promises = [
  $translate('text_delete_modal_header', {COUNT: 1}, 'messageformat'),
  $translate('text_delete_modal_content', {COUNT: 1}, 'messageformat')
 ];
$q.all(promises).then(function(results) {
  console.log('results',results);
})
```
However, I receive an error from MessageFormat:
```javascript
r…t.SyntaxError {name: "SyntaxError", message: "Expected "=", "}" or [a-zA-Z$_] but "," found.", line: 1, column: 37}
```
I have also tried:
```javascript
var promises = [
  $translate('text_delete_modal_header', {COUNT: 'one'}, 'messageformat'),
  $translate('text_delete_modal_content', {COUNT: 'one'}, 'messageformat')
 ];
```
I realize I'm probably missing something very simple.

**Comment by knalli** [comment]
@robhicks We cannot give full support for messageformat.js.. that's not our project. We only provide a bridge into messageformat.js, but both translations and the actual interpolation work is not by us. The translations must be provided (i.e. yours) and the interpolation module delegates the work to the current available and injected/loaded messageformat.js lib version.

Also you should always attach a working demo (i.e. using JSFiddler or plnkr.co) demonstrating your issue. That also shows conflicts much easier.

Reading the syntax error (!), I would assume an invalid messageformat.js pattern. Perhaps a wrong version?

**Comment by robhicks** [comment]
Okay, thanks. I'll track it down in messageformat.

**Comment by theremin** [comment]
in my code it helped to change my translations from
..
"password_length": "The password must consist of at least {{length}} characters.",
..
to
"password_length": "The password must consist of at least {length} characters.",

the double curly bracket notation i have used without the messageformat implementation.
