### ISSUE TITLE
links in the site's flags dropdown are absolute

### ISSUE THREAD

**Issue by gonzalo-roberto-diaz** [angular-translate/angular-translate#1136]
Steps to reproduce:

1. build the site locally
2. go to Getting Started
3. click on the Languages dropdown, then click on any flag

The browser is redirected to the https://angular-translate.github.io/docs/... guide page for that language, not to the local one. 

This makes difficult testing improvements to the website, as one has to manually edit the URL in order to access the language's pages.

**Comment by knalli** [comment]
@gonzalo-roberto-diaz  Thanks for reporting, I've fixed that one. Will be available after next release.
