### ISSUE TITLE
Error when I use variable and html inside translation.

### ISSUE THREAD

**Issue by hmendezm** [angular-translate/angular-translate#1138]
I have the following problem. I pretty sure that I am doing some wrong. Can you help me with this?
<p>{{ 'TRANSLATION_ID' | translate:'{ userName: "{{authentication.userName}}" }' }}</p>

AngularJS v1.4.2
angular-translate - v2.7.2 - 2015-06-01

En-US.json

 "MSG_ENABLEREFRESHTOKEN" :"User <strong>{{userName}}</strong> has enabled <strong>Refresh Tokens</strong> once logged in, to refresh your current access token click on the button below."

Error:

 Lexer Error: Unterminated quote at columns 29-68 ['{ userName: "{{authentication.userName] in expression ['TRANSLATION_ID' | translate:'{ userName: "{{authentication.userName]

Thanks for any help!!

**Comment by knalli** [comment]
That's an invalid filter argument for AJS... Just like the error said already. Remove the quotes...

**Comment by hmendezm** [comment]
Thanks for your reply. I already removed the quotes but If I do that, the value of the variable is not show as supposed to.  So If I have <p>{{ 'TRANSLATION_ID' | translate:'{ userName:{{authentication.userName}}"}' }}</p> without "", this show the name of the variable so How I do this in angular-translate? the example in the documentation uses a static value which is not too realistic. Usually, you use variables to populate variables in the translation.

Best Regards
H.

**Comment by knalli** [comment]
Does work `{{ 'TRANSLATION_ID' | translate:authentication }}`?

**Comment by hmendezm** [comment]
HI Knalli, 

really thx for your reply...  I try the following but it did not work

<p>{{ 'MSG_ENABLEREFRESHTOKEN' | translate:'userName: authentication.userName' }}</p>

The situation is the in my en-US json I have the below for the translation ID. The idea is to replace {{userName}} with the value that I have in authentication.userName.

 "MSG_ENABLEREFRESHTOKEN" : "User <strong>{{userName}}</strong> has enabled <strong>Refresh Tokens</strong> once logged in, to refresh your current access token click on the button below."

Best Regards
H.

**Comment by tspaeth** [comment]
```
{{ 'MSG_ENABLEREFRESHTOKEN' | translate: {'userName': scopeVariableName} }}

{{ 'MSG_ENABLEREFRESHTOKEN' | translate: {'userName': 'MyName'} }}

```

these should do.

**Comment by hmendezm** [comment]
Thanks tspaeth. knalli recommendation fix the problem with the value. Still I have problem with the html that it is not render correctly. 

```
User &lt;strong&gt;USERNAME&lt;/strong&gt; has enabled &lt;strong&gt;Refresh Tokens&lt;/strong&gt; once logged in, to refresh your current access token click on the button below.

```

**Comment by tspaeth** [comment]
Have you enabled any sanitze-strategy and read the http://angular-translate.github.io/docs/en/#/guide/19_security chapter?

**Comment by hmendezm** [comment]
thx tspaeth, I will read it and yes I am using $translateProvider.useSanitizeValueStrategy('escaped'). I am using escape because it is the only one that allow me to have stress in the words. The app is for many countries such as Spain, USA, America Latina etc.

I will try with the other option to see what fit with the requirements.

Best Regadrs
H.
