### ISSUE TITLE
Align and update license headers and information

### ISSUE THREAD

**Issue by tspaeth** [angular-translate/angular-translate#1139]
As raised in https://github.com/angular-translate/bower-angular-translate-loader-partial/issues/18, it is a good idea to at least align all license files and headers to contain the same license information / copyright notice. It is a general discussion on / for enterprise organizations as you know...

Proposal I'd made - inspired by https://github.com/angular-ui/ui-router/blob/master/LICENSE and some others (as we don't have a legal organization behind, we'd need a person or more to be the copyright holder): 

Copyright (c) 2013-2015 The angular-translate team, Pascal Precht

@knalli, @PascalPrecht what do you think?

**Comment by knalli** [comment]
I'm okay with that.

**Comment by knalli** [comment]
Landed

**Comment by PascalPrecht** [comment]
I love your work here :heart:  keep going guys!
