### ISSUE TITLE
Allow group translations

### ISSUE THREAD

**Issue by rkmax** [angular-translate/angular-translate#1140]
The idea is allow to translate

```js
var app = angular.module('at', ['pascalprecht.translate']);

app.config(function ($translateProvider) {
  $translateProvider.translations('en', {
    TITLE: 'Hello',
    FOO: 'This is a paragraph.',
    BUTTON_LANG_EN: 'english',
    BUTTON_LANG_DE: 'german'
  });
  $translateProvider.translations('en.blahblah', {
    TITLE: 'Hello module',
    FOO: 'This is a paragraph in the module.'
  });
  $translateProvider.translations('de', {
    TITLE: 'Hallo',
    FOO: 'Dies ist ein Paragraph.',
    BUTTON_LANG_EN: 'englisch',
    BUTTON_LANG_DE: 'deutsch'
  });
  $translateProvider.translations('de.blahblah', {
    TITLE: 'Hallo module',
    FOO: 'Dies ist ein Paragraph. module.'
  });
  $translateProvider.preferredLanguage('en');
});

app.controller('Ctrl', function ($scope, $translate) {
  $scope.changeLanguage = function (key) {
    $translate.use(key);
  };
});
```

Allow to use like

```html
<h1 translate="TITLE"></h1>
<h2 translate="blahblah.TITLE"></h2>
<p translate="blahblah.FOO"></p>
```

This is only an idea

**Comment by HopefulLlama** [comment]
Is this not already possible by using a spinal-case to denote your secondary English language?

I.e.:
`
...

$translateProvider.translations('en-blahblah', {
    TITLE: 'Hello module',
    FOO: 'This is a paragraph in the module.',
    BUTTON_LANG_EN: 'english',
    BUTTON_LANG_EN-BLAHBLAH: 'english the second',
    BUTTON_LANG_DE: 'german'
  });

...
`

And then use like normal?

**Comment by knalli** [comment]
The first argument is a valid language key.. and not something "anything". If you use something else than a language id as store key, you have to define you own language loader. We will not make this.
