### ISSUE TITLE
Passing language from $routeParams to $translateProvider

### ISSUE THREAD

**Issue by joshikeerti** [angular-translate/angular-translate#1142]
I have an app where the user comes to the app from a url like http://xyz.com/123/en_US (locale is part of the url)
I want to load the app and based on the route params use the async loader to call the appropriate service based on the language.

What is the best way to pass the route params into the preferred language? 
$translateProvider.preferredLanguage('en_US');

**Comment by knalli** [comment]
Just use `$translate.use()` within the state's controller: http://plnkr.co/edit/tQJOfMR1LmljfmTi6s2c?p=preview
