### ISSUE TITLE
page shows the untranslated strings

### ISSUE THREAD

**Issue by vivianhewen** [angular-translate/angular-translate#1144]
I follow the guide to define a en.json file and config the translate provider as follows:
configModule.config(function($translateProvider){
        $.getJSON("i18n-en.json", function(response){
            var enJson = response;
            $translateProvider.translations('en', enJson);
        });
        $translateProvider.preferredLanguage("en");
  });

I translate it in my view page:
 ng-bind="'LABEL_TILESETTING' | translate"

then I test it in my local environment, very strange thing happens.
It shows the untranslated string in the page: LABEL_TILESETTING
but after I click a button and the page is refreshed, and then it shows the translated words:
Tile Setting.

It seems angular-translate doesn't get the value when the page is loaded. But how can I reload it after I get the event $translateChangeSuccess? I tried many times, but failed.
        $rootScope.$on('$translateChangeSuccess', function () {
            $translate.use("de");
            $translate.refresh();
        });
It still display the untranslated string.

**Comment by knalli** [comment]
Please provide a demo at plnkr/jsfiddle exactly with your settings.

**Comment by vivianhewen** [comment]
hi, this is the demo : http://jsfiddle.net/L7yb14pu/3/
I don't know how to upload my i18n-en.json file. can you add it to your project and test?
{
      "LABEL_TILESETTING": "Tile Setting"
}

I found if I use static file to load, the issue will happen. But if i load the translation by this way:
$translateProvider.translations('en', {
                "LABEL_TILESETTING": "tile"
            });
it will work very well.

**Comment by vivianhewen** [comment]
I have solved this issue by using static file loader, thanks:)
$translateProvider.useStaticFilesLoader({
              prefix: '/languages/i18n-',
              suffix: '.json'
          });
