### ISSUE TITLE
How to using AngularJS directives in angular-translate?

### ISSUE THREAD

**Issue by Lukec1** [angular-translate/angular-translate#1146]
Hi,
I have problem with using ng directives in translations. In my example in plnkr(http://plnkr.co/edit/kRVZdP?p=preview) i have two modules. First module have translations of SL and EN in boths json files have header and content keys with values which contains ng-show directive. In key »content1«,  i used link »more« and »less« which must show and hide some information of content with ngShow directive. But this doesn't work… In module2 is static html which is the same like translate value of »content1« in module1 and it's working great. How can i solve this problem?

Many thanks!

**Comment by tspaeth** [comment]
Well, I won't use whole content blocks with directive etc. as translation values as then you're mixing layout and content, but that's up to you. In that case, the content needs to be compiled as well, so please add "translate-compile" to your paragraph:

```
<p translate="content1" translate-compile></p>
```

**Comment by Lukec1** [comment]
@tspaeth  many thanks, that solved my first problem. Now i have another question...

In URL i write some attributes and get it in controller with $location.hash(). How can i show/open hidden information in div? I'm trying with  changing model value(baseInfoOpen or codeInfoOpen in plnk case) to true, but it not open hidden div.

**Comment by tspaeth** [comment]
@Lukec1 is this something that is related to translation? I'm not really getting the issue. sorry.

**Comment by Lukec1** [comment]
@tspaeth thanks anyway.

Issue is solved.
