### ISSUE TITLE
Feature: Component based translation tables

### ISSUE THREAD

**Issue by dwilt** [angular-translate/angular-translate#1148]
This ability/feature might already exist but I've done some googling and seen stuff about "asynchronous loading" as well as `partialLoader` but I'd figure since I couldn't find someone with the same sort of problem I'm having (or figure out how to solve it myself), I figured I'd create an issue:

I'm working on a project with a typical component structure:

```
app
-- components
---- header
------ header.jade
------ header.js
---- footer
------ footer.jade
------ footer.js
```

The typical pattern for locale files is to put a single language file with _all_ of the translations in there. For example, this is a typical `en.json` file:

`app/locals/en.json`
```
header: {
  title: 'My app'
},
footer: {
  someLink: 'Some link text'
}
```
This pattern above though doesn't really follow suit with a component/module organization based approach like I showed I'm doing above.

I'd love to either have the translations in my controller file (`header.js`/`footer.js`):

`header.js`
```
class HeaderController {
    constructor() {
        // somehow attach my translations in here by extending/merging the existing translations table
    }
}

angular.module('Header', [])
    .controller('HeaderCtrl', HeaderController);
```

Or as an external file next to the the rest of the component files, such as:
```
app
-- components
---- header
------ header.jade
------ header.js
------ header.json // this would contain the translations
---- footer
------ footer.jade
------ footer.js
------ footer.json // this would contain the translations
```

and then `header.js` would load in the file. Any help would be greatly appreciated, thanks!

**Comment by knalli** [comment]
I'm quite not sure why this idea would not fit with the partial loader.

**Comment by dwilt** [comment]
@knalli could you explain how you'd use the partial loader here?

**Comment by knalli** [comment]
Given your last example, a possible partial name would be `components.header.header`.

**Comment by shinrox** [comment]
I'm also having problems figuring out how to use the partial loader with this kind of app structure too :disappointed: 

How do I insert more content into the same language when a new component is loaded?

The main goal is to be able to copy the hole component folder into another project, and all the translations specific/default to that component just goes with it. Without the need to copy a separate file or copy/paste the keys into a main translation file.

ty

**Comment by knalli** [comment]
@shinrox  This is a nice idea, but it requires two things

* you have defined such a structure and organize all contents fitting this (components, language texts, ...)
* you have such a component texts loader which is following your self made structure

And again: If you have defined such a layout, you can try to use the [built-in partial loader](https://angular-translate.github.io/docs/#/guide/12_asynchronous-loading).

```js
$translateProvider.useLoader('$translatePartialLoader', {
  urlTemplate: '/app/components/{part}/{}part.{lang}.json'
});
```

Unless the built-in is okay, you can make your own loader.

**Comment by shinrox** [comment]
@knalli hmmm, what if my languages are angular constants and not json files? 

This is the structure that I use, and everything is bundled together with gulp, and again I can import the modules on different projects

```coffee
# app.coffee
angular.module('myModule.constants', [])
angular.module('myModule.services', []) #etc...

# load everything to one module
angular.module('myModule.scripts', [
  'myModule.constants' #etc...
  'pascalprecht.translate'
])

# main module depends on the 'module aggregator'
app.module('myModule', [
  'myModule.scripts'
])
```


I use this structure cause I think it's easier to test separate parts and stuffs :stuck_out_tongue_winking_eye: 

Anyway, I want to define my module languages like this

```coffee
# constants.coffee
angular.module('myModule.constants')
.constant 'myModule_enUS', {
  en_US : {
    MYMODULE:
      TITLE: 'My title'
      TEXT: 'My text'
  }
}

angular.module('myModule.constants')
.constant 'myModule_ptBR', {
  pt_BR : {
    MYMODULE:
      TITLE: 'Meu título'
      TEXT: 'Meu texto'
  }
}

```

How can I add those parts to the translate service, so I can use it like this without worrying about the module languages in every project?
```html
<!-- template.html -->
<h2>{{'MYMODULE.TITLE' | translate}}</h2>
<p>{{'MYMODULE.TEXT' | translate}}</p>
```

I did it like this, but I'm not quite sure if it's the best way or even the correct one
```coffee
# separate file to hold all keys and load on config
angular.module 'HolmesScanAssistant.constants'
.constant 'translations', {}

# factory to reload based on the translations constant above
angular.module 'myModule.factories'
.factory 'i18nLoader', ($q, translations)->
  loader = (options)->
    deferred = $q.defer()

    if translations[options.key]?
      deferred.resolve(translations[options.key])
    else
      deferred.reject('no translations found')

    return deferred.promise


  return loader



# service that add new keys to the constant based on others

angular.module 'HolmesScanAssistant.services'
.service 'i18nService', ($translate, translations)->

  service =
    addTranslation: (lang, values)->
      if !translations[lang]? # if first time adding language
        translations[lang] = {}

      angular.merge translations[lang], values

      $translate.refresh()


  return service


# controller
angular.module 'myModule.controllers'
.controller 'Ctrl', (i18nService, myModule_enUS, myModule_ptBR, $language)->
  # just to illustrate the use but I'm adding keys depending on language ...

  i18nService.addLanguage('pt_BR', myModule_ptBR)
  i18nService.addLanguage('en_US', myModule_enUS)

# app config
angular.module 'myModule'
  .config [ '$translateProvider', ($translateProvider) ->

    $translateProvider.useLoader('i18nLoader', {})
    $translateProvider.useMissingTranslationHandlerLog()
    $translateProvider.useSanitizeValueStrategy('escaped')
    $translateProvider.preferredLanguage('pt_BR')

  ]
```

Sorry about the long post, but I hope I could illustrate what I'm trying to do :P 

ty

**Comment by dwilt** [comment]
I was able to figure out how to achieve what I wanted to do (component-based locale files) via `$translatePartialLoader`

```
$translateProvider.useLoader('$translatePartialLoader', {
    urlTemplate: '{part}/locale-{lang}.json'
});
```

with this kind of folder structure
```
app
-- components
---- header
------ header.jade
------ header.js
------ locale-en.json
------ locale-es.json
------ locale-de.json
------ locale-jp.json
```

**Comment by shinrox** [comment]
Ok by me.
But my question continues about the constant mode that I've posted.

**Comment by knalli** [comment]
What is your question? Of course you can build an own custom loader which is not actually loading but using something else (i.e. constants). It's up to you.

**Comment by shinrox** [comment]
My question was if my approach is ok, or if there's any other better way of doing with constants. =)

**Comment by knalli** [comment]
Well, I'm not sure. I'd not make such things, pushing such stuff into the AJS context.

If someone comes up with a nice idea of doing this...
