### ISSUE TITLE
problem to load dependency using RequireJS - pascalprecht.translate and translateUrlLoader

### ISSUE THREAD

**Issue by gauravbhavsar** [angular-translate/angular-translate#1149]
I am trying to use angular-translate, don't know where I am doing wrong, please my mistake.

When I am load angular-translate as dependency getting error :

`Uncaught Error: [$injector:nomod] Module 'pascalprecht.translate' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.` 

I am using requireJS to load dependency like this :

    paths: {
              'pascalprecht.translate': '/bower_components/angular_translate/angular-translate.min',
              'translateUrlLoader': '/bower_components/angular_translate_loader_url/angular-translate-loader-url.min',
           }

    shim: {
        'angular': {
            exports: 'angular'
        },
    'pascalprecht.translate': {
            deps: ['angular']
        },
        'translateUrlLoader': {
            deps:['angular']
        },
    }

and then change dependency like this :

     shim: {
        'angular': {
            exports: 'angular'
        },
    'pascalprecht.translate': {
            deps: ['angular']
        },
        'translateUrlLoader': {
            deps:['pascalprecht.translate']
        },
    }

now getting error

`Error: [$injector:modulerr] Failed to instantiate module translateUrlLoader due to:
Error: [$injector:nomod] Module 'translateUrlLoader' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.`

again change dependency :

    shim: {
        'angular': {
            exports: 'angular'
        },
     'translateUrlLoader': {
            deps:['angular']
        },
    'pascalprecht.translate': {
            deps: ['translateUrlLoader']
        },
    }

now getting error :

`Uncaught Error: [$injector:nomod] Module 'pascalprecht.translate' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

Uncaught Error: Load timeout for modules: pascalprecht.translate`

**Comment by knalli** [comment]
Given your ids, `translateUrlLoader` (extension) depends on `pascalprecht.translate` (core) -- that is correct. 

However, the AJS module still has the origin name. I'm guessing you have tried something like `angular.app('app', ['translateUrlLoader'])` which is not correct. Neither the AJS name matches the RequireJS id automatically, nor the url loader have its own module (yet).

Your second config is allright, but stick with `angular.app('app', ['pascalprecht.translate'])` and a corresponding line for activating the extension via config.

**Comment by gauravbhavsar** [comment]
I am loading dependency in angular module like this :

    define(['angular','uiRouter','pascalprecht.translate'],function(angular)
    {
        return angular.module('app',['ui.router','pascalprecht.translate']);
    });

**Comment by knalli** [comment]
If you are using (and requiring) the url loader, you should require it in the dependency definition also.

```js
define(['angular', 'uiRouter', 'pascalprecht.translate', 'translateUrlLoader'], function(angular) {
    return angular.module('app',['ui.router','pascalprecht.translate']);
});
```

**Comment by gauravbhavsar** [comment]
Thanks @knalli 

I was loading `translateUrlLoader` as well after `pascalprecht.translate` in `angular.module`, may be that's why getting error.

now its working correcting.

many thanks
