### ISSUE TITLE
Any way to provide a fallback key?

### ISSUE THREAD

**Issue by lcarva** [angular-translate/angular-translate#1150]
Is there a way to provide an alternate key to be used if a certain key is not defined? This would be extremely helpful when the key is being dynamically constructed.

For example, I use the current pattern for handling this scenario:
```
var key = 'some.key.' + name;
var value = $translate.instant(key);
if (value === key) {
  value = $translate.instant('fallback.key');
}
```

Is there a better way to this? I was hoping something like this would exist:
```
$translate.instant('some.key.' + name, 'fallback.key');
```
In this case, if `'some.key.' + name` is not defined, the value for `'fallback.key'` would be returned.

**Comment by knalli** [comment]
No, unless you define the fallbacks already in the translation dataset (with links).

As you are already using the service, I would recommend using promise callbacks in chain: `preferredTranslation.catch(alternateTranslation)` or something similar..
