### ISSUE TITLE
translate directive chooses what to translate based on condition

### ISSUE THREAD

**Issue by artdias90** [angular-translate/angular-translate#1151]
I read the docu but couldn't find out:
Is there a clean way to choose which translation string to send in the directive call?
Something like:

<code> 
 < any translate="this.value > 10? 'foo' : 'bar'"> < /any >
</code>

**Comment by knalli** [comment]
What's wrong with `<any translate="{{value > 10 ? 'foo' : 'bar'}}"> < /any >`? :)

**Comment by artdias90** [comment]
translate="{{myVar? 'translation.string1' : 'translation.string2'}}"

getting always the true case

**Comment by knalli** [comment]
See here (last line): http://plnkr.co/edit/ezQB7kgOYZo84GtlfsMx?p=info

**Comment by artdias90** [comment]
ok so probably something on my model. Thanks
