### ISSUE TITLE
Is there a way we can load all translate json file before app started?

### ISSUE THREAD

**Issue by ramseyfeng** [angular-translate/angular-translate#1152]
We use lots of instant method in js and translate filter in our current project, and we are using staticfilesloader to loader the multiple language json files.
How can i handle the situation if the json file is a little bit big like 1MB, and the network speed is not very fast.
Currently if i run the application locally, i do not have any issues there, but if we deploy the app to the server which the network is not very fast, the word will not be translate properly.

Could you kindly give me a suggestion on this?

**Comment by knalli** [comment]
@ramseyfeng Either you apply some important translation directly (using `$translateProvider.translations()`), see here: http://angular-translate.github.io/docs/#/guide/02_getting-started#getting-started_aaaand-action 

Or you should have a look at the partial loader http://angular-translate.github.io/docs/#/guide/12_asynchronous-loading#asynchronous-loading_using-partialloader

**Comment by ramseyfeng** [comment]
![image](https://cloud.githubusercontent.com/assets/2835062/9128297/addc7868-3cf8-11e5-9bcd-23279a454209.png)
Actually i found all the words in parent controller got translated well, but the template with sub-controller didn't updated, could you kindly help me on this?

**Comment by tspaeth** [comment]
@ramseyfeng without any code example - this is very hard to tell...
