### ISSUE TITLE
using $translate in custom directive

### ISSUE THREAD

**Issue by h4d3s2004** [angular-translate/angular-translate#1154]
Hi
I'm trying  to use translate in a directive I've created but I it does not work. Is there a way to do this ?
Here is my code:
.directive('campRenvoi', function(){
        
            return {
                templateUrl: '/app/directives/ngCampRenvoi.html',
                restrict: 'AE',
                scope: {
                    rendata: "="
                }, 
                controller: ['$translate', '$scope', function ($translate, $scope) {
                    $scope.fq = "";
                    $translate("REN_FREQ").then(function (translatedValue) {
                        $scope.fq = translatedValue;
                    });
                   
                }]
                }       
    });
Or in the template ? Sorry if this is trivial or already answered ( I did not find a working solution).
Thanks.

**Comment by tspaeth** [comment]
Could you please show us a complete example of the issue as a plunker or jsfiddle?

**Comment by rgolea** [comment]
Why don't you pass in the filter?
```
        return {
            templateUrl: '/app/directives/ngCampRenvoi.html',
            restrict: 'AE',
            scope: {
                rendata: "="
            }, 
            controller: ['$filter', '$scope', function ($filter, $scope) {
                $scope.fq = $filter('translate')('REN_FREQ');
            }]
            }       
});
```

Maybe it's not what you've expected but I've used it like that and it works well.

**Comment by h4d3s2004** [comment]
Hi
Thank you.
Is there a way to to retrieve a text in a language different than the current language?  Or I need to switch languages ?
Best regards,Claudiu 


     On Friday, August 7, 2015 12:58 AM, Rares Golea <notifications@github.com> wrote:
   

 Why don't you pass in the filter?        return {
            templateUrl: '/app/directives/ngCampRenvoi.html',
            restrict: 'AE',
            scope: {
                rendata: "="
            }, 
            controller: ['$filter', '$scope', function ($filter, $scope) {
                $scope.fq = $filter('translate')('REN_FREQ');
            }]
            }       
});
Maybe it's not what you've expected but I've used it like that and it works well.—

**Comment by rgolea** [comment]
@h4d3s2004 You need to switch languages but you would've had to anyways.

**Comment by rgolea** [comment]
I saw your directive and I'm pretty sure you're about to do a directive called `ngCampRenvoi`. Don't use `ng` since it's saved for the core dev team... Use your own prefix. I use `rg` for mines... use yours

**Comment by h4d3s2004** [comment]
It works. Mersi. 


     On Friday, August 7, 2015 3:56 PM, Rares Golea <notifications@github.com> wrote:
   

 I saw your directive and I'm pretty sure you're about to do a directive called ngCampRenvoi. Don't use ng since it's saved for the core dev team... Use your own prefix. I use rg for mines... use yours—

**Comment by rgolea** [comment]
Feel free to close this issue.

**Comment by dangercris** [comment]
@rgolea your are a Genius!

**Comment by rgolea** [comment]
@dangercris thank you... But I'm not sure why...

**Comment by rgolea** [comment]
Glad I could help
