### ISSUE TITLE
Knowing if fallback

### ISSUE THREAD

**Issue by rgolea** [angular-translate/angular-translate#1155]
Is there a way to know which keys did the fallback on angular-translate? If you have many languages and keep developing stuff you should be able to do something like:
```
$rootScope.$on('$languageFallback', function(key, lang){
   console.log(key + ' in ' + lang + ' was not found. Please define it.');
});
```
It would help a lot while developing to know exactly which keys aren't available.

**Comment by tspaeth** [comment]
You mean at which language in the fallback stack every key at the end was "taken out"?

**Comment by rgolea** [comment]
I think so, yes... Imagine that I've translated 100% of the english language to spanish and in the meanwhile someone adds stuff to english... I would like to know which keys got to fallback. Is it too difficult?

**Comment by rgolea** [comment]
And maybe it should do on config something like `devEnvironment(true)` so it doesn't broadcast events when it's not necessary. Thank you @tspaeth for answering.

**Comment by rgolea** [comment]
Found out how to do it by using `.useMissingTranslationHandlerLog()`. Haven't found it in the docs until now. Thanks!
