### ISSUE TITLE
Error with MessageFormat and async loading

### ISSUE THREAD

**Issue by vstene** [angular-translate/angular-translate#1158]
I have a problem getting MessageFormat interpolation to work when translations are loaded asynchronous.

It seems like MessageFormat is trying to load the language file instead of waiting for Angular Translate to load it.

Error:
`Uncaught ReferenceError: Locale no could not be loaded: require is not defined`

Plunkr:
http://plnkr.co/edit/AxSZjWaJAtdWzMSOzNji?p=preview

**Comment by tspaeth** [comment]
Hi!
This is not directly an issue of angular-translate, but of messageformat - maybe http://stackoverflow.com/questions/19059580/client-on-node-uncaught-referenceerror-require-is-not-defined helps for you.

**Comment by vstene** [comment]
Hmm, yes. It also seems to fail if the loader is not async:
http://plnkr.co/edit/ZDwPU0I7QBm4WWT3f7WX?p=preview

It works fine if the language is `en` though. 

Anyways, I "solved" my problem by using [ngMessageFormat](https://docs.angularjs.org/api/ngMessageFormat).
