### ISSUE TITLE
  translated text & $sanitize on utf-8 title & placeholder

### ISSUE THREAD

**Issue by eidng8** [angular-translate/angular-translate#1159]
Reference to the original post from angular:

https://github.com/angular/angular.js/issues/12460

Plunker:

http://plnkr.co/edit/mQiWvt?p=preview

The` <title>` tag can't be checked in plunker, so I've put up a `<input placeholder/>` on top of the playlists list, in playlists.html.

P.S. I've checked before while trying to look into this issue. It seems that doesn't matter if I use `{{ 'some' | translate }}` or `translate` & `translate-attr-xxxx` attributes.

**Comment by knalli** [comment]
Note: The issue not new (more or less duplicates), I'll flag them all together.. Stay tuned.

**Comment by herrherrmann** [comment]
I'm having pretty much the same problem: German special characters like ö, ä, ü and ß don't get parsed well to `title` or `tooltip` directives.

This one should say *Priorität*:
![bildschirmfoto 2015-08-18 um 11 57 11](https://cloud.githubusercontent.com/assets/6429568/9327386/bb042e0e-45a0-11e5-90f2-91a64b681aeb.png)

**Comment by eidng8** [comment]
just a reminder that the link in th post has located part (if not root) of the problem, thx to @lgalfaso

**Comment by knalli** [comment]
Duplicate #1101 -- see also for solutions and workarounds.
