### ISSUE TITLE
Translate directive doesn't translate every key after migrating from 2.6.1 to 2.7.2

### ISSUE THREAD

**Issue by kyro38** [angular-translate/angular-translate#1160]
I just migrated from 2.6.1 to 2.7.2

Since that some key that's were working before aren't translated anymore and the key shows up instead (as if it would not be defined in my .json)

**Comment by jmijmi** [comment]
Is there any error or warning in console?

**Comment by kyro38** [comment]
Nothing gets printed in the console.

**Comment by knalli** [comment]
Please provide a demonstration about this issue. We simply cannot guess what your problem is (as everyone else has no issues for months).

**Comment by masi-kun** [comment]
Had this issue switching from 2.5.2 to 2.7.2. 

If your language JSON files are surrounded by square brackets, remove them and it should be fine.

**Comment by knalli** [comment]
Closing this.

If you can provide a demo, feel free to re-issue.
