### ISSUE TITLE
Using a variable's value as translate ID in a filter ?

### ISSUE THREAD

**Issue by warpdesign** [angular-translate/angular-translate#1163]
I have a variable which content I'd like to use as translateId:

.. locale.js: {
    TRUE: 'true'
... }

in JavaScript:
data.value = 'true'

in my template:

{{data.value | translate}}

The problem is that data.value is not evaluated so the end result is: data.value.

I tried to chain filters like this, but it didn't help:

{{data.value | uppercase |translate}}

Is it possible to make it work or do I have to rely on JavaScript ? (adding a function that would do that for me in the scope isn't a problem).

**Comment by knalli** [comment]
Ehm.. if your translations is lookking like `{ TRUE: 'true' }` you should use an expression like `data.value = 'TRUE'` together with `{{data.value | translate}}`.

OK?
