### ISSUE TITLE
ngAnnotate error on minified version angular-translate.min.js and angular-translate-loader-static-files.min.js

### ISSUE THREAD

**Issue by ciro207** [angular-translate/angular-translate#1164]
Hello,

I recently updated to v2.7.2; but I have an error reported both from gulp-annotate and ng-annotate directly. It seems that into angular-translate-loader-static-files.min.js is missing this piece of code

```a.$inject = ["a", "b"];```

![screen shot 2015-08-14 at 10 00 44](https://cloud.githubusercontent.com/assets/3327542/9269600/871419b6-426b-11e5-8df0-8149a2fa5ee5.jpg)

If I a not wrong _a_ should be _$translateStaticFilesLoader_, but I cannot understand what coul be _b_

And this is return from the angular-translate.min.js

![screen shot 2015-08-14 at 10 08 57](https://cloud.githubusercontent.com/assets/3327542/9269711/7c4d2a1c-426c-11e5-9797-cb5e25622f00.jpg)

No problem if I check with ng-annotate the not-minified version.
It is my fault or there is a bug on the minified version?

Thanks!

**Comment by knalli** [comment]
There does not exist such code `"a", "b"` in https://github.com/angular-translate/bower-angular-translate-loader-static-files/blob/2.7.2/angular-translate-loader-static-files.min.js. Whatever you have used, that files is not from our bower repository or has been modified by someone (or a tool).

Also I did not get you comparisons/diffs.. what do you want to tell/show us?

**Comment by ciro207** [comment]
I downloaded right now the minified version from repository. And the problem occurs again.
Let me explain again, maybe in a better way.

The problem is just that `a.$inject = ["a", "b"];` is missing. I'm not telling that file does not work inside the application, I am only reporting that ng-annotate is not validating the minified versione (and, in my case, stop the build process).

In the diff you can see the part of code that ngAnnotate reports as missing. Have you try to check the file with a command like `ng-annotate --add --remove angular-translate-loader-static-files.min.js -o test.js` and then find the differences? Did you get the same result as mine?

Thanks!

**Comment by ciro207** [comment]
Any news guys?

**Comment by knalli** [comment]
I do not understand the problem: The files in the repo do contain $inject. Just check my link in the comment 8 days ago.

**Comment by ciro207** [comment]
I did. I downloaded the file you attached, then I checked it with ngAnnotate and I got the error. Have you try to check the file indeed? Don't you have the same error?

**Comment by knalli** [comment]
What do you mean saying "I checked it with ngAnnotate"?

**Comment by knalli** [comment]
Ah.. you are using "ng-annotate --add --remove angular-translate-loader-static-files.min.js -o test.js". Why? What do you trying to do with this command? Our file is already ready to use.

**Comment by ciro207** [comment]
Because in our build process we checked every angular related files with ngAnnotate and the previous version did not have this problem. But if you say this is not a problem, I will try to bypass it.

**Comment by knalli** [comment]
Well, if you manipulate our file you should not blame us when it is not working anymore. ;) 

Again: Check the file and look for $inject. It will find it.
