### ISSUE TITLE
translate ng-bind which is inside angular directives template

### ISSUE THREAD

**Issue by JugnuPathak** [angular-translate/angular-translate#1167]
I have one directive which is creating dynamic control.Directive's template is as below

    "<div class=\"form-group\">\n <input type='text' ng-model=\"value|translate\" class='form-control'/>\n </div>"

  where in my directive scope i have :

    scope.value = 'VALUE';

and in config section i have :

    .config(['$translateProvider', function ($translateProvider) {
        $translateProvider.translations('en', {
            'VALUE' : 'Some value'
        });

        $translateProvider.translations('ar', {
            'VALUE': 'بعض القيمة',
        });

        $translateProvider.preferredLanguage('en');
    }])

  but it gives nonassign error : `Error: [ngModel:nonassign]`

how ever by applying filter on `scope.value` in directive and removing translate filter from ng-model solves problem.

    $filter('translate')(scope.value);
 and changing `ng-model='value|translate'` to `ng-model=value`

 But when user changes language it will not translate this pre-filled value of textbox because its assigned it by translating it as value and filter is not applied on it.

 here is fiddle : http://jsfiddle.net/jugnu_pathak/X2fsw/47/

**Comment by knalli** [comment]
What is your problem? `ng-model='value|translate'`? Well, that's not valid AJS. A model cannot contain a filter. Even it would be, how should that work? A model reflection by translation?

You are looking for a change of the value of `value` but not the reflection itself, I guess.
And I think you are looking for the HTML input's placeholder attribute?!

Additionally, your demo code was a little bit confusing. See result here http://jsfiddle.net/mk88745o/1/

* You are still using an outdated AJS 1.2, please update.
* You should not use minified code in demos, that's bad for reading error messages.
* You had written a directive a) in a very uncommon (and at least in this case not needed) way and b) skipping the AJS template binding (other than you described here!). There is no need for jQuery, at least a self made template injection will obviously broke the binding feature. Too much code, too less functionality.

Hope that helped you. I'm closing in forward, but feel free to write.
