### ISSUE TITLE
how to use two language at same time??

### ISSUE THREAD

**Issue by JugnuPathak** [angular-translate/angular-translate#1169]
can we have 2 language at a same time?

I have created multilingual site using angular-translate. Its working awesome but i have new requirement according to which i want 2 language on same page at time.So my container will be in user's local language , but inside that i want to show some content in different language but changing  language affects my container's content also???

**Comment by knalli** [comment]
No, at the moment this is not possible (at least: not possible in one app).

We have this feature on the plan for the next big version. #995
