### ISSUE TITLE
Apply translation into element's attributes

### ISSUE THREAD

**Issue by agilederek** [angular-translate/angular-translate#117]
First, I want to thank you that you provide a very high quality module.

When using this module, everything is find except for placeholder case.
Sometimes, I want to put translated word into placeholder.
But this module can't do that.
I modify a little bit. and I think others will meet the same problem.

The idea is add a new attribute "translate-attr" that indicate which attribute should be translated. 
And then in your translate directives, use element.html() or element.attr().
I don't know other people have better solution ?

```
attr.$observe('translateAttr', function (attrParam) {
    scope.attrParam = attrParam;
});
scope.$on('translationChangeSuccess', function () {
    var text = translate(scope.translationId, scope.interpolateParams, scope.interpolation);
    if (angular.isUndefined(scope.attrParam)) {
        element.html(text);
    } else {
        element.attr(scope.attrParam, text);
    }
});
scope.$watch('translationId + interpolateParams', function (nValue) {
    if (nValue) {
        var text = translate(scope.translationId, scope.interpolateParams, scope.interpolation);
        if (angular.isUndefined(scope.attrParam)) {
            element.html(text);
        } else {
            element.attr(scope.attrParam, text);
        }
    }
});
scope.$watch('translationId + interpolateParams', function (nValue) {
  if (nValue) {
    var text = translate(scope.translationId, scope.interpolateParams, scope.interpolation);
    if (angular.isUndefined(scope.attrParam)) {
      element.html(text);
    } else {
      element.attr(scope.attrParam, text);
    }
  }
});
```

**Comment by armyofda12mnkeys** [comment]
Just wanted to add a question onto this ticket since I believe its related....

I have links like so:
```
<a href="http://example.com/privacy-policy.html">Privacy Policy</a>
```
I'd like to use angular-translate to populate the href in addition to the Privacy Policy link:
```
<a href="http://example.com/privacy-policy-fr.html">Politique de confidentialité</a>
```
so I'd like to do something like with angular-translate to set attribute and element text (and a default in case no key is found):
```
<a 
translate-href="privacy.policy.link" translate-href-default="http://example.com/privacy-policy.html"
translate="privacy.policy.wordage" translate-default="Privacy Policy"
></a>
```
Is something like this in the plans for angular-translate or achievable in the current version?
Thanks,
Ari

**Comment by tspaeth** [comment]
No, there is no such feature for "locale specific link generation" in this module. But maybe you could probably still do something with a filter/translate-filter and ng-href if really needed?

**Comment by armyofda12mnkeys** [comment]
K, sounds good. Easiest thing for now was just setting up a $translation_helper variable in the scope which can hold values for things like href. Thanks tspaeth.

**Comment by Nicky-Agarwal** [comment]
Hi Guys

I have to name a column in Ng Table as a combination of own string and model variable i.e LIST PRICE IN (isoCode).Here List Price In is own string and isoCode is a scope variable,how to use translate for it??

will data-title="'List price in isoCode | translate"  be fine?

**Comment by tspaeth** [comment]
@Nicky-Agarwal Please don't comment on old, closed issues. 
For "how to" - questions like you have, we suggest to ask these on Stackoverflow please - thanks: 
http://stackoverflow.com/questions/tagged/angular-translate

**Comment by yokeshwaranR** [comment]
i am new to the angularjs, how to change a specific language font size while using $translate in json files.

**Comment by kristofmoell** [comment]
Hello guys

I'm using the translate in a directive. If I just want to translate one attribute value, the following works fine:
`<div help-me help-title="{{ 'COMPANY_TYPE' | translate }}">`

But when i have multiple values to translate, it doesn't work:
`<div help-me help-title="{{ 'COMPANY_TYPE' | translate }}" help-text="{{ 'COMPANYTYPE_HELPTEXT' | translate }}">`
