### ISSUE TITLE
Isue with placeholder + scope + variable replacement

### ISSUE THREAD

**Issue by MateuLlull** [angular-translate/angular-translate#1170]
Hi guys!

I'm having a trouble with placeholder translation. I'm trying to translate a placeholder from an `<input>` element that has a **ng-model** with it. I've read that `translate-attr-*` has his own scope, so the model won't work.

By the other hand, the variable replacement only works in placeholder by doing it with `translate-attr-placeholder`. There is a sample of my code:

```html
<input type ng-model="user.rating" translate translate-attr-placeholder="RATING_PLACEHOLDER" translate-value-name="{{ user.name }}">
```

And my translate text:

```javascript
var translations = {
     'RATING_PLACEHOLDER': 'Write the rating for {{ name }}'
}
```

Anyone know's how I can do my purpose?

**Comment by knalli** [comment]
Try using the filter in the placeholder Attribute directly.

**Comment by MateuLlull** [comment]
No way. If I put the filter in the placeholder attr then I can't pass my scope var. I tried this:

```html
<input type="text" placeholder="{{ 'RATING_PLACEHOLDER' | translate:'{name: user.name}'}}">
```

But obviously didn't work.

**Comment by knalli** [comment]
Please make a small demo with your code -- as simple as possible.

**Comment by MateuLlull** [comment]
Ok, Demo:

**HTML:**

I have this angular model:

```javascript
var user = {
       name: 'John',
       rating: 0,
       ....
}
```

And I want to put this placeholder over a textarea: *'Write the rating for John'*, but, obviously, I want to change the name dynamically, for this, I need to put a variable in the placeholder.

This can be solved by using `translate translate-attr-placeholder`. But, with this, I can't user `ng-model` for capture the rating.

So, this code works for printing the user name, but does not store the user rating:

```html
<input type ng-model="user.rating" translate translate-attr-placeholder="RATING_PLACEHOLDER" translate-value-name="{{ user.name }}">
```

By the other hand, this code works for storing data in `ng-model`, but I can't pass the user name:

```html
<input type="text" ng-model="user.rating" placeholder="{{ 'RATING_PLACEHOLDER' | translate:'{name: user.name}'}}">
```

The message that print this is: *'Write the rating for'*

This [plunker](http://plnkr.co/edit/uJM3GQpXNRgDSOUYG7uZ?p=preview) is an example of the issue. For numbers, it works, but not for strings and variables.

**Comment by nwhittaker** [comment]
I found passing the values as an object instead of a string got me access to the outer scope:
```javascript
<input type="text" ng-model="user.rating" placeholder="{{ 'RATING_PLACEHOLDER' | translate:{name: user.name} }}">
```
http://plnkr.co/edit/GmjJ0tpKvo37eEvLU5N4

**Comment by MateuLlull** [comment]
Yes! It works! My problem was that I was passing a string to the translate filter and not an object. All the examples of Angular-translate docs are passing a string to the filter and not an object, maybe it must be added to docs for other users can solve the same issue.

**Comment by artuska** [comment]
I have the same problem — `translate` with `translate-attr-title` just does not work in some cases: http://plnkr.co/edit/TNUzo6DsxyJg2oEuW73g?p=preview

**Comment by truongluu** [comment]
> @mateullull, I found passing the values as an object instead of a string got me access to the outer scope:
> 
> ```js
> <input type="text" ng-model="user.rating" placeholder="{{ 'RATING_PLACEHOLDER' | translate:{name: user.name} }}">
> ```
> 
> http://plnkr.co/edit/GmjJ0tpKvo37eEvLU5N4

Yes, it works for me, thanks you very much
