### ISSUE TITLE
Wait pending translation parts

### ISSUE THREAD

**Issue by jeremieca** [angular-translate/angular-translate#1172]
Hello,

I have a problem with angular translate part loader.

**Context**

I have one directive in another (parent and child).
I add a part json file with the following code in the parent directive : 

      $translatePartialLoader.addPart('pages/news');
      $translate.refresh()

Then, in the child directive, I would like to be sure translation part  is loaded before to use $translate.

**Problem**

  - I can't easily use $translateRefreshEnd in child directive, because if event is emitted before child directive load is complete, child directive never receive the event.
  - I can't use $translate.refresh().then() because I do the refresh in parent and I need to wait pending parts in child.

**A possible solution**

To solve the problem, I think to a function like that : 

     $translate.whenAllPendingPartLoaded(function () {
         // Guaranty that there is no pending parts, so I can use my part safely
         $translate('sentence.in.my.part', function () {});
     });

If there is no pending parts, the callback is called immediately, else, the callback is called when all pending parts are loaded.

**Question**

What do you think about that ?

Note : 

   - This issue have some similarities with https://github.com/angular-translate/angular-translate/issues/663.  
   - Sorry for my bad english, I'm french :s  

Jérémie C.

**Comment by knalli** [comment]
If you have to call the service `$translate` directly, you should install a local listener for `translateRefreshEnd` ensuring it can refresh your directive's texts (this fixes language changes in the future including running changes while evaluating/compiling the directive). Be sure to add appropriate listeners for every parameters (for the translations) if they exist. In addition to the initial translation (on compile, postlink, controller) you should cover everything.

You can avoid installing the listener when using the translate directive and filter directly (i.e. in the template).
