### ISSUE TITLE
How to solve the following problem?

### ISSUE THREAD

**Issue by utkant** [angular-translate/angular-translate#1177]
Hello!

I have a problem which I am unable to solve and I would like the community to give me some clarity on how we can best solve this problem.

A description of the problem.

We have a list of objects [{id:1, type: A}, {id:2, type: B}, {id:3, type: C}, {id:4, type: D}] and want to make a text representation like so:

"This is a text and by clicking the link for ```<a ui-sref='routeToA({id:1})'>A</a>```, ```<a ui-sref='routeToB({id:2})'>B</a>```, ```<a ui-sref='routeToC({id:3})'>C</a>``` and ```<a ui-sref='routeToD({id:4})'>D</a>``` you can go to these routes via their correct text and id fetched from the scope variable list of objects".

The problem is also that the list can have a varible number of objects. 

Any ideas on how to solve, or build a solution?

**Comment by knalli** [comment]
I'm not sure I'm getting you right.

If you are asking how to translate an unknown dimension of items -- you cannot. angular-translate is neither replacing you business logic or data structures.

You have (to) control of managing these four (or five, or three, ...) items to render, and you can utilize angular-translate for translating texts.

I'll close this in forward, but feel free to answer again!
