### ISSUE TITLE
How to loop on json array loaded with translate "useStaticFilesLoader"

### ISSUE THREAD

**Issue by maxime1992** [angular-translate/angular-translate#1178]
I would like to "ng-repeat" on thumbnails available in a json file.

The json file is like this :
```json
{  
    "pages": {  
        "page1": {  
            "field1": "My field 1",  
            "field2": "My field 2",  
            "field3": "My field 3",  
            "thumbnails": [  
                {  
                    "illustration": "images/img1.png",  
                    "content": "Content 1"  
                },  
                {  
                    "illustration": "images/img1.png",  
                    "content": "Content 2"  
                },  
                {  
                    "illustration": "images/img1.png",  
                    "content": "Content 3"  
                }  
            ]  
        }  
    }  
}
```

I have no problem to display field1, 2 & 3.
```html
{{ 'pages.page1.field1' | translate }}
{{ 'pages.page1.field2' | translate }}
{{ 'pages.page1.field3' | translate }}
```

But how to loop on thumbnails ? This doesn't work ...
```html
<div ng-repeat="thumbnail in thumbnails = ( 'pages.page1.thumbnails' | translate ) track by $index"> 
```
Here's a plunkr example if you want to give a try : http://goo.gl/qUCN1R

**Comment by claustres** [comment]
You are mixing the translations and your data, which is not a good idea in general.
Indeed translations in the JSON can only be accessed through an ID, you do not directly manages the JSON so you can loop over an array.

You need to have a JSON for your static translations such as 'field1' then a JSON structure in the Angular scope to manage your dynamic content (the thumbnail array) so that you can loop with ng-repeat and ask for dynamic translation of the content.

**Comment by knalli** [comment]
Second that. The intention of angular-translate is providing text translation -- one key, one value (incl. fallback and link feature), perhaps with additional arguments. You are mixing actual data (not texts) with the texts.

Said that, there is no need for iterating on translation texts. In this case.

In your situation, the page structure should be defined either in the controller or as a dedicated page service / model (this depends a little bit on your architecture and the size of the app).

**Comment by bencsbalazs** [comment]
I know this is old, but I think it works as below:
*ngFor="let thumbnail of ('pages.page1.thumbnails' | translate)"

and then you can use the thumbnail variables inside the loop.
