### ISSUE TITLE
First translated element in template outputs "translate"

### ISSUE THREAD

**Issue by Tickolas** [angular-translate/angular-translate#1179]
Hey there,

In my project we've been running into a bug where some translated texts would be output as "translate". In the generated HTML this would, for example, look like this: `<span translate="translate">translate</span>`, rather than the expected: `<span translate>TRANSLATE_KEY</span>`

After some digging we figured out that this would only effect the first translation in a block, such as a div. Also, Chrome seems to be the only browser effected. It appears that Chrome will populate any attribute of the first closed element in a template without an assignment with the name of that attribute. For example, `<span markus>` will be replaced by `<span markus="markus">`. This is usually not a problem, but for Angular Translate it causes the situation above.

As for workarounds, we've found several. Adding an element above with a closing tag (Example: `<span></span>`), visible or not, will cause the translation to work as expected. Also, using the format `translate="TRANSLATE_KEY"` will work. Finally, `<span translate="">TRANSLATE_KEY</span>` will work.

Here is a code example from one of our directive templates:
```
<div>
	<p>
		<img ng-src="item.imageSrc"/>
		<span class="label" translate>TRANSLATE_KEY_1</span>
	</p>
	<p>
		<img ng-src="item.imageSrc"/>
		<span class="label" translate>TRANSLATE_KEY_2</span>
	</p>
</div>
```
Which will output as:

```
<div>
	<p>
		<img ng-src="item.imageSrc"/>
		<span class="label" translate="translate">translate</span>
	</p>
	<p>
		<img ng-src="item.imageSrc"/>
		<span class="label" translate>Translated value 2!</span>
	</p>
</div>
```

This bug appears with Chrome 44.0.2403.157, AngularJS 1.4.4 and Angular Translate 2.7.2.

**Comment by knalli** [comment]
Please show this in a demo. Adhoc, I would assume an additional library is affecting the DOM.

**Comment by Tickolas** [comment]
Hey again!

Finally got some time to build an example, see here: http://plnkr.co/edit/8nTHZ7blDcnbLUAvLpsS?p=preview 

However, now that I try removing our bugfix divs as above the problem seems to have disappeared. Possibly there was some issue with an unclosed tag above or something. I'll let you know if we encounter the bug again!

**Comment by tspaeth** [comment]
closing as there seems to be no bug anymore.
