### ISSUE TITLE
ngOptions & angular-translate & ngSanitize

### ISSUE THREAD

**Issue by wim82** [angular-translate/angular-translate#1180]
Hey,

It seems when you use the "sanitize" sanitizeValueStrategy, it will properly encode all html characters from my language.json files. This means that certain accents get their proper escaped versions.

For example région becomes r&#233;gion as it should be. EXCEPT: inside ngOptions, because select elements don't work properly with html entities. (Per spec it should only accept plain text)

Is there any solution for this? Or am i looking wrongly? I can make a codepen or something to provide an example..

**Comment by knalli** [comment]
Yes, please make a demo we can see the results.

You are already aware of the ongoing [issues with sanitization and unicode strings](https://github.com/angular-translate/angular-translate/labels/ref%3Asanitization)?
