### ISSUE TITLE
Question: Why add preferred language to the fallback stack?

### ISSUE THREAD

**Issue by cmmcleod** [angular-translate/angular-translate#1182]
Why add the preferred language to the fallback stack?

It is done here:

https://github.com/angular-translate/angular-translate/blob/92bc9551279fc2f5bc7daaedebc87adede8b3713/src/service/translate.js#L477

https://github.com/angular-translate/angular-translate/blob/92bc9551279fc2f5bc7daaedebc87adede8b3713/src/service/translate.js#L1034

For my particular application, the only fall back language should be English. Their preferred language is determined automatically, but the user can select a language manually also. As a results of the current implementation, when the language is selected manually the automatically determined preferred language is also in the fallback stack, despite setting the fallback explicitly.

**Comment by knalli** [comment]
@PascalPrecht @DWand  @tspaeth  Any idea?

**Comment by PascalPrecht** [comment]
This is done because if a translation ID doesn't exist in one language, then the fallback language stack is request. angular-translate iterates over all fallback languages until it finds a translation. If you're in a different language and fallback languages are requested, you might want to have your preferred language as last item in the fallback language. Sort of a fallback fallback.

@tspaeth implemented this, maybe he has more thoughts on this.

**Comment by cmmcleod** [comment]
Understood, but is this the best behavior when the fallback stack is explicitly set?

In my particular case this is not the desired behavior, but there are no means to disabled it.

**Comment by PascalPrecht** [comment]
We actually moved this part back and forth when we developed it. We could introduce a new flag method `includePreferredLanguageInFallbackStack()` or sth. to disable it.

@tspaeth thoughts?

**Comment by tspaeth** [comment]
Sorry for the delay, was on holiday :sunglasses: 

It is exactly as @PascalPrecht described it. If you've set your current language for example to

"RU"

and your preferred was detected as "EN" and your fallback contains "DE" and "FR", it'll try to pick the language at last from your preferred language, so you get as a last resort a result... as far as I still remember it without looking into the code itself.
