### ISSUE TITLE
override useLoader's urlTemplate with $http response

### ISSUE THREAD

**Issue by th3nate** [angular-translate/angular-translate#1183]
hi,
im heaving a little difficulties with overriding some config phase settings (translatePartialLoader).
basically i need to receive the useLoader's urlTemplate path from a $http response.

is there any way to do so?
thanks!

**Comment by knalli** [comment]
If the built in loaders are not fitting your needs,you can make your own ones always.

**Comment by th3nate** [comment]
they do fit my needs, 
the problem is i need to wait for a json configuration object that contains the path that will be used in urlTemplate (declared in config phase).
and the json response only happens after the config phase.

so basically i'm asking if there's a way to override the path from outside the config?

**Comment by knalli** [comment]
No, it is not.

Therefor my advice: Write your own loader. Basically it is only a simple service function, you can make everything on your own.
