### ISSUE TITLE
Sanitization Strategy for Embedded HTML In Translate Filter and Service

### ISSUE THREAD

**Issue by dustymiller** [angular-translate/angular-translate#1184]
If I have a translation string that contains html tags, like so:
 
        "TERM_DIALOG": {
            "INSTRUCTIONS": "Select a term from the list below and click <strong>OK</strong> to display the classes, tests and data associated with the specified term."
        },
 
And I’m using the sanitizeParameters strategy, it seems like the only way to get the string ‘OK’ to display with the required strong styling (instead of displaying the literal <strong></strong> html tags in the page) is to use the directive form of translate, like:
 
<p translate="TERM_DIALOG.INSTRUCTIONS"></p>
 
But I cannot do this:
 
<p>{{‘TERM_DIALOG.INSTRUCTIONS’ | translate }}</p>
 
Or this:
 
$translate(‘TERM_DIALOG.INSTRUCTIONS’).then(function (translation) {  // do something with the translated string here });
 
Can we allow the translate filter and service to perform the translation in the same way the directive does?  I need to have the option to use any of the three translation methods in our app with translation strings that may contain embedded html.
 
Thanks for any help and for the excellent module!

**Comment by tspaeth** [comment]
Hm, if you set your sanitize strategy to
```
$translateProvider.useSanitizeValueStrategy('sanitized');
```

it will also parse these basic html tags correctly and even should without any configuration on the strategy if it isn't a parameter (your example isn't).
Please have a look at http://angular-translate.github.io/docs/#/guide/19_security if you haven't done so already.

I've just forked that example on the page and it works to me.

http://plnkr.co/edit/z5vIXNxnHn9Fuk9wyJSa?p=preview

**Comment by dustymiller** [comment]
Thorsten,

Thanks for the explanation. Perhaps my issue report was somewhat incomplete, so I apologize.  I have added to the plunkr to demonstrate what I was trying to report.  

http://plnkr.co/edit/lHSKRJKxJqlCTnWHxZcL?p=preview

See my Dynamic Text section at the bottom of the updated plunkr.  Basically I have one translation string being used in 3 different ways:

* using an interpolation using the **translate** filter, 
* using an interpolation where the variable on the scope has been translated using the **$translate** service's **instant** method, and 
* using the **translate** directive (regardless of whether or not there are translation values)

Notice that the string OK is displayed in bold only using the directive form, not in the other cases.  What I am looking for is a strategy that will display the string OK in bold across all forms.

Also, it would be wonderful if somehow the translate **directive** didn't overwrite existing inner HTML within the element on which it is used, or if there was an option to preserve vs. overwrite.  See the **directive** form with **inner HTML**.

I hope this clarifies my request somewhat.  Thanks for taking the time to reply and assist.

Thanks,

Rich

**Comment by knalli** [comment]
`{{dynamicText}}` is a expression which will be escaped (by AJS) automatically (well, except it is a sanitize wrapper value).

Perhaps I'm overseen something.. but it looks everything as expected (in context of AJS bindings).

**Comment by dustymiller** [comment]
Thanks for looking into this and for the feedback.  As I understand your explanation, the {{dynamicText}} string is being sanitized by AJS, so that once $translate.instant() is called in the controller function to generate the translated string, AJS will sanitize the string for display.  If this is the case, how would you recommend I display translated strings containing HTML that are created using the $translate service?  I tried wrapping the call to $translate.instant() inside $sce.trustAsHtml(), but it still displayed the tags in the web page instead of the **OK** I was expecting.

Thanks again.

**Comment by knalli** [comment]
sidenote: Have a look at my latest reply here https://github.com/angular-translate/angular-translate/issues/1101#issuecomment-140426486

Yeah, I'd accidently thought ng-bind would also look for sanitized values. Well, go for ng-bind-html.http://plnkr.co/edit/hpTjxvgN0qC2ig6sCpC8?p=preview

**Comment by laberg** [comment]
For @tspaeth answer, the strategy is written 'sanitize' and not 'sanitized' ;)
