### ISSUE TITLE
angular-translate-loader-static-files files option support  **/*.json

### ISSUE THREAD

**Issue by hjzheng** [angular-translate/angular-translate#1185]
I hope that `angular-translate-loader-static-files`files option can support  `**/*.json` like following code:
```js
$translateProvider.useStaticFilesLoader(
    files: [ 'dashboard/**/*.json', 'admin/**/*.json' ]
 );
```
If can not support it in future. can we have other solutions?

**Comment by knalli** [comment]
@hjzheng You should that work? Where are the placeholders for the language?

If the built-in loaders are not good you you, you will be able to implement a custom loader always. Have a look at the guide.
