### ISSUE TITLE
How to translate view-title

### ISSUE THREAD

**Issue by FrancescoMussi** [angular-translate/angular-translate#1189]
Hello. Great work!
Just one thing: how can i translate the view title?
Using the normal syntax doesn't work.

For example:
```
<ion-view view-title="Profile Edit">
```
Thanks!

**Comment by tspaeth** [comment]
Are you talking about using angular-translate in an angular-directive that comes from the ionic framework? And what is the normal syntax - we have directive and filter :-) ?

**Comment by knalli** [comment]
Just as @tspaeth  said already.. what is "using the normal syntax"?

Anyway, using the regular translate filter this works:

```html
<ion-view view-title="'profile_edit' | translate">
```

**Comment by FrancescoMussi** [comment]
Yeah sorry, that was the normal syntax for me.. 

Yes i am using it in the angular-directive ion-view in Ionic Framework
Elsewhere in the app is working smoothly.

In this way is not working:
<ion-view view-title="'profile_edit' | translate">

**Comment by tspaeth** [comment]
Sounds a bit like the "famous" bugs on calendars etc in the bootstrap module when these elements where rewriting the view itself. But I'm not a ionic user nor expert :-)
But maybe 

- http://robferguson.org/2015/07/22/internationalisation-i18n-and-localisation-l10n-for-ionic-apps/
- http://forum.ionicframework.com/t/angular-translate-does-not-work/28799/7
- https://blog.nraboy.com/2014/08/internationalization-localization-ionicframework-angular-translate/
could help?

**Comment by knalli** [comment]
@FrancescoMussi : This works at least for the HTML content (you have said view title).

However, the actual *window* title (but not HTML) is not refreshed. This can be a limitation / incompatibility with between translate and ionic, but you will have this issue with standard HTML pages and html::head::title also. If you want to refresh the window's title, you will have to apply this title directly via service and DOM.

If this is still not working, you should make up a demo.

**Comment by FrancescoMussi** [comment]
Ok. This is the solution: 

<ion-view view-title="{{ 'profile_edit' | translate }}">

I had to use the brackets on normal attributes.

**Comment by jwilde2000** [comment]
Angular's translation feature is cool in that you can essentially place all the translation code inside the markup without having to manipulate the DOM with TypeScript.  Still, however, you have to add and maintain that markup code for every single sting in your entire app, amounting to thousands of instances, and then translate by emailing the resource files around, and then see the results only by deploying the translated resource files.  Post-processing translation platforms like GlobalizeIt allow you to have all the same control with no code, online translation and instant publishing.  To set it up in your Angular project, you can these steps: http://www.globalizeit.com/Translate/Angular.
