### ISSUE TITLE
Require support to implement fallbacklanguage

### ISSUE THREAD

**Issue by gowthamanvt** [angular-translate/angular-translate#1190]
I have implemented most of the part for angular-translate, but the fallbacklanguage setup is not working properly. Kindly help me to resolve it.

 

Below is the code snippet:

 

app.config([ '$translateProvider', '$translatePartialLoaderProvider', 'LOCALES', function ($translateProvider, $translatePartialLoaderProvider, LOCALES) {

 

  $translateProvider.useMissingTranslationHandlerLog();

 

  $translateProvider.useLoader('$translatePartialLoader', {

        urlTemplate: contextName+'/app/{part}/resources/{lang}-{part}.json'

  });

 

  $translateProvider.useSanitizeValueStrategy('escaped');

  $translateProvider.preferredLanguage(LOCALES.preferredLocale);

  $translateProvider.determinePreferredLanguage();

 

}]);

**Comment by tspaeth** [comment]
I can't see the fallback-stack definition in your setup.

**Comment by gowthamanvt** [comment]
Sorry.! Finally I see the proper implementation from the docs. I was facing some issue from IE 11 browser, where the "$translateProvider.determinePreferredLanguage();" is not set up properly. Hence the app automatically falls back to "en" (I have set thru $translateProvider.fallbackLanguage('en_US');)

Any Idea, How to set proper browser language in IE 11..? I have set to German(de_DE) from settings but it was taking userLanguage as default (en_IN)..! Could you pls help to sort out this..?

**Comment by knalli** [comment]
Do you mean sth like this issue #1094?

**Comment by knalli** [comment]
Closed due inactivity.
