### ISSUE TITLE
Why is angular-translate always loading the fallback language?

### ISSUE THREAD

**Issue by julmot** [angular-translate/angular-translate#1193]
I am using angular-translate with "en" as a fallback language and in combination with angular-translate-loader-static-files.This is my setup inside `app.config()`:
```javascript
$translateProvider.useSanitizeValueStrategy(
	config.app.translation.sanitizeStrategy
);
$translateProvider.registerAvailableLanguageKeys(["en","de"], {
	"en_*": "en",
	"de_*": "de"
});
$translateProvider.useStaticFilesLoader({
	prefix: config.app.translation.prefix,
	suffix: config.app.translation.suffix
});
$translateProvider.determinePreferredLanguage();
$translateProvider.fallbackLanguage("en");
```
Regardless which language I've defined in my browser settings, the "locale-en.json" will be loaded everytime, before it tries to load the defined language. Example:
I have defined "de" as my primary language, so the plugin will load "locale-en.json" first. After that it will try to load "locale-de.json" and will use "de".

What is the reason for it? Why does the plugin always load the fallback language first?

**Comment by tspaeth** [comment]
before looking into it: Which browsers are you using?

**Comment by julmot** [comment]
@tspaeth Firefox

**Comment by tspaeth** [comment]
The preferred language is additionally also added to the fallback stack as a last resort so in case you're currently having one of the fallback languages as "used" and there are more but none of the fallbacks contains the translation key, it will try as a last resort to look it up in "all languages". Therefore, the async loaders startup will load all languages. 
Take a look at $translate.fallbackLanguage in the service

**Comment by julmot** [comment]
Okay but this does not answer my question why the fallback language is loaded even if no fallback situation is there? Let's say all my translations are available in the requested language then the fallback language will never be used. But as you say the file is beeing loaded nevertheless for the case that something is not available in the requested language.

**Comment by knalli** [comment]
Well, I could not remember this. But now I got it: The languages are loaded because you *think* there is no fallback situation. However, a fallback situation is not predictable. In case of a filter (which cannot use the logical promise/callback styled resolution path of translations), the fallback language *must be available*. There is no way of *wait*. So in order to guarantee at least an almost identical result of both `? $translate()` (which is used by the directive) and `$translate.instant()` (which is used by the filter), the fallback languages must be available.

**Comment by knalli** [comment]
An alternative would be returning nothing (unresolved translation), a deferred loading of the fallback language and the hope everybody who has consumed `$translate.instant()` (even the developer) is also consuming all the translate events and will refresh the texts. I think you are going with me: that's not realistic and therefor will create a lot more "unexpected" issues.
