### ISSUE TITLE
$translate.use() sometimes returns undefined in runTranslate()

### ISSUE THREAD

**Issue by fotofinder** [angular-translate/angular-translate#1195]
I'm trying to get the value of $translate.use() as soon as possible in my application to set a value on rootScope for later use.
I am using localStorage.
So in my .run() I do: 
```$rootScope.interfaceLang = $translate.use()```

Now I see that this is sometimes ( after reloading the page a couple of times in the browser ) ``ùndefined``` .

In  runTranslate after the 
```javascript
$translate.use(storage.get(key))['catch'](fallbackFromIncorrectStorageValue);
```

line I added this logging statement:

```javascript
console.log("translate has a storage and got:", storage.get(key), " now using ", $translate.use());
```
this is the output:
``translate has storage and got: en  now using  undefined``

If I wrap the logging statement in a fairly long $timeout ( about 1000 millis ) the output is as expected:
``translate has storage and got: en  now using  en``

Unfortunately I have no clue how to mock this in a test.
Any thoughts are welcome.

**Comment by knalli** [comment]
You have to wait for using use() because that is the actual used language. "As soon as possivle" in/after run() leads into undefined.

**Comment by fotofinder** [comment]
Would it be correct to translate a dummy string and to assume that when this translation has completed use() returns the correct value?
```javascript
$translate('DUMMY').then(function(data){
   $rootScope.interfaceLang = $translation.use();
});
```

Or is there an event to listen to?

**Comment by tspaeth** [comment]
Events? Please see http://angular-translate.github.io/docs/#/guide/18_events and check if one of the provided matches your needs.

**Comment by fotofinder** [comment]
see my updated comment
