### ISSUE TITLE
angular-translate-loader-static-files supports to modify the format of JSON file

### ISSUE THREAD

**Issue by thanhson1085** [angular-translate/angular-translate#1196]
it supports:
```
{
    "views.users.list.Users": "Users",
}
```
I hope that i can modify to:
```
{
  "views.users.list.Users": {
    "value": "User",
    "files": [
      "app/views/users/view.html"
    ]
}
```

**Comment by tspaeth** [comment]
Can you please explain what this defect / issue shall mean to us? Without any further explanation, this is not readable.

**Comment by thanhson1085** [comment]
Thanks for your response. I meant that I need Angular-translate support the different JSON structures.
For example:
Angular-Translate is able to works with either en_US.json:
```
{
    "translation_key": "Hello",
}
```
or:
```
{
  "translation_key": {
    "value": "Hello",
    "files": [
      "path_to_view"
    ]
}
```
The second format is support by [grunt-locales](https://github.com/blueimp/grunt-locales).

In my project, I used angular-translate. But I also use grunt-locales to generate and update json translation files if have any changes in templates or controllers.
However, grunt-locales and angular-translation are using different json file format. So I have to (pull a request)(https://github.com/blueimp/grunt-locales/pull/11) to make it work together.

I created this issue to hope that angular-translate is able to support differment json file formats.

**Comment by ericjames** [comment]
My karma unit tests don't like .json files.  Is it possible to dynamically load a .js file **and define the object name** inside?

ie: translation-en.js
```
var translation_en = {"something":"something"};
```
instead of: translation-en.json
```
{"something":"something"}
```

For example:
```
myApp.config(function($translateProvider) {
  $translateProvider.useStaticFilesLoader({
    prefix: '/i10n/translation-',
    suffix: '.js',
    name: 'translation_en'
  });
});
```

**Comment by thanhson1085** [comment]
Thanks. I find an alternative solution. So we should close this issue.

**Comment by knalli** [comment]
@ericjames Your question was not related to the original topic, you should create your own getting appropiate anwsers.

However, in your case: Please fix your setup. You can use JSON-files in karma tests (it does not look like a general XHR issue). Your idea will not work as there is no processing of globals (side note: bad style). One possible option could be JSONP.

**Comment by ericjames** [comment]
@knalli Ah ok I was a little confused, yes you're right the files right now are basically global objects which isn't good.  I reproduced the json files and it passed karma, probably was a formatting problem.
