### ISSUE TITLE
Provide option to listen to language change

### ISSUE THREAD

**Issue by julmot** [angular-translate/angular-translate#1197]
Hello,

I have some directives/controllers that translate some strings. When the language changes, I would like to recall my functionality to get the correct translated result. Therefore a listener-option would be great. Currently I am implementing a custom-mediator pattern, but I think it would be helpful for others to get a build-in solution.

**Comment by tspaeth** [comment]
Did you read the documentation on Events? http://angular-translate.github.io/docs/#/guide/18_events

**Comment by julmot** [comment]
My fault. I searched on Google, but this page seems to be not indexed (searched for "angular-translate events").
