### ISSUE TITLE
Provide directive for multi-language JSON

### ISSUE THREAD

**Issue by julmot** [angular-translate/angular-translate#1198]
Hello,

in many apps a JSON structure like this exists:
```javascript
{
  "some-article": {
    "title": {
      "en": "Title for English",
      "de": "Title für Deutsch"
    }
  }
}
```
This is a structure for blogs, threads, posts or any multilanguage page. However, currently we need to build a directive that will get the current language and the preferred fallback language (custom API - no function available for getting the fallback language) and show the related title in this example. And furthermore it's necessary to act on language-changes.

I think this process could be implemented and would be helpful for others to save time.

**Comment by tspaeth** [comment]
Hm, I don't understand what your issue is. Could you please provide a more descriptive example what you want to achieve and what is missing in angular-translate from your point of view?

**Comment by julmot** [comment]
I will try to describe it. Let's say I have a blog and my current route requires the page to show all blog-threads. So I am loading the blog-threads-database which could look like:
```javascript
{
  "some-article": {
    "title": {
      "en": "Title for English",
      "de": "Title für Deutsch"
    },
    "content": {
      "en": "My <b>Blog</b>",
      "de": "Mein <b>Blog</b>"
    }
  }
}
```
After I have loaded the database I (or angular) will parse the JSON object and I will save it to a class-variale. After that a ng-repeat will loop over each article in this class-variable. For example
```html
<div data-ng-repeat="(blogKey, blog) in myClass.blogThreads">
  <!-- Logic goes here -->
</div>
```
Inside the ng-repeat I would like to output the language-related title. If the app-language is "en" for example I would like to print the english title from the database ("Title for English"). How to achieve this? Well, currently I need to build a directive that I will call like this:
```html
<div data-translateBlogProp="theDatabase.title"></div>
```
Now the directive will search if the model "title" has a property with the defined language. If yes, it will replace the text with this property-value. If not, it will fallback to the fallback-language-value (e.g. "en").

Is it clear now?

**Comment by tspaeth** [comment]
As a basic concept of angular-translate, you should not mix multiple languages in one JSON structure but provide one JSON - structure per language.
Mixing is currently not possible nor detectable the way you want it to work.

Maybe you can write a loader that wraps everything in the right place upfront, so you convert the mixed structure to a senseful "clean translation table per language".

**Comment by julmot** [comment]
The reason why I am using the translation inside the JSON structure and not a JSON file for each language is that I am having a fallback language. So if for example the title is not available in my requested language "de" it will fallback to "en". However, this does not affect other properties like the "content". But if I would use a different file for each language if would need to map the data from different JSON objects which is more complicated for me, since this is not possible on the view-side of angularjs (like it is now with a custom directive).

**Comment by tspaeth** [comment]
But you know about "our" fallback-concept already implemented as described here: http://angular-translate.github.io/docs/#/guide/08_fallback-languages ?

**Comment by julmot** [comment]
Yip, I have read this. But how should I solve my problem with this?

**Comment by knalli** [comment]
If you want to load different languages with the same file: Write your own loader. That will not come into the core or as an additional plugin (because its too special).

You try to put logic (fallback strings) into the resolver.. which is not possible (at the moment). You can use the concept of fallback languages: if a translation for the requested key (and the current active language X) is not available, another language Y will be tried instead.

**Comment by julmot** [comment]
The problem with this workaround (different files for each translation key) is that I have to find the related object in a different file maybe for each key. This will cause performance issues and is also less comfortable for development. For my solution I have to search in siblings for the fallback key only.

What is the use case of the translator in multilanguage databases? I mean multilanguage databases with fallback languages are not "too special"?

**Comment by knalli** [comment]
Well, you try to "overload" a translation id being represented multiple times (or not), and being resolving by a special use case.

The much more simpler way is: One string, one translation. And again: The fallback *language* will be activated automatically for the requested string. Mixing a language file with different languages sounds not good.

Let's say Java and its properties files. One file (i.e. base English) is the standard and fallback language. If the requested German key (key in German file) is not found, the English one (key in English file) will be used.

**Comment by julmot** [comment]
I am also not a fan of this method, but it's necessary. I can explain you why. The translation should be done on each property separately and not for all properties inside the file. So we have a blog title and it will be checked if this specific property is available in the requested language. If not, the fallback language title will be used. However, this will not affect the translation for other properties. Your use case makes only sense if it would since you have to reload properties from different files which makes it very complex.

**Comment by knalli** [comment]
Ok, let's summarize that all a bit.

We will not provide a dedicate directive as requested in the issue's title. Perhaps you didn't want that also, an additional/other loader would be the right "thing".

However: We have already different kind of plugins, but they relay on different sources *by language*. The request/provide feature is provided by the chosen loader. If you want to merge every language in one file (or in a lot of files), you will have to generate a loader on yourself doing this. The interface of a loader is clearly documented. But the implementation can be whatever you want.

We have at the moment:

* pluggable loaders (additional the partial loader, and there is also a [pluggable-loader on npm/bower from someone else which is great!](https://github.com/juristr/angular-translate-loader-pluggable)) 
* fallback language stack
* links within a translation pointing to other translations

This request is very special and we don't think it should be part of the core. And I don't see we have to add a missing piece allowing you do solve this.
