### ISSUE TITLE
translation on the backend

### ISSUE THREAD

**Issue by jmls** [angular-translate/angular-translate#1203]
Whilst angular-translate is fantastic on the front end, we now have a need to do translation on the backend (server errors, message logs, debug messages etc)

Can I use any of the translation libs in node.js ? I would *hate* to have to move to another package that runs on both sides, so I am crossing my fingers and whispering "please, please, please say yes" ... ;)

**Comment by knalli** [comment]
Well, I'm not aware of the AJS state of NodeJS compatiblity, as angular-translate depends on this heavily.

If it works and you use an appropriate loader (the standard loader via `$http` probably not work and even won't make sense), it could work. Of cource, any built-in preferred language detection using ´window` and/or `navigator` will not work, too. No surprise?
