### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by aralroca** [angular-translate/angular-translate#1204]
A question...

I'm using angular-translate in some apps, but now I want to use in a big app when the translations JSON file have more than 2000 lines. 

How works angular-translate? Is creating one watcher for any word to translate? How about performance? I'm scared that my project starts to work very slow wrapping a lot of watchers.

Thanks!

**Comment by tspaeth** [comment]
Well, best would be to look a bit through our issue "archive" by searching for "performance" and "large" - you'll find several tickets handling individual tips like one time bindings etc. - but it is always a matter of "what does large mean".

**Comment by knalli** [comment]
Your application won't show all 2000 translations at the same time (I guess). Being a little bit scared is okay (good to check these things when developing a bit app!), but that should be okay.

Also it depends on the app's structure. Isolated scopes with filters will probably digest less often than everything in the main template. 

Hope that helps a bit.

**Comment by aralroca** [comment]
Thanks!
