### ISSUE TITLE
useSanitizeValueStrategy('sanitize') break accented chars

### ISSUE THREAD

**Issue by phuyem** [angular-translate/angular-translate#1205]
Hello, I am usng partialLoader: 

            $translateProvider.useLoader('$translatePartialLoader', {
                urlTemplate: STATIC_ROOT_PATH + 'i18n/{part}-{lang}.json'
            });
            $translateProvider.useSanitizeValueStrategy('sanitize');
            $translateProvider.preferredLanguage(LANG);

            $translatePartialLoaderProvider.addPart('hello');

useSanitizeValueStrategy makes "KẾT QUẢ" into K&#7871 ;T QU&#7843 ;

commenting it out solves the problem but giving a warning in Chrome console which sounds scary:

pascalprecht.translate.$translateSanitization: No sanitization strategy has been configured. This can have serious security implications. See http://angular-translate.github.io/docs/#/guide/19_security for details.

thank you for contributing such a great plugin

**Comment by knalli** [comment]
Duplicate #1101 -- see also solutions and workarounds.
