### ISSUE TITLE
escaped apostrophe breaks the whole translation

### ISSUE THREAD

**Issue by phuyem** [angular-translate/angular-translate#1206]
I am using partialLoading with Json and having problem with \'

This is not working
"key1":"value1","key2":"this \'is\' an error", ....

But this ones work:
"key1":"value1","key2":"this \"is\" an error", ....
or 
"key1":"value1","key2":"this 'is' an error", ....
or 
var langData = {"key1":"value1","key2":"this \'is\' NOT an error", ....}

Thank you

**Comment by knalli** [comment]
Please provide a test/demo case.

**Comment by phuyem** [comment]
I don't know how to use plnkr or jFiddle... sorry. 
But it is easy to reproduce:
1) in Json file just have \' (escaped apostrophe )  like "somekey":"some value \'some inter text\'"
2) use partialLoading with Json : 


   .config([
        '$translateProvider',
        '$translatePartialLoaderProvider',
     
        'LANG',
        'PATH',
        function ($translateProvider, $translatePartialLoaderProvider,  LANG, PATH) {
            $translateProvider.useLoader('$translatePartialLoader', {
                urlTemplate: PATH + 'i18n/{part}-{lang}.json',
                $http: {cache: true}
            });
            //$translateProvider.useSanitizeValueStrategy('sanitize');
            $translateProvider.preferredLanguage(LANG);

            $translatePartialLoaderProvider.addPart('blog');
            $translatePartialLoaderProvider.addPart('base');
        }])

Error: 
Uncaught TypeError: Cannot read property 'replace' of undefined
SyntaxError: Unexpected token '

**Comment by knalli** [comment]
@phuyem Please provide proper valid JSON. `Uncaught TypeError` are hard core JavaScript runtime errors, not related to angular-translate.

In that case, a valid JSON part would be `"somekey":"some value \\'some inter text\\'"`.
