### ISSUE TITLE
Accent word

### ISSUE THREAD

**Issue by furyscript** [angular-translate/angular-translate#1207]
I've a problem with translate accent words.

I've a .json file with all key => translation.

This is result when I translate a key:
`Men&#249;`
This is without filter translate:
`Menù`

Thanks.
I think the problem is `$translateProvider.useSanitizeValueStrategy('sanitize');` any solution?

**Comment by tspaeth** [comment]
Please have a look at the sanitize - issue #1101 - sounds like a well known "problem".

**Comment by knalli** [comment]
Duplicate #1101 -- see also solutions and workarounds.
