### ISSUE TITLE
$translateChangeSuccess event fired multiple times

### ISSUE THREAD

**Issue by Myrdivar** [angular-translate/angular-translate#1211]
Hi,

I'm experiencing a problem with this event. I have the language selection in the main controller of the app. Then I have various templates/controllers nested in the main controller with ng-view and the event is in one of them.

When I select the view for the first time and change the language the event fires correctly only one time. If I decide to select another view and then come back to the first one and change the language again now the event fires two times. If I repeat the process and change the language again it fires three times and so on.

Am I missing something?

**Comment by tspaeth** [comment]
Can you give us a small plunker with some code of yours regarding this issue? As the Event itself is only emitted when uselanguage is called internally, we don't know where the issue is without example usage code.

**Comment by Myrdivar** [comment]
Sure, here it is:

http://plnkr.co/edit/Z69W7dyPNMHBLJGMchCI?p=preview

Go to page two, change the language and you'll see only one alert. Select page one and then two again and when you change the Language you'll see two alerts.

**Comment by knalli** [comment]
You don't clean up your references.

http://plnkr.co/edit/I8ApZ0nCvXnOZH12Vm0R?p=preview

The missing point is `$scope.$on('$destroy', remove);` for removing the created listener. I've added the random id showing the different instances of the controller.

**Comment by chengwuchao** [comment]
Anyone  resolve this problem?
