### ISSUE TITLE
Minor: Syntax of license section in bower.json wrong.

### ISSUE THREAD

**Issue by twwwt** [angular-translate/angular-translate#1212]
Almost by chance we found that the [bower.json](https://github.com/angular-translate/angular-translate/blob/master/bower.json) has a license section that does not comply with the [Bower spec](https://github.com/bower/bower.json-spec#license), which causes an attempt to deploy the project as a Bower WebJar to fail, see webjars/webjars#1204.

**Comment by tspaeth** [comment]
so it should be "license" instead of "licenses" then and just be "MIT"?

**Comment by twwwt** [comment]
Yes.

**Comment by knalli** [comment]
Fixed here and in all bower repositories.

**Comment by knalli** [comment]
The change will be effective on next release.
