### ISSUE TITLE
Escaping of variable content documentation outdated

### ISSUE THREAD

**Issue by k-nut** [angular-translate/angular-translate#1213]
The [`Escaping of variable content`](http://angular-translate.github.io/docs/#/guide/19_security) documentation tries to explain the different escaping strategies by showing one example where XSS is possible and one where it is not thanks to escaping. The output in both cases is the exact same though: Escaped content. 
```
XSS possible!

Hello <span style='color:red;'>HACKED</span>!
```
Did the internal behaviour change and the documentation is outdated?

 This is especially important since angular-translate warns if not sanitization strategy was chosen and links to this page.

**Comment by knalli** [comment]
If you open the demo in plnkr, it works correctly. Looks like the embedded ones have an issue. :/

**Comment by knalli** [comment]
Found it. It will be fixed in next release.

Thank you.

**Comment by knalli** [comment]
Preview @ http://angular-translate.github.io/docs-canary/#/guide/19_security
