### ISSUE TITLE
Would it be possible to support the $templateCache?

### ISSUE THREAD

**Issue by twolff-iow** [angular-translate/angular-translate#1214]
Hi,

I have started to look into your translation tools and I am stunned as it almost supports everything what I need. I though stumble upon - what seems to be - one missing feature. My app is heavily component based and each component should have its own translations. I would like to load the translations of each components into the template cache and once it is requested from the partial loader to be fetched from the template cache instead of through an http call.

Did I missing anything? If not, would you be interested in me providing a pull request?

Thanks for this awesome tool,
  Tobias.

**Comment by tspaeth** [comment]
Did you read the http://angular-translate.github.io/docs/#/guide/12_asynchronous-loading chapter in our guide regarding cache stuff?

**Comment by twolff-iow** [comment]
Thanks so much pointing me to it. I managed to use the $templateCache via late binding with

$translateProvider.useLoaderCache('$templateCache').
