### ISSUE TITLE
question: Using static files loader data as argument for $translate().then()

### ISSUE THREAD

**Issue by nehero** [angular-translate/angular-translate#1215]
Is it possible to use the data I load via:

    $translateProvider.useStaticFilesLoader({
      prefix: 'locale-',
      suffix: '.json'
    });

to pass to 

    $translate(ARRAY_OF_TRANSLATIONS_OBJ).then(function(translations) {
			
    });

So I don't have to manually type out my whole list of translations into an array to pass to the function?

Or is there a better way?

Thanks

**Comment by knalli** [comment]
No, that are totally different processes. Also this is not the concept of angular-translate.

Why do you not want to use the built-in filters and directives? Why after all you are using angular-translate?

**Comment by nehero** [comment]
Oh I totally do! I use the built in filters for all of the views to display to users. 

However, I also have a feature that includes sending out an email with dynamic data, but prefixed by some of the titles in my translation file. There are quite a few so I was looking for a way to streamline the process instead of typing out a long array as the $translate() argument.

**Comment by knalli** [comment]
Okay. Nope, each string (which will be separated looked up using fallback, linking, etc.) must be provided.

**Comment by knalli** [comment]
I'll close this. Feel free to reply if anything is unclear.
