### ISSUE TITLE
Link in documentation (19_security) broken

### ISSUE THREAD

**Issue by k-nut** [angular-translate/angular-translate#1217]
The first link (entitled OWASP)  in the [security chapter](http://angular-translate.github.io/docs-canary/#/guide/19_security) of the documentation is broken. It should end with a `)` but does not. This seems to be due to the markdown formatting (it interprets the character as closing the link section and does not see it as part of the link any more). 

According to example 8 in [this stackoverflow answer](http://meta.stackexchange.com/a/13509) this should work but maybe ngdocs parses it incorrectly?

An alternative would be to either put the link at the end via `[1]` or to just use a plain html link.

I am not sure where this would need to be changed (`19_security.ngdoc` in each of the language folders?!) but would be willing to do this.

What do you think?

**Comment by knalli** [comment]
Thank you for pointing this out, we have overseen this. Please make a PR (based on canary), then we can look for this and even make a preview.

Just have a look for all 19*.ngdoc files in the repo (8 files in pattern `docs/content/guide/$lang/19_security.ngdoc`).

**Comment by knalli** [comment]
Solved via #1219
