### ISSUE TITLE
Dynamic key generates custom error handler call

### ISSUE THREAD

**Issue by sbondor** [angular-translate/angular-translate#1218]
If you use the translate filter like: {{ 'PRE.' + formData.name | translate }}, the custom error handler registered $translateProvider.useMissingTranslationHandler is called with parameter translationID = 'PRE'.

I don't think the error handler should be called at all in these cases.

**Comment by knalli** [comment]
Filters are invoked several times which is not under our control. In that case, it looks like there is a time of `formData.name` being not available. The filter does not know whether the translation id is complete or incomplete.
