### ISSUE TITLE
textpath translation on Safari

### ISSUE THREAD

**Issue by costasT** [angular-translate/angular-translate#1223]
I am using angular-translate to translate svg textpath content. It works fine on all browsers but on Safari, where I get the following error: 'undefined' is not an object (evaluating 'b[0].outerHTML.match'). Any idea why this happen or any workaround to make this work.

**Comment by tspaeth** [comment]
Well, maybe http://stackoverflow.com/questions/12592417/outerhtml-of-an-svg-element might help here

**Comment by knalli** [comment]
Link to #717 -- tried the filter already?

**Comment by knalli** [comment]
Closed due inactivity.
