### ISSUE TITLE
Publish 2.8.0 to NPM

### ISSUE THREAD

**Issue by mchambaud** [angular-translate/angular-translate#1224]
NPM repositories are still serving 2.7.2.

**NPM VERSIONS:**
* [angular-translate](https://www.npmjs.com/package/angular-translate) **2.8.0** 
* [angular-translate-loader-partial](https://www.npmjs.com/package/angular-translate-loader-partial) **2.7.2**
* [angular-translate-loader-static-files](https://www.npmjs.com/package/angular-translate-loader-static-files) **2.7.2**
* [angular-translate-loader-url](https://www.npmjs.com/package/angular-translate-loader-url) **2.7.2**
* [angular-translate-storage-cookie](https://www.npmjs.com/package/angular-translate-storage-cookie) **2.7.2**
* [angular-translate-storage-local](https://www.npmjs.com/package/angular-translate-storage-local) **2.7.2**
* [angular-translate-handler-log](https://www.npmjs.com/package/angular-translate-handler-log) **2.7.2**
* [angular-translate-interpolation-messageformat](https://www.npmjs.com/package/angular-translate-interpolation-messageformat) **2.7.2**

**Comment by knalli** [comment]
I can see 2.8 on npmjs.org. Perhaps a local caching issue?

**Comment by mchambaud** [comment]
I see 2.8.0 only for angular-translate repository. All other modules are still 2.7.2 event on the website, I've included links to help

**Comment by mchambaud** [comment]
Seems like I still have access to the repositories! I will update them for you.

**Comment by tspaeth** [comment]
@knalli is this deployment / upload already automated at some point in time? (didn't check)

**Comment by mchambaud** [comment]
I've updated them all.

**Comment by knalli** [comment]
Thank you. I hadn't really paid attention for the npm repositories for the "shadows". Simply missed :(

@tspaeth No, unfortunately not. We can add an publish-all script into the helpers (angular-translate-root) project.
