### ISSUE TITLE
Missing tranlations Event

### ISSUE THREAD

**Issue by trong291990** [angular-translate/angular-translate#1228]
Have any way to watch if translation is missing ?
For example : English : {  VIEW.EDIT : "Edit", VIEW.ADD : 'Add'}
But in Vietnames :        { VIEW.EDIT : "Sửa"} 
How to know we miss VIEW.ADD ?
Thanks

**Comment by tspaeth** [comment]
Well, that depends on your stack. You currently won't be able to detect if a translation key is missing in one of the languages in your stack, but it will tell you if it is totally missing in a stack (if included fallbacks).
For eventing / catching please read http://angular-translate.github.io/docs/#/guide/17_custom-error-handler

**Comment by knalli** [comment]
Closed due inactivity.
