### ISSUE TITLE
Single language with different asynchronous files

### ISSUE THREAD

**Issue by svikasg** [angular-translate/angular-translate#1231]
Good morning,

I was wondering if there is support or a work-around for supporting asynchronous loading of different files for the same language, the difference being the region. 

    app.config(['$translateProvider', function ($translateProvider) {
      $translateProvider
        .translations('en-us', {
            'COLOR': 'Color',
            'BEHAVIOR': 'Behavior'
         })
        .translations('en-uk', {
            'COLOR': 'Colour',
            'BEHAVIOR': 'Behaviour'
         })
        .preferredLanguage('en-us');
    }]);

The uses for this can help support differentiate language differences like these and also support using links ( for example, application home page links go to appropriate regions if there is inconsistent format ) .

Apologies if this is not framed in a good way. 

All inputs on this issue are welcome, including work-arounds.

**Comment by tspaeth** [comment]
Can't you do it with fallbacks? http://angular-translate.github.io/docs/#/guide/08_fallback-languages
Maybe in combination with something out of the language negotiation and/or partial loading...

**Comment by svikasg** [comment]
A particularly hacky way to try and get this to work is,

    $translateProvider
      .determinePreferredLanguage( )
      .registerAvailableLanguageKeys( [ 'en', 'uk', 'de' ], {
          us: 'us',
          uk: 'uk',
          de: 'de'
       } )
      .useStaticFilesLoader( {
         prefix: '/localization/i18n/',
         suffix: '.json'
       } )

You end up creating a dummy language 'uk', but for my particular case it would require changing the in-use en_uk to uk_uk  and also change service requests ( which bring in region specific data ).

I was hoping for a second level of linking for same language to load different files. 

But I shall try and follow your recommendation for fallback languages ( which I do have currently ).

**Comment by knalli** [comment]
Why are not using language codes like `en-us` and `en-uk` (or equivalents `en_US`, ...)?

**Comment by svikasg** [comment]
I've tried using the language codes en_US and en_GB. These still default to the same en.json file instead of the their individual files (us.json and gb.json).

**Comment by tspaeth** [comment]
Without an implementation example as Plunker or Fiddle, it'll be hard to see the definitve issue...

**Comment by svikasg** [comment]
Use of `determinePreferredLanguage()` here seemed to default fetching the en.json file for regions en_GB, en_US. I had the app to use `$translate.use( langKey)` on load based on current locale and it fetches appropriate JSON files now. 

As for the use of different JSON files for same language based on `determinePreferredLanguage()`, I will have to look a little further to see what wrong I was doing ( or my thinking of `determinePreferredLanguage` and its usage for same language ) or if its really an issue.

**Comment by knalli** [comment]
Okay, please make an update. Until then, I'll close here.
