### ISSUE TITLE
move the configuration from .config()

### ISSUE THREAD

**Issue by HoplaGeiss** [angular-translate/angular-translate#1233]
I would like to avoid to have all my translation directly in my `app.js` file.
Ideally I would like something like this:

```
      $translateProvider
      .useSanitizeValueStrategy(null)
      .translations('en', translationService.en)
      .translations('fr', translationService.fr)
      .preferredLanguage('en')
      .registerAvailableLanguageKeys(['fr'])
      .determinePreferredLanguage()
      .fallbackLanguage('en');
```

And than define objects for each languagues in another file.
Is it possible?

**Comment by tspaeth** [comment]
Have you read the docs? http://angular-translate.github.io/docs/#/guide

**Comment by HoplaGeiss** [comment]
I got a little confused with the docs. 
I didn't look in asynchronous loading.
Thanks
