### ISSUE TITLE
Encoding .json files

### ISSUE THREAD

**Issue by khwerhahn** [angular-translate/angular-translate#1236]
Hi,

I'm using the useStaticFilesLoader to load my language files. In the de_DE.json are some special characters which are not displayed correctly. 

I have set ```<meta charset="utf-8">``` in the header and used Sublime to save the json file as UTF-8. Still the error occurs.

Whats wrong?

EDIT:
In the normal text its fine, just in the placeholder bit in input fields its shown incorrectly

**Comment by tspaeth** [comment]
Could you put up a short example with plunker?
But I think it's due to $sce / sanitation - please see http://angular-translate.github.io/docs/#/guide/19_security

**Comment by khwerhahn** [comment]
Thx for the answer. The strange thing is, that the Umlaute work everywhere else perfectly fine. Its just the inputs placeholder don't seem to work:

```<input type="text" name="position" id="position" placeholder="{{ 'SIGNUPFORM.INPUTS.POSITION.PLACEHOLDER' | translate }}" ng-model="position" />'' ```

A "normal" paragraph for example works without a problem:
```<p><translation translate="ANALYTICS.INFOSTATE.THIRDPARAGRAPH"></translation></p>```

**Comment by knalli** [comment]
As @tspaeth already mentioned: Unless your issue is covered by $sce (see #1101), you should at least provide a demo.
