### ISSUE TITLE
Question: overriding values after REST Call

### ISSUE THREAD

**Issue by unsaluto** [angular-translate/angular-translate#1240]
Hi,

is there any way to change some values in a translation table that was previously loaded via static file loader?

```javascript
$translateProvider.useStaticFilesLoader({
    	prefix: 'i18n/locale-', 
    	suffix: '.json'
});
```

Specifically I need to load a "default" set of language tables at .config time (and this is working perfectly via above call), but then another call to a REST API may return some values I want to use to override values of these tables. This second call fires later than .config time, say at .run time or even later on.

I tried to use a custom loader that returns the "overriding values" , but that does not seem to be used in conjunction with the static file loader (while the REST Call is running, I see no values at all, not even the placeholders).

Thank you,

**Comment by knalli** [comment]
Yes. You can use your [own loader](http://angular-translate.github.io/docs/#/guide/13_custom-loaders) or specifiy special options (i.e. `prefix: '…', suffix: '…', $http: {transformResponse: …}` (see [here](https://code.angularjs.org/1.4.7/docs/api/ng/service/$http#overriding-the-default-transformations-per-request)).

**Comment by unsaluto** [comment]
About the own loader, I'd like to use it but I also want my default values (in .json files) to be loaded immediately, without waiting for the REST call response.
About the second method, this is interesting, but how can I use it to override the translation tables I have (say en_GB, it_IT, pl_PL) ?

**Comment by knalli** [comment]
Making this clear: That is only a loader providing data (translations) for one given language. It does not override anything.

> […] I'd like to use it but I also want my default values (in .json files) to be loaded immediately, without waiting for the REST call response.

I don't get this. You want to load data, but do not wait?? What are you trying to do? If you have an external JSON file, it must be loaded asynchronously (and you have to wait).

**Comment by unsaluto** [comment]
Currently I have "default" data stored in JSON file, I'm able to read it and this is pretty awesome. BUT: upon a REST call that I'd fire later, some of the values should be overridden.

Example:

At the beginning (.conf) I load the following JSON files via static files loader:

i18n/locale-en_GB.json
```javascript
{
    "market.marketplace.title": "Marketplace",
     "market.marketplace.descr": "Here is a description",
     "market.available.items": "Available items"
}
```
i18n/locale-it_IT.json
```javascript
{
    "market.marketplace.title": "Marketplace",
     "market.marketplace.descr": "Ecco una descrizione",
     "market.available.items": "Oggetti disponibili"
}
```
Very nice, values are loaded IMMEDIATELY. And I want to keep things like this.
Now, the rest call returns this data:

REST Call response data:
```javascript
{"en_GB", 
        {                   
           "market.marketplace.title": "ENGLISHTITLE",
           "market.marketplace.descr": "ENGLISHDESCR"
        },
    },
    {"it_IT", 
       {
           "market.marketplace.title": "ITALIANTITLE",
           "market.marketplace.descr": "ITALIANDESCR"               
       }
    }
```

What I want is that translation tables values get overridden. So my translation tables should look like this now:

(English table)
```javascript
{
    "market.marketplace.title": "ENGLISHTITLE",
     "market.marketplace.descr": "ENGLISHDESCR",
     "market.available.items": "Available items"
}
```
(italian table)
```javascript
{
    "market.marketplace.title": "ITALIANTITLE",
     "market.marketplace.descr": "ITALIANDESCR",
     "market.available.items": "Oggetti disponibili"
}
```

I managed to create a custom loader that loads the new values, but I can't have this custom loader work in conjunction with the static files loader (which I want to keep, if possible).

**Comment by knalli** [comment]
One file is one language, there will be no updates.

Exceptions:

* You use the partial loader.
* You use the concept of "fallback language".
* You invoke `$translate.refresh()` will be reload everything (but it will probably the same old ones again).

**Comment by unsaluto** [comment]
So that's not possible. Got it.

**Comment by tspaeth** [comment]
Just wondering: What is the usecase in overriding translations?

**Comment by unsaluto** [comment]
People may want to see labels as they prefer. It's a configuration matter. So if I (developer) say that the title of a page should be "Marketplace" in English and "Marketplace" in Italian, an italian user may want to change the italian label in "Mercato", and leave the english label as it was. This configuration will be applied only for THIS user, while all other users will keep seeing "Marketplace" in both languages (unless they, in turn, change the labels as they want). So the REST call is used to get the user's language configuration.
