### ISSUE TITLE
How to use a translation in an alt-Attribute of an img tag?

### ISSUE THREAD

**Issue by myonara** [angular-translate/angular-translate#1242]
I tried the following:
```
<img src='...' alt="{{'NS_ELEMENTS.HELP' | translate}}" />
```
is not working and an ng-alt is not existing.
I've ended up with getElementById and manipulating the dom directly,
but this isn't working, when the language is changed dynamically.

Any Help?
Thanks in advance

**Comment by tspaeth** [comment]
Well it works in general?

See here: http://plnkr.co/edit/PFn2DAsR3D6Z52gz7lbn?p=preview

**Comment by myonara** [comment]
You're right. I made a mistake in the language files. Now it is working.
