### ISSUE TITLE
Question - Get Translation Value For Language

### ISSUE THREAD

**Issue by nruhe** [angular-translate/angular-translate#1244]
Hello. I have a need to get some labels in alternative languages than what is currently set as the active language for the app. Is there a way to pass a label and language key and be able to get the translated label for that language regardless of current language settings?

E.g.

Labels en: {
  hello_world: 'Hello World'
}

Labels de:{
  hello_world: 'Hallo Welt'
}

And I want to be able to go $translate('hello_world', 'en') and get "Hello World" even if the current language is set to German.

Thanks!

**Comment by knalli** [comment]
Please see #500 -- this is at the moment not possible.
