### ISSUE TITLE
angular-translate-loader-static-files 

### ISSUE THREAD

**Issue by pelallemant** [angular-translate/angular-translate#1245]
Hi,

The plunker examples which are on the Readme.md doesn't work : https://github.com/angular-translate/angular-translate/wiki/Asynchronous-loading 

Best regards,

PE

**Comment by tspaeth** [comment]
Please have a look at the notice on https://github.com/angular-translate/angular-translate/wiki - this wiki is targeting angular-translate 1.x and is just kept in for backwards documentation.
