### ISSUE TITLE
Hiding keys when not translated

### ISSUE THREAD

**Issue by leye0** [angular-translate/angular-translate#1246]
After having tried different solutions to avoid FOUC, I decided to change the linking of the translate directive so that it just hides the element in the preLink and show it in the postLink function.

    compile: function compile(tElement, tAttr) {
        return {
            pre: function (scope, iElement, iAttr) {
                iElement.css('opacity', 0);
            },
            post: function (scope, iElement, iAttr) {
                [...]
                var applyTranslation = function (value, scope, successful, translateAttr) {
                  if (translateAttr === 'translate') {
                    // default translate into innerHTML
                    if (!successful && typeof scope.defaultText !== 'undefined') {
                      value = scope.defaultText;
                    }
                    iElement.html(scope.preText + value + scope.postText);
                    iElement.css('opacity', '1');
                    [...]

Isn't that simpler than any cloaking approach? I think that a lot of users just want to hide their resources when they are not translated yet.

**Comment by knalli** [comment]
Please have a look at our a Guide about [FOUC](http://angular-translate.github.io/docs/#/guide/12_asynchronous-loading#asynchronous-loading_fouc---flash-of-untranslated-content), as well the [translate-cloak directive](http://angular-translate.github.io/docs/#/api/pascalprecht.translate.directive:translateCloak).

**Comment by leye0** [comment]
Using this attribute made my page crash. I have this version:  *
angular-translate - v2.6.0 - 2015-02-08 *
Adding translate-cloak attribute (replacing translate with translate-cloak)
prevents the resource from being translated, so I guess I'm using the wrong
version?

For other propositions to prevent FOUCs, I prefer my solution of using
Angular's preLink and postLink feature. css(opacity, 0), then in
applyTranslation: css(opacity, 1). Almost just two lines.

**Comment by knalli** [comment]
Following remarks:

* Crash?! We would like to see this!
* The current release is 2.8.1. Please consider an update. Also 2.6 has followed patch releases...
* No, a css hack in the main directive is not a proper solution. Sorry. ;)

**Comment by leye0** [comment]
- Oops, I should have removed this phrase. Actually, It just prevents the
translation, but it doesn't crash.
- Ok, I will update. My version contains translate-cloak, but maybe I'm
experiencing other bugs, then.
- :P I'm still curious to know who really wants to see this element during
the time it is not translated. I'll check your code to see how you are
hiding the item without just affecting the style.

**Comment by tspaeth** [comment]
In general, the angular-module can't solve on issue on the FOUC you probably mean:

If the HTML file is loading and the browser starts rendering it - depending on the flow and script integration, it might show the "raw html" right upfront.

The only known solution to me is to set the body element to style="display: none;" and then in an onload event reset this style. This is rather hacky, but seems to be the only cross-browser reliable way to reach your goal if you really need it.

**Comment by knalli** [comment]
Take also into account: `ng-cloak` and `translate-cloak`.

**Comment by leye0** [comment]
The issue with the raw HTML showing with bindings is nicely solved using
ng-cloak on the ng-app DOM element. The only issue I had is with my
translation keys showing. And my final question was about why
angular-translate was not just hiding the DOM element in preLink and
showing it in applyTranslation using the opacity css property. I'm starting
to wonder if placing the translation in an attribute would solve my issue,
though the "collapsing" effect of empty DOM elements would impact the
layout much more than just applying opacity 0 -> 1, which doesn't affect
the layout.
