### ISSUE TITLE
Error thrown due to angular-translate-storage-local dependency on angular-cookies@~1.5.0

### ISSUE THREAD

**Issue by asafse** [angular-translate/angular-translate#1247]
I'm using angular-translate and wanted to start using the storage solutions.
When trying to install 'angular-translate-storage-local', the dependency requires the installation of 'angular-translate-storage-cookie' as well which throws the below error:
"err  No version match found for npm:angular-cookies@~1.5.0"
This make senece as version 1.5.0 is still in beta...
I'm installing the module using JSPM:
sudo jspm install npm:angular-translate-storage-local.
What am i missing?
Is there an issue with the latest version if this module?
Thanks in advance,
Asaf
![screenshot1](https://cloud.githubusercontent.com/assets/6702555/10350866/20c53ab4-6d4f-11e5-95f5-2a351c3eafbd.jpg)
![screenshot2](https://cloud.githubusercontent.com/assets/6702555/10350867/20ca0120-6d4f-11e5-993b-bcb71f7a233c.jpg)

**Comment by knalli** [comment]
There is no release _angular-cookies@~1.5.0_ available. 

The repository [defines in current 2.8.1](https://github.com/angular-translate/bower-angular-translate-storage-cookie/blob/2.8.1/package.json) a range *including* 1.5 which is not correct. But as no stable release is available, that will automatically fallback to stable (at this moment of writing 1.4.7).

Perhaps jspm is not treating numbers as semver? Why after all you are prefer this to npm or bower?

**Comment by asafse** [comment]
Thanks for the quick response.
I'm managing all of my modules over JSPM - working with bower, github and npm.
I tried running 'sudo jspm install bower:angular-translate-storage-local' and got same error.
Is there a workaround?

**Comment by knalli** [comment]
```
$ node -v
v0.12.7
$ npm -v
3.3.5
$ npm install angular-translate-storage-cookie
/private/tmp/i
└─┬ angular-translate-storage-cookie@2.8.1
  ├── angular-cookies@1.4.7
  └── angular-translate@2.8.1
```

```
angular-translate-storage-cookie#2.8.1 bower_components/angular-translate-storage-cookie
├── angular-cookies#1.4.7
└── angular-translate#2.8.1

angular-translate#2.8.1 bower_components/angular-translate
└── angular#1.4.7

angular-cookies#1.4.7 bower_components/angular-cookies
└── angular#1.4.7

angular#1.4.7 bower_components/angular
```

**Comment by knalli** [comment]
> Is there a workaround?

Well, at least I can say: Standard npm and bower works. I don't know jspm.

**Comment by knalli** [comment]
I've checked out `jspm` a little bit.. I cannot see your generated files when using standard command `jspm install angular-translate-storage-cookie`.

With explicit `npm', it will fails.

```
$ jspm install npm:angular-translate-storage-cookie

warn Running jspm globally, it is advisable to locally install jspm via npm install jspm --save-dev.
     Looking up npm:angular-translate-storage-cookie
     Creating registry cache...
     Looking up npm:angular-translate
     Looking up npm:angular-cookies

err  Installing npm:angular-translate-storage-cookie@2.8.1, no version match for npm:angular-cookies@~1.5.0
```

Anyway, not an issue for us.

**Comment by knalli** [comment]
Well, I would say that's it: https://github.com/jspm/jspm-cli/issues/1172

**Comment by asafse** [comment]
Thank you so much knalli!
I've omitted the 'npm' and let JSPM install lead the way - it solved it.
