### ISSUE TITLE
Detecting domain and switch language

### ISSUE THREAD

**Issue by khwerhahn** [angular-translate/angular-translate#1250]
Hi,

is there a preferred way of detecting the domain (i.e. ".com" or ".de") and switch the language accordingly?

```javascript
angular.module('angularApp')
.config(['$translateProvider', function ($translateProvider) {
	$translateProvider.usePostCompiling(true);
	$translateProvider.useStaticFilesLoader({
	    prefix: 'i18n/locale-',
	    suffix: '.json'
	});
	$translateProvider.preferredLanguage('de_DE');
}]);
```

**Comment by knalli** [comment]
Please have a look at the documentation.

You will [find](https://angular-translate.github.io/docs/#/api/pascalprecht.translate.$translateProvider#methods_determinepreferredlanguage) `$translateProvider.determinePreferredLanguage(fn)` which can be configured with a custom resolver function.
