### ISSUE TITLE
difference between translate filter and directive interpolation with messageformat

### ISSUE THREAD

**Issue by hugsbrugs** [angular-translate/angular-translate#1251]
Hi !

using angular-translate v2.7.2, I can only use directive declaration to translate this chain : 
```javascript
"TOTAL_WEBPAGES" : "{TOTAL, plural, one {one page saved.} other {# pages saved.}}",
```

```javascript
<span
    translate="TOTAL_WEBPAGES"
    translate-values="{ TOTAL: website.count_webpage }"
    translate-interpolation="messageformat"></span>
```

When trying to use filter declaration, I always get the singular translation. I feel like scope variable website.count_webpage can't be accessed. In docs, I can only find a hard-coded example for TOTAL value. Is there another way to write it to make it works ?

```javascript
{{ 'TOTAL_WEBPAGES' | translate:"{ TOTAL: website.count_webpage }":"messageformat" }}
```

Thanks for your suggestions !

**Comment by knalli** [comment]
Since AJS 1.3, must have to apply any arguments to a filter function (even the scope). A filter does not have access to the scope any more.
