### ISSUE TITLE
Default value of Angular Material's md-select is not translated

### ISSUE THREAD

**Issue by doppio** [angular-translate/angular-translate#1253]
When using the ```<md-select>``` directive from Angular Material, the translations appear correctly translated in the list once you click on the dropdown widget. However, the first value that is selected by default (in my case, from a data-binding) is not correctly translated until the md-select is clicked upon, at which point it becomes updated.

**Comment by knalli** [comment]
@doppio  Please provide a running demo/sample.

**Comment by tspaeth** [comment]
friendly reminder: @doppio any update on this?

**Comment by knalli** [comment]
Closed due inactivity.

**Comment by S8nsick66** [comment]
I did some testing, maybe the next googler will save some time with this info.

Doesn't work (the label is not translated):

```javascript
<label translate>My label</label>
<label><translate>My label</translate></label>
<label>{{ 'My label' | translate }}</label>
```

Works but is deprecated and doesn't look as nice:
```javascript
<md-select-label>{{ 'My label' | translate }}</md-select-label>
```

Works and looks nice but is without a label element:
```javascript
<md-input-container>
  <md-select ng-model="selectedState" placeholder="{{ 'My label' | translate }}">
```

Plunker: https://embed.plnkr.co/aRD0aTljBc7846suJNGC/

**Comment by rhclayto** [comment]
Check out this issue in Angular Material's queue: https://github.com/angular/material/issues/8781

i solved this problem with a little hint from DevVersion over there.
