### ISSUE TITLE
$translate.use() does not return fallback language

### ISSUE THREAD

**Issue by elmalto** [angular-translate/angular-translate#1255]
According to the docs and the issue trackers, $translate.use() is supposed to return the current language.

But if I use a language, that is not defined by translations, it returns the "wrong" language and not the fallback:
```
$translate.use(language).then(function(){
  console.log("using " + $translate.use());
})
```

would print whatever I put in language. Even "xxxyyyzzzz" (which I clearly haven't defined). Is there a way to check if a language has been defined?

**Comment by wtreur** [comment]
I'm having the same issue. I've added an isolated test in a local copy of `translate.spec.js` to confirm:

    describe('$translate#use() with language negotiation and fallback', function () {
      
      beforeEach(module('pascalprecht.translate', function ($translateProvider) {
          $translateProvider
              .translations('en', { 'WELCOME': "Welcome!"})
              .translations('nl', { 'WELCOME': 'Welkom!' })
              .fallbackLanguage('en')
              .determinePreferredLanguage(function () {
                  // mocking - copied from translate.determineLocale.spec.js
                  var nav = {
                      language: 'de'
                  };
                  return ((
                      nav.language ||
                      nav.browserLanguage ||
                      nav.systemLanguage ||
                      nav.userLanguage
                      ) || '').split('-').join('_');
              });
      }));

      var $translate;

      beforeEach(inject(function (_$translate_) {
          $translate = _$translate_;
      }));

      it('should use the fallback language when an unavailable language is provided', function() {
          expect($translate.use()).toBe('en');
      });
    });

Result from `grunt test`

    Chrome 46.0.2490 (Mac OS X 10.11.0) pascalprecht.translate $translate#use() with language negotiation and fallback should use the fallback language when an unavailable language is provided FAILED
     	Expected 'de' to be 'en'.
     	    at Object.<anonymous> (/Users/wtreur/Development/angular-translate/source/test/unit/service/translate.spec.js:567:36)
    Chrome 46.0.2490 (Mac OS X 10.11.0): Executed 391 of 391 (1 FAILED) (2.155 secs / 2.005 secs)
    Warning: Task "karma:unit" failed. Use --force to continue.

**Comment by wtreur** [comment]
By the way, using the following setup for `$translationProvider` the test will pass:

    $translateProvider
      .translations('en', { 'WELCOME': "Welcome!"})
      .translations('nl', { 'WELCOME': 'Welkom!' })
      .fallbackLanguage('en')
      .preferredLanguage('de'); // Manually setting preferred language to 'de' instead of negotiation

**Comment by tspaeth** [comment]
@elmalto What is a defined language if you're using partial and async loaders? We don't have a definitive setting telling the module what is a valid and "accepted" language. If the loader is able to find a translation-json on async calls, it's considered valid. And even if you are missing the async-file for some reason - it might still be a valid language for your overall application.

**Comment by wtreur** [comment]
@tspaeth I see your point and now I come to think of it, I think the issue I described in the test is perhaps related, but not the same. What do you think?

**Comment by tspaeth** [comment]
One thing to consider here is: Using a fallback-stack of languages won't change the current language being "used" - It might sound a bit irritating, but that's the way it was introduced. Example:

You're having EN, DE, FR, ES in your application defined.
Now, you're viewing a page having EN as the "current" language. And the fallback for the current setup is configured as DE - FR - ES. 
In case, you're missing some translations in EN, it tries to look them up (in that order) in DE, FR, ES. In case it finds one key only in ES -> it's taken from there and presented.
BUT - in that case, the use - function won't change to ES.

**Comment by wtreur** [comment]
I see! And since you can either provide all the translations during the configuration or using lazy loading you can't actually 'know' beforehand what language is actually available with `$translate.use()` as well.

(Perhaps this bit below needs to be asked at stackoverflow)
So if I understand correctly, during runtime, there is no way to determine if a negotiated language using `determinePreferredLanguage()` is actually available. Given your example I figured `'available language' == At least 1 translation for that language is available`

**Comment by wtreur** [comment]
As to answer the question myself, using the setup below I am able to accomplish the same thing as using `.fallbackLanguage('en')` and receiving that language with `$translate.use()`. I'm not sure if it is supposed to be used like this, but it works for me and perhaps is suitable for you as well @elmalto

    $translateProvider
        .translations('en', { 'WELCOME': "Welcome!"})
        .translations('nl', { 'WELCOME': 'Welkom!' })
        .registerAvailableLanguageKeys(['en', 'nl'], {
            'en_*': 'en',
            'nl_*': 'nl',
            '*': 'en'
        })
        .determinePreferredLanguage()

Now, when the browser has `de_DE` as language setting `$translate.use()` will return `en` while `nl_NL` as browser language will still result in `nl`

**Comment by knalli** [comment]
> So if I understand correctly, during runtime, there is no way to determine if a negotiated language using determinePreferredLanguage() is actually available. 

Correct. The term "preferred language" means the language is only.. well.. preferred.

Note: For v3, I'm planning to uniform the terms of "used language" and "preferred language" letting users less irritations. Input is welcome! #995
