### ISSUE TITLE
Problem with ASP.NET MVC Bundling

### ISSUE THREAD

**Issue by emaish** [angular-translate/angular-translate#1256]
Module 'pascalprecht.translate' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

the problem solved when i disabled the bundling optimiazation in my MVC website

**Comment by knalli** [comment]
I have actually no clue what about you are talking. We don't use ASP.NET, but I'm sure that the language will not have such a feature. Perhaps you tool chain is the problem.. but not this plugin.

**Comment by emaish** [comment]
I will be more specific, the ASP.NET MVC bundling is just a tool for CSS and JS minification, when i enable bundling i got this error in my AngilarJS application

Module 'pascalprecht.translate' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

i faced this problem before in my AngularJS controller, the reason is common with JS Minifiers, Minifiers will shorten identifiers where possible, they won't modify any string literals in your code. The idea is to provide the dependency names as a separate array of strings which will survive the minification process. My favorite approach to pass this array to the constructor function is through the $inject property.

**Comment by tspaeth** [comment]
But - how can we help or support here in any issues regarding angular-translate itself?

**Comment by emaish** [comment]
I'm not sure, maybe the plugin should use dependency as mentioned in my previous comment in its inner code.

**Comment by emaish** [comment]
Dear,

i was using the plugin file that is already minified "angular-translate-min.js" i replaced it with the original one because some people reported that minification of a minified file may cause issues , and the problem is gone, and the plugin is working fine.

But, after adding "storage-cookie.js" to my application i faced a new problem
```javascript
Unknown provider: nProvider <- n <- $translateCookieStorage <- $translate
```
The problem solved by applying the concept i mentioned in previous comment
> Provide the dependency names as a separate array of strings which will survive the minification process

i changed the way the factory is defined in "storage-cookie.js" file.
 
```javascript
angular.module('pascalprecht.translate')

/**
 * @ngdoc object
 * @name pascalprecht.translate.$translateCookieStorage
 * @requires $cookieStore
 *
 * @description
 * Abstraction layer for cookieStore. This service is used when telling angular-translate
 * to use cookieStore as storage.
 *
 */
  .factory('$translateCookieStorage', ['$cookieStore', function ($cookieStore) {

      'use strict';

      var $translateCookieStorage = {

          /**
           * @ngdoc function
           * @name pascalprecht.translate.$translateCookieStorage#get
           * @methodOf pascalprecht.translate.$translateCookieStorage
           *
           * @description
           * Returns an item from cookieStorage by given name.
           *
           * @param {string} name Item name
           * @return {string} Value of item name
           */
          get: function (name) {
              return $cookieStore.get(name);
          },

          /**
           * @ngdoc function
           * @name pascalprecht.translate.$translateCookieStorage#set
           * @methodOf pascalprecht.translate.$translateCookieStorage
           *
           * @description
           * Sets an item in cookieStorage by given name.
           *
           * @deprecated use #put
           *
           * @param {string} name Item name
           * @param {string} value Item value
           */
          set: function (name, value) {
              $cookieStore.put(name, value);
          },

          /**
           * @ngdoc function
           * @name pascalprecht.translate.$translateCookieStorage#put
           * @methodOf pascalprecht.translate.$translateCookieStorage
           *
           * @description
           * Sets an item in cookieStorage by given name.
           *
           * @param {string} name Item name
           * @param {string} value Item value
           */
          put: function (name, value) {
              $cookieStore.put(name, value);
          }
      };

      return $translateCookieStorage;
  }]);

//$translateCookieStorageFactory.displayName = '$translateCookieStorage';
```

I think this way of definition should be used in every where in the plugin code.

What do you think ?

**Comment by knalli** [comment]
We use [ng-annotate](https://github.com/olov/ng-annotate) in the build chain to avoid such  boiler code. You can look into our Gruntfile.

I think we are done, I'll close in forward.
