### ISSUE TITLE
Angular injector error when compiling with Browserify

### ISSUE THREAD

**Issue by suomiton** [angular-translate/angular-translate#1260]
Our application scripts are mainly built with Browserify but we still use RequireJS on some other scripts. But our Angular application is fully compiled with Browserify. Yesterday I tried to add Angular-translate module to out Angular app but I keep getting the following error

![module-error](https://cloud.githubusercontent.com/assets/2194945/10475996/6f4d3a6c-7252-11e5-95c3-3e98fc6a2430.jpg)

Currently we are using Angular v1.4.7 and Angular translate v2.8.1. 
Here's how our application dependencies are stacked and how the application is instantiated

![dependencies](https://cloud.githubusercontent.com/assets/2194945/10476025/b6e05440-7252-11e5-8e1a-7f42ba97a089.jpg)

![app-instantiation](https://cloud.githubusercontent.com/assets/2194945/10476027/b9f2d5b8-7252-11e5-8b5f-f55fd20c2a8c.jpg)

I have tried to use older Angular versions and different script ordering but nothing helps. Any ideas what might be causing this issue?

**Comment by knalli** [comment]
I cannot see RequireJS in the sample code. Said this, as long as this processed by browserify and you have ensured `angular-translate.js` is already loaded, the sample should work. However, I cannot see you are loading actually the code? Including a module by string is not loading a module (script(s) file).

**Comment by knalli** [comment]
It does not look like an issue for angular-translate, but a configuration problem in your app.

Feel free to reply, but I will close this in forward.

**Comment by suomiton** [comment]
Now I had the time to try this again and figured out it was the RequireJS and Angular-translate that had some conflicts. When I removed RequireJS from my project everything worked fine. Although I don't understand why Angular-Translate and RequireJS does not work when loaded separately. 

Here a screenshot on how scripts are loaded 
![scripts](https://cloud.githubusercontent.com/assets/2194945/10633974/26d7d1ac-77f7-11e5-9b0d-3f1a783ca8e1.png)

And the ***Deps.js file is being compiled with Browserify but source looks like this 
![scripts](https://cloud.githubusercontent.com/assets/2194945/10634025/853ab9bc-77f7-11e5-918f-bc451d073f61.png)

If I remove Angular-Translate or RequireJS everything works. Why is it that those scripts can't co-exist on same page?

**Comment by suomiton** [comment]
Also noticed that if I load require.js dependency after the Angular components the site works. Though it might raise some other issues.
