### ISSUE TITLE
translate-cloak with partialLoader

### ISSUE THREAD

**Issue by th3nate** [angular-translate/angular-translate#1261]
hi guys,
just wanted to find out if someone tried using the translate-cloak with partialLoader.
it doesn't seem to work and i think that's because various controllers are used for loading parts of the translation when they load therefore the cloak mechanism fails.

i would be happy to get your opinion on how to efficiently hide async loaded translated content

cheers

**Comment by knalli** [comment]
@th3nate  Please elaborate your issue a bit more, especially a demo would be helpful. Have you already tried the optional argument of the cloak directive?

http://angular-translate.github.io/docs/#/api/pascalprecht.translate.directive:translateCloak

**Comment by th3nate** [comment]
cant really provide a demo because im working remotely via secured VPN.
as i said, i am using translate-cloak but the translate key still flickers before loading.
im partially loading the relevant translation inside the controller and it takes a 1-2 sec until the key hides itself and the actual value shows properly

**Comment by knalli** [comment]
@th3nate  We don't want to see your full app, but a simple test/use case what you are doing actually.

**Comment by th3nate** [comment]
its a bit hard to set up a working demo but ill try to explain my best.

firs of all the translation loads inside a directive's template:

```javascript
        var directive = {
            restrict:         'EA',
            replace:          true,
            scope:            {},
            controller:       LoaderController,
            bindToController: true,
            controllerAs:     'vm',
            template:         '<div class="welcome-overlay">\
                                    <div class="welcome-loader f-s-22 text-center" id="loader">\
                                        <span class="block" \
                                        translate-cloak \
                                        translate="Loader.Text.Welcome" \
                                        data-ng-if="vm.firstLogin === false || vm.hideText === false"><span>\
                                    </div>\
                                    <div class="welcome-loader-time f-s-22 text-center" \
                                    data-ng-if="vm.firstLogin === false || vm.hideText === false">\
                                        <span>{{vm.LastLoginTimeSO}}</span>\
                                    </div>\
                                </div>'
        };
```
And inside LoaderController im calling for the partial translation:
```javascript
$translatePartialLoader.addPart('SO_GetLoaderData', directoryName);
$translate.use('en');
$translate.refresh();
```

**Comment by knalli** [comment]
I will close this. As I already said months ago, you should be aware of optional argument of the directive (which you aren't using).

To be clear: If you enable `translate-cloak`, it will be only apply the cloak unless translations are loaded. As soon as the first translation is being available, the cloak will be removed. Unless you specify a specific condition.
