### ISSUE TITLE
CONTRIBUTING.md instruction `npm run clean-test-scopes` doesn't work

### ISSUE THREAD

**Issue by moshen** [angular-translate/angular-translate#1266]
[CONTRIBUTING.md](https://github.com/angular-translate/angular-translate/blob/453a0292d8af76133a44451b295e4470467760b9/CONTRIBUTING.md#contributingsubmitting-changes) specifies that if `npm run test-scopes` fails with a "dependency resolution issue", you should `npm run clean-test-scopes` and try again.

However, there is no script specified for `clean-test-scopes`.

**Comment by knalli** [comment]
Oops. Thank you.

The line script `"clean-test-scopes": "for f in test_scopes/*; do (cd $f; rm -rf bower_components); done",`  is clearly missing. :(

**Comment by knalli** [comment]
Fix landed in c22c727, will be part of the next regular release.
