### ISSUE TITLE
angular-translate-storage-local and requirejs leads to an error

### ISSUE THREAD

**Issue by messyOne** [angular-translate/angular-translate#1267]
Error I get: `Error: [$injector:unpr] Unknown provider: $translateCookieStorageProvider <- $translateCookieStorage <- $translateLocalStorage <- $translate`

My `requirejs.config`:

    requirejs.config({
    	shim: {
		    angular: {
			    exports: 'angular'
		    },
    		ngTranslateLoader: ['ngTranslate'],
    		ngTranslateLocalStorage: ['ngTranslate']
    	},
    
    	paths: {
    		ngTranslate: '../../vendor/angular-translate/angular-translate',
    		ngTranslateLoader: '../../vendor/angular-translate-loader-static-files/angular-translate-loader-static-files',
    		ngTranslateLocalStorage: '../../vendor/angular-translate-storage-local/angular-translate-storage-local'
    	}
    });

My `module`:

    define(function(require) {
    	require('ngTranslate');
    	require('ngTranslateLocalStorage');
    	require('ngTranslateLoader');
    
    	var angular = require('angular');
    
    	var app = angular.module('app', [
    		'pascalprecht.translate'
    	])
    		.config([$translateProvider', function ($translateProvider) {
    			$translateProvider
    				.useStaticFilesLoader({
    					prefix: '/language/',
    					suffix: '.json'
    				})
    				.preferredLanguage('en-DK')
    				.useSanitizeValueStrategy('escape')
    				.useLocalStorage();
    		}]);
    });

Why does the `vendor/angular-translate-storage-local` not work, but the `angular-translate-loader-static-files` plugin works well?

**Comment by knalli** [comment]
That has nothing to do with RequireJS.

@messyOne I would advice reading carefully both the module dependencies as well as the error message.

Both in [bower.json](https://github.com/angular-translate/bower-angular-translate-storage-local/blob/2.8.1/bower.json) and [package.json](https://github.com/angular-translate/bower-angular-translate-storage-local/blob/2.8.1/package.json) defines _angular-translate-storage-cookie_ as a dependency. And the error message is clearly yelling a missing.. yeah, _$translateCookieStorageProvider_. Said this, one one: At least with 2.x, the dependency to the cookies will stay.
