### ISSUE TITLE
Translate filter combined with staticFilesLoader and statefulFilter

### ISSUE THREAD

**Issue by mattlavallee** [angular-translate/angular-translate#1268]
I am trying to setup angular-translate with the staticFilesLoader.  The staticFilesLoader alone works very well, however if I also try to set statefulFilter to false as well, the translations do not happen.

A snippet of my setup is as follows:

JSON File (en_US.json):
```
{
   "TestString": "hello world"
}
```

Configuration:
```
angular.module('app', []).config( function( $translateProvider ) {
    $translateProvider
        .useStaticFilesLoader( {
            prefix: '/languages/',
            suffix: '.json'
        } )
        .determinePreferredLanguage()
        //set the fallback language to english
        .fallbackLanguage( 'en_US' )
        //evaluate filters only once
        .statefulFilter( false )
        .useSanitizeValueStrategy( 'sanitize' );
} );
```

Sample Template:
```
<div>{{ 'TestString' | translate }}</div>
```

It seems that the filter is applied initially and then the json file is pulled in so it will no longer apply the filter due to statefulFilter being set to false.

Is there a way to workaround this?  Perhaps a callback or something that I can access from the staticFilesLoader so that I can set the statefulFilter setting afterwards?

Please let me know if you need any additional information

**Comment by pratik14** [comment]
@mattlavallee  you need to include ngSanitize module to get this working.

**Comment by mattlavallee** [comment]
@pratik14, I apologize for messing up the sample code.  In my application I am including ngSanitize and pascalprecht.translate so the missing module is not the problem

**Comment by knalli** [comment]
@mattlavallee  You are right, that is not the problem.

> It seems that the filter is applied initially and then the json file is pulled in so it will no longer apply the filter due to statefulFilter being set to false.
> Is there a way to workaround this? 

No. That is why `stateful = true` exist. `false` works only with preset translations without using asynchronous loadings. Asynchronous results cannot be applied into non stateful filters.

**Comment by mattlavallee** [comment]
Thanks for clarifying @knalli
