### ISSUE TITLE
Discuss: $translate.quick(...) - quicker way to use in-code (controller) translation

### ISSUE THREAD

**Issue by iJungleboy** [angular-translate/angular-translate#1271]
AFAIK to use angular-translate in a controller offers two options
1. using the promise-syntax - which looks very ugly and quickly bloats the code
2. using the filter syntax $filter("translate")(...) which is also not really nice

I understand the reason the promise is recommended, but in many cases a complex application has a load-wait for everything to start, making any kind of language-resource-wait in a deeper controller unnecessary. I've worked around it with a simple service like this:

```
    .factory("translate", function($filter) {
                return $filter("translate");
            })
```

but it feels like such a functionality should be in the $translate, like $translate.quick(...) or something - also because it actually took me quite a while to realize that the $function... would do the trick. 

what do you think? should this be something to provide on the normal $translate? or maybe this feature exists and I just missed it...

**Comment by knalli** [comment]
Please have a look at $translate.instant().

**Comment by iJungleboy** [comment]
You are awesome :)
