### ISSUE TITLE
Using translate-attr- with attributes that contain a hyphen

### ISSUE THREAD

**Issue by rwberendsen** [angular-translate/angular-translate#1272]
Adding a translated value to the `aria-label` atrtibute using  `translate-attr-` does not seem to work. I suspect it has to do with the fact that `aria-label` contains a hyphen.

Disclaimer: I'm still learning angular, apologies if this turns out not to be an issue. I'm also new on github, so let me know if I should have reported this in another way.

**Comment by tspaeth** [comment]
Could you provide a short Plunker/JSFiddle on your setup please? Thanks.

**Comment by rwberendsen** [comment]
Actually, the issue is a misnomer. To get a minimal example that showed the erratic behaviour, I needed to include a dependency: angular-material. And, the issue also arises with attributes that do not have a hyphen. Instead, I now suspect it has something to do with an interaction with angular-material stuff. See: http://embed.plnkr.co/5WsEmKQ3gnGWnzSR7w6k/preview

**Comment by rwberendsen** [comment]
Perhaps, the issue should be closed, since what I am trying to do, in fact, is using a translate directive inside somebody else's directive (angular-material, in this case). Perhaps mixing directives in one element does not work in general?

**Comment by rwberendsen** [comment]
Closing issue, since it is incorrectly formulated.
