### ISSUE TITLE
translate filter in Html not working on page refresh

### ISSUE THREAD

**Issue by ssivaprasad** [angular-translate/angular-translate#1274]
My HTML code looks like this
<button>{{'button_new_access_group' | translate}}</button>

The above code is working fine on page load. 
But when page is refreshed translate filter in not working.

any help is appreciated.

**Comment by tspaeth** [comment]
What does 'refresh' mean in detail? If you have a small complete example, it is much easier to help.

**Comment by ssivaprasad** [comment]
browser refresh : F5

**Comment by tspaeth** [comment]
As Browser reload "the f5 case" always reinitializes the whole application, I bet it'll be hard to find out what you're doing wrong - especially without a Plunker / JSFiddle. Please provide one.

But in general I can tell you: This is normally working.

**Comment by ssivaprasad** [comment]
My code looks like this : 

angular.module('myApp.translate', ['pascalprecht.translate'])
.constant('TRANSLATION_PARTS', [
    'home',
    'error',
    'common',  
    'user',   
    'locations'
]).config(function($translateProvider, $translatePartialLoaderProvider, TRANSLATION_PARTS) {
    $translateProvider.preferredLanguage('en-US');
    $translateProvider.useLoader('$translatePartialLoader', {
        urlTemplate: 'assets/translation/{lang}/{part}.json'
    });
    for ( var i = 0; i < TRANSLATION_PARTS.length; i++ ) {
        $translatePartialLoaderProvider.addPart(TRANSLATION_PARTS[i]);
    }
});

I am injecting 'myApp.translate' as dependency into my main module

**Comment by tspaeth** [comment]
Thanks, but that still won't help as there is no example controller or state so I have an idea of how you're using the whole translation package in the controllers with routings etc...
Please provide a short Plunker, so we don't have to do "try & error"

**Comment by tspaeth** [comment]
Closed due to inactivity. Feel free to reopen.
