### ISSUE TITLE
Persian l10n-fa for Angular!

### ISSUE THREAD

**Issue by 5y** [angular-translate/angular-translate#1277]
Hi,

Recently i figure out about l10n and Angular and it's great idea for Angular specific development  local community looks like Mozilla reps and ... 
So I wanted to contribute for developing Persian language for Angular and How to start?

Bests,
Reza

**Comment by tspaeth** [comment]
Hi Reza!

Thanks for your offer - indeed, angular-translate would like to have some support on RTL languages from a native expert, but I'm not sure if you wanted to reach out for this here?
To make it a bit clearer: This is just the team of the angular-translate module and NOT of AngularJS itself. 

If you want to reach out to the amazing guys at Google - the main repository can be found here: https://github.com/angular/angular.js

Nevertheless, if you're an interested Javascript developer and want to improve this module - you're very much welcome :-)

**Comment by 5y** [comment]
Hi,

Thank you for your suggestion.
I following up this topic with Angular main Repo, and if there is an solution for working on the l10n-fa i'm interesting for working on it :)

Bests,
Reza

**Comment by knalli** [comment]
I'll close this. As @tspaeth  already mentioned, this is not the place for contributions to the AngularJS project itself.
