### ISSUE TITLE
Test Cases failing in the run phase

### ISSUE THREAD

**Issue by Gaurav-Ambasta** [angular-translate/angular-translate#1279]
Hi @PascalPrecht,

I would need your help in order to resolve my failing test cases. When I am trying to use the   $translateProvider.uniformLanguageTag('bcp47').determinePreferredLanguage() in the module.run , it causes my entire test cases to fail. Do we have any solution for this problem. I tried creating a custom loader in global before each but that is also causing my test cases to fail. Please do suggest if we have any workaround for this.

Thanks in advance.

Regards,
Gaurav Ambasta

**Comment by Gaurav-Ambasta** [comment]
@PascalPrecht  I am using translate Partial Loader to load my json files. Also below is the sequence of execution  :
      $translateProvider.preferredLanguage('en-us');
      $translateProvider.useCookieStorage();
      $translateProvider.useLocalStorage();
      $translateProvider.uniformLanguageTag('bcp47').determinePreferredLanguage();
      $translateProvider.fallbackLanguage('en-us');

The error which it is throwing  "Failed to instantiate module ../.../en-US.json due to " Module is not available.

**Comment by Gaurav-Ambasta** [comment]
To get rid of the error "Failed to instantiate module ../.../en-US.json" which occurs while executing test cases, the custom loader seems to be working. But after adding the custom loader in before Each, other set of unit test cases are breaking which are mostly related to `Unexpected request` and some expectation failure. Can you please suggest  ??

**Comment by knalli** [comment]
@Gaurav-Ambasta  Do you already know this here https://angular-translate.github.io/docs/#/guide/22_unit-testing-with-angular-translate

In general, your issue is fixing the angular-mocks of you testcase.

**Comment by Gaurav-Ambasta** [comment]
@Knalli Thanks for your response , I went through the shared link , However , adding the custom loader does help to resolve 'failed to instantiate .. en-us.json ' errors but how to resolve other `unexpected request` errors.

Also I am calling a service in angular run block in order to determine the language and using $translate.use() to set it up. This is also causing my unit tests to fail. Any pointer / suggestion is much appreciated !!

**Comment by knalli** [comment]
Again: You have to fix your mocking.

If you really need to use dynamic translations in your tests (I don't think so), you must configure your mocks. `unexpected request` is just a complaint by angular-mocks you didn't.

Have a look at https://code.angularjs.org/1.4.6/docs/api/ngMock/service/$httpBackend
