### ISSUE TITLE
$translate.refresh is not working as desired

### ISSUE THREAD

**Issue by Gaurav-Ambasta** [angular-translate/angular-translate#1280]
Hello @PascalPrecht 

I am trying to load my locale from the cookie/ local storage. Can you give some example how it really works. On page refresh, the language selected gets lost. Can you please suggest how to load the page on the same language even after the page refresh. Also below is the code which I have used for taking care of the refresh issue . But in this case some message are not properly translated.
```app.run([
    '$rootScope',
    '$translate',
    'cookies',
    function($rootScope, $translate,cookies) {
       var locale = $cookies.locale;
        $translate.use(locale);
       $rootScope.$on('$translatePartialLoaderStructureChanged', function() {
          $translate.refresh();
        });
    }
  ]);
```

Please suggest and appreciate your support.

**Comment by tspaeth** [comment]
Hm, is this just a typo or are you missing the $ in front of cookies in the function head and the dependency injection?

**Comment by Gaurav-Ambasta** [comment]
sorry ,its a typo..

**Comment by tspaeth** [comment]
@Gaurav-Ambasta issue is still there?

**Comment by knalli** [comment]
What is the state?  Are you not using `angular-translate-storage-cookie`?

**Comment by knalli** [comment]
Closed due inactivity.
