### ISSUE TITLE
Why there is a difference between $translate directive and filter?

### ISSUE THREAD

**Issue by huyph** [angular-translate/angular-translate#1281]
I noticed that there is a difference between $translate service and $translate filter.

The original text from json file is 'Cities & Suburbs'. And the results in HTML are different as shown below: 

<img width="306" alt="screen shot 2015-10-27 at 3 37 49 pm" src="https://cloud.githubusercontent.com/assets/3280795/10749655/01571612-7cc1-11e5-9f18-c2fe2252b2c1.png">

**Comment by tspaeth** [comment]
Please have a look at the chapters in the documentation http://angular-translate.github.io/docs/#/guide/04_using-translate-filter and  http://angular-translate.github.io/docs/#/guide/03_using-translate-service 

regarding the differences in between these two usage scenarios. 
Please note that sanitizing and configuring in case of the filter will probably lead to this differences.
See http://angular-translate.github.io/docs/#/guide/19_security

**Comment by Zero-Hassan** [comment]
I noticed that when using translate as directive there are a lot of watchers in the element where it is. but using it as filter, there are zero watchers.!!
