### ISSUE TITLE
How to show special character like '&' in placeholder attribute?

### ISSUE THREAD

**Issue by huyph** [angular-translate/angular-translate#1282]
So the text is 'Cities & Suburbs' in json. And I want to show exactly that in HTML for placeholder attribute.

I tried to do the followings but still got `Cities &amp; Suburbs` on the screen
```javascript
<input translate translate-attr-placeholder="{{translationId}}"/>
OR
<input placeholder="{{translationId | translate}}"/>
```

I know one solution is to change `$translateProvider.useSanitizeValueStrategy('sanitize');` to `$translateProvider.useSanitizeValueStrategy();` but this will make the application vulnerable.

Any other suggestions?

**Comment by Tudes** [comment]
I'm not sure, but I think I had the same problem. Can you change ```sanitize``` to ```escape```

**Comment by SamVerschueren** [comment]
If you use escape, it will be printed like this

```
Cities &amp;amp; Suburbs
```

Not sure why `sanitize` isn't working when using the filter. Is this a bug or is it by design? Experiencing the same issues.

**Comment by tspaeth** [comment]
Kindly the same discussion family as in #1101 ? If it is somehow different, then please point it out, otherwise we'd like to close it as a duplicate. Thanks.

**Comment by artuska** [comment]
Just turn off the sanitize strategy 'cos it is totally broken:

```
angular.module('flat').config(function($translateProvider) {
    $translateProvider.preferredLanguage('en');
    $translateProvider.useSanitizeValueStrategy(null);
});
```

**Comment by knalli** [comment]
I'l close this. The issue is being tracked at #1101. Also have made https://github.com/angular-translate/angular-translate/issues/1101#issuecomment-140426486 as full overview. Please share further information or issue in #1101

**Comment by adeopura4** [comment]
Hi  artuska - Could you clarify what is the impact of changing the sanitize strategy?
