### ISSUE TITLE
using correctly ng-repeat and refresh it when language changes?

### ISSUE THREAD

**Issue by kvbappinio** [angular-translate/angular-translate#1284]
Hey.

it might not be an gerneral issue here, but i have some troubles with
ng-repeat and $translate. 
Before i was loading the data from a js. now its a static json. 

1. Is there a way to let ng-repeat wait until the json is loaded completly ? 
I Couldnt figoure out how to parse the data from the js - to the json, so i used
$translate.instant - thats working good, but ng-repeat isnt "waiting - to load the data completly" 
2. Is there a way to refresh the module when the language is changed ? 

Couldnt find a guide for ng-repeat and this awesome addon. 

Thanks

**Comment by tspaeth** [comment]
I don't know your exact setup, but maybe invoking one of the matching events + invoking some digest might help?

See http://angular-translate.github.io/docs/#/guide/18_events

**Comment by knalli** [comment]
Closed due inactivity.
