### ISSUE TITLE
Mixed Content

### ISSUE THREAD

**Issue by Tudes** [angular-translate/angular-translate#1285]
Any suggestions why I might get this error?

```
Mixed Content: The page at 'https://website.com/#/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://website.com/#/localization/en-US/strings.json'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by tspaeth** [comment]
You're loading some elements / retrieving AJAX-requests on your webpage via http, while it has been retrieved via https (exactly what the error says). But I don't see why / how this related to angular-translate bugs?

Feel free to reopen if you have more information that leads to a bug in angular-translate.
