### ISSUE TITLE
Question about determinePreferredLanguage and registerAvailableLanguageKeys

### ISSUE THREAD

**Issue by budkin76** [angular-translate/angular-translate#1286]
Hello,

Currently I have a site that supports English and German where I have English (en) as the fallback language. I'm using the determinePreferredLanguage() method to automatically translate the site and I'm also using the useStaticFilesLoader so each language corresponds to a json file. Additionally I'm using the registerAvailableLanguageKeys method specifying en and de. I understand the nature of this method is to map all variants of a language key to a unified format (ie. en_UK and en_US to en) but is there a way to tell it to map all "non-registered" languages to say, en?

Here's my issue. If a French user hits my site it tries to use 'fr' (in fact calling $translate.use() returns 'fr'). The site appears in English because there is no fr language file but I still get a 404 when the site tries to request fr.json in my static files directory. I was hoping that the registerAvailableLanguageKeys would tell the client "I can ONLY use these languages." and it would never check for any language that wasn't registered. Obviously that's not how it works. Anyone have a good solution for avoiding this issue? Thanks.

**Comment by tspaeth** [comment]
Besides the loading and 404 aspect you should have a look at the fallback syntax, which would additionally limit the languages the user can use / the system provides for consistency.

**Comment by fabritw** [comment]
@tspaeth I'm curious if you can provide more details on your described solution (i.e. what "fallback syntax" should we use specifically)? It seems to me a quite common use case that people will encounter; that determinePreferredLanguage returns a language key not known in registerAvailableLanguageKeys... for example, is there a method available to set a "default" language is this situation?

**Comment by tspaeth** [comment]
@fabritw As you've modified your comment - anything left to answer? :)

**Comment by knalli** [comment]
Closed due inactivity.
