### ISSUE TITLE
onReady usage

### ISSUE THREAD

**Issue by marcelorio** [angular-translate/angular-translate#1287]
The rootscope solution works, but the onReady solution presents as being ready, but doesn't work. Am I using it correctly?

I am using angular-translate 2.8.1 and angular 1.4.6

$translatePartialLoader.addPart('pages/cadastros/unidade-metrica');

               $rootScope.$on('$translateChangeSuccess', function () {
                    $scope.label.yes = $translate.instant('Cost_UnitOfMeasure_Yes');
                });

                $translate.onReady().then(function () {
                    if ($translate.isReady()) {
                        $scope.label.no = $translate.instant('Cost_UnitOfMeasure_No');

                    }
                    console.log($translate.isReady()); // returns true but translation isn't loaded
                });

**Comment by knalli** [comment]
@marcelorio  Do you using [2.8.1](https://github.com/angular-translate/angular-translate/releases/tag/2.8.1)? Because the bug with `isReady()` should be fixed.

`$translate.onReady()` is already a promise which does not require to check for `isReady()`.

**Comment by knalli** [comment]
Ah, I have missed your said already using 2.8.1.

So, no you don't have to call isReady(), although it should work and looks like the bug was not fixed in 2.8.1

**Comment by marcelorio** [comment]
Indeed the isReady() inside the onReady() is a bit redundant. I only used it as a test to see if it would show up in the console, and it does, but the translation isn't loaded.

**Comment by matikun86** [comment]
I don't know if it's the same cause but I was using $translateProvider.preferredLanguage and I think that was firing the onReady callbacks. I removed that line and onReady fired correctly (at least the first time)

**Comment by knalli** [comment]
What do you mean?

**Comment by marcelorio** [comment]
I was using $translateProvider.preferredLanguage, but taking it from the code did not solve the problem..

**Comment by knalli** [comment]
So basically this does not work for you? https://github.com/angular-translate/angular-translate/blob/2.8.1/src/directive/translate-cloak.js#L37-L39

**Comment by knalli** [comment]
In combination with a condition I 've fixed a bug. I'll close this in favor.
