### ISSUE TITLE
$translate.use works only the second time

### ISSUE THREAD

**Issue by manar-mk** [angular-translate/angular-translate#1288]
I've created method to change language as in example and used 'StaticFilesLoader' to load my translations
        $scope.changeLanguage = function (key) {
            $translate.use(key);
            $scope.lang = $translate.use();
        };
$scope.lang changes only when method is triggered the second time. What am I doing wrong?

**Comment by knalli** [comment]
Sorry for waiting, this issue has been overlooked.Can you provide a demo with your minimal setup?

However, looking at your source code: You have a timing issue between the two `$translate.use()` calls. The first one will be not finished when invoking the second one. Please be aware of the promise (return of the first call).

**Comment by knalli** [comment]
Closed due inactivity.

As I already said: It looks like a timing issue. $translate.use() will invoke asynchronous operations.
