### ISSUE TITLE
Translate a dynamically created JSON 

### ISSUE THREAD

**Issue by nichuHere** [angular-translate/angular-translate#1289]
I am creating a json in my controller. Is it possible to translate the keys?
vm.dropdownJson = {
    			    "Action1": {
    			        "Answered": "ANS",
    			        "Unable to Answer": "UNABLE_TO_ANSWER"
    			    },
    			    "Action2": {
    			        "Solution Found": "SF",
    			        "No Solution Found": "NSF"
    			    }
    			};

**Comment by tspaeth** [comment]
Isn't the discussion in #930 similar and helps?

**Comment by tspaeth** [comment]
Closed due to inactivity
