### ISSUE TITLE
Unit testing Angular views using translateStaticFilesLoader

### ISSUE THREAD

**Issue by sovattha** [angular-translate/angular-translate#1290]
Dear all,

I would like to unit test my view which contains `translate` filters.

The following loads the view and displays the key of my translation, but not its actual real value.

```javascript
  it('should load the view', inject(function($rootScope, _$templateCache_, _$compile_, $translate, $translateStaticFilesLoader, $httpBackend, $translationCache) {
    $httpBackend.when('GET', 'locale-fr.json').respond({
      "vehicule": "Véhicule"
    });
    $httpBackend.when('GET', 'locale-de.json').respond({
      "vehicule": "Fahrzeug"
    });
    $httpBackend.expectGET('locale-fr.json');
    $translateStaticFilesLoader({
      key: 'fr',
      prefix: 'locale-',
      suffix: '.json'
    });
    $httpBackend.flush();

    var tpl = _$templateCache_.get("/detail.tpl.html");
    var scope = $rootScope.$new();
    var view = _$compile_(angular.element(tpl))(scope);
    scope.$digest();
    console.log(view.find('th'));
  }));
```

My view contains:
```html
<th>{{ 'vehicule' | translate }}</th>
```

The expected ouput of the console should be `Véhicule` but it is `vehicule`.

Would you have any idea on how to provide my keys to the view?

**Comment by tspaeth** [comment]
How does $translate know which languages to take? I'm missing something like $translate.use('fr') or something.

**Comment by sovattha** [comment]
Thank you for your answer, but it does not help or maybe it is only part of the solution.
I get the same result.

**Comment by tspaeth** [comment]
Another approach: Did you have a look at our own test suite for maybe a matching example?
https://github.com/angular-translate/angular-translate/tree/master/test

**Comment by sovattha** [comment]
I did search for a matching example using the $translateStaticFilesLoader but none of your examples uses it.

**Comment by tspaeth** [comment]
Hm? Isn't https://github.com/angular-translate/angular-translate/blob/920a9febc22f61368153d844f7cbefcfebb6ecec/test/unit/service/loader-static-files.spec.js using it?

**Comment by sovattha** [comment]
It does, thank you and it is the same code I already copied :)
But I am looking for a working example. I am struggling here with my example. Do you see what I am missing in my code above?

**Comment by knalli** [comment]
@sovattha Well, you can reduce the complexity of this case to the thing want to test: your template. Instead of retesting angular-translate's async loading process, I would recommend 

* a static set of translations
* no XHR mock tooling: no `$httpBackend`

So, using copy-paste of your code of the op: 

```
describe('', function () {
  beforeEach(module('pascalprecht.translate', function ($translateProvider) {
    $translateProvider.translations('fr', {
      "vehicule": "Véhicule"
    });
    $translateProvider.translations('de', {
      "vehicule": "Fahrzeug"
    });
    $translateProvider.preferredLanguage('fr');
  }));

  it('should load the view', inject(function($rootScope, _$templateCache_, _$compile_, $translate, $translationCache) {
    var tpl = _$templateCache_.get("/detail.tpl.html");
    var scope = $rootScope.$new();
    var view = _$compile_(angular.element(tpl))(scope);
    scope.$digest();
    console.log(view.find('th'));
  }));
});
```
```

**Comment by sovattha** [comment]
Thank you knalli, yes in a way, you are right. I try to test too much things in the same test.
I will follow your guideline. Thanks!
