### ISSUE TITLE
Text not changing on translate.use for titles

### ISSUE THREAD

**Issue by psgganesh** [angular-translate/angular-translate#1291]
I use the same in  below way
```html
<ion-tab title="{{ 'coffee_title_label' | translate }}">
```
![image](https://cloud.githubusercontent.com/assets/2221525/11111044/eb9e81ca-8936-11e5-8714-c473b7739424.png)

But when it is 
```html
<ion-tab translate="coffee_title_label" title="{{ 'coffee_title_label' | translate }}">
```
![image](https://cloud.githubusercontent.com/assets/2221525/11111034/cdaa8790-8936-11e5-9408-043d322f0e02.png)

I referred the below codepen example
http://codepen.io/andrewmcgivery/pen/tqymb

Can you let me know, what am doing wrong here !

**Comment by mladenp** [comment]
I think you have the same problem as me. It seems language is not switched if content is in different controller.

**Comment by tspaeth** [comment]
how does the ion-component internally handle the parameter title? Maybe it's not an issue of angular-translate direct, but on the directive it is applied to... just a guess...

**Comment by knalli** [comment]
Looks like it does: https://github.com/driftyco/ionic/blob/v1.2.0/js/angular/directive/tab.js#L60 -- attributes will be not injected dynamically (I guess due performance).

In that case, you have to rebuild the template on your own. We cannot make this, you have to.
