### ISSUE TITLE
Update to angular 1.4 from 1.3 got Uncaught Error: [$injector:unpr] Unknown provider: $$cookieReaderProvider

### ISSUE THREAD

**Issue by snowcxt** [angular-translate/angular-translate#1292]
I got error when I upgraded angular to 1.4 from 1.3. I updated angular-cookies to 1.4 as well. I'm using
```json
"angular-translate": "~2.8.1",
"angular-translate-loader-partial": "~2.8.1",
"angular-translate-storage-local": "~2.8.1",
"angular-translate-storage-cookie": "~2.8.1"
```

source code:
```javascript
$translateProvider
    .useLoader('$translatePartialLoader', {
        urlTemplate: '/i18n/{part}.{lang}.json'
    })
    .useSanitizeValueStrategy('escape')
    .fallbackLanguage('en')
    .preferredLanguage('zh')
    .useLocalStorage();
```

The error details:
```
Uncaught Error: [$injector:unpr] Unknown provider: $$cookieReaderProvider <- $$cookieReader <- $cookies <- $cookieStore <- $translateCookieStorage <- $translateLocalStorage <- $translate <- $cookies
```

**Comment by knalli** [comment]
@snowcxt Your dependency lookup path shows you the problem is not related to angular-translate, but `->$cookies->$cookieReader`. 

I would guess you either have no `angular-cookies`loaded or it is not matched the corresponding version with angular.

**Comment by snowcxt** [comment]
Here's the index.html:

```html
<script src="bower_components/angular/angular.js"></script>
<script src="bower_components/angular-cookies/angular-cookies.js"></script>
<script src="bower_components/angular-translate/angular-translate.js"></script>
<script src="bower_components/angular-translate-loader-partial/angular-translate-loader-partial.js"></script>
<script src="bower_components/angular-translate-storage-cookie/angular-translate-storage-cookie.js"></script>
<script src="bower_components/angular-translate-storage-local/angular-translate-storage-local.js"></script>
```

the bower.json
```json
"angular": "~1.4.7",
"angular-cookies": "~1.4.7",
```

and also I remove the bower_components folder and run`bower install`

the app.js

```javascript
angular
    .module('app', [
        'pascalprecht.translate',
        'ngCookies',
        // something else ...
    ])
```

Is there anything else I have to check?

**Comment by knalli** [comment]
Then you have locally cached something. I've replayed, works as expected: https://gist.github.com/knalli/0b15198e1bf4eab780d6

**Comment by knalli** [comment]
I would recommend to check the versions you are actually using. Perhaps bower has not replaced correctly?

**Comment by snowcxt** [comment]
I went into the bower_components folder and check the package.json of angular and angular-cookies. They are version 1.4.7

```json
  "name": "angular",
  "version": "1.4.7",
  "description": "HTML enhanced for web apps"
```

```json
  "name": "angular-cookies",
  "version": "1.4.7",
  "description": "AngularJS module for cookies"
```

**Comment by snowcxt** [comment]
BTW, I just degraded to use angular-cookies 1.3. Now everything works.
```json
"angular": "~1.4.7",
"angular-cookies": "~1.3.20",
```

**Comment by knalli** [comment]
@snowcxt  Can you checkout my gist?

**Comment by snowcxt** [comment]
Can you send me the link?

**Comment by knalli** [comment]
See here https://github.com/angular-translate/angular-translate/issues/1292#issuecomment-156217300

**Comment by snowcxt** [comment]
It works for me. Do you have any recommendations for me to clean the local cache?

**Comment by knalli** [comment]
Bower cache clean will be your friend, goto man ;)

However, if my mini project is working for you, it does not look like a cache issue. Exzept you have configured a local cache...
