### ISSUE TITLE
Problem with Partial loader for prefered language 'ru' 

### ISSUE THREAD

**Issue by mdima-it-guru** [angular-translate/angular-translate#1293]
I faced such a strange problem: when i execute this command $translate.use('ru') - nothing happens and no locales loaded with partial Loader. But when i use 'en' (for english) or 'es' (for spanish) everything goes right and all used locales are successfully loaded. Very weird problem.

**Comment by tspaeth** [comment]
Hard to guess without an example Plunkr. Could you setup one?

**Comment by knalli** [comment]
Closed due inactivity.
