### ISSUE TITLE
How to manage translations?

### ISSUE THREAD

**Issue by iJungleboy** [angular-translate/angular-translate#1295]
I don't know where to post this - so please forgive me if this is the wrong forum. I have an application which currently has 3 languages (EN, DE, FR) and will quickly have 20+ languages, which many open-source helpers contributing to the translations. How can I manage the JSONs so people know what changed, what must be added/removed in other languages etc. ?

I'm sure there must be a common best-practice tool out there, but I can't figure it out. Help would be appreciated.

**Comment by ahmeij** [comment]
I found https://www.transifex.com yesterday, it seems they offer exactly the management of the translation files, the json format used by angular-translate is supported.

**Comment by iJungleboy** [comment]
@ahmeij I've also been looking into transifex. So far I was able to use a kind of manual import to then compare & evaluate how much is translated, but it doesn't feel quite right yet. They have some kind of scripts you could also run to sync with github, I'll have to do some testruns to see if it can cover the entire process like that.

**Comment by knalli** [comment]
We have no recommendation for that. Everything is useful, starting with a standard text editor.
