### ISSUE TITLE
Disable SanitizeValueStrategy for one $translate call

### ISSUE THREAD

**Issue by guillaume-fr** [angular-translate/angular-translate#1297]
I configured `translateProvider` with `'sanitize'` strategy and want to keep it to prevent injection.

There is a chart in my application draw using a canvas, I want to disable (or change) the `SanitizeValueStrategy` when I call `$translate()` to retrieve text (series names) that will be written on the canvas.

I don't know if this is already possible, otherwise it could be great to have a parameter for SanitizeStrategy or a dedicated function like `$translate.unsafe()` ignoring sanitize.

**Comment by mwz** [comment]
Having ```$translate.instant()``` accepting a null sanitization strategy would be useful, alternatively calling ```$translateSanitization.sanitize(value, mode, "null")``` would also work for me.

I've been using the following as a workaround:

    $translateSanitization.useStrategy(null);
    var translation = $translate.instant('KEY');
    $translateSanitization.useStrategy('escape');

**Comment by RenaldasK** [comment]
+1 Having same issue

**Comment by knalli** [comment]
Ok. I have tagged this as "Contribution Welcome". (hint-hint).
