### ISSUE TITLE
What is the proper user of MissingTranslationHandler

### ISSUE THREAD

**Issue by HadrienPierart** [angular-translate/angular-translate#1298]
I have tried using MissingTranslationHandler to supply a fallback translation when a key is missing in a language and combine this with an error logger to notify me that some key is missing. I know that using `$translate.fallbackLanguage('en');` might solved part of the problem, because it would fallback to english when a key is missing in another language but my main issue is being notified that some translation is actually missing.
Here is what I managed to put together : 

    $translateProvider.useMissingTranslationHandler('MissingTranslationHandler');

Combined with this : 

```
.factory('MissingTranslationHandler', ['$exceptionHandler', '$translate', function ($exceptionHandler, $translate) {
  return function (translationId, lang) {
    if (lang !== 'en') { // If a translation is missing in another language than english, fallback to english translation
      $translate.use('en');
      var translation = $translate.instant(translationId);
      $translate.use(lang);
    } else { // If it's missing in english, we're screwed, leave the key being displayed and log the error
      translation = translationId;
    }
    var missingTranslationMsg = `Translation for lang '${lang}' and key '${translationId}' could not be found.`;
    $exceptionHandler('Missing translation id', missingTranslationMsg);

    return translationId;
  };
}]);
```

This kinda work, but as the change of language is async with `.use()`, it actually changes completely the language of the app when a translation is missing. But Im not sure that using a promise around it would solve much...
Plus, when a translation is missing, this is being call hundreds of times in a matter of minutes...

A proper example of this feature would be much appreciated, because the doc is quite scarce on that :(

That being said, angular translate is some awesome piece of work, and I've always found my way around it, so, pretty good !

Thanks !

**Comment by knalli** [comment]
The `missingTranslationHandler` is meant to be a static resolver for a missing translation. Please do not invoke `$translate` itself again, that could cause obviously an infinite loop state.

Possible scenarios: 
* You want to resolve to the (modified) translation id as a default.
* You have another resource of translations.
