### ISSUE TITLE
Set/Update translations "later", through a service

### ISSUE THREAD

**Issue by Nabellaleen** [angular-translate/angular-translate#1300]
My application can be divided in three steps :
- Choose a server
- Login
- Use the content of the app'

After the choose of the server and the login, it's this server which provide a large parts of the translations.
So, after login step, I have to call a server, which will ask a REST API to get this translations, then I need to add these translations into the translate service.

How to do that ?

Indeed, the ".translations()" method is a part of the $translateProvider, which can be used only in config, and not in a service. And the $translate service seems to not have a method such this ".translations()" one.

**Comment by tspaeth** [comment]
Hi!

Thanks for your report. 
As this is the feature- and bug-tracker for the module, please ask "How to do" questions on the StackOverflow site as you'll reach a broader user base there. Thanks.
http://stackoverflow.com/questions/tagged/angular-translate

Anyway, you should look for partialloaders and a custom loader.
