### ISSUE TITLE
How to translate HTML content?

### ISSUE THREAD

**Issue by raysefo** [angular-translate/angular-translate#1302]
Hello,

I wonder if there is a way to translate content with html?

Here is a sample:
```
<h1 class="rotate">We are <span>IOTERM</span><br>INTERNET OF THINGS (IOT) <br>Solutions <span>Company.</span></h1>
```
Is there a way to add this whole inner html as a key?
```
$translateProvider.translations('en', {
         'MOTTO': 'We are <span>IOTERM</span><br>INTERNET OF THINGS (IOT) <br>Solutions <span>Company.</span>',
```
Best Regards.

**Comment by knalli** [comment]
No, it isn't. You cannot rely on the markup on every environment (say: browser). Stay with a key and a value, latter can be html of course.
