### ISSUE TITLE
Feature-Request: YAML-Support

### ISSUE THREAD

**Issue by faboweb** [angular-translate/angular-translate#1303]
It would be convenient for the static file loader to also load yaml-files. It's easier to write yaml so this would make the life of the editors easier.
I use a gulp-task (gulp-yaml) for this now, but I would like the translation to be as much modular is it can be.

Cheers

**Comment by knalli** [comment]
@faboweb Yeah, you can write your own loader. We don't include this in our core.

Afterwards, you can publish this loader for everyone to include via npm and bower.

**Comment by tjad** [comment]
So was anything ever written or published ? 

@knalli your response is rather distorting - asking the community to contribute without providing support (and closing the issue with essentially nothing done). Rather unattractive.

**Comment by tjad** [comment]
@knalli I am a bit unsure now, are you stating that I shouldn't develop this as a part of the staticFilesLoader module ?

**Comment by knalli** [comment]
@tjad I'd never told *you* anything.

> your response is rather distorting - asking the community to contribute without providing support (and closing the issue with essentially nothing done). Most unattractive.

The leading question was about a feature request regarding a YAML reader. And as I had pointed out this can be solved writing an own loader. If the author wants to share this code for everyone, I have suggested to publish his code. That's it. 

There is nothing "distorting". We cannot add every (mini) use case or feature request solution in our code -- we have to maintain this afterwards!

> @knalli I am a bit unsure now, are you stating that I shouldn't develop this as a part of the staticFilesLoader module

I have never said this.

If you had looked into the guide and/or the API, you would have read about the simplicity of such a loader ([see here](https://angular-translate.github.io/docs/#/guide/13_custom-loaders)). Said this, it can be interesting to have a look at the existing loaders.

Additionally, but currently not in the docs yet, you can even [add a transformer ($http)](https://github.com/angular-translate/angular-translate/blob/c5c20ac7e06d8569c79019b340102ce30fad8572/src/service/translate.js#L1177-L1182) to existing loaders via [this documented setting](https://github.com/angular-translate/angular-translate/blob/c5c20ac7e06d8569c79019b340102ce30fad8572/src/service/translate.js#L594-L609).

**Comment by tjad** [comment]
I have been following the documentation to get the code down - it's running with all tests passing and have looked into the staticFilesLoader module. My initial thought was to include support for yaml there - as it might become a preferred method of maintaining static files for translations.

I am busy converting my padrino application into angular and have now hit i18n, angular-translate is great, however doesn't support YAML, which currently all our translations are in. Objectively looking at this, padrino has a nice style of maintaining i18n files ( specifically the loading of yaml files http://padrinorb.com/guides/localization/ )

The transformer sounds good in terms of modularization - so perhaps I'll go that route that it wont involve changes to the core code.

Apologies for the above, I don't understand the just of the conversation - and am not allowing it to become an impediment.

And thanks for your response!

**Comment by tjad** [comment]
The implications of including this into the core, are that I would take the route of using js-yaml, which probably wont be acceptable - as you stated, you can't include every bit of code that may fulfill a use-case, will point to the solution from here.

**Comment by tjad** [comment]
I eventually decided to use a more javascript friendly storage format for my translations, [cson](https://github.com/bevry/cson), a coffeescript json variant that transpiles to pure  json  which has supporting grunt utilities [grunt-cson](https://www.npmjs.com/package/grunt-cson), this gives the syntax similar to YAML that I was looking for.

I further added code to flatten my structures so that the nested object keys become concatenated into one separated by `.` implemented as suggested using a custom loader.

Thanks for your pointers @knalli, - What an awesome module! Srsly!
