### ISSUE TITLE
Is there a getter for the registered available languages?

### ISSUE THREAD

**Issue by ppollono** [angular-translate/angular-translate#1304]
Hi,
I'm building an app which every time I need to do stuff with languages I'm making a request to my languages endpoint....

I'd like to register the available languages in the translate provider, and then use it instead of that request to my api/languages endpoint.

I couldn't find a way to get and use those registered languages in my controllers and directives, I'm mixing up stuff?

Thanks

**Comment by tspaeth** [comment]
Currently you can only retrieve the keys you put in via "registerAvailableLanguageKeys" from exactly the same function during configuration, but not from controllers. Right.
Why not storing this key-object in an application-wide constant if you're anyway putting them in from within your business logic (outside the module)?

**Comment by ppollono** [comment]
Well I found 2 solutions for this:
* Decorate the $translateProvider with a getter/setter of my appLanguages 
* Using constants. 

Maybe will be a nice add to angular-translate since he is responsable of the internationalization of my app.

Thanks anyway for the answer. :+1:

**Comment by knalli** [comment]
Will be in 2.11
