### ISSUE TITLE
wrong translation on not existing fallback language in directives

### ISSUE THREAD

**Issue by bluepanter** [angular-translate/angular-translate#1305]
Setting:
- static file loader
- multiple fallback languages

Case:
On setting the language at run time to a fallback language which is not available, it loads the correct 
translation if its a filter, but not, if its a directive. If its a directive it returns always the language key.

Example on plunker:
http://plnkr.co/edit/XAK2zaRzilCLvzaDBV4D?p=info

**Comment by tspaeth** [comment]
Please use the latest versions of angular and angular-translate if checking for issues.
Using 2.8.1 of angular-translate and e.g. 1.4.8 - this issue doesn't come up.
