### ISSUE TITLE
$translatePartialLoader.addPart causing multiple loads of each part

### ISSUE THREAD

**Issue by M21B8** [angular-translate/angular-translate#1307]
I have a load of child modules within the app, each of which has its own translation bundle. when the module is loaded, it loads its translation bundle.

The problem i has is that when i load more than one module at a time, each module calls add part, the $translate.refresh call, loads the bundles more than once.

Example code (somewhat simplified!):

```
$rootScope.$on('$translatePartialLoaderStructureChanged',function () {
    $translate.refresh();
});
```

to add the parts:

```
function loadModule(module){
  $ocLazyLoad.load(module).then(function(){
    $translatePartialLoader.addPart(module);
  });
}
var modules = ['m1','m2','m3'];
angular.forEach(modules, function(module){
    loadModule(module);
});
```

The pattern of loads is:

m1,m1,m2,m1,m2,m3

It looks like the subsequent refreshes, aren't aware that the module file has already been requested, so requests it again.

**Comment by knalli** [comment]
Yes, that is an inefficiency of the partial loader. It only works with $translate.refresh() but this will refresh always. See also #399

**Comment by weldelmongi** [comment]
pour résoudre ce problème il faut lors de la config du module d'ajouter cette ligne
 $translateProvider.useLoaderCache(true);

**Comment by tspaeth** [comment]
English please! En anglais s'il vous plaît! Merci.

**Comment by niaher** [comment]
It's a bug. Please check the pull request: https://github.com/angular-translate/bower-angular-translate-loader-partial/pull/26

**Comment by weldelmongi** [comment]
i have face this bug and i have solve it ,as i mentioned before in french language ,so
to solve the problem i have configure the  " $translateProvider" to use the cash by adding this line of code when making the configuration of the module :
$translateProvider.useLoaderCache(true);

**Comment by knalli** [comment]
Will be fixed in 2.14

**Comment by dmitry-dedukhin** [comment]
Hi!

I've looked at https://github.com/angular-translate/angular-translate/commit/8b2cea8 and have a questions.
Why not use $http cache and resolve duplicate requests with one line of code?
Or why not use $translateProvider.useLoaderCache at all?

**Comment by knalli** [comment]
@dmitry-dedukhin I would imagine `$http` was not part of AngularJS at this time, but this is speculating. Also I'm not sure how it will deal with refreshing content. 

So: Yes, you would build it with other existing tooling nowadays probably. But this is old cold base...
