### ISSUE TITLE
partialLoader part data transformation

### ISSUE THREAD

**Issue by timhoekstra** [angular-translate/angular-translate#1310]
In my project I'm having to organize the translation of an application that is using services from quite a few different teams working on their own services. Modifying existing api's from services isn't always a first option.

To prevent conflicts between parts I would like to have the ability to add prefixes to the table keys of the parts.
One of the other issues I'm running into is that the api's we are working with are not returning the data for the part in the way the partialLoader expects. For example it is an object with multiple properties one of which is a property that contains the table.

What I'm looking for is the ability to register a transformation function per specific part when calling partialLoader.addPart and then let the partialLoader perform that transformation on the returned data when the data is retrieved in the getTable method. 

Is this something that might be considered for a future release of the partialLoader?

**Comment by tspaeth** [comment]
Won't this also work with a custom loader you develop perfectly matching to your requirements? (adopt the partial loader e.g.)

**Comment by knalli** [comment]
I hope we can make the "partial loader" to make such as easy as the custom loader (which is actually only one function with promise), but it will not happen in this 2.x release any more (definitely).

Even in a new feature, angular-translate will only provide features for translation text. Nothing more.

Said this, as the library maintainer: If you have such specific requirements, I advice you to build your own loader.
