### ISSUE TITLE
Angular 2 support

### ISSUE THREAD

**Issue by wstoettinger** [angular-translate/angular-translate#1315]
Hey @PascalPrecht 

i've seen your talk from ng-conf and read your blogpost about the new angular-translate. you state "Work on support for Angular 2 is likely to start a few weeks after Angular 1.4 is out." Unfortunately, I haven't been able to find anything related to Angular 2 in your docs or via google. 

Are there any news on that?

**Comment by tspaeth** [comment]
You refer to http://blog.thoughtram.io/angular/2015/03/21/angular-and-i18n-the-new-world.html probably? 

Well, the i18n module mentioned is about a module (currently inactive afaik) supposed to be in the angular core and is not about angular-translate to be ported 1:1 into an Angular2 module.

As the architecture and approach of the Angular i18n module is somewhat different compared to angular-translate in the current architecture, this will not be "upgraded" to that I would say.

**Comment by wstoettinger** [comment]
thanks for your quick response! 

yes, exactly that post. that means, we have to wait, i guess.
