### ISSUE TITLE
Need ability to watch context for changes

### ISSUE THREAD

**Issue by tommck** [angular-translate/angular-translate#1317]
Currently, if I use a context in a translation string and the context object changes, the translation is not updated.

It would be really nice to have this feature built-in to angular-translate.

**Comment by knalli** [comment]
What do you mean with "context in a translation string"?

**Comment by tommck** [comment]
string: "Remove Object {{foo}}"

javascript object:

var contextObject = { foo: 'hi' };

translate call: <p>{{'string' | translate:contextObject}}</p>

if we change foo to "hello", the translation doesn't change

**Comment by knalli** [comment]
Can you please make a test case showing this? Because that's actually an feature: we are watching the (interpolated) params.

Also: Which version is used?

**Comment by tommck** [comment]
I'm using 2.8.1

I will try to repro it in a small example

**Comment by tommck** [comment]
As usual, when trying to reproduce it, I realized that the error is mine, not in angular-translate :)

Sorry for the trouble.
