### ISSUE TITLE
Plain translations without directives

### ISSUE THREAD

**Issue by uoziod** [angular-translate/angular-translate#1318]
Is that possible somehow to output labels containing "&" as is (without replacing with "&amp;amp;") not only by directive but with filter (and/or service).

**Comment by tspaeth** [comment]
You mean in case you configured a sanitizeStrategy named 'escape' or 'sanitize'??

Because: If you do not configure any sanitizeStrategy - it will not encode the text.

**Comment by uoziod** [comment]
Yes, that helped!
Thank you
