### ISSUE TITLE
Namespace conflicts with $scope 

### ISSUE THREAD

**Issue by kenp77** [angular-translate/angular-translate#1319]
Hi,

When i use the `translate-namespace` attribute inside a div, all the ng-model value inside this div are undefined in my angular controller. 
ex : 
```html
    <div translate-namespace="MAP">
     <form name="form">
        <input type="text" ng-model="country">
     </form>
    </div>
```
`$scope.country` is undefined, but when i remove the translate-namespace attribute, `$scope.country` has a value. Are you aware about this bug ? Do you have a fix for it ?

Thanks

**Comment by tspaeth** [comment]
I don't see that issue - could you check your whole setup please or post a Plnkr of it.
Here is a variant of what I've understood - contains a controller-only variable "valueIntern" and also includes partial loading - seems to work fine:

http://plnkr.co/edit/FqCf4wV0Ft2Vyxzf1SUL?p=preview

**Comment by knalli** [comment]
Closed due inactivity.
