### ISSUE TITLE
Variable replacement inside loops

### ISSUE THREAD

**Issue by Danita** [angular-translate/angular-translate#132]
Hi!

I couldn't solve the following use case. What do I have to do when I have to replace a variable in a translation string inside a loop like `ng-repeat`?

For example, given the following:

Controller:

``` javascript
$scope.messages = [
    { author: "John", body: "Lorem ipsum" },
    { author: "Peter", body: "Lorem ipsum" },
    { author: "Nancy", body: "Lorem ipsum" }
]
```

Translation:

``` javascript
{
    "REPLY_TO" : "Reply to {{user}}"
}
```

Partial:

``` html
<ul>
    <li ng-repeat="message in messages">
        <p>message.body</p>
        <a href="#">{{ 'REPLY_TO' | translate:'{user : message.author}' }}</a>
    </li>
</ul>
```

I think something like that is not possible without doing all in the controller, which I feels breaks the principle of separation of concerns.

**Comment by AqquaBug** [comment]
Hi,

I am very new to angular-translate, so please forgive me if this is a very stupid question!

Now on this example that SebC99 has provided : http://jsfiddle.net/UGLjh/

all seems well, however i am in a situation where i need the body to be translated as well

$scope.messages = [
    { author: "John", body: "Lorem ipsum" },
    { author: "Peter", body: "Lorem ipsum" },
    { author: "Nancy", body: "Lorem ipsum" }
]

body variable in the messages array is "Lorem ipsum" which is in Latin, what if i needed that to be translated as well.Is there a way to do that, imagine that $scope.messages array is actuall coming from a json file through $http service, and that data in that file is in english.Which has multiple nested arrays with english data.

How can i change that body data which is Lorem ipsum while i am translating "REPLY_TO" : "Reply to {{user}}".

I hope you can help me.

Thank you in advance

**Comment by knalli** [comment]
Hi @AqquaBug , thank you for using angular-translate!

In short: In the example, just like translating `message.author` you can use translating for `message.body` as well. You have to provide such translations: http://jsfiddle.net/ofawsL4m/

I hope I could help you!

[ Please open a new issue future. They are do not billed for anyone ;) ]

**Comment by AqquaBug** [comment]
Hey knalli, thank you for your prompt reply.

But i mean this, please see the body variable in messages array :

https://jsfiddle.net/orcun/m5znzcq9/1/

Where the body variable inside messages are now in English, what if I had millions of descriptions like that coming from a database into a .json file in different languages.

In your example and SebC99's examples it seems to me that we are translating the UI -User interface text, buttons, messages to user's etc.

How about if i need to change the data that coming from a database, like descriptions of an author in several languages.

Or comments left for a product by customers, in 2 different languages, what would be the correct way to implement translations of this kind of data into our project.

Thank you for your help again
