### ISSUE TITLE
non-translate prefixes or suffixes in translate directives

### ISSUE THREAD

**Issue by p1tt1** [angular-translate/angular-translate#1320]
It is possible to define non-translate prefixes or suffixes in translate directives. Now I using the translate-filter to solve this problem:

```html
<div>Prefix {{TranslationID | translate}}</div>
```

It is possible to solve this with a directive? I need this to translate the Page-Tab-Title. If I using the translate-filter, the filter-content need more time to load as the prefix.

**Comment by tspaeth** [comment]
If I understood the question right (I'm unsure): no, you can't "non-translate" one part per string currently. Either you put the prefix text also into the translation or separate your translation with a <span translate> or similar.

**Comment by p1tt1** [comment]
mh... ok.
yes can put the prefix in each translation, but this is not a good style. And I can't put the prefix in a other htlm-element, because I think this is not possible within a html-header-title.

**Comment by p1tt1** [comment]
This works and is a nice solution:
'''
<title translate>Prefix{{TranslationID}}</title>
'''

**Comment by knalli** [comment]
@p1tt1 Yes, this is a feature but will probably removed in v3 (#995) due spec issues. Just for notice.
