### ISSUE TITLE
Directive priority improvement idea

### ISSUE THREAD

**Issue by RopoMen** [angular-translate/angular-translate#1322]
Hi,

I currently use angular-translate in project which also has ngMessages module. I found that using angualr-translate with ngMessages is not always "drop in"

my usage was:
```html
<div ng-message-exp="required" translate="myKey"></div>
```

which will cause error https://github.com/angular-translate/angular-translate/issues/949

I have also noticed this warning which is ok
"pascalprecht.translate.$translateSanitization: No sanitization strategy has been configured. This can have serious security implications. See http://angular-translate.github.io/docs/#/guide/19_security for details."

Could you also add some kind of warning if angular-translate is used with ngMessages that "You should set $translateProvider.directivePriority(2) (at least) when using with ngMessages" (warning shown if directivePriority is not set to >= 2)

It tooked me to 30min. to find solution to that issue with ngMessages module, that warning would have droped the time in seconds :)

Br,
-Markku

**Comment by knalli** [comment]
Sorry, we can't. 

We cannot add for all other libraries a warning. Why only ngMessages but not angular-gettext? The priority option is available in the api interface, although it would always being possible with a custom override/decorate.
