### ISSUE TITLE
Bug with: browserify + angular-translate-interpolation-messageformat + loading locale

### ISSUE THREAD

**Issue by ArnaudValensi** [angular-translate/angular-translate#1325]
The following example create the error:
```
Uncaught Error: Plural Function not found for locale: xx
```

```javascript
require('./node_modules/messageformat/messageformat.js');
require('./node_modules/messageformat/locale/fr.js');
require('angular-translate-interpolation-messageformat');

...

$translateProvider.useMessageFormatInterpolation();
$translateProvider.preferredLanguage('xx');
```

The problem is in the load code of `angular-translate-interpolation-messageformat'`:
```javascript
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module unless amdModuleId is set
    define(["messageformat"], function (a0) {
      return (factory(a0));
    });
  } else if (typeof exports === 'object') {
    // Node. Does not work with strict CommonJS, but
    // only CommonJS-like environments that support module.exports,
    // like Node.
    module.exports = factory(require("messageformat"));
  } else {
    factory(MessageFormat);
  }
}(this, function (MessageFormat) {
...
```

Because we're using Browserify, `exports` is an object, so the code is loaded with this line:
`module.exports = factory(require("messageformat"));`.
This line reload the module `messageformat` in the window scope which is replaces our first loading with our locale:
```
require('./node_modules/messageformat/messageformat.js');
require('./node_modules/messageformat/locale/fr.js');
```

**Comment by knalli** [comment]
We are not loading `messageformat` in the window scope. As you can see, we are injecting this a non global. If there is something defining a global `messageformat`, this can be only done by messageformat itself.

It's possible messageformat is not fully working with browserify, perhaps you have to add a shim entry?

**Comment by knalli** [comment]
Regarding your PR: Eh.. that makes the usage of modules being a little bit absurd. You are relying on globals while using a module system? That's not the right way, and I don't see we should even support this...

Side note: If you are in trouble of injecting the locales too late: You have to inject them as a dependency itself.

**Comment by ArnaudValensi** [comment]
Yes but here, the problem is that messageformat uses this to load the code:
```
(function ( root ) {
...
})( this );
```
I'm not sure about what does browserify, but if it does nothing special, `this` is `window`. Also it is why we have to load a local doing this:
```
require('./node_modules/messageformat/messageformat.js');
require('./node_modules/messageformat/locale/fr.js');
```
Or, maybe there is another way to load locales without being overridden when we load `angular-translate-interpolation-messageformat`?

**Comment by ArnaudValensi** [comment]
I tryed using browserify-shim and injecting as depency but I was not able to do it. But maybe I did it wrong.

**Comment by patlux** [comment]
@ArnaudValensi:

Use the prerelease (v0.3.0-1) of messageformat.js. @NeverwinterMoon created a fork with the prelease:

https://github.com/NeverwinterMoon/bower-angular-translate-interpolation-messageformat

```bash
# install locales
npm install --save make-plural
# install prerelease of messageformat.js
npm install --save messageformat@prerelease
# install fork of  bower-angular-translate-interpolation-messageformat
npm install --save git+https://github.com/NeverwinterMoon/bower-angular-translate-interpolation-messageformat.git
```

```javascript
angular.module('yourModule', [
  require( 'angular-translate' );
  require( 'angular-translate-interpolation-messageformat' );
])

.config( function( $translateProvider ) {

  $translateProvider
    .addInterpolation('$translateMessageFormatInterpolation')
    .preferredLanguage( 'en' );

});
```

See: https://github.com/SlexAxton/messageformat.js/issues/120

**Comment by ArnaudValensi** [comment]
@patlux That's perfect!

Thank you.

**Comment by andreialecu** [comment]
I think this should be reopened, since it is an issue when using webpack/browserify and locales. 

MessageFormat v0.3.0-1 fixes this, so perhaps pin that version instead?
