### ISSUE TITLE
translate-namespace directive doesn't work

### ISSUE THREAD

**Issue by odedniv** [angular-translate/angular-translate#1327]
Am I missing something? Even the demo in the documentation doesn't work...

https://angular-translate.github.io/docs/#/api/pascalprecht.translate.directive:translateNamespace

**Comment by tspaeth** [comment]
Upgrading to angular-translate 2.8.1 seems to help here.

**Comment by odedniv** [comment]
Ha weird... well the docs should be updated

Thanks!

**Comment by knalli** [comment]
@odedniv What do you mean? Missing statement to use 2.8.1 instead of 2.8.0?

**Comment by knalli** [comment]
OK. Got it. The libs in the docs must be updated.

**Comment by knalli** [comment]
@odedniv  Thank you for the message. Docs will be refreshed next release. 23d5ce1
