### ISSUE TITLE
translate does not work properly with useStaticFilesLoader 

### ISSUE THREAD

**Issue by kenp77** [angular-translate/angular-translate#1330]
Hi,

When i use StaticFilesLoader, the tanslation is not done when i load the page for the first time.
 Also, when i click my second link (fr_FR)  for the first time, it translate in english and when click it for the second time, it translated in french !.  It's weird what is happening here.

Here's my code : 
 ```JAVASCRIPT
  $translateProvider.useStaticFilesLoader({
    prefix: 'l10n/',
    suffix: '.json'
  });

 // Tell the module what language to use by default
  $translateProvider.preferredLanguage('en_US');
 ```

Note that the Json file is well formated and loaded since i'm able to translate when i hit the translation links for the second time !

Json files : 

EN : 
 ```JSON

{
	"HELLO"        : "Hi"
}
```
FR:
 ```JSON
{
	"HELLO"        : "Bonjour"
}
 ```

My controller : 
 ````JAVASCRIPT
$scope.hello= $translate.instant('HELLO');
	
  $scope.setLang = function(langKey) {
    // You can change the language during runtime
    $translate.use(langKey);

   $scope.hello= $translate.instant('HELLO');
 ```

View : 

 ```HTML
  <p>
    <a href="#" ng-click="setLang('en_US')">English</a>
    |
    <a href="#" ng-click="setLang('ru_RU')">Русский</a>
  </p>

   <p>{{hello}}</p>
 ```



Note that everything works fine when i use this instead of json file :  

 ```
  $translateProvider.translations('en_EN', {
    "HELLO"        : "Hi"
  });
  $translateProvider.translations('fr_FR', {
    "HELLO"        : "Bonjour"
  });
```

Any idea why i'm not able to translate properly when i use the json files ?

**Comment by tspaeth** [comment]
could you set a used language  explicitly during setup phase with

```
$translateProvider.use('en_US');
```
and check if it works better?

**Comment by kenp77** [comment]
You mean use $translateProvider.use('en_US') instead of $translateProvider.preferredLanguage('en_US') ? Yes i did but still have the same issue.

**Comment by kenp77** [comment]
I created a plunk : http://plnkr.co/edit/U7xbn621mF60UgkxkXiO?p=preview

**Comment by tspaeth** [comment]
Hi!
As you're doing instant translations and in combination use the ".use" function with async - loading mechanisms, the instant will in this case fail as it doesn't wait for any async resources to be finished if not existing yet.
I've modified your example a bit to demonstrate how it would work better - please also read the documentation carefully ($translate.use gives back a promise) at 
http://angular-translate.github.io/

Plnkr:
http://plnkr.co/edit/Ibq4EaFcvyUPGpqb81Jo?p=preview

**Comment by kenp77** [comment]
how come the translation works with  : $translateProvider.translations() even if i use the combination of "instant" and ".use" ?
Your plunks show the key "HELLO" when i load the page. And why you have "hello" two times ? 
```HTML
Hello
  <p>
    <a href="#" ng-click="setLang('en_US')">English</a> |
    <a href="#" ng-click="setLang('fr_FR')">French</a>
  </p>
  <p>{{hello}}</p>
```
I think the bug is more with StaticLoader.

**Comment by tspaeth** [comment]
I don't see a bug really, you just have to know about that static files loader is asynchronous and $translate.instant is synchronous. So mixing these two is not a good idea with this setup.

See the updated plnkr for a working version - you'll have to wrap your initial scope variable into another use - function.

http://plnkr.co/edit/Ibq4EaFcvyUPGpqb81Jo?p=preview

**Comment by knalli** [comment]
As @tspaeth has  already pointed out, `$translate.instant()` is the *current loaded* state of translations. It will/can not wait for any loader to finish. Our guide explicitly warns about the usage and is not recommending it the first way.
