### ISSUE TITLE
Automated / Grunt task to generate translation template file ?

### ISSUE THREAD

**Issue by toni-moreno** [angular-translate/angular-translate#1331]
Is there is any way to automaticaly look for translation strings on html files and  create/ update a translation json template file.

Is there any way to integrate with grunt ?

**Comment by tspaeth** [comment]
How would you detect and decide what a translation string is?
But indeed there is some grunt task already: https://github.com/angular-translate/grunt-angular-translate

And maybe, you'll get some inspiration of what is possible with the other repos like 
https://github.com/angular-translate/translate-compile

**Comment by knalli** [comment]
I think this is being well answered. I'll close in forward.

**Comment by toni-moreno** [comment]
thank you very much @tspaeth , I will test this grunt task.
