### ISSUE TITLE
Error while bower installing 'bower-angular-translate-loader-static-files.git'

### ISSUE THREAD

**Issue by VaibhavP17** [angular-translate/angular-translate#1332]
I am getting the following error while installing "bower-angular-translate-loader-static-files.git" -

bower angular-translate-loader-static-files#~2.7.2           cached git://github.com/PascalPrecht/bower-angular-translate-loader-static-files.git#2.7.2
bower angular-translate-loader-static-files#~2.7.2         validate 2.7.2 against git://github.com/PascalPrecht/bower-angular-translate-loader-static-files.git#~2.7.2
bower angular-translate-loader-static-files#~2.7.2          ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/PascalPrecht/bower-angular-translate-loader-static-files.git", exit code of #128 fatal: read error: Connection reset by peer

What could be the reason for the same ?

**Comment by tspaeth** [comment]
I don't have that issue when calling that git command from the command line. You probably need to increase the verbosity to see the issue. Looks like somewhat a network issue?

**Comment by VaibhavP17** [comment]
I had the following dependency in my bower.json -
    "angular-translate": "~2.7.2",
    "angular-translate-loader-static-files": "~2.7.2",
    "angular-translate-loader-url": "~2.7.2"

One running the command - "bower install" , I get the above mentioned error. I even updated the version of these dependencies to 2.8.1 (latest) but still no luck. Can you please try installing it using bower? I don't think there is any network related issues as all other libraries are getting downloaded just fine.

**Comment by tspaeth** [comment]
Again: Works fine here. 
Please check if you're using any proxy or firewall that might cause issues or block ports on git:// urls. If you google for the "Connection reset by peer" with bower etc., you'll maybe get some hints / reasons.

**Comment by VaibhavP17** [comment]
Yes, you got that right. I executed the following command - 
git config --global url."https://".insteadOf git://

and it worked just fine. Thanks a lot :+1:
