### ISSUE TITLE
$translateProvider.fallbackLanguage(lang) seems to block $translateChangeSuccess

### ISSUE THREAD

**Issue by memee** [angular-translate/angular-translate#1336]
It seems that setting `fallbackLanguage()` stops `$translateChangeSuccess`

    config(function ($translateProvider) {
        $translateProvider.useStaticFilesLoader({
                prefix: 'locale/locale-',
                suffix: '.json'
            });
        // $translateProvider.fallbackLanguage('en_US'); // uncomment that
        $translateProvider.determinePreferredLanguage();
        $translateProvider.useLocalStorage();
        $translateProvider.useSanitizeValueStrategy('sanitize');
    })

somewhere in controller

    controller: function ($rootScope) {
        $rootScope.$on('$translateChangeSuccess', function () {
            console.log('$translateChangeSuccess fired');
        });
    }

**Comment by knalli** [comment]
@memee  Please prepare and provide a working demo always. I cannot confirm this issue with my setup: http://plnkr.co/edit/60xY7Aw4RGOzQMmVMglZ?p=preview

**Comment by memee** [comment]
I confirm, it's working. I think it's an issue with missing fallback language json file but I cannot check it now. Sorry, could be closed.
