### ISSUE TITLE
Variable as key looping in the template

### ISSUE THREAD

**Issue by LeoAJ** [angular-translate/angular-translate#134]
Hi
I have question about when variable as key of translation looping through `ng-option`.

In the controller:
I have a array
```
$scope.arr = ['k1', 'k2', 'k3']
```

Translation json:
```
{
    "common": {
         "test1": {
              "k1": "This is k1",
              "k2": "This is k2",
              "k3": "This is k3"
         }
    }
}
```

In the view:
```
<select ng-model="m1" ng-option="{{'common.test1.' + i | translate}} for i in arr"><select>
```

I tried to create a dropdown button with translation supported. Obvious this one is not going to work, I was wondering is there anyway to create this similar structure by using angular translate ?

Thanks for the help, I appreciated.

**Comment by knalli** [comment]
@tspaeth  can we close this?
