### ISSUE TITLE
How to use safely in 3rd party module?

### ISSUE THREAD

**Issue by yaronguez** [angular-translate/angular-translate#1340]
Hi there, I'm just digging into angular-translate and so far am very impressed. What would be the best way to use angular-translate within a module that I was going to distribute?  For example, if I'm releasing an angular authentication module that displays certain error and login messages and I want to provide translatable versions of these messages and also allow developers to to override these messages with translations of their own, how would I do that safely? I could list angular-translate as a requirement but even then the translateProvider.useStaticLanguageProvider within my module could inadvertently over write translations used my consuming app.  Apologies if I'm getting this entirely wrong. Any advice is appreciated!

**Comment by knalli** [comment]
There is no ideal way.

Either you ask for `$translate` service using `$injector` allowing to use optional dependencies. Alternatively you provide a set of JSONs which people can integrate in there *choice* of i18n system.

**Comment by yaronguez** [comment]
Any plans to add such a feature?  Something comparable to [angular.extend ](https://docs.angularjs.org/api/ng/function/angular.extend) that allows any module to extend the translation table without overwriting anything that's already in it would be an invaluable addition.

**Comment by knalli** [comment]
No plans, because simply no ideas. `angular.extend` is actually another level.

a) You can build your own loader at any time.
b) We have a special purpose loader called "partial loader" which is loading texts in parts.
c) Even if you would use this, I would not recommend this. Why should you make an assumption of any app how they should load the translations? Perhaps the app later can/must handle translations without files, or with one big file, or with another translations plugin.

**Comment by yaronguez** [comment]
Making assumptions is what I'm trying to avoid. I want to use angular-translate to provide localized messages in my plugin. I don't want to assume whether or not the app using my plugin uses angular-translate.  If the app IS using angular-translate, I don't want my plugin to override the app's translation table. Also, if the app is using angular-translate and decides to provide its own customized set of messages for my plugin, it would be nice if they could simply add those messages to their existing translation table and my plugin would just defer to those messages.

This could be accomplished by an optional parameter used when loading a translation, something like use useStaticFilesLoader({files: [], merge: false});  If merge is true, the loader wouldn't replace the existing translation table, it would append to it and skip any existing duplicate entries.

Apologies if I'm misunderstanding the way this works. When I was using my own home brewed localization service, I had an addIfNotExists() method to add new translations to an existing set.
