### ISSUE TITLE
use newer messageformat?

### ISSUE THREAD

**Issue by tahoemph** [angular-translate/angular-translate#1345]
The bower.json in angular-translate-interpolation-messageformat specifies messageformat ~0.1.6.  The Gruntfile.js in angular-translate uses messageformat 0.2.2 in the ngdoc section.  This makes me think that maybe the specification in angular-translate-interpolation-messageformat might just be oversight and should really be something closer to 0.2.2.

messageformat 0.2.0 introduces a change (a9314e22) which causes it to litter less in the global variable space.  Unfortunately I have another package and messageformat before 0.2 side swiping each other.

**Comment by knalli** [comment]
That's right I think. However, you are free to use use another version of messageformat. You have only to override the resolution in your bower.json. AFAIK the next breaking change is 0.3 which makes the current version incompatible.

**Comment by tahoemph** [comment]
So if I pushed a delta to change messageformat from ~0.1.6 to 0.2.x that would be accepted, right?  The problem I have is that to somebody using the angular-translate it looks like you are saying that the (dirty) 0.1.6 is what is normal.  Playing version roulette by just bumping that to (for example) 0.2.2 seems wrong.  If I hadn't noticed the usage in ngdoc I probably would have assumed I was way out of line doing that.

**Comment by knalli** [comment]
In general, I would mark the version range allowing newer releases would be installed automatically. However, the API of messageformat.js is not stable or following semver at the moment (well: it is still using 0.y.z as version schema). Therefore, we cannot blindly allow everything, but we also cannot follow up each release.

If 0.2.0/0.2.2 passes our tests, we can use this. Obviously, the dependency of the bower shadow repository should match the one of the developing repository.

**Comment by tahoemph** [comment]
I created a PR in the bower repo.  I don't think the dependency should be in the angular-translate repo as it comes through angular-translate-interpolation-messageformat or am I missing something?

**Comment by knalli** [comment]
I've raised the spec by 

```
    "messageformat": "~0.3.0"
```

Although it looks like versions before 0.3 still works.
