### ISSUE TITLE
plnkr for using custom loader service is broken

### ISSUE THREAD

**Issue by fahussain** [angular-translate/angular-translate#1346]
The plnkr for using custom loader service is throwing errors.

Uncaught TypeError: $translateProvider.uses is not a function from myApp

**Comment by knalli** [comment]
`$translateProvider.uses` -> `$translateProvider.use`, but already since v2.

@fahussain  Which plnkr you have used? Where did you find it?

**Comment by knalli** [comment]
Closed due inactivity.
