### ISSUE TITLE
With sanitation strategy 'sanitize" the accentuated letters do not render

### ISSUE THREAD

**Issue by louisdoe** [angular-translate/angular-translate#1347]
Hi

in my ionic app, there's a tag where I need to use

    $translateProvider.useSanitizeValueStrategy('sanitize');

because there is html in the translation field (translation-fr.js):

     "recommendedboard": "Prefer a <span class=\"animateFUN\">SMALL-WAVE</span> board</span>"

But there are others spots where I need to use

    $translateProvider.useSanitizeValueStrategy('escape');

because in the French translation, there accents on some letters, like :

     "31": "Modèle"
The only solution I found for now is to use the null strategy. Is there a way to use both strategies, or to specify the strategy for each translation ?

I have this in index.html:

    <meta charset="utf-8">

and I checked the translation-fr.js file:

    $ file -bi www/js/dicts/translation-fr.json 
    text/plain; charset=utf-8

Thanks

**Comment by knalli** [comment]
@louisdoe Please have also a look at #1101 collecting everything about this issue.

Regarding your question: 

> Is there a way to use both strategies, or to specify the strategy for each translation ?

Currently not. But a contribution would be welcome.

**Comment by louisdoe** [comment]
I used 

    $translateProvider.useSanitizeValueStrategy('sanitizeParameters'); 

and it seems to work now.
