### ISSUE TITLE
translate-namespace is not working

### ISSUE THREAD

**Issue by Steve30** [angular-translate/angular-translate#1348]

**Comment by denjaland** [comment]
Hi - are you taling aabout a plugin?  if you are, I'm interested to know since I'm actually looking for some way to lazy-load translated items based on its namespace :-)

**Comment by knalli** [comment]
@Steve30  Nobody will know the issue using such a short message. Without any details, I'll close this.

**Comment by pdanpdan** [comment]
It looks like the example from
https://angular-translate.github.io/docs/#/api/pascalprecht.translate.directive:translateNamespace
in the bottom of the page is not working

**Comment by knalli** [comment]
The demo is not working because we have forgot to update the library within the docs itself.

Updating to use the latest 2.8.1 and it works: http://plnkr.co/edit/HyGOfQ4FUJghwnRnP5CC?p=preview

**Comment by Steve30** [comment]
I see! Thank you!
