### ISSUE TITLE
Understanding the different sanitisation behaviour of the translate directive and filter

### ISSUE THREAD

**Issue by delbertooo** [angular-translate/angular-translate#1349]
As fas as I see, the sanitisation of the translate directive and the filter can nearly never be equal if used in templates.

If you use the filter in an ng-bind expression like `{{ 'HEADLINE' | translate }}` the ng-bind will always escape the result. If you enable sanitisation in angular-translate, the result will be escaped twice (see http://plnkr.co/edit/gmkba8ksJPXIbQmkYqm6?p=preview).

With this behaviour it seems like it's never possible to use the directive and the filter in the same application. *What are the thoughts behind this behaviour? Is it really advantageous?*

I currently bypassed this behaviour with an additional translateRaw filter and a custom sanitizer. The filter tells my sanitizer to skip the next sanitisation and therefore the results of the directive and my filter are equal. Even if this gets the job done, it just doesn't feel right.

**Comment by knalli** [comment]
I've created a sheet some weeks ago at http://plnkr.co/edit/8BHONOjhsxBxxO9oVYOK?p=preview We aren't finished with this, any ideas are welcome!

**Comment by knalli** [comment]
> With this behaviour it seems like it's never possible to use the directive and the filter in the same application.

The filter's value is escaped by AJS itself. We do not have this under control. If you use filters in AJS, you always should be aware of this.

Again: Suggestions and ideas are welcome, please have a look at the #1101
