### ISSUE TITLE
Ionic ion-header-bar button-right width not calculated correctly

### ISSUE THREAD

**Issue by leschirmeur** [angular-translate/angular-translate#1350]
When using an Ionic ion-header-bar as follows, the button-right width is not calculated properly:

```
<ion-header-bar class="bar-light">
        <a class="button button-icon icon slicon slicon-close" ui-sref="start"></a>
        <h1 class="title" translate>register.finishprofile.navbar.label.welcome</h1>
        <button class="button button-clear button-positive button-strong" type="submit" translate>common.button.next</button>
```

However, if passing the translation id as an attribute value, the button width is calculated correctly:
````
<ion-header-bar class="bar-light">
        <a class="button button-icon icon slicon slicon-close" ui-sref="start"></a>
        <h1 class="title" translate>register.finishprofile.navbar.label.welcome</h1>
        <button class="button button-clear button-positive button-strong" type="submit" translate="common.button.next"></button>
    </ion-header-bar>
```

So, to me it seems that Ionic takes the length of the translation id if the id is not set as an attribute to determine button width, BEFORE the translation id is replaced by angular-translate.

I am not sure if this repo is the appropriate place to file this issue or if I should rather head over to the Ionic repo...

**Comment by knalli** [comment]
@leschirmeur The library angular-translate is not responsible for any DOM sizing calculations. Actually, except for looking for translate attributes and reading/writing innerHTML, it is even not related to DOM things.

Even if Ionic would have a manual event trigger recalculating everything, we could not invoke this.

I would suggest a stackoverflow question. You can even reduce the testcase w/o angular-translate: Just apply any (longer) text with a timeout.
