### ISSUE TITLE
Translating from an array of values

### ISSUE THREAD

**Issue by corneadoug** [angular-translate/angular-translate#1351]
Hi,

I'm still learning all the ropes of using angular-translate, and I found a particular case in which i'm not sure what the best solution is.

I have an array values `type = [ 'DEFAULT', 'SIMPLE', 'REPORT'];`
which are shown as a list through `ng-repeat`

I was thinking of having translations like: `TYPE_DEFAULT: 'default'`
and maybe something like that to show it: {{ 'TYPE_{{myvalue}}' | translate}}
however this is not working.

Would the best way be to make a rendering function that use the translate service like this?
```
$scope.showType = function (type) {
    $translate(‘TYPE_’ + type).then(function (text) {
      return(text);
    });
  };
```

Thank you,

**Comment by tspaeth** [comment]
If you use the filter, do it this way:
```
<ul>
  <li ng-repeat="myvalue in type">
    {{ 'TYPE_' + myvalue | translate }}
  </li>
</ul>
```
