### ISSUE TITLE
translations are not being updated on disabled elements

### ISSUE THREAD

**Issue by denjaland** [angular-translate/angular-translate#1354]
Hi,

We have buttons that are disabled by default; and only enable when the form is valid and ready for submission.  When the user changes the language, all content is correctly refreshed, but the caption on the button remains unchanged.  This only occurs when the button is disabled.

Is this a known issue?  I'm guessing this is caused by browser behaviour not allowing for ANY update on disabled elements, but maybe we should build in an option to temporarily enabled when angular-translate updates the translated caption, and re-disable right after that?  I'm guessing it might cause flickering, but not having it translated seems even worse to me.

THanks for considering :-)

David.

**Comment by denjaland** [comment]
To add to this.  It seems to be only occuring in MacOS Safari.

**Comment by knalli** [comment]
@denjaland  Please prepare a working demo of this issue.. i.e. in plnkr. Which version of Safari is affected?

**Comment by denjaland** [comment]
I'll dig into that asap.

**Comment by tspaeth** [comment]
friendly reminder: @denjaland any update?

**Comment by knalli** [comment]
Demo is here, I don't see an issue. http://plnkr.co/edit/ueNaUBOXje7Qx60IMBMJ?p=preview

Closed due inactivity.

**Comment by denjaland** [comment]
sorry - I lost sight of this issue.  It can be closed as you did though.
