### ISSUE TITLE
translate all values in a JavaScript object

### ISSUE THREAD

**Issue by xtoff** [angular-translate/angular-translate#1355]
Is it possible (if so, what's the best way) to translate all values in a JavaScript object.

An example:

```javascript
{
  "Questionnaire": {
    "Questions": [
      {
        "Question": "QUESTION_1",
        "Answers": [
          {
            "Answer": "ANSWER1_Q1"
          },
          {
            "Answer": "ANSWER2_Q1"
          }
        ]
      },
      {
        "Question": "QUESTION_2",
        "Answers": [
          {
            "Answer": "ANSWER1_Q2"
          }
        ]
      }
    ]
  }
}
```

I want to translate "QUESTION_1", "ANSWER1_Q1", "ANSWER2_Q1", "QUESTION_2", "ANSWER1_Q2".

**Comment by tspaeth** [comment]
Hi!
Did you see the chapter "Multiple translation IDs" in the manual? 
See http://angular-translate.github.io/docs/#/guide/03_using-translate-service

**Comment by xtoff** [comment]
Oh, didn't see that chapter :)

I think that helps me yeah.. The only problem is that I never know the structure of my JavaScript object. It is possible to have more questions or answers..

**Comment by tspaeth** [comment]
Well, but angular-translate is only a translation module, not a business logic for your app :-).You can experiment with custom stuff, but in general I'd advise that you just give the translation logic the exact keys you need instead of relying on what the translation file provides. If you need the JSON for defining your questionnaire - angular-translate is not the right thing to look for in the first place...

**Comment by xtoff** [comment]
I understand :) I already use angular-translate in my app and the keys in my Javascript object are also used in a html page in my app with angular-translate. I'm going to try to extract the keys an put them in an array, so I can give as a parameter to the $translate service.

**Comment by knalli** [comment]
Already like @tspaeth  said: We are only serving translations. Multiple ids can be translated, but that's it. We try it Keep It Simple and Stupid.
