### ISSUE TITLE
`proposedLanguage` does not get reset after being confirmed

### ISSUE THREAD

**Issue by rkoch** [angular-translate/angular-translate#136]
Hey there,

I found a problem with `$translate.proposedLanguage()` where `$nextLang` does not get reset after confirming an async loaded translation file.

I created a plunker to reproduce this issue: http://plnkr.co/edit/rQUnQv?p=preview

Can you look into that?

Thanks in advance.

**Comment by prithveesh** [comment]
@PascalPrecht I am trying to load 2 files one after another on different condition at the load time, and its the same issue, $nextlang variable is not getting undefined. So the 2nd file is not getting loaded. 
Please find a sample code at 
http://plnkr.co/edit/2E7bWJXphRklwvC1I82x?p=preview
