### ISSUE TITLE
multiple translations from project and components do not work together

### ISSUE THREAD

**Issue by SebastianPickl** [angular-translate/angular-translate#1360]
In my project, i have a de_DE.json, which is included with

    $translateProvider.useStaticFilesLoader({
        prefix: 'translation/',
        suffix: '.json'
    });

    $translateProvider.preferredLanguage('de_DE');

One of the components i use has its own translations, which are included in the javascript code:

    angular.module('testmodule').config(['$translateProvider',
      function ($translateProvider) {
        var translations = {
          'testmodule': {
            'ui': {
              'datepicker': {
                'ok': 'Schließen',
                'clear': 'Löschen',
                'currentDate': 'Heute'
              },
              'panel.action': 'Ändern',
              'multiselect': {
                'empty': 'Die Liste ist leer.',
                'noMoreOptions': 'Alle vorhandenen Optionen wurden bereits hinzugefügt.'
              },
              'table.cell': {
                'boolean.true': 'Ja',
                'boolean.false': 'Nein'
              },
              'filter': {
                'booleanValue.true': 'Ja',
                'booleanValue.false': 'Nein'
              }
            }
          }
        };
        $translateProvider.translations('de_DE', translations);
        $translateProvider.translations(translations);
        if ($translateProvider.preferredLanguage) {
          $translateProvider.preferredLanguage('de_DE');
        }
      }
    ]).value('preferredLanguage', 'de_DE');

Since the javascript code is executed and the translations of my module are loaded first, the actual translations file is never loaded.

It seems like angular-translate only loads the file if there is no other translation information for the selected language.
In my opinon, it should try to load a language file if a key is not available for the selected language( e.g. there are german translations, but the key common.foo.bar can not be found)

**Comment by tspaeth** [comment]
Can #1125 help you getting some ideas? And by "parameter" you mean key?

Completely mixing the multiple translation table "additions" from different sources per language in memory is - as far as I still know - not really possible until now and we've had also some tickets about that (can't find them quickly).

**Comment by SebastianPickl** [comment]
Thank you for your quick answer!
Yes, i meant key, O've edited my Answer.
My issue was actually quite similar to #1125 and I managed to get my code working with the https://github.com/juristr/angular-translate-loader-pluggable library.
