### ISSUE TITLE
ng-bind-html does not work

### ISSUE THREAD

**Issue by outilio** [angular-translate/angular-translate#1362]
Hi all,

I have a similar problem like in issue #409. In my project I used a JSON file for my translations e.q

"Next": "Weiter"

If I try to used it in my html part, this works:

<code>
<span>{{'Customer' | translate}}</span>
</code>

My output is "Weiter".
If I try to use this, my output is in each case empty...

    <span ng-bind-html="Next  | translate"></span>

Have anyone an idea?
Thanks a lot

**Comment by tspaeth** [comment]
two things:

1) check if you have ngSanitize included - read https://docs.angularjs.org/api/ng/directive/ngBindHtml

2) 
´´´
<span ng-bind-html="'Next'  | translate"></span>
´´´

should be the correct way

**Comment by knalli** [comment]
`Next | translate` is a filter, what should `ng-bind-html` make this better?

**Comment by outilio** [comment]
1) ngSanitize is still included
2) I tried this before, but this does not work

I have no ideas anymore :(

**Comment by tspaeth** [comment]
What's the issue? See
http://plnkr.co/edit/2lAzG0Md7O2IYvXBEgjr?p=preview

**Comment by outilio** [comment]
I got the failure...

I used ng-show="Next". If I delete this tag, It will be translated!

    <div ng-show="Next" class="alert alert-warning">
        <span ng-bind-html="'Next' | translate"></span>
    </div>

**Comment by tspaeth** [comment]
Well... if Next is not true or false... erm... yes.

**Comment by nmoinvaz** [comment]
I noticed that before the translation is loaded 'Next' will be displayed. If you want to change this behavior you can do something like this:
```
<div ng-show="Next" class="alert alert-warning">
    <span ng-if="('Next' | translate) != 'Next'" ng-bind-html="'Next' | translate"></span>
</div>
```

**Comment by Brijeshlakkad** [comment]
I found solution on: [ng-bind-html](http://erikaugust.com/thoughts/ng-bind-html/)
insert $sce (Strict Contextual Escaping) service to your controller.
and then use `ng-bind-html`.
For instance:
```
<div ng-bind-html="success_modal_val"></div>
<script>
myApp.controller("BrijController", function($scope,$http,$sce) {
    $scope.make_transaction=function()
    {
         $scope.success_modal_val=$sce.trustAsHtml("<h2>BL</h2>");
    };
});
</script>
```
