### ISSUE TITLE
Can I split translation file?

### ISSUE THREAD

**Issue by Taewa** [angular-translate/angular-translate#1364]
Hello guys.

I want to split translation file like 'fr.js', 'en.js'

and Inside file it would be

$translateProvider.translations('fr', {
		HELLO: 'BONJOUR',
	});

Like that.

Because the 'config' angular function getting bigger.

How can I make it?

Thank you.

**Comment by knalli** [comment]
I don't get it. Please elaborate this a little bit.

**Comment by tspaeth** [comment]
Blind guess... look for loaders?
http://angular-translate.github.io/docs/#/guide/12_asynchronous-loading

**Comment by Taewa** [comment]
@knalli @tspaeth 
I am sorry for not enough info and thank you guys for quick response.
Simply, I want to create javascript file for all the translation data.

http://angular-translate.github.io/docs/#/guide/07_multi-language
This one helped me. thank you @tspaeth 

But I have still a question.
According to the below url, you will see 'Source' section.
http://angular-translate.github.io/docs/#/guide/07_multi-language

In this source, translation sources are out of angular. (translationsEN, translationsDE)
I thought in the beginning, I could put these into either provider or factory.
However, since these provider or factory can not be injected into angular config, I couldn't make it.
So I put this translation code out of angular too. It works.
But I am wondering if it's possible to put inside angular.

Thank you!

**Comment by tspaeth** [comment]
@Taewa what does "out of angular" mean? It is Javascript. So it depends where you put it and if the variable is visible in the config-section of an app or not?!

**Comment by knalli** [comment]
I think you are just at the beginning of AJS. That's okay, but we don't have the resources providing that support (here).

Guessing your `out of angular` is just a global variable in this specific context. Well, you can make this, also it is definitely not the recommended way (thinking of app scaling).

>  However, since these provider or factory can not be injected into angular config, I couldn't make it.

I don't get it. In a `module.config` you can inject providers (actually you can only inject them). You can even provide (earlier of course) a module's constant and use this as a static translation (just as in the example). But also not recommended.

Thinking of a good style: Either stick with `translateProvider.translations(lang, texts)` or a specific loader.
