### ISSUE TITLE
don't find foo/bar.json

### ISSUE THREAD

**Issue by ccomparone** [angular-translate/angular-translate#1365]
In the page of Asynchronous loading in wiki guide there is writter like this:

$translateProvider.useUrlLoader('foo/bar.json');

But I cannot find the file foo/bar.json in the suourse code and folders.
Does it refer to an onlne web service or a local file?

**Comment by tspaeth** [comment]
Just create yourself some json file containing translation content and point to it. 
It is just an example "foo" and "bar" is quite common for dummy text :-)

**Comment by ccomparone** [comment]
ahh ok I understand! Thank you ;-)
