### ISSUE TITLE
How can i capitalize my label?

### ISSUE THREAD

**Issue by yobre** [angular-translate/angular-translate#1366]
```javascript
  $translateProvider.translations('en-US', {
    'LANGUAGE': 'language'
    'WIDZ_LANG_AVAILABLE': "we are available in {{value}} languages"
  })
````

If i want to have  {{ 'LANGUAGE' | translate }} in some case capitalized(Language) and in other case de-capitalized(language)? exist filter or some parameter that does this?

I also need when I use it in this way:
```html
<h5 translate="WIDZ_LANG_AVAILABLE" translate-values="{ value: '{{languages.length}}'}"></h5>
```

Thanks to all

**Comment by tspaeth** [comment]
Well, yes, write a filter, convert it with Javascript. Whatever you want. 
It's nothing that looks like something related to angular-translate, or? We try to keep the module as generic as possible and you can always extend it with whatever you find or develop.

**Comment by yobre** [comment]
Ok but in this case

```html
<h5 translate="WIDZ_LANG_AVAILABLE" translate-values="{ value: '{{languages.length}}'}"></h5>
```
I can't use angular filter and i don't know how to capitalize. have you any ideas?

**Comment by tspaeth** [comment]
As this is somehow very, very special - you could still write an own directive, do some logic in there and call $translate from there.

**Comment by knalli** [comment]
Second that: Such custom logic can be self made with a custom filter and using the `$translate.instant` service.
