### ISSUE TITLE
use $translateProvider.preferredLanguage's problem

### ISSUE THREAD

**Issue by wangpengxpy** [angular-translate/angular-translate#1372]
when I use $translateProvider.preferredLanguage("zh-cn") is right,but use  $translateProvider.preferredLanguage(Browser.language) is wrong?why?

Browser.language:get browser language，the result is zh-cn！
I don't know where is wrong，hope get the reason and  answer，thanks in advance !

**Comment by tspaeth** [comment]
Can you point me to where The call to "Browser.langauge" comes from or where this is defined in browser specs?

**Comment by wangpengxpy** [comment]
Browser.language = navigator.language;

so the result is zh-cn but wrong....

**Comment by tspaeth** [comment]
What does "wrong" mean - do you have another language set as primary in your browser? Which browser do you use? Which languages are configured in it / the operating system.
There are a lot of buggy places for language detection client-side only, so I'd strongly suggest to send a "language dummy ping" to the server and resolve that result.

**Comment by wangpengxpy** [comment]
hi,solve the problem,it's result from my code...
thanks for your reply.
