### ISSUE TITLE
Using directive within <a> tag

### ISSUE THREAD

**Issue by cathaloneill** [angular-translate/angular-translate#1373]
Hi 
I am trying to apply angular-translate using the 'translate="KEY"' directive.

However, if I add this to a <p> tag and then to an <a> tag within this, only the first translation appears. When I view this in console, the translation appears to work, but it does not appear on the screen. 

    <p translate="CLICK">
        <a href="http://www.google.com" translate="HERE"></a>
    </p>

This should output as:
Click [here](http://google.com)

But it appears only as:
Click

Thanks for any help.

**Comment by chris0550** [comment]
The directive is working fine. See my plunker: http://plnkr.co/edit/21ys4WwiWKh4VaomFNGQ?p=preview

**Comment by cathaloneill** [comment]
I am not trying to use two different <a> tags. I am trying to use a <p> tag and an <a> tag within it. See my plunker: http://plnkr.co/edit/DLD4FNUD0I9w5DpbzxFI?p=preview

**Comment by chris0550** [comment]
The problem is that the \<p> surrounds the \<a> tag. The translate directive replaces the content (which is the link) of \<p> with the translation. So the result is \<p>Click\</p>.

**Comment by tspaeth** [comment]
Nesting multiple translation directives does not work due to the replacement. Yes. Expected behavior currently.

**Comment by albi34** [comment]
If you want nested translations you can use the translate filter instead of the directive: http://plnkr.co/edit/u8Tymno17T4L2BVJBugS?p=preview

**Comment by knalli** [comment]
We have a [change](cafc0cfb4340c09fe8a81a77cda475a45aeedd0d) in the pipeline (currently on canary only), which will touch this issue slightly. But in the end: If you use `<elem translate="CLICK">`, then the translation of `CLICK` will be used as `innerHTML` of the element `elem`.  That's actually one core feature of the directive.
