### ISSUE TITLE
Feature Request: Access list of translation items from external

### ISSUE THREAD

**Issue by iJungleboy** [angular-translate/angular-translate#1374]
Background
1. I have a fairly large AngularJS + angular-formly + angular-translate front end...
2. which uses 2-3 non-angular components like tinyMCE
3. I have custom translations on these third party, non-angular components
4. ...which I must provide with a list of translations while they load

I have two options: 
1. create another, completely separate language management for these components
2. manage the languages in angular-translate, and then write a few lines of code to pass on the relevant values

I prefer option two, but this requires that I can say something like (pseudo code)

```
var x = translate.dictionary.Extensions.TinyMce;
foreach(key in x)
   addToTinyMce(key, ...)

```

this is not possible. As far as i can see the list of translations cannot be retrieved from outside.

**Comment by knalli** [comment]
@iJungleboy  Well, we can provide something like `$translate.getCurrentTranslations()` only as the `translate service` does not know  which translation could be possible. Said this, if you would call `getCurrentTranslations()` before the loader has (successfully) completed, you would even get an empty list. If you use something like a partial loader, you will get incomplete list. If you use a mixed setup with fallbacks, this actual "list of current translations" is not that easy as it looks in the first view.

I'll mark this as a feature request with call for contribution. A nice idea, but definitely with some work to do.

**Comment by iJungleboy** [comment]
For anybody else trying to find a temporary workaround, my solution is to keep a comma-separated list of keys for all items I need to forward to TinyMCE, and then loop through these to lookup the translations and then forward them to TinyMCE. Not perfect, but works and keeps all my translations in one place.

**Comment by tomlandia** [comment]
+1 would be perfect if you could read and overwrite translations from outside of angular. Right now I'm using a custom loader using translations from an external variable.

**Comment by headcrabmeat** [comment]
How about if it just returns object like `$translationTable[traslation_id]`

**Comment by knalli** [comment]
Landed.

**Comment by iJungleboy** [comment]
Very cool :). I'll test it within the next few weeks.

**Comment by iJungleboy** [comment]
To anybody who is interested - here's how I used the angular-translate table to translate TinyMCE in [2sxc](https://github.com/2sic/2sxc)

```javascript
    // Initialize the tinymce resources which we translate ourselves
    function initLangResources(editor, language, $translate) {
        var keys = [], mceTranslations = {}, prefix = "Extension.TinyMce.", pLen = prefix.length, primaryLan = "en";

        // find all relevant keys by querying the primary language
        var all = $translate.getTranslationTable(primaryLan); 
        for (var key in all)    
            if (key.indexOf(prefix) === 0) 
                keys.push(key);

        var translations = $translate.instant(keys);

        for (var k = 0; k < keys.length; k++)
            mceTranslations[keys[k].substring(pLen)] = translations[keys[k]];
        tinymce.addI18n(language, mceTranslations);
    }
```
