### ISSUE TITLE
$translate service not working with partial loading (part 2)

### ISSUE THREAD

**Issue by shiruken1** [angular-translate/angular-translate#1375]
I've just spent a day at this, and although I wish the prior posts on this issue would've helped, I'm still stuck. I would appreciate any advice.

I haven't worked with Plunker before, so I have no clue why it's complaining that the ui-router or translate modules aren't there. [Plunker](http://plnkr.co/edit/Rn6kr0JCRn5UzTyKDFVU)
My config:
```
	angular.module('app.config').config(function($translateProvider) {

	    $translateProvider.useSanitizeValueStrategy('escapeParameters');

	    $translateProvider.useLoader('$translatePartialLoader', {
	      urlTemplate: '/lang/{lang}/{part}.json',
	    });
	    
		$translateProvider.use('en');
    	$translateProvider.preferredLanguage('en');

        $translateProvider.fallbackLanguage('en');
    });
```

After my routes config:
```
	angular.module('app.routes').run(function ($rootScope, $translate, $translatePartialLoader) {

		$rootScope.$on('$stateChangeStart', function(event, toState, toParams, fromState, fromParams){

			var app = toState.name.indexOf('.');
			if(app !== -1) {

				var part = toState.name.slice(app+1, toState.length);
		    	$translatePartialLoader.addPart(part);

		    	var from = fromState.name.indexOf('.');
				if(from !== -1) {

					var old_part = toState.name.slice(app+1, toState.length);
		    		$translatePartialLoader.deletePart(old_part, true);
				}
			}

		});

		// refreshes the view, having loaded the translation tables
		//@TODO: FOUC issue
		// $rootScope.$on('$translateChangeSuccess', function () {
		$rootScope.$on('$translatePartialLoaderStructureChanged', function () {
			$translate.refresh();
		});

	});
```

The translation filter works. Passing it as an attribute works. Interpolation works.

...yet I can't use the service at all:
```
	    	$translate('TEST').then(function(out) {
	    		$log.info('out: '+out);
				vm.test = out;
	    	});

                $scope.$on('$translateChangeSuccess', function() {
	    		$log.info('out: '+out);
			vm.test = $translate('TEST');
	    	});
```

Neither one of these give me anything. Please help!

**Comment by tspaeth** [comment]
@shiruken1 It is complaining because you haven't add the dependencies in the HTML file correctly as far as I can see. If you don't include the scripts correctly - it won't work :)

**Comment by shiruken1** [comment]
@tspaeth Whoops! Thanks for that.

"Now I'm getting: $translateProvider.useSanitizeValueStrategy is not a function" :disappointed:

**Comment by knalli** [comment]
You are using angular-translate v1.1. Not the latest one... ;)

**Comment by shiruken1** [comment]
That's what I get for copy-pasting... Alright, all set.

Just kidding, now it gives me an unintelligible error. :sob:

**Comment by tspaeth** [comment]
You could start off with a Plunkr @knalli created (updated with 2.8.1 some weeks ago)... - the code showing some things is from some experiments, but the dependencies / script links should be a good starting point...
 http://plnkr.co/edit/2lAzG0Md7O2IYvXBEgjr?p=info

**Comment by shiruken1** [comment]
@tspaeth Thanks for that! Alrighty, the Plunker's finally ready.

Thanks for your help, and thanks in advance for any tips/advice!

**Comment by tspaeth** [comment]
Besides some typos that also needed to be fixed, here is a basic one, but I'm not so familiar with controlleras in combination the the translate-promises, ui-router AND partial loader... the scope-vars get lost during page transitions back and forth - no time to look deeper into it now.
For a "how to" I'd suggest: Use stackoverflow as you'll reach a broader base!

http://plnkr.co/edit/BeAClaiOxvGN6kKpIINM?p=preview

**Comment by shiruken1** [comment]
@tspaeth You got it working!

Besides my typos and the obvious lack of "var vm = this;" what did you change?

**Comment by shiruken1** [comment]
Although it seems to go away after a few back-and-forth clicks between Page1 and Page2

**Comment by shiruken1** [comment]
Wow... holy typos, batman. I need to try reading this out loud 3 times fast:

$translatePartialLoaderStructureChanged

LOL.

Alright, well, once again. thank you for your help, @tspaeth. My plunker's working, so now I'll go see what's different about my app.

Cheers!

**Comment by shiruken1** [comment]
BTW, for anyone interested in figuring out this bug: it still, nonetheless, craps out after a few back-and-forth clicks.
