### ISSUE TITLE
No 2.9.0 tag in bower-angular-translate-storage-local

### ISSUE THREAD

**Issue by alexnoox** [angular-translate/angular-translate#1376]
Hi,

I wanted to update to v2.9.0. It seems a tag is missing on repo ```bower-angular-translate-loader-static-files```. The other repositories seems to be tagged.

```
bower resolved      git://github.com/PascalPrecht/bower-angular-translate-loader-static-files.git#2.9.0
bower ENORESTARGET  No tag found that was able to satisfy ~2.9.0
```

PS: Thank you for this awesome project!

Alex

**Comment by knalli** [comment]
@alexnoox Sorry, missed pushing the tags. :(
