### ISSUE TITLE
Having race condition with static loader and yeoman scaffold

### ISSUE THREAD

**Issue by brenolf** [angular-translate/angular-translate#1378]
I'm using angular translate with a yeoman scaffold for my project. I've made a simple module to handle the loading of the translations and be accessible throughout my entire project.

If I run `gulp serve`, then everything runs as expected and I get my files translated. However, when serving the `dist` folder I don't get my translations, just their keys instead. It seems that Angular is rendering the views before the json is cached with the translation. Since I wrote my own filter using `.instant()`, I believe that could be a problem. Also, I don't know whether or not this is an issue with angular-translate or the way the files are getting compressed.

I also tried using `$translateProvider.forceAsyncReload(true);` but it didn't help either.

**translator.config.js**
```js
    (function () {
      'use strict';

      angular
        .module('translator')
        .config(configure);

      /* @ngInject */
      function configure($translateProvider) {
        $translateProvider.useStaticFilesLoader({
          prefix: '/assets/i18n/landing/',
          suffix: '.json'
        });

        $translateProvider.preferredLanguage('en');
        $translateProvider.useSanitizeValueStrategy('escaped');
        $translateProvider.useLocalStorage();
      }
    })();
```

**translator.filter.js**
```js
    (function () {

      'use strict';

      angular
        .module('translator')
        .filter('translate', translate);

      /* @ngInject */
      function translate ($translate) {
        return function (input) {
          return $translate.instant(input);
        };
      }

    })();
```

**Comment by tspaeth** [comment]
Well, yes. Using instant with async loaders to retrieve the content / translations from the server might cause weird results as instant is simply doing what it says: Instantly translate the keys.
If the $http calls haven't been finished yet it will not take care of this.

**Comment by brenolf** [comment]
Thanks @tspaeth, so I basically deleted my filter and it started to work.
