### ISSUE TITLE
Fallbacks not working with urlLoader

### ISSUE THREAD

**Issue by BrentWheeldon** [angular-translate/angular-translate#1379]
Hi there,

We use `urlLoader` to asynchronously load our translations from our backend.

The [documentation](http://angular-translate.github.io/docs/#/guide/08_fallback-languages) says that we can chain `translations` calls and then finish with a call to `fallbackLanguage`, like:

```
$translateProvider
  .translations("en-US")
  .translations("en-GB")
  .fallbackLanguage("en");
```

However, `$translateProvider.translations("en-US")` returns `undefined`, so the chaining fails. I've searched around but haven't been able to find what I'm doing wrong.

Any ideas?

Thanks!

**Comment by BrentWheeldon** [comment]
Work this out:

```
  $translateProvider.
    translations("en-US", {}).
    translations("en-GB", {}).
    fallbackLanguage("en")
  $translateProvider.forceAsyncReload(true)
```

We need to pass in empty objects, and then call `forceAsyncReload`. This isn't very obvious, why do I need to call `forceAsyncReload`?

**Comment by tspaeth** [comment]
Could you show a complete example as a plunkr? Just with the config - and it looks a bit weird if you don't define any translation keys, define an inline translation table and  I don't know what the expectation you have would be?

**Comment by BrentWheeldon** [comment]
@tspaeth I may be totally misunderstanding how I should be configuring this. All of our translations come from the backend, we have no inline translations. If that's the case, do we need to declare these translations? Can we just do `$translate.use("en-US")` at runtime to change to "en-US"? Because that didn't work. Do I need to do the `forceAsyncReload` after the `use` call?

**Comment by tspaeth** [comment]
Did you read the next chapters besides the one you referenced on fallbacks?
Especially http://angular-translate.github.io/docs/#/guide/12_asynchronous-loading
or partials?
Usually you configure this as the async loaders

**Comment by BrentWheeldon** [comment]
Yes, and it works for the first language. But when I change languages (with a `use` call) none of the translations are found for the new language.

**Comment by tspaeth** [comment]
But for the setup above you pointed out, we're missing your async-loader configuration. Maybe to better support you - can you put up a complete plunker?

**Comment by BrentWheeldon** [comment]
Sorry, I'd excluded that. A complete example of what our working, though probably not optimal, solution is [here](https://plnkr.co/edit/ivzuftQrVGnBZ53PSJl0). Is there a cleaner way to do what we're doing?

**Comment by tspaeth** [comment]
Hm, have you seen the examples in the demo folder here? 
Especially I mean 
https://github.com/angular-translate/angular-translate/blob/master/demo/ex9_load_dynamic_files.htm

As you can see, there is no need to define "empty" translations.
If you simply add a fallback (de in this case) to the setup phase - I've tested locally:

```
$translateProvider.fallbackLanguage('de');
```

- the demo will try to find the translation in (without the cookie set) en_US and if this is not successful, look for it in a file / resource de.json on the server (as configured).

**Comment by BrentWheeldon** [comment]
Going to close this for now - I've not had a chance to get back to it yet. I'll update when I pick it up again.
