### ISSUE TITLE
Number of page watchers increased with introduction of multiple languages support

### ISSUE THREAD

**Issue by cstefanache** [angular-translate/angular-translate#1381]
Along with the commit:
https://github.com/angular-translate/angular-translate/commit/e591462af379150cb1bae29f493137cb825025b1
 the line 
 [306] scope.$watch('translateLanguage', updateTranslations); 

introduced a new watcher in each directive scope that might not be necessary. 
A provider configuration can be introduced in order to conditionally add the watcher in order to avoid long digest cycles for pages with many translation directives. Once disabled (watcher not present) the app can rely on: $translateChangeSuccess event in order to do the updates.

**Comment by knalli** [comment]
@cstefanache  Yes, that sounds to be a great optimization.

**Comment by cstefanache** [comment]
I will open a pull request for it soon.

**Comment by cstefanache** [comment]
Pull request opened: https://github.com/angular-translate/angular-translate/pull/1387. All the details are added in the pull request message. I changed my initial proposal with watchers on the translate-language directive in order not to introduce a new configuration and preserve the $watch functionality only when needed.
