### ISSUE TITLE
angular-translate-loader-url only stored on Bower

### ISSUE THREAD

**Issue by danpantry** [angular-translate/angular-translate#1382]
This prevents us lowly `npm` users from being able to use the urlLoader. Any chance it could be published to npm too?

**Comment by knalli** [comment]
https://www.npmjs.com/package/angular-translate-loader-url is available w 2.9.0. Do you have a local cache?

**Comment by danpantry** [comment]
Hm, that's interesting. When I searched for `angular-translate` on the npmjs website it wasn't coming up. Thanks.
