### ISSUE TITLE
Load templates based on language

### ISSUE THREAD

**Issue by iamdriz** [angular-translate/angular-translate#1383]
In our app we have a complex set of templates using UI.Router to create nested states.

For we might have a url like: `/introduction/vision-for-health-and-wellbeing`

And the following config:

~~~
exampleApp.config(function($stateProvider, $urlRouterProvider, $locationProvider) {

	$stateProvider

		.state('maincontent',
		{
			abstract: true,
			url: '',
			views: {
				'all': {
					templateUrl: 'partials/maincontent.html'
				}
			}
		})
			.state('introductionMaster',
			{
				abstract: true,
				parent: 'maincontent',
				url: '/introduction',
				views: {
					'header': {
						templateUrl: 'partials/introduction/_header.html'
					},
					'sidebar': {
						templateUrl: 'partials/introduction/_sidebar.html'
					}
				}
			})
				.state('vision-for-health-and-wellbeing',
				{
					parent: 'introductionMaster',
					url: '/vision-for-health-and-wellbeing',
					views: {
						'content@maincontent': {
							templateUrl: 'partials/introduction/vision-for-health-and-wellbeing.html'
						}
					}
				})
						
});
~~~

How could we translate these templates? As, as you can see we use a template file for each piece of content (because each page is varied in design and copy), so we'd like to avoid masses of placeholders inside each template file and would like to swap out the templates themselves based on language instead. (Though we do use the placeholders approach as well in some places).

So for example, have the templates for German pull out like: `templateUrl: 'partials/introduction/de/vision-for-health-and-wellbeing.html'`

Would it be a case of passing the language into the url string itself? e.g.

~~~
templateProvider: function($stateParams, $translate)
{
	  return 'partials/' + ( $translate.use() ? $translate.use() : $translate.preferredLanguage ) + '/introduction/vision-for-health-and-wellbeing.html';
}
~~~

**One problem with the above is that it just returns the url as a string and doesn't use the url as the template...**

Or is there a more robust and correct way to handle this? **Ideally we'd like it to fallback to the default language if the template doesn't exist or the language is invalid, much like it does for the placeholder replacement shown in the documentation.** And I'm not sure the above code would handle this.

Also we're not interested in having the language in the URL it would just use the standard Storage to get the language out, but needs to use this to load the correct template (if available).

**Comment by knalli** [comment]
Sorry for the delay.

I don't think this place is the right one for your question. We mostly discuss the technical aspects of angular-translate which is made for translating strings (as part of a template, service or more generally a component). The module is not made for controlling template content (aka replacing).

However, you can use the `$translateProvider` as part of the asynchronous `resolve` within route configurations. But that's more an aspect for your routing configuration.
