### ISSUE TITLE
Translate live feature

### ISSUE THREAD

**Issue by AVE-cesar** [angular-translate/angular-translate#1385]
In my application using your tool, I would like to be  able to translate a label live.

I would like to allow my application to be translated by a translator in situation.

I'll give a specific role to this kind of users and each label will appear with a link (or anything else) to allow the translation to be done live in one or several languages.

**Comment by knalli** [comment]
@AVE-cesar you idea is great, but I  don't think angular-translate is the right tool for this. One of the key concepts of angular-translate is loading/providing sets of translation texts -- and not a translation resolution by string. Perhaps this idea could be realized with a new approach (like in "angular translate v3" concepts), but at the moment not.
