### ISSUE TITLE
Make getLocale public

### ISSUE THREAD

**Issue by fridaberg** [angular-translate/angular-translate#1388]
I would like to get the browsers language and I found a function called getLocale which seems to do just that. Only problem is that I can't seem to access it. Can it be made public please?

**Comment by PaulAnnekov** [comment]
+1, I want to create my own language detection logic and getLocale() can help me to write less.

**Comment by knalli** [comment]
Landed in d0469ac

**Comment by knalli** [comment]
In next release 2.11
