### ISSUE TITLE
uniformLanguageTag add language only resolver

### ISSUE THREAD

**Issue by verbeeckjan** [angular-translate/angular-translate#1392]
Currently the uniformLanguageTag method only transforms existing language tags by adjusting the case, hyphens or underscores.

Is it possible to add a resolver that just drops all region information (just dropping everything starting from the first hyphen?). The reason I ask is because my app just adds translations for french, dutch and english listed as fr, nl and en. My browser tries to load en-us when I use determinePreferredLanguage.

**Comment by knalli** [comment]
Currently, the resolvers are not extensible. This is not fixed, but simply not implemented. 

Howver, [$translateProvider.registerAvailableLanguageKeys(languageKeys, aliases)](http://angular-translate.github.io/docs/#/api/pascalprecht.translate.$translateProvider#methods_registeravailablelanguagekeys) will do this.
