### ISSUE TITLE
reset available language registrations?

### ISSUE THREAD

**Issue by craig-at-rsg** [angular-translate/angular-translate#1393]
I have a Cordova app, and the first couple of pages use local translation files. Because it's difficult to re-release these apps, and because different groups of users will have different languages available, the rest of the translations come from the server.

So, here's an example of what I'm trying to accomplish: serve the local en.json translations for the first page from the phone's locale code of en-US, give the users a selection of languages from the server (e.g. en-US, en-GB, en-AU), and use the language the user picks. 

Below is the code I'm using to get started - I'm calling $translate.use([code from phone]) to kick things off, and then calling $translate.refresh() and $translate.use([code selected, from server]). The refresh is OK because the user will never revisit my first couple of pages - it's a one time signup, so I won't need those translations again, and I don't need to load with parts. My issue is that I'm setting aliases for languages during config using registerAvailableLanguageKeys, but I don't always want these aliases used after I know which languages are available to that user. If there's a way to re-register, I think that would solve the issue, or my code might be completely wrong and there might be some easy way to accomplish this, but I'm hoping there's some way to accomplish this...

`

		.factory('translationLoader', ['$q', '$translateStaticFilesLoader', 'prefs', 'logger', function ($q, $translateStaticFilesLoader, prefs, logger) {
			return function (options) {
				return prefs.getPromise("translations").then(
					function (translations) {
						logger.log('Translations from prefs for ' + options.key);
						if (options.key in translations) {
							return $q.when(translations[options.key]);
						} else {
							return $q.reject(options.key);
						}
					},
					function () {
						logger.log('Translations from files for ' + options.key);
						return $translateStaticFilesLoader({
							prefix: 'languages/',
							key: options.key,
							suffix: '.json'
						});
					}
				);
			};
		}])
		.config(['$translateProvider', function($translateProvider) {
			$translateProvider.useLoader('translationLoader', {});
			$translateProvider.registerAvailableLanguageKeys(['en', 'fr'], {'en-*': 'en', 'fr-*': 'fr'});
			$translateProvider.preferredLanguage('en'); // preferred == default
		}])
`

**Comment by knalli** [comment]
There is no way re-registering the language keys. But I'm not sure what the problem is.. although there would be a set of _n_ language keys set, the actual translations will be loaded only when requested.

However, as you already have a custom loader, you can solve this there. Your custom loader will check a specific state (i.e. via your prefs service?): either it uses a local translations strategy or it uses a standard remote file loader. And as you already have pointed out: The reset will be invoked with a `.refresh()`.

**Comment by craig-at-rsg** [comment]
@knalli Thanks for the response. 

I have a couple issues, most likely from my not understanding how this is supposed to work:

1. It looks like I have to call registerAvailableLanguageKeys. I was getting an error in an indexOf method because of an undefined array without this. I'd rather not register these up-front, and handle the lookup in my custom loader.
2. This registerAvailableLanguageKeys call is hard-coded into the client, and the mapping would map en-gb to en, so my custom loader gets asked for en, but en-gb might be an available language for a user after they register with the server.

Is there an easy way around this? Maybe the indexOf method could be patched to handle undefined arrays so I wouldn't need to register during config?

**Comment by knalli** [comment]
What "error in an indexOf method"? Please provide a working demo demonstrating your issue.

`registerAvailableLanguageKeys` is not a required config setting.

**Comment by craig-at-rsg** [comment]
I'll try to reproduce it - my first attempt didn't work; I've made too many changes since I put it in.

However, this call was failing because $fallbackLanguage was undefined: indexOf($fallbackLanguage, $preferredLanguage)

**Comment by craig-at-rsg** [comment]
I was calling useFallbackLanguage without specifying any fallbacks ahead of time; I was trying to have a local language fall back to its general one, so for en-US I was trying to do $translate.useFallbackLanguage('en'). Is this supported?

**Comment by craig-at-rsg** [comment]
Closing - I don't know what the issue was, but I have something working...

This catch lets me load an empty translation, which lets it just use the fallback instead:

`
return $translateStaticFilesLoader({
							prefix: 'languages/',
							key: options.key,
							suffix: '.json'
						})['catch'](function () { return {}; })
`
