### ISSUE TITLE
2.9.0 incompatible with angular 1.5.0 according to bower

### ISSUE THREAD

**Issue by dougamos** [angular-translate/angular-translate#1394]
As shown by `bower list` angular-translate is shown as incompatible with angular 1.5.0

angular-translate#2.9.0
─ angular#1.5.0 incompatible with >=1.2.26 <=1.5 (1.4.9 available, latest is 1.5.1-build.4601+sha.c966876)

**Comment by knalli** [comment]
Good catch. I wonder why bower does not resolve `1.5` to `1.5.0`. Sigh..

Until we fix this, use a resolution.

```
$ bower install angular-translate
bower angular-translate#~2.9.0 install angular-translate#2.9.0
bower angular#>=1.2.26 <=1.5   install angular#1.4.9

angular-translate#2.9.0 bower_components/angular-translate
└── angular#1.4.9

angular#1.4.9 bower_components/angular

$ bower install angular#1.5

Unable to find a suitable version for angular, please choose one:
    1) angular#>=1.2.26 <=1.5 which resolved to 1.4.9 and is required by angular-translate#2.9.0
    2) angular#1.5 which resolved to 1.5.0

Prefix the choice with ! to persist it to bower.json

? Answer !2
bower angular               resolution Saved angular#1.5 as resolution
bower angular#1.5              install angular#1.5.0

angular#1.5.0 bower_components/angular

$ cat bower.json
{
  "resolutions": {
    "angular": "1.5"
  }
}
```

**Comment by knalli** [comment]
Applied a patch `2.9.0.1` for the package angular-translate. Beware of caching issues.

```
$ bower install angular-translate#2.9.0.1

angular-translate#2.9.0.1 bower_components/angular-translate
└── angular#1.5.0

angular#1.5.0 bower_components/angular
```

**Comment by ArniDzhan** [comment]
could you please update release here too? 
https://github.com/angular-translate/angular-translate/releases

**Comment by knalli** [comment]
This is actually not a release in this repo. It effects the bower repo only, this one here is not published to bower.

**Comment by ArniDzhan** [comment]
sorry, what I meant is that if you try to install without specifying version 2.9.0.1 then it install 2.9.0
I though it has to do with this project not being updated.

**Comment by tregusti** [comment]
Why not use `<1.6` instead? `<=1.5.0` will prevent patch updates for angular to be supported. And since angular follows semver, supporting `1.5.0` should also allow support for `1.5.1-9`.

**Comment by knalli** [comment]
Eh.. good point. That's explaining why 1.5 has been used.

Ehm.. Angular (1.x) does not follow semver; and bower does not follow all details, too. Or why should <= 1.5 not work?

**Comment by tregusti** [comment]
My bad. No, they are not following semver, one dot off. But all releases in 1.5.x is most probably compatible with eachother. So you could support all of those. And even if <= 1.5 would work, as you wrote above, the intent is much more clear with < 1.6. At least for me.

**Comment by evilaliv3** [comment]
@knall: i think the same as tregusti that only 1.6 could allow the whole 1.5.x to be supported. 

given the current "<=1.5.0" at every 1.5.1, 1.5.2 etc that will fore sure follow easily you will have always to make a change and release.

i would suggest to have < 1.6 to be sure to not require to release a package every time and it will all the user that using it, eventually will notice that a stupid change angular 1.5.6 will cause a breaking change for us and we will put then <=1.5.6 but at that time for a reason.

**Comment by knalli** [comment]
Yes, <1.6 is fine. Hold on.
