### ISSUE TITLE
angular 1.5.0 compatibility in bower

### ISSUE THREAD

**Issue by Michael-Dawkins** [angular-translate/angular-translate#1395]
Some libs are trying to bump angular to 1.5.0.

The ~1.2.6 angular version specified in angular-translate bower.json cannot go up to 1.5.0 which causes conflicts, only resolved by a resolution.

Is the lib compatible with angular 1.5.0 and if so, is it possible to include that version range in the bower.json?

**Comment by knalli** [comment]
Should be solved, see #1394
