### ISSUE TITLE
Update AngularJS bower dependency to 1.5.0

### ISSUE THREAD

**Issue by julmot** [angular-translate/angular-translate#1397]

**Comment by evilaliv3** [comment]
Yep i'm here suggesting the same.

The current dependencyis setting is:
https://github.com/angular-translate/angular-translate/blob/master/package.json#L72
```
  "dependencies": {
    "angular": ">=1.2.26 <=1.5"
  }
```

this makes the resolution find 1.4.9 preventing to setup the 1.5.0 if not specifically forced indipendently.

**Comment by julmot** [comment]
yes. This will cause a conflict with angular-route as it uses 1.5.0.

**Comment by julmot** [comment]
made the same
https://github.com/julmot/jmBoilerplate/commit/560a06f91dc7f2877f3034adea67310a30ce7b36

**Comment by evilaliv3** [comment]
@knalli @PascalPrecht as far that you know is there some particular incomaptibility with angularjs 1.5.0?

**Comment by knalli** [comment]
No. It works. An update for the version range will come.
