### ISSUE TITLE
sanitize not working on directives with useSanitizeValueStrategy as 'sanitize'

### ISSUE THREAD

**Issue by darkylmnx** [angular-translate/angular-translate#1398]
Hi, i've been seeing a lot of issues avout accent and stuff with the sanitize as useSanitizeValueStrategy, but i'm having a problem here more dangerous for me.

The plugin does not sanitize text used with directives when useSanitizeValueStrategy as sanitize

I changed the doc's plunker to set html tag in the locale file string directly instead of with some interpolation parameter

http://plnkr.co/edit/gFMqn1INN1uqwqV7vF1P?p=preview

**Comment by knalli** [comment]
It *is* working. Perhaps you have a wrong assumption about "sanitization"? It will not simply escape the string. Instead of this it will allow html but without the bad things.

Said this, your comment in the code "// Enable escaping of HTML" is actually wrong.

> https://docs.angularjs.org/api/ngSanitize/service/$sanitize
> Sanitizes an html string by stripping all *potentially dangerous tokens*.

A bold tag is not dangerous, but a script or link tag.

**Comment by darkylmnx** [comment]
so why is the translate filter escaping ?

**Comment by knalli** [comment]
> so why is the translate filter escaping ?

Because that's how AngularJS is treating filters' output. It is encoded always.

**Comment by darkylmnx** [comment]
okay i see, thanks

2016-02-13 14:11 GMT+01:00 Jan Philipp <notifications@github.com>:

> so why is the translate filter escaping ?
>
> Because that's how AngularJS is treating filters' output. It is encoded
> always.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-translate/angular-translate/issues/1398#issuecomment-183662520>
> .
>



-- 
Cordialement Darkun91@gmail.com
