### ISSUE TITLE
Uncaught TypeError: $injector.get(...) is not a function

### ISSUE THREAD

**Issue by pascal08** [angular-translate/angular-translate#1399]
This error occurs only when I minify my code. I'm quite sure it has everything to do with minification. Debugging Angular leads to this line:

```
$injector.get($loaderFactory)(loaderOptions)
          .then(onLoaderSuccess, onLoaderError);
```

Hovering on $loaderFactory in DevTools shows: "TranslationLoaderFactory"

The TranslationLoaderFactory is registered the same way as in this boilerplate:
https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate

```
function TranslationLoaderFactory($q, LocaleModelService) {
    'ngInject';

    return function (options) {
        let deferred = $q.defer();
        let language = options.key;

        LocaleModelService.all(language).then(function(locales){
            // Get correct locale file
            deferred.resolve(locales);
        });

        return deferred.promise;
    };
}

export default {
    name: 'TranslationLoaderFactory',
    fn: TranslationLoaderFactory
};
```

```
angular.module('***', []).factory(***.name, ***.fn);
```

This is the piece of code where the error comes from:
```
module.exports = function (..., ...) {
    'ngInject';

    $translateProvider.useLoader('TranslationLoaderFactory');
    [...]
};
```

I guess I have to tell angular "TranslationLoaderFactory" should refer to the corresponding module, but haven't got a clue how to do this. 

Same question on StackOverflow:
http://stackoverflow.com/questions/35378584/angularjs-uncaught-typeerror-injector-get-is-not-a-function

**Comment by knalli** [comment]
Please be a more specific about the actual error message. I just have to guess the problem. :(

The corresponding lines in the service are [starting here](https://github.com/angular-translate/angular-translate/blob/b4b633c8e6b703387b15a324846ad968d554df6b/src/service/translate.js#L983). Clearly shown, we declare `$injector` explicitly by name. If this is not working, there would be much more serious issues.

Eventually `$injector` is not the problem, but the result of `$injector.get(...)`. In this case the provided service is not valid or wellknown -- in your case `TranslationLoaderFactory`.

If you use `$translateProvider.useLoader('TranslationLoaderFactory');`, you will have to declare such a service as well. Somewhere in your codebase something like `module.factory(TranslationLoaderFactory)` must exist.

**Comment by knalli** [comment]
Ah, I have overseen the line `angular.module('***', []).factory(***.name, ***.fn);`.

Probably you only missed to include the module `***` in your module configuring angular-translate`

**Comment by pascal08** [comment]
I have to apologize, I was on the wrong track. This issue was caused by something completely different. Though, I'm still groping in the dark why I was pointed to "TranslationLoaderFactory". 

Thanks for your reply and your time to look into the issue. Much appreciated. :+1:

**Comment by nooruddinabbas** [comment]
I know this is an old thread but could you tell me what was causing injector.get() is not a function. Because I am stuck with the same error...

**Comment by pascal08** [comment]
Check if your code is [minification-proof](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#minification-and-annotation). Also check if you are injecting the right dependencies. I remember it had something to do with a combination of these things.
