### ISSUE TITLE
Namespaces for translation dictionary.

### ISSUE THREAD

**Issue by cehoffman** [angular-translate/angular-translate#14]
I was wondering if you'd given any thought to adding namespaces to the translation dictionary.

My main use for it is to allow expressive translation keys while reducing the repetition and wasted space in the translation dictionary. For example

``` json
{
  "component1.label.foo": "Foo",
  "component1.label.bar": "bar",
  "component2.header.foobar": "foobar",
  "login.label": "Email",
  "login.submit": "Sign in"
}
```

becoming

``` json
{
  "component1": {
    "label": {
      "foo": "Foo",
      "bar": "bar"
    },
    "header": {
      "foobar": "foobar"
    }
  },
  "login": {
    "label": "Email",
    "submit": "Sign in"
  }
}
```

**Comment by stulentsev** [comment]
This flat object thing is great! What about the namespace fallback chain? Guess, it's not implemented? :)

**Comment by MattiJarvinen-BA** [comment]
@stulentsev @PascalPrecht that fallback chain would be nice.

> @cehoffman It might be beneficial to look at how ruby's i18n gem works. You can specify a chain of fallback lookup keys and rails does it so that if currently `component1.form3.confirm` button doesn't have any text the translate will use the text for `component1.confirm` and then `confirm` if that wasn't found. This allows the translators to drill down as specific as they want without ever needing to change the code base.

Is there an example implementation of that using useMissingTranslationHandler somewhere?

**Comment by franciscop-invast** [comment]
Probably too late, but according [to an article I wrote](https://medium.com/@fpresencia/understanding-gzip-size-836c74b66c0b) about testing GZIP, the first point about reducing _wasting space_ probably doesn't change anything/much since GZIP is very efficient for those.

But about an improvement for developers, I agree it's good :)
