### ISSUE TITLE
partial loader loads incorrect language

### ISSUE THREAD

**Issue by rolandjitsu** [angular-translate/angular-translate#1400]
So I have the following config:
```js
$translateProvider
	.useSanitizeValueStrategy('escape')
	.registerAvailableLanguageKeys(['en', 'da'])
	// .preferredLanguage('en')
	// .fallbackLanguage('en')
	.useLoader('$translatePartialLoader', {
		urlTemplate: '/app/components/{part}/{part}.{lang}.json'
	});
```
And during the config phase of ui-router, I add the parts as instructed in the docs:
```js
$stateProvider
	.state('root', {
		abstract: true,
		url: '/{locale:(?:da|en)}',
		views: {
			'main': {
				template: '<div ui-view="layout" layout="column" layout-fill flex></div>',
				controller: AppController,
				controllerAs: 'app'
			}
		},
		resolve: {
			locales: ($translatePartialLoader, $translate) => {
				console.log($translate.proposedLanguage(), $translate.preferredLanguage(), $translate.use());
				$translatePartialLoader.addPart('app');
				return $translate.refresh();
			}
		}
	});
```
What I want to achieve is when the user lands on the page and has a specific language set in the url `myapp.com/en/`, use the correct translations.

I tried this by using:
```js
$rootScope.$on('$stateChangeStart', (event, toState, toParams) => {
	console.log(toParams, $translate.proposedLanguage(), $translate.preferredLanguage(), $translate.use());
	$translate.use(toParams.locale);
});
```
But that does nothing and it does not load any part. If I set the preferred lang or the fallback lang, it, of course, loads that one, but not the one that I actually set in the url.

So my questions is, how do I make this work?

@knalli any pointers?

**Comment by rolandjitsu** [comment]
Ok, so the way I solved this was by using `.determinePreferredLanguage()`. It looks like on first page load, that is the only way to make this work. The only problem is that during config phase you do not have access to `$location`, so that makes things a little less ideal:
```js
const langs = [
	'en',
	'da'
];
$translateProvider.determinePreferredLanguage(() => {
	let parts = window.location.pathname.split('/');
	let part = parts.find((part) => langs.includes(part));
	return part;
})
```

**Comment by knalli** [comment]
I think you should stick with that. You should consider a fallback (if the path does not include a language).
