### ISSUE TITLE
ng-model vs. child $scope created by translate-attr-placeholder

### ISSUE THREAD

**Issue by rodrigobranas** [angular-translate/angular-translate#1403]
I really searched a lot to try finding some answers, sorry if it is duplicated somehow.

Today I tried to use ng-translate with placeholder using the translate-attr-placeholder directive.

It worked, however, this directive is creating a child $scope and, because of that, the ng-model creates an object inside of each directive $scope, instead of creating in the controller's $scope:

Example:

```
<input type="text" ng-model="auth.username" translate translate-attr-placeholder="Username"/>
<input type="password" ng-model="auth.password" translate translate-attr-placeholder="Password"/>

<button ng-click="login(auth)">LOG IN</button>
```

In this case, the login function receives an undefined auth.

If it's the normal behavior, no problem, of course that are many ways to deal with nested $scope. I just would like to know if I'm using it wrong?

Thanks a lot!

**Comment by rajush** [comment]
This is something I faced too. I had a similar question posted here: [https://github.com/angular-translate/angular-translate/issues/874](url)

For now, I'm using filter within the expression of the placeholder `placeholder="{{ 'text' | translate }}"` which binds the scope to the controller, until I find a way to figure it out. I hope there is way to solve this without using a filter.

Thanks!

**Comment by rodrigobranas** [comment]
Hello @rajush, is exactly the same situation that I experience. For the placeholder, I'm doing the same thing, with the filter. However, would be much better use the directive.

Thanks for replying!

**Comment by jculverwell** [comment]
Also not working for me using 
<input type="text"  translate translate-attr-placeholder="TL_USER_RECORD_ADD_A_TAG"/>

**Comment by rodrigobranas** [comment]
Maybe, one solution for this case would be using the "Controller as" approach. This way, you have control over the $scope object and could pass it's reference directly avoiding the new $scope.

**Comment by knalli** [comment]
Right. Currently we cannot resolve this without a scope.

Highly recommended: Use always expressions with dots. The *controllerAs* approach is a very good way! The other way is using the filter.
