### ISSUE TITLE
Text with empty value in fallback language shows the key as value

### ISSUE THREAD

**Issue by fmgs31** [angular-translate/angular-translate#1404]
If a text doesn't have a key in the selected language it will use the fallback language, but if that key in the the fallback language has an empty string as value then the value taken will be equal to the key instead of the empty string.

**Comment by fmgs31** [comment]
The reason for this is that there is a wrong checking when asking for the key in the fallback language. I can do the pull request if you want

**Comment by cniaulin** [comment]
Yes same issue here. @fmgs31, did you push the pull request ?

**Comment by iamdriz** [comment]
Is this the same as: https://github.com/angular-translate/angular-translate/issues/1413

**Comment by knalli** [comment]
Add an explicit test for this scenario: 2c15d26

**Comment by iamdriz** [comment]
@knalli Is that commit a fix for this issue? Thanks

**Comment by knalli** [comment]
Please have a look at the current canary, as well as #1413 including the corresponding PR. I've added the tests above covering your use case.

Please report if this does not help.

The fix will be available in the next release (2.11)
