### ISSUE TITLE
Value expressions not evaluated when using messageformat with ng-if

### ISSUE THREAD

**Issue by psaniko** [angular-translate/angular-translate#1406]
See plunkr: http://plnkr.co/XQHMOQAWnIFTKEybXLOy

Encountered an issue when using messageformat interpolation combined with ng-if directive as in:

`<span ng-if="falseThenTrue()" 
  translate="lorem.customers" 
  translate-value-count="{{ 1+1 }}" 
  translate-interpolation="messageformat">`

According to `console.log` angular-translate-interpolation-messageformat receives the expression as a string (not evaluated). Although an error is thrown the output is correct. It works as expected when
- Using `ng-show` instead of `ng-if`
- Using default interpolation
- Avoiding expression in translation value

We suspected `ng-if`'s behaviour of DOM recreation but then again why does it work perfectly with default interpolation?

angular: 1.4.7
angular-translate: 2.9.0
angular-translate-interpolation-messageformat: 2.9.0
messageformat: 0.1.6

**Comment by knalli** [comment]
The messageformat does not like invalid interpolation params, but the default/regular interpolation service does not care.

There is currently no well-known way of ignoring this specific situation (which you have already correctly identified).

A ongoing improvement is perhaps switching to more recent version of messageformat (#1345) or angular-message-format (#1227).
