### ISSUE TITLE
Is it possible to avoid displaying the Translation ID's?

### ISSUE THREAD

**Issue by nmpribeiro** [angular-translate/angular-translate#1407]
I am using ui-router, and when I switch views, I am briefly seeing the 'TRANSLATION_ID' due to async loading of both view and translation json from the server (all by parts, so we don't load too much and unecessary things). Is it possible to avoid displaying the Translation ID's altogether?

**Comment by tspaeth** [comment]
Did you read the chapter on http://angular-translate.github.io/docs/#/guide/12_asynchronous-loading ?

**Comment by nmpribeiro** [comment]
Well, I did read it some time ago for part loading... is it this? It seams I never saw this on any real case example...
loadFailureHandler: 'MyErrorHandler' ?
