### ISSUE TITLE
How to use inline html in the translations?

### ISSUE THREAD

**Issue by ludydoo** [angular-translate/angular-translate#1408]
### Subject of the issue
I am trying to use standard html tags inside a translation like such : 
```
{ 'TEST' : 'Hello <em>People!</em>' }
```
But using the sanitize or escape methods get rid of this.

### Your environment
* version of angular-translate : ^2.9.2
* version of angular : ~1.4.2
* which browser and its version : Chrome 48.0.2564.116, Safari 9.0.1 (11601.2.7.2)

https://plnkr.co/edit/n1q46Qu19bUQExBzofdj?p=preview

### Expected behaviour
I'd like to be able to use inline html tags

### Actual behaviour
It's escaped / sanitized.

**Comment by tspaeth** [comment]
If you really want to do have these values 1:1 inserted, you have to set the sanitize value accordingly (maybe to null). Sanitizing is working as specified in the docs as far as I can see in your example.

**Comment by knalli** [comment]
> But using the sanitize or escape methods get rid of this.

No, that's not true. :) You have simply ignored the error message in the console stating and complaining about the missing sanitize plugin.

In fixed manner, it is working for me:
https://plnkr.co/edit/SALPxc5Vj0qlxoYo6BmE?p=preview

Okay with that?

**Comment by ludydoo** [comment]
Hi there, it seems to be working like a charm!

I'm going to check this out later today.

Thank you both for your help

**Comment by tspaeth** [comment]
Closing. Feel free to reopen in case some bug comes up or open a new issue. thanks.
