### ISSUE TITLE
why use $rootScope.$emit to broadcast some event

### ISSUE THREAD

**Issue by why520crazy** [angular-translate/angular-translate#1409]
when i call $translate.use method to change locales, can't receive $translateChangeSuccess event in sub scope.
`$scope.$on("$translateChangeSuccess",function(){
})`

**Comment by tspaeth** [comment]
maybe for some reason (I don't know your code), your $scope is not getting the event? Tried with $rootScope?

**Comment by why520crazy** [comment]
use $rootScope should be ok，i use it in controller or directive，if use $rootScope.$on("$translateChangeSuccess",function(){ })，it must need freed when controller destroy，
You can modify to $rootScope.$broadcast ?

**Comment by tspaeth** [comment]
If it doesn't work in your case with the $scope - then you've already shown your solution. Clean it up in a destroy function. I wouldn't advise to modify such a core event now in the module as it might affect a lot of existing applications which work fine currently.

**Comment by why520crazy** [comment]
thanks very much. I think there is no problem so modified, but choice is yours.
