### ISSUE TITLE
Enhancement: Allow different host for angular-translate-loader-static-files

### ISSUE THREAD

**Issue by netzaffin** [angular-translate/angular-translate#1411]
I want to import the <lang>.json file from a different host (CDN).

angular-translate-loader-static-files only allows two options, prefix and suffix.

To add the feature, one line has to be added

```
url: [
   options.host || '', // new line
   options.prefix,
   options.key,
   options.suffix
].join(''),
```

What do you think?

**Comment by tspaeth** [comment]
from a security point of view, this could open some holes in combination with disabled sanitizing etc. - just my 2cent

**Comment by knalli** [comment]
The `url` will be build with three parts: `prefix`, `languageId` and `suffix`. There is absolutely no need for an additional `prefix`. @netzaffin If you want to prepend the host, then will include this in the `prefix`. Simple as that.

Regarding the security pov: Obviously, the browser will not allow such requests in situation of a web context (serving by http/https) enforced by the Same Origin Policy. Applying additional `$http` headers (and serving Allow-* headers on the CDN site) or switching to another protocol (i.g. JSONP) can fix this.
