### ISSUE TITLE
useSantizeValueStrategy('escapeParameter') breaks object prototypes

### ISSUE THREAD

**Issue by tonyfinn** [angular-translate/angular-translate#1412]
### Subject of the issue
When escapeParameters is turned on, translate parameters are replaced by clones without the prototypes before they are passed to any filters. This issue has specifically happened to us with moment.js dates, but can occur to any object that relies on a prototype to provide functions etc.

### Your environment
Tested in our app on ng-translate 2.7.2/ angular 1.4.8, but can reproduce on Angular 1.5.0 and Angular Translate 2.9.0

Tested in Firefox 44 but the issue is likely cross browser

### Steps to reproduce
1. Call $translateProvider.useSanitizeValueStrategy('escapeParameters')
2. Interpolate a complex object with a prototype in a string, that gets passed to a filter:
e.g. "The date is {{someMomentObject | dateFilter }}"
3. The filter gets passed a broken clone.

See this plnkr below:
https://plnkr.co/edit/ndVs09yGk19hGPbfL5Lw?p=preview

### Expected behaviour
1. The filter should be passed the original object (with prototype) that was passed as a translate parameter.

### Actual behaviour
1. The filter is passed a clone that does not have the object prototype

**Comment by knalli** [comment]
No, it works actually. ;)

Well, that does not make sense. Either we escape or sanitize the specific arguments or inputs.. well, or we don't. We cannot say strings are bad, but "objects not looking like a string" not.

I'm not sure how we can solve this without generating a security issue (beware of `toString`). Perhaps, we can introduce a whitelist, but this will be a neverending story. In your case it is not a date object, but a Moment-Wrapper.

**Comment by knalli** [comment]
@tspaeth wdyt?

**Comment by tspaeth** [comment]
I agree with you, Knalli. This is a bit of encapsulating logic inside a text content - so more of the interpolation of the interpolation or "cascading filters".
@tonyfinn Isn't it an option for you to use the directive and pass in the formatted date value? That would usually be the way to go.

**Comment by knalli** [comment]
@tonyfinn You can change the complete sanitization process adding a custom one (`$translateSanitization.addStrategy()`). Doing that you are able to change this, but you are also responsible for security on your own.
