### ISSUE TITLE
Key is used as fallback instead of original text

### ISSUE THREAD

**Issue by iamdriz** [angular-translate/angular-translate#1413]
If I have a link like so:
`<li><a ng-class="{ active : $state.includes('section1') }" ui-sref="section1" translate="SECTION1">Introduction</a></li>`

And the translate key value `SECTION1` doesn't exist in the currently selected language it will instead use the fallback language key value instead which is great! However if it doesn't find the fallback language key value either, instead of just falling back to what the original text was, it just falls back to the key itself, in this case `SECTION1`. What I want is for it to just say `Introduction` if it doesn't find the `SECTION1` key value in either the selected or fallback language.

Is this a missing feature? Or a bug?

**Comment by knalli** [comment]
Did you have already read our documentation and guide at https://angular-translate.github.io/ ?

You can either use a [custom error handler](https://angular-translate.github.io/docs/#/guide/17_custom-error-handler) or use the `default` extension of the [translate directive](https://angular-translate.github.io/docs/#/api/pascalprecht.translate.directive:translate).

I guess that is what you are looking for.

**Comment by iamdriz** [comment]
Yeah read the documentation. However I'm not seeing anything that allows the current inline content to be used as the fallback. All the examples show either using a global error fallback or specifying the default as an attribute... I want it to use the actual inline content that is already there.

**Comment by iamdriz** [comment]
@knalli Any updates on this? Thanks.

**Comment by knalli** [comment]
http://plnkr.co/edit/tHWNfwDv0nTqhVWc08nx?p=preview

Alright, no, that is not possible. If you define a translation key, this will override the element's content (which will be used as an element id unless defined).

This is not a bug, perhaps a missing feature. If you want, you can make a pull request. :)

**Comment by tspaeth** [comment]
@knalli didn't we have this request already in some other issues? I'll see what we can do ...

**Comment by iamdriz** [comment]
@knalli Cool. Why do you believe this is not a bug out of curiosity? As if the key isn't defined in any translation, **why would you want the key to show and not the original content?**

**Comment by tspaeth** [comment]
@iamdriz 
> why would you want the key to show and not the original content?

Well, at least speaking for the projects I am working on and where we use this module on, we're not putting dummy content in the node value/text, but only use Keys with either empty content/text or simply the key. 
And we want to see where texts are untranslated so we can feed in a translation at least for one language. To achieve that, we use an error handler but also we can see it on screen that it is untranslated.
I guess, the approaches are simply different we have in the wild.

**Comment by iamdriz** [comment]
@tspaeth I can appreciate it is a good quick and easy way to see where missing translations are, but I think it'd be better to have this handled by the error handler and just let it fallback to whatever original content is there. In my opinion anyway :)

**Comment by iamdriz** [comment]
In any case, it'd be great if this could be an option.

**Comment by tspaeth** [comment]
Could we combine this probably with #986 request?
