### ISSUE TITLE
Angular-Translate in cooperation with ng-models and forms

### ISSUE THREAD

**Issue by MariusHerget** [angular-translate/angular-translate#1414]
### Subject of the issue
When you want to translate the placeholder of an input field, but work with ng-models, the ng models cannot be used.

### Your environment
angular-translate: 2.9.2
angular: 1.5.0
Firefox, Chrome in different version

### Steps to reproduce
example on Plunker: https://plnkr.co/edit/4JTMjZG0OftkZsVU3gVc?p=info

### Expected behaviour
input value should be written into ng variable model

### Actual behaviour
When you fill the translated input first, it does not will work / be displayed in the model
if you fill in the non translated input first and then the translated, everything works fine

**Comment by knalli** [comment]
You have to initialize your object `forminput` at the beginning: either with `ng-init` or simply in the controller.
