### ISSUE TITLE
fallbackLanguage broken after upgrade to 2.9

### ISSUE THREAD

**Issue by sebek64** [angular-translate/angular-translate#1415]
### Subject of the issue
After upgrading from angular 1.4 to 1.5 and angular-translate from 2.8 to 2.9, language switching to "fallbackLanguage" stopped working.

### Your environment
* version of angular-translate: 2.9.2
* version of angular: 1.5.0
* which browser and its version: Firefox, Chrome

### Steps to reproduce

In our application, language switching stopped working in a strange way. Switching among all languages works, but we cannot switch to 'en'. After some investigation, we found that dropping

$translateProvider.fallbackLanguage('en');

fixes the switching problems. Here is a part of our code:

    .config(function ($translateProvider) {
      $translateProvider.useLocalStorage();
      $translateProvider.useSanitizeValueStrategy('sanitizeParameters');
      $translateProvider.useMessageFormatInterpolation();
      $translateProvider.preferredLanguage('en');
      $translateProvider.fallbackLanguage('en');
      $translateProvider.uniformLanguageTag('bcp47');
      $translateProvider.determinePreferredLanguage();
      $translateProvider.registerAvailableLanguageKeys(['en', 'cs', 'pl'], {
        // en
        'en-AU': 'en', 'en-BZ': 'en', 'en-CA': 'en', 'en-CB': 'en', 'en-GB': 'en', 'en-IE': 'en', 'en-JM': 'en',
        'en-NZ': 'en', 'en-PH': 'en', 'en-TT': 'en', 'en-US': 'en', 'en-ZA': 'en', 'en-ZW': 'en',
        // cs
        'cs-CZ': 'cs',
        //pl
        'pl-PL': 'pl'
      });

      $translateProvider.useLoader('$translatePartialLoader', {
        urlTemplate: 'modules/{part}/{lang}.json',
        loadFailureHandler: 'SITranslationErrorHandler'
      });
      $translateProvider.useLoaderCache(true);
    })

    .run(function ($rootScope, $stateParams, $translate, $translatePartialLoader){
      $rootScope.$on('$stateChangeSuccess', function () {
        if ($stateParams.lang !== undefined){
          $rootScope.activeLang = $stateParams.lang;
          $translate.use($stateParams.lang);
          $translatePartialLoader.addPart('translation');
          $translate.refresh();
        }
      });
    });

Another way how to fix switching (but without dropping fallback language) is to move fallback language to .run() block:

$translate.fallbackLanguage('en');

and change useLocalStorage to useCookieStorage. Just one of these changes was not sufficient.

### Expected behaviour
Language switching should be working - language should be switched.

### Actual behaviour
Language switching is working except that switch to "fallbackLanguage" is ignored.

**Comment by mkalafior** [comment]
I have the same issue and noticed also, that this line (angular-translate:2112) is causing the problem:
`} else if (langPromises[key]) {`
and if we change it to:
`} else if (langPromises[key] && langPromises[key].$$state.status !== 1) {`
changing languages is working again. 

It seems that when `fallbackLanguage` method is used, after file with translations is loaded, promise isn't removed from `langPromises` object.

**Comment by knalli** [comment]
Perhaps introduced in 40ad523. Is `$$state.status` an internal `$q` api for current resolution state?

**Comment by knalli** [comment]
Things so far to do: 

- [ ] Test case in browser
- [ ] check for test case coverage in the unit tests
- [ ] proper solution (if `$$state.status` is public api, it's fine. otherwise we have to look).

Any contributions are welcome ;) I'll look into it, but not before end of the week.

**Comment by tspaeth** [comment]
I'd try to have a look, but won't manage it before the weekend.

**Comment by knalli** [comment]
Note: If this is introduced by 40ad523, it would be okay in 2.9.0 still. It's a 2.9.2 fix.

**Comment by sebek64** [comment]
Yes, I can confirm that 2.9.1 does not have this problem. So we can stay with 2.9.1 until a fix is made.

**Comment by tspaeth** [comment]
On 1st thing: "Test case in browser"
Tested in browser with my long-term, own fallback-all-in-scenario on canary - branch. As soon as the if block

```
if (!$uses) {
```

is commented out -> works as expected. Otherwise not.

**Comment by tspaeth** [comment]
FYI: created a test for the issue locally

**Comment by tspaeth** [comment]
@sebek64 / @mkalafior - I've provided a small PR, can you have a try on it and patch it probably locally manually for a short test if your both scenarios will be fixed? Would be great. Or just wait if knalli has done his check and integrated it to canary.

This fallback / preferred / whatever stack is a bit grown too volatile :-)

**Comment by knalli** [comment]
Published 2.10.0 few minutes ago, including the PR by @tspaeth .

**Comment by sebek64** [comment]
Confirming that 2.10.0 fixes the bug, thanks to all who worked on the solution.
