### ISSUE TITLE
2.7.2 release is not enlisted in any package sources for NuGet 3

### ISSUE THREAD

**Issue by bahram-aliyev** [angular-translate/angular-translate#1416]
Can not install the latest 2.7.2 release of angular-translate using NuGet v3.

Visual Studio 2015 Community Edition
NuGet 3.3.0.167
Packages source: https://api.nuget.org/v3/index.json

Open NuGet package manager and try to install angular-translate 2.7.2
In case of using a package manager console, the 2.6.1 version of the library is installed.

**Solution:**
Copy package sources from Visual Studio 2013 and add as an additional package source (https://www.nuget.org/api/v2/), use this packages source for the angular-translate installation.

**Comment by knalli** [comment]
2.7.2 is not the latest release, this is 2.9.2 as of today.

We don't have added the library to NuGet which means we have neither the control to manage or upload packages nor we have the ability to do. 

At last but not least: Contributions for an mostly automatic process uploading releases to Nuget are welcome.

Also https://github.com/angular-translate/angular-translate/search?q=nuget&type=Issues

**Comment by bahram-aliyev** [comment]
Thank you for the reply.

Excuse me for disturbing you, I did not notice that the author of the package in not a member of the dev team. I will contact the author and ask him to update the package.

>>At last but not least: Contributions for an mostly automatic process uploading releases to Nuget are welcome.
Don't get me wrong, but I believe that it would be beneficial for all of us if you get in touch with the author of the package. May be he has already got the tools for uploading releases to NugeGet. The package is quite popular, 22003 download, so it would be nice to have your support as a dev team member.

>>Personally, I would manage javascript dependencies only with NPM, Bower or JSPM.
Thank you for the recommendation, I am considering to use bower in the future, but NugGet is still a very convenient tool for me.
