### ISSUE TITLE
How to properly test with Jasmine?

### ISSUE THREAD

**Issue by gruberb** [angular-translate/angular-translate#1420]
### Subject of the issue
I want to unit test a toggle function where I pre-define the language as 'en_EN', call the function where I toggle it to 'de_DE'. In the browser, it works fine. When testing with Jasmine, $translate.use() is undefined. 

```
    $scope.toggleLang = function() {
      if ($translate.use() === 'en_EN') {
        $translate.use('de_DE');
      } else {
        $translate.use('en_EN');
      }
    };
```

My test:
```
 it( 'should switch the translation from english to german', inject(function($translate) {
    httpBackend.when('GET', 'assets/locale/locale-en_EN.json').respond(200);
    spyOn($translate, 'use');

    var homeController = controller('HomeController', {});

    homeController.toggleLang();

    expect($translate.use).toHaveBeenCalledWith('de_DE');
  }));
```

### Your environment
* version of angular-translate: 2.8.1
* version of angular: 1.5.0
* which browser and its version Chrome 48, PhantomJS2 while testing

### Steps to reproduce
`git clone git@github.com:gruberb/angular-boilerplate.git`
`cd  angular-boilerplate `
`npm install`
Uncomment the test in home.spec.js 
`grunt test`

### Expected behaviour
The test should pass, because I toggled the language and want to be de_DE active

### Actual behaviour
It is still en_EN active

**Comment by tspaeth** [comment]
Did you have a look at the bunch of test suites we have for testing the functionalities?

https://github.com/angular-translate/angular-translate/tree/master/test

**Comment by gruberb** [comment]
Yes. With no results. Can you have a look is this the way to test $translate? Because I could not think of another solution and I am trying for hours now.

**Comment by knalli** [comment]
@gruberb  We do have a working scenario, i.e. https://github.com/angular-translate/angular-translate/blob/5dfa8ca49137425d0614c5693b2fe67fa72c125f/test/unit/service/loader-static-files.spec.js#L7-L63

An advice: You don't have to test with XHR files. You can mock you tests specifying a custom url loader which is much more easier, i.e. this [custom loader (in this case for delaying, but you should get it)](http://plnkr.co/edit/F9bsLhIOKCNpkPR6Xbrc?p=info).
