### ISSUE TITLE
Latest angular translate plugins aren't published to npm

### ISSUE THREAD

**Issue by mattlewis92** [angular-translate/angular-translate#1422]
### Subject of the issue
The [main repo](https://www.npmjs.com/package/angular-translate) is published as 2.10.0, but all child plugins are still on 2.9.2 e.g.
https://www.npmjs.com/package/angular-translate-handler-log
https://www.npmjs.com/package/angular-translate-loader-url

This causes angular translate to be duplicated when installed with npm like so:
```
├── angular-translate@2.10.0 
├─┬ angular-translate-handler-log@2.9.2
│ └── angular-translate@2.9.2 
├─┬ angular-translate-loader-url@2.9.2
│ └── angular-translate@2.9.2 
```

Thanks! :smile:

**Comment by knalli** [comment]
Sorry again. The steps are still not scripted enough.

Done.

**Comment by mattlewis92** [comment]
Thanks so much for the quick response! :smile:
