### ISSUE TITLE
ng-translate is awesome but it leaves no neat identifiers behind for Protractor to grab - opportunity here?

### ISSUE THREAD

**Issue by Andre-H** [angular-translate/angular-translate#1423]
### As it is now

![as it is today](https://cloud.githubusercontent.com/assets/4048967/13411924/b7d59224-dfa4-11e5-9922-d6db614d1302.png)

### As I wish it was

![as i wish it was](https://cloud.githubusercontent.com/assets/4048967/13411940/d7fc0cfe-dfa4-11e5-99bf-f37a702802e5.png)

### Steps to reproduce
Given I set ng-bind attribute (or ng-model) of an element in the format 

`.*\|translate`

When I set the ng-bind to something followed by |translate, for instance: `<span ng-bind="HEADLINE|translate"></span>`

Then the element will display the translated value of the model attribute in its inner text (in the example, HEADLINE) and the elment will have an ng-bind HTML attribute with the value "HEADLINE|translate" - see attached screenshot.

### Expected behaviour

The HTML that's exposed to the user agent will have explicit identifiers that Protractor tests can use easily and robustly.

`<span ng-bind="HEADLINE|translate">Translated content here</span>`

### Actual behaviour
`<span translate>Something translated here that has no ID, what a wasted opportunity</span>`

### Disclaimer
I know that in the form presented, it is not an enhancement to angular-translate, but to ng-bind directive itself! This is a question in the shape of a feature request: - Can't we have a tranlation that has the benefic side-effect of leaving behind unique identifiers for my end-to-end GUI test to pick up?

**Comment by knalli** [comment]
Why do not using `<span ng-bind="'HEADLINE' | translate"></span>`? If you like this, then use it.

Unfortunately, we cannot make this (without saying we should). The filter is interpreted by AngularJS itself and the filter is virtually only a function being called. The filter *does not know anything about the context*. `ng-binding` is only added by AngularJS for debugging purpose (see https://code.angularjs.org/1.5.0/docs/guide/production and search for "Disabling Debug Data").
