### ISSUE TITLE
Translate optional modules should have their own module name and depend on the main translate module to allow out of order/async loading

### ISSUE THREAD

**Issue by pdanpdan** [angular-translate/angular-translate#1425]
Translate optional modules should have their own module name and depend on the main translate module to allow out of order/async loading

**Comment by knalli** [comment]
@pdanpdan  I'm not sure what you are talking about? Which modules? What do you mean with "async loading"?

**Comment by pdanpdan** [comment]
- angular-translate-loader-partial
- angular-translate-storage-cookie
- angular-translate-storage-local
... all live in separate files, and all need "angular-translate" file to be loaded before they can execute.
"angular-translate" creates a module "pascalprecht.translate", and all the other files use the same module.
If the files are loaded out of order (using async or other method) one might end up loading "angular-translate-loader-partial" before "angular-translate".
If each file ("angular-translate-loader-partial", ...) would create a separate module depending on "pascalprecht.translate" it would work well.
Like: angular.module('pascalprecht.translate.storage.local', ['pascalprecht.translate'])

**Comment by tspaeth** [comment]
I guess, I know what you mean, but where exactly do you currently have an issue with the order of loading the scripts? (e.g. in oc.lazyLoad you can trigger dependencies and load order also)

And on the other hand, this concept is already part of discussion on 3.0 - #995

**Comment by knalli** [comment]
Allright.

Yes, this is **already addressed** in the next major release. Meanwhile, the order of the scripts is important. But honestly, that should be no big deal today. Even without a package/bundle manager in use, you still must ensure that polyfills or even `angular.js` will be loaded at first.
