### ISSUE TITLE
Documentation todo: Add doc for $translate.instant to the main docs

### ISSUE THREAD

**Issue by tspaeth** [angular-translate/angular-translate#1427]
As mentioned by the users in #473 - it is true that using the instant functionality is missing in the main docs. Even though we've always wanted to push the async approach, the sync way still is a must have for a lot of users.

Therefore, we should prepare documentation
- [ ] ~German~
- [ ] English
- [ ] ~French~
- [ ] ~Spanish~
- [ ] ~Russian~
- [ ] ~Chinese~

**Comment by knalli** [comment]
Right, it was mentioned in the migration guide for 2.0 only.
However, it is included in the API docs (that does not mean I'm against this here).

**Comment by tspaeth** [comment]
You know... no one reads it :sweat_smile:

**Comment by alpalmerxactware** [comment]
Can this method be used with only a translationId and the desired language? If so how? If not, what is the minimum needed to to use this method for translation?

**Comment by knalli** [comment]
The API is documented both at source level as well as API docs https://angular-translate.github.io/docs/#/api/pascalprecht.translate.$translate (actually based on the source code docs).

**Comment by alpalmerxactware** [comment]
@knalli Thanks for the link. I have actually looked at that and it leaves much to be desired imo. 
For example: Can the interpolateParams object be empty? or are there some minimum required values? Is there an existing example somewhere of this method being used and working?

Short story, Its not working for me, and I'm not sure why.

**Comment by knalli** [comment]
Added additional info in d2d621f
