### ISSUE TITLE
Error on app lauch : Uncaught Error: [$injector:unpr] Unknown provider: $$cookieReaderProvider <- $$cookieReader <- $cookies <- $cookieStore <- $translateCookieStorage <- $translateLocalStorage <- $translate <- $cookies

### ISSUE THREAD

**Issue by RodolpheNivelet** [angular-translate/angular-translate#1428]
Hi,

I get this error when I lauch my app with Grunt on the browser console :

Uncaught Error: [$injector:unpr] Unknown provider: $$cookieReaderProvider <- $$cookieReader <- $cookies <- $cookieStore <- $translateCookieStorage <- $translateLocalStorage <- $translate <- $cookies

My environment:

angular 1.4.6
angular-cookies 1.4.6
angular-translate: 2.8.1
angular-translate-loader-static-files 2.8.1
angular-translate-storage-local 2.8.1
angular-translate-storage-cookie 2.8.1

Thank you !

**Comment by tspaeth** [comment]
what does it mean "when I launch my app with Grunt" ?

**Comment by RodolpheNivelet** [comment]
It mean I use grunt for development. So after doing
`grunt serve`

**Comment by tspaeth** [comment]
Without knowing your exact config - I'm not sure how we could help in your app development here. But if I search quickly on the web - it leads me to SO and this particular link:

http://stackoverflow.com/questions/30885568/angularjs-unknown-provider-cookiereader

**Comment by RodolpheNivelet** [comment]
Thank you for the link but i'm perfectly sur my angular-cookies is the same version as my angular (1.4.6).

I know it because I downgraded angular-cookies for 1.5.0 to 1.4.6 after bower asked me to update it.

Every forum topic on the internet that is related to this problem is people having a diferent version of angular-cookies and angular

**Comment by knalli** [comment]
@RodolpheNivelet The error is not thrown by angular-translate. Given the trace, `$cookies` (by AJS) looks up for `$cookieReader` (also AJS) which does not exist.

I would also say you have an incompatible setup of dependencies. Said this, I will close this.

**Comment by RodolpheNivelet** [comment]
Hi,

I had a dependency problem it is resolved now thank you.
