### ISSUE TITLE
question: how to

### ISSUE THREAD

**Issue by clembou590** [angular-translate/angular-translate#1429]
suppose that we have this:
var translations = {
  HEADLINE: 'What an awesome module!',
  PARAGRAPH: 'Srsly!',
  NAMESPACE: {
    PARAGRAPH1: 'And it comes with awesome features1!',
    PARAGRAPH2: 'And it comes with awesome features2!',
    PARAGRAPH3: 'And it comes with awesome features3!',
    PARAGRAPH4: 'And it comes with awesome features4!',
    PARAGRAPH5: 'And it comes with awesome features5!',
  }
};

the doc says we can use directive like this:

app.controller('Ctrl', ['$scope', '$translate', function ($scope, $translate) {
  $translate(['NAMESPACE.PARAGRAPH1','NAMESPACE.PARAGRAPH2', 'NAMESPACE.PARAGRAPH3','NAMESPACE.PARAGRAPH4','NAMESPACE.PARAGRAPH5',]).then(function (translations) {
    $scope.namespaced_paragraph1 = translations['NAMESPACE.PARAGRAPH1'];
  $scope.namespaced_paragraph2 = translations['NAMESPACE.PARAGRAPH2'];
  $scope.namespaced_paragraph3 = translations['NAMESPACE.PARAGRAPH3'];
  $scope.namespaced_paragraph4 = translations['NAMESPACE.PARAGRAPH4'];
  $scope.namespaced_paragraph5 = translations['NAMESPACE.PARAGRAPH5'];
  });
}]);

THAT IS A LOT OF CODE TO WRITE if you have 50 values in your namespace...

is it not possible to possible to translate "the full namespace"?

like this:
app.controller('Ctrl', ['$scope', '$translate', function ($scope, $translate) {
  $translate(['NAMESPACE']).then(function (translations) {
    $scope.namespace = translations['NAMESPACE'];
  });
}]);

If it's not could you add this feature?

**Comment by knalli** [comment]
> THAT IS A LOT OF CODE TO WRITE

@clembou590 Really? Why do you are shouting?

This project's aim resolves the problem of resolving texts (translations). You give it one key, and it will return a resolved one. This includes features like asynchronous loading (load the translations only on demand) or fallback language resolving (if the actual language cannot provide a translation, but an alternate one could).

In opposite of that, you are trying to get.. well.. all resolved translation by given nothing.

So, in the end: Yes, we don't reduce your code lines. We still don't build any magic.

For the convient way, we have introduced in v2.8.0 the additional co-directive `translate-namespace` (see 45523bb).

If you really need to get and put 50 translations by the service into the scope:

1. I don't recommend this. Why you are not using the filter or the directive? The service is only useful in scenarios of custom build texts or the configuration of non-AJS components.
2. I'm still not recommend this. You will lost any reference of usage where in your app a specific key ist used.
3. However, if you still want to make it: Well, you can reduce the code slightly.

```js
app.controller('Ctrl', function ($scope, $translate) {
  var ns = 'NAMESPACE.';
  var keys = ['PARAGRAPH1', 'PARAGRAPH2', 'PARAGRAPH3', 'PARAGRAPH4', 'PARAGRAPH5'];
  $translate(keys.map(function(key) {return ns+key;})).then(function (translations) {
    keys.map(function(key) {
      $scope[ns + key] = translations[ns + key];
    });
  });
});
```

**Comment by clembou590** [comment]
Hello.
thank you very much for this answer and also for the good job that has been done in this project. sorry for the delay of my answer. 
I wrote with capital letter not to shout but just to emphasize that I was having an issue.

I am using directive and filters in almost everything, however sometimes it's not possible and I have to code using the service.

Thanks again for the function you gave me but when I have 50 'keys" in the namespace I still have to write them all  down to get the translation.... 

the directive translate-namespace is kind of what I need... but what I need is in fact the service....

**Comment by odedniv** [comment]
For anyone coming here to work around it and get objects/arrays from this library I suggest the following: use `JSON.stringify` in the translation configuration on your object/array, and `JSON.parse` when you retrieve it.

I understand that this library is not meant to be used this way, but in my case I had an object built by many attributes and nested objects. I really didn't want to translate each and every attribute's value and just wanted each language to provide the full object structure.

@knalli the original thread #352 is locked, but I suggest you add this comment there for anyone else still interested in doing this in spite of your warnings.
