### ISSUE TITLE
Need to switch to staticFilesLoader in case of any error from customLoader

### ISSUE THREAD

**Issue by gowthamanvt** [angular-translate/angular-translate#1430]
### Subject of the issue
Need to switch to staticFilesLoader in case of any error from customLoader.
 - I am using the customLoader to load the JSON files from database.
 - In case of any error or if the file doesn't exist in the database, I have to use staticFilesLoader to show the translated values.
```
app.factory('customLoader', function ($http, $q, $rootScope) {
	return function (options) {
	  var deferred = $q.defer();
	  var loggedInUserData = appUser.getJson();
	  var tenantId = loggedInUserData.tenantId;
	  
	  $http({
		method:'GET',
		url:'/api/content/locale/'+ options.key
	  }).success(function (data) {
		deferred.resolve(data);
	  }).error(function () {
		deferred.reject(options.key);
	  });
	  
	  return deferred.promise;
	};
});
```
### Your environment
* version of angular-translate - v2.7.2
* version of angular - v1.4.4

### Expected behaviour
I have use the static files from my work-space in case of any error from the customLoader

### Actual behaviour
Translate shows the keys in the UI. :(

**Comment by tspaeth** [comment]
So what is the error here? You're anyway rejecting with "options.key" - so it will return the key.
You need to cascade here nad call the staticFilesLoader I would say.

**Comment by gowthamanvt** [comment]
Thanks @tspaeth for the response. 

I am using angular translate for first time and just got confused with using multiple loader.

I have written the code part I am using, please provide a sample snippet to utilize staticFilesLoader in case any error in customLoader. It would be a great help for me.

app.config([ '$translateProvider', function ($translateProvider) {

  $translateProvider.determinePreferredLanguage();
  $translateProvider.fallbackLanguage('en_US');

  $translateProvider.useLoader('customLoader');

  $translateProvider.useSanitizeValueStrategy('escaped');
  
}]);

**Comment by tspaeth** [comment]
We're always happy to help, but for general "how to" questions, Stackoverflow is the best place to ask as there are more experts being able to help you. 

In your case, I would suggest you should refer the staticFilesLoader factory and call it from your error part of the example code with sth like (don't have example code here currently):
```
return $staticFilesLoader(options);
```

or something similar (this is just an outline, maybe the quick - shoot is just a shoot in the foot ;-) )

**Comment by gowthamanvt** [comment]
Thanks for the kindness & idea @tspaeth ..

I have got the flow and now am able to call staticFilesLoader. :)
