### ISSUE TITLE
Translate filter with deep link

### ISSUE THREAD

**Issue by robertomcampos** [angular-translate/angular-translate#1431]
Translate filter doesn't work for direct url

"angular": "1.4.8",
"angular-translate": "~2.2.0",
Chrome last version

When the application starts, and I navigate to some page, the translate filter works.
The problem occurs when I put the direct link in browser. In this case, all of places that i use "translate filter", It does not work.

Example:

it works
` <h1 translate="SOME_KEY"></h1>`

It does not work
` <h1>{{ 'SOME_KEY' | translate }}</h1>`

 
Thanks for your help,

**Comment by tspaeth** [comment]
Without your complete setup as an example case via plnkr.co - it is hard to guess what goes wrong. But please - use and try it with the latest version of angular-translate. We do not support any older releases like 2.2.0. Thanks.

**Comment by renegadeds** [comment]
Can confirm I have the same issue. When you use the $translate.use() function, the content of the app will translate just fine, but the nav title of the previous page and the back button point to it will not.

**Comment by knalli** [comment]
@robertomcampos  @renegadeds  Without a working demo showing your issue we cannot neither see/reprodue nor fix the issue.

In general the filter or the service is working, so it must be a specific (config) situation on your site. We have no look at your app (and don't want it).

> When the application starts, and I navigate to some page, the translate filter works.
The problem occurs when I put the direct link in browser. In this case, all of places that i use "translate filter", It does not work.

Sorry, but I cannot follow this. It's hard (impossible) to guess what you are meaning.

**Comment by sammiwei** [comment]
@renegadeds thanks for the insights. I had a similar issue . @robertomcampos What I have done is do a $state.reload() in the translate controller, and it worked for me. Hopefully this will help you a little.
