### ISSUE TITLE
using static loads, $translate ( 'mykey' )  returns not the data, but rather object <d>

### ISSUE THREAD

**Issue by geetee24** [angular-translate/angular-translate#1435]
any idea why in javascript, a call using your static loader  to

$translate ( 'mykey' ) 
returns
d {$$state: Object}

and not the data associated with "mykey".

note that in the html
<p translate="{{ 'mykey' }}" ></p>  WORKS correctly.

Thank you

**Comment by tspaeth** [comment]
Could you please provide a complete plnkr showing your setup? Without it, it is a bit hard to see what is wrong.

**Comment by igorng** [comment]
Hello! 
I've got a behavior similar to this one!
The service is supposed to return a promise, but it seems it doesn't.

(sorry,I'm not familiar with plnkr, so I'll just provide you with scripts' snippets here :/ )

**control.js**:
```
$scope.test = $translate('TEST');
console.log($scope.test)  // this will output a thing like: 
//Object {}
// -catch: (callback)
// -finally: (callback)
// -then: (callback, errback, progressback)
// -__proto__: Object
```
This is clearly not a promise, but rather an object with functions as members.

On the HTML side, I've got:

**test.html**:
`<div>The translated is: {{test}}</div>`

this will resolve into an empty object "{}". 

So my conclusion is, the $translate service doesn't return a promise as it should.

Note that I recently migrated from:
**"angular-translate": "1.1.1", "angular-translate-loader-static-files": "0.1.8"**, 
 to 
**"angular-translate": "2.11.0", "angular-translate-loader-static-files": "2.11.0"**.

Using **Angular 1.2.21**

Thanks :)
