### ISSUE TITLE
Tab crash when server returns HTTP 502 in combo with urlLoader

### ISSUE THREAD

**Issue by danpantry** [angular-translate/angular-translate#1436]
### Subject of the issue
When using `urlLoader`, if the server which the translations are located at returns HTTP 502, the application memory balloons in size and CPU usage until eventually crashing the tab the page is loaded in. This occurs in all browsers and can be avoided simply by removing the `$translateProvider.useUrlLoader` line.

### Your environment
* `angular-translate` version 2.9.0
* `angular` version 1.3.0
*  Chrome 48, though the issue may also occur in Firefox Dev Edition, Firefox and IE9 through 11 (a.k.a, all our test environments), so I'm going to assume the problem isn't tied to a specific browser.

### Steps to reproduce
I cannot provide a plunkr as there's no easy way to replicate a server 502. Our set up is as follows:
```
    $translateProvider.preferredLanguage('en-gb')
    $translateProvider.fallbackLanguage('en-gb')
    $translateProvider.useSanitizeValueStrategy('escape')
    $translateProvider.useUrlLoader('/api/Localisation/GetTranslationsByLanguage')
```

We have all urls that start with `/api` being proxied to a separate web server via settings specified on the IIS server that hosts the static files (though this also occurs with a local dev server using `webpack-dev-server`). When that server is unreachable and thus returns a 502 http code, the url loader causes the tab to spiral rapidly out of control in terms of memory and CPU usage, eventually leading to the crashing of the tab. 

Removing the `useUrlLoader` line prevents this issue. In both cases the server error is recorded in the Network tab of Chrome, however it is only in the second one that the app yields control back to the browser (so that other things may fail :grin:). We have no interceptors set up for HTTP 502 responses (only 401 and 403), though there is a rule with `$urlRouteProvider` that will redirect users to `/404` if the route they have found is not recognised (though the route we are visiting definitely exists).

This is a fairly large app with lots of `translate` directives, which may have something to do with it.

### Expected behaviour
I would expect `angular-translate` to fail fast and inform me that there was an error getting the translations.

### Actual behaviour
It would appear some kind of cyclic loop occurs which ends up killing the tab..

**Comment by tspaeth** [comment]
Are you really using an **Angular 1.3.0** as a baseline?

**Comment by danpantry** [comment]
@tspaeth Not a requirement we can move away from, unfortunately. It is decided by issues outside of my control. I am gradually upgrading Angular as I go along - when I joined this project a year ago, it was still on 1.2.26.

Some rather critical components rely on older versions of Angular. :(

**Comment by knalli** [comment]
Why is this an issue for angular-translate? 

We have a simple XHR setup which will either result into a success (200) or error (4xx, 5xx). So neither is an issue for 502 only (but must be also 404 for example which is presumably better for tests), nor this is a specific library.

**Comment by danpantry** [comment]
@knalli  I've raised it with angular-translate simply because by removing the url loader line, the issue goes away. It seemed rather instinctive to therefore place blame on angular-translate - especially as the rest of the app works fine without that specific line.

**Comment by tspaeth** [comment]
But, honestly, try with the latest angularjs from the 1.3 stream. If the error still stays and has some relationship to angular-translate - ok. But otherwise, it's digging in the dirt of some angular-stuff. 
And for test / issue replication, it is always a basic to use the latest version of the core framework...

**Comment by knalli** [comment]
> Are you really using an Angular 1.3.0 as a baseline?

Actually, that should/must be not relevant in case for *us*. If this really blows up, it must be something in AJS internally.

However (!), I would recommend a working demo. Until now that is guessing only.
I'm quite sure that an 502 will not be handled in other way as a 404. Or 403...

**Comment by danpantry** [comment]
I gave it a whack with Angular 1.5 and it appears that the issue is somewhere in our code, and it's just something *to do* with angular-translate that is masking that issue when we enable the url loader.

Thank you for the quick responses.

**Comment by knalli** [comment]
Okay @danpantry 

I want to add: Given the simplicity of the url loader, there is not much space for such memory consumption, i.e. we don't make any retries. Without knowing details, I personally would assume something internally in AJS (if this is the core issue after all).

**Comment by danpantry** [comment]
@knalli  I agree, I did give a look of the package before posting here and I saw nothing untoward either.
