### ISSUE TITLE
$translate function not working when being passed to to ng-repeat or as an argument to a directive

### ISSUE THREAD

**Issue by paulius005** [angular-translate/angular-translate#1438]
When passing a key and value to ng-repeat in this manner: `a: $translate('c.d.e')` and using it in `ng-repeat` as such: 
```
<option ng-repeat="(key, value) in data.points" value="{{key}}">{{value}}</option>
```
the $translate function does not seem to work and we are seeing `c.d.e` rather than what it should be translated to when running our application.

Same thing happens with directives when passing `{{'c.d.e'|translate}}` to a directive as an attribute as such 
```
<my-directive title-label="{{'c.d.e'|translate}}"></my-directive>
```

Are we using it wrong in this case, should we be using partial loader in these cases?

angular-translate: 2.10.0
angular 1.5.0
Chrome: 49.0.2623.87

**Comment by tspaeth** [comment]
Hm, the first case I don't really get on where you insert variable a as the option code doesn'T contain it. 
Second question: Do you really use angular-translate 2.1.0 or is this a typo?
Also it will be hard to guess that the issue could be without a complete example - that makes life easier. Possibly it also depends on how you process the title-label

**Comment by knalli** [comment]
@paulius005 : Please provide a simple use case / demo of this issue.

**Comment by knalli** [comment]
Closing this. I'm still not getting the issue and now demo is provided giving explainations.
