### ISSUE TITLE
ng-repeat with json array is not working in angular translate

### ISSUE THREAD

**Issue by Sharmasonu** [angular-translate/angular-translate#1439]
ng-repeat with json array is not working in angular translate

I have a View:

I have created a array using ng-repeat : city in cnames
```
   <div ng-repeat="city in cnames">
            <p>{{ city.name }}</p>
      </div>
         <button ng-click="changeLanguage('de')" translate="BUTTON_LANG_DE"></button>
          <button ng-click="changeLanguage('en')" translate="BUTTON_LANG_EN"></button>
```
In controller:
```
 var app = angular.module('myApp', ['ngCookies', 'pascalprecht.translate']);

    app.config(['$translateProvider', '$translatePartialLoaderProvider', function($translateProvider, $translatePartialLoaderProvider) {

        $translatePartialLoaderProvider.addPart('locale');
        $translateProvider.useLoader('$translatePartialLoader', {
            urlTemplate: '{part}-{lang}.json'
        });
        $translateProvider.preferredLanguage('en');
    }])
    app.controller('Ctrl', ['$translate', '$scope', function($translate, $scope) {

        $scope.changeLanguage = function(langKey) {
            $translate.use(langKey);
        }
    }]);
```
In Json file:
```
  "cnames" = [{
           "name": "sdvdsv"
         }, {
           "name": "dsvdsv"
      }, {
           "name": "Modul"
       }, {
           "name": "übergeben"
        }, {
             "name": "wurde"
        }]
```
I have not able to access the the array using ng-repeat.

**Comment by tspaeth** [comment]
But what does iterating a normal array have to do with angular-translate?
If you're iterating through "cnames", you have to put it into the scope and not fetch it as a part for angular-translate. But that's nothing that has to do with this module. The architecture is simply wrong you're using.

It's the best way to ask "How To" questions on Stackoverflow.com as we can only support fixing bugs or adding new features here.

**Comment by Sharmasonu** [comment]
yes..i am aware of that..we can use scope. But I have a Website with 15 pages....and I don't want to use controller for adding the contents...I have created JSON files for each page...actually 2 JSON files..one for english and one for spanish...

**Comment by knalli** [comment]
Please provide a proper demo. Like @tspaeth already said: Where is the actual issue? angular-translate has nothing to do with your array.. ?
