### ISSUE TITLE
$translate.use() at runtime to the setup fallbackLanguage does not change the language

### ISSUE THREAD

**Issue by adrianbader** [angular-translate/angular-translate#1440]
angular-translate version: 2.9.2
angularjs version: 1.3.7

I have the following angular-translate configuration:

    myApp.config(function ($translateProvider) {
        $translateProvider.useSanitizeValueStrategy(null);
        $translateProvider.useStaticFilesLoader({
            prefix: 'translations/lang-',
            suffix: '.json'
        });
        $translateProvider.fallbackLanguage(['en']);
    });

Then I setup (at regular runtime, not in .config) my language, e.g. `$translate.use('de')`. This works fine; all my bindings (e.g. `<span>{{'MY_TEXT' | translate}}</span>` in html are correct.

If I switch now a second time the language with `$translate.use('en')`, my html bindings are **not** changed to english, they stay at the previously set language; however, I may change the language to whathever I like and it works - except for 'en', because it is setup as fallbackLanguage. If I remove the fallbackLanguage assignement, there is no problem.

Why this behavior? For me, this looks like a bug... or what did I have understand incorrectly?

**Comment by tspaeth** [comment]
Hm. Works? What is different in your setup?

http://plnkr.co/edit/hLjZwKH8MptxkeOIsqp4?p=preview

**Comment by adrianbader** [comment]
Hm. I see. Even with 2.9.2 (the version I used) it works. I will check, what is different in my project...
Thanks for your quick response and the plunker!!

**Comment by adrianbader** [comment]
I really do not understand, what I have made... as I wanted to trace down this problem today, I can no more see a problem in my real project... I must have messed up somthing. I am really sorry for this wrong issue notification!
