### ISSUE TITLE
translate directive hides following elements

### ISSUE THREAD

**Issue by trks1970** [angular-translate/angular-translate#1442]
### Subject of the issue
I am using angular-translate (awesome!) in conjunction with font-awesome. For some reason the icon is not displayed if I am using the directive, only if the filter.

### Your environment
* angular-translate 2.10.0
* angular 1.5.1
* Chrome 49.0.2623.87 m

### Steps to reproduce
Example:
`<li class=""><a ng-href="#/" translate="HOME"><i class="fa fa-home fa-fw pull-right"></i></a></li>`
`<li class=""><a ng-href="#/" translate>HOME<i class="fa fa-home fa-fw pull-right"></i></a></li>`
`<li class=""><a ng-href="#/">{{ 'HOME' | translate }}<i class="fa fa-home fa-fw pull-right"></i></a></li>`

### Expected behaviour
I expected, that the translation of HOME is displayed followed by an icon in all three cases.

### Actual behaviour
The icon is only displayed in the last case.

**Comment by knalli** [comment]
The directive will *replace* the inner content of the specific element; therefore it is expected the icon will be replaced. Think again about this: How should the directive know where the final translation should be present? Before or after the icon?

Either you wrap the text with a inner span (`<span translate="HOME"></span>`) or with the usage of a filter (like you already have done).

**Comment by trks1970** [comment]
Thank you for the explanation. On second thought, it is quite logical. <span> is good enough for me.
