### ISSUE TITLE
Error installing angular-translate ^2.9.2 with JSPM from npm

### ISSUE THREAD

**Issue by nimedev** [angular-translate/angular-translate#1443]
### Subject of the issue
can`t install angular-translate and related plugins with versions up to 2.9.2

### Your environment
* version of angular-translate: up to 2.9.2
* version of angular: 1.5.2

### Steps to reproduce
```sh
jspm install npm:angular-translate@2.10.0
```

### Actual behaviour
```sh
     Looking up npm:angular-translate
     Updating registry cache...
     Looking up npm:angular
     Looking up github:jspm/nodelibs-process

err  Installing npm:angular-translate@2.10.0, no version match for npm:angular@~1.6.0

warn Installation changes not saved.
```

### Posible solution
Maybe modify "angular": ">=1.2.26 <=1.6" by "angular": ">=1.2.26 <1.6" from "dependencies" of package.json fix this issue.

Thanks!

**Comment by knalli** [comment]
That's a well-known issue by jspm (see here https://github.com/angular-translate/angular-translate/issues/1247#issuecomment-146341841): it simply not resolving the version correctly and does not handle non existing versions gracefully. Not our fault.

You can fix this switching the used package manager (within jspm).
