### ISSUE TITLE
partial loader with spanish as preferred language

### ISSUE THREAD

**Issue by voluntadpear** [angular-translate/angular-translate#1444]
Hi. I have the next code:
```
$translatePartialLoaderProvider.addPart('home');
  $translateProvider.useLoader('$translatePartialLoader', {
    urlTemplate: 'languages/{part}/{lang}.json'
  });

  $translateProvider.preferredLanguage("es");
```

I try to load my spanish translations but nothing happens. If I change the last line to `$translateProvider.preferredLanguage("en");` it works as expected. I'm only having this problem when trying to use Spanish as preferred language. What am I missing here?

**Comment by tspaeth** [comment]
Can you provide a complete plnkr setup with the language files? Either I'm overseeing an issue in the already-posted text part, or something is wrong :)
