### ISSUE TITLE
Loading of parts overrides previously loaded parts

### ISSUE THREAD

**Issue by wooderz** [angular-translate/angular-translate#1446]
### Subject of the issue
I have 2 translation parts. One is for dashboard page, one is for wizard page.
They both have values for the header of the page which is a common component.

dashboard.json
{
  "header": {
    "title": "Dashboard Title"
  }
}

wizard.json
{
  "header": {
    "title": "Wizard Title"
  }
}

In both controllers I run $translatePartialLoader.addPart(part) (either wizard or dashboard)

Problem is if I go from Dashboard page to Wizard page and back again, the Dashboard page now has the wizard page's translations.

It seems Angular Translate takes the last one loaded, whereas I'd like to only use the part my controller has loaded and none others. Is there a way round this?

**Comment by knalli** [comment]
You cannot reuse an unique translation id. Given the use case, I would suggest wizard.title and dashboard.title.

**Comment by wooderz** [comment]
That doesn't work for me as the header is a shared component so can only have one key in the directive. 

I'm using angular ui-router so have got it working by deleting all the parts currently loaded upon a $stateChangeSuccess event, but it would be nice to have the option within angular-translate to enforce 1 part at a time when calling addPart

**Comment by knalli** [comment]
> That doesn't work for me as the header is a shared component so can only have one key in the directive.

Well, that's an implementation detail up to you.

angular-translate is treating translation keys globally and "parts" are only sub trees of this complete one. You can hack a way resetting the already loaded translations and change the parts.. but it is still a hack an not intended by design.
