### ISSUE TITLE
need your idea about translating $scope generated value

### ISSUE THREAD

**Issue by wandiong** [angular-translate/angular-translate#1447]
hi guys
I have 2 translation variable
```
en = {"generator : "Generator"}
ID = ("generator" : "Genset"}
and I got a problem translating controller generated value such like 
 $scope.itemList= [{
                "id": "generator",
                "name": "generator"
            }]
```
I guess I can use (key,value) options on angular looping
but 
as I know **it only affects targeted variable in looping.. so it wont be working i presume**

so is there any idea to made it happens guys?

big thanks for the one who replying and correct
also much appreciated for the one who tried to help me :)

**Comment by tspaeth** [comment]
I'm sorry, I don't get it.
Even it is better to ask "how do I..." questions on Stackoverflow (http://stackoverflow.com/questions/tagged/angular-translate) , as this is the feature-/bugtracker for angular-translate. Thanks.

**Comment by wandiong** [comment]
I got the solution
- make sure your json key is same as your scope target
example 
var ID : {'generator' : 'genset'}
var EN : {'generator' : 'generator'}

$scope.items = $scope.tenantAllocated = [{ 
//same with json key 
id : 1,
code : 'generator' 
}]

then on your view
just do something like {{items.code |translate}}
hope it works :)
