### ISSUE TITLE
determinePreferredLanguage and messageformat's "Plural Function not found"

### ISSUE THREAD

**Issue by phw** [angular-translate/angular-translate#1451]
When using determinePreferredLanguage() together with angular-translate-interpolation-messageformat and the user has set an unsupported locale in the browser an "Plural Function not found" error is thrown by messageformat.

I think angular-translate-interpolation-messageformat should not just try to intitialize messageformat with any language but limit it to those languages registered with the $translateProvider. Otherwise this combination easily breaks, unless you include every possible pluralization rule for messageformat and even then there might be some users with unsupported languages.

I am not sure whether this should be fixed here or in determinePreferredLanguage (having determinePreferredLanguage not return any languages not registered with the $translateProvider) . Currently I work around it by using a custom determinePreferredLanguage which discards unsupported languages.

Copied from https://github.com/angular-translate/bower-angular-translate-interpolation-messageformat/issues/10

**Comment by knalli** [comment]
Are you sure this is still valid in 2.11? It includes a fix regarding the available languages and the invalid tries of resolving others...

**Comment by phw** [comment]
Might be resolved then, I have to validate this against the latest version. For now I just copied over the bug report.

I will report back.

**Comment by phw** [comment]
Seems to be resolved using version 2.11. Thanks

**Comment by knalli** [comment]
Thank you!
