### ISSUE TITLE
useStaticFilesLoader file locations array error

### ISSUE THREAD

**Issue by hornetnz** [angular-translate/angular-translate#1452]
### Subject of the issue
Setting up multiple file locations with useStaticFilesLoader as noted in the docs does not work.
The docs say to allow the loader to look in multiple locations via:
```
`$translateProvider.useStaticFilesLoader({
                files: [{
                    prefix: 'locale-',
                    suffix: '.json'
                }, {
                    prefix: '/absolute/path/to/locale-',
                    suffix: '.json'
                }, {
                    prefix: 'another/path/to/locales/',
                    suffix: ''
                }]
            });`
```
But IntelliJ gives the following error:
```
> Error:(56, 17) TS2345: Argument of type '{ files: { prefix: string; suffix: string; }[]; }' is not assignable to parameter of type 'IStaticFilesLoaderOptions'.
 Object literal may only specify known properties, and 'files' does not exist in type 'IStaticFilesLoaderOptions'.
```
If I remove the files array and load from one file source, it compiles and works fine.
```
`$translateProvider.useStaticFilesLoader(
                {
                    prefix: './app/translations/',
                    suffix: '.json'
                }
            );`
```
### Your environment
Using version 2.11

### Steps to reproduce
http://plnkr.co/edit/jVOQEZgzaooyVjoCazMC?p=preview

### Expected behaviour
Should load the 2 json files.

### Actual behaviour
Neither is loaded.

**Comment by tspaeth** [comment]
Without IDEA and using your plnkr - I don't see this TS2345 error. I'm just getting simple 404 errors. 
But I'm moreover wondering why the first translation file is loaded and the others get 404, BUT the translation is not displayed (as it should be in the translation array anyway). Maybe there is a promise.reject - issue ... 

But your IntelliJ-IDEA issue is to me none (whatever IStaticFilesLoaderOptions might be)

**Comment by knalli** [comment]
I would guess TypeScript when seeing `TS2345`, also afaik they use the i-prefix pattern for interfaces sometimes. Do you have TypeScript enabled in your Web module within your project in IntelliJ/WebStore/...?

As we neither provide nor support (read: do not test) TypeScript (yet), this error is more less invalid for us right now. 

So there are two options: Either you are using a TS interface of angular-translate, but this would be not by us. Or someone is interpreting the JSDoc and/or code and tries to determine the possible values -- and fails.

**Comment by hornetnz** [comment]
You can ignore for now the fact I'm using Typescript. I see now that someone installed a TS version (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/angular-translate/angular-translate.d.ts), which looks to be behind on version. 
I'm more interested in why my Plnkr doesn't work. I'm guessing it may be a simple path issue, as I dont know how pathing works for files in your plnkr code. 

Beyond that, your sample demos techincally don't work either...it has the code for multiple json locations, but is using the json thats in that same file. Therefore the example is invalid. I noticed that issue on many of the examples.

**Comment by knalli** [comment]
@hornetnz I don't get your issue: http://plnkr.co/edit/PYyTHKufDumHeTHUt4Ur?p=preview What's wrong with that?

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
