### ISSUE TITLE
need help for using translate filter on controller

### ISSUE THREAD

**Issue by wandiong** [angular-translate/angular-translate#1453]
hi guys

in usual usage, we will see <something>{{'something'|translate}} </something> right?

for this case... I want to made something like this in controller
pointFormat: '{{"store"|translate}}: {point.percentage:.1f}%',

is there any other ways to made it happens like <something>{{'something'|translate}}</something> ?
I've tried to use usual usage translate filter. also $filter('translate)(something) but still doesnt working

**Comment by knalli** [comment]
Please elaborate your issue a little bit. What do you want to know?

**Comment by wandiong** [comment]
for what I want to know is, how can I made translation filter look like in usual usage which is looks like {{'something'|translate}} in controller?

edit : I've made it by using $translate.instant(my_translate_id) , but it wont dynamically translating. is there any way to made it dynamically?

**Comment by knalli** [comment]
It would help a lot if you provide a *full* example. And I would recommend to use the formatting options of Markdown, especially for code.
