### ISSUE TITLE
Dynamic variable replacement - using translate directive and filter together

### ISSUE THREAD

**Issue by parky128** [angular-translate/angular-translate#1454]
I am making use of the variable replacement feature from angular-translate in my application as documented in the guides [here](https://angular-translate.github.io/docs/#/guide/06_variable-replacement)

Using the example in this guide, I was wondering how you could translate an interpolated value being passed in. So say I have something as follows for displaying some validation text to the user.

````html
<div ng-message="required" translate="REQUIRED_FIELD" translate-value-field="Description"></div>
````

```javascript
{
  "REQUIRED_FIELD": "{{field}} is required",
}
```

A problem I see with this is that `Description` is being used literally and therefore not translated.

Could a filter be used for the value being assigned to the `translate-value-*` directive like so:

````html
<div ng-message="required" translate="REQUIRED_FIELD" translate-value-field="{{'GENERAL_TERMS.DESCRIPTION' | translate}}"></div>
````

```javascript
{
  "REQUIRED_FIELD": "{{field}} is required",
  "GENERAL_TERMS": {
		"DESCRIPTION": "Description"
	}
}
```

This does work for me locally, but I wondered whether this approach is correct.

Can anyone offer any advice please?
Thanks

**Comment by tspaeth** [comment]
Another approach is to write a custom directive that does the trick and fetches the two translation segments separately. 
Now, you're mixing the (synchronous) filter approach with the directive (async) approach, which is from an architectural view not really good.

And one general remark: Please ask "How To" questions on StackOverflow as you'll there reach a broader audience with such questions.

**Comment by merlosy** [comment]
Hum, have you considered ES6 templates?
Maybe this link can give you a hint (quick google search): http://jaysoo.ca/2014/03/20/i18n-with-es6-template-strings/

Rgds,
