### ISSUE TITLE
Error: Couldn't refresh translation table, no loader registered!

### ISSUE THREAD

**Issue by wandiong** [angular-translate/angular-translate#1455]
hi ...

I trying to use translate.refresh() but it returns ** Error: Couldn't refresh translation table, no loader registered!**

am I miss out something?

here's my code 
config

> angular.module('books',['pascalprecht.translate','ngCookies'])
	.config(function ($translateProvider, $translatePartialLoaderProvider) {
			//$translateProvider.useSanitizeValueStrategy('escape');
			// add translation tables
			$translateProvider.translations('en', translationsEN);
			$translateProvider.translations('cn', translationsCN);
			$translateProvider.preferredLanguage('cn');
			$translateProvider.fallbackLanguage('en');
			// remember languag
			$translateProvider.useLocalStorage()})

controller

> .controller('translateController',function($scope,$translate,$translatePartialLoader){
	$scope.changeLanguage = function(langKey) {
							$translate.use(langKey);
							$translatePartialLoader.addPart('books');
							$translate.refresh(langKey);
	}
})

big appreciate for helping :) :+1:

**Comment by knalli** [comment]
It does not look like you have registered a loader.

Honestly, that is the error message! :)

**Comment by wandiong** [comment]
ok... I get it @knalli  , after I re-read the documentation, yep I missed out loader.. thanks for helping :smile:
