### ISSUE TITLE
Skipping sanitizing of specific element?

### ISSUE THREAD

**Issue by devboxr** [angular-translate/angular-translate#1456]
Hi guys,

first of all, thanks for creating this library and for keeping it updated.

I have worked with other libraries in the past, and they all had support for what I am trying to do, so I am sure this is possible from inside `angular-translate` as well. Generally I am using `ngSanitize` to filter all my translations, however, for some specific ones I would like to print them with the HTML.

Any idea on how to do that?

Further, is there a better documentation? I have found a couple of things that were not mentioned in the docs (e.g. `$translate.instant()`) which I only found while looking through the Github issues.

Thanks!

**Comment by knalli** [comment]
> Further, is there a better documentation? I have found a couple of things that were not mentioned in the docs (e.g. $translate.instant()) which I only found while looking through the Github issues.

Have a look at http://angular-translate.github.io/ containing both the guide as well as a general api doc.

> Generally I am using ngSanitize to filter all my translations, however, for some specific ones I would like to print them with the HTML.

I'm not sure what you are looking for. You can define your own sanitization strategry: http://angular-translate.github.io/docs/#/api/pascalprecht.translate.$translateSanitizationProvider

**Comment by devboxr** [comment]
Hi there,

I know about the sanitization strategies, however, this did not solve my problem. What did the trick was a `sanitize` filter + `ng-bind-html`, which does work but does not feel like it was intended to be used like that. I am relatively new to AngularJS, learning it at work (I know a decent amount of JS though), and this just doesn't feel right.

An example would be, having an element in the translations like so:
```Already a customer? <a href="{{ href }}">Log in here!</a>```
or
```I read and agree to the SamKnows Ltd <a href="{{ href }}">Terms and Conditions</a>```

How would this be done, without AngularJS escaping the elements automatically? I first thought this is a `angular-translate` issue, but then realised that AngularJS is actually escaping "unsafe" strings automatically.

Question now is, is there any better practice in using elements like the ones above, without the sanitize filter?

I understand that this may fall out of the `angular-translate` scope, but am sure that I am not the first one to encounter this problem and I am happy to hear any approach on this.

Thanks a bunch in advance!

**Comment by knalli** [comment]
> What did the trick was a sanitize filter + ng-bind-html, which does work but does not feel like it was intended to be used like that. I am relatively new to AngularJS, learning it at work (I know a decent amount of JS though), and this just doesn't feel right.

What do you mean? This one?

```js
$translateProvider.useSanitizeValueStrategy('sanitize');
```

+

```html
<span ng-bind-html="{{'XYZ' | translate}}"></span>
```
