### ISSUE TITLE
White Blank Screen in Ionic on Arabic Translation

### ISSUE THREAD

**Issue by aqarain** [angular-translate/angular-translate#1457]
### White Blank Screen in Ionic on Arabic Translation
I am developing an Ionic app in which I am also using angular-translate lib. The app works fine in all views in English but when I switch to Arabic, on some views it work fine but on some of the views show a white blank screen after a blink of the original view.

It is very strange when i click on inspect element, the view appears and there is a white flash when switching from one view to another.
Also the performance decreases when I use Arabic language. 
It only happens when I select Arabic as a language. It works fine in English lang.

What could be the possible reason and how can I overcome it?

### ionic (Android)
* version of angular-translate => v2.8.1 
* version of angular => v1.0
* chrome Version 49.0.2623.110 m

### Steps to reproduce
I have different views in my app but on some views when I switch to, it shows a blank white screen instead of showing the view. The view is there but not showing

### Expected behaviour
It should should show the view and its elements

### Actual behaviour
It is showing blank white screen

**Comment by tspaeth** [comment]
Well, without a complete code example, it is hard to see if there is a bug.

**Comment by iamrutvik** [comment]
@aqarain , Have you solved this issue? I am having the same problem.

Here is my code snippet :

I have ar.json and en.json stored in i18n folder at root of www folder.

in config : 

```
$translateProvider.useStaticFilesLoader({
        prefix: 'i18n/',
        suffix: '.json'
    })
    .preferredLanguage('en');
```

On change language function : 
```
$scope.changeLanguage = function (lang) {
        var appLang = lang;
        if (appLang == 'ar') {
            $translate.use(appLang);
        }
        else if (appLang == 'en') {
            $translate.use(appLang);
        }
    };
```

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.

@iamrutvik : Your code is the first code we have seen. No example, no solutions. If you still have an issue, feel free to open a new issue and follow the template's guide.
