### ISSUE TITLE
Strip comments from .min.js

### ISSUE THREAD

**Issue by PaulAnnekov** [angular-translate/angular-translate#1461]
### Subject of the issue
It looks like at least latest version includes all jsdoc comments in minified version https://cdn.jsdelivr.net/angular.translate/2.11.0/angular-translate.min.js.

### Expected behaviour
Doc comments must be stripped from minified version.

**Comment by knalli** [comment]
Thanks. We should revisit the uglify options. Probably introduced with 66877f0654c3959c24ebb6964dffe35510e09a36

**Comment by knalli** [comment]
I just picked a workaround by @marclr  -- Thank you. Will be released soon in 2.11.1.
