### ISSUE TITLE
Some multilingual contents are render on browser like this. kj�pe (the question mark sign)

### ISSUE THREAD

**Issue by amoldorkar-ezest** [angular-translate/angular-translate#1463]
I am using Norwegian and English language to translate using angular-translate, and I am storing translation content in json file but some of the Norwegian characters are shown as question mark sign like kj�pe this.

environment
* version of angular-translate- v2.6.1 - 2015-03-01
* version of angular- 1.5.0
* which browser and its version- Google chrome 49.0.2623.112 m

### Expected behaviour
kjøpe

### Actual behaviour
 kj�pe

**Comment by tspaeth** [comment]
Maybe you have some UTF-8 issue? Did you check on this? e.g. have a look at #1101

**Comment by amoldorkar-ezest** [comment]
yes, I have seen this but found some confusion...
Plz suggest me the excact solution

**Comment by knalli** [comment]
Given the described situation, your translation files are either generated or delivered with an invalid content character set. For example, it contains UTF-8, but is delivered an non UTF 8 one (or vice versa). Also it is possible, that there are already stored in the wrong content type.
