### ISSUE TITLE
Use of translate-namespace directive and $scope variables

### ISSUE THREAD

**Issue by Jerige** [angular-translate/angular-translate#1464]
### Subject of the issue
When using translate-namespace $scope variables are no longer updated

### Steps to reproduce
http://plnkr.co/edit/tpGLSmdDkEybqB4vSndu?p=preview

**Comment by neelvadgama-hailo** [comment]
+1

**Comment by mostafabarmshory** [comment]
+1

**Comment by knalli** [comment]
You should use expressions in AJS always with a "dot".

Simple answer: You cannot rely the current scope.

Here an improved version of you example using:

* dot syntax
* replacing `$scope` with the more elegant `this`

http://plnkr.co/edit/pVatcu8ekqrElWJ3Aa4M?p=preview
