### ISSUE TITLE
Translate code that outside angular

### ISSUE THREAD

**Issue by aaani** [angular-translate/angular-translate#1465]
Hello,  

I have some code in my project that isn't part of my angular application. This code is guised in angular templates using `<Script type="text/x-jquery-tmpl"...` and is essentially a template that is used dynamically by my angular app. 
I want to be able to translate these templates as well. Is there anyway I can call the $translate service with a html template, and some variables to translate and it can return me the translated template as a string, which I can use in my app?

Thanks!

**Comment by tspaeth** [comment]
Please ask "how do I..." questions on Stackoverflow: http://stackoverflow.com/questions/tagged/angular-translate - you'll reach a bigger audience. 

This issue tracker is mainly the feature-/bugtracker for angular-translate. But you're always free to add a feature request later on. 

Thanks.

**Comment by aaani** [comment]
Thanks. I just moved this question to stackoverflow: http://stackoverflow.com/questions/36721231/translate-code-that-is-outside-angular-with-angular-translate
