### ISSUE TITLE
Translate alert messages question?

### ISSUE THREAD

**Issue by Jarvey** [angular-translate/angular-translate#1466]
I know how to add translation like this in the html file:
`<h2 translate>SETUP.WELCOME</h2>`

But how can I add a translation to a confirm popup or alert popup in my controller.js  
```
var alertPopup = $ionicPopup.alert({
   title: "Error", // how can I translate this line
   template: "Something is going wrong, try again later" // how can I translate this line
});			
alertPopup.then(function(res) {
   console.log('ok is pressed');
});
```

Thanks!

**Comment by tspaeth** [comment]
you could use the service with $translate or the filter - see the docs here: http://angular-translate.github.io/docs/#/guide/03_using-translate-service
