### ISSUE TITLE
Forcing another language does not work anymore (breaking in 2.11)

### ISSUE THREAD

**Issue by knalli** [angular-translate/angular-translate#1471]
@almeidap reported a regression introduced in 2.11
> Forcing a language is now working in version 2.11.0 but it produces errors when trying to switch to another language afterwards:

    angular.js:13236 TypeError: Cannot read property 'key' of undefined
        at angular-translate.js:2216
        at processQueue (angular.js:15552)
        at angular.js:15568
        ...

> You should be able to reproduce the issue if you click in any language button on the updated demo Plunk (see console for stack trace):
http://plnkr.co/edit/3YVgipajDFwLuYBVVBeh?p=preview

> FYI, angular-translate determines my preferred language as French, which is correct.

____

> In fact after some more testing, it looks like forcing a translation only works properly when using the `translate` pipe. Take a look to the improved demo again:
http://plnkr.co/edit/3YVgipajDFwLuYBVVBeh?p=preview

> * When using the `translate-force` directives, it fails radomly (probably due to the promise mechanism behind the scene).
> * Note that I had to comment the `$translateProvider.determinePreferredLanguage()` call as it seems to conflict with `$translateProvider.fallbackLanguage()` (see #1075) and breaks completely `translate-force`.

> Unless there is something wrong in the demo, this issue should be reopened again.

____

@tspaeth  I would assume that we have add something which breaks it: https://github.com/angular-translate/angular-translate/compare/5dfa8ca49137425d0614c5693b2fe67fa72c125f...adeaa3e3a19f46cc4d40de8665f7e4492fce8475

The are errors in the console because [here](https://github.com/angular-translate/angular-translate/blob/adeaa3e3a19f46cc4d40de8665f7e4492fce8475/src/service/translate.js#L1876-L1879) the `translation` is actually an empty object and thefore NPEs. And that's wrong, `translation` should not be empty.

**Comment by knalli** [comment]
@almeidap Thanks for reporting. Your demo is working using 2.10 -- because it is a feature already introduced in 2.9. Nevertheless, the regression is bad :(

**Comment by almeidap** [comment]
@knalli you are welcome ;)

**Comment by tspaeth** [comment]
@knalli Question to you - is this line https://github.com/angular-translate/angular-translate/blob/master/src/service/translate.js#L1845 
working correct? (introduced by your commit in the range of 2.10 <-> 2.11) https://github.com/angular-translate/angular-translate/commit/bde935e110a470ad56d322e494fa9ae000ca610d

Shouldn't it reject if the user (in the referenced demo) tries to get de_DE, but it is not registered?
In this case
```
 if ($availableLanguageKeys.length > 0 && !aliasedKey) {
```
leads to the values $...length = 0 and aliasedKey = undefined ... as aliasedKey is undefined -> shouldn't it reject?
Or I'm getting it wrong ❓

**Comment by alaingiller** [comment]
Is there any progress on this issue? And any idea when will come next release with this fix? Thanks!

**Comment by knalli** [comment]
@tspaeth  bde935e IMHO cannot be relevant because it is only adding one conditional break which is not even triggered.

**Comment by knalli** [comment]
I've applied a fix, see this demo with patched angular-translate.js: http://plnkr.co/edit/ETMZPINBJtLhjsA6HiX9?p=preview

The actual error (`Cannot read property 'key' of undefined`) is fixed. I hope that this it is.

**Comment by tspaeth** [comment]
Yup, looks okay regarding the error. As this error is a bit flaky to find, could also be the right solution 👍 

As long as all tests still run - coverage should in the meanwhile also be good enough for fallback stacks...

**Comment by knalli** [comment]
2.11.1 released, please retest and report. Thank you.

**Comment by knalli** [comment]
Closing this. No complaints any more..
