### ISSUE TITLE
Angular translate not working with IE 10

### ISSUE THREAD

**Issue by laudess** [angular-translate/angular-translate#1473]
### Subject of the issue
Hello, 

I am using angular translate with chrome, firefox and IE Edge with no problem, but i need to run my app on IE 10 too, and when I try to do it it fails. 
There is some solution for this?

Thank you

### Your environment
* version of angular-translate :   v2.8.1 
* version of angular: v 1.5.5
* which browser and its version: internet explorer 10

**Comment by tspaeth** [comment]
It works with IE10 - I can guarantee that as I've running several setups with IE10. So without further details or an example, we're unable to help.

**Comment by laudess** [comment]
## This is my translate file, where I define the options

`angular.module('app.translate', ['pascalprecht.translate'])
  .config(['$translateProvider', function ($translateProvider) {

      

      $translateProvider.translations('es-ES', {
          TEXTO: 'fsdfdsfsd',
          INTRO_TEXT: 'And it has i18n support!'
      });

      $translateProvider.useStaticFilesLoader({
          prefix: '/Assets/strings.',
          suffix: '.json'
      });


      $translateProvider.registerAvailableLanguageKeys(['es-ES', 'en-EN', 'pt-PT'], {
          'es': 'es-ES',
          'en': 'en-EN',
          'pt': 'pt-PT'
      });

     

    

      PREFERRED_LANGUAGE = navigator.language || navigator.userLanguage || navigator.browserLanguage || navigator.systemLanguage || DEFAULT_VALUE;


      $translateProvider.useSanitizeValueStrategy('escape');
      console.log(PREFERRED_LANGUAGE);

     

      $translateProvider.preferredLanguage(navigator.language);
     



  }]);
`

## And this is how I show it on the view

` {{ 'INTRO_TEXT' | translate}}`


On the screen of my IE10 I only see : INTRO_TEXT

but on chrome I see: And it has i18n support!


Thank you

**Comment by tspaeth** [comment]
And what does the developer console on IE10 say? Any errors?

**Comment by laudess** [comment]
No erros on developer console

**Comment by laudess** [comment]
Any idea?

**Comment by laudess** [comment]
Ok I found the solution for the issue. The problem was in this line:

`$translateProvider.preferredLanguage(navigator.language);`

Internet explorer 10 is returning different value for navigator.language than the other browsers

**Comment by leonardoResendeLima** [comment]
Same problem. Apparently the Edge also gets tweaked when trying to retrieve the language from the localStorage or localSession.
