### ISSUE TITLE
"TypeError: Cannot read property 'setLocale' of undefined

### ISSUE THREAD

**Issue by rafaelcoutinho** [angular-translate/angular-translate#1476]
I'm using this plugin on an Ionic project, but even being harmless i'm getting the following error always:

 [INFO:CONSOLE(25642)] "TypeError: Cannot read property 'setLocale' of undefined
I/chromium( 7333):     at onResolve (file:///android_asset/www/lib/angular-translate/angular-translate.js:1675:25)
I/chromium( 7333):     at processQueue (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:27879:28)
I/chromium( 7333):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:27895:27
I/chromium( 7333):     at Scope.$eval (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:29158:28)
I/chromium( 7333):     at Scope.$digest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:28969:31)
I/chromium( 7333):     at Scope.$apply (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:29263:24)
I/chromium( 7333):     at HTMLBodyElement.<anonymous> (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:25398:24)
I/chromium( 7333):     at HTMLBodyElement.eventHandler (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:16583:21)
I/chromium( 7333):     at triggerMouseEvent (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:2948:7)
I/chromium( 7333):     at tapClick (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:2937:3)", source: file:///android_asset/www/lib/ionic/js/ionic.bundle.js (25642)

My translation provider configuration is as follows:
   .registerAvailableLanguageKeys(['en', 'pt'], {
                'en_*': 'en',
                'en-*': 'en',
                'pt-*': 'pt',
                'pt_*': 'pt'
            })
            .determinePreferredLanguage()
        ;
        $translateProvider.fallbackLanguage('en');
        $translateProvider
            .preferredLanguage('en');

**Comment by tspaeth** [comment]
On which version are you working and where is the angular-translate.js taken from? It sound either a bit as if you're missing somehow the standard Interpolator (https://github.com/angular-translate/angular-translate/blob/master/src/service/default-interpolation.js) - which should be in the dist file or you defined some other interpolator that is not existing?

**Comment by rafaelcoutinho** [comment]
I have not defined any interpolation. 
the version is:
    "angular-translate": "^2.11.0"

**Comment by tspaeth** [comment]
As I never used angular-translate in an ionic application and without an example it is more-or-less blind guessing... is the file being included also containing the default interpolation? like here: https://github.com/angular-translate/bower-angular-translate/blob/master/angular-translate.js#L2652 ?

**Comment by rafaelcoutinho** [comment]
it does not happen if i comment out determinePreferredLanguage. well since i don't need this method that's all fine
