### ISSUE TITLE
$translateMessageFormatInterpolation does not support MessageFormat custom formatting functions

### ISSUE THREAD

**Issue by stnor** [angular-translate/angular-translate#1479]
$translateMessageFormatInterpolation does not support MessageFormat  custom formatting functions as the constructor for MessageFormat is hard-coded without arguments.

It would be nice if $translateProvider.useMessageFormatInterpolation() could accept MessageFormat custom formatting functions as a parameter.

The workaround was to copy the factory and hard code my custom formatter.

See this plunker for an example of a custom formatter.
https://plnkr.co/edit/69F5lDzC0xEnP0LgDIdR

Thanks,
Stefan

**Comment by knalli** [comment]
@stnor yeah, this would be a nice contribution 😉

**Comment by akempes** [comment]
You could try:

```js
angular.module('app')

.config(function( $translateMessageFormatInterpolationProvider ){
    'use strict';

	$translateMessageFormatInterpolationProvider
	    .messageFormatConfigurer(function ($mf) {

	        var $filter = angular.injector(['ng']).get('$filter');
	        
	        $mf.addFormatters({
	            currency: function(v) { return $filter('currency')(v) }
	        });

	    });

});
```

It worked for me...

**Comment by knalli** [comment]
Why angular-flashmessage? :)

And yes, messageFormatConfigurer has been added, meanwhile. We can close this as fixed. #1619

**Comment by akempes** [comment]
Sorry, the dependency was typo. It should be "messageformat": "^1.0.2" due
to the addFormatters function.

Met vriendelijke groet, Arjan Kempes

*CREATIVE SKILLS*
ARJAN KEMPES WEB DEVELOPER
CREATIVE SKILLS, VEERDIJK 42R, 1531 MS, WORMER
T: 075 647 69 40 F: 075 647 69 41

2016-12-08 9:54 GMT+01:00 Jan Philipp <notifications@github.com>:

**Comment by knalli** [comment]
Ah, okay. Well, note please #1661
