### ISSUE TITLE
translate-cloak has problems with ng-if / modals / dropdowns

### ISSUE THREAD

**Issue by dryanmas** [angular-translate/angular-translate#1480]
### Subject of the issue

When translate-cloak is used within an ng-if statement, a modal, a dropdown, or any element that is not rendered on the dom initially at page load, the element will be permanently cloaked. I realize that modals/dropdowns don't need cloaking, but I would rather not have to worry about accidentally adding a cloak statement within one of these elements and having it permanently disappear. 
### Your environment
- latest angular translate (2.11)
- latest angular (1.5.1)
- latest chrome 
### Steps to reproduce

Put a translate-cloak statement in an element within an ng-if, modal, or dropdown. Demonstrated below with ng-if: 
https://plnkr.co/edit/I5GgMmSdux5dVD7SMZWe?p=preview
### Expected behaviour

The cloak class should be removed as expected. 
### Actual behaviour

The cloak is added as expected but the 'translate-cloak' class is never properly removed.

**Comment by knalli** [comment]
Your demo is using *2.10*, but with *2.11* it is working?

**Comment by dryanmas** [comment]
The app I was working on when I initially discovered the bug was using 2.11, so no it does not work with 2.11.

**Comment by knalli** [comment]
The bug exists at least in 2.11, 2.10 and 2.9.

So far, I can see both apply and remove calls are being performend correctly: https://github.com/angular-translate/angular-translate/blob/c76fee36ac6abe672f09b7fa95856a9e40f63d17/src/directive/translate-cloak.js#L31-L36

However, it looks like `ngIf` is replacing the actual dom element somehow. `ngIf` is sometimes tricky, so it will be perhaps better to wrap it.  But what is about the modal/dropdown use case?
