### ISSUE TITLE
variable substitution in translated strings

### ISSUE THREAD

**Issue by sandeep-instinct** [angular-translate/angular-translate#1482]
I am not sure if it's a bug or a feature request from me (funny part is i'm not sure if I can make a feature request or not). Still I'll try to explain my problem.

Can I use variable substitution along with translation?
Strings for say, are:

English:
`"my.key.to.string" : "foo bar {0} and {1}";`

German:
`"my.key.to.string" : "Deutsche foo bar {0} and {1}";`

Now i call in $translate.
`var translatedString = $translate("my.key.to.string");`

I obviously want to replace {0} and {1} with values i already have.
I can manually do a [replace](http://www.w3schools.com/jsref/jsref_replace.asp), but how helpful it would be if am able to do
`var translatedString = $translate("my.key.to.string","baz","poo");` which will give me the output as 
"foo bar baz and poo" or "Deutsche foo bar baz and poo".

Thanks and cheers for such a beautiful work btw :+1:

**Comment by knalli** [comment]
@sandeep-instinct Well, please read your post again. It looks like you have mixed up something with title and the actual text.

So, I have a little problem identifying our actual problem. Yes, you can [use translations with placeholders](https://angular-translate.github.io/docs/#/guide/06_variable-replacement).

**Comment by sandeep-instinct** [comment]
@knalli Wonderful. I found what I wanted and I think this issue can be closed. [This](https://angular-translate.github.io/docs/#/guide/06_variable-replacement) was what I was looking for.
cheers!
