### ISSUE TITLE
Angular 2.0 version ?

### ISSUE THREAD

**Issue by Delagen** [angular-translate/angular-translate#1483]
Any plans ?

**Comment by knalli** [comment]
At the moment, there is no final plan. This also depends on required time/effort for this.

Speaking of new releases, we had already plans for the next major version "angular-translate 3". See #995 

The API of Angular2 was not stable enough (even in beta). Now being in RC state, the API is hopefully more stable. 

Personally, I would like to support both AngularJS 1.x (i.e. >=1.5) and Angular 2.
