### ISSUE TITLE
determinePreferredLanguage & using "fi_FI" naming convention with asset files instead of "fi_fi"

### ISSUE THREAD

**Issue by envision** [angular-translate/angular-translate#1484]
### Subject of the issue
We have our translation files named with convention like "fi_FI" but when using determinePreferredLanguage Safari tries to load file "fi_fi.json" instead of "fi_FI.json".

Using registerAvailableLanguageKeys fallback format doesn't help this issue.

### Your environment
* angular-translate 2.11 with static files loader 2.11
* angular 1.4.7
* happens on Safari 9.1 browser while not on Firefox 46.0

### Steps to reproduce

	$translateProvider
	.useStaticFilesLoader({ prefix: '/lang/', suffix: '.json' })
	.registerAvailableLanguageKeys([ 'en_US', 'fi_FI', 'ko_KR', 'zh_CN' ], {
		'en-*': 'en_US', 'en_*': 'en_US',
		'fi-fi': 'fi_FI', 'fi_fi': 'fi_FI',
		'fi-*': 'fi_FI', 'fi_*': 'fi_FI',
		'zh-*': 'zh_CN', 'zh_*': 'zh_CN',
		'ko-*': 'ko_KR', 'ko_*': 'ko_KR'
	})
	.fallbackLanguage('en_US')
	.determinePreferredLanguage();

**Comment by knalli** [comment]
Did you have tried [`uniformLanguageTag()`](https://github.com/angular-translate/angular-translate/blob/adeaa3e3a19f46cc4d40de8665f7e4492fce8475/src/service/translate.js#L783-L837) already?

**Comment by envision** [comment]
@knalli thanks, I had not seen that yet. So what I'm looking is with setting 'java' as [documented here](http://angular-translate.github.io/docs-canary/#/api/pascalprecht.translate.$translateProvider#methods_uniformlanguagetag). Seems to be working!
