### ISSUE TITLE
How to run code after useStaticFilesLoader has loaded language files?

### ISSUE THREAD

**Issue by envision** [angular-translate/angular-translate#1486]
I would need to refresh Highcharts global config's lang values after useStaticFilesLoader has loaded language files. Is there a way to hook into event or other way to run code after the files have been loaded?

**Comment by knalli** [comment]
Sure: Have a look at our guide: https://angular-translate.github.io/docs/#/guide/18_events

**Comment by envision** [comment]
Great, thanks @knalli – it would be nice to have an example there also, but found this from SO:

    .controller('foo', function ($rootScope, $scope, $translate) {
        $rootScope.$on('$translateChangeSuccess', function () {
            $scope.pageTitle = $translate.instant('PAGE.TITLE');
        });
    })'
