### ISSUE TITLE
Apply post filter when using the "translate" directive

### ISSUE THREAD

**Issue by amcpanaligan** [angular-translate/angular-translate#1487]
Hi I have the code <span translate="MyKey"></span> which works perfectly fine (translates to expected value). But sometimes I want the translated output to be post processed by filter say uppercase or lowercase, titlecase and more.

<span translate="MyKey | uppercase"></span> does not work.

I don't like to use the postProcess of the $translateProvider since the filter is conditional by need and need not to be configured globally.

Any idea?

using the translate filter {{ 'MyKey' | translate | uppercase }} does not work neither.

PS: I load my translations using .net resources (web api call) using $translateProvider.useUrlLoader

**Comment by knalli** [comment]
If you want to intercept the directive, you will have two options:

* implement your own directive
* decorate the existing directive with your logic

> using the translate filter {{ 'MyKey' | translate | uppercase }} does not work neither.

Well, sure, this is working. Please prepare and show a demo why and when this should not work as expected.
