### ISSUE TITLE
Translate attribute affecting multiple binding when blankspace.

### ISSUE THREAD

**Issue by JordanAlimi** [angular-translate/angular-translate#1489]
### Subject of the issue
When using the translate attribute with a value of blank space with a multiple binding, Angular only parses the last binding.

### Your environment
* Angular Translate: 2.10.0
* Angular: 1.4.8
* Browser: Google Chrome 50.0.2661.86 

### Steps to reproduce
[JS Bin](http://jsbin.com/xoseto/2/edit?html,js,output)

### Expected behaviour
The expected behaviour is for the translate attribute to be ignored and parse all values.

### Actual behaviour
The actual behaviour is Angular parsing only the last binding.

Code:
```html
<div ng-controller="DemoCtrl as demo">
    <span translate="">
      Hello {{demo.name}} of {{demo.planet}}, my name is {{demo.author}}. Is your name {{demo.author}}?
    </span>
</div>
```
```javascript
app.controller('DemoCtrl', function() {
  this.name = 'world';
  this.planet = 'earth';
  this.author = "Jordan";
});
```

Output:

Hello {{demo.name}} of {{demo.planet}}, my name is {{demo.author}}. Is your name Jordan?

### Note
A question that will come up is the reasoning for having the translate attribute when you aren't translating. I've read examples and personally use it myself for keeping track of elements that will be or are currently being translated.

**Comment by knalli** [comment]
_You are holding it the wrong way._ :)

Seriously, this is the correct way of using both filters and directives. I suggest visiting our guide at https://angular-translate.github.io/docs/#/guide/05_using-translate-directive.

In short: Either use the directive or the filter.. but not mixing it. Speaking of your case (with variables), the section about params is also interesting: https://angular-translate.github.io/docs/#/guide/06_variable-replacement

**Comment by JordanAlimi** [comment]
@knalli Thanks for the response and information. I agree my usage isn't in line with the documentation but I do feel that the translate attribute shouldn't be affecting Angular's parsing if nothing is being translated.

The translate attribute should act the same way as other HTML attributes and not cause issue if nothing is set. This can be seen with the style attribute not affecting the style of a DOM element if set to blank space [here](http://jsbin.com/tanuve/edit?html,css,js,output).

**Comment by knalli** [comment]
Nope. You are using the directive not as is should be used. If the attribute translate is empty, the innerHTML will be used.
