### ISSUE TITLE
angular-translate has some problems with ui-grid

### ISSUE THREAD

**Issue by qichangjun** [angular-translate/angular-translate#1490]
this is my code
 `angular.module "myApp" .factory 'hsTranslateService', 
['$translate', ($translate) ->
      translate:(key) -> 
          if key 
            console.log 'trannn',$translate.instant(key) 
            return $translate.instant(key) else return key ]`

` name: 'object_name' displayName: hsTranslateService.translate 'OPS_PURCHASE_UIGRID_TITLE_OBJECT_NAME' minWidth:300 cellTemplate:'webComponents/common/hsTemplates/doc/list-docContent.html' editableCellTemplate:hsTpl.hsEditableCellTemplate`

somtimes after I refresh my web it doesn't translate the header like this,but other models working well

![image](https://cloud.githubusercontent.com/assets/15797310/15208016/19bef9c2-185c-11e6-9517-bd3099fc6577.png)
anyway to avoid this problem?

**Comment by tspaeth** [comment]
I don't understand really your issue with this explanation as the example code is incomplete somehow.
In general think of not using the instant calls here. 

And: Please ask "how do I..." questions on Stackoverflow: http://stackoverflow.com/questions/tagged/angular-translate - you'll reach a bigger audience. 

This issue tracker is mainly the feature-/bugtracker for angular-translate. But you're always free to add a feature request later on. 

Thanks.

**Comment by qichangjun** [comment]
anyway,thanks for help
