### ISSUE TITLE
I want to load language before any UI is displayed with ui-router resolve

### ISSUE THREAD

**Issue by essivision** [angular-translate/angular-translate#1492]
I want to load language before any UI is displayed. I created a RequireTranslations factory like this:
```
'use strict';

app.factory("RequireTranslations", function($q,$translatePartialLoader, $translate) {
    return function() {
        var promises = [];
        angular.forEach(arguments, function(translationKey) {
            promises.push($translatePartialLoader.addPart(translationKey));
        });
        return $q.all(promises).then(function() {
            $translate.refresh();
        });
    }
});
```
and use it in `ui-router` config:
```
$stateProvider
    .state('admin', {
        url: '/admin',
        templateUrl: 'views/admin.html',  
        data:{
            authenticated:true
        },
        controller:'AdminCtrl',
        resolve: {
            dep: ['translations','$ocLazyLoad',
                function(translations, $ocLazyLoad ){
                    return $ocLazyLoad.load(['directive/somePlugin.js']).then(
                        function(){
                            return $ocLazyLoad.load(['controllers/AdminCtrl.js']);
                        }
                    );
                }],
            translations: ['RequireTranslations',
                function(RequireTranslations) {
                    return RequireTranslations('shared');
            }]
        }
    })
```
and config `angular-translate` like this:
```
$translateProvider       
    .fallbackLanguage('en-us')
    .registerAvailableLanguageKeys(['en-us', 'ar-ae','pt-br'], {
        'en_*': 'en-us',
        'pt_*': 'pt-br'
    })
    .useLoader('$translatePartialLoader', {
        urlTemplate: '{part}/locale_{lang}.json'
    })       
    .preferredLanguage('en-us');
```
but on page load error me:

> http://errors.angularjs.org/1.4.8/ng/areqp0=AdminCtrl&p1=not%20aNaNunction%2C%20got%20undefined

##### My environment
* angular-translate v2.11.0
* angularjs v1.4.8

**Comment by tspaeth** [comment]
Out of this snippet it's hard to guess any error. Please either provide a complete example as something around AdminCtrl seems wrong in first sight.

And in general: 
Please ask "how do I..." questions on Stackoverflow: http://stackoverflow.com/questions/tagged/angular-translate - you'll reach a bigger audience. 

This issue tracker is mainly the feature-/bugtracker for angular-translate. But you're always free to add a feature request later on. 

Thanks.

**Comment by tspaeth** [comment]
I just saw, that you already crossposted? http://stackoverflow.com/questions/37182597/angular-translate-resolve-in-ui-router

**Comment by essivision** [comment]
Hi

I added [https://plnkr.co/edit/YnQBUQfgQBoR39Q35p0d?p=preview](https://plnkr.co/edit/YnQBUQfgQBoR39Q35p0d?p=preview)

**Comment by knalli** [comment]
Well, the latest demo has some issues:

* you should correct and full working imports of the scripts (there are blocked?)
* you should use minified resources -- there are only for production systems
* I'm seeing at least one `Module 'ngCookies' is not available!` -- which means a required module is missing

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
