### ISSUE TITLE
How to load Angular-translate with ui-router resolve

### ISSUE THREAD

**Issue by essivision** [angular-translate/angular-translate#1493]
Hi

I raised this question in [http://stackoverflow.com/questions/37247083/how-to-load-angular-translate-before-any-ui-is-displayed-with-ui-router-resolve](http://stackoverflow.com/questions/37247083/how-to-load-angular-translate-before-any-ui-is-displayed-with-ui-router-resolve). 

I'm grateful you help me solve this problem. I need this feature very high.

Thanks

**Comment by knalli** [comment]
Solution in in SOF.

**Comment by sarazhang123** [comment]
@knalli Can you tell me the meaning of SOF? I also need to resolve this issue. Thx

**Comment by knalli** [comment]
The solution is in the linked StackOverflow posting.
