### ISSUE TITLE
Error in angular-translate/src/directive/translate-language.js

### ISSUE THREAD

**Issue by sussh** [angular-translate/angular-translate#1494]
### Subject of the issue
Error in generatet docummentation
file angular-translate/src/directive/translate-language.js:
line 39:
          .translations(.preferredLanguage('en');
need replace
          .translations().preferredLanguage('en');

**Comment by knalli** [comment]
@sussh thank you for reporting. Already fixed (0e7c808 ) and will be in the next released.
