### ISSUE TITLE
Category support

### ISSUE THREAD

**Issue by peeter-tomberg** [angular-translate/angular-translate#1496]
Hello!

I've been reading through the documentation and can't find anything about categories. How do you manage big applications that may have the same translation string in different places? E.g. home screen has the key "HELLO" and any other view might have the same key "HELLO" but it should be translated differently based on the view.

**Comment by knalli** [comment]
We have no answer for this -- technically.

However, you are able to make you own structure of (JSON) file and build a small loader on top of this. 
Then you have everything under you own control.
