### ISSUE TITLE
How to translate controller function objects

### ISSUE THREAD

**Issue by danielbair** [angular-translate/angular-translate#1497]
en.json
```
{
  "CHOOSE_IMAGE": "Choose image source",
  "CAMERA": "Camera",
  "LIBRARY": "Library",
  "CANCEL": "Cancel"
}

```
th.json
```
{
  "CHOOSE_IMAGE": "เลือกที่มาของภาพ",
  "CAMERA": "กล้อง",
  "LIBRARY": "แกลอรี่",
  "CANCEL": "ยกเลิก"
}

```
feedback.controller.js
```
...
			function getImageSource() {
				var deferred = $q.defer();

				$ionicActionSheet.show({
					buttons: [
						{ text: 'CAMERA' },
						{ text: 'LIBRARY' }
					],
					titleText: 'CHOOSE_IMAGE',
					cancelText: 'CANCEL',
					cancel: function () {
						deferred.reject();
					},
					buttonClicked: function (index) {
						if (index === 0) {
							deferred.resolve(Camera.PictureSourceType.CAMERA);
						} else {
							deferred.resolve(Camera.PictureSourceType.PHOTOLIBRARY);
						}
						return true;
					}
				});

				return deferred.promise;
			}
...
```

**Comment by knalli** [comment]
Hi @danielbair, please elaborate your question a little bit more.

**Comment by danielbair** [comment]
Inside the function are system button labels that need to be translated. I provided the actual en.json and th.json files to show what needs to be translated. I can find no examples for angular-translate that translate non-html objects like in this function. I have managed to get translation working on all other areas of my application, but not this function. I don't know where to begin or how to make it happen for this one.

**Comment by Delagen** [comment]
$filter("translate")(translaterId, params)

**Comment by danielbair** [comment]
I tried that. It does nothing but break the application. There is seriously lacking good examples on how to translate content that doesn't touch the html dom (ie. stuff that gets passed to the system). There are tons of examples for how to translate html elements, but no real world examples for translation inside of the controller functions, and nothing that exists that fits the code in my question. If there was an example that paralleled the code I gave, I would be able to proceed.

**Comment by danielbair** [comment]
I have now posted this question here... http://stackoverflow.com/questions/37336133/how-to-angular-translate-controller-function-objects

**Comment by Delagen** [comment]
```
.controller(["$filter",....],function($filter,....){
var translateFilter=$filter("translate");
...
buttons: [
                        { text: translateFilter('CAMERA') },
                        { text: translateFilter('LIBRARY') }
                    ]
...

})
```

**Comment by knalli** [comment]
You will have to use the [`$translate` service](https://angular-translate.github.io/docs/#/guide/03_using-translate-service). Additionally, there will be found [`$translate.instant`](https://angular-translate.github.io/docs/#/api/pascalprecht.translate.$translate#methods_instant).

If something "breaks", you will have to show us the break. We cannot guess what you are doing at your place.
