### ISSUE TITLE
Use translation depending on url query param

### ISSUE THREAD

**Issue by nschurmann** [angular-translate/angular-translate#1498]
I have an already big application built, and i need to implement translation to all of it, the idea is to not touch any controller at all, but to add a query param (lang or locale) that will persist along all the application. 

So all the routes should have a param ?locale or ?lang that should persist, if the user comes into the application from anywhere it should add a default value to this query param (IE: 'en') so i should come to the app in any route (/some/route/of/the/app) and if there is no query param, then set it to 'en'. 

I was thinking on doing this on the app.run and add a listener to $stateChangeSuccess but don't know exactly how to handle this. Any pointers with it?

**Comment by knalli** [comment]
I'm not sure.. if you are using ui-router, you should have a look at the `resolve()` function. It is able to return a promise avoiding un-/invalid- translated content.
