### ISSUE TITLE
browser language detection causes app to error when user is not using a supported language

### ISSUE THREAD

**Issue by joshvito** [angular-translate/angular-translate#1501]
### Subject of the issue
When using 
`$translateProvider.useLoader('$translatePartialLoader' ...`
with 
```
$translateProvider.registerAvailableLanguageKeys(['en', 'ja'], {
    'en*': 'en',
    'ja*': 'ja'
  }).determinePreferredLanguage();
```
and
`$translateProvider.fallbackLanguage('en');`

Angular-translate still looks for language files that are not registered. 
Is this the expected result/behavior?

### Your environment
* version of angular-translate - 2.11.0
* version of angular 1.5.5
* which browser and its version - IE11, Chrome Version 49.0.2623.87 m

### Steps to reproduce
Set your preferred browser language to one other than 'en' or 'ja' (these two are available in the application, I used 'es')
Run this plnkr [(https://plnkr.co/edit/VeeJSTK1xKUNSkv7CzVz?p=preview)]

### Expected behaviour
The app should load the fallback language when the user's preferred language is not registered

### Actual behaviour
The application errors because it is looking for a <lang>.json that doesn't exist. It doesn't even load the fallback language.

**Comment by tspaeth** [comment]
Register a complete wildcard element at the end of the registerAvailableLanguageKeys 
```
...,
'*', 'de'
})
```

- did you try this already?

**Comment by joshvito** [comment]
@tspaeth Adding a wildcard to the end of registerAvailabelLanguageKeys does indeed fix the issue of the loader looking for non-existent .json file.

If this is the intended use, it should be added to the documentation.

**Comment by chrisbygrave** [comment]
Doesn't the suggested workaround have unintended consequences?

Let's say I use:
```
$translateProvider.registerAvailableLanguageKeys(['en', 'ja'], {
    'en*': 'en',
    'ja*': 'ja',
    '*': 'en'
  }).determinePreferredLanguage();
```
And a user comes with a browser configured with ['de', 'ja']... we _should_ pick up 'ja' as a second preference, but with the '*' entry, the user would get 'en'.

**Comment by knalli** [comment]
The fix for the docs has been added (canary branch, unreleased).

> Doesn't the suggested workaround have unintended consequences?

No. The resolver is working in the intended way. 

But I know what you are meaning: Well, we can try to add an alternative way of finding the language -- PR welcome ;) But this is slightly more complex than the existing way.

**Comment by knalli** [comment]
Corresponding pr is closed, docs are fixed.
