### ISSUE TITLE
Not working in firefox

### ISSUE THREAD

**Issue by dawoodahmad** [angular-translate/angular-translate#1503]
angular-translate not working on Firefox
angular-translate not working on Firefox. I am unable to find the error message. 

this is the directive 

```
function agTranslate() {
    var directive = {
      restrict: 'E',
      templateUrl: 'app/components/translate/translate.html',
      controller: TranslateController,
      controllerAs: 'trans',
      bindToController: true
    };

    return directive;
  }
```

and this is how i am using it in jade
`
.title.text-center {{ 'TOTAL_MEMBERS_TOTAL_COUNT' | translate }}`

**Comment by tspaeth** [comment]
Please provide a complete Plnkr as an example, otherwise it is a try&error guessing without the controller etc. and your dependency injection in general.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
