### ISSUE TITLE
How to translate the dynamic parameter passed using translate-values?

### ISSUE THREAD

**Issue by neelspoc32** [angular-translate/angular-translate#1505]
I am providing validations in my application using ng-messages.The application requires internationalization.So for that purpose validations are also translated.
But there is one specific requirement where i will give validation below the input field,providing in formation about that particular field.So i tried to used translate-values to have dynamic validations. 
For e,g. 
https://embed.plnkr.co/2JIXby6qFXXNSfjLHXza/

Now the problem is {name : "Sorting"} is hard-coded . So the ,word "Sorting" won't be translated when the language is switched.

What i would rather prefer to do is : 
```
<div class="form-group">
      <label name="Sorting" translate>sorting_name</label>
      <input type="text" name="sortingInput" ng-model="sorting"/>
      <div ng-messages="myForm.sortingInput.$error" ng-if="myForm.sortingInput.$dirty">
        <div ng-message="required" ><span  translate-values="{name:'sorting_name'}" translate>required_validation</span></div>
      </div>
    </div>

```
Here , i am trying to provide label name as a dynamic parameter value,so that it can be automatically translated .But i am not sure if any functionality like that is available.
Can you please Help on this?

Environment
angular-translate 2.7.0
angular v 1.3.15
Google Chrome : v 50.0

**Comment by knalli** [comment]
If the built-in directive or filter do not match your need (and this could be a special case), you will have to to at least one level of service usage on your own.

So either you use something like this here

1. watch for changing of `sorting`
2. use `$translate()` (promise, async) or `$translate.instant()` (direct value, sync)
3. store the result into another scope var, i.e. `sortingDisplay`
4. use this as a value

Or you build the complete string on your own.

**Comment by cmorgant** [comment]
You should be able to do this using directives!

> Since version 2.0, translate directive comes with another neat feature to pass values into your translations. We just learned how to use the translate-values attribute, which is nice, but what if we could in some cases be a bit more declarative in our code. What if we only want to pass in one or two values but declare these explicitly in our HTML?
> 
> Well, in angular-translate >=2.0 you can do exactly that. You are able to define your own translate-value-* attributes.

Source: [Guide](https://angular-translate.github.io/docs/#/guide/06_variable-replacement)


```
<div class="form-group">
    <label name="Sorting" translate>sorting_name</label>
    <input type="text" name="sortingInput" ng-model="sorting"/>
    <div ng-messages="myForm.sortingInput.$error" ng-if="myForm.sortingInput.$dirty">
        <div ng-message="required">
            <span translate-value-name="{{'sorting_name' | translate}}">required_validation</span>
        </div>
    </div>
</div>
```

And like Pascal said:
> If that isn't a cool feature, I'm sold.

Thanks for that awesome module that surprises me everyday!
