### ISSUE TITLE
How to translate and use values in array order?

### ISSUE THREAD

**Issue by kaynz** [angular-translate/angular-translate#1506]
Hey,

I have a string "Hello, my name is {0}. I'm from {1}" and a sorted array ["Michael", "Berlin"].

I want to put the first array element in {0}, the second in {1}, and so on. How can I achieve this with angular-translate?

**Comment by tspaeth** [comment]
Please ask "how do I..." questions on Stackoverflow: http://stackoverflow.com/questions/tagged/angular-translate - you'll reach a bigger audience. 

This issue tracker is mainly the feature-/bugtracker for angular-translate. But you're always free to add a feature request later on. 

Thanks.

Besides that - have you read https://angular-translate.github.io/docs/#/guide/06_variable-replacement
