### ISSUE TITLE
"Arrays of translations"

### ISSUE THREAD

**Issue by rodrigograca31** [angular-translate/angular-translate#1508]
### Subject of the issue
As far as I can seed there's no way to use "arrays of translations" right?

### Your environment
"angular-translate": "^2.11.0"
"angular-translate-loader-static-files": "^2.11.0"
"angular": "1.5.3"

```javascript
$translateProvider.preferredLanguage("pt");
$translateProvider.fallbackLanguage("pt");
$translateProvider.useStaticFilesLoader({
	prefix: 'js/locale/',
	suffix: '.json'
});
$translateProvider.useSanitizeValueStrategy('sanitize');
```

### Steps to reproduce
I have the following `pt.json` files
```javascript
{
	"beacons": [
		{
			"id": 1,
			"title": "Title 1",
			"img": "",
			"text": "Something"
		},
		{
			"id": 2,
			"title": "Title 2",
			"img": "",
			"text": "Something"
		},
		{
			"id": 3,
			"title": "Title 3",
			"img": "",
			"text": "Something"
		}
	],
	"aaaa": "value"
}
```

### Expected behaviour
I expected that this code would return and array and then the string "value"
```javascript
console.log($translate.instant('beacons'));
console.log($translate.instant('aaaa'));
```

### Actual behaviour
It's not returning the array.... It outputs the key name "beacons" IMHO it should return the content of the "variable" `beacons` (an array)....

**Comment by knalli** [comment]
All apis are used for a given string (key) to return a string (value). There are additional features like variable replacement, fallback and alternative strings or even global defined fallback strings. That all is not easy (I would say: not without additional hassle) to make consistent with such a feature.

We have discussed this feature already some times..  https://github.com/angular-translate/angular-translate/search?q=array&state=closed&type=Issues&utf8=%E2%9C%93

**Comment by rodrigograca31** [comment]
Ok. I've searched around and had only found one issue talking about this problem and was not exactly this, but I can see now that you guys have discussed this many times....

IMHO this should "simply work ", If I say to the plugin that my "translated data" is in X file, it should get it and return it not carrying if it's string, array, number, etc....

Thanks for the help.

P.S.: For future reference: I've solved it by including a file with all translations in this format:


```javascript
var beacons = [
	{
		"id": 1,
		"title": {
			"pt": "Title 1",
			"es": "",
			"en": "",
			"fr": ""
		},
		"img": "",
		"text": {
			"pt": "Text 1",
			"es": "",
			"en": "",
			"fr": ""
		}
	},
	{
		"id": 2,
		"title": {
			"pt": "Title 2",
			"es": "",
			"en": "",
			"fr": ""
		},
		"img": "",
		"text": {
			"pt": "Text 2",
			"es": "",
			"en": "",
			"fr": ""
		}
	}
];
```
The controller:
```javascript
$scope.beacons = beacons;
$scope.language = $translate.use();
```
The view:
```html
<ion-list>
	<ion-item ng-repeat="beacon in beacons" href="#/app/beacon/{{beacon.id}}">
		{{beacon.title[language]}}
	</ion-item>
</ion-list>
```
