### ISSUE TITLE
Help: Forcing another language in controller not working

### ISSUE THREAD

**Issue by SandeepThomas** [angular-translate/angular-translate#1509]
* version of angular-translate - 2.11.0
* version of angular - 1.5.5

Trying to get text translated in specific language irrespective of the current one. But always getting text in the current language only.

This is the code I'm using 
$translate('hello', null, null, 'de').then(function (translation) {
  _this.forcedtext = translation;
});

Please see this plunker: https://plnkr.co/edit/M48AZbQgonPctpO3r8nt?p=preview

Can someone please point out to me what I'm doing wrong? 

Thanks

**Comment by tspaeth** [comment]
use 'de' as the 5th parameter, not the 4th.

**Comment by SandeepThomas** [comment]
oh.. thank you..

i should use it like this right?

$translate('hello', null, null, null,'de').then(function (translation) {
	_this.forcedtext = translation;
});

**Comment by tspaeth** [comment]
API-Documentation needs update here as far as I can see. :-)

**Comment by knalli** [comment]
Corresponding pr closed already.
