### ISSUE TITLE
Error when trying too translate a falsy value with translate filter

### ISSUE THREAD

**Issue by 4kochi** [angular-translate/angular-translate#1511]
### Subject of the issue
When using a falsy JavaScript value the translation filter does not work and raises an exception. It works with the translate directive.

Our use case are validation messages with ng-message

```
<div ng-message="server">
    <span 
        translate="{{form.age.$error.serverMsg}}" 
        translate-value-expected="{{form.age.$error.expected | translate}}">
    </span>
</div>
```

The corresponding translation key looks like this:

`"SERVER_VALIDATION_MINIMUM": "Wert muß größer/gleich {{expected}} sein"`

### Your environment
* `2.11.0`
* `1.5.5`
* Safari Technology Preview 9.1.1

### Steps to reproduce
Does not work: `<p>{{ 0 | translate }}</p>`
Works: `<p translate>{{ 0 }}</p>`

### Expected behavior
The value should be translated. Or at least returned as is if there is no translation key.

### Actual behavior
Exception in the console:

`Error: text.replace is not a function. (In 'text.replace(escapedStartRegexp, startSymbol)', 'text.replace' is undefined)`

<img width="1274" alt="bildschirmfoto 2016-06-06 um 14 37 14" src="https://cloud.githubusercontent.com/assets/1742426/15822217/b0d7f9d4-2bf4-11e6-942f-c4aff2ef9ef1.png">

**Comment by knalli** [comment]
It looks like the filter is missing a "is string" condition.

**Comment by knalli** [comment]
@4kochi  I have add some tests.. but they are not failing. What I'm missing here?

**Comment by 4kochi** [comment]
Ok. Thanks. I will have a look.

**Comment by 4kochi** [comment]
Seems to be a problem with angular 1.5.x. The command `TEST_SCOPE=angular_1.5.x grunt test` fails. The other angular versions are fine.

**Comment by knalli** [comment]
https://travis-ci.org/angular-translate/angular-translate/builds/140397869

Yeah, yesterday I have thought it was only temporarily. Looks like there has been changed something.

**Comment by knalli** [comment]
Got it.
