### ISSUE TITLE
Request: Global One time binding configuration

### ISSUE THREAD

**Issue by 1nfinite** [angular-translate/angular-translate#1512]
I am using this translation plugin for my angular app development. It is undoubtedly a great translation plugin. However, i feel that something important is missing. Since Angular 1.3+ introduce one-time binding, one-time binding has become one of the important utility in maximizing the performance of the app. Whats more than most of the time one-time binding is sufficient for translation.

So, I would like to know is there any ways to enable one-time binding globally as the latest version, as I could not find any on the documentation. It seems DRY to me to repeat `::` in each and every translation i made.

If there is no existing solution, hopefully that there is some solution to it in the upcoming release. Cheers.

Something that I expect:
`$translateProvider.enableOneTimeBinding(true);`

**Comment by tspaeth** [comment]
As this is not the first time having "one time bindings" here - have a look at the issues #1450 and #1062 for some more ideas.
