### ISSUE TITLE
There is a way to translate date object ( 'EEEE' )

### ISSUE THREAD

**Issue by FrancescoMussi** [angular-translate/angular-translate#1513]
### Translate Date object
How can i translate the days of the angular date object, specifically in the format 'EEEE' ?
There is a way to do it with angular-translate?

### Your environment
* angular v1.3.13
* angular-translate - v2.11.0 
* chrome

Thanks!

**Comment by knalli** [comment]
You are requesting a feature which is not translating, but localizing. Said this, you should have a look at the AngularJS documentation.

i.e. https://docs.angularjs.org/api/ng/filter/date

**Comment by FrancescoMussi** [comment]
Thanks for replying.
I know that documentation, is about date formats.
I am looking for possible solutions for two days but didn't find yet...

**Comment by FrancescoMussi** [comment]
Ok i needed to move on so for now i have made a directive to translate the date object.
It is cumbersome but is working:
http://stackoverflow.com/questions/37744029/angularjs-how-to-translate-a-date-object/37785397#37785397
Looking forward for better solution.
Thanks anyway.

**Comment by knalli** [comment]
Well, as I already said: This is the job for localization. Even the names are localized: https://github.com/angular/bower-angular-i18n/blob/c0a4902ba9f3d783a8f0f5ad9d2209f9a315cc74/angular-locale_de-de.js#L28-L36
