### ISSUE TITLE
translate filter does not work with ASCII translation values

### ISSUE THREAD

**Issue by satyavanu** [angular-translate/angular-translate#1518]
### Subject of the issue

my json key value contains "&Auml;"  and expecting the text to be displayed  as Ä when using translate filter , but in reality it just outputs ascii value.
The same issue is being resolved by using filter as directive.Is this know issue or  there is fix ?
### Your environment
- 2.7.2
- 1.2
- chrome
### Steps to reproduce

http://plnkr.co/edit/qicVqPXn3qo6hMNa1fY2
### Expected behaviour

must  render as UTF-8 text
### Actual behaviour

display ascii value

**Comment by knalli** [comment]
Apart of the demo is not showing the issue (I can see `Überschrift` correctly), your issue could be a general issue with utf8+sanitize. See #1101 for more details.

**Comment by satyavanu** [comment]
sorry please check this link  :+1: 
http://output.jsbin.com/nitagojeqo#

**Comment by satyavanu** [comment]
when you switch to russian, The ascii values gets displayed : &Ouml;

**Comment by knalli** [comment]
I still not get it. What's wrong? Can you please make a demo with the required lines only?

**Comment by satyavanu** [comment]
in the last comment I posted link, here is my question,

let's say I am translation json as  {"tittle" : "test&Uuml;"}.If i use translation filter  {{"tittle"  | translate}}   I expect the text should be displayed as testÜ but it displays as  test&Uuml;

**Comment by knalli** [comment]
Sorry for the delay, but you have not still make your point.

Please use [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).

**Comment by tspaeth** [comment]
@satyavanu what part of your strings is shown as "ASCII"? If you could provide a screenshot and mark the error and expectation it might also help us. I don't get it either :)

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
