### ISSUE TITLE
JSDoc comments show all params as required

### ISSUE THREAD

**Issue by cudasteve** [angular-translate/angular-translate#1519]
### Subject of the issue

My IDE (WebStorm) is throwing warnings when using this library when I don't include all the params in my function call.  Looking at the source code, it appears that the `@param` statements in most of the JSDoc comments are specified as required.  I'd recommend changing optional params from this format:

```
@param {object} interpolateParams Params
```

to this format:

```
@param {object} [interpolateParams={}] Params
```

so that IDEs can understand which params need to be specified.

I'm happy to make a PR for this, but just wanted to run it by everyone to see if this is ok since I just started using this library.  Thanks!
### Your environment
- version of angular-translate: 2.11.0
- version of angular: 1.5.6
- which browser and its version: N/A

**Comment by knalli** [comment]
Hi @cudasteve 

Thank you for sharing your idea. I like it, this sounds being a good addition. 

Please have a look at our contribution guide for FAQ. 

Thank you, awaiting your PR.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
