### ISSUE TITLE
Question: Global variable replacement possible?

### ISSUE THREAD

**Issue by leschirmeur** [angular-translate/angular-translate#1521]
### Subject of the issue
Is it possible to use "global variables" in the translate directive without passing it into the directive via translate-values?

We are using variable replacement with the translate directive using the translate-values attribute. By doing so, we pass a scope value into the directive which gets replaced.

What we are trying to do now, however, is to replace "global variables" which are static across our app so that we don't need to pass in the same variable to the translate directive in a multitude of places. We couldn't find anything like this in the docs and therefore would like to ask if there is anything available to accomplish this? If not, maybe you guys have thought about something like this before already and can share your thoughts?

Example:
```
"userprofile.popup.title.email_to_admin": "Send an email to {{ adminemail }}"
```

where {{ adminemail }} is globally defined across the app. You you might wonder why we don't just hard-code the email. The reason is that the value is different depending on the logged in user and the app area the user is authorized to use.

### Your environment
* angular-translate version 2.11.0
* angular version 1.4.9
* Ionic version 1.3.1

**Comment by knalli** [comment]
You should be able to use any scope value as a translate value. However, this will not work if any scope is isolated of course.

Said this, this will not work in filters as filters are not having access to scope by default since some AJS  versions (I think it was 1.3).

**Comment by leschirmeur** [comment]
@knalli Thanks for your really fast reply! Let's say we'd call the above translation id 20 times from different places in the code like this:

```
<span translate translate-values="{ adminemail: vm.adminEmail }">userprofile.popup.title.email_to_admin</span>
```

What we'd like to achieve is that we do not have to pass in the variable into the directive 20 times so that we could use it just like this:
```
<span translate>userprofile.popup.title.email_to_admin</span>
```

However, the key-value pair in our translation json file would still look like this:
```
"userprofile.popup.title.email_to_admin": "Send an email to {{ adminemail }}"
```

and {{ adminemail }} would be replaced by a global variable somewhere. In other words, we would like to get rid of padding in the same scope variable into the directive again and again.

**Comment by knalli** [comment]
My personal advice is not doing such "optimizations". It will help you some seconds of writing, but will require more time in the future for you and others to understand what is happening.

As I said already: You can use a reference to the scope, but this is still an explicit way.

I don't think anything more "global" (as you preferred) will come, because there another limitation: 

If any global key has changed (and how should that be triggered?), *every* translation has to be refreshed. There is no information which translation uses which (global) variables or expressions with (global) variables.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
