### ISSUE TITLE
Unable to load translation json file of a module when it is used in another module 

### ISSUE THREAD

**Issue by tkthuc** [angular-translate/angular-translate#1524]
Hi, I have a module named "preview" which includes a directive and a template. I want to apply angular-translate for that module so that the translation file locale-en_US.json and the preview.js are in the same folder. The problem is when I use this module in another module the translation doesn't work. I think it is because the prefix path is wrong.

I am using angular translate 2.9 and angular 1.5

Here is an example of my code
https://plnkr.co/edit/4Ye8Pm?p=preview

Do you know how to solve this problem? Thank you. 

Sorry for the reopening, I make a mistake in plunkr.

**Comment by knalli** [comment]
Please elaborate your problem with more details: The attached demo is running two AJS apps side by side, is this really intended?

> The problem is when I use this module in another module the

What does this mean?

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
