### ISSUE TITLE
Custom translate value attribute for camel case key

### ISSUE THREAD

**Issue by oleksii-nimbus** [angular-translate/angular-translate#1525]
If we have next translation id:
{
  "GREETING": "Hi, my name is {{firstName}}"
}

Then
```
<p translate="GREETING" translate-value-firstName="Pascal"></p>
```
will not work. To make it function, we should do it like this:
```
<p translate="GREETING" translate-value-first-name="Pascal"></p>
```

Will be good if this fact is reflected in documentation https://angular-translate.github.io/docs/#/guide/06_variable-replacement

**Comment by knalli** [comment]
See also #1467 (dup).

CamelCase is not possible at attribute level. This is a feature/limitation how AngularJS handles these data.

We are always open for additions in the documentation. Suggest a PR :)
