### ISSUE TITLE
Load all translations by factory in one time

### ISSUE THREAD

**Issue by sergeykolesnikov** [angular-translate/angular-translate#1527]
Hello! I have a problem with loading translations using a factory, I made all like in docs, with custom loader, all working good but... I don't like delay between translations. I'm making an app with ionic, it have language switcher in menu (danish/english), when this app is loaded it loads current language translation (I use local storage), and if I change language, then it starts loading another translation, it takes maybe 4 seconds, after it, language changing proceed immediately. So, I want to load both translations in one time from API using this factory, I don't want to load them only when language changed. Can you tell me, is this possible and if 'yes', then how? Thanks!

**Comment by delorge** [comment]
you can pass your translations into application constants and start using them immediately. hence, no need to download them separately
```javascript
.module('myApp', [])
    .constant('en_US', {
      'HELLO_WORLD': 'Hello world!'
    })
```

**Comment by tspaeth** [comment]
Why should you put them into constants? In case you want to have them available immediately, why not putting them in the configuration section as documented in https://angular-translate.github.io/docs/#/guide/02_getting-started.

But anyway, maybe also having a look at the other sub-/sisterprojects helps a bit here to do some precompiling instead of async loading if you don't like it. E.g. https://github.com/angular-translate/translate-compile

**Comment by delorge** [comment]
well I find it unmaintainable when I have 200 lines of each language in one file, so i split them into different files. Of course, you don't have to put them into constants; you can import them if you use es6/requireJS, but if you don't, constants look reasonable beacause they are available immediately and may be declared in separate file.
I don't say that my approach is best, but in my experience it worked out quite well.

**Comment by sergeykolesnikov** [comment]
Thanks for your answers! Yesterday I found out a solution. I just pass all translations from API to $rootScope variable when app starts, after this I take translation from there, so now I don't have a problem with time after first language change.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
