### ISSUE TITLE
Cookie storage prohibits setting the 'lang' attribute correctly

### ISSUE THREAD

**Issue by timkraut** [angular-translate/angular-translate#1528]
### Subject of the issue
Hi,
I've got an issue with setting the `lang` attribute of the `<html>` tag correctly. I use the following event listener to update the attribute:
```javascript
$rootScope.$on('$translateChangeStart', function (event, data) {
   document.documentElement.setAttribute('lang', data.language);
   ...
});
```
This works fine if I click on the buttons which change the language. The cookie which stores the language selection is updated, too. Sadly, when I store a language such as German (DE) in the cookie and reload the page, the default selection (English (EN)) is active (by default, the `lang` attribute is set to `"en"`). The issue here is that my event listener doesn't fire and therefore, the `lang` isn't set correctly. Do you have any ideas how I might solve this issue? Thanks in advance!

### Your environment
* version of angular-translate: 2.11.0
* version of angular: 1.5.7
* which browser and its version: Firefox Beta 48.0

**Comment by knalli** [comment]
I think you should use another event; `$translateChangeStart` is marking the *start* of the translation change.

translateChangeSuccess or End should be work.

https://angular-translate.github.io/docs/#/guide/18_events

**Comment by timkraut** [comment]
@knalli Indeed, this works! Thanks a lot!
