### ISSUE TITLE
The link to Angular filters is wrong

### ISSUE THREAD

**Issue by ougwen1235** [angular-translate/angular-translate#1534]
>When I clicked the link to Angular filters in [Using translate filter](https://angular-translate.github.io/docs/#/guide/04_using-translate-filter), something wrong happened.
>The right link to Angular filters is [here](https://docs.angularjs.org/api/ng/filter)

**Comment by tspaeth** [comment]
Yeah, you're right. Thanks for the report. We'll fix it.

**Comment by tspaeth** [comment]
It's not fixed, so please don't close.

**Comment by knalli** [comment]
Will be resolved in next 2.11.1
