### ISSUE TITLE
HTML with angular in JSON being sanitised

### ISSUE THREAD

**Issue by shaun-ba** [angular-translate/angular-translate#1535]
### Subject of the issue

Using HTML in JSON with variables/bindings
### Your environment
- 2.11.0
- 1.5.7
- firefox 47
### Expected behaviour

HTML from translate JSON should render correctly with links
### Actual behaviour

Doesn't load links

I have JSON files with translations, one key include html, such as:

{"content": "<a ui-sref=\"app.register\">Click here to register now</a>"}

I cannot get this to load using <span data-ng-bind-html="'content' | translate "></span>.

I have tried using all different useSanitizeValueStrategy's including "null", yet the link refuses to load!

**Comment by tspaeth** [comment]
Hi! 

Thanks for the report. To help out - can you setup a short Plunker (plnkr.co) so we have a running example to take a look on?

**Comment by knalli** [comment]
Hello,

this is a general reminder: We are still waiting for your reply with additional details. If you cannot help us, we cannot help you.

Looking forward to hear from you.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
