### ISSUE TITLE
Why is there no dist folder is release packages?

### ISSUE THREAD

**Issue by courchef** [angular-translate/angular-translate#1540]
I am running VS Studio 2015 & Windows 7 and I have no intentions to install nor use node.js, npm, bower, grunt, etc.

Is it possible to add a `/dist` folder in each release so end users can use your library without having to build it?

Thank you

**Comment by tspaeth** [comment]
Hi!

Have a look at the bower - dist mirrors we currently provide - e.g. for the main module: https://github.com/angular-translate/bower-angular-translate

**Comment by courchef** [comment]
Perfect! Thank you very much.
May I suggest to add this link on the home page of the project, in the Installation section?
