### ISSUE TITLE
Not able to get values using angular translate

### ISSUE THREAD

**Issue by mohanmanis** [angular-translate/angular-translate#1543]
Hi!

I am trying angular-translate in my project and I successfully set up translations in HTML files using your library. Now I would like to translate messages used in my JavaScript scripts, but the browser reports error message "ReferenceError: $translate is not defined". How translation service should be accessed from JavaScript?

My function defined in controller.js:
```
`$scope.sendCartByEmail = function() {
alert($translate('CART_SEND_EMAIL_SUCCESS'));
}
```
translate-angular imported in app.js as decribed in tutorial:
```
var app= angular.module('dutyfree', [
'pascalprecht.translate',
'ui.bootstrap',
'ngRoute',
'dutyfreeControllers'
]);

app.config(['$translateProvider', function($translateProvider) {
$translateProvider.useStaticFilesLoader({
prefix: 'js/languages/',
suffix: '.json'
});
$translateProvider.preferredLanguage('en');
}]);

app.controller('TranslateCtrl', ['$translate', '$scope', function ($translate, $scope) {
$scope.changeLanguage = function (langKey) {
$app.uses(langKey);
};
}]);`
```

**Comment by mohanmanis** [comment]
am also facing the same issue and when i am trying to execute this $scope.sendCartByEmail = function() {
alert($translate('CART_SEND_EMAIL_SUCCESS'));
}

I am getting alert as [object object].

@PascalPrecht  can you throw light on this if i am doing anything wrong?

**Comment by knalli** [comment]
@mohanmanis  Please do not spam other issues with your problem. If you do not find help in existing topics, you should consider opening an own issue.

In your case: Please provide more information, including a demo.

**Comment by knalli** [comment]
@mohanmanis  Sorry. my fault. :(

**Comment by tspaeth** [comment]
One thing I'm already seeing (even though I'm not Pascal...):
$translate is returning a promise, so that is why you see "object Object" as the return value. Please see the documentation https://angular-translate.github.io/docs/#/guide/03_using-translate-service

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
