### ISSUE TITLE
translation doesn't happen on a translate = array element

### ISSUE THREAD

**Issue by louisdoe** [angular-translate/angular-translate#1547]
### Subject of the issue

Hi,

the translation doesn't work if I use this line : 

```
<h1 ng-if="!data.firstNavParam" class="title" ng-show="( (data.slideIndex + 1) > 1 ) && ( (data.slideIndex + 1) < data.slideTitle.length )" translate="{{data.slideTitleTranslationIDs[data.slideIndex-1]}}">{{data.slideTitle[data.slideIndex-1]}}</h1>
```
### Your environment
- version of angular-translate  : 2.8.1
- version of angular : 1.5
- which browser and its version : ionic app (ionic 1.3.1)
### Steps to reproduce

The translation doesn't happen with

```
 <h1 ng-if="!data.firstNavParam" class="title" ng-show="( (data.slideIndex + 1) > 1 ) && ( (data.slideIndex + 1) < data.slideTitle.length )" translate="{{data.slideTitleTranslationIDs[data.slideIndex-1]}}">{{data.slideTitle[data.slideIndex-1]}}</h1>
```
### Expected behaviour

Whereas when I inspect via Chrome, I see `translate="general.height"`

```
<h1 ng-if="!data.firstNavParam" class="title ng-binding" ng-show="( (data.slideIndex + 1) > 1 ) &amp;&amp; ( (data.slideIndex + 1) < data.slideTitle.length )" translate="general.height" style="">Height</h1>
```

which should work fine

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
