### ISSUE TITLE
$translateChangeSuccess fires in tests

### ISSUE THREAD

**Issue by AlexKhymenko** [angular-translate/angular-translate#1548]
### Subject of the issue
I'm writing tests and have $rootScope.on('$translateChangeSuccess') but it always fires even i dont change the language so test always misleading. Started with version 2.9.2
### Your environment
* version of angular-translate 11.1.1
* version of angular 1.5
* which browser and its version chrome

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://plnkr.co/edit/XorWgI?p=preview) as a base.

### Expected behaviour
Should not fire $translateChangeSuccess in tests
### Actual behaviour
always fires $translateChangeSuccess

**Comment by tspaeth** [comment]
As written in the template for the issue: Please provide a working code example. Otherwise it is hard to guess the issue. Thanks.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
