### ISSUE TITLE
placeholder translation into Korean is showing some codes

### ISSUE THREAD

**Issue by Mudin** [angular-translate/angular-translate#1551]
Hello,

I have an issue on translating all placeholders into Korean as described in the following screenshot image.

![screen shot 2016-08-04 at 4 18 00 pm](https://cloud.githubusercontent.com/assets/15241252/17393613/c3115d36-5a5f-11e6-92ba-e7cd11b48649.png)

I am not sure if it is font issue or translate issue.
It is fine in English, not Korean
It would be really great If you help me to figure it out.
Thank you,

Mudin

**Comment by tspaeth** [comment]
Please have a look at #1101 - it might be something on sanitation and UTF8.

**Comment by Mudin** [comment]
@tspaeth  There are many issues related to this.
I didn't see them before.

`$translateProvider.useSanitizeValueStrategy();`
works for me!

Thank you

Mudin

**Comment by knalli** [comment]
You should be aware that `null` is not secure: https://angular-translate.github.io/docs/#/guide/19_security

**Comment by Mudin** [comment]
@knalli  Yeah you are right. Is there any other way to solve my issue instead of setting `useSanitizeValueStrategy(null)`?

**Comment by knalli** [comment]
@Mudin See already mentioned 1101. This is an open issue. Feedback is welcome.

**Comment by knalli** [comment]
See #1101 Close.

**Comment by Mudin** [comment]
Hello @knalli,

Thank you for a great work!
I just updated to 2.12.1 and it is working with
`$translateProvider.useSanitizeValueStrategy('sanitize');`
