### ISSUE TITLE
Why not sessionStorage?

### ISSUE THREAD

**Issue by pjotrsavitski** [angular-translate/angular-translate#1553]
Why not implement sessionStorage as one of the possible Storages.

The implementation details would be almost identical to localStorage one.

One of the possible issues would be that it would need to use cookieStorage as fallback, although this would mean that expected behaviour would be broken in that case: value would not be stored for the duration of a session but until the cookie lasts.

**Comment by knalli** [comment]
A storage plugin must provide `get` and `put` only. Therefor it is full compliant with any Angular Cache compatible instance.

Said this: You can add all possible storage implementations on your own, you don't need our support.

You can develop a dedicated plugin (inspired by localStorage), but it can be a local solution also.
