### ISSUE TITLE
Current Stable Chrome (52) sees changes to fallback behaviour

### ISSUE THREAD

**Issue by JamesHenry** [angular-translate/angular-translate#1554]
### Subject of the issue
Chrome 52 is now stable and when moving between 51 and 52, my production app has now changed in its handling of Missing Translation errors when fallbacks are available.

To confirm: No code changes were made, the behaviour changes purely by changing browsers.

### Your environment
* version of angular-translate `2.10.0`
* version of angular `1.5.6`
* which browser and its version `Chrome 52`

### Steps to reproduce
https://plnkr.co/edit/1q4logYLNvKB0Rf7JG1q?p=preview

### Expected behaviour
It used to silently fallback to the configured fallbackLanguage's translation for the given token

### Actual behaviour
Now throws a `Missing Translation` error in every case

**Comment by JamesHenry** [comment]
Updated description with plunkr https://plnkr.co/edit/1q4logYLNvKB0Rf7JG1q?p=preview

**Comment by JamesHenry** [comment]
Now I feel like I am going mad as the behaviour seems consistent across Chrome 52, FF and Safari... :smile:

**Comment by JamesHenry** [comment]
I apologise if this has always been the behaviour and I have just somehow not observed it. It is possible that there was a caching (of selected language) issue to blame for me seeing one behaviour pre-update and another post.

If you can confirm that is what is supposed to happen, feel free to close the issue and I will work out a better way to handle it in my app!

**Comment by tspaeth** [comment]
Yes, that is the default behavior. The error handler is IMHO called per language - so that's why you see it double on your second key and only once in case of german for the other key.
The "tested" language is also handed in as a parameter, so the error handler can log or react.

**Comment by JamesHenry** [comment]
Thanks @tspaeth, sorry for the false alarm
