### ISSUE TITLE
Translate service: forced language returns wrong promise

### ISSUE THREAD

**Issue by jzahka** [angular-translate/angular-translate#1555]
### Subject of the issue
When using the translate service with forced language, the function returns the wrong promise. This causes timing issues in the application. This is only an issue when preferred language is set.

### Your environment
* angular-translate 2.11.0
* angular 1.4.9

### Steps to reproduce
As you can see in this line, if preferred language is set, a promise for the preferred language is always waited on. However, in the case of forced language, you would want `langPromises[uses]` where `uses` is the forced language, as set above.

https://github.com/angular-translate/angular-translate/blob/master/src/service/translate.js#L1115

### Expected behaviour
Forced language promise is waited on.

### Actual behaviour
Preferred language promise is waited on

**Comment by Psysoul** [comment]
+1 Issue exists and can be reproduced ie:

1. Use 'en' as preferredLanguage
2. Try to use $translate with forcedLanguage set to 'de'

Result:
$translate fails even tho the translation files are being loaded from the network.

As Jzahka wrote it could be fixed at L1115, similar to this:
`
 var promiseToWaitFor = (function () {
          var promise;

if (forcedLanguage) {
promise = langPromises[uses];
} else {
promise = $preferredLanguage ?
            langPromises[$preferredLanguage] :
            langPromises[uses];
}
`

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
# Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
# Fork it (at the top left).
# Ensure the version of AngularJS and angular-translate is correct.
# Ensure all angular-translate plugins are available; reduce and remove anything you can.
# Write a minimal as possible demo for your specific issue.
# Save and freeze. Provide us the final link to your demo.

We had an related issue (#1459), but that is fixed or not reproducible any more.

**Comment by jzahka** [comment]
https://github.com/angular-translate/angular-translate/pull/1459 implements the same fix that I suggested, fine by me if this is closed. Thanks!
