### ISSUE TITLE
script like value is removed by angular-translate

### ISSUE THREAD

**Issue by nosus** [angular-translate/angular-translate#1559]
### Subject of the issue
I find that augular-translate will strip some value from the translation string if it's a tag or script like format, for example, 

When I have a translation value like 
{
      key: "<something"
}

If I call $translate.instant("key"), I will get an empty value ""

### Your environment
* angular-translate 2.11
* angular 1.5

### Steps to reproduce
the demo, I basically just add the "<" to the default demo

https://plnkr.co/edit/rGyGHk9TljEiMKXrZkyU?p=preview

### Expected behaviour
should return the original value, because in the translation they could be valid value.

### Actual behaviour
only return empty string

**Comment by knalli** [comment]
Did you have taken a look into our guide, especially the chapter about security? https://angular-translate.github.io/docs/#/guide/19_security
