### ISSUE TITLE
angular-translate issue when interpolating parameters with escapeParameters sanitization

### ISSUE THREAD

**Issue by Luxor001** [angular-translate/angular-translate#1560]
### Subject of the issue
I'm encountering a weird issue (no translation displayed) when using angular-translate, with parameters interpolation as date objects.

Using a sanitization strategy 'escapeParameters' in the translate provider,

why with a json formatted like this:
`$scope.title = { day: 'tomorrow', today: new Date() };`

the results of my translations are always {}, using the contracted forms
```
{{'VARIABLE_REPLACEMENT' | translate : title}}
<translate="VARIABLE_REPLACEMENT" translate-values="{ day: 'tomorrow', today: title.today }">

```
I am doing something wrong?

### Your environment
angular-translate v.2.10.0 
angular v.1.5.5
Chrome 52.0.2743

### Steps to reproduce
You can find a live example in this [plunker](http://plnkr.co/edit/8NevDFkRuPsu8ZlTLO6l?p=preview).

### Expected behaviour
All the 4 translations in the plunker should be diplayed correctly.

### Actual behaviour
Only 2 translations are displayed correctly, the others displays {} brackets

**Comment by knalli** [comment]
I've updated the example here: http://plnkr.co/edit/UBD0vpwWpV7Pafb8pG0z?p=preview

The different result have the case in `$translateProvider.useSanitizeValueStrategy('escapeParameters');` which escapes the parameters. And a date is treated as an object.

This is a bug! Fixed in ab1ecce
