### ISSUE TITLE
How to translate the language's name itself?

### ISSUE THREAD

**Issue by envision** [angular-translate/angular-translate#1562]
I would need to populate select list for the settings language option. I would need fetch the language name for each language with $filter('translate') within a service module...

Is there a syntax for getting the translation for a key for a specific language (without switching language altogether)?

**Comment by saoron** [comment]
You can do it in the view

     <select ng-repeat="language in languages">
          <option translate="LANG.{{language.CODE}}" ></option>
     </select>

And in your translation JSON just keep a translation for the languages for each language.

    {
        "LANG":{
           "EN": "English",
           ...
        }
    }

**Comment by envision** [comment]
This could work but I'm using PhraseApp to manage translations and the files are structures as single file per language...

@saoron is there a way to specifically define the language used with $filter('translate') ?

**Comment by knalli** [comment]
If you have a list of languages, you can translate just using the key as each of them. If you want to translate each key (language) in its language, you should have a look at `translate-language`: https://angular-translate.github.io/docs/#/api/pascalprecht.translate.directive:translateLanguage

```html
<select ng-init="languages=['de', 'en']">
  <option ng-repeat="lang in languages" translate-language="language" translate="LANG.{{language}}"></option>
</select>
```
