### ISSUE TITLE
Angular2 Support

### ISSUE THREAD

**Issue by sathyesh** [angular-translate/angular-translate#1565]
### Subject of the issue
Need Angular2 support with Ionic2 

### Your environment
* version of angular-translate
* version of angular
* which browser and its version

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://plnkr.co/edit/XorWgI?p=preview) as a base.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by knalli** [comment]
At this moment we have no Angular 2 support.

And for the records, reasons are: Lack of time, "agile/dynamic" Angular2 api design in the past which requires additional work.

Ideas do exist, but are not being implemented, see aso #995

**Comment by mendeza** [comment]
Meanwhile, there is no shortage of others filling the void for Angular 2+, for example https://github.com/ngx-translate is being used by a team in my company who previously used angular-translate with Angular 1.

**Comment by knalli** [comment]
Really looks like the thing I would do when restarting this. ;)

@mendeza What are the impressions?

**Comment by mendeza** [comment]
Well, my team hasn't used it, and I can't speak for the other team, but they are starting to build enterprise software with it, though still in early days. In fairness, the `ngx` project describes itself as 
> An implementation of `angular translate` for Angular 2

meaning of course that it is at the very least _strongly inspired_ by this project.

Don't be disheartened, with increased community effort there is still plenty of room for a next-gen version of Angular Translate. It is well-established, respected, and mature compared to many other ephemeral projects. 

Out of curiosity, now that the Angular 1.6 test has passed do you intend to cut a release, or will wait until this list is cleared? https://github.com/angular-translate/angular-translate/milestone/34

**Comment by knalli** [comment]
No, will cut some. But no release today.
