### ISSUE TITLE
It freezes Firefox to death

### ISSUE THREAD

**Issue by jednorog** [angular-translate/angular-translate#1566]
### Firefox not responding

Firefox stops responding when angular-translate tries to load JSON files.
It performs well in other browsers (Chrome 52.0.2743.116 m (64-bit) and MS Edge / Internet Explorer latest versions
### The environment
- version of angular-translate: 2.11.1
- version of angular: 1.4.9
- which browser and its version: Firefox 48.0.2
- operating system: Windows 10 (64)
### The plugin configuration

```
`       'pascalprecht.translate',
        ])
        .config(['$translateProvider', function ($translateProvider) {
            // define translation JSON files' name pattern
            $translateProvider.useStaticFilesLoader({
                prefix: 'scripts/translations/translation-',
                suffix: '.json'
            });
            $translateProvider.fallbackLanguage('en-AU');
            $translateProvider.preferredLanguage('en-AU');
            // remember language
            $translateProvider.useCookieStorage();
        }])`
```

**Comment by knalli** [comment]
@jednorog  Please provide a working demo with the crash.

**Comment by mickyinba** [comment]
the working application is on this URL (language switching is temporarily disabled but language defaults to using JSON translation file for en-AU. There is another JSON translation for lv-LV which can be accessed if cookie value is edited):
https://memberstest.icompetenatural.com/#/

**Comment by knalli** [comment]
@jednorog  Please provide an isolated demo/test case only with your issue.

**Comment by knalli** [comment]
Hello,

this is a second reminder: We are still waiting for your reply with additional details. If you cannot help us, we cannot help you.

Outdated issues will be discarded after a period of time.

Looking forward to hear from you.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
