### ISSUE TITLE
Filter does not respect translate-namespace directive

### ISSUE THREAD

**Issue by cudasteve** [angular-translate/angular-translate#1568]
### Subject of the issue

The `translate` filter, when used in the interpolation engine (`{{}}`), does not respect the `translate-namespace` directive the same way the `translate` directive does.  Given that both are used within the DOM (as opposed to when the filter is used via $filter()), I feel like they should both act the same way with respect to the namespace.  Is there any reason it can't work this way?

### Your environment
* version of angular-translate: 2.11.0
* version of angular: 1.5.6
* which browser and its version: all

### Steps to reproduce

This works:

    <div>
        {{'foo.bar' | translate}}
    </div>

This works:

    <div translate-namespace="foo">
        <span translate=".bar"></span>
    </div>

This does not work:

    <div translate-namespace="foo">
        {{'.bar' | translate}}
    </div>

**Comment by knalli** [comment]
A filter does not its element context. It's a pure function with some arguments.

**Comment by skyboyer** [comment]
since translate -namespace stores namespace name in $scope it's possible to fetch it and use for filter:
{{translateNamespace + '.bar' | translate}}
