### ISSUE TITLE
Cookie from cookie-storage disappears when browser is closed.

### ISSUE THREAD

**Issue by idenisovs** [angular-translate/angular-translate#1569]
### Subject of the issue
Cookie from cookie-storage disappears when browser is closed. Debug console shows that cookie expiration is set to _Session_ and there is no possibility to override the cookie expiration.

### Your environment
* version of angular-translate **v2.9.0**
* version of angular **v1.5.0**
* which browser and its version **Firefox v48.0**

### Steps to reproduce
1. In browser, clear cookies and open application, that uses the language-translate;
2. Switch from default language to another one;
3. In debug console, switch to the _Cookies_ tab and observe that language cookie is set;
4. Close browser, open it again and navigate to application;

### Expected behaviour
Translation language should be as selected in step **2**.

### Actual behaviour
Translation language still is default.

**Comment by knalli** [comment]
Hi @idenisovs ,

At first: We are actually using `$cookieStore` in the [built-in store implementation](https://github.com/angular-translate/angular-translate/blob/2.11.1/src/service/storage-cookie.js). If this is limitation, the limitation also applies to this eventually.

And second: We are using a [simple "store" interface adapting the $cache interface of AngularJS](https://angular-translate.github.io/docs/#/guide/10_storages) using only `get()` and `put()`. Therefore you easily write your own store handler, even using native JavaScript Cookie operations.
