### ISSUE TITLE
100% cpu

### ISSUE THREAD

**Issue by webattitude** [angular-translate/angular-translate#1573]
### Subject of the issue
cpu usage at 100%, page loaded. No action, just doing nothing the cpu is 100% high and more. No network activity.

### Your environment
* version of angular-translate
2.7
* version of angular
 angularjs-rails (1.5.6)
* which browser and its version
all

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://plnkr.co/edit/XorWgI?p=preview) as a base.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by vprasanth** [comment]
@webattitude I can't seem to reproduce this 😕

**Comment by webattitude** [comment]
weird, but I'm not surprised...
I can't figure out what is going on

**Comment by webattitude** [comment]
Also I'm not sure what to do to point out the source of this

**Comment by knalli** [comment]
Well, without any hint we cannot do nothing. 

Also: please check using the latest/recent versions of the libraries if possible.

**Comment by webattitude** [comment]
Yes, of course, sorry for that. I just hoped someone has had the same issue.
I'll just do as you say, update the lib and keep in touch.

**Comment by knalli** [comment]
I'm closing this right now. As already mentioned in the issue template, we need a demo showing the issue. You are not the only user of translate and until now no one else have reported such issues.

Feel free to open a new issue again if the issue stays and is related to angular-translate.
