### ISSUE TITLE
Can not translate the character "&"

### ISSUE THREAD

**Issue by hank-hong** [angular-translate/angular-translate#1574]
### Subject of the issue
Can not translate some special character, example for "&".

### Your environment
* angular-translate 2.11.1
* angular-translate-loader-static-files 2.11.1
* angular 1.2.0
* Chrome/IE 11

### Steps to reproduce
1. Load the file from json, the format of json is as follows:
{
"Permissions"       :"Permission & Role",
}

2. Set configration:
   $translateProvider.useStaticFilesLoader({
      prefix: '/i18n/',
      suffix: '.json'
    });
    $translateProvider.preferredLanguage('en_US');
    $translateProvider.useSanitizeValueStrategy('escape');

3. Use translate in HTML
<span>{{ 'Permissions' | translate }}</span>

### Expected behaviour
I want to have the character "Permission & Role", not " Permission &amp; Role"

### Actual behaviour
Only have label "Permission amp; Role"

**Comment by knalli** [comment]
@hank-hong  You have [chosen to escape all the content](https://angular-translate.github.io/docs/#/guide/19_security) -- so this is working as intended.

I would recommend having a look at the other strategies, but also having a look at #1101

**Comment by hank-hong** [comment]
@knalli  Thank you very much. It's OK now by using sanitizeParameters.
