### ISSUE TITLE
translate-attr not working

### ISSUE THREAD

**Issue by nunof07** [angular-translate/angular-translate#1577]
### Subject of the issue
Reading the [documentation](https://angular-translate.github.io/docs/#/guide/05_using-translate-directive#using-translate-directive_translate-html-attributes) I would expect `translate-attr` to work, but I could only get it working using the deprecated way.

Using `translate-attr="{ placeholder: 'placeholder' }"` doesn't work.
Using `translate translate-attr-placeholder="placeholder"` works.

### Your environment
* version of angular-translate: 2.12.0
* version of angular: 1.5.8

### Steps to reproduce
Plunker: http://plnkr.co/edit/oIXnkRVHpO3xP4kDdsJ9?p=preview

**Comment by tspaeth** [comment]
Looks like the directive "translateAttr" is not included in the dist build result.

**Comment by tspaeth** [comment]
@odedniv The translate-attr.js file is having some issues on the jshint step as well.

**Comment by odedniv** [comment]
Running `grunt test` I don't see any error, not sure how else to trigger them.

Should the new file maybe be added to https://github.com/angular-translate/angular-translate/blob/master/Gruntfile.js ?

Is there some build process to run?

**Comment by tspaeth** [comment]
Yup, it must be added somewhere around line 60 in that file, then it will be added to the core js.
The fix will probably take some days as @knalli is afaik off for some days and I'm not 100% aware of the release process currently. 😞

**Comment by odedniv** [comment]
In this case I won't be touching anything... Glad to see people need it :smile:

**Comment by knalli** [comment]
Ah.. the grunt file have to be patched adding the new js file also. Sorry, overseen this. 

PRs are welcome, then I can handle this next week.

**Comment by kopancek** [comment]
Added a PR, feel free to review.

**Comment by knalli** [comment]
Will be available in 2.12.1 shortly.

**Comment by dbrgn** [comment]
Doesn't seem to work for me though... Maybe I'm doing something wrong? Can someone confirm that it works now with the version installed through bower?

**Comment by knalli** [comment]
Here is a demo http://plnkr.co/edit/BjccjrhDqaweUHrkykx2?p=preview using the 2.12.1 tag, which is automatically the bower release of 2.12.1

**Comment by dbrgn** [comment]
@knalli thanks. strange, then I'll have to debug some more :)

**Comment by a-change** [comment]
Hi,
Don't know if it's a bug or it isn't supposed to work this way or just my errors somewhere, but it seems that `translate-attr=""` doesn't work for directive attributes, like in this case with `ui-select`: 
`<ui-select-match translate-attr="{placeholder: 'PLACEHOLDER'}">{{$select.selected.value}}</ui-select-match>` (angular-translate: 2.13.1, angular: 1.6.1)
Here's a plunkr: https://plnkr.co/edit/r5aBGLVXIqXoxWvJSWge?p=preview 

In this case it seems it successfully adds the attribute to the wrapping `<div>` but not to the `<input>` element inside it. Filter works fine and adds the attribute both to the `<div>` and the `<input>`.

A similar thing is reported here: http://stackoverflow.com/questions/41035450/angular-translate-directives-attribute-without-the-filter

**Comment by odedniv** [comment]
@a-change this looks like a separate bug (which is not really stackoverflow material in my opinion).

Looks like the way `translate-attr` adds the attributes doesn't compile the element in the way `ng-attr-*` does for example (you can add new directives with `ng-attr-*`).

In my short search I couldn't find where `ng-attr-*` is implemented, though I'm afraid it's not a normal directive. If you can find how they do it and add a pull request that would probably be best, otherwise I encourage you to open a separate issue for this.

PS. what you wrote about `ui-select` might actually be a priority issue (or more than that if `translate-attr` is triggered on the next digest with a watcher), which is another different issue that might even be harder to solve.

**Comment by jamesbrobb** [comment]
Did this issue ever get resolved? I'm still experiencing it in version 2.15.1

**Comment by odedniv** [comment]
@jamesbrobb which issue? Multiple things are discussed here. You should submit a new issue with your specific problem (this issue has been closed).

**Comment by jamesbrobb** [comment]
@odedniv sorry, should have been more specific. I'm referring to the previous point raised by @a-change

**Comment by odedniv** [comment]
@jamesbrobb I told @a-change as well - this is not related to the original bug opened by @nunof07, why not open a separate issue that can be discussed with a proper title?

**Comment by jamesbrobb** [comment]
Will do, thanks for the response
