### ISSUE TITLE
working with official released locale file?

### ISSUE THREAD

**Issue by dotku** [angular-translate/angular-translate#1579]
### Subject of the issue
Angular official does already release few locale file: https://docs.angularjs.org/guide/i18n, I want to use them with angular-translate, such as {{12345 | currency}} would automatically translate the currency sign according to the locale setting or angular-translate language setting.

**Comment by tspaeth** [comment]
angular-translate is a translation module while the official i18n modules for AngularJS target localization. These are two different things. 

Better ask such "how do I..." questions on Stackoverflow: http://stackoverflow.com/questions/tagged/angular-translate - you'll reach a bigger audience - if you really need some locale integrated stuff in angular-translate. 

This issue tracker is mainly the feature-/bugtracker for angular-translate. But you're always free to add a feature request later on. 

Thanks.

**Comment by knalli** [comment]
We do not provide or support anything regarding "localization" -- only translation.

Perhaps you are looking for https://github.com/lgalfaso/angular-dynamic-locale
