### ISSUE TITLE
untranslated content when app loads

### ISSUE THREAD

**Issue by SET001** [angular-translate/angular-translate#1580]
### Subject of the issue

I made a simple configuration to test translations and on application start I can see untranslated content. I do not use async loading so I suppose here should be such a problem and I don't have to use `translate-cloak`. Or do I still have?
### Your environment
- version of angular-translate - 2.12.0
- version of angular - 1.5.8
- which browser and its version - Google Chrome Version 51.0.2704.106 (64-bit
### Steps to reproduce

```
    $translateProvider.useSanitizeValueStrategy(null);
    $translateProvider.translations('en', {
        common: {
            home: "home"
        }
    });
    $translateProvider.preferredLanguage('en')
```
### Expected behaviour

User should not see untranslated content
### Actual behaviour

I see FOUC as the app loads

**Comment by SET001** [comment]
I also have `$translate.use('en');` in my main controller but that does not change anything

**Comment by tspaeth** [comment]
You provided an example of the configuration, but not a complete example - that is bad as so many things could lead to this situation. (slow JS loader, order of scripts etc). Have you also used the translate-cloak stuff?

**Comment by SET001** [comment]
I'm using browserify to put all my files and libraries in single file so there is no need to show JS loader. I do not loading translation from anywhere, I declare them in application configuration as show in my first post.

In templates I'm trying both ways:

`<li ui-sref-active="active"><a ui-sref="news" translate>common.home</a></li>`

and

`<li ui-sref-active="active"><a ui-sref="news" translate>{{'common.home'|translate}}</a></li>`

Is this problem suppose to happen when all translation strings declared in application configuration block?

**Comment by tspaeth** [comment]
One thing that you always should have in mind: If e.g. the base html file already contains translation keys, you will nearly always see them shortly as they are loaded, immediately rendered and the javascript is loaded afterwards. This all depends - as said - on some complexity levels. If you really need some 100% hiding, the best is to hide the targeted elements somehow with inline CSS or similar. 
And a bigger JS file could still cause this behavior.

**Comment by SET001** [comment]
Thank you. Indeed those phrases were on base html file. I have to move them to ui-router templates or use `translate-cloak`

**Comment by SET001** [comment]
@tspaeth,  what problems do you mean saying "And a bigger JS file could still cause this behavior.". Currently on my local dev environment the whole application concatenated in 5MB file (which loads in ~200-250 ms)

**Comment by knalli** [comment]
ng-cloak covers loading of AJS itself (maybe untranslated values of filters) and will remove the class of AJS is "ready", and translate-cloak covers loading of (first) translations and will remove the class of translate is ready.

As everything is working with events side-by-side, I would add the cloaks or event hooks for something else outside a template always.
