### ISSUE TITLE
Angular translate gets resource string from .json file even if file is deleted.

### ISSUE THREAD

**Issue by AkkiKumar9487** [angular-translate/angular-translate#1581]
###Angular translate gets resource string from .json file even if file is deleted.

### Your environment
* version of angular-translate -- v2.11.1 - 2016-07-17
* version of angular -- v1.5.7
* which browser and its version -- IE11 (11.0.9600.18282)

### Steps to reproduce
i am using i18n/.json files for my translations.
if i select any language and run application, angular translation works properly and display strings according to selected language.
But, if i delete .json file of selected language and restart browser, it still works and show translated strings even if i deleted file from i18n folder.
If i press refresh/F5 browser then only it fails and shows strings of fallback language.
Is there any cache involved in this?

### Expected behaviour
It should not show translated strings if i delete .json file from i18n folder

### Actual behaviour
It shows translation even if corresponding .josn file of selected language is deleted.

**Comment by knalli** [comment]
We do not use a cache directly, however, you can provide additional configuration options for $http if you want (https://github.com/angular-translate/angular-translate/blob/2.12.0/src/service/loader-static-files.js#L47).

This should cover all options you can make in AngularJS for XHR. If this does not help, it is a server/app issue in general.

**Comment by AkkiKumar9487** [comment]
Thanks for your reply
This Post [Disable Cache](http://stackoverflow.com/questions/16098430/angular-ie-caching-issue-for-http) helped me, Not it is working fine.
