### ISSUE TITLE
Event when translate filter doesn't find resource

### ISSUE THREAD

**Issue by ruisilva450** [angular-translate/angular-translate#1583]
### Subject of the issue
I have a huge website that is using angular-translate and it's great, but when we make changes to resources (add/delete) I want to make sure that everything is has a resource in place without having to look at every page of my website.
It would be awesome to have an event fired every time a resource is not found by the translate service. 
Any reason not to include this feature or am I missing some docs on how to do it?

### Environment
* Angular-translate - v2.12.0
* Angular - v1.5.7

### Steps to reproduce
https://plnkr.co/edit/FZUa7LhasoRh9HJnObr1?p=preview

**EDIT**: If I have a resource that is 'hello', the expected way to translate this using the angular filter is `{{ 'hello' | translate }}`. But I make a mistake and type `{{ 'helo' | translate }}` it doesn't show translated on the DOM as expected. If this ever happens, I want to be notified by an event (at $rootScope level maybe) that the angular filter didn't found the 'helo' resource. 

### Expected behaviour
An event firing when we switch language to **DE** and translate service not being able to find *hello* resource.

### Actual behaviour
Doesn't seem to have that event

**Comment by knalli** [comment]
Do you mean the loader cannot find languages?

You can build your own loader (i.e. copy the default url loader) and add your custom logic

**Comment by ruisilva450** [comment]
I missed the point. Edited the original issue

**Comment by knalli** [comment]
See docs https://angular-translate.github.io/docs/#/guide/16_error-handling

**Comment by ruisilva450** [comment]
That is a great help, but doesn't solve my primary issue. 
I don't want to have to visit all pages so that I have this error logs.

**Comment by knalli** [comment]
If the pages are not visited, the code will not be executed. 
If the code is not executed, the translations will not be requested. 

It just simple as that. Either you execute everything (prepared in isolated test context), or you have to develope a static analyze of our code. 

For the moment we can provide the solution via the handler only.
