### ISSUE TITLE
translate-cloak

### ISSUE THREAD

**Issue by SET001** [angular-translate/angular-translate#1584]
Translate-cloak works in very strange way:
1. If I just put `translate-cloak` directive on translated element - that just wont make any effect.
2. If I will set any value to `translate-cloak` attribute, like `translate-cloak="asd"` - then it seems like it will set a `translate-cloak` class to that element (the attribute value seems to be ignored)
3. Also it does not actually hide translated element unless translation loaded (as one may suggest from analogy with ngCloack). Instead it require all such elements to be hidden and then it will (try to) show it.
4. Finally after I make all this work, I can still see barely noticeable flickering of untranslated content (still better than when not using translate-cloak)

Please help me understand where I'm wrong about understand how this suppose to work and also are there any ways to:
1. make it hide translated elements, not show
2. make it work without visible flickering
### my environment settings:

version of angular-translate - 2.12.0
version of angular - 1.5.8
which browser and its version - Google Chrome Version 51.0.2704.106 (64-bit
### the code I'm using

```
$translateProvider.useSanitizeValueStrategy(null);
    $translateProvider.translations('en', {
        common: {
            home: "home"
        }
    });
    $translateProvider.preferredLanguage('en')
```

**Comment by knalli** [comment]
Please provide a demo; what do you mean exactly?

Also please be aware: `translate-cloak` does not make sense using static translations. It is only used for dynamic/async loaded translations. If you need an expression cloak, you have to stick with `ng-cloak`.

**Comment by knalli** [comment]
Is this a dup of #1580 ?

**Comment by mtwar** [comment]
Fix: https://github.com/angular-translate/angular-translate/pull/1689

**Comment by knalli** [comment]
Duplicate and will be fixed.
