### ISSUE TITLE
Update to messageformat@1.0.0

### ISSUE THREAD

**Issue by arty-name** [angular-translate/angular-translate#1586]
### Update to messageformat@1.0.0

Current angular-translate depends on messageformat@0.3.1. Recently messageformat@1.0.0 was released. It would be nice to update to it. 

Issue #1227 here has [a comment from the co-author of messageformat regarding changes in this release](https://github.com/angular-translate/angular-translate/issues/1227#issuecomment-193240916).

**Comment by knalli** [comment]
Yeah. Contribution is welcome. I'm not aware of the release at all, perhaps API changes?

**Comment by arty-name** [comment]
I can’t be sure, but for my relatively simple use cases I have just plugged the new version in and it works. Mayme @eemeli himself can comment.

**Comment by knalli** [comment]
Ok.

Just to be clearify: You can always override your local version (of messageformat) and pin that version explicitly. bower term is resolution, npm term is just a local dependency.

**Comment by eemeli** [comment]
The API has changed a bit, but assuming that [this comment](1227#issuecomment-193251607) is still accurate in its description of how you use it, no changes should be needed.

**Comment by knalli** [comment]
Issue/PR open #1661

**Comment by knalli** [comment]
in canary landed
