### ISSUE TITLE
Default value for placeholder

### ISSUE THREAD

**Issue by auschmann** [angular-translate/angular-translate#1592]
Hi,

is it possible to set a default value for a specific placeholder-key and use this in all strings?

I am asking because we are currently building a white label feature for our product.
In this feature the user can replace the product name with it´s own name.

So if i have strings like:
"Welcome to {{product_name}}",
"Thanks for using {{product_name}}"

It would be nice if i could set the value of product_name globally.

Hope this makes sense.

Kind regards

André

**Comment by knalli** [comment]
No, this is not possible at the moment. Feel free to make PR adding such a base default parameters integration.

In your case, you could try to make solution with a generated translation map also.

**Comment by TheWrongAlice** [comment]
Did this get anywhere? I need this :D
