### ISSUE TITLE
**$translate.storageKey** is not a function

### ISSUE THREAD

**Issue by pdjole** [angular-translate/angular-translate#1596]
### Subject of the issue
**$translate.storageKey** is not a function

### Your environment
* version of angular-translate - latest (2.12.1)
* version of angular - latest (1.5.8)
* tried on latest Chrome and Firefox

### Steps to reproduce
Basically what i did is, that i followed getting started tutorial on official page.
I only referenced, **angular-translate** module and added '**pascalprecht.translate**' into angular app module definition, reloaded webpage and this is what i get:

### Expected behaviour
 _var key = $translate.storageKey()_
It happens on line **44** of **angular-translate.js** file

Is this a bug, or am i missing something very obvious?

Cheers,
Djordje

**Comment by tspaeth** [comment]
This doesn't happen here. See this simple example on the versions you mentioned:

https://plnkr.co/edit/7zdTmhZloVEaovjjy2DV?p=preview

But make sure that you include as well an implementation for cookie / storage.
Feel free to modify the plnkr to show your problems in detail. Without an example code, it's hard to help.

**Comment by pdjole** [comment]
Hey, i also tried simple tutorials and it works, i suppose it has to do with our project's huge and complex dependency mechanism. I cannot model it well in plankr, so sorry for trouble, i will find a way around it.
