### ISSUE TITLE
determinePreferredLanguage - Second Language

### ISSUE THREAD

**Issue by JordiOrriols** [angular-translate/angular-translate#1597]
### Second language with determinePreferredLanguage and useStaticFilesLoader

I'm trying to get the correct language with determinePreferredLanguage. If I set one of the languages of the registerAvailableLanguageKeys as a First Option, there are no problems.

I found the solution of adding this line `'*': 'en'` to fix if my first option is not on the list. so works fine if my first option is 'ca' for example.

But if I choose another language not in the list (like 'ca'), and the second one like 'es' (in the list), i'm getting the ID of the strings. And if I remove the slash comments, and add the line  `'*': 'en'` (with the comma), I get always english even I set my second option to Spanish due to my first option is not on the list.

I don't know if I'm missing something, but I can not find the way to get determinePreferredLanguage working with more than 1 language preference.
### My environment
- version of angular-translate v2.8.1
- version of angular v1.5.5
### Steps to reproduce

```
$translateProvider
  .useStaticFilesLoader({
      prefix: 'https://example.com/translations/',
      suffix: '.json'
  })
  .registerAvailableLanguageKeys(['da-DK', 'de', 'en', 'es', 'fr', 'nl', 'sk', 'sv'], {
    'da_*': 'da-DK',
    'de_*': 'de',
    'en_*': 'en',
    'es_*': 'es',
    'fr_*': 'fr',
    'nl_*': 'nl',
    'sk_*': 'sk',
    'sv_*': 'sv'
  //  '*': 'en'
  })
  .fallbackLanguage('en')
//  .preferredLanguage('en')
  .determinePreferredLanguage()
  .useLoaderCache(true);
```
### Expected behaviour

I expect to get Spanish as a default Language
### Actual behaviour

I get Id's or English language.

**Comment by tspaeth** [comment]
The question is: What browser are you using and what are the locale settings. Client side detection is not as stable as also written in the documentation. Are all language files as well in place?
And also try again with some latest angular-translate version.

For a better diagnosis, a Plnkr would be helpful.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
