### ISSUE TITLE
Can not read the json on server

### ISSUE THREAD

**Issue by hank-hong** [angular-translate/angular-translate#1598]
### Subject of the issue
Angular-translate get the wrong path of url and it can't read the json on server,

### Your environment
* angular-translate 2.11.1
* angular 1.2.0
* Chrome Version 53.0.2785.113 m (64-bit)

### Steps to reproduce
I used staticFilesLoader to get the json on server.

The file **en.json** is in the path **'folder1/folder2/langs/'** on the server.

The codes I used are as follows:
```
$translateProvider.useStaticFilesLoader({
      prefix: '/folder1/folder2/langs/',
      suffix: '.json'
    });

$translateProvider.preferredLanguage('en');
$translateProvider.useSanitizeValueStrategy('sanitizeParameters');
```
On the other hand, the project I published on server is "**http://192.168.0.1/angularJs/**".

It's very weird, the path Angular-translate read is "**http://192.168.0.1/folder1/folder2/langs/en.json**", then the file won't be found.

It should be "http://192.168.0.1/angularJs/folder1/folder2/langs/en.json".

### Expected behaviour
The process will read the the json for path "**http://192.168.0.1/folder1/folder2/langs/en.json**".
The path "angularJs" is missing.

### Actual behaviour
The path Angular-translate read should be  "http://192.168.0.1/**angularJs**/folder1/folder2/langs/en.json".

Could you  please help me with this issue?

Thanks

**Comment by knalli** [comment]
Don't prefix with an absolute path `'/folder1/folder2/langs/'`.

**Comment by hank-hong** [comment]
Hello @knalli  

Thanks for your response, but could you please tell me how to read the json in some special path if I won't prefix with an absolute path.

For example, if the json in **"/folder1/folder2/langs/"** on server, how can I set the configuration?

$translateProvider.useStaticFilesLoader({
      prefix:  **???**  ,
      suffix: '.json'
    });

If I didn't prefix with a path, it doesn't work.

Thanks

**Comment by tspaeth** [comment]
what happens if your remove the / at the beginning? Then it is a **relative** path.
Try that first

**Comment by hank-hong** [comment]
Hello @tspaeth  

It works, only remove "/" at the beginning.

Thank you so much, it puzzled me for a long time. I think it's the best way.

Thanks again!!!

**Comment by hemachandrav** [comment]
Thanks. After removing "/" at the beginning it's working for me.
