### ISSUE TITLE
Passing HTML into Variable Replacement 

### ISSUE THREAD

**Issue by ericjames** [angular-translate/angular-translate#1599]
I want to pass HTML span into my translated string because obviously I would want to style certain areas differently.

So in my json `"MINS": "{{number}} minutes"` would become `<span class="numeral">5</span> minutes`

But looks like I can't just do `{{ "MINS" | translate:{number:'<span>5</span>'}`

However it DOES work with directive version `translate-value-number="<span>5</span>"`

http://plnkr.co/edit/El0Zr7LKfuXsQXZQjEn9?p=preview

**Comment by knalli** [comment]
Please have a look at https://angular-translate.github.io/docs/#/guide/05_using-translate-directive#using-translate-directive_post-compiling

I think that is what you are looking for.

**Comment by knalli** [comment]
Also to be mentioned: https://angular-translate.github.io/docs/#/guide/19_security -- the chosen strategy is important.

**Comment by ericjames** [comment]
Yeah it looks like sanitized is the future, that means the templating for translations will have to be rethought and simplified since we can only use sanitized HTML.
