### ISSUE TITLE
MissingTranslationHandlerLog changes functionality

### ISSUE THREAD

**Issue by JaZo** [angular-translate/angular-translate#1600]
### Subject of the issue
When using the MissingTranslationHandlerLog, the $translate service does not reject the translation-promise when the translation is missing.

### Your environment
* version of angular-translate: 2.12.1
* version of angular-translate-handler-log: 2.12.1
* version of angular: 1.5.8
* which browser and its version: Firefox Dev 51.0

### Steps to reproduce
Please see these plunkers: [without missing-translation-handler-log](http://plnkr.co/edit/8UpiWLDzqDIxXLmrYuwF?p=preview) and [with missing-translation-handler-log](http://plnkr.co/edit/ONq9POtNFtaUm4ZFBfZQ?p=preview).

### Expected behaviour
I would expect that the $translate service always rejects the translation-promise with or without using the MissingTranslationHandlerLog as stated in the [documentation](https://angular-translate.github.io/docs/#/guide/03_using-translate-service).

### Actual behaviour
The $translate service resolves the translation-promise when using the MissingTranslationHandlerLog.

**Comment by knalli** [comment]
Do you like providing a PR?
