### ISSUE TITLE
How Does the Library Re-Compile Views When Language is Changed?

### ISSUE THREAD

**Issue by Irrelon** [angular-translate/angular-translate#1601]
Great module!

I am interested in how the module signals to AngularJS that the language has changed and the rendered views need updating? I'm talking about the technical underlying process rather than how to use the $translate.use() method.

This is purely from an academic interest point of view as I would like to work on some updates and roll them into a pull request but need to understand the underlying functionality first.

I am the author of ForerunnerDB (https://github.com/Irrelon/ForerunnerDB) and have some ideas about how I would like to integrate with this module.

**Comment by knalli** [comment]
This is a plugin for the AngularJS framework. The technical concept as well as the implementation is part of the framework (scope, digesting, events). I do not want to not rephrase AngularJS details here.. :)

- https://docs.angularjs.org/guide/introduction
