### ISSUE TITLE
$translateProvider.useStaticFilesLoader with non JSON file

### ISSUE THREAD

**Issue by kaythree** [angular-translate/angular-translate#1603]
### Subject of the issue
I am trying to configure my app to support multiple languages. Its working fine when I have .json files under /translators folder. But when I have .properties file , the correct content is not displaying but keys showing up.

### Your environment
* angular-translate - v2.12.1 - 2016-09-15
* angular 1.5.8
* All browsers

### Steps to reproduce
Its simple. The translate Provider working without any issue, but when I give prefix as .properties its failing , see my code below

.config(['$translateProvider', function($translateProvider) {

    $translateProvider
        .useStaticFilesLoader({
            prefix: '../translations/content-',
            suffix: '.properties'
        })
        .preferredLanguage('en');
    // Enable escaping of HTML
    $translateProvider.useSanitizeValueStrategy('escape');
}]);

### Expected behaviour
Since I have file with the name content-en.properties under my /translations folder, I am expecting it will work the way how it picked the right keys from a JSON file.

### Actual behaviour
Application is trying to load the content-en.properties file (in request HEADERs, I see ACCPET : application/json ) and in the browser I am not seeing content from my properties file but keys.

**Comment by tspaeth** [comment]
is your properties file in A=B - style or as JSON-format? (just to make sure...)

**Comment by kaythree** [comment]
A=B format. See the properties file below
GCC_USERNAME="User Name",
GCC_PASSWORD="Password",
GCC_LOGIN_TEXT="Login"

**Comment by kaythree** [comment]
This is what I am trying to read the properties file..

<div class="login-page">
        <form method="POST" name="login">
            <label>{{ 'GCC_USERNAME' | translate}} </label>: <span><input type="text" name="username" value=""></span><br />
            <label>{{ 'GCC_PASSWORD' | translate}} </label>: <input type="text" name="password" value=""><br /><br />
            <input type="submit" name="submit" value="{{'GCC_LOGIN_TEXT' | translate}}">
        </form>
    </div>

**Comment by tspaeth** [comment]
No. it's not possible with the base we provide. You may have a look at #924

**Comment by knalli** [comment]
The file loader is to be used for JSON files. However, you can adapt its implementation for another layout like properties files.
