### ISSUE TITLE
Translate from config ?

### ISSUE THREAD

**Issue by cyrilchapon** [angular-translate/angular-translate#1606]
In order to set the title of my page from ui-router, I have to $translate() from a .config.

How to accomplish this ?

```
$stateProvider
      .state('app', {
        abstract: true,
        templateUrl: '<ui-view/>'
      })
        .state('app.map', {
          url: '/map',
          templateUrl: 'views/map.html',
          controller: 'MapCtrl',
          title: // <-- HERE I WANT TO $TRANSLATE
        })
```

**Comment by knalli** [comment]
You cannot use the service in config phase.

Have a look at ui-router's `resolve()`, otherwise the corresponding controller in use.
