### ISSUE TITLE
useStaticFilesLoader to load multiple files in different locations gives 404 error

### ISSUE THREAD

**Issue by alokapm** [angular-translate/angular-translate#1608]
angular-translate docs specifies that loading multiple static files from different locations is possible with useStaticFilesLoader.

```js
$translateProvider.useStaticFilesLoader({
    files: [{
        prefix: 'locale-',
        suffix: '.json'
    }, {
        prefix: '/absolute/path/to/locale-',
        suffix: '.json'
    }, {
        prefix: 'another/path/to/locales/',
        suffix: ''
    }]
});
```

I'm trying to load en.json (vendor/i18n/en/en.json) and fr.json (vendor/i18n/fr/fr.json) locale files in different locations and using the following code.

```js
$translateProvider.useStaticFilesLoader({
    		    files: [{
    		        prefix: 'vendor/i18n/en/',
    		        suffix: '.json'
    		    }, {
    		        prefix: 'vendor/i18n/fr/',
    		        suffix: '.json'
    		    }]
    		});
      $translateProvider.preferredLanguage('en');
```

When loading the app it gives the error
'angular.js:11756 GET http://localhost:3000/vendor/i18n/fr/en.json 404 (Not Found)'

It is trying to locate en.json file inside the fr folder.

If I remove the files array and both files are included inside vendor/i18n this works perfectly. 

**Environment**
* version of angular-translate: 2.10.0

**Expected Behaviour**
Should load both locale files in distinct locations

**Actual Behaviour**
Getting a 404 error and translation is not working.

**Comment by knalli** [comment]
Well, if you are defining the prefix `vendor/i18n/en/` and suffix `.json`, it will result into `vendor/i18n/en/fr.json` for language `fr`. Suffix + language + prefix.

If you are planing to group language files into dedicate directories, you will have to build your own loader. That is easy, just have a look for custom loaders and use an existing loader (like the static files loader) for a start.
