### ISSUE TITLE
Error when changing to language with more cardinal categories 

### ISSUE THREAD

**Issue by yusk90** [angular-translate/angular-translate#1609]
### Subject of the issue
Doesn't work when in runtime changing to language with more cardinal categories (http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html). For example from English to Russian. In that case it throws error:
```
Invalid key `few` for argument `NUMBER`. Valid plural keys for this locale are `one`, `other`, and explicit keys like `=0`.
```

### Your environment
The latest versions, see plnkr.

### Steps to reproduce
https://plnkr.co/edit/CmFVg7v5wHVzx7bPHn8r?p=preview

**Comment by knalli** [comment]
Hi @yusk90  

The error is thrown by (your chosen) interpolation adapter for messageformat. Btw: The minified code of messageformat does not help, the actual used version is not readable.

Anyway: I don't seen an issue for angular-translate, and we cannot help. Perhaps I have missed the point, but the problem is because of an unsuitable translation.

**Comment by yusk90** [comment]
Hi @knalli 

Ok, sorry for minified code, updated version: https://plnkr.co/edit/CmFVg7v5wHVzx7bPHn8r?p=preview.
I've also added text that doesn't use messageformatting and it translates correctly both ways. I don't sure if it's a problem with angular-translate-interpolation-messageformat or with messageformat itself. For me it looks like for pluralized message plugin somehow doesn't change locale. Hope it helps a little.

**Comment by knalli** [comment]
The error is produced by messageformat, not by our adapter. Reading the messages it looks like `few` is illegal used.

You should break down the issue calling messageformat directly with the given locale, text and params.

**Comment by yusk90** [comment]
At the same time if I start app with
```
$translateProvider.preferredLanguage("ru");
```
it works as expected for all cardinals, but still messageformat doesn't detect locale change when switching between languages.
Ok, if it's not a problem with angular-translate adapter, I'm sorry for taking your time.
Will try to dig deeper into problem.
