### ISSUE TITLE
Issue when calling a function for a translate-value

### ISSUE THREAD

**Issue by xtoff** [angular-translate/angular-translate#1611]
### Description
If I call a function for filling up a translate-value value, this function (in my case getTextProperty) gets called multiple times.

`<h1 translate="EXAMPLE" translate-values="{textProperty: getTextProperty()}"></h1>`

### I use:
* angular-translate v2.12.1
* angular v1.4.9
* Chrome

### Steps to reproduce
Here is my fiddle: http://jsfiddle.net/X2fsw/106/
Open console before loading the page and try to type something in the input field. Then you see the 'Actual behaviour' and not what I expected..

### Expected behaviour
The console.log in 'getTextProperty' should only be called once when loading the page and when modifying an input field.

### Actual behaviour
When you check console, the console.log in the property 'getTextProperty' is called 3 times when loading the page and every time I type in a character in an input field with a ng-model property the console.log is also called.

**Comment by knalli** [comment]
That's right. AngularJS filters (and you are using it) are called multiple times. That's a core feature/behavior.

Solution: Do not use function calls in expressions. This is a general recommendation, not related to angular-translate specifically.
