### ISSUE TITLE
Proper binding to allow inline html

### ISSUE THREAD

**Issue by just-trey** [angular-translate/angular-translate#1613]
### Subject of the issue
I am trying to use translation bindings that contain inline HTML elements using `$translateProvider.useSanitizeValueStrategy('sanitizeParameters');`

`<h1>{{'value' | translate}}</h1>`

### Steps to reproduce
https://plnkr.co/edit/vDsqsFyvT3ntysO8DmpN?p=preview

### Expected behaviour
Item should print as 
_value_

### Actual behaviour
HTML is actually printing to the screen.
\<em\>value\</em\>

the below ways render as I would expect as _value_
```
<h1 translate="">value</h1>
<h1 translate="value"></h1>
```

**Comment by knalli** [comment]
Hi @just-trey 

That result is correct so far: AngularJS filters' output is escaped always (by AngularJS).

I also recommend and linking to #1588 as we discussing how we can improve the situation with filters and services also.

I'll close this as it duplicates #1588 actually. Feedback is still welcome.
