### ISSUE TITLE
translate with brace in message

### ISSUE THREAD

**Issue by brusand** [angular-translate/angular-translate#1614]
### Subject of the issue

i want to translate message wich contain braces inside, how to encode them :+1:  
        "data_caption": "enter the json pojo key/value, like : { \"key1\" : \"value1\", \"key2\":  \"value2\" } ",
### Your environment
- version of angular-translate
  1.5
- version of angular
  1.5
- which browser and its version
  chrome
  ### Steps to reproduce
  Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://plnkr.co/edit/XorWgI?p=preview) as a base.
### Expected behaviour

display :  enter the json pojo key/value, like : { "key1" : "value1", "key2":  "value2" } 
### Actual behaviour

Error: [$interpolate:interr] Can't interpolate: {{ 'lo.assets.commands.new.data_caption' | translate }}
Error: Parser error: SyntaxError: Expected "," or "}" but ":" found.

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
