### ISSUE TITLE
 Error: [$rootScope:infdig] when translating data-title attribute in ngTable

### ISSUE THREAD

**Issue by meeravi007** [angular-translate/angular-translate#1615]
### Subject of the issue

I'm using ng-table and angular-translate to translate header (not dynamically) it was working quite well before language file separation but after language file separated it throwing [$rootScope:infdig]  error. 

   "td data-title="'AUTHOR' | translate">{{ w.author }}</td>"
### Your environment
- angular-translate - v2.12.1 - 2016-09-15
- version of angular 1.4.7

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
