### ISSUE TITLE
How to use translation cache 

### ISSUE THREAD

**Issue by mukuljp** [angular-translate/angular-translate#1617]
### Subject of the issue

How to use translationCache properly 
### Description

i am currently using the static file loader to load json file for development ,but planning to use translationCache in production build  , below is the code i tried to manualy trigger the cache , but it is not working , It would be great to provide steps to use translationCache ,
Thanks 
### Current Code

`  MyApp.config(['$translateProvider', function($translateProvider) {

```
  $translateProvider.preferredLanguage('content');
  $translateProvider.useLoaderCache(true);
  $translateProvider.useStaticFilesLoader({
      prefix: '/content/',
      suffix: '.json'
  }); }]);
```

```
MyApp.run(function($translationCache, $templateCache) {
          $translationCache.put('content/content.json', {
          "HEADLINE": "What an awesom sase module! {{greeting}}",
          "PARAGRAPH": "Sddrsly!",
          "PASSED_AS_TEXT": "Hey there! I'm passed as text value!",
          "PASSED_AS_ATTRIBUTE": "I'm passed as attribute value, cool ha?",
          "PASSED_AS_INTERPOLATION": "Beginners! I'm interpolated!",
          "VARIABLE_REPLACEMENT": "Hi {{name}}",
          "BUTTON_LANG_DE": "German",
          "BUTTON_LANG_EN": "English"
      });
  });`

```

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
