### ISSUE TITLE
MessageFormat: add support for date and time formatting

### ISSUE THREAD

**Issue by fromi** [angular-translate/angular-translate#1619]
### Subject of the improvement
We are using $translateMessageFormatInterpolation, and we would like to use the date and time function available in messageFormat.js: https://messageformat.github.io/guide/#intl-formatters
As you can see in the documentation, ".setIntlSupport(true)" must be call on messageFormat object before date and time function are available.

We explored the $translateMessageFormatInterpolation factory code, and there is currently no convenient way to customise the new MessageFormat objects created in there.

### Your environment
* version of angular-translate: 2.11.0
* version of angular: 1.5.0

**Comment by knalli** [comment]
Added.

```
angular.module(‘app’, [‘pascalprecht.translate’])
       .config(($translateMessageFormatInterpolationProvider) => {
         $translateMessageFormatInterpolationProvider.messageFormatConfigurer((mf) => {
           mf.setIntlSupport(true);
         });
       });
```

**Comment by fromi** [comment]
Thanks :)
