### ISSUE TITLE
onReady doc duplicate of isReady

### ISSUE THREAD

**Issue by siebenfarben** [angular-translate/angular-translate#1620]
### Subject of the issue

The function documentation for onReady is a duplicate of isReady and is not exactly appropriate.
### Your environment
- Not applicable
### Steps to reproduce

https://github.com/angular-translate/angular-translate/blob/master/src/service/translate.js#L2255
### Expected behaviour

Updated doc is provided.
### Actual behaviour
- Not applicable

**Comment by knalli** [comment]
Ehm.. `$translate.isReady()` returns a boolean, `$translate.onReady(fn)` consumes a callback and returns a promise.

Which one these behaviors make you feel these are duplicates of each other?

**Comment by siebenfarben** [comment]
onReady does not "Returns whether the service is "ready" to translate (i.e. loading 1st language)."

**Comment by knalli** [comment]
Gotcha.

Thank you for clarification.
