### ISSUE TITLE
translate-keep-content also for translate-attr

### ISSUE THREAD

**Issue by fmunafokion** [angular-translate/angular-translate#1621]
Hi,
what about having anything similar to `translate-keep-content` also for `translate-attr`?

It could be `translate-attr-keep-content` for the directive and `.keepAttrContent(true)` for the provider.

The idea could be to apply the attribute value, if present.
In the following example, and without a translation for "id_2", `title` could be "a title" and not "id_2".

`<a href="....." translate-attr="{title: 'id_2'}" title="a title">a link text</a>`

Filippo

**Comment by knalli** [comment]
OK: Feel free to add a PR covering this feature. Have a look at our contribution guideline for the required steps.

I'll close this here.
