### ISSUE TITLE
Translation in controller and service

### ISSUE THREAD

**Issue by MarcoDias7** [angular-translate/angular-translate#1623]
Hi, 

I'm using this plugin, and it works flawlessly in my views. I now want to translate some messages that I have in my controllers and services, but I don't know how to. I have my array of translations in app.js. I know how to do it in HTML with the {{ 'message_detail' | translate }} or 
```
<h2 translate="noMessage"></h2>
```
or even in a tag parameter, but in the Javascript files, no idea.

Can someone enlighten me ? Thanks

**Comment by tspaeth** [comment]
Have a look in the documentation - see https://angular-translate.github.io/docs/#/guide/03_using-translate-service

**Comment by MarcoDias7** [comment]
As I understood this, we use this to translate something directly in the controller, and pass it to the view with $scope.variable = translated value.

I'm not sure I get it, I couldn't make it work for my case.
In my controller I have some popups :
`var alertPopup = $ionicPopup.alert({
            title: "Erreur",
            template: data
        });`
And I want to translate the title there.

So, if I have an error field in my translations array, I should do :
`$translate('error').then(function (error) {
    $scope.error= error;
  }, function (translationId) {
    $scope.error= translationId;
  });`

and put $scope.error in Title field of my popup ?
I didn't understand the purpose of TranslationId, could someone explain ?

**Comment by tspaeth** [comment]
I don't know exactly about Ionic - components. 

Please ask "how do I..." questions on Stackoverflow: http://stackoverflow.com/questions/tagged/angular-translate - you'll reach a bigger audience. Also, the documentation at https://angular-translate.github.io is a good place to start looking for deeper knowledge on angular-translate.

This issue tracker is mainly the feature-/bugtracker for angular-translate. But you're always free to add a feature request later on if needed. 

Thanks.

**Comment by knalli** [comment]
In that case the ionic component is only a service also. Said that, the dialog can be given a template also (here: `data`) in which both translate's directive and filter work.

Case closed.

Please understand we cannot handle AngularJS basic here.
