### ISSUE TITLE
Store translations locally - trigger update from API - Mobile WebApp

### ISSUE THREAD

**Issue by Jay031** [angular-translate/angular-translate#1625]
I have a webserver containing translations i.e.
/api/en/translations will return a JSON string with all English translations

In my WebApp I already have 3 files, locale/en.json, locale/de.json, locale/nl.json
But I want to be able to overwrite these translation files so I can easily refresh translations from the server.
What's the best way to do this? Maybe I should use the localstorage instead?
And if so, how can I manually refresh the translations then? Because I want to check for an internet connection first.

Thanks in advance!

**Comment by tspaeth** [comment]
Please ask "how do I..." questions on Stackoverflow: http://stackoverflow.com/questions/tagged/angular-translate - you'll reach a bigger audience. 

This issue tracker is mainly the feature-/bugtracker for angular-translate. But you're always free to add a feature request later on. 

Thanks.

**Comment by Jay031** [comment]
I'm sorry I will do this! I should've known!
Thanks 👍
