### ISSUE TITLE
Angular-translate.useStorage(“customStorage”) is not working with Custom Storage

### ISSUE THREAD

**Issue by omairkhan** [angular-translate/angular-translate#1628]
### Angular-translate.useStorage(“customStorage”) is not working with Custom Storage

http://stackoverflow.com/questions/40214521/angular-translate-usestoragecustomstorage-is-not-working-with-custom-storage

I am new in angular-translate. I have implemented everything, but failed to implement customStorage for storing the state of angular-translate.

My configuration file:

```
var app = angular.module('app', ['ngRoute', 'ngToast', 'angularMoment', 'pascalprecht.translate', 'ngCookies'])
.config(['$translateProvider', function ($translateProvider) {
        // add translation table
        $translateProvider.fallbackLanguage('en');

        // remember language
        $translateProvider.useStorage('customStorage');

```

My customStorage service use localstorage is defined as below:

```
(function () {
    angular.module('app').service('customStorage', function () {

        return {
            put: function (name, value) {
                debugger
                if (typeof (Storage) !== "undefined") {
                    // Store
                    localStorage.setItem(name, value);

                } else {
                    "Sorry, your browser does not support Web Storage...";
                }
            },
            get: function (name) {
                debugger
                // Retrieve
                localStorage.getItem(name);
            }
        }
    })
});
```

I am getting the following error:

Error I am facing due to this above code.

I have included all the required files in the configuration in bundle.config file in ASP.NET MVC.

```
bundles.Add(new ScriptBundle("~/js/translation-plugins")

           .Include("~/node_modules/angular-cookies/angular-cookies.min.js")
           .Include("~/bower_components/angular-translate/angular-translate.min.js")
           .Include("~/bower_components/angular-translate-storage-cookie/angular-translate-storage-cookie.min.js")
           .Include("~/bower_components/angular-translate-storage-local/angular-translate-storage-local.min.js")
           .Include("~/bower_components/angular-translate-loader-static-files/angular-translate-loader-static-files.min.js")
           );
```
### ASP.NET MVC

*angular-translate - v2.12.1 - 2016-09-15 version of angular-translate
-  AngularJS v1.3.15 version of angular
- Firefox, 49.0.2
### Steps to reproduce

http://stackoverflow.com/questions/40214521/angular-translate-usestoragecustomstorage-is-not-working-with-custom-storage
### Expected behaviour

Whenever I refresh the page, it should fetch the language from custom storage. As useStorage is not working in my case properly. is it compatibility issue with angular version or translate version or anybody can help to identify my mistake? 
whenever I refresh the page, it throw error that 
Error: [$injector:unpr] Unknown provider: customStorageProvider <- customStorage <- $translate
http://errors.angularjs.org/1.3.15/$injector/unpr?p0=customStorageProvider%20customStorage%20%3C-%20%24translate
return new ErrorConstructor(message);

![a](https://cloud.githubusercontent.com/assets/2535661/19649484/678d7d46-9a1f-11e6-8ff3-33879399b66a.png)

here is the plunker example:
http://plnkr.co/edit/mJhwlmRdqQhvJBJv6sOo?p=preview

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by omairkhan** [comment]
I think If you see carefully i have given the plnker url in the
stackoverflow. please have a look in it. its really important for me to
resolve it.

جزاک اللہ خیراً
Rana Umair
Website <http://www.accordax.com> | Mob : 0092-3224201085

**Comment by knalli** [comment]
Sorry, don't see that. Your getter does not return the stored value.. :)

**Comment by knalli** [comment]
A getter must return the value, i.e. https://github.com/angular-translate/angular-translate/blob/2.13.0/src/service/storage-local.js#L35-L41

**Comment by omairkhan** [comment]
Thanks Jan. I am sorry to be rude little :)
but 👍

جزاک اللہ خیراً
Rana Umair
Website <http://www.accordax.com> | Mob : 0092-3224201085
