### ISSUE TITLE
table's data title not getting translated using conditional operator .

### ISSUE THREAD

**Issue by nishantk9870** [angular-translate/angular-translate#1629]
### Subject of the issue
unable to translate based on conditional operator .
```
data-title="{{(installedPillars.indexOf('LM') != -1 && installedPillars.indexOf('TM') == -1) ? 'JOB_MANAGER_FIELD_JOB_CODE' | translate : 'JOB_MANAGER_JOB_ID' | translate }}"
```
### Your environment
* version of angular-translate
* version of  angular 1.4.12
* all browsers 

### Expected behaviour
the values should get translated .
### Actual behaviour
Tell us what happens instead
No value gets displayed .

**Comment by tspaeth** [comment]
Why don't you write
```
{{(installedPillars.indexOf('LM') != -1 && installedPillars.indexOf('TM') == -1)?'JOB_MANAGER_FIELD_JOB_CODE':'JOB_MANAGER_JOB_ID' | translate }}
```
??

**Comment by knalli** [comment]
AngularJS expression fix provided, but not an issue with translate actually.

Case closed.
