### ISSUE TITLE
Is it possible to translate ui-bootstrap tooltips?

### ISSUE THREAD

**Issue by bcamp1973** [angular-translate/angular-translate#163]
I'm using ui-bootstrap on my project. I would like to translate tooltips...however, not sure how to accomplish it?

``` html
<a href="..." tooltip="TRANSLATE_THIS | translate">...</a>
```

**Comment by qnodesign** [comment]
tooltip-html-unsafe is deprecated and it is not working with tooltip-html. Any suggestions?

**Comment by uhtred** [comment]
Same problema as @qnodesign, any ideas?

**Comment by starf** [comment]
use uib-tooltip-html="'{{myVar | translate}}'"
do not forget the single quotes!

**Comment by soulesjms** [comment]
doesn't this work? 
`translate-attr="{tooltip : 'TRANSLATION_ID'}"`

**Comment by elbasityassine** [comment]
Is verry simple just add 

`<a href="..." [tooltip]="TRANSLATE_THIS | translate" container="body">...</a>`

**Comment by codestitch** [comment]
how about translating tooltips not via static string but by variable? like if you loop through a navigation. say:

`<ul *ngFor="let nav for navs">
<li>
  <a tooltip="{{ nav.translate | translate }}"></a>
</li>
</ul>
`

**Comment by LoyalPotato** [comment]
@starf Why are the single quotes needed?
