### ISSUE TITLE
Is there a way to populate $translationTable outside the config part

### ISSUE THREAD

**Issue by Vengefull** [angular-translate/angular-translate#1631]
Hello,
Is there a way to populate the $translationTable outside the config block of the application.
I want to be able to dynamically change the $translationTable's content.
The provided service $translateUrlLoader is only doing a simple http.get (which i could do by myself) but it doesn't populate the $translationTable

**Comment by knalli** [comment]
Either you configure the table right into the config phase, or you have to use the loader only responsible fetching the translations.

You can use a custom loader, you don't have to "load" data actually. It's just a function returning the data wrapped in a promise.

**Comment by Vengefull** [comment]
Getting the translations from a rest service and populating the $translationTable are 2 different things.
You are correct that the $translateUrlLoader is returning the data wrapped in a promise but this is not enough for the $translation to visualize the translations, since it is searching inside the $translationTable.
As i saw the only way to populate the translation is by using the $translateProvider.translations('lang',translations); at config phase where you are not allowed to use service/factory etc.  to fetch the translations => all users must hard code their translations ?

**Comment by knalli** [comment]
Why do you not use the loader only? You do not have to apply the translations on your own.

**Comment by Vengefull** [comment]
because the $translateUrlLoader is simply getting the translations wrapped in a promise - right ?
After that the $translate (service/filter) is searching the passed translation id/key/param in the $translationTable which is not populated by the loader.
example:
myTranslJson.json
{
```
 "first.translation":"This is my translation"
}

```
```
// this will not populate the $translationTable
$translateUrlLoader({
                                  url : "path_to_the_file/myTranslJson.json",
                                  key : "en-us"
                                });

```
When the $translation (service/filter) is called it will look inside the $translationtable = >
//code from the sources
```
for (var j = 0, d = possibleLangKeys.length; j < d; j++) {
          var possibleLangKey = possibleLangKeys[j];
         // next lines of code are passed because there is no $translationTable
          if ($translationTable[possibleLangKey]) {
            if (typeof $translationTable[possibleLangKey][translationId] !== 'undefined') {
              result = determineTranslationInstant(translationId, interpolateParams, interpolationId, uses);
            }
          }
          if (typeof result !== 'undefined') {
            break;
          }
        }
```

**Comment by tspaeth** [comment]
Hm. I don't get the issue. $translationTable will contain the async result as soon as it is available.

**Comment by knalli** [comment]
> ```
// this will not populate the $translationTable
$translateUrlLoader({
                                  url : "path_to_the_file/myTranslJson.json",
                                  key : "en-us"
                                });
```

*This* will not generate data into the table, that's right. But that is not how you have to use it. Neither this is documented like that.

**Comment by Vengefull** [comment]
knalli you are right about the documentation ->
 `$translateProvider.useUrlLoader('foo/bar.json');`
Yet this is a provider and i can not use it else were but in the config.
Also the $translateUrlLoader is a factory which i guess could be used as it is outside the provider ?
Even if i create a custom loader i still have to use it in the config phase, but unfortunately that is now what i want to achieve. 
The desired behavior for me is to dynamically load translations per page (in the resolve method of the routeProvider)

**Comment by knalli** [comment]
@Vengefull  You are not using the components like in the documentation and guide explained, so you are getting a wrong result also. Sorry, that's it up to you.

> Yet this is a provider and i can not use it else were but in the config.

Perhaps to rephrase this: You define a loader in the config phase, but the loader will not be invoked in the config phase, but at any time later (and again).

> Even if i create a custom loader i still have to use it in the config phase

Yes, and that is not an issue.

> The desired behavior for me is to dynamically load translations per page (in the resolve method of the routeProvider)

Aha! That simple piece of information you don't shared yet. You should have a look at the partial loader at https://angular-translate.github.io/docs/#/api/pascalprecht.translate.$translatePartialLoader

**Comment by Vengefull** [comment]
@knalli 
I will take a look at it. 
Thank for the quick responses and the information .

**Comment by Vengefull** [comment]
actually i have one more question,
$translatePartialLoader doesn't have service setPart() that i could use outside the config part.
Once again i am stuck at this config phase of the project.
The service addPart only sets the part name + priority

**Comment by tspaeth** [comment]
If you look at the documentation of https://angular-translate.github.io/docs/#/guide/12_asynchronous-loading and then think a bit further, what you do in the config section is:
- Define what loader to use (can be your completely own written one) 
- What file path / pattern to look for language files or resources

So if you need something special, why not define your own (partial) loader, tell angular-translate to use that and implement the "interface" methods it is seeking for with what you need / want. 

And yes, in some point in time in the configuration section you NEED to tell the core module how to look for translation(s) (tables). 

You call addPart from where you need whatever in the services / controllers - depending on your architecture. And if all the module currently provides as flexibility still not fulfills your requirement, maybe then - the architecture needs a review :-).

**Comment by Vengefull** [comment]
I will ignore the architecture thing.
So i did all the steps described in the documentation about the partial loader and how ppl could change the translations by this peace of code 
```
angular.module('contact')
.controller('ContactCtrl', function ($scope, $translatePartialLoader, $translate) {
  $translate.preferredLanguage('en');
  $translatePartialLoader.addPart('contact');
  $translate.refresh();
});
```
But after the first call to the server there is no second one after the code above.
The first call in the config phase is ok, the data is returned wrapped in a promise - everything looks ok.
But in the controller when i call `$translatePartialLoader.addPart('contact');` and the other things described in the documentation there is no second call to repopulate the translations for different part (create in the controller).
Is it normal? - if yes then this still stays a limitation in the config phase or i don't do it right ?
