### ISSUE TITLE
How to invalidate browser-cached translation JSON file?

### ISSUE THREAD

**Issue by mickyinba** [angular-translate/angular-translate#1632]
### Subject of the issue
I have released an application that uses static JSON files that contain translations. These work fine until I release another version of the application with more translation keys and values added to the JSON files.
I could not reproduce this in Plunker. I have seen, however, a screenshot of a page that previously had static content that was replaced by <any translate="KEY"></any>  syntax and in it the key literals were rendered and not the translated text. Clearing browser cache fixed this, but I can't expect all my users to clear cache each time I add more translations.
What cache-busting strategy to use here? If it were a normal script loaded in a <script> tag, I would simply add a querystring with a timestamp, but I can't do this with static .json files for angular-translate, can I ?

* Would renaming all of my files from names like "translation-en-AU.json" to names like "translation-20161026-en-AU.json" and also the prefix to: 

$translateProvider.useStaticFilesLoader (
{ 
  prefix: 'scripts/translations/translation-20161026-',
  suffix: '.json'
});
fix the issue? Is there a better way to invalidate cached JSON translation ?

### Your environment
* version of angular-translate: 2.12.1
* version of angular: 1.4.14
* which browser and its version: Safari 10 (iOS) on iPhone 6, but potentially any

### Steps to reproduce
* I could not reproduce this in Plunker as it reloads the page when the code changes. The cached JSON is used only when visiting the URL directly. Reloading page loads the file again. 

A html view had static content. I changed this content with <any translate="KEY"></any> placeholders and updated my .json files to include these keys and values.

An updated .json translation file was deployed along with the changed .html that implements these translations.

### Expected behaviour
After the release of the new application version, the updated JSON static files have to be used instead of the ones browser has cached.

### Actual behaviour
After the release of the new application version, the newly added substitution placeholders are displayed instead of their matching translations. It seems that the cached JSON files are used and not the updated static files.

**Comment by knalli** [comment]
The loaders except additional options which includes the possibility to apply `$http` option for the actual XHR.

**Comment by mickyinba** [comment]
Where is the documentation for this?

**Comment by knalli** [comment]
https://angular-translate.github.io/docs/#/api/pascalprecht.translate.$translateProvider (useLoader)

**Comment by knalli** [comment]
```js
$translateProvider.useLoader('anyloader', {$http: {}});
``

Documentation for `$http` is in the official AJS docs.

**Comment by knalli** [comment]
Also: https://angular-translate.github.io/docs/#/guide/13_custom-loaders (Additional options)

**Comment by tspaeth** [comment]
And if you want to prevent the browser in general to cache only the latest versions of "files" (including these JSON), have a look at the whole caching http headers like ETag etc. - but this is not an issue of our module here.
