### ISSUE TITLE
Incompatible with safari preview release 16 - returning [Object object] or "{"0":{},length:1}"

### ISSUE THREAD

**Issue by mitomm** [angular-translate/angular-translate#1634]
Hi guys,

I'm not sure if this is related to a browser bug or if Apple changed some things in their upcoming safari version that break angular-translate.

Today I installed the safari technology preview 16 and since then, I sometimes see `[Object object]`  or`{"0":{},length:1}`  instead of the translated value on my screen. If I reload the page, sometimes everything works fine and sometimes it shows `[Object object]` or `"{"0":{},length:1}"` again.

Note: Using Chrome or regular (non-review) Safari works totally fine and I have no issue at all.

Further notes:
- Using `translate="key"` results to`[Object object]`
- Using `{{'key' | translate}}` results to`{"0":{},length:1}`

Furthermore, it seems that the issue only occurs in Bootstrap modals that are asynchronously loaded as a directive.

Below are the official release notes regarding JS changes of Safari Preview 16. Maybe somebody familiar with the code sees an issue in those change at first glance:

> Implemented `Intl.getCanonicalLocales`
> Changed ES6 method functions to not have a `prototype` property
> Forbid `"use strict"` directive in generator functions with non-simple parameters
> Prevented `Array.prototype.concat` from modifying frozen objects
> Prevented `Array.prototype.slice` from modifying frozen objects
> Prevented `JSON.parse` from modifying frozen objects
> Handled non-function, non-undefined comparator in `Array.prototype.sort`

Let me know if I can provide further details

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by knalli** [comment]
I've Safari Tech Preview 16 also and I don't see an issue with the mentioned demo base.

**Comment by mitomm** [comment]
I'll see what I can do with the plunker if I find some more time (since I have to setup an async call to some server to load the bootstrap modal).

I guess you are not seeing any issues in the demo base because those translation tags are not inside a directive that is loaded at a later point in time. Regular translation on the initial page work fine for me too.

Also, I just noted that I don't see the issue on my server (only while testing locally). So I guess it wouldn't even work in a Plunker. 

Im really sorry for those unspecific descriptions and I'm quite aware that it is really hard to replicate. Maybe someone else simpler situation with the same issue.

**Comment by mitomm** [comment]
First of all, sorry for my late response.

I tried hours to replicate the issue in a plunker. But, it seems to always work fine there. 

However, I was still able to narrow down the issue to a more specific situation.

It seems that the issue is related to `.useSanitizeValueStrategy('escape')`. If I leave out that line in my code, everything works fine.

I also quickly looked into the angular translate code found that it has to be related to one of those lines:

`var htmlEscapeValue = function (value) {
  var element = angular.element('<div></div>');
  element.text(value); // not chainable, see #1044
  return element.html();
  };
`

Not sure if this is still related to #1044 or if somebody else has an idea on what the issue might be related to?

I guess it's rather expected, but still I'll point out that if I modify the above code to: 

`var htmlEscapeValue = function (value) {
  return value;
  };
`

everything works fine.

I'm really sorry that I still can't provide a minimal test case in a plunker (since the bug doesn't seem to occur there. For reasons beyond my understanding).

If I can provide further details, please let me know.

**Comment by mitomm** [comment]
Btw, not sure if it helps but replacing those three lines with the same jquery counter parts produces the same results for me.

```
var htmlEscapeValue = function (value) {
  var element =   $('<div></div>');
  element.text(value);
  return element.html();
};
```

**Comment by mitomm** [comment]
All issues are gone in the new Preview version 19. So I guess it was a safari bug.
