### ISSUE TITLE
setTranslateNamespace

### ISSUE THREAD

**Issue by fmunafokion** [angular-translate/angular-translate#1635]
Hi,
having a look at source code, I've found a directive, `translate-namespace`, that is the perfect companion of "namespaces", "part" and "keepContent".

Now I can use a json like this:

```
{
  "Page1": {
    "10": "text",
    "20": "another text",
    "22": "a longer text with some more words",
    "25": "and son on"
  }
}
```

Use addPart to load a different json for each page, on `$routeChangeSuccess`:
`$translatePartialLoader.addPart(pageCode);`

Use keepContent to show default text inside element instead of the id:
`$translatePartialLoader.keepContent(true)`

and have page views like so, without repeat namespace string (pageCode) for every translate:
```
<div translate-namespace="Page1">
   <p translate=".10">some default text</p>
.....
</div>
```

How about add a new method, `setTranslateNamespace`, in order to change namespace on need?
By this way, it could be possibile to add a call to `setTranslateNameSpace` on each `$routeChangeSuccess`, as we just did with addPart.

Thanks,
Filippo

**Comment by knalli** [comment]
It does not make sense setting the namespace globally on the service. This would be a state which cannot and should not shared with all others (like filter, directive).

The namespace is particular useful only in context of a directive and its usage within hierarchic/contextual tag structure.

**Comment by fmunafokion** [comment]
You are right, "it does not make sense setting the namespace globally on the service", without changing it when needed.
What if each page has a different namespace, each page one and only one namespace? Or, module speaking, what if each module has only one page? A developer should add the directive, `translate-namespace`, on each page. Adding `setTranslateNamespace` is the only way to avoid this boilerplate code in each page.
Furthermore, the same applies using modules with more than one page, the standard way. It could be possibile to automate namespace changes, intercepting navigation between modules, without adding the directive on each page of module.

Filippo
