### ISSUE TITLE
Angular directive attributes get removed from translate-values

### ISSUE THREAD

**Issue by keeprock** [angular-translate/angular-translate#1641]
Hi! I'm using Angular translate 2.12. I've got a link similar to this:

```Html
<p class="board-helper__txt"
                   translate
                   translate-compile
                   translate-values="{
                        tasksLink: '<a ui-sref=&quot;^.tasks&quot; class=&quot;btn-link tasks-link&quot;>tasks</a>',
                        risksLink: '<a ui-sref=&quot;^.risks&quot; class=&quot;btn-link rs&quot;>risks</a>'
                   }"
                >objectives_help-2_content-1</p>
```

Issue is this gets compiled into a link without **ui-sref** directive.

```Html
<a class="btn-link tasks-link ng-scope">tasks</a>
```
What am I doing wrong with it? Thanks!

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by knalli** [comment]
Maybe a sanitize strategy chosen which removes html off values?

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
