### ISSUE TITLE
Can't use angular-translate-interpolation-messageformat with npm in browser

### ISSUE THREAD

**Issue by laurentperroteau** [angular-translate/angular-translate#1644]
The package actual [angular-translate-interpolation-messageformat](https://github.com/angular-translate/bower-angular-translate-interpolation-messageformat/blob/master/package.json) can't be used in browser with npm (instead of bower) because it uses an old version of [messageformat](https://github.com/messageformat/messageformat.js/releases) (0.3.1).

Since version 1.0.0, **messageformat** can be use with npm in browser.

Thanks

**Comment by knalli** [comment]
I'll close this being duplicate. See more at #1661
