### ISSUE TITLE
Incorrect value of 'params' in static loader request

### ISSUE THREAD

**Issue by zgmnkv** [angular-translate/angular-translate#1646]
According to angular docs 'params' should be a map, not string
https://docs.angularjs.org/api/ng/service/$http#usage

https://github.com/angular-translate/angular-translate/blob/132e49a62053491ae661f1796d8a509f7d902482/src/service/loader-static-files.js#L52

**Comment by tspaeth** [comment]
Thanks for the report. You're right. But gladly, until now it didn't cause any issues so far :smile:

**Comment by zgmnkv** [comment]
In my case I added an http interceptor and expected params to be always an object.

**Comment by knalli** [comment]
Yes, we should fix this. Do you want to provide a patch? Either we replace it with `{}` or remove it completely. Cannot say here what is better, should have a look into it.
