### ISSUE TITLE
StaticFilesLoader not loading the strings on first pageload 

### ISSUE THREAD

**Issue by rkg823** [angular-translate/angular-translate#1649]
StaticFilesLoader not loading the strings on first pageload. Strings are coming after page refresh.

below is my code - 
angular
        .module("app")
        .config(function config($translateProvider){
        $translateProvider.useStaticFilesLoader({
            prefix: "/app/resources/locale-",
            suffix: ".json"
        });
        $translateProvider.preferredLanguage("en_US");
        $translateProvider.useSanitizeValueStrategy("escape");     
    });

environment
*  angular-translate - v2.9.0 
*  vangular-translate-loader-static-files - v2.13
*  angular - v1.5.8
*  Chrome

**Comment by tspaeth** [comment]
a) never mix versions of a loader and a base of our module. Always take the same versions.

b) Have a look at the demo https://plnkr.co/edit/NO9oIqtnWWsVMMuIXa6Y  -- I don't get any issues. So what is the problem?

**Comment by erperejildo** [comment]
I've got the same problem. Running it with Meteor.

I'm running both packages:
```
import Translate from 'angular-translate';
import TranslateJSONs from 'angular-translate-loader-static-files';
```
And this is my .config:
```
.config(function ($translateProvider) {
        'ngInject';

        $translateProvider.useStaticFilesLoader({
            prefix: 'locale-',
            suffix: '.json'
        });
        $translateProvider.preferredLanguage('es');
    })
```
I've got a `locale-es.json` and a `locale-en.json`.

The normal angular-translate works as expected with no extra-package.
I have no errors.

Am I doing something wrong?

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by erperejildo** [comment]
Hi @knalli 

The point is, I'm using Meteor, which is the only difference and I can't change the plnkr. I'll change later my code to do exactly the same (I'm at work now).

Do I need ngSanitize? I think I had a warning related with that. Could be a reason?

Cheers

**Comment by knalli** [comment]
ngSanitize is used for better escaping strings.

**Comment by erperejildo** [comment]
The plnkr works as expected

**Comment by erperejildo** [comment]
I found this package as well for Meteor:
planettraining:angular-translate-loader-static-files
But I don't know what is the name of the package to import it

**Comment by erperejildo** [comment]
https://cloud.githubusercontent.com/assets/5629919/22224394/669beec0-e1b6-11e6-9519-2e672aecda47.jpg

**Comment by knalli** [comment]
We don't support meteor as a dedicated plugin. You will also see the plugin you mentioned have another scope (planettraining).

We had already an issue about this (#1259) and I don't see we have to publish a specific plugin.

Said this, angular-translate is just like AngularJS a browser-targeted framework and therefor will be debuggable easily. Everything you do in your meteor app is possible without (speaking of AngularJS, not specific integrations/features).

**Comment by erperejildo** [comment]
Ok fair enough. I'll try to figure out what's going on here:
https://github.com/planet-training/meteor-angular-translate/issues/4#event-934029270

If we find a fix I'll publish it here anyway.

Thanks

**Comment by erperejildo** [comment]
Fixed:
https://github.com/planet-training/meteor-angular-translate/issues/4#issuecomment-274867409
