### ISSUE TITLE
Multiple angular-local.xxx or dynamically loading ?

### ISSUE THREAD

**Issue by ianjohnspain** [angular-translate/angular-translate#1653]
Hi,

I am using angular-translate and as far as I am aware I can only include 1 angular-locale script tag, actually I am using webpack to import (require), but as far as I am aware, its only possible to use 1 angular-locale at a time.

Does angular translate offer some kind of way of dynamically loading this files ? So when I change the language that it would automatically include the locale file.

I was hoping to use the inbuilt angular filters like 'numeric', 'currency' but it using the correct locale.

**Comment by ianjohnspain** [comment]
This is the package I am currently using https://www.npmjs.com/package/angular-i18n

**Comment by knalli** [comment]
angular-translate is only for translation, but not localization.

You are looking for https://github.com/lgalfaso/angular-dynamic-locale or something else.
