### ISSUE TITLE
Make it easer to use setIntlSupport

### ISSUE THREAD

**Issue by timmipetit** [angular-translate/angular-translate#1655]
We were trying to use the Intl Formatters from messageformat.js, but had troubles getting it working in angular-translate. In order to use the Intl Formatters, you need to do this call: `mf.setIntlSupport(true);`

After reading the source, we found out that it was possible to achieve this using this code:
```
$translateMessageFormatInterpolationProvider.messageFormatConfigurer(function(mf) {
    mf.setIntlSupport(true);
});
```

This may require a Polyfill, so I understand why it's no on by default. Would it be an idea to add this option to the docs? If not, this issue servers as a future reference for others with the same problem :)

**Comment by knalli** [comment]
What are you missing? This here https://angular-translate.github.io/docs/#/api/pascalprecht.translate.$translateMessageFormatInterpolationProvider ?

**Comment by timmipetit** [comment]
Ah indeed. I guess I expected something about this option on this page: https://angular-translate.github.io/docs/#/guide/14_pluralization

**Comment by knalli** [comment]
Well, the guide is not a replacement for the API docs.

Because I'm not a messageformat user: If you think this is worthy to add, you are welcome extending the guide (PR). :)
