### ISSUE TITLE
Find out if fallbackLanguage was used in $translate

### ISSUE THREAD

**Issue by sodac** [angular-translate/angular-translate#1656]
Hi angular translate Team,

thanks for your awesome work it's really incredible, it solves every translation problem on my current Project -so far.

By the way is there some way to donate a little money for your efforts?

### Find out if fallbackLanguage was used in $translate

I need to find out if a translation was made with the active language or using a fallback.
My best bet so far is the custom Error Handler, since at least the missing translation logger seems to log missing translation based on each language. Is this the right way to go or is there some better approach?

### Your environment
* version of angular-translate
v 2.13.0
* version of angular
v 1.5.8 
* which browser and its version
chrome 54.0.2840.71

### Steps to reproduce
Really no steps to reproduce.

### Expected behaviour
Concept of how to find out if fallbackLanguage was involved in the translation.

### Actual behaviour
Just fine, but can't find out where the translation is from. (If a fallback Language was involved)

**Comment by tspaeth** [comment]
Maybe the last part "Using Post processing functionality" can help you here in combination with a "uses" call to determine current language and fallback etc. - see  https://angular-translate.github.io/docs/#/guide/16_error-handling

**Comment by sodac** [comment]
thanks a lot, i'm going to look into it and post the results

**Comment by sodac** [comment]
Ok, thanks a lot! This is what worked for me:
During the post Processing i add a specific string containing the language, like "###en-us" to the translation.
Later, when i receive the translation i split the received translation at the ###, seperate the translation from the language, and check if the language from the translation is the same as the active language.

Maybe not the best way but it works.

Thanks a lot for guiding me to the post processing functionality!
