### ISSUE TITLE
Using namespaces issue

### ISSUE THREAD

**Issue by IliyaF** [angular-translate/angular-translate#1658]
### Subject of the issue
I"m using the translate-namespace directive to define the desired namespace, and next the translate directive on the element with the actual key for translation(which resolves after binding). The problem is that if the key is not in the translations file, the prefix is appended to the resolved value ( which is not in the translation file).

Code example: 
```
<div translate-namespace="annotation"><span  translate>{{'.'  + someScopeObject.name}} </span></div>
```
Translation file:
```
{  
  "annotation": { 
    "chrom" : "chromosome",
    "adp": "read depth"
  }
}
```
### Your environment
* Angular-Translate version 2.13.0
* Angular version 1.5.5
* Chrome  54.0.2840.99

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://plnkr.co/edit/XorWgI?p=preview) as a base.

### behaviour behaviour
Let assume that the value of someScopeObject.name is "position". I would expect that in case that this key is not in the translation file, the result will be "position"

### Actual behaviour
Instead the actual result is "annotation.postion"

**Comment by tspaeth** [comment]
Could you please fill out all fields in the ticket form (expected behaviour etc.) and then as well, provide a working demo? thanks. 
I'm not getting it 100%...

**Comment by IliyaF** [comment]
Sure. I have updated the issue. Thanks

**Comment by IliyaF** [comment]
I managed to solve this using translate-default directive.
 Thanks
