### ISSUE TITLE
Ascii character 160 showing as &nbsp;

### ISSUE THREAD

**Issue by Syco54645** [angular-translate/angular-translate#1662]
### Description
Our translation service is inserting ascii character 160 before punctuation marks for french translations. This is rendering as `&nbsp;` in the output. We are not binding the html on these elements (and doing so would be quite bad in some cases) so is there a way that we can avoid this without using bind-html?

**Comment by tspaeth** [comment]
Have you read about the security / escaping on https://angular-translate.github.io/docs/#/guide/19_security ? And maybe you should provide a complete example so we can see what goes wrong.

**Comment by Syco54645** [comment]
So a few of the problem translations are
`
"Est:" : "Est :",
"Estimate: High to Low" : "Estimation : élevée à plus faible",
"Estimate: Low to High" : "Estimation : faible à pus élevée"
`
between "Est" and ":" and "Estimation" and ":" there is an ascii character 160 and that is showing as &nbsp; I have tried a.. of the various sanitation methods with no change. We are currently using the escape strategy as the docs note that there is a bug with the sanitize mode.

**Comment by tspaeth** [comment]
A complete example would be some plnkr according to the guidelines for issue filing. But anyway - I don't see an issue here. Look: https://plnkr.co/edit/TJm0BT?p=preview

**Comment by Syco54645** [comment]
Sorry about that. Your example has shown what the issue was and I now have it sorted out. Thanks! In short I am now using escapeParamters sanitation service.
