### ISSUE TITLE
Show all translations with translatePartialLoader

### ISSUE THREAD

**Issue by onepunchagency** [angular-translate/angular-translate#1668]
Hi, I have the following issue.

I would like to create a dynamic translatable navigation.
This navigation will be used in combination with NG-REPEAT.

For example:

```// File: menu/en.json
"MENU": {
      "HOME": {
        "TITLE": "Home",
        "ICON": "assets/img/home-icon-en.png"
      },
      "ABOUT": {
        "TITLE": "About",
        "ICON": "assets/img/about-icon-en.png"
      },
      "CONTACT": {
        "TITLE": "Contact",
        "ICON": "assets/img/contact-icon-en.png"
      }
    }
```

How can I iterate this menu with NG-REPEAT?

PS: I have found some solutions, but they were not applicable for my case. ( nested structure )

Example:
```
$translatePartialLoader.addPart('menu');
$translate.refresh();

$translate('MENU.HOME.TITLE')
        .then(function (translation) {
            console.log(translation);
});
```

What I need is to log the "MENU" and be able to see the fully nested structure and be able to use this in my HTML ng-repeat.

What I would like to have, but this is not the right way.
```
$translate('MENU')
        .then(function (translation) {
            console.log(translation);
// See the full nested menu structure
});
```

Ideally I would like to have the following:

```
$translatePartialLoader.getPart('menu');
// This would show me the full nested structure of the menu
```

Alternatively if this is not possible, is it possible to show all translations loaded with the partial loader? ( in a controller )

I have been struggling with this for almost 4-5 days, any help would be much appreciated and sincere thanks!

**Comment by knalli** [comment]
Hi @onepunchagency  Sorry for the delay, we have missed this issue.

angular-translate is not made for providing configuration or structure logic. Said this, it will provide texts for texts (maybe interpolated, maybe in another language). It will not provide information like "how many texts should be displayed".

The focus of this library is translating only.
