### ISSUE TITLE
Translate Cloak being removed too early causing FOUC

### ISSUE THREAD

**Issue by Beastw00d** [angular-translate/angular-translate#1669]
### Subject of the issue
I am doing my translations async and I've gotten rid of all the flickering switching between views (using ui-router). The only flickering I have left is when I do a hard refresh (initializing angular SPA). I have a translate-cloak around the view but it is getting removed too early. I am specifying a key value with the translate-cloak.

### Your environment
* version of angular-translate - 2.9
* version of angular - 1.5
* which browser and its version - doesn't matter

### Steps to reproduce
Check out this sample: https://plnkr.co/edit/mhetJhLIVdCOckpZTuBp?p=preview

You will notice the tabs display the translation key for a split second. I think I have narrowed it down to the call:

`$translateProvider.fallbackLanguage("en")`

I think it is causing the $translate.onReady() call to be fired before the translation for the keys are ready. 

### Expected behaviour
There should be no FOUC

### Actual behaviour
There is FOUC.

**Comment by knalli** [comment]
@Beastw00d  You are using angular-translate 2.9, that's outdated :)

We have fixed this months ago; fast-replacing with 2.13.1 removed the issue in the demo. Ok?

**Comment by Beastw00d** [comment]
That does fix the issue. I should have checked that first. @knalli thanks for the quick response.
