### ISSUE TITLE
escapeParameters escapes null to "null" or to ""

### ISSUE THREAD

**Issue by jnizet** [angular-translate/angular-translate#1670]
### Subject of the issue
The escapeParameters sanitization strategy escapes `null` to `""` (in the following plunkr), or to `"null"` (in my environment, where jQuery is used). This causes problems, because I use a filter in the translation, and this filter is checking for null, and doing something if null, and something else if not null.

I went back to the null strategy instead to circumvent the issue.

Note that I also realized, when debugging this, that escapeParameters escapes the values recursively, which means that if I pass a huge object as translate-values, even though I'm only interested in one of the properties of this huge object in the translation, this causes serious performance issues. This, I think, should be explained in the documentation (sorry if it is and if I missed it)

### Your environment
* version of angular-translate: 2.13.1
* version of angular: 1.4.6 (yes, I know I should upgrade, this is planned)
* which browser and its version: Chrome 55.0.2883.95 (64-bit)

### Steps to reproduce
See this plunkr: https://plnkr.co/edit/Ikiu4wmyzCDURVb87wQF?p=preview. It should display "France" in the h1, but doesn't display anything (it displays "null" in my environment, most probably due to the usage of jQuery in addition to angular). Set the sanitization strategy to null instead of 'escapeParameters', and France appears.

### Expected behaviour
The sanitization should leave null as null.

### Actual behaviour
The sanitization transforms null to something else.

**Comment by knalli** [comment]
>  if I pass a huge object as translate-values, even though I'm only interested in one of the properties of this huge object in the translation, this causes serious performance issues.

Well: Without knowing which values are used (using `translate-values`), we have to escape everything for that specific strategy.

Regarding the demo: Is there something missing? It's a blank/white page.

**Comment by jnizet** [comment]
I don't disagree with escaping everything. I just think a big red warning should be in the documentation about that, because it can have a significant performance impact on performance, that doesn't exist with the null strategy.

Regarding the demo, no, nothing is missing. The point of the demo is to show that instead of showing "France" in the `<h1>` as it should (and as it does if you use the null strategy rather than the escapeParameters strategy), it shows nothing, because the strategy replaces the null value of the `localName` field by an empty string.

**Comment by knalli** [comment]
Right, got it. Misunderstanding.

angular-translate does not support filter support within the key expressions. In case of such a expression logic, you have to build your own filter (which you have already) and using `$translate.instant(key)`.

**Comment by knalli** [comment]
Well, not clear enough: It is working without `escapeParameters` being enabled. But that's the thing: That's is (perhaps) unsecure.

**Comment by jnizet** [comment]
Great. Thanks @knalli. Keep up the great work!
