### ISSUE TITLE
Masterplan 2017

### ISSUE THREAD

**Issue by knalli** [angular-translate/angular-translate#1671]
Happy new year!

Unfortunately, I will kick of directly: The situation of this project has not changed in the last months, well, years.

![giphy](https://cloud.githubusercontent.com/assets/65389/21582224/68ec4ae4-d04f-11e6-877d-7e95015e2525.gif)

* Not much time for this project
* Too many feature requests (mostly w/o work of thirds, but also "only with maintenance" work for us).
* A lot of standard support issues about either AngularJS basics or even JavaScript development (JavaScript basics, understanding of bower, and so on) issues.
* Still lacking catch up for Angular 2 at any idea. Yes, there is still #995...
* The translated guides are not equal and there is no strategy for refreshing them according to a release side by side.

Please do not get the understanding there was nothing; in the last year we had

* [10 releases](https://github.com/angular-translate/angular-translate/releases) (without patches 5)
* more then (roughly) 150 commits, a lot of contributed by external helpers

Summarizing the situation: While I'm happy the project is still alive and producing ideas and releases, I'm not satisfied with this at all, more effort is really required but not available. This is not a new situation, actually, I'm thinking about writing this one here for a year now.

----
I'd already started and marked several feature requests as well as pull requests for [Contribution Welcome](https://github.com/angular-translate/angular-translate/issues?q=is%3Aopen+is%3Aissue+label%3A%22Contribution+Welcome%22). Even for high candidates like AngularJS 1.6 support or the long standing UTF/sanitization issue, there is also a lack of community contributions. This projects relies on that, but unfortunately, it is not. There are features which have worked great (like integration of published npm packages) and many, many details.. but it is not enough. 

Let's simplify it: The pressure of creating and closing issues is not "efficient" (find another work for efficient, I'm still looking for it..).

There is **no plan to stop the project at all**, but we have to reconsider topics and cutting things away.

My suggestions so far:

* Reconsider each feature request:
  * if the feature is a plugin/api extension allow more: probably stay/open
  * if the feature would be already possible with 3rd party work: probably close
  * otherwise: [Close it, we have no interest.](http://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes)
* replay the same with other things: bugs, docs (details required)
* Introduce an explicit standard policy (=> affects docs homepage, Readme.md, issue template) stating we do not support non related angular-translate issue. We will close them asap (with help hints to stackoverflow, angular docs, our docs, maybe mdn as well).
* Closing issues without any change in the last time x (current: 91 open, 21 no change last year, 43 no change within last 6 months)
* Remove all guide translations except English. Well, that will heartbreaking somehow, but otherwise I cannot see how we can manage either a working/updated guide (How do you know which release is compatible with a given translated guide text?, Can I replace the standard English with a better text and layout? What about the others? What happens?) and a best standard guide text. Alternatives are welcome!

cc @angular-translate/members 

I highly await replies from everyone. Not only from out team members, but also users what there think.

**Comment by DWand** [comment]
Hi, @knalli. I'm glad to see that this project is alive. Unfortunately, I still have pretty high pressure with work and cannot spend time on Open Source :-( Hopefully, some day I'll have an opportunity to work with you, @tspaeth and @PascalPrecht again. That is a pretty valuable experience.

**Comment by tspaeth** [comment]
Hi!
I agree with you in most points, and even a bit more realistic, I see that maintaining only one language on the "guide" is the only solution to have a good documentation attached to the most current release. Maybe, we should introduce a "this documentation was made for V ..." stamp on the pages, so whenever someone out of the community updates the documentation to be in line, I'm happy with that.
The point on support is a major one, and I still think, it/we should or must be more straight forward to forward "how can I" - threads to StackOverflow or wherever, while reducing the support amount here.

Regarding the feature and compatibility improvements - and this is the most crucial part - I personally would still try to reach out to the community and the i18n streams of the core team, so we see, what is already core-planned as the plans changed a lot the last 2yrs there as well. It could be an approach to rewrite this module in TypeScript or make it Angular2 compatible as a smaller step, but it must be worth while.
Currently, I'm still having a time shortage for everything besides business and family but will keep up supporting and fixing here with you 👍 
And if we have an idea, where to go with *useful* radical refactoring (means to me: driven by projects / community), we should go there if we can effort this (means, mostly us two).
From my business projects perspective, currently there is no feature driver in the background, so it'll all be volunteer work for me.

I'm asking myself something like: "Did we reach feature completeness already and the pending requests are more cosmetic and project specific requirements by the users?". We could do a Skype call or similar to walk through the list and then refine it...

**Comment by knalli** [comment]
Thank you both.
Perhaps others will add some input also.

My current plan is to prepare end of months a list of points (mainly extract of the posts above).

**Comment by twwwt** [comment]
Hi
I agree with putting focus on the important things. From my point of view, this is currently support for Angular 1.6. Second, fixing security-related issues. I think it is not that important to agree on an accepted strategy on how to handle the rest (feature requests, bugs, pull requests). Just *do* what you believe is necessary.

Thanks for all your work that went into this project!

**Comment by knalli** [comment]
Thank you for your input. The issue was 5 weeks open, that should be fine.

I'll start the next days and will mark open issues with the label [_2017_WillBeRejected](https://github.com/angular-translate/angular-translate/labels/_2017_WillBeRejected). The next release will be a regular one (still having the AJS 1.6 issue open), but *then* I will start cutting things away: The list is identical with the list in my first posting here:

0. Outdated/Old/Not-in-focus-anymore issues will be collected under the label [_2017_WillBeRejected](https://github.com/angular-translate/angular-translate/labels/_2017_WillBeRejected).
1. The list's issues will be closed with a nice message linking to this issue.
2. Integrating new policy about support, help: Readme.md, Docs/Guide-Homepage. Readme.md will refresh NPM page also directly.
3. Removing all languages except english from the guide, moving the generated files into a dedicated place for browsing only. Maybe with a big flash header about its outdated state.

**Comment by knalli** [comment]
Note: I have labeled a first bunch of issues with the label.

**Comment by knalli** [comment]
Ok, that is my text for the issue closing step: https://gist.github.com/knalli/acc2dfbfd6ad3a3f358ad9d6ba64ca4f Any comments or remarks?

**Comment by knalli** [comment]
Also, redesign README.md started: https://github.com/angular-translate/angular-translate/blob/feature/landing_care_support/README.md

**Comment by jakefreeberg** [comment]
Thank you for managing the project and communicating it's status. I now understand that I may need to dig a bit harder and contribute to solutions for problems in this repo. I will pass this information on to other developers within my company who are using this codebase.

**Comment by knalli** [comment]
* Redesign readme part of the 2.15.0 update released right now.
* Will starting closing rejected issues...

**Comment by knalli** [comment]
Case closed. :octocat:
