### ISSUE TITLE
translate not working when its loaded in slow internet connection

### ISSUE THREAD

**Issue by prabhjotkaur10** [angular-translate/angular-translate#1675]
I am using $translateProvider.preferredLanguage('en'); in my app.js, but in regular 3g or slow internet connection the file corresponding to it gets loaded but changes do not get reflected on the page. I am using this async loader directive 

//this factory is used to fetch the language file according to selected language for translation
```
app.factory('asyncLoader', function($q, $timeout, $http, envService){
  return function(options) {
  var deferred = $q.defer(), translations;
  var pathUrl = envService.read('lang_file_path');

  var resturl = pathUrl + 'language-' + options.key + '.json';
  $http.get(
    resturl,{cache:true}).success(function(translations) {
      deferred.resolve(translations);
      }).error(function(translations) {
        deferred.reject(translations);
      });
    $timeout(function() {
        deferred.resolve(translations);
      }, 2000);

      return deferred.promise;
    };
});
```
Setting done in app.js
//language settings
  $translateProvider.preferredLanguage('en');
  $translateProvider.useLoader('asyncLoader');
  $translateProvider.useSanitizeValueStrategy('sanitizeParameters');

**Comment by tspaeth** [comment]
Hi! 

To help out - can you setup a short Plunker (plnkr.co) so we have a running example to take a look on?
Otherwise, if you need more help on a "how do I" basis, please try asking this question on StackOverflow - you'll reach a broader audience there.

Thanks.

**Comment by prabhjotkaur10** [comment]
yep sure...
Thanks.

**Comment by LennyLip** [comment]
+1 

Got
"Could not translate angular Please check your Angular-Translate $translateProvider configuration"

sometimes for first time after reset cache

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by knalli** [comment]
Friendly reminder.
