### ISSUE TITLE
Implementing translations in dependencies

### ISSUE THREAD

**Issue by PawelDecowski** [angular-translate/angular-translate#1677]
Hi. This is not an issue per se, but I wasn’t sure where else to ask.

I maintain an Angular module which provides a calendar directive. Basically, it’s a dependency rather than a standalone product. I’m wondering what’s the best way to implement translations.

I can think of two options:

1. Make Angular Translate a dependency of my module and use translations as normal. The downside is if someone doesn’t use translations for their project, Angular Translate is imported technically for no reason (other than my calendar directive using it).
2. Let users of my module inject already translated strings. I think this is viable when there are very few translations (like in this case: only days of the week need translating). On the other hand, it doesn’t seem very clean.

I’m wondering if there is another, better way of handling it?

And if not, what do you think about my two suggestions?

Thanks!

**Comment by tspaeth** [comment]
Please ask "how do I..." questions on Stackoverflow: http://stackoverflow.com/questions/tagged/angular-translate - you'll reach a bigger audience. 

This issue tracker is mainly the feature-/bugtracker for angular-translate. But you're always free to add a feature request later on. 

Thanks.

**Comment by PawelDecowski** [comment]
@tspaeth How it wasn’t my first place to ask the question is beyond me. Thanks!

**Comment by PawelDecowski** [comment]
For reference: http://stackoverflow.com/questions/41773278/how-to-implement-angular-translations-in-dependencies
