### ISSUE TITLE
Change request headers in order to read non standard Unicode languages when use staticFilesLoader

### ISSUE THREAD

**Issue by sashberd** [angular-translate/angular-translate#1678]
angular-translate version 2.13.1

I`m trying to create select language box and change display language according to user choice. However, with some languages there are problems with Unicode reading when I used staticFilesLoader. E.g. with Russian it provides next result:

![image](https://cloud.githubusercontent.com/assets/11975561/22180779/bf8fa1fa-e082-11e6-805e-4eb7cc8da1a7.png)

where the initial file looks like: 

![image](https://cloud.githubusercontent.com/assets/11975561/22180816/f9adcce4-e083-11e6-8a58-1400aabe8f05.png)

The file was created under UTF-8 encoding and translates were taken from google translate service. I`d tried to change the encoding of the text to many others but no result.
The solution could be to change contentType of request that sent form angular-translate (e.g. to Content-Type: text/plain;charset=iso-8859-1), but I did not found and way to do such changes.

Is there is a way to fix such problem?

**Comment by knalli** [comment]
This is an issue with your webserver, not angular-translate running only in the browser/client. If you cannot change the setting, you should convert the translations into the matching encoding.
