### ISSUE TITLE
Translations won't be loaded into template files when using dragend JS

### ISSUE THREAD

**Issue by peterwesterlund** [angular-translate/angular-translate#1683]
### Subject of the issue
Translations won't be loaded into template files when using [dragend JS](https://github.com/Stereobit/dragend). I have debugged a lot and concluded that it has to do with the dragend JS declaration. The translations appears when i comment away the `dragend()`, bot won't appear when I uncomment it and reload the page.

The template files are appearing with it's HTML correctly. And dragend JS is doing it's job with fixing the slides. It's just that they don't get the translations into it.

The translations for header and footer works though.

### Environment
* angular-translate - v2.9.0 - 2016-01-24
* AngularJS v1.6.1
* Google Chrome Version 55.0.2883.95 (64-bit)

### The code
Here is the javascript:

```javascript
var myApp = angular.module('MyApp', ["ngRoute", 'pascalprecht.translate']);

myApp.config(["$routeProvider", '$translateProvider', function($routeProvider, $translateProvider)
{
    $routeProvider
    .when("/", {
        templateUrl : "home.html"
        ,controller:"StageController"
    })
    .when("/about", {
        templateUrl : "about.html"
        ,controller:"StageController"
    });

    $translateProvider.useStaticFilesLoader({
        prefix: 'lang/locale-',
        suffix: '.json'
    });
    $translateProvider.preferredLanguage('sv');

}]);

myApp.controller('StageController', ['$scope', '$translate', function($scope, $translate) 
{
  $scope.changeLanguage = function (langKey)
  {
    $translate.use(langKey);
  };

  $scope.$on('$viewContentLoaded', function()
  {
    // Translations for templates won't load when using this:
    $(".ui-content").find(".dragend-pages").dragend();
  });

}]);
```

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by peterwesterlund** [comment]
All right, finally, here is the demo:

https://plnkr.co/edit/5G3jJxF3DSfClzfopGEg?p=preview

**Comment by peterwesterlund** [comment]
Okay I changed to [revolunet / angular-carousel](https://github.com/revolunet/angular-carousel) instead. But having problem with the nested carousels. They won't appear. And after som debugging I found that they doesn't when coming from inside a translation string. There's still problem with the touch swipe functionality even testing outside translation string. But one problem at a time. So, how do I get the carousel from translation string to be built?

**Comment by knalli** [comment]
Sorry, but please build a demo with the code/feature/bug in question only.

**Comment by knalli** [comment]
Is this still an issue? 1. We need more information, 2. (noted) this is not the current version.

**Comment by peterwesterlund** [comment]
No, you can close this. I changed to another slider.

**Comment by knalli** [comment]
Alright, thank you.
