### ISSUE TITLE
translate-attr having problems with dashes in the attribute name aria-label becomes aria_label

### ISSUE THREAD

**Issue by adofito** [angular-translate/angular-translate#1684]
### Subject of the issue
Hi,
I am using something like this

translate-attr="{ARIA_LABEL:'Products.Create_Product.Delete'}"

and while inspectig it has created and attribute like this:

aria_label = "Borrar Producto"

instead of

aria-label = "Borrar Producto"

I just updated to angular-translate v. 2.13.1 and the problem is stil there

### Your environment
* 2.13.1
* 1.5.6
* Chrome Version 55.0.2883.95 (64-bit) / Mac OS

### Steps to reproduce
I have a button like this:
<button class="bytemark-text-button"
        ng-click="undelete($event,id)"

        translate-attr="{ARIA_LABEL:'Products.Create_Product.Undelete'}"
        translate="Products.Create_Product.Undo"
        ng-if="id.deleted">
  UNDO
</button>

### Expected behaviour
It should translate the aria label and it does but with the wrong attribute name
aria-label = "Deshacer"

### Actual behaviour
aria_label = "Deshacer" // underscore instead of dash

**Comment by knalli** [comment]
Well, you have used the name `ARIA_LABEL`, so it will be `aria_label` (small cases). That is not an issue, actually.

Anyway, as usual:

As we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by adofito** [comment]
Hi knalli,

Thanks for the prompt response but it doesn't work.

I changed the case, the code looks like this now:
<button 
        ng-click="undelete($event,id)"
        translate-attr="{aria_label:'Products.Create_Product.Undelete_Variant'}"
        translate="Products.Create_Product.Undo"
        ng-if="id.deleted">
  UNDO
</button>

I changed the case and this the html generated:

<button  ng-click="undelete($event,id)" translate-attr="{aria_label:'Products.Create_Product.Undelete_Variant'}" translate="Products.Create_Product.Undo" ng-if="id.deleted" aria_label="Deshacer Borrar">Deshacer</button>

so the aria-label property is still being written as aria_label and the screen reader can't parse it.

-Carlos

**Comment by adofito** [comment]
Plunker here:

https://embed.plnkr.co/lkaSKP4aM5Q6BFlLGGdy/

**Comment by knalli** [comment]
As I said already: Use the correct attribute name, `ARIA_LABEL` is not correct: https://plnkr.co/edit/ExYPNRpRl8f6cmkbORjJ?p=preview

**Comment by adofito** [comment]
Cool. Got it. So, the syntax is different with dashed attributes. Do you need help updating the documentation?

**Comment by knalli** [comment]
There is no different syntax: It takes the given property name and uses it as an attribute name. Both keys aren't the same.

**Comment by knalli** [comment]
If you think there should be an addition in the docs, you are welcome for any suggestions (just as a pull request, our docs are in the source code).

**Comment by adofito** [comment]
The doc reads as this:

```
<ANY translate-attr="{ ATTRIBUTE_NAME: 'TRANSLATION_ID' }"></ANY>
```

The actual functioning code here is
```
<ANY translate-attr="{ 'ATTRIBUTE_NAME_WITH_DASHES': 'TRANSLATION_ID' }"></ANY>
```

Thanks a lot

**Comment by knalli** [comment]
That does not make sense. There cannot be any "magic" code because attribute cases are important for some other parties (clients, frameworks). Just because AJS supports several formats (like ngIf vs ng-if vs ng:if ng data-ng-if) that does not mean they are the same.

In addition, in this case also useful: `translate-attr translate-attr-aria-label="ariaLabel"`. Plnkr updated.

A docs PR would be still nice, but we can close this, I guess.

**Comment by adofito** [comment]
My point is not the case but the quotes around the attribute name when it contains a hyphen in the name. I assumed the ATTRIBUTE_NAME was just a placeholder not an actual style suggestion (as in, it should be all caps).

So, attribute without dashes no quotes needed, attributes with dashes in the name need quotes in the name.
