### ISSUE TITLE
Using Cookies across http/ng-apps

### ISSUE THREAD

**Issue by Flignats** [angular-translate/angular-translate#1686]
### Subject of the issue
I'm using ng-translate and useCookieStorage for translations and to remember the user's language preferences. The language preferences can be changed on multiple pages, such as the Account page or the Profile page.

Setting the language sets a cookie for that page and if the user refreshes the browser the correct language is displayed. However, the cookie is page (location?) specific and the language is not correctly being applied across pages (http requests).

The cookie is being stored as follows:

Example:
If user is on the /Account page and set their language, the cookie is as follows:
Name: NG_TRANSLATE_LANG_KEY
Path: /Account

If the user is on the profile page:
Name: NG_TRANSLATE_LANG_KEY
Path: /Profile

### Your environment
Angular-translate v2.13.1
Angular 1.3.15
Chrome Version 55.0.2883.87 

### Steps to reproduce
Hopefully steps to repro are not needed. The cookie is setting the language, but not being remembered across different pages of the application. The application is comprised of multiple ng-apps. I.e. the profile page is its own app, the account page its own, ect.

### Expected behaviour
If a user sets their language preference on page A, that language preference should be used on page B

### Actual behaviour
Each page remembers its language preference set. I.e. if I set my language to German on the Account page, it will be remembered upon refresh. But, if I navigate to the /Profile page the language preference used is the last set from this page. ( not from other pages).

**Comment by knalli** [comment]
You can implement your own cookie storage plugin. Just have a look at the default implementation and built it for your app.

**Comment by Flignats** [comment]
So, is it because I have multiple ng-apps that a custom storage solution is required?

**Comment by knalli** [comment]
Well, we don't care. Don't get this wrong: The api for a storage plugin is very simple. If you have a case which the default implementations do not work for you, just create your own.

And indeed, multiple apps is not a regular situation.

**Comment by Flignats** [comment]
Ok, so I went ahead and created a custom storage. However, I'm still having the same issue where the cookie is being set uniquely to each page.

My storage:

`app.factory('languageStorage', function ($cookieStore) {
    return {
        put: function (name, value) {
            $cookieStore.put('language', value);
        },

        get: function (name) {
            return $cookieStore.get('language');
        }
    }
})`

When using Chrome Dev Tools to view the cookie ( Application > Storage > Cookies ) I seen an entry for language with its value.

Both pages have the same cookie entry but the values remain unique to themselves. The 'Path' values are not the same, could this be causing an issue? Angular 1.3.15 does not support adding an options object to the cookie, so cannot add in { path: '/' } as a third parameter.

They have their respective paths:

/Account
/Profile

**Comment by knalli** [comment]
Yep, that's the custom storage api. Everything else is custom impl.

I'm sorry, but dealing with AngularJS/$cookieStore is up to you. I cannot help you with that. If the api does not supports your case, there would be the standard way left.

**Comment by Flignats** [comment]
Unfortunately, I think the issue is related to the infrastructure and that 1.3.15 does not support a third options parameter. This is supported in 1.4.

Still, localStorage does allow for persistent language settings, so there is that as a workaround.

Thanks for the help knalli.
