### ISSUE TITLE
Unit Test for using translate as a directive, not a filter

### ISSUE THREAD

**Issue by bschmitz9** [angular-translate/angular-translate#1690]
### Subject of the issue
Describe your issue here.
I am trying to wrote a unit test (karma/jasmine) for my component, which is using "translate" as a element attribute, not a filter. The test was passing fine when I used translate as a filter but in an effort to reduce the number of watches on the DOM, I am trying to use the translate directive rather then the filter.

### Your environment
I am using angular-translate 2.13.1
angular 1.5.8

### Steps to reproduce
I have a button with the label defined as: {{"button.label"}}
The above gets translated literally as if it should be "button.label" when it really should be translated to "Click Me". Is there a way to write a karma/jasmine mock directive that allows for this test to pass:

var buttonLabel = element.find("button").html();
expect(buttonLabel).toEqual("Click Me");

This fails: "expected "button.label" to equal "Click Me".

var mockFilter = function (value: any) {
       if (value === "button.label") {
              return "Click Me"
        }

angular.mock.module(function ($provide:any) {
            $provide.value("translateFilter", mockFilter);
  });

Is there a way to make this test pass when using translate as a directive, and not a filter?

**Comment by knalli** [comment]
Apart from you should not been required testing our directive, you must ensure digest cycles in unit tests manually. And if the translations are loaded async and with promises (as it is used in a directive), this can be even more than one.

**Comment by bschmitz9** [comment]
I'm testing to make sure the strings are being translated correctly within the template of a custom component I'm building. All works fine when translate is used as a filter but not as a directive. Running digest cycles manually in the beforeEach and within each necessary test doesn't seem to work either. It still interprets the "button.label" literally and doesn't translate.

**Comment by knalli** [comment]
Maybe your test setup is too complex. Use just `.translations()` like here: https://github.com/angular-translate/angular-translate/blob/d4a04685340f900b3d2801051257484e58140368/test/unit/service/translate.spec.js#L63

**Comment by bschmitz9** [comment]
Yep that does it. Thanks for the help!
