### ISSUE TITLE
Dynamic variable not updating HTML attribute on change

### ISSUE THREAD

**Issue by Flignats** [angular-translate/angular-translate#1691]
### Subject of the issue
Dynamic variable in HTML attribute not updating with change.

### Your environment
* version of angular-translate - **v2.13.1**
* version of angular - **v1.3.15**
* which browser and its version - **Chrome Version 56.0.2924.87 (64-bit)**

### Steps to reproduce
I have the following code:
`<span ng-show="boolean" data-toggle="tooltip" data-container="body" translate-value-variablename="{{someVariable}}" translate-attr="{'data-original-title': 'id'}" data-placement="auto right">!</span>`

In my language file I have 'id' as an entry and {{variablename}} in its content. In my view, when {{someVariable}} updates, the 'data-original-title' does not include the variable. **I do get the correct results** for the variable in the 'translate-value-variablename' attribute. As shown below:

`<span ng-show="boolean" data-toggle="tooltip" data-container="body" translate-value-variablename="Ray W." translate-attr="{'data-original-title': 'id'}" data-placement="auto right" data-original-title="In use by: ">!</span>`

### Expected behaviour
Expectation:
data-original-title="In use by: Ray W."

`<span ng-show="boolean" data-toggle="tooltip" data-container="body" translate-value-variablename="Ray W." translate-attr="{'data-original-title': 'id'}" data-placement="auto right" data-original-title="In use by: Ray W.">!</span>`

### Actual behaviour
The data-original-title attribute does not update to include the variable content.

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
