### ISSUE TITLE
Removing duplicate keys from translation file

### ISSUE THREAD

**Issue by sadiksha** [angular-translate/angular-translate#1695]
### Subject of the issue
I want to detect if my translation has duplicate keys or same text that has duplicate texts..

### Your environment
* version of angular-translate: 2.12.1
* version of angular: 1.5.8
* which browser and its version: 1.8.0

### Steps to reproduce
Lets assume that I have an translation js file called messages_en.js which looks like this:

```
var translationsEN = {
	TASKS:'Tasks',
        TASKS:'Tasks'
}
```
In this case both the keys and values are same.

### Expected behaviour
As the angular-translate-handler-log displays error message on the browser when there are missing translation, I expect my duplicate values also to be shown on the console of the browser.

### Actual behaviour
There is no console right now even if I have duplicate keys and values, only duplicate keys, or only duplicate values.

**Comment by tspaeth** [comment]
Hello,

as we had already mentioned in the issue's template, we need a working and as minimal as possible demo covering your specific use case or issue.

Follow these steps:

- Please open this plnkr base.
- Fork it (at the top left).
- Ensure the version of AngularJS and angular-translate is correct.
- Ensure all angular-translate plugins are available; reduce and remove anything you can.
- Write a minimal as possible demo for your specific issue.
- Save and freeze. Provide us the final link to your demo.

Thanks.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
