### ISSUE TITLE
Typings definition for $translate.use() is string but should be ng.IPromise<string>

### ISSUE THREAD

**Issue by rcollette** [angular-translate/angular-translate#1696]
I'm not sure if maintainers here are also submitting Typings definitions.  But for some direct visibility to the issue I am cross referencing.  Feel free to close if not appropriate to be an open issue here.

https://github.com/typings/registry/issues/966

**Comment by knalli** [comment]
No, the definitions are not provided by us.

**Comment by rcollette** [comment]
Scratch that.  This was all confusion because someone in our environment had coded a test stub incorrectly, returning a promise in all cases.  Sorry for the confusion.  Closing.
