### ISSUE TITLE
Multiple breaking digest iteration errors after updating to 2.14.0

### ISSUE THREAD

**Issue by MSchip** [angular-translate/angular-translate#1697]
### Subject of the issue
Multiple breaking digest iteration errors after updating to 2.14.0

### Your environment
* version of angular-translate: 2.14.0
* version of angular: 1.5.11
* which browser and its version: Chrome 56.0.2924.87

### Steps to reproduce
I'm still looking into what $translate actions are causing this specifically. Right now it's a repeated error upon application load.

### Expected behaviour
No breaking digest iteration errors

### Actual behaviour
![screen shot 2017-02-13 at 12 29 43 pm](https://cloud.githubusercontent.com/assets/5643058/22894838/7060dc94-f1e8-11e6-89c9-7ff186b27901.png)

**Comment by tspaeth** [comment]
Do you have your configuration part at hand or even better as in the template mentioned - a short plnkr - example?

**Comment by MSchip** [comment]
Here's the configuration simplified:
```
/* global module */
'use strict';
/**
 * Services                                                                                                 Directives - Web Components
 * ************************************************************************************************************************************
 */
var angular = require('angular');
require('../../node_modules/angular-translate/dist/angular-translate.min');
var app = angular.module('i18n-implementation', ['pascalprecht.translate']).config(['$translateProvider', function ($translateProvider) {

    var eng = 'eng';
    var spa = 'spa';
    var deu = 'deu';

    function get(argument) {
        if (argument === 'eng') {
            return {
                testOne: 'English',
                testTwo: 'EnglishTwo'
            };
        }
        if (argument === 'spa') {
            return {
                testOne: 'Spanish',
                testTwo: 'SpanishTwo'
            };
        }
        if (argument === 'deu') {
            return {
                testOne: 'German',
                testTwo: 'GermanTwo'
            };
        }
    };

    $translateProvider.translations(eng, getTranslationData(eng));
    $translateProvider.translations(spa, getTranslationData(spa));
    $translateProvider.translations(deu, getTranslationData(deu));

    $translateProvider.useSanitizeValueStrategy('escape');
    $translateProvider.fallbackLanguage(eng);
    $translateProvider.preferredLanguage(eng);

}]);

module.exports = app;
```

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

*Please don't give a "simplified" configuration away. And, btw, it is always a bad idea working with minified code. Minified code is legacy only and meant for people who do not combine/import the actual library code.*

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by knalli** [comment]
Friendly reminder. We need more information.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
