### ISSUE TITLE
Translate filter fails to replace variable when using components

### ISSUE THREAD

**Issue by Stnaire** [angular-translate/angular-translate#1700]
Translate filter doesn't replace variables when using angular's components and "$ctrl.varName" notation.

### Your environment
* version of angular-translate: 2.14.0
* version of angular: 1.5.9
* which browser and its version: chrome 56

### Steps to reproduce
Here is a unit test : https://plnkr.co/edit/twOaJC8xIT4SG9DbCxc8?p=preview.

### Expected behaviour
The output should be "Hi, John" (or "Bonjour, John") each time.

### Actual behaviour
The second example fails.

**Comment by knalli** [comment]
AngularJS filter do not have access to the current scope (in which `$ctrl` is hold). Therefor, the expression `$ctrl.name` cannot be resolved.

You must provide a full object, not an interpolation expression.

Scratch (look for ng-init): https://plnkr.co/edit/8T9d9GDbFCeYB7uF4Tuv?p=preview
