### ISSUE TITLE
Since version 2.14.0: keys isn't translated when change language twice with partial loader

### ISSUE THREAD

**Issue by detollenaere** [angular-translate/angular-translate#1703]
We use the partial loader (a part is a json file which contains translations for a specific language). When using version 2.14.0, if we change the language once, it works perfect. But if we change one more time to put back the original language, keys are not translated.

Remarks: it worked nice with version 2.13.1

### Your environment
* version of angular-translate: 2.14.0
* version of angular: 1.6.2
* which browser and its version: chrome

### Steps to reproduce
I created quickly an example:
https://plnkr.co/edit/9ECE1dXl4ECfmx9Kgdxh?p=preview

Please, change language to FR (it works) and put back EN -> key 'label1' won't be translated.

**Comment by knalli** [comment]
Oh, this is bad. We have optimized and fixed the partial loading process for 2.14. So far, I can confirm the demo case.

**Comment by knalli** [comment]
Well, there was a conflict because of an additional addPart (why?) and a refresh+use combo. 

That works, a `$translate.use()` only: https://plnkr.co/edit/SNzePFma6xOI2M4ipE1u?p=preview

**Comment by detollenaere** [comment]
The additional addPart was well a mistake ;). But without this additional addpart, the bug is still there with the refresh + use combo. I will see if I can bypass the refresh step in my project.

**Comment by knalli** [comment]
But why refresh and use? Isn't the plnkr I've updated enough?

**Comment by detollenaere** [comment]
Like I said, I will check in my project but I think it will be enough for us. I just want to inform you that the bug still occurs in this case. Thanks
