### ISSUE TITLE
Translate cloak class not removed when using translate-cloak directive

### ISSUE THREAD

**Issue by laurent-bettin** [angular-translate/angular-translate#1705]
Hi, 

When using translate-cloak directive `<any translate-cloak>` the .translate-cloak class is not applied, in  other case when using `<any translate-cloak="key">` the .translate-cloak is not removed.
I provide a plunker to illustrate, am I doing something wrong ?

Thanks

### Your environment
angular-translate 2.15.0
angular 1.5.3

### Steps to reproduce
http://plnkr.co/edit/UwGYhf2O1opdkZwuuORf?p=preview

**Comment by knalli** [comment]
Hi.

Yes, that's a bug. You should use `$translateProvider.use('en')` in the config phase in order to let translate the correct language much more earlier than in run(), but the cloak issue is a bug.

Fixed in 2.15.1 coming im some seconds.
