### ISSUE TITLE
npm WARN grunt-angular-translate@0.3.0 requires a peer of grunt@~0.4.0

### ISSUE THREAD

**Issue by Arti3DPlayer** [angular-translate/angular-translate#1706]
When i do `npm install`, i get warning;

`npm WARN grunt-angular-translate@0.3.0 requires a peer of grunt@~0.4.0 but none was installed.`

My dependencies looks like:
```
{
    "angular": "1.5.9",
    "grunt": "^1.0.1",
    "grunt-angular-translate": "^0.3.0",
}
```

### Your environment
* version of angular-translate
0.3.0
* version of angular
"1.5.9"

**Comment by knalli** [comment]
Hi @Arti3DPlayer Please file an issue at https://github.com/angular-translate/grunt-angular-translate so @firehist can take care of it.
