### ISSUE TITLE
Does not update locale after page reload

### ISSUE THREAD

**Issue by Delagen** [angular-translate/angular-translate#1707]
### Your environment
* angular-translate@2.15
* version of angular 1.5.11
* Chrome 56

### Steps to reproduce
2 language en-us ru-ru
with fallback to en-us
save current locale to localeStorage

switch language to en-us ($translate.use)
reload page
switch language to ru-ru 
values not updated

### Expected behaviour
Update values of translations

### Actual behaviour
Translation stays on English
On version 2.13.1 all works fine

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by Delagen** [comment]
I think error near
```
if (angular.isString($preferredLanguage) && indexOf($fallbackLanguage, $preferredLanguage) < 0) {
        $fallbackLanguage.push($preferredLanguage);
      }
```
when $fallbackLanguage does not equal $preferredLanguage
$fallbackLanguage turns into array and load both translations (may be sometimes wrong)
since it, switch between start up language to second (both in $fallbackLanguage) is impossible
I simply change my app to call .fallbackLanguage earlier than .preferredLanguage to exclude this behavior
Since it my app works as expected.

**Comment by knalli** [comment]
I have added some improvements to docs, api and used samples. Without rewriting the loader life cycle, we cannot do more.
