### ISSUE TITLE
'pascalprecht.translate' not found even though it's there in the js files.

### ISSUE THREAD

**Issue by Tebra** [angular-translate/angular-translate#1708]
### Subject of the issue
I just can't load pascalprecht.translate as a dependency. 
Error message from angular: 
`Error: [$injector:nomod] Module 'pascalprecht.translate' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
`

    angular.module('app', [
    'app.run',
	'app.filters',
	'app.services',
	'app.components',
    'app.directives',
	'app.routes',
	'app.config'
    ]);

    angular.module('app.run', []);
    angular.module('app.routes', []);
    angular.module('app.filters', []);
    angular.module('app.services', []);
    angular.module('app.config', []);
    angular.module('app.directives', []);
    angular.module('app.components', [
    'ui.router',
    'angular-loading-bar',
	'restangular',
	'ngStorage',
	'satellizer',
	'ngSanitize',
    'ngResource',
	'ngTouch',
	'ngAnimate',
	'ngResource',
    'ui.load',
	'pascalprecht.translate'
    ]);

I CAN find the angular-translate module in my .js file and it should be loadable. My final.js file is structured like this:
 - angular.js
 - lots of other libs
 - angular-translate.js
 - my.app.js file 

I uploaded my final.js in a zip here, if it's of any help.
[final-0d08d1d216.js.zip](https://github.com/angular-translate/angular-translate/files/819320/final-0d08d1d216.js.zip)

Im using Bower to manage my dependecnies, and everything else works when I remove the angular-translate dependency.
I'm stuck on this for weeks now. I don't know how to debug this properly. Any hints are very very welcome. If you need more info just tell me.

### Enviroment
      "angular-translate": "^2.15.0"
      "angular": ">=1.5.x"
latest chrome and firefox versions.

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by Tebra** [comment]
A quick update, I deleted all the other dependencies from my bower.json and added only angular.js and angular-translate.js and now it's working. So my setup is ok. 

I will now add the other dependencies one after the other to try and find out which one is causing the collision with angular-translate. 

I will post my findings here in hope that it helps other people.

**Comment by knalli** [comment]
Ok, great you have find the problem. Looking forward, I'm closing this issue.

**Comment by stephanebouget** [comment]
@Tebra I have the same issue since today.
Did you find the dependency that causes the collision ?

**Comment by pfigueiredo** [comment]
For anyone having this problem checks the order of loading.  having it load at the end and making sure that `angular-translate` loads before `angular-translate-loader-partial`... as I was using _angular-translate-loader-partial_ in my case.
