### ISSUE TITLE
translate converts successfully all spaces except one (rendered as &nbsp;)

### ISSUE THREAD

**Issue by vivelys** [angular-translate/angular-translate#1709]
### Subject of the issue
Hello,
In my es_ES.json file I have :
```
"load" : {
   ...
   "editBlocks": {
      ...
      "selectBlocksFile": "Seleccione el archivo de parcelas a importar",
      ...
   }
   ...
}
```
in my html page I have:
`<span class="listItemA">{{'load.editBlocks.selectBlocksFile' | translate}}</span>`
The rendered page looks like :
`Seleccione el archivo de&nbsp;parcelas a importar`
I don't understand why all space chararcters are successfully rendered except one.

### Your environment
* version of angular-translate : 2.7.2
* version of angular : 1.4.0
* which browser and its version: IE 11.576.14393.0, Firefox 51.0.1

### Expected behaviour
`Seleccione el archivo de parcelas a importar`

### Actual behaviour
`Seleccione el archivo de&nbsp;parcelas a importar`

Thank you for your help

**Comment by knalli** [comment]
Hi,

please have a look at your setup. You are using old versions both of Angular JS as well as angular-translate.

As we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
