### ISSUE TITLE
$translate.use() reloads my controllers using ui-router

### ISSUE THREAD

**Issue by liamtarpey** [angular-translate/angular-translate#1711]
We've implemented angular translate into an app successfully before but we're using a different approach on this new one and running into issues.

So our current order of affairs is:
1. basic angular-translate config (static files path)
2. display loader
3. authenticate user
    - If user is logged:  use interface language
    - If user is NOT logged: get lang from param or fallback to 'en' if no param
4. set language using `$translate.use(lang) `
5. hide loader 

In every controller we have a `var init = function() {` which runs first and sets up whatever it needs to. 

Placing a console.log() inside of this always runs it twice as well as every subsequent function using the above steps.

Checked through the docs but can't see anything about .use() reloading controllers after it's finished but removing .use() and not setting any translate language fixes the issue. 

I'm assuming that because the controller is being loaded before $translate.use() has been executed that we're running into a reload immediately after the language has been set. Is this expected behaviour? Would be quite a huge job for us to now block loading of any controller until after all these steps have ran unfortunately.

Any ideas? Been stumped on this for a while now.

### Environment
* Angular translate v2.11.0
* Angular JS v1.5.5
* Angular UI Router v0.2.18
* All browsers

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by knalli** [comment]
Maybe the angular-translate directive would regenerate a html element (when used with html value), apart from this we do not regenerate HTML and therefore are not able to a) know and b) reload any existing controller.

**Comment by knalli** [comment]
> I'm assuming that because the controller is being loaded before $translate.use() has been executed that we're running into a reload immediately after the language has been set.

Although that's true, the pending loader is being stored also. Without more details, there is nothing more to say. Maybe a look for more recent releases would be worth.
