### ISSUE TITLE
Kannada or Hindi language is not working with minified version of the project using angular translate

### ISSUE THREAD

**Issue by naga7557** [angular-translate/angular-translate#1714]
### Kannada or Hindi language is not working with minified version of the project using angular translate

Angular translate plug-in using for my project for both controller text and UI text. It is working fine with un-minified project build. But minified project build, junk values are displaying for kannada or hindi languages. 

I have tried all files minified except the plugin and resource file is unminified - not working.

I have tried all files minified including the plugin and resource file is minified - not working.

If I separately open the minified resource file in notepad, it showing correctly the languages.
But while in browser when application loading and displaying, it is showing the junk file.

Expectation:
All the minified files should work normally including angular-translate plugin and resource files.

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by knalli** [comment]
Hello,

this is a general reminder: We are still waiting for your reply with additional details. If you cannot help us, we cannot help you.

Looking forward to hear from you.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
