### ISSUE TITLE
Data-binding with multiple files

### ISSUE THREAD

**Issue by Qti3e** [angular-translate/angular-translate#1715]
Hello, everyone.
I'm writing a modular web application that has multiple plugins, each plugin has a different languages objects.
The plugins are JSON files, I attached an example for you to see.
[editor.txt](https://github.com/angular-translate/angular-translate/files/869906/editor.txt)
My question is that how can I load plugin's languages?

For more details I put my loader function:
```js
load: function (csp_file, callback) {
                callback = typeof callback !== 'undefined' ? callback : angular.noop;
                $http.get(csp_file, {
                    // todo: it must be true in production
                    // cache: true
                }).then(function (response) {
                    if(response.status == 200){
                        // I should load language files here
                        $rootScope.plugins[response.data['package']] = response.data;
                        (function (plugin) {
                            eval(response.data['app']);
                        })(pdk.plugin(response.data['package']));
                        callback(true);
                    }else {
                        callback(false);
                    }
                })
            },
```
Thanks for your helping :)

**Comment by tspaeth** [comment]
Please ask "how do I..." questions on Stackoverflow: http://stackoverflow.com/questions/tagged/angular-translate - you'll reach a bigger audience. 

This issue tracker is mainly the feature-/bugtracker for angular-translate. But you're always free to add a feature request later on. 

Thanks.

**Comment by knalli** [comment]
Given our API for loading translations incl. support for full custom loaders as well as the implementation of the specific partial loader, we have enough prepared for customized situations.

Maybe, your question can and should be discussed on a more abstract way at SOF.
