### ISSUE TITLE
angular-translate is there a way to reference an ID_KEY inside other ID_KEY?

### ISSUE THREAD

**Issue by serchduran** [angular-translate/angular-translate#1718]
I need to reference an ID_KEY inside other ID_KEY in order to use commmons Strings inside my APP, but I don´t know if this is possible, if not I need a suggestion please, what I try to do is something like this:

```
//inside commons.js
"mainTitle.applications": "Applications"
```
```
//inside header.js
"header.mainTitle.link.applications": "mainTitle.applications"
```
```
//inside home.js
"home.mainTitle.label.applications": "mainTitle.applications"
```

So with this I could give to the Professional Translator a good context for each ID_KEY in order to write the right translation.

**Comment by tspaeth** [comment]
Please ask "how do I..." questions on Stackoverflow: http://stackoverflow.com/questions/tagged/angular-translate - you'll reach a bigger audience. 

This issue tracker is mainly the feature-/bugtracker for angular-translate. But you're always free to add a feature request later on. 

Thanks.

**Comment by serchduran** [comment]
Thanks

**Comment by knalli** [comment]
We haven't such a feature. Maybe you can create a self made version of a translation file and either use a custom loader or use a custom transformer within your build chain for creating a final translations file.
