### ISSUE TITLE
Directive for "foo-bar" syntax attributes is not working

### ISSUE THREAD

**Issue by serchduran** [angular-translate/angular-translate#1719]
I am trying to use the directive component in order to translate an attribute like this:

`translate-attr="{ uib-tooltip: 'table_organizationHeader_text_editTooltip' }"
`
My attribute as you can see is: `uib-tooltip`

But when I make something like that the translation is not achieved, I got the next error:

`Syntax Error: Token '-' is unexpected, expecting [:] at column 6 of the expression [{ foo-bar: 'table_organizationHeader_text_editTooltip' }] starting at [-tooltip: 'table_organizationHeader_text_editTooltip' }].`

If I use filter everything works well, but since angular-translate recommend to use DIRECTIVES instead of FILTERS I would like to find any solution for this.

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/.github/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by knalli** [comment]
Hello,

this is a general reminder: We are still waiting for your reply with additional details. If you cannot help us, we cannot help you.

Looking forward to hear from you.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
