### ISSUE TITLE
Is it possible to integrate it in Angular 4.0 project ?

### ISSUE THREAD

**Issue by gtzinos** [angular-translate/angular-translate#1720]
Is it possible to integrate it in Angular 4.0 project ?

**Comment by knalli** [comment]
@gtzinos  This project does only work in AngularJS 1.x based projects. Any support for Angular 2+ would require a full rewrite.

Although we had/have plans for such things, there is no progress.

You could have a look at http://www.ngx-translate.com/, a project which looks nice and seems to follow some similar ideas.

**Comment by gtzinos** [comment]
Okay thank you. You have a great project, upgrade it.
