### ISSUE TITLE
Using with Intel XDK

### ISSUE THREAD

**Issue by flythird** [angular-translate/angular-translate#1721]
### Subject of the issue
I Use Intel XDK and this tool has its own bower management
I don't see angular-translate  in the list of i18n packages.

### Your environment
T* version of angular-translate:      the last version
* version of angular : 1.6.4
* which browser and its version: chrome or ie no matter

### Steps to reproduce
install intel XDK
create a new project html5
add a bower package

### Expected behaviour
The angular-translate should or could be in the i18n package list

### Actual behaviour
i am testing intel XDK and i wonder : 
- why i don't find this very good angular-translate

**Comment by knalli** [comment]
Sorry, we neither know about nor will take care special support for Intel XDK. We are publishing packages listed in bower and npm, that's enough and is working.
Your toolchain have to support one of both (bower/npm).

In your case: It sounds it does not support bower correctly.
