### ISSUE TITLE
translate filter fails on reload of the page.

### ISSUE THREAD

**Issue by amitparrikar** [angular-translate/angular-translate#1723]
### **translate** filter fails when we refresh the page.
I have used **translate** filter in my templates, however i have used **One-Way Databinding**
eg. {{ :: TEXT_TO_TRANSLATE | translate }}
With this set up in my html, i try to refresh the page. When the page loads; **translate** filter fails to replace the text.

I went on to your source code and noticed that **translate** filter uses the service **$translate.instant();** method.
now the method documentation of **instant** says that:
> Returns a translation instantly from the internal state of loaded translation. All rules regarding the current language, the preferred language of even fallback languages will be used except any promise handling. If a language was not found, an asynchronous loading  will be invoked in the background.

So looks like with One-Way data-binding async loading is of no use. 
Also my **en_us.json** file is pretty big, may be it takes time to load.
I tried with Two-Way data-binding and it works, however this is not the right way for huge applications!.

**My Question is:**
How to use **translate** filter in such scenario? i.e. with One-Way data-binding ?

I appreciate your help.

### Your environment
* version of angular-translate : **2.15.1**
* version of angular: **1.6**
* which browser and its version: **Chrome 57**

### Steps to reproduce
Since my question is not code specific hence I have given the exact details.

### Expected behaviour
**translate** filter should translate properly on page refresh.

### Actual behaviour
**translate** filter fails and displays the keywords of the translation

**Comment by knalli** [comment]
You cannot use one-way binding in combination with an asynchronous loader -- both are incompatible features limited due the fact an AngularJS filter is a pure function without any possible deferred execution context (no "wait for load").

Option 1: Use no one-way binding (read: no binding which cannot be updated).
Option 2: Use not an asynchronous loading setup which means all translations have to be available in the config phase.

**Comment by amitparrikar** [comment]
Thanks a lot for quick response.

**Comment by amitparrikar** [comment]
I came up with a solution for One-Way Data-binding:
'use strict';
```
angular.module('MY_APP_MODULE').filter('i18n', function ($filter) {
  function _i18n(input) {
    var val = $filter('translate')(input);
    if(input === val){
      return;
    }else{
      return val;
    }
  }
  _i18n.$stateful = true;
  return _i18n;
});
```
One-Way template data-binding is complete when the value bound is not **undefined**

**Comment by knalli** [comment]
Well, ok. 

But beware default translations will not work, as well as translationId==translationText situations. Maybe in your situation a proper solution, but not in general.
