### ISSUE TITLE
Cannot use numeric keys in translate-value

### ISSUE THREAD

**Issue by danallen88** [angular-translate/angular-translate#1724]
### Subject of the issue
It would be nice to be able to use numeric keys for variable replacement, for example with the `translate-value` attribute.  In JavaScript, numeric keys are casted to a string, and I would expect angular-translate to treat them the same way.

### Your environment
* version of angular-translate: ~2.7.2
* version of angular: ~1.4.3
* which browser and its version: Chrome Version 57.0.2987.133 (64-bit)

### Steps to reproduce
http://plnkr.co/edit/R6Z5vWvO9RUA6UyExeDj?p=preview

### Expected behaviour
If I have no control over the JSON translation files and they contain strings that require variable replacement that look like `"name-full": "{{1}}; {{0}}"`, I would expect that something like `<span translate="name-full" translate-values="{ 0: first, 1: last}"></span>` would turn into `<span>last; first</span>`.

### Actual behaviour
I get numeric values instead of expression value for that key`<span>1; 0</span>`.

**Comment by knalli** [comment]
Note/reminder:

It looks like your environment is using an old or older release of AngularJS and/or angular-translate. After updating your dependencies, please check and verify your issue again.

**Comment by knalli** [comment]
... but this will not help in case of the request for numeric values. Intentionally, we only support strings (so `'0'` would be fine) because that's the common type of everything (i.e. an attribute value).
