### ISSUE TITLE
Transclusion directive and translate question

### ISSUE THREAD

**Issue by jakobadam** [angular-translate/angular-translate#1726]
Is it possible to create a transclusion directive that translates correctly in all the cases beneath?
```
<my-header>KEY</my-header>
<my-header><span translate>KEY</span> ...</my-header>
<my-header><span translate>KEY</span></my-header>
```

Example: https://codepen.io/jakobadam/pen/bWwyJY

kind regards,
Jakob

**Comment by knalli** [comment]
Well, I assome: The issue is not the transclusion per se, but the scope configuration (isolated).

=> Either you switch to the filter, or add a nested tag.

An element having a `translate`-attribute (and so creating the directive instance) and additional inner content does not make sense at all.
