### ISSUE TITLE
Undocumented cool hack

### ISSUE THREAD

**Issue by cyrilchapon** [angular-translate/angular-translate#1728]
I found this hack, which I find pretty cool and is not documented [here](https://angular-translate.github.io/docs/#/guide/06_variable-replacement), kinda "double interpolation".

I personaly used it so I guess I'm not the only one facing this use-case

```
{
  'table.total': 'Total for {{group}}',
  'table.label.muffin': 'muffins'
}
```

```
$scope.groupKind = 'table.label.muffin';
```

```
<span translate="table.total" translate-value-group="{{groupKind | translate}}"></span>
```

Which prints

> Total for muffins

=]

**Comment by knalli** [comment]
Well, that's no actually, but using everything as expected! So no fear this will be forbidden anytime.
