### ISSUE TITLE
Override English translation using static file loader

### ISSUE THREAD

**Issue by dhaval85** [angular-translate/angular-translate#1729]
### Subject of the issue
I've a default translation for en_US in my source code. However I'd like to allow user to override these translations using static file loader. How can I do this? Let me know if more information is required. 

### Your environment
* version of angular-translate - 2.11.1
* version of angular - 1.5.5
* which browser and its version - Chrome 57

### Steps to reproduce
None
### Expected behaviour
Want to override translations

**Comment by knalli** [comment]
Sorry, but you are not providing any information. Is this a bug or missing detail in the documentation?

**Comment by dhaval85** [comment]
Thank you. I managed to get it work using forceAsyncReload(true). :)
