### ISSUE TITLE
Do not work with the lastest ui-router release

### ISSUE THREAD

**Issue by nipmarsh** [angular-translate/angular-translate#1730]
### Subject of the issue
There is no translation applied with ui-router 1.0.1

### Your environment
* version of angular-translate 2.15.1
* version of angular 1.6.4
* which browser and its version Chrome

### Steps to reproduce
update ui-router to the version 1.0.1 and reload your webite

### Expected behaviour
Translations applied

### Actual behaviour
No translations

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/.github/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by ZappaFan** [comment]
Hi,
I had this problem as well, for me this happened because I was registering a partial loader;
`$rootScope.$on('$stateChangeStart', function () {
      $translatePartialLoader.addPart('translation');
      $translate.refresh();
    }); `
Rewriting this for ui-ruiters new transition hooks gives
`$transitions.onStart( {}, function (transition) {
      $translatePartialLoader.addPart('translation');
      $translate.refresh();
    });`
and then it worked fine. Hope this helps!

**Comment by nipmarsh** [comment]
Still not working for me... I'm also using the partial loader...
You want a plnkr and maybe some coffee?

**Comment by ZappaFan** [comment]
A plunker would be great, I tried to make one but it ended up working and now I can't get it to break nicely... (it's at https://plnkr.co/edit/S3RHEs9hsZgS4WVdXRCu?p=preview )

**Comment by knalli** [comment]
Hello,

this is a general reminder: We are still waiting for your reply with additional details. If you cannot help us, we cannot help you.

Looking forward to hear from you.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
