### ISSUE TITLE
.catch is breaking IE8

### ISSUE THREAD

**Issue by jlongo-daitan** [angular-translate/angular-translate#1733]
I can see two ".catch" calls on angular-translate. This is breaking IE8. Please, change them to ["catch"] like you did with ["finally"]

**Comment by knalli** [comment]
Thank you. Maybe you want contribute making a PR?

**Comment by jlongo-daitan** [comment]
Hello

I’d like to contribute. I’m checking internally here in the company here if I can, because the time I found this bug I was working.

Regards
João Sávio Ceregatti Longo
Software Engineer
+55.19.3112.1200<tel:%2B55.19.3112.1200> ext.1280
DaitanGroup | www.daitangroup.com<http://www.daitangroup.com/> | Accelerating.™
Privileged and confidential. If this message has been received in error, please notify sender and delete it immediately.
Conteúdo confidencial. Se esta mensagem foi recebida por engano, favor avisar o remetente e apagá-la imediatamente.

**Comment by knalli** [comment]
PR landed.
