### ISSUE TITLE
translation link @: inside another link

### ISSUE THREAD

**Issue by lolofr62** [angular-translate/angular-translate#1734]
First, sorry for my english !

I begin with angular-translate and i try to use translation link id.
It's working only if @: is at the beginning, but if you want "the @:other_id", it doesn't work.

I see in source code that you always use : 
`translation.substr(0, 2) === '@:'`
and this is why what i'm trying to do doesn't work.

For exemple this is an extract of my translation configuration : 
`"data": {
    "code": "code",
    "libelle": "libellé",
    "groupe": "groupe",
    "groupes": "groupes",
    "groupe_long": "groupe d'applications",
    "groupes_long": "groupes d'applications"
  },
  "view": {
    "groupe": {
      "titre": "Les @:data.groupes_long",
      "msg": {
        "ajout": "Le @:data.groupe a bien été ajouté !",
        "modif": "Le @:data.groupe '{p1}' a bient été modifié !",
        "suppr": "Le @:data.groupe '{p1}' a bient été supprimé !",
        "conf_suppr": "Etes vous sûr de vouloir supprimer le @data.groupe '{p1}' ?"
      }
    }
  }`

Do you think this case could be taken into account in an upcoming delivery?
thanks

**Comment by knalli** [comment]
No. We only translate full strings, with parametrized arguments.
