### ISSUE TITLE
How to set request header while fetching translation via translateProvider.useUrlLoader ?

### ISSUE THREAD

**Issue by rtcoms** [angular-translate/angular-translate#1736]
### Subject of the issue
I am using angular-translate in a rails app. We want to fetch translation from a fingerprinted asset file. To do that we're using `$translateProvider.useUrlLoader(window.translation_file_url);` , where translation_file_url is a cloudfront url.

It is working fine in development environment but we are facing issues in production environment.
Error I'm getting is 
"Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin '<domain_name>' is therefore not allowed access. The response had HTTP status code 403.

Looks like I need to set request header while calling function `$translateProvider.useUrlLoader(window.translation_file_url);`

I've also tried, fetching translations from url explicitly and then setting it as json but that also didn't work. Something like this :

```
$.get(window.translation_file_url, function(data){ 
     var translation_data = JSON.stringify(data)
     $translateProvider.translations('en', translation_data); 
 } )
```

In above request, I was able to fetch translations successfully but `$translateProvider.translations('en', translation_data); ` is not working as expected.

### Your environment
* angular-translate - 2.15.1
* angular - 1.5.3 -
* Google chrome - 58.0.3029.110 (64-bit)

**Comment by knalli** [comment]
You can apply additional `$http` options for the used url loader using `$http: {…}`, see here https://github.com/angular-translate/angular-translate/blob/2.15.1/src/service/loader-url.js#L35-L39.

```js
$translateProvider.useUrlLoader(url, {
  $http: {…}
});
```

The possible values for this are the same as defined in AngularJS itself when using `$http({…})`.

Otherwise use a custom loader.
