### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by marianborlean** [angular-translate/angular-translate#1737]
Circular dependency issue in version 2.15.1

$translateProvider.fallbackLanguage results in circular dependency 

This is my code:

angular
    .module('app')
    .config(translateConfig);

function translateConfig($translateProvider, LOCALES, $injector) {
    $translateProvider.useStaticFilesLoader({
        prefix: 'resources/translate/locale-',
        suffix: '.json'
    });

    $translateProvider.preferredLanguage(LOCALES.preferredLocale);
    $translateProvider.fallbackLanguage(LOCALES.preferredLocale);

}

This is what I get:
dependencies.js:13166 Uncaught Error: [$injector:cdep] Circular dependency found: $http <- $translateStaticFilesLoader <- $translate <- errorInterceptor <- $http <- $templateFactory <- $view <- $state
http://errors.angularjs.org/1.6.4/$injector/cdep?p0=%24http%20%3C-%20%24tra…-%20%24http%20%3C-%20%24templateFactory%20%3C-%20%24view%20%3C-%20%24state

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/.github/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by knalli** [comment]
Well, however:

It looks like the circular dependency situation is made by our configuration. While angular-translate is in the chain of the dependency stack, it has only the parts `$translateStaticFilesLoader` and `$translate` under control. Everything else is up to you, including this "errorInterceptor".

**Comment by marianborlean** [comment]
Hello,

You are right, it was related to injecting translate in the errorInterceptor. So everything is fine, thank you so much for your quick response, this issue can be closed.
