### ISSUE TITLE
Auto translation (question)

### ISSUE THREAD

**Issue by erperejildo** [angular-translate/angular-translate#1738]
Maybe you have spoken regarding this but I'd like to know if this would be possible.

I'm already using angular-translate for  my app in which you can share different recipes. I've got a couple of languages well configured and working like a charm but the ingredients, steps... I can't translate that.

Would be possible this? Obviously not with the same quality being an automated process

**Comment by knalli** [comment]
I don't get it.. what is the issue? Is this a feature?

**Comment by erperejildo** [comment]
No, it's not an issue. I'm talking about a possible feature which translates automatically some content like comments (mostly).

I know some social network like Facebook or Instagram already have this feature but I don't know how they manage this.

**Comment by knalli** [comment]
Ok.

That's not our goal. We translate for well-known translation ids, but not dynamic texts.

>but I don't know how they manage this.

They use an api like Google Translate (obviously, they will not use Google Translate) -- either on server or client side. Server maybe because of api usage tokens..

**Comment by erperejildo** [comment]
Ok, fair enough.

Thanks for your answer and sorry to bother.
