### ISSUE TITLE
Case of different directory for translation

### ISSUE THREAD

**Issue by thedudeboja** [angular-translate/angular-translate#1739]
Hello everyone, I have some issues with angular-translate especially with the loading of translation.
I am programming a website in angular for my school project. In this project, we have an association with differents sports sections.

Each section have specifics translations due to sport's language, and a default translation to avoid issues in case of unavailable key.

### Your environment
* version of angular-translate 2.11.0
* version of angular  1.3.20

translationDir
  |
  |
  |-----default
             | ---i18n_en.json
             | ---i18n_fr.json
  |
  |-----specificSport
              | module1
                     | ---i18n_en.json
                     | ---i18n_fr.json
              | module2
                     | ---i18n_en.json
                     | ---i18n_fr.json

angular.module.config here

```
$translateProvider.fallbackLanguage('en');
$translateProvider.preferredLanguage('en');
$translateProvider.useCookieStorage();

$translateProvider.useLoader('$translatePartialLoader', {
            urlTemplate: '{part}-i18n_{lang}.json',
            loadFailureHandler: 'translationHandler'
 })
```

And the factory

```
factory('translationHandler', function ($q, $log) {
      return function (part, lang, response) {
        $log.error('The "' + part + '/' + lang + '" part was not loaded.');
        return $q.when({});
      };
    })
```

Actually, if the key is unavailable in section, we load english key of this section.
But this is possible to have unavailable key in English too, due to specific translation (we could include default translation everywhere, but it's bad and uggly).

Have you an idea to fix this please ?

Ps: Sorry for my english, I'm not native.

**Comment by knalli** [comment]
On the level of translation key resolving, you can use default values (i.e. as a directive's attribute) or an error handler.

On the level of translations part resolving (for partial loader), there is no such redirection.

If the existing partial loader implementation does not fit you needs, you can implement your own one. Maybe just fork the existing one.. :)
