### ISSUE TITLE
Change language when using $translate service instead of filter

### ISSUE THREAD

**Issue by powerpixelsoft** [angular-translate/angular-translate#1740]
### Subject of the issue
I am using **$translate()** call to retrieve a value for specific translation and this value is used via model binding. There is no filter or directive in my html.
It all works fine when the page is loaded. However, I would like to be able to change translation language by calling **.use(language)** but in my case nothing is translated and I understand, it is logical. Is there a way to update the language and have the changes instantly without using filters?

### Your environment
* version of angular-translate 2.15.1
* version of angular 1.5.9
* which browser and its version IE 11.1066

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://plnkr.co/edit/XorWgI?p=preview) as a base.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by knalli** [comment]
You have three ways to use angular-translate:

1. via the service using `$translate(key).then( (translation) => {…}, …)` (one-time shot)
2. via the directive incl. derivates for attributes: this will watch for changes
3. via the filter: this will watch for changes

In case of the service, you have to listen for the events fired after translations are ready or have been updated. That's all not required using directive/filter.

**Comment by powerpixelsoft** [comment]
Hi knalli,
Thank you for your answer. Would you additionally be so kind to give me a small use-case example for using $translate(..) and subscribing for an event? 
Here is a little code sample from my scenario.
I use TypeScript:
`$onInit() : void {
this.$translate('KEY').then((result: string) => {
              someVMVariable = result;
           });
}`
This is how I am using it now. Why do I do it this way? Because my html files are templates and they have to stay as clean as possible.
Thanks in advance!

**Comment by knalli** [comment]
We have documentation for you:

* https://angular-translate.github.io/docs/#/guide/18_events

**Comment by powerpixelsoft** [comment]
Thanks, I must have missed it accidentally!
Cheers!
