### ISSUE TITLE
How to avoid first page to load with default language and only THEN translate

### ISSUE THREAD

**Issue by louisdoe** [angular-translate/angular-translate#1743]
### Subject of the issue
Hi
I am using Angular-translate in my ionic (1) app. And `translateChangeSuccess` is fired AFTER my first page is loaded, so the user sees the default language, then it is changed to his language just before his eyes. Which is bad UX.
Can you please help me improve that ?

Thanks for yo uhelp

### Your environment
* version of angular-translate v2.8.1
* version of angular ionic 1.3
* which browser and its version Chrome Version 58.0.3029.96 (64-bit)

### Expected behaviour
The first page should load with the right language

**Comment by kptLucek** [comment]
If you're using ui.router, you might consider placing an `resolve` with resolving your language in there.

**Comment by knalli** [comment]
As already said: eventually you will have to look for something like ui router's `resolve` method or similar ideas.
