### ISSUE TITLE
Language change not beeing applied by the translate directive after a route/view change

### ISSUE THREAD

**Issue by leolux** [angular-translate/angular-translate#1744]
Imagine an angular app consisting of two views  A and B. A user starts the app at view A and changes the language there (controller of view A changes the language using the service `$translate.use('new Language');` ). After he changed the language all elements inside view A are translated correctly. So far so good. But when the user navigates from view A to view B (using angulars $location service) the elements inside view B still get translated using the old language. Why is that?

Is it possible to apply language changes in a way that the translate directive always uses the language the user selected even when the user has changed the language inside the previous route/view?

Btw, why does the translate directive use `scope:true,`  which inerhits everything from the parent scope. Wouldn't it be more secure to use an isolated scope?

### environment
* version of angular-translate 2.15.1
* version of angular 1.6.4

**Comment by knalli** [comment]
Demo or it didn't happened. :)

> But when the user navigates from view A to view B […] still get translated using the old language

Maybe the view is rendered without an active AJS context? It's not "live"/not binded any more? Otherwise I cannot understand this.. Because this would amply the angular directive would not be getting active.

> Btw, why does the translate directive use scope:true, which inerhits everything from the parent scope. Wouldn't it be more secure to use an isolated scope?

Well, I guess, it is because of the namespace feature?

**Comment by leolux** [comment]
Sorry, my fault! The issue was caused by a wrong namespace nesting within my language maps.  
In general do you know some gist or extension for checking mismatching keys in a list of local maps? I think it would be helpful during development to avoid such kind of issues when dealing with larger data sets.
