### ISSUE TITLE
Use separate file in $translateProvider.translations

### ISSUE THREAD

**Issue by lararogu** [angular-translate/angular-translate#1745]
I have defined some strings in my app.config.Is it possible to define those strings in a separate file and import it?
 
 $translateProvider.translations('en', {
        TITLE: 'Hello',
        FOO: 'This is a paragraph.',
        BUTTON_LANG_EN: 'english',
        BUTTON_LANG_DE: 'german'
    });

What i would like to have is something like this;
 $translateProvider.translations('en', {
        "strings_file"
    });

**Comment by PAnvesh** [comment]
You can define the strings in a seperate file (languages/lan-en.json), and use below
$translateProvider.useStaticFilesLoader({
    prefix: 'languages/lan-en',
    suffix: '.json'
  });

**Comment by lararogu** [comment]
And where should I place the json file?.Now i have it in the same folder as my app config file but I am not getting the expected string values in the html view.

**Comment by knalli** [comment]
Please have a look at our docs, especially at https://angular-translate.github.io/docs/#/guide/12_asynchronous-loading

**Comment by lararogu** [comment]
thanks,now is working!
