### ISSUE TITLE
Not able to find 

### ISSUE THREAD

**Issue by renilbabu03** [angular-translate/angular-translate#1752]
![screenshosdsdsdt from 2017-06-16 15 25 09](https://user-images.githubusercontent.com/18526147/27221970-2a0922bc-52a8-11e7-9c78-64fca1b559f5.png)

cannot find pascalprecht.translate when using with require js

My configuration:

requirejs.config({
 paths:{
   angularTranslate:'/js/bower_components/angular-translate/angular-translate',
   angularCookie:'/js/bower_components/angular-cookies/angular-cookies',
   angularTranslateStorageCookie:'/js/bower_components/angular-translate-storage-cookie/angular-translate-storage-cookie',
   angularTranslateStorageLocal:'/js/bower_components/angular-translate-storage-local/angular-translate-storage-local',
   angularTranslateLocalStatic:'/js/bower_components/angular-translate-loader-static-files/angular-translate-loader-static-files',
 },
shim:{
 angularTranslate: ['angular'],
        angularCookie:['angular'],
        angularTranslateStorageCookie:['angular'],
        angularTranslateStorageLocal:['angular'],
        angularTranslateLocalStatic:{
            deps: ['angular-translate']
        }
}
})

requireJs(['angularTranslate','angularCookie','angularTranslateStorageCookie','angularTranslateStorageLocal','angularTranslateLocalStatic','pascalprecht.translate'],function(module)..{})

And in the module
(function() {
    define(['angular', 'angularResource','angularSanitize','angularRoute','angularCookie','angularTranslateStorageCookie','angularTranslateStorageLocal','angularTranslateLocalStatic'], function (angular) {
      return angular.module('fleet', [ 'ngResource', 'ngSanitize', 'ngRoute','ngMap','pascalprecht.translate']);
    });
})();

I tried everything but no solution obtained. Pls help

**Comment by knalli** [comment]
We have had already several issues with misconfigured setups regarding RequireJS. Have a look in our search: https://github.com/angular-translate/angular-translate/search?q=requirejs&type=Issues

Our current structure enforces the plugins like angular-translate-storage-local requires angular-translate and so one.

* angular-translate-storage-local requires angular-translate
* angular-translate-loader-static requires angular-translate
* angular-translate requires angular
* etcpp
