### ISSUE TITLE
Infinite loop when fallback language custom loader network call fails

### ISSUE THREAD

**Issue by omarmeky** [angular-translate/angular-translate#1754]
### Subject of the issue

This is similar to https://github.com/angular-translate/angular-translate/issues/1468. If you call `$translateProvider.fallbackLanguage` and use a custom loader for translations and that loader returns a rejected `$http` request then the app hangs.

### Your environment
* version of angular-translate: 2.15.1
* version of angular: 1.5.0
* which browser and its version: Chrome 58

### Steps to reproduce

Visit [this plunker](https://plnkr.co/edit/bgmGAkxtycssadxg0UJ8?p=preview). Change the custom loader to load `i18nk.json` instead of `i18n.json`.

### Expected behaviour
Network call fails but app keeps working.

### Actual behaviour
App hangs (goes into an infinite loop). If you comment out `$translateProvider.fallbackLanguage("es");` this will not happen.

**Comment by knalli** [comment]
The issue is being called because the loader should reject to the requested `options.key` like in [url-loader](https://github.com/angular-translate/angular-translate/blob/2.15.2/src/service/loader-url.js#L42-L44).

See here in plnkr https://plnkr.co/edit/OKXGmAtPATxYO82f0o4e

**Comment by knalli** [comment]
Atm I have no idea how we could check this probably at runtime.
