### ISSUE TITLE
Using translate inside template string

### ISSUE THREAD

**Issue by Ssabin-devalore** [angular-translate/angular-translate#1756]
### Subject of the issue
Hello,

I need to use translate inside template string, i tried to use translate directive and filter but it don't work.

`<div class="tooltip-template">
                        <h6 class=title translate>KEY</h6>
                        <hr/>
                        <div class="tooltip-body">
                            ${contant}
                        </div>
                    </div>`

### Your environment
* angular-translate 2.7.0
* angular 1.4.8
* Any browser

**Comment by knalli** [comment]
Note/reminder:

It looks like your environment is using an old or older release of AngularJS and/or angular-translate. After updating your dependencies, please check and verify your issue again.

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/.github/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
