### ISSUE TITLE
Sanitize

### ISSUE THREAD

**Issue by NilakArgento** [angular-translate/angular-translate#1758]
### Your environment
* version of angular-translate:**2.7.2**
* version of angular:**1.3.15**
* which browser and its version: **Chrome version 58.0.3029.110 (64-bit)**

### Steps to reproduce
http://plnkr.co/edit/jeAvF02XVA55j6EXxq7K?p=preview
### Expected behaviour
` <p>{{ 'HEADLINE' | translate }}</p>`

`   HEADLINE: 'Headline <br> as',`
### Actual behaviour
Why `<br>` tag is not compiled, and what i need to do.. ?!

**Comment by knalli** [comment]
Note/reminder:

It looks like your environment is using an old or older release of AngularJS and/or angular-translate. After updating your dependencies, please check and verify your issue again.

**Comment by NilakArgento** [comment]
Tried also
* version of angular-translate:**2.15.2**
* version of angular:**1.6.5**
Result is same as previous

**Comment by knalli** [comment]
Okay, well: We have [additional "sanitize" strategies](https://github.com/angular-translate/angular-translate/blob/2.15.2/src/service/sanitization.js#L53-L93) and as well the [post-compile addition](https://angular-translate.github.io/docs/#/guide/05_using-translate-directive#using-translate-directive_post-compiling)

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
