### ISSUE TITLE
Change language with $translatePartialLoader

### ISSUE THREAD

**Issue by AndreasHo** [angular-translate/angular-translate#1759]
Hello,

i have a problem with loading the translations. I am using the $translatePartialLoader.

My versions:
angular-translate - v2.15.2 - 2017-06-22
AngularJS v1.6.4
Google Chrome v59.0.3071.115 

My problem:
I am on state "profile" and have the active language "DE" now i am switching to language "EN".
Then i switch the state to "settings" and switch my language back to "DE".
Now i don't see the my translations i only see my keys for the translations.

_State change event_
```
$rootScope.$on('$stateChangeSuccess', function (event, toState, toParams, fromState) {
    $scope.unloadModule(event, fromState.name);
    $scope.loadModule(event, toState.name);
    $translate.refresh();
});
```

_Functions for load/unload the modules_
```
$scope.loadModule = function ($event, module) {
    $event.preventDefault();
    $translatePartialLoader.addPart(module);
};
$scope.unloadModule = function ($event, module) {
    $event.preventDefault();
    $translatePartialLoader.deletePart(module);
};
```

Thanks for watching for a solution.

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/.github/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by AndreasHo** [comment]
Hello,

sry for waiting long time... now i have created an example in plunker.

https://plnkr.co/edit/CoMg4zFuKV8h0LSWe742?p=preview

Here the steps of the error:

1. Start: State "start" + language "DE"
2. Change state to "stop"
3. Change language to "EN"
4. Change state to "start"
5. Change language to "DE"

Now you don´t see the translated value, you see "start.INFO".

**Comment by AndreasHo** [comment]
@knalli ist there any solution?

**Comment by knalli** [comment]
I think this should work

```js
$translate.use(sprache)
  .then(function() {
    $translate.refresh();
  });
```

I'm not sure, looks like this is a specific issue with partial loading and language changes at all. Alternatively, don't remove already loaded parts (depends on the number of translations).

**Comment by vicary** [comment]
@knalli Your workaround did the trick but still FOUC, should really resolve inside the library before it renders out any content IMO.

Not sure if I should open a new issue.
