### ISSUE TITLE
Namespace and Component (isolated $scope)

### ISSUE THREAD

**Issue by AngularPlayer** [angular-translate/angular-translate#1764]
### Subject of the issue
With component angular is using an isolated $scope, and the translate-namespace seen to be lost.

### Your environment
* version of angular-translate : 2.15.2
* version of angular : 1.6.4

###MAIN HTML
```
<div class="content" translate-namespace="MyModuleName">
	<section id="toolbar">
		<toolbar-component>
		</toolbar-component>
	</section>
	<section id="banner">
		<banner-component>
		</banner-component>
	</section>
	<section id="login">
		<login-component>
		</login-component>
	</section>
</div>
```

### LOGIN COMPONENT HTML
```
<div class="content"  translate-namespace=".loginComponent">
	<div class="container">
		<div class="row">
			<span translate=".text"></span>
		</div>
	</div>
</div>
```

### USED JSON FILE
```
{
    "MyModuleName":{
            "loginComponent":{
                  "text":"it's work !"
              }
     }
}
```

### Expected behaviour
```
<div class="content"  translate-namespace=".loginComponent">
	<div class="container">
		<div class="row">
			<span translate=".text">it's work !</span>
		</div>
	</div>
</div>
```

### Actual behaviour
```
<div class="content"  translate-namespace=".loginComponent">
	<div class="container">
		<div class="row">
			<span translate=".text">loginComponent.text</span>
		</div>
	</div>
</div>
```

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/.github/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.
