### ISSUE TITLE
Translate.use "undefined" on Ionic App with Side-menu

### ISSUE THREAD

**Issue by rafaeldcastro** [angular-translate/angular-translate#1765]
I'm using it on an Ionic App with a Home and Side-menu.
The translation goes ok when I initiate the app and even when I change the lang on my phone :D

The problem is that I need to translate through a select on the Side-menu. 
I injected the "**$translate**" on the control, but the property _**use**_ is being marked as undefined.

**My html select:**
`<select id="selLang" ng-model="selLangOption" ng-change="selDefineLanguage(selLangOption)">
            <option value="en">English</option>
            <option value="cn">Chinese</option>
</select>`

**My controller**
`.controller('menuCtrl', ['$scope', '$stateParams',
function ($scope, $stateParams, $ionicPlatform, $translate) {

$scope.selDefineLanguage = function(optionSelected){
        $translate.use(optionSelected);
}`

* angular-translate - v2.9.0 - 2016-01-24
* AngularJS v1.5.3 | Ionic, v1.2.4
* Chrome 59.0.3071.115

**Comment by knalli** [comment]
Note/reminder:

It looks like your environment is using an old or older release of AngularJS and/or angular-translate. After updating your dependencies, please check and verify your issue again.

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/.github/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by knalli** [comment]
... and I also recommend using the search for this: https://github.com/angular-translate/angular-translate/search?q=ionic&type=Issues&utf8=%E2%9C%93

Please update you dependencies and provide a working example. We do not want to rebuild your ionic app.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
