### ISSUE TITLE
Blank text is shown for few seconds

### ISSUE THREAD

**Issue by hani647** [angular-translate/angular-translate#1766]
### Blank text appears for few seconds when user visit website for a first time
When user arrives website for a first time blank text appears for few seconds and then translated text is shown afterwards and works fine through out website.
For example if I've been using p tag
```
<p translate-default="Hello world" translate="landingPage.helloWorld">
</p>
```
Indeed I've used default text if it doesn't find key then default text must be shown but for few seconds
<p> tag appears with innerText null and after few seconds it is populated with literals. I guess it's because JSON file is not fully loaded and template renders so I tried using events and show loader but still loader is shown after few seconds i.e. after 2 seconds but for before 2 seconds my all elements are shown empty which causes bitter UX. 
```
 $rootScope.$on("$translateChangeStart",function(){
      
        $("#globe-loader").show();
    });
    $rootScope.$on("$translateChangeEnd",function(){
        $("#globe-loader").hide();
       
    })
```

Any help would be appreciated. Thanks !

### Enviroment
* Latest version
* 1.3.4
* ALL

**Comment by knalli** [comment]
Please have a look at our documentation: https://angular-translate.github.io/docs/#/guide/12_asynchronous-loading

**Comment by hani647** [comment]
grrrr. I've already gone through your documentation and also tried using different events but still the same result :`( . Any suggestions?

**Comment by hani647** [comment]
Well I might guess it's an angular bug !!

**Comment by knalli** [comment]
This issue (FOUC) is well known and can be handled with either `ng-cloak` or `translate-cloak`which both are handled in our documentation.
