### ISSUE TITLE
Unit test to test for missing strings

### ISSUE THREAD

**Issue by cdloh** [angular-translate/angular-translate#1767]
Bit of a stretch but I was wondering if anybody has been able to find a nice way to unit test their front end code to locate strings / parts of the code that don't have translations?

I'd imagine that it'd be nigh impossible but worth a shot asking.

**Comment by dmitryevseev** [comment]
I would try to introduce a custom error handler for the test which make it to fail if no translation found:
https://angular-translate.github.io/docs/#/guide/17_custom-error-handler

**Comment by knalli** [comment]
Yeah, the approach of @dmitryevseev is a useful approach. For example, you could check for zero results of the error handler or something similar one.
