### ISSUE TITLE
Translate refresh causes "No language key specified for loading" error when preffered language is not specified

### ISSUE THREAD

**Issue by MykhailoKyrychenko** [angular-translate/angular-translate#1769]
### Subject of the issue
When changing translate language, console error with message "No language key specified for loading" is present. In my research I found out that the problem is caused by [this line of code](https://github.com/angular-translate/angular-translate/blob/c7e743bb54b18f404e7ab5b91b88f842f144bbae/src/service/translate.js#L1132) when preferred language is not set: on attempt to refresh translations it simply adds undefined to the $fallbackLanguage array. It looks like either consummers of $fallbackLanguage array should check if array element is not null or undefined or this part of code should not put undefined into array.

I know that this issue can be avoided if preffered language is set, but we do not use preffered language in our set-up since it causes another problem in our code (translations in ui are refreshed only from the second attempt).

### Environment
* angular-translate v2.15.2
* angular v1.6.5

### Steps to reproduce
1. Set fallback language in translate configuration and do not set preffered language.
2. Load application (with fallback language loaded on init)
3. Change language to another one using `translateService` `use` method
4. Refresh translations using `translateService` `refresh` method

### Expected behaviour
All translations changed to newly set language without any console errors.

### Actual behaviour
All translations changed to newly set language with console error "No language key specified for loading".

**Comment by knalli** [comment]
How should be the translating work if there is no technical fallback default (aka  preferred) defined?

**Comment by MykhailoKyrychenko** [comment]
We have fallback language set by default

**Comment by knalli** [comment]
Can you please share a minimal working demo?

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
