### ISSUE TITLE
translateLanguage directive is not working together with asynchronous language loading by static files loader when translation files are big enough

### ISSUE THREAD

**Issue by dmitryevseev** [angular-translate/angular-translate#1770]
### Subject of the issue

`translateLanguage` directive is not working, when used together with asynchronous language loading by static files loader, in the case when translation files are big enough

### Your environment
* version of angular-translate: 2.15.2
* version of angular: 1.5.11
* which browser and its version: Chrome 60.0.3112.90

### Steps to reproduce
See the [plunker](https://plnkr.co/edit/Jye5sQwjiurhlc4tb9NC?p=preview)

App is set to load languages from the static files with the default language `en`.

To the body added an element needing a translation in another language, under the element with `translate-language="de"` attribute.

When language files are taking longer to load (there is a race condition), the text under `translate-language="de"` is not translated – the translation key is shown instead.

### Expected behaviour
After the translation file was loaded, the actual translations are displayed.

### Actual behaviour
Elements under `translate-language="de"` are not translated into any language

### Note
1. There is a race condition, rarely you can see plunker working as expected, restart it then to start over.
2. When I tried to create a simpler plunker with the tiny translation files, all was working as expected.

**Comment by knalli** [comment]
Sorry for the delay. Overseen this here.

As everything is event based here, we should see this issue also when using a custom loader with a explicit deferred load (`setTimeout`). Can you provide a demo with this?

In the tests we are using such custom loader with different timings as well: https://github.com/angular-translate/angular-translate/blob/c7e743bb54b18f404e7ab5b91b88f842f144bbae/test/unit/service/translate.spec.js#L648-L696

Basics: The promise resolve will be deferred with a specific amount of time.

**Comment by knalli** [comment]
Fix in canary.
