### ISSUE TITLE
Angular-translate not working inside angular services

### ISSUE THREAD

**Issue by samguergen** [angular-translate/angular-translate#1771]
### Subject of the issue
The angular-translate service only works in controllers and views, but not inside other services

**Comment by dmitryevseev** [comment]
@samguergen I'm sure I used it inside the service, could you share some code?
Plunker with the issue would be perfect

**Comment by knalli** [comment]
.@samguergen as everything is a service finally (except a filter function maybe), that is simply not true :)

But on topic. 

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/.github/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
