### ISSUE TITLE
$translate.instant not working on page refresh

### ISSUE THREAD

**Issue by renilbabu03** [angular-translate/angular-translate#1772]
var PLEASESELECT = $translate.instant('PLEASESELECT');

I have written this in the controller. It works fine during the first load but when i refresh the page the output is showing PLEASESELECT and not its translation . I think the problem is with the aysncronisation of the instant method.

**Comment by knalli** [comment]
Yeah, you are right.

Please have a look at our documentation, especially our guide at https://angular-translate.github.io/docs/#/guide

In that case I recommend also https://angular-translate.github.io/docs/#/guide/04_using-translate-filter
