### ISSUE TITLE
importing pascalprecht.translate with webpack

### ISSUE THREAD

**Issue by elsticky** [angular-translate/angular-translate#1773]
I currently have the following imports in my index.js .

```
import angular from 'angular';
import ngAnimate from 'angular-animate';
import ngCookies from 'angular-cookies';
import ngSanitize from 'angular-sanitize';
import ngMessages from 'angular-messages';
import ngResource from 'angular-resource';
import ngRoute from 'angular-route';
import uiBootstrap from  'angular-bootstrap';
import uiRouter from 'angular-ui-router';
import ngDragDrop from 'angular-dragdrop';
import 'angular-translate';
import 'angular-translate-loader-static-files';
import 'angular-translate-once';

const requires = [
        'pascalprecht.translate',
]
```

When loading my page I get the following error:

> Error: [$injector:modulerr] Failed to instantiate module pascalprecht.translate due to:
> Error: [$injector:nomod] Module 'pascalprecht.translate' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
> http://errors.angularjs.org/1.6.6/$injector/nomod?p0=pascalprecht.translate
> 

I think the import statement is correct but maybe something else is missing. Any suggestions?

**Comment by thomasthiebaud** [comment]
I'm facing the same problem right now. Did you find a solution ?

**Comment by knalli** [comment]
Because the libraries do not specify the requirement (there are no modules), the correct order is important. Therefor, this looks ok.

Given the error message, I cannot say more without details.

Maybe the error "module not available" is produced by your own code because of a missing/too late dependency requirement on the module `pascalprecht.translate`.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
