### ISSUE TITLE
Why angular-translate-loader-url.js v2.7.2 uses a .success and .error as they are depreciated?

### ISSUE THREAD

**Issue by muzammil90** [angular-translate/angular-translate#1774]
angular-translate-loader-url.js uses .seccess and .error in its http call which causes an error. Is it a bug or I am doing some thing wrong. I have update these to "then" and error removed and everything works fine.

**Comment by knalli** [comment]
Because this was "okay" as release 2.7.2 has been published.
You should consider using a more recent version which includes [this already](e7516dcc070a75d5d2da0ba912c6c64a03f8aafb). It must be karma, but it already in 2.8, although I would recommend the latest 2.15.x
