### ISSUE TITLE
Translate does not work with useStaticFilesLoader

### ISSUE THREAD

**Issue by marcdepelteau** [angular-translate/angular-translate#1777]
### Subject of the issue
I am experiencing the same issue as seen in this thread: https://github.com/angular-translate/angular-translate/issues/606

FYI: Everything works perfectly fine when I use the following, instead of the Static Files Loader:

```
$translateProvider.translations('en', {
    "HELLO": "Hello",
    "LANGUAGE": "Language"
}).translations('fr', {
    "HELLO": "Allo",
    "LANGUAGE": "Langue"
});
```

### Steps to reproduce
Here is a Plunker of what I have [link to demo](https://plnkr.co/edit/dapw0YYB1qlXwhbclDco?p=preview)

The only difference is the prefix path at the config level since I have a folder named 'translations' located in the same folder as my config file.

In other words

-parent folder
     -config file
     - translations folder
          - translation_en.json
          - translation_fr.json
```
app.config(['$translateProvider', function ($translateProvider) {

        $translateProvider.useStaticFilesLoader({
            prefix: './translations/translation_',
            suffix: '.json'
        });
$translateProvider.preferredLanguage('en');
        $translateProvider.useSanitizeValueStrategy('escape');
    }]);
```
I also have those in my Html:

```
<script type="text/javascript" src="./Scripts/angular-resource.min.js"></script>
<script type="text/javascript" src="./Scripts/angular-translate.js"></script>
<script type="text/javascript" src="./Scripts/angular-translate-loader-static-files.js"></script>

...

<select ng-options="language | translate for language in languages" ng-model="language" ng-change="updateLanguage()">
</select>
```

### Expected behaviour
I expect the message to change according to the selected language.

### Actual behaviour
I see the name of the Key.

**Comment by SimonSimCity** [comment]
@marcdepelteau Please take again a look at your demo and also include the results you see in the browsers console.

Your demo is trying to load a file from `https://cdnjs.cloudflare.com/ajax/libs/angular-translate/2.15.2/angular-translate-loader-static-files.js`, which doesn't exist. You have to change this path in your script-tag to `https://cdnjs.cloudflare.com/ajax/libs/angular-translate-loader-static-files/2.15.2/angular-translate-loader-static-files.js` and it will work.

**Comment by marcdepelteau** [comment]
@SimonSimCity Thanks Simon! The example does work now, but when I upload all the files to a folder in SharePoint, it does not work!

**Comment by SimonSimCity** [comment]
@marcdepelteau As I said ... please check out your browsers console and work yourself up from there. If you want, I can assist you in that, provided you first do all you know, keep struggling until you don't know more. Tell me everything you've done and we continue from there on.
