### ISSUE TITLE
Demo missing for ng-repeat

### ISSUE THREAD

**Issue by leolux** [angular-translate/angular-translate#1778]
Is there any demo for a translation of a dynamic translationId derived from a variable inside ng-repeat.

```
<div ng-repeat="item in items">
      <span translate="????item.dynamicTranslationId????"></span>
</div>
```

**Comment by knalli** [comment]
The value of element's attribute `translate` is a string (otherwise you would have to write `<span translate="'translationId'"></span>` always). Maybe use AJS interpolation (`<span translate="{{item.dynamicTranslationId}}"></span>`) or use a dedicate component (and calling the service).

**Comment by leolux** [comment]
Thank you very much! I am going to implement a dedicated component because I think that components are more clean and flexible.

**Comment by knalli** [comment]
But remember to use the events so you get translation language changes correctly.
