### ISSUE TITLE
AngularJS asynchronous json messages browser header page title shows untranslated key and then takes time to display actual value

### ISSUE THREAD

**Issue by kpat143** [angular-translate/angular-translate#1779]
### Subject of the issue
I'm using $translateProvider with default language 'en' although body content key values load fine, the browser header page title is not resolving quickly and shows untranslated key as title first and after few seconds the actual value of the key loads. Please let me know if there's a solution for this issue/bug.

### Your environment
AngularJS 1.x
Chrome and Edge

### Steps to reproduce
Load the json key value pairs data using the below code: 
$translateProvider.useStaticFilesLoader(mention prefix and suffix details here);
$translateProvider.preferredLanguage('en');

### Expected behaviour
The browser header title also should have shown the translated value similar to page body.

### Actual behaviour
The browser page title shows the untranslated key page.home.title and then after few seconds shows the actual value "My home page".
<title translate>page.home.title</title>

**Comment by uguurozkan** [comment]
I just found something useful. If you add `translate-cloaked`, key doesn't show up.
`<title translate-cloaked translate="APP.TITLE"></title>`

**Comment by kpat143** [comment]
Thank you.
