### ISSUE TITLE
Warning when adding keys that are already registered

### ISSUE THREAD

**Issue by stnor** [angular-translate/angular-translate#1780]
### Subject of the issue
As a developer I'd like to know if I have duplicate keys in my translation files.

### Steps to reproduce
https://plnkr.co/edit/OagTzPaRwIbBQDavcGYP?p=preview

### Expected behaviour
I would like to see a warning being logged if my second call to $translateProvider.translations() contains keys already registered.

### Actual behaviour
There is no warning, and the last call to $translateProvider.translations() overwrites the previous ones.

**Comment by stnor** [comment]
Something like this added to pascalprecht.translate.$translateProvider#translations should work:

`      for (var key in translationTable) {
        if ($translationTable[langKey][key]) {
          console.warn('pascalprecht.translate.$translateProvider: Duplicate translation key \'' + key + '\' [' + langKey + ']');
        }
      }
`

**Comment by knalli** [comment]
Maybe I am missing something.. but a map does not contain duplicate entries by specification. Or in other words: Any duplicate entry will be sorted out by the parser engine (i.e. Browser).

**Comment by stnor** [comment]
Yes, of course but if I have multiple translation files and accidentally overwrite a value already registered I've like to know about it.

**Comment by stnor** [comment]
Fair point.
