### ISSUE TITLE
Angular translate static files loader doesn't load json files in IONIC Android

### ISSUE THREAD

**Issue by phuwin** [angular-translate/angular-translate#1787]
My ionic app is using Angular Translate. It works very fine on the web using `ionic serve`. But when I build it to Android, I use chrome inspector to check the network requests, the json file isn’t loaded and no error is shown. 
I have checked an earlier question, my prefix doesn’t have `/` at the beginning.
I put a breakpoint in the `angular-translate-loader-static-files.js` and it doesn't stop there in runtime in Android (but it does in web browser)

    $translateProvider.useStaticFilesLoader({
        prefix: 'js/locales/',
        suffix: '.json'
    })
    //locales is a string type variable e.g "fi","en"
    $translateProvider.preferredLanguage(locale).fallbackLanguage('en').useSanitizeValueStrategy('escapeParameters');         

My directory structure

    —-www
    ------js
    ---------locales
    -----------en.json
    -----------fi.json

**Comment by knalli** [comment]
This is a plugin for AJS, a web developing framework using basic technologies like JS, HTML and maybe CSS. 

It is a common issue in Cordova apps, that developers do not understand the different modes. [See more at Ionic's blog](http://blog.ionic.io/handling-cors-issues-in-ionic/).

You are pointing out it is working in {{ionic serve}}. If it is not working in the other mode (like in a native app), it is not an issue with angular-translate, but with remote requests ("XHR") in the background in general (i.e. CORS).

So you will reproduce this issue with any "local" file loaded with standard XHR techniques.

Please use more appropriate boards like StackOverflow.
