### ISSUE TITLE
Case in available language keys is handled inconsistantly.

### ISSUE THREAD

**Issue by jjabba** [angular-translate/angular-translate#1788]
### Letter case in available language keys is sometimes ignored, behaviour is inconsistant.
When registering 'avaliable languages' such as (en_UK, de_DE) the letter case of the language returned when language is negotiated is inconsistant. It's sometimes en_UK, sometimes en_uk, depending on the way a match is found. 

### Your environment
* angular-translate - v2.15.2 - 2017-06-22
* AngularJS v1.6.6
* all browsers/environments

### Steps to reproduce
Run the testcase supplied in pull request https://github.com/angular-translate/angular-translate/pull/1783 or look at this plunker https://plnkr.co/edit/5Eu5Qu0EXlBGd0ecigPg?p=preview

### Expected behaviour
The language returned from $translate.use() should respect casing used when registering avaliable languages.

### Actual behaviour
Depending on how matching is done in internal function 'negotiateLocale(preferred)', sometimes the letter case is respected, but sometimes not.

### Fix
I've implemented a solution in pull request https://github.com/angular-translate/angular-translate/pull/1784 which passes the test in pull request https://github.com/angular-translate/angular-translate/pull/1783 and makes the returned language always respect case used when registering avaliable languages.

### Why?!
The importance for this fix is more obvious if ngTranslate is used with the **angular-translate-loader-static-files** loader. Since the key/identifyer/language resolved by negotiateLocale() is used to determine which fileUrl is loaded, loading translations will fail if the server hosting the translations is case sensitive. This was how I originally found this bug.

**Comment by knalli** [comment]
@jjabba  Thank you for all the great PRs! 🏎 

I will have a look asap.

**Comment by jjabba** [comment]
@knalli Thanks for an awesome module, glad to try and make it even more awesome, my product is dependent on it.

**Comment by knalli** [comment]
Thank you very much for these contributions. Same as in #1789 :)
