### ISSUE TITLE
Wildcards in language map uses case sensitive matching. 

### ISSUE THREAD

**Issue by jjabba** [angular-translate/angular-translate#1789]
### Wildcards in avaliable languages are case sensitive, while non-wildcard entries are not.
When providing a language map with wildcard patterns (en_\*, de_\*) the part of the wildcard used for matching with avaliable languages is case sensitive. But for non-wildcard entries, the matching is (confusingly) case insensitive.

### Your environment
angular-translate - v2.15.2 - 2017-06-22
AngularJS v1.6.6
all browsers/environments

### Steps to reproduce

Run the testcase supplied in pull request https://github.com/angular-translate/angular-translate/pull/1785

### Expected behaviour
The language map wildcards should match detected language in a case insensitive manner. ie. en_* should match with en_US, En_US, eN_US and EN_US. 

### Actual behaviour
Wildcard map entries are matched case sensitive, which means the map needs alot of redundant entries to cover all (unfortunately valid) variations of casing.  

### Fix
I've implemented a solution in pull request https://github.com/angular-translate/angular-translate/pull/1786 which passes the test in pull request  https://github.com/angular-translate/angular-translate/pull/1785 making it less cumbersome to cover different casings when using wildcards in the language map.

### Why?!
I have translation for my app in two files, one for en_US, and one for de_DE. Anyone who wants english translations or german translations should use this these translations regardsless of their territory. Unfortunately, because of the many possible conventions used by different browsers, my map therefore has to include alot of redundant entries.
```javascript
registerAvailableLanguageKeys(['en_US', 'de_DE'], {
    'en': 'en_US', // wildcard not needed as this is global default (last line in map).
    'de': 'de_DE', 'de_*': 'de_DE', 'dE_*': 'de_DE', 'De_*': 'de_DE', 'DE_*': 'de_DE',
    // ultimate catch all fallback if requested language is not detected.
    '*' : 'en_US'
});

**Comment by knalli** [comment]
@jjabba  Thank you very much for these contributions.
It is very helpful splitting the different things in different pull requests, I welcome this 👍 

Both landed right now in `canary` and will be available the next release.

(But there is no need for separating the change and the corresponding test -- unless something else  or technically required.)

**Comment by jjabba** [comment]
@knalli Thanks for the quick pr-processing! I'll bundle fixes and tests in the future.
