### ISSUE TITLE
$translateProvider.useStaticFilesLoader with external source

### ISSUE THREAD

**Issue by iliasadfenix** [angular-translate/angular-translate#1791]
I was trying to use useStaticFilesLoader with external source.

`$translateProvider.useStaticFilesLoader({
  prefix: 'http://localhost:3001/i18n/',
  suffix: '.json'
}); `

Source json is downloading correctly from location Ex- http://localhost:3001/i18n/sw.json. But language translation is not working.

Here is how I am using it.

`<h2 class="ops" data-translate="ERROR_IMAGE_AREA_SELECT_MULTIPLE _SELECTION"></h2>`

**Comment by knalli** [comment]
Are you sure the request is done? Because you must be aware of [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS).

**Comment by iliasadfenix** [comment]
yes. It showing result on network tab as expected.

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/.github/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by knalli** [comment]
Well, the thing is: This works, this is definitely a non angular-translate specific issue. I would say, it is even non related to AngularJS.

Do you have tried `translate` instead of `data-translate`?

But we need more information.

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/.github/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
