### ISSUE TITLE
error[$injector:unpr] Unknown provider: $translateMissingTranslationHandlerLogProvider <- 

### ISSUE THREAD

**Issue by zishon89us** [angular-translate/angular-translate#1792]
### Error
[$injector:unpr] Unknown provider: $translateMissingTranslationHandlerLogProvider <- $translateMissingTranslationHandlerLog http://errors.angularjs.org/1.6.3/$injector/unpr?p0=%24translateMissingTranslationHandlerLogProvider%20%3C-%20%24translateMissingTranslationHandlerLog

### Environment
* "angular-translate": "^2.15.2"
* "angular": "~1.6.0"
* "angular-translate-loader-static-files": "^2.15.2"

### Required
I need to understand the possibilities of the error because `angular-translate` and `angular-translate-loader-static-files` both are bowered before `grunt build` and it runs smoothly on my local machine but on staging it is throwing this error.

### Update1
After applying `translate-cloak` translation keys flicker is gone and app is working smoothly **BUT it throws the same error mentioned above when run as `grunt server:dist`**

**Any suggested fix?**

**Comment by zishon89us** [comment]
https://stackoverflow.com/questions/46695028/errorinjectorunpr-unknown-provider-translatemissingtranslationhandlerlogpr

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/.github/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by knalli** [comment]
Thank you for using STO instead. Answer is available there for the record.
