### ISSUE TITLE
Catch words which is not translated.

### ISSUE THREAD

**Issue by CrackerakiUA** [angular-translate/angular-translate#1795]
When we filtering word, if that word existing, we get the translation, if not we get the key. How can we catch the scenario when key is returned?

**Comment by CrackerakiUA** [comment]
I have looked at your code, added modifications which helps me out. On the use side it's something like 
`$translate.failCallback(function(word){
	// Code
});` But i am not sure if i can make proper PR as you do coding or if you need this. I would like to have that.

**Comment by tommck** [comment]
You write a service to handle it:

    $translateProvider.useMissingTranslationHandler('missingTranslationService');

**Comment by CrackerakiUA** [comment]
ok, i will try

**Comment by knalli** [comment]
If you want to be notififed globally, use the already mentioned `$translateProvider.useMissingTranslationHandler('missingTranslationService')`. See [more here](https://angular-translate.github.io/docs/#/guide/17_custom-error-handler).

If you want to handle this locally, a filter is not appropriate. A directive have additional options for default/standard texts. See [more here](https://angular-translate.github.io/docs/#/api/pascalprecht.translate.directive:translate).
