### ISSUE TITLE
angular.lowercase will be deprecated in Angular.js 1.6.7 that it's close to be released

### ISSUE THREAD

**Issue by ManRueda** [angular-translate/angular-translate#1797]
### Subject of the issue
Angular-translate uses `angular.lowercase`, that is an internal method of angular and in the next version will be remove and make it internal.

https://github.com/angular/angular.js/commit/1daa4f2231a89ee88345689f001805ffffa9e7de#diff-1d54c5f722aebc473dbe96f836ddf974

Looks like they hide it behind `angular.$$lowercase`.

### Your environment
* version of angular-translate: 2.13.1
* version of angular: 1.6.7
* which browser and its version: Chrome 63

### Steps to reproduce
The code breaks as soon the app start, the function is no there anymore.

**Comment by knalli** [comment]
Thank you for this.

**Comment by knalli** [comment]
Maybe you want to make a PR with a replacement, maybe `toLowerCase`?

**Comment by ManRueda** [comment]
Sure, i don't know if it was using the angular one for some reason, but if native `toLowerCase` it's ok, i will send a PR.

**Comment by ManRueda** [comment]
I didn't  see the question about the version, looking the Angular.js branches and the pre-releses that are in Bower, the change will be in 1.6.7

**Comment by knalli** [comment]
PR picked
