### ISSUE TITLE
Problems with umlauts (special characters)

### ISSUE THREAD

**Issue by mnemotron** [angular-translate/angular-translate#1801]
Hi,

after the translation, umlauts / special characters are displayed as code.

Example:     EN: Change ---> Translated to ---> \&#196;ndern  (although maintained DE: Ändern)

What do I wrong?

**Comment by knalli** [comment]
This depends on the selected sanitization strategy. See this demo for the differences: http://plnkr.co/edit/rJ0R6GzHGbMVxhSa237C?p=preview

**Comment by knalli** [comment]
Also see documentation: https://angular-translate.github.io/docs/#/guide/19_security

**Comment by mnemotron** [comment]
Thanx for the advice.
