### ISSUE TITLE
Use Static Files Loader - Fallback solution when file is not existed

### ISSUE THREAD

**Issue by aleen42** [angular-translate/angular-translate#1808]
Recently, I have met a use case in which there can be custom files like `custom_locale-en.json` for loading, which will overwrite default locale files when it exists. However, when the file does not exist, angulat-translate does not work at all:

```js
$translateProvider.useStaticFilesLoader({
    files: [
        {
            prefix: 'locale-',
            suffix: '.json'
        }, {
            prefix: 'custom_locale-',
            suffix: '.json'
        }
    ]
});
```

Is there any fallback solution for this situation?

**Comment by aleen42** [comment]
I have a ugly solution, where I can run code above after an attempt to detect whether files are existed before. It's ugly because it results in two network requests for one same file. Can I solve this problem with other solutions?

**Comment by knalli** [comment]
I guess you are wondering about a feature like an optional resource. No, that’s not supported. 

You can just copy the small loader and implement your own logic.

**Comment by aleen42** [comment]
Is there any tutorial about how to re-implement a loader like `useStaticFilesLoader`

**Comment by knalli** [comment]
Documentation has a chapter about custom loaders, but more or less~ they are a function only. See the existing ones.

**Comment by aleen42** [comment]
👌  I will check the source code directly

**Comment by aleen42** [comment]
I have created a custom loader like the following snipppet, but I found that the first rendered page will not get the corresponding translated item, and how can I work around this problem?

```js
app.factory('useExistentStaticFilesLoader', function ($http, $q) {
    return function (options) {
        var deferred = $q.defer();
        var localeObject = {};
        var count = 0;
        var recursiveRequest = function () {
            var item = options.files[count++];
            if (!item) {
                deferred.resolve(localeObject);
                return;
            }

            $http.get(item.prefix + options.key + item.suffix).then(function (result) {
                angular.merge(localeObject, result.data);
                recursiveRequest();
            }).catch(function () {
                deferred.resolve(localeObject);
            });
        };

        recursiveRequest();

        return deferred.promise;
    };
});
```

**Comment by knalli** [comment]
I don't think this is an issue with angular-translate. Hint: maybe another target/audience is better ;)

1: I would change the code running without any side-effect; also that is better when working with asynchronous recursive calls (and callbacks).

2: Moreover, I would replace the explicit calls with implizit promise resolvings.

Blueprint: see here as standard implementation (non AJS): http://plnkr.co/edit/mHhtRIrcG7TIeAKzFhdo?p=preview

If you have with a working concept implementation (no issues with unresolved promises or rejected promises), please ping me again.
