### ISSUE TITLE
Custom languageTagResolver or fix bcp47 resolver

### ISSUE THREAD

**Issue by tenjaa** [angular-translate/angular-translate#1811]
### Subject of the issue
We have a bcp47 conform language tag, that includes a specific script.
When using 'bcp47' as languageTagResolver I dont get the expected locale.

The reason for this can be found in https://github.com/angular-translate/angular-translate/blob/master/src/service/translate.js line 56.

So it is not an unspotted bug, the implementation is simply different than I expected it to be.

Is there a way to adapt the bcp47 language key?
Or add another one like "bcp47withScript"?
Or can I pass my custom languageTagResolverFunction?

One possible solution would be to just revert all the changes from the languageTagResolver.
But I dont like that because we would do the same work twice.

Another option that would make it a bit better would be a no-op languageTagResolver?

### Your environment
* latest version of angular-translate
* every browser

### Steps to reproduce
config:

    $translateProvider
    .uniformLanguageTag('bcp47')
    .determinePreferredLanguage(function() {
        var key = $translateProvider.resolveClientLocale();

        // try to find perfect match
        for (var i = 0; i < languages.length; i++) {
            if (languages[i].code.localeCompare(key) === 0) {
                return key;
            }
        }

        // try to find a language only match
        var languageOnly = key.substr(0, 2);
        for (var i = 0; i < languages.length; i++) {
            if (languages[i].code.localeCompare(languageOnly) === 0) {
                return languageOnly;
            }
        }

        // default
        return 'en';
    })

code:
`$translate.use('sr-Latn')`

### Expected behaviour
I want the returned language key to be 'sr-Latn'.

### Actual behaviour
The returned language key is 'sr-laTN' and does not get found.

**Comment by tenjaa** [comment]
Some ideas come when writing it properly down...

I can probably just say
`$translateProvider.uniformLanguageTag(undefined or 'no-op')`
and when getting the locale angular translate won't find this resolver and ignores it if I see it right?

**Comment by knalli** [comment]
Should it not return `sr-LATN` (everything uppercase)?

And yes: It's look like a bug, because I had thought the second part must be uppercase always (like `en-GB` or `de-DE`). Maybe you want to make a PR?

> Or can I pass my custom languageTagResolverFunction
At the moment, there is no option for adding custom languageTagResolvers. Again: PR is welcome, as part of the `$translateProvider`.

> Or can I pass my custom languageTagResolverFunction?
Not directly, but you can provide a custom implementation for `$translateProvider. determinePreferredLanguage(customFn)`. In your case, that's the only extension point you have atm.

> `$translateProvider.uniformLanguageTag(undefined or 'no-op')`
I think an additional `none` could be useful. PR is welcome ;)

Note: languageTagResolver will be used only if `determinePreferredLanguage` is not called with a custom resolver function.

**Comment by tenjaa** [comment]
> Should it not return sr-LATN (everything uppercase)?

Possible yes. I'm only sure it is not sr-Latn (the expected one) but I will check tomorrow.

> And yes: It's look like a bug, because I had thought the second part must be uppercase always (like en-GB or de-DE).

The second part can also be the script, which consists of four letters, first uppercase followed by three lowercase.
For reference:
https://tools.ietf.org/html/bcp47#section-2.2.3
https://www.unicode.org/iso15924/codelists.html

>>`$translateProvider.uniformLanguageTag(undefined or 'no-op')`

> I think an additional none could be useful.

Isn't using undefined kind of a no-op?

    var locale = getFirstBrowserLanguage() || '';
    if (languageTagResolver[uniformLanguageTagResolver]) {
      locale = languageTagResolver[uniformLanguageTagResolver](locale);
    }
    return locale;

If the uniformLanguageTagResolver is unknown (=> NOT default, bcp47, java or iso6931) it should not execute its function, right?

> Note: languageTagResolver will be used only if determinePreferredLanguage is not called with a custom resolver function.

Not in our case, as we call $translateProvider.resolveClientLocale() manually

**Comment by knalli** [comment]
> Isn't using undefined kind of a no-op?

Right. That's what you requested. `undefined` is the noop.

**Comment by tenjaa** [comment]
Thanks for accepting the pull request :)
This can be closed now.
