### ISSUE TITLE
translate in a customFilter in combination with CustomLoader

### ISSUE THREAD

**Issue by MisterEd0105** [angular-translate/angular-translate#1812]
### Subject of the issue
If you use 
`return $filter('translate')(value);`
within a filter everything is fine until you define a customLoader for $translateProvider.

### Your environment
* version of angular-translate 
plunker is with v2.16.0 but you can probably reproduce this issue with any other version

* version of angular
plunker is with v1.6.6 but you can probably reproduce this issue with any other version

* which browser and its version
chrome 62.0.3202.94
firefox 56.0.1

### Steps to reproduce
See this plunker [plunker](https://embed.plnkr.co/IhsnrUxLVzlLoJQH3eo2/)

### Expected behaviour
i expect that the translated string would be displayed after timeout

### Actual behaviour
the key isn`t replaced with the translation

**Comment by knalli** [comment]
This behaviour is not a bug. A filter must return data directly and cannot wait. Therefor the filter have to called again.

If you use the filter within templates, AngularJS will do this for you.

But if you call the filter explictly (outside of a template), then the same rules will apply as using `$translate.instant()`.
