### ISSUE TITLE
Is it possible to link translation ids as a part of another translation

### ISSUE THREAD

**Issue by crhistianramirez** [angular-translate/angular-translate#1814]
### link translation id's to partials

I have several translations on which part of their text relies on another translation.
In a configuration file for example I might have something like:

```
{
    "PAYMENT_TYPES": {
        "PURCHASE_ORDER": "Purchase Order",
        "CREDIT_CARD": "Credit Card",
        "SPENDING_ACCOUNT": "Spending Account"
    }
}
```

and then somewhere else in my file I'd like to like to do this:

```
{
    "CREDIT_CARD": {
        "CREATE_NEW": "Create a new @:PAYMENT_TYPES.CREDIT_CARD"
    }
}
```
so that `CREDIT_CARD.CREATE_NEW` generates "Create a new Credit Card"

Is that possible?

**Comment by knalli** [comment]
Currently, this is supported as full-alias only.

You have two options I would say:
1. Make a contribution which will add such a feature. We are welcome this!
2. Create your own tooling in frontend of producing the data files for angular-translate (ala preprocessing)
