### ISSUE TITLE
translate is not working for hyperlinks <a> and ng-click

### ISSUE THREAD

**Issue by maxfremars** [angular-translate/angular-translate#1818]
### Subject of the issue
Describe your issue here.

I tried to implement angular-translate into an hyperlink and it is translating correctly, but ng-click doesn't work anymore.

Code example:

```
<li class="nav-item mr-sm-1" ng-class="{active:tab === 1}" style="width: 30%">
                    <a class="nav-link bg-blue brd-top-5"
                       href=""
                       ng-click="tab=1"
                       onmouseover="this.style.color='#333D47'"
                       onmouseout="this.style.color='#F8F8F8'"
                       translate>TEST</a>
</li>
```

ng-click should set tab variable to 1 but this does never happen. If im disabling angular-translate, it works perfect.

Im not sture if it has something to do with angular-translate or ng-click

### Your environment
* version of angular-translate

latest

* version of angular

latest

* which browser and its version

latest safari browser, doesn't even work in firefox

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://plnkr.co/edit/XorWgI?p=preview) as a base.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by knalli** [comment]
Sometimes, there are scope clashes in AJS applications. Sometimes we win, sometimes the others. Maybe today a problem with angular-translate, tomorrow in something else's directive.

You have the following options
* Change the directive priority https://angular-translate.github.io/docs/#/api/pascalprecht.translate.$translateProvider#methods_directivepriority
* use two different tags
* replace with translate filter
