### ISSUE TITLE
angular translate partial loader - $translatePartialLoader.setPart is not a function

### ISSUE THREAD

**Issue by mmanista** [angular-translate/angular-translate#1819]
### Subject of the issue
I have an issue with setPart method of the angular-translate-partial-loader service. It just simply can't find this method.
I have checked available methods of the service (see plunker) and it returned few methods, but the setPart one is missing.
Tested the other methods, they work as expected.

### Your environment
* version of angular-translate: 2.17.0
* version of angular-translate-partial-loader: 2.17.0
* version of angular: 1.5.0
* which browser and its version: Chrome 63.0.3239.132

### Steps to reproduce
Plunker with reproduced error: [plunker](https://plnkr.co/edit/w4bjVPAkCrtydCbhfbNE?p=preview) - check the console for details

### Expected behaviour
It should set a new part of translations

### Actual behaviour
The method is not found, so an error is thrown and I cannot set any new parts

Apologize if the way I have described it is not how it should look like, but it is just my first time ;)

**Comment by mmanista** [comment]
Just realised that the provider has this method and the service doesnt (yet). Not sure if it's intentional (not developed yet). Please feel free to close it if it has not been developed yet or something

**Comment by knalli** [comment]
The partial loader does not need this method. It is loading the data itself, because it *is* a loader. That is the reason why `$translatePartialLoader.addPart` also is not loading, but only hinting for a later loading.
