### ISSUE TITLE
Problem in Select Option

### ISSUE THREAD

**Issue by stelioschar** [angular-translate/angular-translate#182]
Hello to all,

I use the code below for a <select> <option> and just prints the default(in my case english) translation

``` html
<select name="searchLevel" class="select" ng-model="searchLevel" ng-change="updateLevelMenu(searchLevel)" ng-options="level.id as level.name for level in levels | filter:dropDownLevels">
   <option value="">{{ 'mainScreen.chooseLocation' | translate | doUppercase }}</option>
</select>
```

and right after this <select> I print

``` javascript
{{ 'mainScreen.chooseLocation' | translate | doUppercase }}
```

and brings the proper translation.

Is there any suggestion on this?

Thank you

**Comment by JMDidon** [comment]
I have a similar problem using the last version (e.g 2.6.1).

When using the translate filter on the first option of a select with a ng-options directive, the option remains empty (the key is not displayed).
The other contents are correctly translated.

**Comment by knalli** [comment]
@JMDidon  Please create a new issue and append a demo for this case.
