### ISSUE TITLE
Angular-translate cannot use local storage

### ISSUE THREAD

**Issue by ridvansumset** [angular-translate/angular-translate#1820]
Hi, I am using angular-translate with angular-local-storage. 

#### main.js:
```
$scope.localStorage = $localStorage;

$scope.changeLanguage = function() {
    $translate.use($scope.localStorage.lang_key);
};
```

#### ui-select-box:
```
<ui-select ng-model="localStorage.lang_key" ng-init="localStorage.lang_key" ng-change="changeLanguage()">
          <ui-select-match>{{$select.selected}}</ui-select-match>
          <ui-select-choices repeat="language in ['tr','en']">
            <div ng-bind-html="language | highlight: $select.search"></div>
          </ui-select-choices>
</ui-select>
```

#### My config file:
```.config(['$translateProvider',function ($translateProvider) {
  $translateProvider
  .useLocalStorage()
  .useStaticFilesLoader({
    files: [{
        prefix: 'js/locales/',
        suffix: '.json'
    }]
  })
  .registerAvailableLanguageKeys(['en', 'tr'], {
    'en_*': 'en',
    'tr*': 'tr'
  })
  .determinePreferredLanguage()
  .useSanitizeValueStrategy('sanitize');
}])
```

#### bower.json:
```
    "angular-local-storage": "0.1.5",
    "angular-translate": "^2.15.1",
    "angular-translate-loader-static-files": "^2.15.1",
    "angular-translate-storage-cookie": "2.15.1",
    "angular-translate-storage-local": "2.15.1"
```
#### My problem: the language select box is in empty state.

Even though I have `.useLocalStorage()` and `.determinePreferredLanguage()` functions, there isn't ngStorage-lang_key property under storage -> local storage tab in developer's console. 
After I select a language from the select box (lets say "tr"), the ngStorage-lang_key property initializes with `"tr"`. By this way, my language select box has the value "tr" which is in empty state before. 

So, how can I have the preferred language on page load and store it to the local storage to have my select box filled with that value?

Note: Sorry if it's too complicated.

**Comment by knalli** [comment]
Well, you should not relay on the existence nor the data value of this key. The key is maintained by angular-translate, not any 3rd party code.

For your case: Use `. getAvailableLanguageKeys ()` (list of available keys) and `.use()` (current key).
