### ISSUE TITLE
language not correctly showing on html

### ISSUE THREAD

**Issue by ShankzPatil** [angular-translate/angular-translate#1824]
### Subject of the issue
**language not correctly showing on html**
Language: gu_IN
& #2738;& #2761;& #2711;& #2751;& #2728;

please remove spaces between & and #.
because not able to show you exact issue.

### Your environment
* version of angular-translate - **Latest**
* version of angular - **1.6**
* which browser and its version - **Chrome latest, safari iOS 11 and IE 11**

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://plnkr.co/edit/XorWgI?p=preview) as a base.

### Expected behaviour
Tell us what should happen
text gu_IN : 
& #2738;& #2761;& #2711;& #2751;& #2728;

expected to show like લૉગિન

### Actual behaviour
Tell us what happens instead

**Comment by ShankzPatil** [comment]
i found that after applying sanitization
        $translateProvider.useSanitizeValueStrategy('sanitize');

now i added strategy null working fine.
        $translateProvider.useSanitizeValueStrategy(null);

please suggest.

**Comment by knalli** [comment]
@ShankzPatil  Interesting local you have.

Could you maybe explore issue #1101 a bit?  I have also added an overview + demo/hack see in https://github.com/angular-translate/angular-translate/issues/1101#issuecomment-315880432

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
