### ISSUE TITLE
Multi line interpolated keys don't work

### ISSUE THREAD

**Issue by tscheinecker** [angular-translate/angular-translate#1825]
### Multi line interpolated keys don't work
Angular supports interpolation regardless of the whitespace characters used. This includes new lines.

So for example

```html
{{ 2
+ 2
}}
```

is a completely valid interpolation expression. But angular-translate applies a custom regex to validate whether or not the element body is an interpolation expression which is not multi line compatible.

### Your environment
* angular-translate 2.17.0
* angular 1.6.8

### Steps to reproduce
Just add a newline within the interpolation body

```html
<div translate>{{
'not.working'
}}
</div>
```

See Plunkr: https://plnkr.co/edit/l2IpQCD1SGkmeSAf3X98?p=preview

### Expected behavior
Newlines should not have any effect on interpolation detection

### Actual behavior
Newlines prevent interpolations from being detected

**Comment by knalli** [comment]
I'm not sure what do you mean. We will not support multiline expressions. Maybe we should add an appreciate trim function for bugfixing?

**Comment by tscheinecker** [comment]
the problem is that it behaves differently from angularjs itself as explained above

```html
{{ 2
+ 2
}}
```
would correctly evaluate to `4` but when the same is applied within a `translate` directive it doesn't work.

i only checked the code briefly and found out that you just check the element text via a regex to decide whether or not an interpolation has to be performed or not.

just trimming / replacing the newlines is probably not a good solution as then a template like
```html
{
{ 'myKey'}}
```
would be detected as interpolation altough in angularjs core it wouldn't be

isn't there a way of just reusing angularjs core logic here instead of creating some kind of regex which tries to replicate something that angularjs does internally?

for example also mutli interpolations are not possible
```html
{{'prefix'}}{{'suffix'}}
```
(i also extended the plunkr)


Note that if you don't want to fix that this is of course your decision, but then at least update the documentation that this is NOT angularjs interpolation and there are unsupported usecases

**Comment by knalli** [comment]
The thing is: We are using the default interpolation feature by AngularJS -- but you can out-out/replace this. However, we do not have active support for multiline key values (translation ids containing new lines) which would go beyond any default usage. Said this, I would recommend using only simple keys -- without newlines. If this works, fine. But it is not intended. Translation ids are meant to be without newlines. Maybe that's worth for a discussion, however, not for this plugin any more.

Additionally, a directive with an interpolated text value is somehow special, too. The code in question is likely the check determining whether an additional interpolation is required (IMHO, an awkward and misplaced feature, but it is there, won't break features). If you can provide a fix which would help you and others, you are welcome. 👍

**Comment by tscheinecker** [comment]
i think we are still talking about 2 different things here.

i never wrote anything about newlines wihtin translation keys - where did you get that idea from?

please just have a look at the supplied plunkr and the issue should be more then obvious, i even updated it once more to show the issue in another scenario.

and just for reference: i know that i can use the translate pipe instead of the directive for example, or just ensuring all expressions are always single line, but as stated before it just behaves differently to regular angularjs interpolation.

i'm also aware that you using the angularjs interpolation feature, i was talking about the regular expression you use to decide whether or not interpolation is necessary that is broken, nut the interpolation itself.

**Comment by knalli** [comment]
Well, okay.

And my last sentence is still valid: 
> If you can provide a fix which would help you and others, you are welcome. 👍

I see the problem you have, however, it does not have been issued for years. Maybe we/you can fix/enhance the way of loading the correct payload: Feel free to contribute. 

I will close this -- either this will be handled within a contribution (hint, hint) or effectivly-wontfix.
