### ISSUE TITLE
Is it possible to get the original unflattened object using Angular translate?

### ISSUE THREAD

**Issue by kensplanet** [angular-translate/angular-translate#1827]
It seems Angular Translate flattens the entire object. I need the original unflattened object as it is used in some places in my code. Is it possible to somehow get this object?

**Comment by knalli** [comment]
@kensplanet No, as we see this as a translation library which is designed for translating text (string) with text (string) -- maybe parametrized. Therefor both plugins and internals are not expecting non-strings in general.
