### ISSUE TITLE
useStaticFilesLoader doesn't send any XHR to fetch JSON file

### ISSUE THREAD

**Issue by POPOEVER** [angular-translate/angular-translate#1829]
Works fine with $translateProvider.translations() way, but doesn't work with useStaticFIlesLoader()

### My environment
* version of angular-translate: 2.17.0
* version of angular: 1.4.7
* Chrome/Safari latest

### Steps to reproduce
My config code (config.js):
```
var langKey = window.navigator.language == 'zh-CN' ? 'cn' : 'en';
$translateProvider
	.useStaticFilesLoader({
		prefix: 'locale-',
		suffix: '.json'
	})
	.use(langKey);
	$translateProvider.useSanitizeValueStrategy('escape');
```

My JSON file (locale-cn.json):
```
{
	"CONTENT_EDITOR": "内容编辑器",
	"EDITOR_PLACEHOLDER": "信心满满滴开始吧......"
}
```

My HTML (editor.html):
```
<h1>{{ 'CONTENT_EDITOR' | translate }}</h1>

<script src="vendors/bower_components/angular/angular.min.js"></script>
<script src="vendors/bower_components/angular-translate/angular-translate.min.js"></script>
<script src="vendors/bower_components/angular-translate-loader-static-files/angular-translate-loader-static-files.min.js"></script>
```

### Expected behaviour
It should translate the 'CONTENT_EDITOR' into Chinese as '内容编辑器'

### Actual behaviour
Now it just shows the string 'CONTENT_EDITOR'

And, one more strange thing, I have to use $translateProvider.use(langKey) to make translation happen, even when using the $translateProvider.translations() way, using preferredLanguage() doesn't work.

I checked Network tab in console, no XHR called for JSON file, the file is at same directory with my HTML file, so does the config.js, and I'm using ui-router, I tried visiting the absolute path of JSON file from browser address bar, it shows the file correctly, so what's wrong with this?

P.S, I'm lazyloading the config.js, but also tried embedding it in HTML directly, both not loading the JSON

P.S, I tried forked your plukr and tested, it works fine, so it this an issue with my settings or my Angular version? It's a quite old project so it stays on 1.4.7 anyway.

**Comment by knalli** [comment]
You should determine the differences between your code and the plnkr's one. ;) You can manually downgrade the library version; but this will be not an suitable approach for the future, obviously.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
