### ISSUE TITLE
Angular translate not working while moving from login to index 

### ISSUE THREAD

**Issue by Sumangalaknair** [angular-translate/angular-translate#1831]
### Subject of the issue
Angular translate not working while moving from login to index

### Your environment
* version of angular-translate v2.17.0 
* version of angular  v1.6.6
* which browser and its version chrome latest

### Steps to reproduce
Please help.. and suggest, bit urgent !!!!
[Languages.zip](https://github.com/angular-translate/angular-translate/files/1777357/Languages.zip)

On login page Login renders correctly
But IndexFinYear doesnt render on the index.html page , it throws angula 14700 Possibly unhandled rejection

in app.js as below:

 (https://plnkr.co/edit/XorWgI?p=preview)
[Login.zip](https://github.com/angular-translate/angular-translate/files/1777356/Login.zip)
 as a base.

### Expected behaviour
It should ideally translate index page too

### Actual behaviour
It should ideally translate index page too

**Comment by knalli** [comment]
@Sumangalaknair Sorry, but it looks like your demo-code in the plnkr does not contain something other than the base (do you have saved?)

Also I will not debug your application, but a (single) bug/feature of angular-translate only.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
