### ISSUE TITLE
angular-translate not working in chrome browser

### ISSUE THREAD

**Issue by vst123** [angular-translate/angular-translate#1832]
i have used this code in my project which is working fine with Firefox, but when i switch to chrome nothing happens. the language does not change and no errors as well in the console.
it just shows a warning in console, but at app initialisation.

**warning**  pascalprecht.translate.$translateSanitization: No sanitization strategy has been configured. This can have serious security implications. See http://angular-translate.github.io/docs/#/guide/19_security for details.

this code in my app.module.js

```
var app = angular.module('app', ['ui.router', 'vcRecaptcha', 'ngAnimate', 'ngSanitize', 'ngToast', 'ngCookies', 'ngTouch', 'ui.bootstrap', 'angularMoment', 'ngIntlTelInput', 'ui.select',
    //main modules
    'login', 'dashboard', 'pascalprecht.translate'
]);
```

```
controller: function ($scope, $translate) {
                    $scope.changeLanguage = function (key) {
                        $translate.use(key);
                    };
                }
```
this code in my app.config.js

```
var app = angular.module('app').config(['$translateProvider', function ($translateProvider) {
    $translateProvider.useStaticFilesLoader({
        prefix: 'assets/translation/locale-',
        suffix: '.json'
    });
    $translateProvider.preferredLanguage('en');
}]);
```

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/.github/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
