### ISSUE TITLE
Zip files from Releases currepted

### ISSUE THREAD

**Issue by yupitomets** [angular-translate/angular-translate#1835]
All zip archives are corrupted and can't be open on windows.

**Comment by knalli** [comment]
@yupitomets  What do you have downloaded? The "Source code (zip)" files aren't corrupt and being generated by GitHub actually (it contains the current git branch's files status effectively). Additionally, we are adding angular-translate-vx.x.x.zip as a build result. But this isn't corrupt either. Maybe you have a download issue or an AV agent is causing trouble.

**Comment by knalli** [comment]
Maybe you have downloaded the `*.tar.gz`? Then you have to use a compatible extractor, obviously ;)

**Comment by yuriipitomets** [comment]
I've download zip file from assets, and I can't extract it on multiple Windows machines.

https://github.com/angular-translate/angular-translate/releases/download/2.17.0/angular-translate-2.17.0.zip

**Comment by knalli** [comment]
Which program you are using for extracting?

**Comment by yuriipitomets** [comment]
I guess it is build in in Windows 7. MB3 -> Extract all. 

![image](https://user-images.githubusercontent.com/28987818/38624135-f67783ca-3d6c-11e8-9430-2036b0755f2e.png)
