### ISSUE TITLE
Dynamic translate doesn't work, page needs to be reloaded

### ISSUE THREAD

**Issue by pitometsyurii** [angular-translate/angular-translate#1836]
I have application with angular 1.2.16 and after switched to 1.3.0 I noticed that translates doesn't happen automaticaly, and page needs to be reloaded.

I am using static-files loaders and local storage.

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/.github/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by knalli** [comment]
Note/reminder:

It looks like your environment is using an old or older release of AngularJS and/or angular-translate. After updating your dependencies, please check and verify your issue again.

**Comment by yuriipitomets** [comment]
Which version of Angular 1.x is minimum required to work with latest angular-translate?

**Comment by knalli** [comment]
@yuriipitomets  The current versions are angular-translate@2.17 and AngularJS 1.6. We have tests running our suite against the older one including the latest AngularJS 1.2.x. So it should work.

But if you have issues with very old versions and do not providing any information and demonstration, we cannot help. Effectively, the latter one will also provide your actual used versions.

In general I would recommend using the latest supported versions (AngularJS 1.3).

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
