### ISSUE TITLE
Async Loader is not working correctly in one specific case

### ISSUE THREAD

**Issue by amorek** [angular-translate/angular-translate#1839]
### Subject of the issue
I'm using custom async loader to load translations and there is scenario, where the translations for language are loaded, but after switching back and forth to the same language, I will only see translations keys.
It's a very specific situation and I can't exactly describe why this happens or how to reproduce it in any other application, please see "Steps to reproduce" first to observe the problem. 

I've determined that it happens when $translate.use()
goes to this block:
`      } else if (langPromises[key]) {`

Also it seems to be fixed when I've added 
`(translation.key, translation.table);`
to that else if block. I'm not sure if that rings any bell for you?

```
langPromises[key] = langPromises[key].then(function (translation) {
            translations(translation.key, translation.table);
            deferred.resolve(translation.key);
          if ($nextLang === translation.key) {
            useLanguage(translation.key);
          }
          return translation;
        }
```

forceAsyncReload(true) would also fix this problem, but the if condition fails on `&& !langPromises[key]` and therefore translations are not reloaded.
This also seems to be a bug to me, since it should be forcefully reloaded.

### Your environment
* angular-translate - v2.17.0
* AngularJS v1.6.9
* UI Router version v1.0.15

### Steps to reproduce
https://dev-prd-smartpass.cs88.force.com/LegalPortal#!/login?language=nl
Login using email "piotr.kozuchowski+14@weare4c.com" and remember the language.
After logging in, you can change the language and everything should work fine.
Log out, change the language to something different than at 1st login and login again.
Change the language to the one you 1st logged from.
At this point you should see translations keys even though translation table is populated,
it will only occur for that 1 particular language that you were first logging in from.

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/.github/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

---

Sure, you have added a demo. But we need a working editing demo like provided in a plnkr or similiar (that's up to you). This enables the following:

1. You build a demo only the relevant part of the code -- I cannot debug your application at all.
2. We all can see and make changes on the fly.
3. Not using compressed files shows improved traces.

For example, I would see the actual configuration parts of translate. But I don't want to search in your minified app code. ;)

**Comment by nzamps** [comment]
Thanks @amorek, adding  **translations(translation.key, translation.table);** does work!

```
      } else if (langPromises[key]) {
        // we are already loading this asynchronously
        // resolve our new deferred when the old langPromise is resolved
        langPromises[key].then(function (translation) {
         // add this >>
          translations(translation.key, translation.table);
          if ($nextLang === translation.key) {
            useLanguage(translation.key);
          }
          deferred.resolve(translation.key);
          return translation;
```
