### ISSUE TITLE
Single curly brackets for variables

### ISSUE THREAD

**Issue by liamtarpey** [angular-translate/angular-translate#1841]
### Subject of the issue
Apologies that this isn't an 'issue' as such but this seemed like the correct place to post this question.
Thanks first of all for an amazing library! We've been using this a long time and have never had any issues with it. 
However, the time has come for us to migrate away from Angular 1.x towards React and one of the first tasks we want to tackle is our i18n.
The first problem that I've encountered is variable replacement, we'd like to change our interpolation to single brackets `{ var }`. instead of double `{{ var }}` to match with the translation library we are planning to move towards.
I understand that from the docs that you use Angular's default interpolation syntax but I was wondering if there was a way to configure this in the library? I would like to at least rule this out in advance if this is not an option. A search across the web didn't really help me much.

Thanks in advance!

### Your environment
* version of angular-translate: 2.15.2
* version of angular: 1.6.6
* which browser and its version: n/a

### Expected behaviour
Variables in single brackets to be replaced

### Actual behaviour
No variables wrapped in single brackets get replaced

**Comment by knalli** [comment]
You can implement your own interpolation service, but have to add all features on your own.

**Comment by liamtarpey** [comment]
@knalli thank you! Just built a prototype and works exactly as expected. :)
