### ISSUE TITLE
urlLoader failure handling and fallback loading strategie

### ISSUE THREAD

**Issue by dominicrico** [angular-translate/angular-translate#1848]
### Subject of the issue
We want to load our translation files from our server. But, if the server is not reachable, for what ever reason, the loading fails and we can not load our translations from any other source (ex. static files), because the error is handled in the `.run()` function from events and not in the `.config()` function of the app.

### Your environment
* version of angular-translate: 2.15.2
* version of angular: 1.6.4
* which browser and its version: electron@latest

### Steps to reproduce
use the urlFileLoader with an url that returns an 404

### Expected behaviour
There should be an configurable fallback loader, like static file loader, if the url loading fails.

### Actual behaviour
The error throws and could be handle in the `.run()`functions but no translations could be loaded from there.

**Comment by knalli** [comment]
Please consider building your own custom loader (its actually only a function). You can delegate calls to the provided ones, or just rebuild the flow for your specific use case (maybe offline related situation within your Electron app).

**Comment by knalli** [comment]
https://angular-translate.github.io/docs/#/guide/13_custom-loaders
