### ISSUE TITLE
missing file reference to messageformat.js in bower shadow repository

### ISSUE THREAD

**Issue by leolux** [angular-translate/angular-translate#1849]
The "main" includes only the file to angular-translate-interpolation-messageformat.js and is missing messageformat.js:

https://github.com/angular-translate/bower-angular-translate-interpolation-messageformat/blob/master/bower.json#L5

**Comment by knalli** [comment]
Ehm.. no, why? This is resolved via the dependency tooling. We don't ship vendors.

**Comment by leolux** [comment]
Because "grunt wiredep" is able to import the scripts into index.html automatically based on the "main" attribute of each high level dependendy and in the result the messageformatn.js file is missing and would have to be added manually each time.

Maybe the concpet of "grunt wiredep" reaches its limits

**Comment by knalli** [comment]
Well @leolux  -- no idea about `grunt wiredep`, but the `main` property is best/current practice and will be used by tools like webpack also. `main` is always the package's code, nothing else. 

As already said: We ship no vendor code / other dependencies.

**Comment by leolux** [comment]
Alright, thanks! 
I am going to switch to webpack anyway.
