### ISSUE TITLE
angularjs 1.7.x

### ISSUE THREAD

**Issue by GlauberF** [angular-translate/angular-translate#1852]
some things changed in angularjs 1.7.x that cease to exist, for example: lowercase, uppercase that happened to be $$lowercase, $$uppercase

**Comment by knalli** [comment]
Hi @GlauberF 

could you please elaborate what exactly is not working? We have run our tests again AngularJS 1.7 without issues, however, maybe our tests are not covering everything.

**Comment by GlauberF** [comment]
**Version** agular-translater
![captura de tela de 2018-08-01 13-00-07](https://user-images.githubusercontent.com/11314585/43532717-97d41d0e-9589-11e8-88ba-1ef2ca89004a.png)




**Erro**
![captura de tela de 2018-08-01 11-37-11](https://user-images.githubusercontent.com/11314585/43532720-9900cc22-9589-11e8-8af5-344fc7795c5e.png)

**Comment by knalli** [comment]
Alright, this has been fixed in efc91c3733cac1554ce83bc78185f3070c4dad08 contained in 2.16 at first. You should consider updating this old version of angular-translate.
