### ISSUE TITLE
Opt-out cookie support

### ISSUE THREAD

**Issue by javorosas** [angular-translate/angular-translate#1853]
Could you please add an option for localStorage to not fall back to cookieStorage, intentionally dropping support for older browsers, if desired?

The rationale behind this is that I need my cookies to have both `secure` and `httpOnly` attributes set, for security reasons. This means my cookie won't be accesible to any script in the browser and therefore angular-translate won't be able to modify it.

**Comment by knalli** [comment]
@lavorosas, the easiest one is to build your own storage plugin -- just have a look at the impl of cookie or localstorage. Basically, it's a get and put.

**Comment by javorosas** [comment]
Sorry, this only shows how much I didn't understand cookies. Each cookie is independent, so if my session cookie is `httpOnly` and `secure`, that doesn't mean it's the same case for all cookies on the site.

I'm closing now.
