### ISSUE TITLE
Smoke Testing functionality

### ISSUE THREAD

**Issue by jpike88** [angular-translate/angular-translate#1857]
I want an easy way of accessing a 'dummy' language, which can share the keys of the preferred (or specific) language, with values of just `!DUMMY_VALUE!` or something like that.

We have a lot of translation keys and it would be useful to be able to easily check that everything is accounted for.

**Comment by knalli** [comment]
Well, you can add any language you will. I don’t know what angular-translate can and should do.

**Comment by jpike88** [comment]
Gotcha
