### ISSUE TITLE
Replace double quotes with single using angular-translate?

### ISSUE THREAD

**Issue by adeelasghar88** [angular-translate/angular-translate#1858]
I am using angular-translate for translating English to French but the issue is it converts single quote to double quote. I want to replace translated double quotes with single quote. I have a filter but its not applying on translated text.
`<div class="no-text" ng-if="question.length == 0" translate="msg.site_is_not_applicable" translate-default="This site is not applicable"></div>`

e.g. msg.site_is_not_applicable(EN) = This site is not applicable
After translated in French = le site n''est pas applicable

Doing this but its not working!

`<div class="no-text" ng-if="question.length == 0" translate="msg.site_is_not_applicable | quoteSingle" translate-default="This site is not applicable"></div>`

Want to replace double quoted with single quote. Can someone help how I can do this using angular-translate?

`app.module('app.filters', []).filter('quoteSingle', function() {
   return function(text) {
    return text.replace(/"/g, "'");
   };
});`

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/.github/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by knalli** [comment]
Also I'm in doubt we are converting anything..
