### ISSUE TITLE
Variables not translated in bigger environment with controller and factory files 

### ISSUE THREAD

**Issue by michschu** [angular-translate/angular-translate#1859]
I took over an AngularJS-/Ionic-/Cordova-project without documentation and hand-over and have to change it now. Future will be to use angular-translate from Pascal Precht using _locale-language.json_ files.

We are talking about a bigger application, with separate files for controller and factory for i.e.
- game
- round
- player

Within _app.js_ (which I understand as the "main" JavaScript) I have found/built the following:
```
'use strict'; 
angular.module('app', ['ionic', 'config', 'pascalprecht.translate'])
.run(function ($ionicPlatform, $rootScope, $window, $translate, GameState) 
{
   (...)
   
	.config(function ($translateProvider) 
	{
		$translateProvider.useStaticFilesLoader(
		{
			prefix: 'locale-',
			suffix: '.json'
		});
	  $translateProvider.preferredLanguage('de'); 
	})

	(...)
}
```

Within _game.controller.js_ I have
```
'use strict';
angular.module('app').controller('GameCtrl', function ($rootScope, $scope, $window, $timeout, $interval, $ionicPlatform, $translate, $ionicModal, $ionicPopup, GameState, Players, Purchase) 
{
  (...)

  $scope.remove = function () 
  {
	var confirmGameRoundDelete = $translate.instant('GAME_ROUND_DELETE');	
	var confirmCancelText = $translate.instant('GAME_CANCEL');
	var confirmOkText = $translate.instant('GAME_OK');
	
    $ionicPopup.confirm({
      cssClass: 'rules__popup',
      title: confirmGameRoundDelete,
      subTitle: '',
      cancelText: confirmCancelText, 
      okText: confirmOkText,
      okType: 'button-balanced'
    }).then(function (confirmed) 
	{
      if (confirmed) 
	  {
        GameState.get().removeRound();
      }
    });
  };
```
Here the translation works as expected.	

However when talking about _players.factory.js_ the translation does not work:
```
'use strict';
angular.module('app').factory('Players', function ($window, $translate) 
{
  var player1 = $translate.instant('PLAYERS_1'); 
  var player1 = $translate.instant('PLAYERS_1'); 
  var player1 = $translate.instant('PLAYERS_1'); 
  var player1 = $translate.instant('PLAYERS_1'); 
  
  console.log("player1:", PLAYERS_1);
  var DEFAULTS = [
	player1,
	player2,
	player3,
	player4,
	];
	
	(...)
}
```
`console.log` (like the HTML-file "behind" shows the variable itself = `PLAYERS_1`, not the translation.

I believe I overlook something obvious, to have it working, but I am lost in knowing what. Therefore please help.

**Comment by knalli** [comment]
Within a factory method, you are in the bootstrapping phase still. Translations are being resolved asynchronous.

First: do not resolve translations in the „constructors“, only at runtime. 
Second: alternately resolve them using the async way (promise) which would resolve later.

**Comment by michschu** [comment]
@knalli : Thanks so far.

Not sure, I understand what I have to do in detail here. Do you think, I should follow these [lines](https://angular-translate.github.io/docs/#/guide/12_asynchronous-loading)?

**Comment by knalli** [comment]
Yeah, that is a good resource getting the main thing about our async loading.

You should always remember: we load translations asap, but this is completed after running every constructor/factory/init method of any initial angular service and rendered components/filters.
