### ISSUE TITLE
How to check if a translation mapping exists

### ISSUE THREAD

**Issue by asgeo1** [angular-translate/angular-translate#186]
Hi there,

I couldn't see if there was a way to see if a translation mapping exists?

What I mean is, I have an angular page where I am looking up translations dynamically in a loop. Mappings for some of them may not exist for whatever reason, and I'd like to make that check before attempting to render the translation and associated markup.

I mainly want to do these checks from a view, where I would be using the `translate` filter or directive.

But I also couldn't see a way to do this from a controller using the `$translate` service either - although I'm sure it's probably possible using the $translate service directly.

Any ideas?

**Comment by mjrk** [comment]
+1 
Note: Both links are "Page not Found"

It would be really great to have a helper method to explicitly check in advance if a translation exists. Also, if I could define a fallback-key that is used for non existent mappings.

**Comment by tspaeth** [comment]
Well, it is a very old thread and the docs moved. Look here:

http://angular-translate.github.io/docs/en/#/guide/14_error-handling

**Comment by skawaguchi** [comment]
For anyone else looking: http://angular-translate.github.io/docs/en/#/guide/16_error-handling

**Comment by vinyoliver** [comment]
When using $translate it would be much better if just print the key in case there was no translation instead of not doing nothing.

**Comment by tspaeth** [comment]
@vinyoliver please do not comment on closed issues if there is some issue you'd like to point out. thanks.
Anyway: Did you read the referred chapters above on handling of non-existing translations?
