### ISSUE TITLE
Improved "Possibly unhandled rejection" error handling for AngularJS 1.6+

### ISSUE THREAD

**Issue by gabbsmo** [angular-translate/angular-translate#1860]
### Subject of the issue
This is more of an enhancement request than a bug report.

Since AngularJS 1.6 rejected promises that are not handled by a catch block results in an exception with the message "Possibly unhandled rejection".

If I use the $translate service to get a translation by a dynamic id it gets very difficult to track down the source of the problem if undefined is passed as translationId.

### Your environment
* version of angular-translate: 2.18.1
* version of angular: 1.7.2
* which browser and its version: Google Chrome 69 on Windows 10

### Steps to reproduce
http://next.plnkr.co/edit/nEpRbSKThpDXq3Qs?open=lib%2Fscript.js&deferRun=1

See the exceptions in the console.

### Expected behaviour
More informative error handling. Stack trace would be nice.

### Actual behaviour
The translationId is passed to the angular's exceptionHandler.

**Comment by knalli** [comment]
`undefined` as a translation id (aka input argument) should be checked right in the service, before even requesting the internal stack.

So I think returning the rejection asap is far besser. Maybe you want to make the PR?

**Comment by gabbsmo** [comment]
How does "returning the rejection" give more information about where the invalid argument was passed? Not questioning at all I am just not very familiar with the source code.

**Comment by knalli** [comment]
Well, if a function is returning a promise, it would be a surprise handling for exceptions also. That's why Promise.reject() exist.

**Comment by gabbsmo** [comment]
@knalli It took a little over a year but I have submitted PR #1891. Not sure if it is what you meant but it should pass unit tests.

**Comment by xhlatky** [comment]
good request.. .closed w/o a solution

**Comment by knalli** [comment]
@xhlatky What exactly is the "rude way" here?

**Comment by xhlatky** [comment]
no valid explanation for me

Dňa št 12. 11. 2020, 16:08 Jan Philipp <notifications@github.com>
napísal(a):
