### ISSUE TITLE
Unable to change language to spanish but french and english work

### ISSUE THREAD

**Issue by amiceli** [angular-translate/angular-translate#1864]
### Subject of the issue

Unable to change language to Spanish

### Your environment
* version of angular-translate : 2.18.1
* version of angular : 1.6.8
* which browser and its version : Chrome 70

### Steps to reproduce

Use this angular module config : 

~~~js
import fr from './fr';
import en from './en';
import es from './es';

angular.module('translations', [])
    .config([
        '$translateProvider', ($translateProvider) => {
            $translateProvider
                .translations('en', en)
                .translations('fr', fr)
                .translations('es', es)
                .registerAvailableLanguageKeys(['en', 'fr', 'es'], {
                    'en*' : 'en',
                    'fr*' : 'fr',
                    'es*' : 'es',
                    '*'   : 'es'
                })
                .determinePreferredLanguage()
                .useSanitizeValueStrategy(null);
        }
    ]);
~~~~

Call `$translate.use('es')` and `console.log ($translate.use())` in a controller.

### Expected behaviour

console.log should return **es**.

### Actual behaviour

English is use instead.

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/.github/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.
