### ISSUE TITLE
want callback while using useloader

### ISSUE THREAD

**Issue by ShankzPatil** [angular-translate/angular-translate#1866]
### Subject of the Feature/Information
want callback fucntion while using useloader, propmt event laoding completed if locale file loaded complety in browser.

### Your environment
    "angular": "^1.6.4",
    "angular-translate": "^2.17.0",
    "angular-translate-handler-log": "^2.17.0",
    "angular-translate-loader-static-files": "^2.17.0",
    "angular-translate-storage-local": "^2.17.0",

### Expected behaviour
want to success event so i can handle my some custom logic.

**Comment by knalli** [comment]
Hi @ShankzPatil, please have a look at our guide documenting all the events https://angular-translate.github.io/docs/#/guide/18_events
