### ISSUE TITLE
$translate.instant needs to guarantee a valid return, or need alternative to $translate.instant

### ISSUE THREAD

**Issue by ericnewton76** [angular-translate/angular-translate#1867]
### Subject of the issue
Various invocations of $translate.instant all seem to fail.

For example, using UI-grid which has a configuration setup (annoyingly) in the controller, and trying to setup translations by using $translate.instant for the more esoteric stuff, like select options for the filters.

Sample code:
```js
var gridOptions = {
  columnDefs: [
    {
            name: 'enabled'.
            field: 'enabled',
            displayName: 'FuneralListPage_Enabled_Disabled',
            headerCellFilter: 'translate',
            enableSorting: false,
            enableFiltering: true,
            enableColumnMenu: false,
            enableHiding: false,
            width: 168,
            filter: {
              term: '',
              type: uiGridConstants.filter.SELECT,
              selectOptions: [
                { value: true, label: $translate.instant("FuneralListPage_Enabled") },
                { value: false, label: $translate.instant("FuneralListPage_Disabled") }
              ]
            },
            cellTemplate: '... snip ...'
          }
  ]
}
```

Ignore the "switch" directive, this is a toggle control that mimics the toggle in iOS and just doesnt work at all, and will have to be addressed elsewhere.

If you look at the `displayName` property, I used the `headerCellFilter: 'translate'` which is working as expected.  However, the ui-grid filter setup, to establish the option list for what to filter for, via `selectOptions`, I'm having to use $translate.instant, and it never seems to work.

Now the problem is, if I F5 refresh this page, the ui-grid options are being setup way before $translate.instant is ready to deliver valid values.

Doesn't the implementation contract indicate that $translate.instant is a (potentially) blocking call?  That is what I was expecting... if the translation tables havent been loaded, then there's several points where I simply must have it... and I'm willing to wait for it (blocking call).

### Your environment
* version of angular-translate: 2.18.1
* version of angular: 1.6.3
* which browser and its version: chrome 71

### Steps to reproduce
https://plnkr.co/edit/19tZot?p=preview

### Expected behaviour
calls to $translate.instant work before and after a translation table is loaded, blocking if a language table isn't loaded.

### Actual behaviour
$translate.instant returns translationId often.

**Comment by ericnewton76** [comment]
Perhaps (as mentioned) an alternative would be good?

Realistically, I'm seeing that others are looking to $translate.instant with the same expectations as I... we acknowledge that the language tables either havent fully loaded (ok, so wait) or failed to load (ok, so fallback) but in either case wait.

Yes unfortunately thats a blocking call... its just pretty darn important though! lol

**Comment by knalli** [comment]
Hi @ericnewton76,

honestly, I really don't know why you are thinking a method/function with the name `instant` would be waiting or blocking ever. Really. `instant`. We had thought choosing this name would be clear enough..

Anyway: There is no "blocking" concept after all the world of (browser's) JavaScript, well, except for browser provided APIs.

There is also a promise based variant as `$translate('Page_Title_Label')`.

Please have a look at our documentation and guide.

**Comment by ericnewton76** [comment]
You didn't address the issue of the willingness to wait for that translated data to be available.

Sometimes I need that translation... now.  What are we to use in that case?  Being async and all is nice, but sometimes its too late.

**Comment by ericnewton76** [comment]
So I get what you're saying... use either of these, instant or $translate but if it ain't ready, it aint ready...

I'm saying I'm okay with a blocking call if the translation tables aren't ready... ie (haven't loaded|are loading|failing to load|time-out, fallback) because I need that translated string due to the design of a particular component that I dont have control over.

You're saying $translate.instant will give you a value "Now" but I'm finding it won't give you a valid value "Now". 
 
I need a method that will (potentially block) and give me a valid value... now.  Not on the next tick, but now, because (for example) I'm having to prepare a gridOptions object that the ui-grid wants to get its render on.

Now perhaps I need to use 
```
$translate(["grid-translation-id1", ... , "grid-translation-idN"]).then( (trans) -> {
  _this.gridOptions.somethingThatNeedsTranslating = trans["grid-translation-id1"];
})
```

which means the grid doesnt even get a chance to render placeholders until after the translate tables fully load.

**Comment by knalli** [comment]
Again:
> I need a method that will (potentially block) and give me a valid value... now.

These are mutually exclusive goals and are impossible. "Blocking" is not an option (you are in a browser environment), and valid+now is not possible as of loading (you already said this).

`$translate(array)` would be an option, as well as post-updating the components labels (if possible) or even replacing it, or even delaying the rendering.
