### ISSUE TITLE
Issue with Loader 

### ISSUE THREAD

**Issue by deadmann** [angular-translate/angular-translate#1873]
### Subject of the issue
refresh cause error to be thrown, it's good to check if loader are loaded, and be able to do things after that....

### Your environment
* 2.18.1
* v1.6.5
* Chrome 71 & Firefox 64

### Steps to reproduce
I'm using ui-router, and send language as part of url, since some data are static, i moved them to lower part of system:

my config:
```
        var $q = angular.injector(['ng']).get('$q');
        var $http = angular.injector(['ng']).get('$http');
        $q.all(
            [
                $http.get("/App/translations/global.en.json"),
                $http.get("/App/translations/global.fa.json"),
                $http.get("/App/translations/app.en.json"),
                $http.get("/App/translations/app.fa.json")
            ]
        )
            .then(function (response) {

                $translateProvider.translations('en', {
                    global: response[0].data
                });

                $translateProvider.translations('fa', {
                    global: response[1].data
                });

                $translateProvider.preferredLanguage('en'); // -->moved to run.js
                $translateProvider.useSanitizeValueStrategy('sanitize');
        }, function (response) {

        });
```

then i have another main/root controller which sit above all route, and basically the head of my whole html, even before ui-router directives...

in $translate refresh i get the error, because first config try to load the files, then before the JS compiler, queue the callback, it queue the onStateChange, and due to that, `$translate.refresh();` get called before the config callback section and loader being load.
```
//controller {
self.globalEvent = {
            onStateChanging: function () {
                var state = $rootScope.$state;
                //TODO: FIX LANGUAGE
                 $translate.use(state.params && state.params.lang || 'en')
                     .then(function (key) {
                         $translate.refresh();
                         $rootScope.$applyAsync();
                         console.log("Language Changed to " + key + ".");
                     }, function (key) {
                         console.log("Could not change the language.\n\r" + key);
                     });
//}
```

### Expected behaviour
Refresh should load new language and application should show translated data on the web page...

### Actual behaviour
Tell us what happens instead
Exception get thrown

**Comment by knalli** [comment]
I'm not quite sure what you have done here.. In general, angular-translate must be configured in the config/init phase which also means either the translations are added or a loader is set/defined.

Your first block looks like a config phase (as you retrieving `$q` and `$http`), but the result of the load is being processed already asynchronously. That is already a failing point. Either you can manage the translation being available at this point synchronously (i.e. added at compile/build time), or you have to use a loader.

Your second block is using basically `$translate.use().then( () => $translate.refresh() )`. I don't see why you have to call `refresh` after `use`. Maybe a misleading guess because of the previous issue?

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
