### ISSUE TITLE
Translate custom directive attributes

### ISSUE THREAD

**Issue by larsreith** [angular-translate/angular-translate#1879]
### Subject of the issue
Translate custom directive attributes

Describe your issue here.

Hey, great library! Is it possible to translate custom directive attribues?
For example, I have a simple custom directive that works a a reusable component that I reuse all over the project.

`<content-hero title="some title'" description="'some text"></content-hero>`

Can the title and description property some be translated? I searched long time for an example like this, without success, and tried things like translate-attr="{ title: 'TRANSLATION_KEY'}"

### Your environment
* version of angular-translate: 2.18
* version of angular: 1.4.8
* which browser and its version: current chrome

### Steps to reproduce

**Comment by knalli** [comment]
There are two options:
* Either you use a filter à la `<content-hero title="{{'TITLE' | translate}}"/>`
* Or you use the directive as in `<content-hero translate translate-attr-title="TITLE"/>`

Note: You need to invoke the actual directive `translate`. The attribute `translate-attr-title` is actually a companion argument of the directive.
