### ISSUE TITLE
Need to add translation for multiple files from different modules using StaticFilesLoader

### ISSUE THREAD

**Issue by madhurirode21** [angular-translate/angular-translate#1880]
###  Need to add translation for multiple files from different modules using StaticFilesLoader

I want to add translation for multiple files from different modules using StaticFilesLoader
but those file details are not available at a time so need to call  $translateProvider.useStaticFilesLoader for multiple times for the same language.

But issue is here that it is loading only first translation file not later on.

### Your environment
* version of angular-translate  2.18.0
* version of angular  1.7.5

### Steps to reproduce

http://plnkr.co/edit/HqGOCwmZZceeYSelUdEz?p=preview 
Here is similar kind of example we have created.

### Expected behaviour
Translation from both the files should get uploaded 

### Actual behaviour
Only first file is getting translated and none of the other file is getting translated.

**Comment by knalli** [comment]
Hi @madhurirode21 , you are looking for the partial loader. Have a look at our guide at https://angular-translate.github.io/docs/#/guide/12_asynchronous-loading .

**Comment by knalli** [comment]
+ If you languages are not preset the the time, you simply call for refresh.

**Comment by madhurirode21** [comment]
Cant it be possible with StaticLoader for with multiple file with same language?

**Comment by knalli** [comment]
You can either load multiple files or use your own loader loading whatever you want. Please have a look at our guide's chapters about the asynchronous loaders.

**Comment by madhurirode21** [comment]
Is there any demo/git project for custom StaticLoader  with multiple files added dynamically

**Comment by knalli** [comment]
The same syntax static loader supports for loading one pattern is available under the key `files` for multiple ones: https://github.com/angular-translate/angular-translate/blob/eda9f29b3343d84f43f9fa30a39a1ae636d1c494/src/service/loader-static-files.js#L27

**Comment by knalli** [comment]
Additionally, there is directory `demo/` included for running some use cases combined with a node server -- no multiple files, but you will get the idea.

**Comment by madhurirode21** [comment]
yes. but for that, all file details should be known at a single point.
We are in requirement of translating multiple files one after another with staticLoader

**Comment by knalli** [comment]
Then use the partial loader, as I suggested at the start. Both docs and samples are provided in the urls above.

Alternatively, as I already said, you can build your own loader loading whatever you want. The API to angular-translate is the resolved promise containing the complete data regardless how they have been fetched.
