### ISSUE TITLE
want to customize data received from Part.prototype.getTable in PartialLoader before sending for translation

### ISSUE THREAD

**Issue by madhurirode21** [angular-translate/angular-translate#1881]
### Your environment
* version of angular-translate 2.18.0
* version of angular 1.7.5

### Steps to reproduce
I have implemented partial loader in my application.
But json files which contain data which needs to be translated has a application specific json format.

So In partialLoader, I want to customize my partial loader such a way that data received by Part.prototype.getTable needs to transform to standard json format before sending for translation.

https://github.com/angular-translate/angular-translate/blob/master/src/service/loader-partial.js#L55 
data returned by this function needs to be customsied as per the requirement.

handleNewData function is having data from files so customization can be done at this step.
So please provide a way to do it.
https://github.com/angular-translate/angular-translate/blob/master/src/service/loader-partial.js#L75 

It will be great if you provide a way to do such use case as it is very urgent issue.

**Comment by knalli** [comment]
I won't see major updates to the partial loader any more. So if you need bigger changes, I would suggest of creating your own one. Just create your own custom loader based on our partial loader code. Basically, a loader is only a function which returns a table of translations (wrapped in a promise).
