### ISSUE TITLE
Sanitize strategy not working

### ISSUE THREAD

**Issue by mhanke** [angular-translate/angular-translate#1883]
I have set the sanitize strategy using $translateProvider.useSanitizeValueStrategy('sanitize'). It is not working when i use the translate directive. When I am using the translate filter, all works as expected. Do I miss an option? 

### Your environment
* version of angular-translate: 2.18.1
* version of angular: 1.5.5
* Chrome: 75

### Steps to reproduce
```
<div ng-controller="Ctrl">
  <p>{{ 'HEADLINE' | translate }}</p>
  Not working
  <p translate="{{text}}"></p>
  <br/>
  <br/>
  Working
  <p>{{text | translate}}</p>
</div>

var app = angular.module('myApp_escaped', ['pascalprecht.translate', 'ngSanitize']);

app.config(['$translateProvider', function ($translateProvider) {
  $translateProvider.translations('en', translations);
  $translateProvider.preferredLanguage('en');
  // Enable escaping of HTML  
  $translateProvider.useSanitizeValueStrategy('sanitize');
}]);

app.controller('Ctrl', ['$scope', function ($scope) { 
  $scope.text = 'Test <span style=\'color:red;\'>HACKED</span>';
}]);
```

http://plnkr.co/edit/fypR6SxqNp2CyPKgw8hy?p=preview

### Expected behaviour
HTML is only visible as text

### Actual behaviour
HTML is in the dom

**Comment by dsschnau** [comment]
Hey, I have this same issue. I'm interested in finding a way to sanitize using the directive so I don't have to change a lot of code to use the filter instead.

**Comment by dsschnau** [comment]
Hey, in your plunker, I change the sanitization strategy from `sanitize` to `escape` and that achieves the expected behavior.

**Comment by mhanke** [comment]
Hello, I have tested your statement but I can't reproduce it. When I change the strategy to escape like this: $translateProvider.useSanitizeValueStrategy('escape');, the text "Test HACKED" is still shown. Can you check it again please? Or post a working plunker? Thanks

**Comment by dsschnau** [comment]
Ah... nevermind. I misread the output of that change.

**Comment by knalli** [comment]
Well, escaping the *translation* works as you already pointed out. But the *translation key* will not be modified, which in this case is the "hacked" text.

Originally, we see a translation key as an internal (and therefor trustful) information/string. Eventually you can intercept this behavior with a custom handler: https://angular-translate.github.io/docs/#/api/pascalprecht.translate.$translateProvider#methods_usemissingtranslationhandler
