### ISSUE TITLE
$translateMessageFormatInterpolation breaks fallback locale

### ISSUE THREAD

**Issue by theodesp** [angular-translate/angular-translate#1887]
### Subject of the issue
Describe your issue here.

### Your environment
* version of angular-translate
* version of angular
* which browser and its version

"bower": "^1.5.3",
"angular": "~1.4.5",
"angular-translate": "~2.18.1",
"angular-translate-interpolation-messageformat": "~2.18.1"

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://plnkr.co/edit/XorWgI?p=preview) as a base.

I had the following config:

```
$translateProvider.translations('en', Translation.EN);
  $translateProvider.translations('ja', Translation.JA);
  $translateProvider.translations('zh_CN', Translation.ZH_CN);
  $translateProvider.registerAvailableLanguageKeys(['en', 'ja', 'zh_CN'], {
    'en_*': 'en',
    'ja_*': 'ja',
    'zh_CN': 'zh_CN'
  });
  $translateProvider.useSanitizeValueStrategy();
  $translateProvider.determinePreferredLanguage();
  $translateProvider.addInterpolation('$translateMessageFormatInterpolation');
  $translateProvider.fallbackLanguage('en');
```

And some example MESSAGES

```
 PASSWORD_RULE_CHARS: 'Password must contain 8-16 characters',
 PASSWORD_RULE_LOWERCASE: 'Upper and lowercase letters',
PASSWORD_RULE_NUMBER: 'One number',
PASSWORD_RULE_SPECIAL: 'One special character (＆!@%£)',
```

### Expected behaviour
Tell us what should happen

When I change a locale to a non supported one for example Spanish the fallback language which is English will not trigger. Instead I can see that it renders only the message keys for example `PASSWORD_RULE_CHARS` instead of `Password must contain 8-16 characters` throughout the app.

### Actual behaviour
Tell us what happens instead

It should render the fallbackLanguage values instead of keys.

To rectify it  I had to add the following line:

```
$translateProvider.registerAvailableLanguageKeys(['en', 'ja', 'zh_CN'], {
    'en_*': 'en',
    'ja_*': 'ja',
    'zh_CN': 'zh_CN',
    '*': 'en' <----- ADDED
  });
```

Is this the expected configuration because it seems something is strange here?. Before adding the `$translateMessageFormatInterpolation` everything was working correctly - no issues with the fallback.

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/.github/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
