### ISSUE TITLE
Add option for Secure flag on cookie storage cookie

### ISSUE THREAD

**Issue by kpyfan** [angular-translate/angular-translate#1888]
### Subject of the issue
For compliance reasons, the cookie that is used to store the currently in use language needs to be a "Secure" cookie. This is available in the API used by angular-translate to set the cookie. Please provide a flag/option on the storage service to use a secure cookie instead of the insecure.

### Your environment
* version of angular-translate 2.18.1
* version of angular 1.7.5
* which browser and its version Chrome 76.0.3809.132 MacOS (but applies to all browsers)

### Steps to reproduce
Inspect the cookie being set by the translate cookie storage.

### Expected behaviour
There should be be the secure flag if the developer wants

### Actual behaviour
There is no way for the developer to set the secure flag on the cookie. The cookie will always be insecure.

**Comment by knalli** [comment]
Hi @kpyfan, feel free providing a PR with this addition. We have contribution guide lines which support you. Ensure this also requires additions in tests and docs.

Besides: You can also provide your own storage implementation (cookie storage is only one example, localstorage the other one).

**Comment by kpyfan** [comment]
@knalli I'm working on the PR for this - Any suggestions on testing the secure flag of the cookie? Also, I'm not seeing a way to set the secure flag for the deprecated $cookieStore used in angular<1.4, is it reasonable to have the flag do nothing in that case?

**Comment by knalli** [comment]
Well, the abstraction `$cookieStore` does not expose any api for this, which means it isn’t the right tool for that. I guess, you have to use the native browsers‘ api. And this would mean, a test is either using a mock or checking the cookie in an integration test — or both of them. So eventually you copy the existing cookie storage service and rewrite following your requirements. Maybe it‘s enough to share the code here in working demo for all. In the Guide line and issue template we are sharing templates.

**Comment by kpyfan** [comment]
@knalli I think you're right here that writing a custom service is a little easier than trying to adapt the existing service to also provide this functionality.

I've essentially copied the code from [storage-cookie.js](https://github.com/angular-translate/angular-translate/blob/master/src/service/storage-cookie.js) and added in the option for secure. It's worth it to note that other $cookies options can be set here (such as expiration).

```
/**
 *
 * @ngdoc object
 * @name pascalprecht.translate.$translateCookieStorage
 * @requires $cookieStore
 *
 * @description
 * Abstraction layer for cookieStore. This service is used when telling angular-translate
 * to use cookieStore as storage.
 *
 */
.factory('$translateSecureCookieStorage', $translateSecureCookieStorageFactory);

function $translateSecureCookieStorageFactory($injector) {

  'use strict';

  // Since AngularJS 1.4, $cookieStore is deprecated
  var delegate;
  var $cookies = $injector.get('$cookies');
  delegate = {
    get: function (key) {
      return $cookies.get(key);
    },
    put: function (key, value) {
      $cookies.put(key, value, {secure: true});
    }
  };

  var $translateSecureCookieStorage = {

    /**
     * @ngdoc function
     * @name pascalprecht.translate.$translateCookieStorage#get
     * @methodOf pascalprecht.translate.$translateCookieStorage
     *
     * @description
     * Returns an item from cookieStorage by given name.
     *
     * @param {string} name Item name
     * @return {string} Value of item name
     */
    get: function (name) {
      return delegate.get(name);
    },

    /**
     * @ngdoc function
     * @name pascalprecht.translate.$translateCookieStorage#set
     * @methodOf pascalprecht.translate.$translateCookieStorage
     *
     * @description
     * Sets an item in cookieStorage by given name.
     *
     * @deprecated use #put
     *
     * @param {string} name Item name
     * @param {string} value Item value
     */
    set: function (name, value) {
      delegate.put(name, value, secure);
    },

    /**
     * @ngdoc function
     * @name pascalprecht.translate.$translateCookieStorage#put
     * @methodOf pascalprecht.translate.$translateCookieStorage
     *
     * @description
     * Sets an item in cookieStorage by given name.
     *
     * @param {string} name Item name
     * @param {string} value Item value
     */
    put: function (name, value) {
      delegate.put(name, value);
    }
  };

  return $translateSecureCookieStorage;
}
```

This is used in our config as follows (service is declared in the same file):

```
angular.module('module.name', [])
.constant('CONFIG_TRANSLATE', function (provider) {
      // Provides a common function to allow for configuration of the translate provider
      provider
      .useSanitizeValueStrategy('escaped')
      .useStaticFilesLoader({
        prefix: "/assets/translations/",
        suffix: ".json"
      })
      .uniformLanguageTag('java')
      .registerAvailableLanguageKeys(
          ['en_US', 'en_GB', 'en_KF', 'ja_JN', 'fr_FR', 'de_DE', 'ru_RU', 'zh_CN', 'pseudoloc'], {
            'en_US': 'en_US',
            'en_GB': 'en_GB',
            'ja_JN': 'ja_JN',
            'fr_FR': 'fr_FR',
            'de_DE': 'de_DE',
            'ru_RU': 'ru_RU',
            'zh_CN': 'zh_CN',
            'pseudoloc': 'pseudoloc',
            '*': 'en_US'
          })
      .determinePreferredLanguage()
      .storageKey('LANGUAGE_COOKIE')
      .useStorage('$translateSecureCookieStorage');
    }
)
```
