### ISSUE TITLE
Run-time error

### ISSUE THREAD

**Issue by markzolotoy** [angular-translate/angular-translate#1889]
### Subject of the issue
I am getting the following error:
angular.min.js:127 TypeError: angular.lowercase is not a function
    at L (angular-translate.min.js:6)
    at Function.R.use (angular-translate.min.js:6)
After the this line of the code:
$translate.use(lang);

### Your environment
* 2.18.1
* 1.7.8

* which browser and its version
Chrome
Am I using  correct version of angular-translate with AngularJS 1.7.8?

**Comment by tspaeth** [comment]
Are you sure, that you're using version 2.18.1 from angular-translate?

**Comment by markzolotoy** [comment]
/*!
 * angular-translate - v2.18.1 - 2018-05-19
 * 
 * Copyright (c) 2018 The angular-translate team, Pascal Precht; Licensed MIT
 */

**Comment by markzolotoy** [comment]
This code helped with the problem:
angular.uppercase = function (text) {
    return text.toUpperCase();
}
angular.lowercase = function (text) {
    return text.toLowerCase();
}

**Comment by tspaeth** [comment]
I'm asking, because the calls to angular.lowercase have already been removed with 2.17.0 and within the release-files I download from/for 2.18.1, there is no call to angular.lowercase in the min.js - files.

**Comment by markzolotoy** [comment]
Well, I downloaded it today. Anything else you want me to check?

**Comment by tspaeth** [comment]
Well, as described in the issue template, best would be if you setup a complete example so others can check what goes wrong.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
