### ISSUE TITLE
useStaticFilesLoader files array does not work as per documentation

### ISSUE THREAD

**Issue by VAMSHI18** [angular-translate/angular-translate#1890]
Using useStaticFilesLoader files array in angular js translate doesn't work as expected

### Your environment
* angular translate version: 2.18.1
angular-translate-loader-static-files: "^2.18.1"
* version of angular : 1.3.15
Chrome browser

Use like this in any js file: 
$translateProvider.useStaticFilesLoader({
    files: [ {
        prefix: '/absolute/path/to/locale-',
        suffix: '.json'
    }, {
        prefix: 'another/path/to/locales/',
        suffix: ''
    }]
});
$translateProvider.preferredLanguage('en');

### Expected behaviour
In the above code if "/absolute/path/to/locale-en.json" is not present then the file should be fetched from "another/path/to/locales/en-us.json"

### Actual behaviour
Webpage not getting translated

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/.github/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by VAMSHI18** [comment]
hi @knalli , Thanks for the reply.
my plunkr is here: https://plnkr.co/edit/NYOwTEM9goFzX5hOgSKn?p=preview
It's not working demo because I cannot install `useStaticFilesLoader`.

So, explaining my question using the plunkr code:
1. In line #7, `useStaticFilesLoader` will create something like this: {{prefix}}{{langKey}}{{suffix}}
2. From the files array(line #8), if files[0] path does not exists then angular-translate should pick files[1] resource json file but in my case it's not picking up.
Here files[0]:  /locale-en.json
files[1]: ._/locale-es_mx.json_

**Comment by knalli** [comment]
Well, you have to import the angular-translate-loader-static-files as well, see for example [here](https://next.plnkr.co/edit/YbPTvG3Oozd9Rcg2).

**Comment by VAMSHI18** [comment]
Hi @knalli ,
Understood. I have edited the plukr: https://plnkr.co/edit/c9vKfw6DknRh64IsC4eA
Expected Output: **Heading**
Observed Output: **TITLE**

**Details**:

- When hits(https://run.plnkr.co/i3JidS3BPX3Jl52a/locale_first_en-us.json) the response is 404 NOT Found as expected.

- The subsequent API second hit would be(https://run.plnkr.co/i3JidS3BPX3Jl52a/locale_second_en-us.json) which will be 200K as expected since the JSON file exists in directory.

- Since the second API results in 200 OK, why does the HTML page is still not translated? Why does **TITLE** key does not get resolved to **Heading** value?

I hope the behavior should be like this: 
When the files[0] path does not exists it should be using files[1] path. 
I am having a requirement like this. 
If you get to know some workaround please let me know

Thanks,
Vamshi

**Comment by knalli** [comment]
Because the loader implementation uses `$q.all`(see https://docs.angularjs.org/api/ng/service/$q#all). If the loader does not meet your requirements, I suggest you make your own one. You can simply copy it and make your own modification for your own. In that case, maybe using `$q.race`?

**Comment by knalli** [comment]
See more information about this topic at https://angular-translate.github.io/docs/#/guide/13_custom-loaders

**Comment by VAMSHI18** [comment]
Sure @knalli , I'll take a try that and ping you in case of help. Thx!

**Comment by VAMSHI18** [comment]
Thanks @knalli , custom loader worked in my case. :)
