### ISSUE TITLE
form - How to edit a label

### ISSUE THREAD

**Issue by manakeo** [angular-translate/angular-translate#1893]
### Subject of the issue
How can i make a form to edit a label in each languages : 

```
<input type="text" ng-model="user.label['en']" ng-value="'label_1' | translate | 'en' ">
<input type="text" ng-model="user.label['fr']" ng-value="'label_1' | translate | 'fr' ">
```

something like that :/

### Your environment
* version of angular-translate 2.8.1
* version of angular 1.5.5
* which browser and its version chrome

**Comment by knalli** [comment]
Hi @manakeo 

it looks like this got missed last year. 

Nevertheless this is not an issue with this framework, I am afraid I cannot help you. Or, with other words: We do not have the feature of editing the labels (in the web). Of course you can build a site with dynamic labels, but that's far far away out of our scope.
