### ISSUE TITLE
AngularJS1.6.2 - IE9 compatibility slow rendering for Translate Provider Static File Loader #1892

### ISSUE THREAD

**Issue by balakrishnanamala** [angular-translate/angular-translate#1894]
Here is the demo link for this issue

https://plnkr.co/edit/RfRnpGrmf95aRn8DCiqs?p=preview

Below code is causing issue in IE9 compatibility mode with IE11 browser . Its taking around 2mins to render in IE9 compatibility mode (with IE11), also getting message about long running query.

In IE11 this code is taking around 40 seconds.

$translateProvider.useStaticFilesLoader({
prefix: ${root}langs/locale-,
suffix: '.json',
})

**Comment by knalli** [comment]
Hi @balakrishnanamala,

are you sure you are not using violating code in IE9? I remember there were some limitations of using dangling commas as you have there in the line of `suffix`...

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
