### ISSUE TITLE
Use templated string as key

### ISSUE THREAD

**Issue by aresot** [angular-translate/angular-translate#1895]
### Subject of the issue
We are using gulp job to extract all elements marked with "translate" into json files. As result strings that have variables like `<span translate>Hello {{name}}!</span>` will be pushed into say en_US.json file with key of "Hello {{name}}!". It suits us well since we dont have to maintain key-value pair file manually and translators have context. Problem is that it doesnt work. 

### Your environment
* version of angular-translate: 2.11.0
* version of angular: 1.5.7
* which browser and its version: Any

### Steps to reproduce
Please check out this [plnkr](https://plnkr.co/edit/MlPC9Aa4WAC2A370TdnC?p=preview) example. Last line in there not working.

### Expected behaviour
Would like to see "hello {{name}}" from example as key to be working.

### Actual behaviour
Key of "hello {{name}}" is ignored.

I think I know reason why it happens: AngularJs template engine probably applies interpolation 1st and thus will convert  "hello {{name}}" into "hello John Doe". "translate" directive is applied after that and uses "hello John Doe" as key instead of "hello {{name}}". I think solution would be to apply translate **before** AngJs applies variables.

**Comment by knalli** [comment]
>  I think solution would be to apply translate before AngJs applies variables.

That is is not possible. We *are* using the AJS directive and filter infrastructure which also means we cannot intercept the actual processing implementation. We only can register things as a filter or directive (or the service, of course).
