### ISSUE TITLE
bower repo doesn't have latest release tag

### ISSUE THREAD

**Issue by schrej** [angular-translate/angular-translate#1896]
The bower shadow repository for angular-translate doesn't have the latest release's tag `2.18.2`, which leads to bower not being able to resolve said version.
The files have been upgraded in the repository, the tag is just missing.

**Comment by knalli** [comment]
@schrej  Thank you. Something with the tooling is broken, I've fixed the missing tags.

**Comment by schrej** [comment]
Thanks for the quick response. Apparently a little too quick though, you just tagged `2.28.2` 😄

**Comment by knalli** [comment]
![sad](https://media.giphy.com/media/9Y5BbDSkSTiY8/giphy.gif)

Fixed this..
