### ISSUE TITLE
De-cloaking broken in 2.18.2

### ISSUE THREAD

**Issue by pcoder47** [angular-translate/angular-translate#1897]
### Subject of the issue
In version 2.18.2 of angular-translate the cloak removal is no longer working.

When using AngularJS 1.6.10 together with angular-translate 2.7.2 the cloak/decloak functionality was working without issues.
After upgrading to AngularJS 1.7.9 and then switching to angular-translate 2.18.2 (due to the angular.lowercase change) the cloak/decloak no longer works

### Your environment
* version of angular-translate: 2.18.2
* version of angular: 1.7.9
* which browser and its version: tested with latest Chrome (v80) and FF-ESR

### Steps to reproduce
In the plunkr you can switch between the working version (AngularJS 1.6.10 + angular-translate 2.7.2) and the non-working version (AngularJS 1.7.9 + angular-translate 2.18.2)

https://plnkr.co/edit/4a5YWHpng6mXmsBhDHfA?p=info

When switching to the broken version, the translation is not shown (not de-cloaked) and the loading area is not hidden

### Expected behaviour
After the sample time of 5s has finished the translation should be shown (de-cloak) and the loading area should be hidden

### Actual behaviour
After the sample time of 5s has finished the translation area is still cloaked and the loading area is still hidden

**Comment by knalli** [comment]
@pcoder47 Try either to remove the value of the cloak or use an existing translation key.

**Comment by pcoder47** [comment]
@knalli: what I don't understand is that the automatic removal worked before in angular-translate 2.7.2 together with AngularJS 1.6.10. You can see this in the plunkr when changing the versions in the index.html.
I was under the impression that angular-translate in version 2.18.2 has a regression regarding some $rootscope changes in AngularJS which have been fixed in an earlier angular-translate version.

**Comment by knalli** [comment]
I think it has changed with 2.8. The point is: You have there the value `any` which is not required at all. But if set, it will treat as a translation test (think as an extended cloaking).

**Comment by pcoder47** [comment]
Hi there,
thanks for the help.
I changed the value on the directive as you suggested and it works for me.
I'll close the ticket.
Thanks again!
