### ISSUE TITLE
How to use UI router with angular translate?

### ISSUE THREAD

**Issue by vgavrilovikj** [angular-translate/angular-translate#1902]
### Subject of the issue
Describe your issue here.
I am trying to connect Angular Translate with UI Router. I have found this plunker: http://embed.plnkr.co/yleNY6alvqsEZ9dJfYSh/ and implemented it successfully. However, that is not what I really want to achieve. 

What I want is to have the following URL: www.domain.com/en/us/ (Language code first and then country code), instead I have this now -> www.domain.com/en/

Another thing is, how to resolve the issue that I am getting Error 404 when I go directly to the www.domain.com/en/

Here is my angularjs app configuration:
`app.run(['$rootScope', '$translate', '$state', function ($rootScope, $translate, $state) {
    $rootScope.onChangeValue = function (e) {
        $rootScope.$broadcast("changeValue", e);
    };

    $rootScope.$on('$stateChangeSuccess', onStateChangeSuccess);

    function onStateChangeSuccess(event, toState, toParams) {
        var current = $translate.use();
        if (!current || current !== toParams.lang)
            $translate.use(toParams.lang);
    }
}]);

app.config(['$translateProvider', function ($translateProvider) {
    $translateProvider.useStaticFilesLoader({
        prefix: '../languages/locale-',
        suffix: '.json'
    });
    $translateProvider.fallbackLanguage('en');
    $translateProvider.preferredLanguage('en');
    $translateProvider.useSanitizeValueStrategy('escape');
    $translateProvider.useCookieStorage();
}]);

app.config(['$stateProvider', '$locationProvider', function ($stateProvider, $locationProvider) {
    $locationProvider.html5Mode(true);
    $locationProvider.hashPrefix('');

    $stateProvider.state('catalog', {
        url: '/{lang}',
        controller: "SudokuController",
        params: {
            lang: {
                value: function ($translate) {
                    return $translate.use();
                }
            }
        }
    });
}]);`

I have the following code in my controller:
`app.controller("SudokuController", ['$scope', 'Chronicle', '$timeout', '$cookies', '$translate', '$state', '$stateParams', function ($scope, Chronicle, $timeout, $cookies, $translate, $state, $stateParams) {

    $scope.params = $stateParams;
    $scope.changeLanguage = function (newLang) {
        var params = angular.extend($stateParams, { lang: newLang });

        $translate.use(newLang).then(function () {
            $state.transitionTo($state.current, params, {
                reload: true, inherit: false, notify: true
            });
        });
    }
}]);`

Here is the HTML that is generating the nav with multiple languages:
`<div class="language-dropdown">
    <ul class="country-list" ng-controller="navigationLanguages">
        <li class="country" ng-repeat="language in languagesMenu">
            <div class="country-flag" style="background-image: url('images/mk.png');"></div>
            <a ng-bind="language.Language" ng-click="changeLanguage(language.Code)"></a>
        </li>
    </ul>
</div>`

Is it possible for these URLs/ languages to be crawlable by Google?

### Your environment
* version of angular-translate
* version of angular
* which browser and its version

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://plnkr.co/edit/XorWgI?p=preview) as a base.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by knalli** [comment]
> Is it possible for these URLs/ languages to be crawlable by Google?

In general, the GoogleBot is able to execute JavaScript for some years now, but personally, I would not trust the functionality (I doubt Google is promising that). Also I would assume the GoogleBot will not visit your page multiple times in different languages? Nevertheless, I'm not quite familiar with the more recent developments here.

> Is it possible for these URLs/ languages to be crawlable by Google?

In case of additional work or misbehaving JavaScript when crawler visiting the page, just do not forget the server side rendering option.

> What I want is to have the following URL: www.domain.com/en/us/ (Language code first and then country code), instead I have this now -> www.domain.com/en/
> 
> Another thing is, how to resolve the issue that I am getting **Error 404** when I go directly to the www.domain.com/en/

You must have a server-side logic which can serve your files regarding your specific needs (here: serving different path segments). That's not JS website can handle itself. Said that, this cannot be done any client-side JavaScript software.
