### ISSUE TITLE
translate-sanitize-strategy

### ISSUE THREAD

**Issue by TylerZubke** [angular-translate/angular-translate#1905]
I'm trying to use the `translate-sanitize-strategy` attribute so I can override the value set by `useSanitizeValueStrategy` on a specific string but it's not working. I'm setting `translate-sanitize-strategy="escape"` so the string `Name: <name>` will show up properly but `<name>` ends up getting stripped out because I believe the value set by `translate-sanitize-strategy` is either ignored or not working. 

Example: http://plnkr.co/edit/UwIcZpCZLWzja3AZ?preview
If you change the value passed to `useSanitizeValueStrategy` to `escape` it works, but trying to do it for only one string using `translate-sanitize-strategy` does not.

**Comment by knalli** [comment]
Hi @TylerZubke,

your demo looks not being working. There is something broken with your configuration.

Btw: You're using AJS 1.5 which is quite old. Consider updating.

**Comment by TylerZubke** [comment]
@knalli 
Sorry about that, it should be working now. As you can see, it just prints 'Name' and the '<name>' part is stripped out. If you change `useSanitizeValueStrategy` to `escape` it works as expected even though I have `translate-sanitize-strategy` set to `escape` on that element.

**Comment by knalli** [comment]
Ok, well.

1. Also this AJS is outdated and is a mixed combination from AJS core 1.6.9 and angular-sanitize 1.5.8. Be careful. And update.
2. The used angular-translate 1.12.1 is also outdated. Please update.
3. I don't the original intent, but the directive's attribute `translate-sanitize-strategy` is being bound using the interpolation parser. Therefor, just write `<p translate-sanitize-strategy="'escape'" translate>test</p>` and it works (a string is an interpolatable expression returning the string itself).

Note: angular-translate supports this attribute with 2.16 starting. As I said already: Update :)

**Comment by TylerZubke** [comment]
`translate-sanitize-strategy="'escape'"`
Ah, didn't realize it to be a quoted string. Thanks.
