### ISSUE TITLE
Cookie “NG_TRANSLATE_LANG_KEY” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute.

### ISSUE THREAD

**Issue by chickahoona** [angular-translate/angular-translate#1908]
### Subject of the issue
Thanks alot for your hard work! In Firefox I noticed this message here:

```
Cookie “NG_TRANSLATE_LANG_KEY” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
```

![image](https://user-images.githubusercontent.com/8075146/104585420-42101280-5664-11eb-9e5b-1210a0e8b275.png)

The problem is that the cookie is stored with SameSite None:

![image](https://user-images.githubusercontent.com/8075146/104585905-0590e680-5665-11eb-9b28-6513c4a09181.png)

### Your environment
* version of angular-translate: v2.18.3
* version of angular: v1.8.0
* which browser and its version: Firefox 84.0.2 (64-bit)

### Steps to reproduce

Use the latest version with cookie storage and open the page in Firefox.

**Comment by knalli** [comment]
Hi @chickahoona , thank you for reporting. Are you able to [fix this here](https://github.com/angular-translate/angular-translate/blob/canary/src/service/storage-cookie.js) in a small PR?

**Comment by chickahoona** [comment]
I could. Just for my understanding. Is that cookie store used somewhere else or only for this `NG_TRANSLATE_LANG_KEY` ? If its not used anywhere else, my proposed fix would be to add samesite: "strict" as default

**Comment by knalli** [comment]
No, the cookie is only used in that specific storage plugin.

**Comment by chickahoona** [comment]
Done

**Comment by knalli** [comment]
Thank you very much.

Picked 4bbbd6a

**Comment by knalli** [comment]
As a reminder for future requests of other people: If someone needs other/specific settings except fixing basic/security things like that, simply [create your own storage plugin](https://angular-translate.github.io/docs/#/guide/11_custom-storages) just like the cookie is actually. For example a more strict version, different naming, fallback strategies and so on.

**Comment by knalli** [comment]
:shipit: [2.18.4](https://github.com/angular-translate/angular-translate/releases/tag/2.18.4)

**Comment by chickahoona** [comment]
@knalli Sorry to bother you again, could I get here a tag for 2.18.4 https://github.com/angular-translate/bower-angular-translate

**Comment by knalli** [comment]
Fixed. Looks like I have to check my scripts again.. :/
