### ISSUE TITLE
 $translatePartialLoader.doesnot allow ë à á characters

### ISSUE THREAD

**Issue by Ton024** [angular-translate/angular-translate#1914]
When using $translatePartialLoader there is no way to get the right UTF-8 characters from the url specified. I've tried all settings for $translateProvider.useSanitizeValueStrategy, none of them work. Never do I see ü á or ë in my German and ranch translations.

Code:
$translatePartialLoader.addPart(part);
$translate.refresh();

How is this possible after al these years.

**Comment by knalli** [comment]
> How is this possible after al these years.

Weil, that may be the hint this is perhaps not an issue of the library after all. As this is a client side framework, all charset/encoding relevant stuff is done within the client (aka browser). Any data received by XHR must be advertised correctly. Otherwise the client/browser/js may not handle strings correctly. 

Yes, there are open issues with special Unicode characters in combination with interpolation/sanitization. But the standard characters of iso are working without issues for years. This includes german umlauts specifically. 

If you still think there is an issue: please follow the recommendation and demonstrate the problem.

**Comment by Ton024** [comment]
I can understand what you're saying. It should be the web.config to set the correct settings to receive the carachterset UTF-8. I thould I did it. Please take a look at the settinsg down below:

  <system.web>
    <compilation debug="true"/>
    <globalization
        requestEncoding="utf-8"
        responseEncoding="utf-8"
        fileEncoding="utf-8"/>

    <customErrors mode="Off"></customErrors>
  </system.web>
  <system.webServer>
    <httpProtocol>
      <customHeaders>
        <add name="Cache-Control" value="no-cache, no-store, must-revalidate, pre-check=0, post-check=0, max-age=0, s-maxage=0"/>
        <add name="Pragma" value="no-cache"/>
        <add name="Expires" value="0"/>


      </customHeaders>
    </httpProtocol>
    <modules runAllManagedModulesForAllRequests="true">

    </modules>
    <staticContent>
      <remove fileExtension=".txt" />
      <mimeMap fileExtension=".txt" mimeType="text/plain; charset=utf-8" />
      <remove fileExtension=".json" />
      <mimeMap fileExtension=".json" mimeType="application/json; charset=utf-8" />
  
    </staticContent>

**Comment by knalli** [comment]
Using the browser developer tools, you can maybe already check whether the resources are correct in the response or not.

Please understand we cannot give support for your backend configuration (quite not sure what you are using here). This may be better located at StackOverflow or something like that. Said this, you should also include the server/version and framework/version you are currently using, besides the relevant configuration for more context.

**Comment by Ton024** [comment]
Thank you for your comment. I've allready posted a question to get the response I want:
https://stackoverflow.com/questions/71211404/utf-8-json-file-is-encoded-with-wrong-characters?noredirect=1#comment125889610_71211404

Till now no answer. 
BTW: I'm using v2.19.0 (loader) and v2.7.2 (translate) on Visual Studio Development and IIS for hosting.
