### ISSUE TITLE
Unexpected behavior registering translations with .translations() and using an async loader with .forceAsyncReload(true)

### ISSUE THREAD

**Issue by Agustin-Q** [angular-translate/angular-translate#1916]
### Subject of the issue
When using an async loader and `forceAsyncReload` is enabled, the translations registered with `$translateProvider.translations()` are ignored.
When trying to prevent _FOUC - Flash of untranslated content_ I'm registering some translations with `$translateProvider.translations()`. So I'm expecting that these translations are displayed meanwhile the async loader fetches the rest of the translations. But the translations are not displayed until the async loader finishes fetching the translations, generating _FOUC_.

Reading documentation I understand this is the method for preventing _FOUC_. This in the [**Force asynchronous reloading**](https://angular-translate.github.io/docs/#/guide/12_asynchronous-loading/:~:text=force%20asynchronous%20reloading) of the **Asynchronous Loading** docs.

### Your environment
* version of angular-translate: 2.15.2
* version of angular: 1.6.2
* which browser and its version: Google Chrome | 106.0.5249.103 (Official Build) (64-bit)

### Steps to reproduce
The issue can be reproduced here: https://plnkr.co/edit/IIxfuRtUopxOo38U

### Expected behaviour
Translations registered with `$translateProvider.translations()` should be displayed immediately and translations fetched with an async loader should be displayed once they are retrieved.

### Actual behaviour
Translations registered with `$translateProvider.translations()` are displayed once the async loader finished loading, generating   _FOUC_.

**Comment by knalli** [comment]
Hi @Agustin-Q 

that's is interesting finding. The feature is really a couple of years old, but no one has issued this one. Unfortunately, the project more or less deprecated as angular (Angular JS 1.x) itself is deprecated also. Speaking of this, you are aware not using the latest versions?

However, you may look into it for a fix. Yes, it looks like the directive should resolve the well-known (static) defined value, but instead waiting for the async loaded one. On other hand, a service call to `$translate(…)` should maybe resolve to the right one? Nevertheless, this would be a breaking change, so I would recommend a flag for this.

The directive is calling the service here with already a couple of flags.
https://github.com/angular-translate/angular-translate/blob/1114534c064eddfb77fc4243b0deb61c37f5f41f/src/directive/translate.js#L294-L299

... which invokes the service function here:
https://github.com/angular-translate/angular-translate/blob/1114534c064eddfb77fc4243b0deb61c37f5f41f/src/service/translate.js#L1124

In detail, these lines wait for the existing (async) load and could maybe modified not waiting for the load.

https://github.com/angular-translate/angular-translate/blob/1114534c064eddfb77fc4243b0deb61c37f5f41f/src/service/translate.js#L1177-L1204

In specific this line 
https://github.com/angular-translate/angular-translate/blob/1114534c064eddfb77fc4243b0deb61c37f5f41f/src/service/translate.js#L1178

"finds" the existing promise.

Feel free providing the solution here or making up a PR. 

Thank you.

**Comment by Agustin-Q** [comment]
Hi @knalli 
Thanks for the detailed response I will look into a possible fix. 
For the time being I think I can use the following workaround with `forceAsyncReload` disabled:
```js
app.run(["$translate", function($translate){
  $translate.onReady(function(){
    $translate.refresh($translate.use());
  });
}]);
```
As I only need to load the async translations once.

Kind regards

**Comment by knalli** [comment]
Tip: If you still have to deal with the time until its loaded, you may have a look at [$translate.onReady()](https://angular-translate.github.io/docs/#/api/pascalprecht.translate.$translate#methods_onready) or [translate-cloak](https://angular-translate.github.io/docs/#/api/pascalprecht.translate.directive:translateCloak).
