### ISSUE TITLE
$translateStaticFilesLoader should behave gracefully when one of translations cannot be loaded

### ISSUE THREAD

**Issue by a-bronx** [angular-translate/angular-translate#1918]
An AngularJS app needs to support user customizations, and for that it provides two locations for translations, say: `/i18n/default/{langID}.json` and `/i18n/custom/{langID}.json`. The `$translateProvider` is configured to attempt loading translation files from both locations and merge them, so that custom strings override default ones:
```js
    $translateProvider
        .useStaticFilesLoader({
            files: [
                {  prefix: "i18n/default/", suffix: ".json" },
                {  prefix: "i18n/custom/", suffix: ".json" },
            ]})
```
When users want to customize some strings, they are supposed to add their [partial] translation files into the custom folder, but never modify default files. This is required to make app upgrades easier: an installer is free to upgrade default translation files when moving to a next version, but it must preserve all user's customizations.

The custom location has no user translations in the beginning, and the $translateStaticFilesLoader is supposed to handle this situation gracefully, providing default translations. But instead it fails to provide any translation at all.

The core issue here is that the `$translateStaticFilesLoader` uses `$q.all()` which rejects when any of loads fails.

Perhaps, this could be resolved easily if `$http` request [returns an empty object `{}` instead of calling `$q.reject`](https://github.com/angular-translate/angular-translate/blob/master/src/service/loader-static-files.js#L56), propagating the error and completely breaking the chain. Even better if this could be configurable via `options`, e.g. :

```js
    $translateProvider
        .useStaticFilesLoader({
            files: [
                {  prefix: "i18n/default/", suffix: ".json"},                   // must fail if missing
                {  prefix: "i18n/custom/", suffix: ".json", optional: true },   // must not fail if missing
            ]})
```

**Comment by knalli** [comment]
Hi @a-bronx,

we likely will not add new features this library any more, AngularJS is out-of-support for some time. However, I recommend to have a look into our [documentation regarding the loaders ](https://angular-translate.github.io/docs/#/guide/13_custom-loaders) and especially the source code of the static file loader. Feel free to copy it and build some for your specific needs.
