### ISSUE TITLE
translate events fired before translate occurs

### ISSUE THREAD

**Issue by Grigorius** [angular-translate/angular-translate#196]
This is a plunker that demonstrates this:
the html of the element is not translated when event '$translateChangeEnd' is broadcasted: http://plnkr.co/edit/RoVBXL44Pu3n09NlnRAL

**Comment by xtoff** [comment]
@PascalPrecht @DWand Is there an update on this functionality? I really need to manipulate my DOM elements with the translated text for my current project.. 

Like you said before, you can't fire 200 events after every translate directive, but isn't there a way to emit an event when those 200 events are done?

**Comment by knalli** [comment]
Nope, we have only one event for this.. more or less the situation has not changed due the already known concerns.

Perhaps it would be possible to provide (as part of the directive) a generic hook and/or optional event sender. Anyway, that's not on our map at the moment. Feel free to make a PR.

**Comment by Grigorius** [comment]
I implemented this by just looking at the language - not at when the translation occurs. (When the user selects another language - change DOM accordingly - without waiting for translation to occur) (it may flicker but users don't constantly change language so I think that this is acceptable for most cases)

**Comment by xtoff** [comment]
Mmh, I have also a workaround when I change my language, but I need this when my page is loaded for the first time.. 

To be more specific, I want to execute my custom attribute directive (that does DOM manipulation on translated events) after all DOM elements are translated.
