### ISSUE TITLE
Chinese characters shown as unrecognizable characters when defining the translation table in config.

### ISSUE THREAD

**Issue by jixiangcn** [angular-translate/angular-translate#228]
Thanks for this nice angularjs extension.

the problem is when I load Chinese translation table through <code>$translateProvider.useStaticFilesLoader()</code> it works properly.

but if I set Chinese translation table using <code>$translateProvider.translations('zh-CN',{}) </code> as default language, I will get some unrecognizable characters. the application works but the TEXT is unrecognizable characters.

Any suggestion? or I should do some encode or decode with the translation table?
BTW: I set 'UTF-8' as my character.

**Comment by ricardovalquin** [comment]
Hi Jixiangcn, currently I'm using angular translate for an ionic app, i make the translations 
$translateProvider.translations('en',{list of words});
$translateProvider.translations('es',{list of words});
for english and spanish language, that works so great!!, but now, i need to add a new language, chinese..., how can i add these list of characters for my app?, please help me, i don't understand what do you mean with the all the js loaded with utf-8 encoding, that's no only for the xml and the html??

**Comment by jixiangcn** [comment]
hi Ricardovalquin, 
You should save the js file itself with utf-8 encoding.
With SublimeText, [File]->[Save with Encoding]->[UTF-8]

**Comment by ricardovalquin** [comment]
Ahh ok, thx so muchos, and... Can you bring me a link of the chinesse
characters or what can i do forma that (about to import these character for
an external file or whatever)

**Comment by miukki** [comment]
it doesn't work for me.  in documentation it clearly describes.
