### ISSUE TITLE
How to load translation files in unit tests using $translateStaticFilesLoader?

### ISSUE THREAD

**Issue by szimek** [angular-translate/angular-translate#244]
I'm trying to test a directive that returns a template that uses translate filter. The test works fine if I provide translations via `$translateProvider.translations`, but I'd like to use the same translation files that I use on production. I tried injecting `$translateStaticFilesLoader`, but I only managed to hang karma server...

**Comment by maxmarkus** [comment]
There are lots of stackoverflow threads to that, but this one finally helped me: 
I created a i18nMock.js file which I load in files: [] just before the tests, but after the app, so the declaration of the i18n factory gets overridden by the mock.

```javascript
angular.module('ds.i18n', ['pascalprecht.translate'])
.config(function ($provide, $translateProvider) {
  $provide.factory('customLoader', function () {
    return {
        $get: function(get){ return get; }
    };
  });
  $translateProvider.useLoader('customLoader');
});
````
For reference, this is how my translate factory looks like:
```javascript
'use strict';

angular.module('ds.i18n', ['pascalprecht.translate')

.config(['$translateProvider', function ($translateProvider) {
        $translateProvider
            .useStaticFilesLoader({
                prefix: 'locales/locale-',
                suffix: '.json'
            })
            .registerAvailableLanguageKeys(['en', 'de'], {
                'en_*': 'en',
                'de_*': 'de',
                '*': 'en'
            })
            .fallbackLanguage('en')
            //.useLoaderCache(true)
            .determinePreferredLanguage();
        $translateProvider.useSanitizeValueStrategy('escaped');
    }]);
```
Hope this helps you.

**Comment by septagram** [comment]
Well, I can see why we have to mock data that comes from a remote server, and maybe sort of see why we would prefer to mock the local API responses, but see no reason at all why is it so difficult to load the local static files in our tests. There are tons of valid use cases for that.

I can name you one regarding translations. Recently, a locale file for a language that nobody on the dev team speaks was modified improperly, breaking that locale completely. This might very well happen again, and the language is fairly popular with our users.

**Comment by septagram** [comment]
Well, I can see why we have to mock data that comes from a remote server, and maybe sort of see why we would prefer to mock the local API responses, but see no reason at all why is it so difficult to load the local static files in our tests. There are tons of valid use cases for that.

I can name you one regarding translations. Recently, a locale file for a language that nobody on the dev team speaks was modified improperly, breaking that locale completely. This might very well happen again, and the language is fairly popular with our users.

**Comment by pavelsl** [comment]
@septagram Agree with you.

```
describe('my component', () => {
  let $httpBackend

  const translatinURL = 'app/translation/locale-en_GB.json'
  const translationFile = require('./../../../translation/locale-en_GB')

  let selectedIndex

  beforeEach(() => {
    angular.mock.module('dib')

    inject((
      _$httpBackend_,
    ) => {
      $httpBackend = _$httpBackend_

      $httpBackend
        .when('GET', translatinURL)
        .respond(translationFile)
    })

})
```
