### ISSUE TITLE
Get translation in my JavaScript function

### ISSUE THREAD

**Issue by igorbljahhin** [angular-translate/angular-translate#246]
Hi!

I am trying angular-translate in my project and I successfully set up translations in HTML files using your library. Now I would like to translate messages used in my JavaScript scripts, but the browser reports error message "ReferenceError: $translate is not defined".  How translation service should be accessed from JavaScript?

My function defined in controller.js:
$scope.sendCartByEmail = function() {
   alert($translate('CART_SEND_EMAIL_SUCCESS'));
}

translate-angular imported in app.js as decribed in tutorial:

var app= angular.module('dutyfree', [
    'pascalprecht.translate',
    'ui.bootstrap',
    'ngRoute',
    'dutyfreeControllers'
]);

app.config(['$translateProvider', function($translateProvider) {
    $translateProvider.useStaticFilesLoader({
        prefix: 'js/languages/',
        suffix: '.json'
    });
    $translateProvider.preferredLanguage('en');
}]);

app.controller('TranslateCtrl', ['$translate', '$scope', function ($translate, $scope) {
    $scope.changeLanguage = function (langKey) {
        $app.uses(langKey);
    };
}]);

**Comment by mohanmanis** [comment]
I am also facing the same issue and when i am trying to execute this $scope.sendCartByEmail = function() {
alert($translate('CART_SEND_EMAIL_SUCCESS'));
}

I am getting alert as [object object].

**Comment by davidmartinezros** [comment]
You have to do something like this:

public showIntroductionAlert() {
    this.translate.get("IntroductionAlert").subscribe(
      key => {
        window.alert(key);
      }
    );
  }

Because the get method returns an Observable.

**Comment by bSratUoH** [comment]
How can we translate a text in javascript..
for example if I have a code like below in javascript what kind of keyword can be used to translate this 

`function errorCallback(errorResponse) {
      $scope.loginParams.errorText = 'The username and password that you entered don\'t match.';
      $scope.SigningIn = false;
}`

like in html we are using 
{{'key'|translate}} what will be used in javascript.
