### ISSUE TITLE
Publish 'angular-translate' to the npm registry

### ISSUE THREAD

**Issue by elfreyshira** [angular-translate/angular-translate#255]
It would be nice to have `angular-translate` on npm so that we can use it with [browserify](http://browserify.org/). You already have a `package.json`, so it should be a simple `npm publish`.

Fortunately, nobody has claimed the namespace yet: https://npmjs.org/search?q=angular-translate

**Comment by orizens** [comment]
hi.
I'm trying to require angular translate, but am getting this error with browserify:
```
Error: Parsing file /home/my-project/node_modules/angular-translate/dist/angular-translate.js: Unexpected token (1873:0)
```
please assist.
thanks.

**Comment by knalli** [comment]
Which version you are using?

**Comment by orizens** [comment]
UPDATE: the latest.  
I deleted the node_module directory and npm install it again.  
it works now.  
thank.
