### ISSUE TITLE
Default translation in the markup

### ISSUE THREAD

**Issue by bsr203** [angular-translate/angular-translate#258]
Hello,

I am looking for a way to do default translation in the markup itself. For example, below code

`<span translate="i18n.label.Close">Close</span>`

 will output `i18n.label.Close`

 if the configured locale is not available, I would like to use the supplied value `Close` as default. It doesn't make sense to replace the current content with the translation id.

thanks.

**Comment by sureshvsvb** [comment]
@PascalPrecht, @knalli  - I have the following scenario. I have locale file available but if keys are not available in that locale, i would like to use default/fallback language values. Does angular translate support this scenario ?

**Comment by knalli** [comment]
@sureshvsvb  Please have a look at "fallback languages" http://angular-translate.github.io/docs/#/guide/08_fallback-languages
