### ISSUE TITLE
Unknown provider when using localStorage or cookieStorage

### ISSUE THREAD

**Issue by jonaswindey** [angular-translate/angular-translate#274]
I'm trying to add localStorage as storage provider to store the current language but I'm getting a module error:

http://errors.angularjs.org/1.2.7-build.2027+sha.056c849/$injector/unpr?p0=%24cookieStoreProvider%20%3C-%20%24cookieStore%20%3C-%20%24translateCookieStorage%20%3C-%20%24translateLocalStorage%20%3C-%20%24translate

when adding:

```
app.config(['$translateProvider', function ($translateProvider) {
    $translateProvider.translations('en', translationsEN);
    $translateProvider.translations('de', translationsDE);
    $translateProvider.preferredLanguage('en');

    $translateProvider.useLocalStorage();  // If I comment this the application works but doesn't store current language
}]);
```

I have included all necessary scripts and they are loaded by the browser:

```
<script src="/lib/angular/angular.min.js"></script>
<script src="/lib/angular-cookies/angular-cookies.min.js"></script>
<script src="/lib/angular-route/angular-route.min.js"></script>
<script src="/lib/angular-translate/angular-translate.min.js"></script>
<script src="/lib/angular-translate-storage-cookie/angular-translate-storage-cookie.min.js"></script>
<script src="/lib/angular-translate-storage-local/angular-translate-storage-local.min.js"></script>
```

I'm using angular 1.2.7 (build 2027)

Am I missing something here? 

Thanks

**Comment by Purus** [comment]
Spend lot of time today to figure this out.

I have edited the Wiki page at https://github.com/angular-translate/angular-translate/wiki/Multi-Language

Please let me know if this is the correct thing to update.

**Comment by tspaeth** [comment]
@Purus  Sorry. No. That is - as mentioned on the index page - the old manual for Version 1.x :-)

The current docs are here: http://angular-translate.github.io/

They're generated from https://github.com/angular-translate/angular-translate/tree/master/docs

**Comment by Purus** [comment]
Submitted a PR. Thanks.

**Comment by worldspawn** [comment]
I dont get why local storage has a dependency on the cookie storage. I didn't need angular-cookies and to use this lib i now do for reasons that are quite unclear.

**Comment by tspaeth** [comment]
cookie storage is a fallback for client browsers that don't implement LocalStorage.

**Comment by worldspawn** [comment]
Ahh OK. Makes sense
