### ISSUE TITLE
Discussion: complete dist-download package for "end users" / docs improvements

### ISSUE THREAD

**Issue by tspaeth** [angular-translate/angular-translate#288]
Hi!

I'm currently setting up a new customer project and collect all the necessary dependencies and modules.
As bower and the "node ecosystem" is not always used in companies (and some developers come from the java world like me ;-) ) and the docs currently link to source-release packages, it might be very useful for end-users to have a dist directory or zip file with translate + modules (Yes, I've seen #135 ) - somewhere for download.
The "cluttered" bower angular-translate projects in GitHub don't make it easy to download it with one click. 

What do you think, @PascalPrecht @knalli @DWand?
Shouldn't we provide a "all-in-solution" also as downloadable archive? 
Also, the docs lack the actual links to these repos.

**Comment by knalli** [comment]
Ongoing.

**Comment by knalli** [comment]
Closing fast-forward. There will be both a tarball and zip file (of `dist/`) attached to the next releases.
