### ISSUE TITLE
$translate service not working for partial loading

### ISSUE THREAD

**Issue by egervari** [angular-translate/angular-translate#306]
Hi there,

I am trying out angular-translate, and for the most part, I think it's a pretty cool module for angular.

I am having trouble though with partial loadings. Like a lot of people who posted here in other threads, $translate() - when called in a controller just after a part has been loaded - does not actually return the correct translation. Instead, it just returns the key for the translation.

```
$translatePartialLoader.addPart('welcome');

$rootScope.title = $translate("WELCOME.TITLE"); // returns 'WELCOME.TITLE', and not 'Welcome'
```

Now, I am assuming that the translation tables haven't been loaded yet, because when I go away from that screen and return, the $translate service returns the correct result.

And I do have the event to call $translate.refresh() enabled, as per your documentation. I've tried this with and without, but the same behaviour occurs. If I do not include this event as indicated in the documentation, then none of the translations work - even the directives.

Like many others have said, $translatePartialLoader.addPart() needs to return a promise object so we can use $translate() when the tables have been loaded.

As it stands, I think I am either forced to avoid partial loading, or I will have to preload all of the translations in my module's config in every place where my application is calling the $translate service directly.

Of course, directives work perfectly with partially loaded i18n data. The problem is only with calling $translate().

I would appreciate any timely assistance.

**Comment by rogercoder** [comment]
@tspaeth 

I did your trick of adding:

`$translateProvider.use('en'); `

to the app config section. It makes LennyLip's plunkr work, and it made my app work ... but only if I didn't also have:

`$translateProvider.fallbackLanguage('en');`

in the config section. Setting the fallbackLanguage led to the problem coming back: the translation part I attempted to add in the controller was not working.

Oddly enough, in the plunkr it still works even with the fallbackLanguage() call.

I see this issue is closed ... is that because it will be fixed in the next release? It would be nice if the guide (which is very well done, by the way) included a warning about using the partialLoader's addPart() method in a controller ... I just wasted half my afternoon!

**Comment by doppio** [comment]
+1. I just spend 3 hours trying to figure out why my app wouldn't work either like any of the examples I could fine online. Roger, thank you for your comment. I removed my fallback language and my JSON was loaded.

Also, why do we need to call $translateProvider.use() if we have a preferred language set? Shouldn't this be the language used if no other language is specified? This seems like it should be a very high-priority bug.

**Comment by shiruken1** [comment]
I've just spent a day at this, and although I wish the prior posts would've helped, I'm still stuck. I would appreciate any advice.

My config:
```
	angular.module('app.config').config(function($translateProvider) {

	    $translateProvider.useSanitizeValueStrategy('escapeParameters');

	    $translateProvider.useLoader('$translatePartialLoader', {
	      urlTemplate: '/lang/{lang}/{part}.json',
	    });
	    
		$translateProvider.use('en');
    	$translateProvider.preferredLanguage('en');

        $translateProvider.fallbackLanguage('en');
    });
```

After my routes config:
```
	angular.module('app.routes').run(function ($rootScope, $translate, $translatePartialLoader) {

		$rootScope.$on('$stateChangeStart', function(event, toState, toParams, fromState, fromParams){

			var app = toState.name.indexOf('.');
			if(app !== -1) {

				var part = toState.name.slice(app+1, toState.length);
		    	$translatePartialLoader.addPart(part);

		    	var from = fromState.name.indexOf('.');
				if(from !== -1) {

					var old_part = toState.name.slice(app+1, toState.length);
		    		$translatePartialLoader.deletePart(old_part, true);
				}
			}

		});

		// refreshes the view, having loaded the translation tables
		//@TODO: FOUC issue
		// $rootScope.$on('$translateChangeSuccess', function () {
		$rootScope.$on('$translatePartialLoaderStructureChanged', function () {
			$translate.refresh();
		});

	});
```

The translation filter works. Passing it as an attribute works. Interpolation works.

...yet I can't use the service at all:
```
	    	$translate('TEST').then(function(out) {
	    		$log.info('out: '+out);
				vm.test = out;
	    	});

                $scope.$on('$translateChangeSuccess', function() {
	    		$log.info('out: '+out);
			vm.test = $translate('TEST');
	    	});
```

Neither one of these give me anything. Please help!

**Comment by knalli** [comment]
@shiruken1 Please make a new issue, and provide your code as demo (i.e. using plnkr.co). Thank you
