### ISSUE TITLE
Overrule current language

### ISSUE THREAD

**Issue by pdwinkel** [angular-translate/angular-translate#309]
Use case:
Current language is set to Dutch by the user.
User opens a confirm dialog (with Dutch texts) and selects the OK button.

I like to log the activity of the user in English independent of the language chooses by the user.

So I created the following method:

```
$translate.overruleLanguage = function(lang, translationId, interpolateParams, interpolationId) {
   var current$uses = $uses;
   $uses = lang;
   var translation = $translate(translationId, interpolateParams, interpolationId);
   $uses = current$uses;
   return translation;
};
```
Then I call it like this:
```
   $translate.overruleLanguage('en', dialogMessageId, dialogMessageValues);
```
It is just a hack, but shows the functionality I need.

**Comment by scriby** [comment]
+1

**Comment by knalli** [comment]
Please follow #500 -- closing this as a duplicate.

**Comment by utkant** [comment]
I have a case where I would like the possibility to tell the translate tag which language to use. 

Like so:

<p translate="keyHere" translate-language="ScopeVariableHere/LanguageKeyHere">

Hope this will be taken into consideration when creating this.
