### ISSUE TITLE
Insert new translations to part at runtime.

### ISSUE THREAD

**Issue by Shakeandbake** [angular-translate/angular-translate#316]
I have a very large set of translated values which the page would only use a small subset of based on query results and business logic. Some key example keys would be Q50285, QA303 etc. I would like to add these to the partial loader under a specific 'part' at run time when resolving a promise from a rest call. The standard translate provider seems to merge tables when calling translations('lang', moreData) but the partial loader simply replaces the table with the newly provided. Can the partial loader setPart be changed to also perform a merge?

**Comment by knalli** [comment]
@DWand  Is still something open here? Should we migrate missing features into a separated topic?

**Comment by DWand** [comment]
@knalli, there was nothing said here for about a year. I'd like to said against this feature. But, however, it could be easily implemented if needed. The only thing is that we should think about events fired by this method.

Additional thoughts:

* The `setPart` method was initially designed as a replacement of the `$translate.translations` method (it becomes useless with the `$translate.refresh` method).
* As I understand, there is only one source of truth in the partial loader now - the server. Adding this method we'll introduce a new one - a user.
* It is impossible to restore a translation table of the part after deletion if it was changed this way.
* This functionality can be implemented in a custom loader.

**Comment by knalli** [comment]
As part of v3, we can rethink the architecture including new events (i.e. like `translations changed`). It's more or less already available as a result of several other events.

I won't add this feature in v2 anyway. But improvements to the partial loader are still weoclome -- filed into a new issue.
