### ISSUE TITLE
$translateStaticFilesLoader and $translateUrlLoader are not available from browserify

### ISSUE THREAD

**Issue by NickHeiner** [angular-translate/angular-translate#333]
I am using browserify to pull in this module. I have the following in my app:

```js
$translateProvider.useStaticFilesLoader('/some/url.json');
```

This causes the following error:

```
Error: [$injector:unpr] Unknown provider: $translateStaticFilesLoaderProvider <- $translateStaticFilesLoader <- $translate
http://errors.angularjs.org/1.2.7/$injector/unpr?p0=%24translateStaticFilesLoaderProvider%20%3C-%20%24translateStaticFilesLoader%20%3C-%20%24translate
```
(Full stack trace omitted for clarity, but I can add it if need be.)

I get the same error when trying to use $translateUrlLoader.

Investigating this, I saw that package.json declares index.js to be the main:

```js
{
  // ...
  "main": "index.js",
  // ...
}
```

When I investigate `index.js`, I don't see any definitions for the missing services. It looks like someone ran a concat script and just forgot to update it when those services were added?

I can help you create a better build system if you'd like, but if you're not interested in that I just wanted to let you know that this issue existed.

**Comment by knalli** [comment]
One year later: Is this still a topic? We have not changed the specs, but perhaps the tools are better. I've found debowerify so far, it would solve the problem using the available bower packages?

**Comment by mchambaud** [comment]
@knalli I would very much like to be able to use angular-translate plugins with browserify. Currently only the main module will work out-of-the-box.

**Comment by knalli** [comment]
@mchambaud Does debowerify be an option for you?

**Comment by knalli** [comment]
How about this strategy? https://github.com/angular/angular.js/pull/10732

**Comment by mchambaud** [comment]
@knalli I'd rather use NPM all the way. Why not create an NPM package for each angular-translate module, each package can then have it's own package.json with main script. 

At the moment I'm referencing the ./node_modules/.../angular-translate...js in package.json browser field which is not very scalable but works.

**Comment by knalli** [comment]
Technically, this would mean a npm module for every bower shadow repository -- but not bower-angular-translate because this one already exists. And this one actually contains everything already. I'm just feeling something would be wrong. ;)

**Comment by mchambaud** [comment]
You currently have the following repositories:

- angular-translate
- bower-angular-translate
- bower-angular-translate-storage-cookie
- bower-angular-translate-loader-url
- bower-angular-translate-loader-static-files
- bower-angular-translate-loader-partial
- bower-angular-translate-interpolation-message-format
- bower-angular-translate-storage-local

This means you can easily install individual plugins using Bower but you cannot using NPM. You could change the your repositories to:

- angular-translate
- angular-translate-storage-cookie
- angular-translate-loader-url
- angular-translate-loader-static-files
- angular-translate-loader-partial
- angular-translate-interpolation-message-format
- angular-translate-storage-local

And have a bower.json as well as a package.json files in each repositories. Packages would then be individually installable via Bower or NPM, which means people would be free to use which ever technology they want, including Browserify.

**Comment by NickHeiner** [comment]
That solution sounds great to me! :smile:

**Comment by knalli** [comment]
Yes, but this means a significant internal change spliting everything ins module. Don't me wrong, I'm fully with this as I'm also unhappy with this bower shadow repository. 

But's not done in some moments..

**Comment by mchambaud** [comment]
You could also add one package.json per plugins in the main repository to make them installable via npm

**Comment by mchambaud** [comment]
Pull-Request:

- [angular-translate-storage-local](https://github.com/angular-translate/bower-angular-translate-storage-local/pull/8)
- [angular-translate-storage-cookie](https://github.com/angular-translate/bower-angular-translate-storage-cookie/pull/3)
- [angular-translate-loader-url](https://github.com/angular-translate/bower-angular-translate-loader-url/pull/4)
- [angular-translate-interpolation-messageformat](https://github.com/angular-translate/bower-angular-translate-interpolation-messageformat/pull/7)
- [angular-translate-loader-partial](https://github.com/angular-translate/bower-angular-translate-loader-partial/pull/17)
- [angular-translate-loader-static-files](https://github.com/angular-translate/bower-angular-translate-loader-static-files/pull/17)

**Comment by knalli** [comment]
Wow, thank you. 

Obviously we have to change the repo. But that is no problem.

Should we not declare dependencies? However, I'm not sure about the correct usage via browserify (transitive dependencies).

**Comment by mchambaud** [comment]
Using this with browserify means the user will

```
npm install angular-translate-storage-local --save
```

and in his code 

```
require('angular-translate-storage-local');
```

Browserify will know which javascript file to include from package.json "main" field.

**Comment by mchambaud** [comment]
It would be even better if each modules exported it's name! But it would mean injecting each module into the app definition.

**Comment by knalli** [comment]
> It would be even better if each modules exported it's name! But it would mean injecting each module into the app definition.

Currently this (splitting into dedicated modules) on the map for 3.0. Until now nobody has voted against this.. 

> Using this with browserify means the user will

No, that's not what I meant.

If someone uses `npm install angular-translate-storage-local --save`, it will not work until (s)he also uses `npm install angular-translate --save`. Should we not declare `angular-translate` being a dependency? Would this actually work without additional work by the user/developer?

**Comment by mchambaud** [comment]
The way it is setup right now we need to install angular-translate as well as every angular translate modules required.

IMO, this is ok. angular-cookies does not ship with angular so why would angular-translate-storage-local ship with angular-translate? Or angular for that matter.

**Comment by DWand** [comment]
> angular-cookies does not ship with angular
And vise versa. It is a thing which a don't like in angular - I've already downloaded a framework, but I still need to download additional files and provide additional dependencies to use cookies.

> It would also be a good idea to have different angular modules for each modules
Do you really want to write a long list of angular-translate dependencies in each of your applications? A core module, storages, error handlers, loaders, interpolators...

**Comment by DWand** [comment]
@knalli, I like the idea to separate things to different entities. But is it possible to keep these entities in one module? Just to avoid long lists of dependencies of the application module. However, I feel that I probably misunderstand something. Do we talk about separate files (which is okay), separate npm modules (which is also okay) or separate angular modules (which I don't like)?

**Comment by mchambaud** [comment]
@knalli There is no reason to install an optional angular-translate module unless you're already using angular-translate. Besides, package.json could/should have a dependencies for angular-translate. 

@DWand @knalli nothing stops us from having an index file which loads all other angular-translate modules. Modularization, if done right, allows for everybody to be happy =)

**Comment by knalli** [comment]
Well, angular-translate is NOT optional when requiering angular-translate-anything-else.

**Comment by mchambaud** [comment]
@knalli I will update the *package.json* to have angular-translate as a dependency.

**Comment by knalli** [comment]
The time flies (away). The *v3* will be take some time, so we can at least publish the satellite shadow repositories with local copies of the library.

@mchambaud You have already did some work and published the repositories.. that's okay. But I want to care take on this on release time, so I need at least full publish access to all npmjs projects you have initially created. My nick is `knalli` just like to be verified in https://www.npmjs.com/package/angular-translate/. Thank you!

**Comment by mchambaud** [comment]
@knalli added you on all npmjs

**Comment by knalli** [comment]
@mchambaud  Thank you, you have forgot one https://www.npmjs.com/package/angular-translate-loader-static-files

**Comment by knalli** [comment]
Anyway.. all packages except that one are published with latest 2.7.2

**Comment by mchambaud** [comment]
I can't add you on this package, I have contacted NPM's support. There seem to be an issue on their end.

**Comment by mchambaud** [comment]
You should have access to the last one now.

**Comment by knalli** [comment]
Thanks. Published!
