### ISSUE TITLE
Twice $translateLoadingSuccess with $translateStaticFilesLoader

### ISSUE THREAD

**Issue by marcalj** [angular-translate/angular-translate#344]
I have a strange bug, my config:

```
    .config(function ($translateProvider) {
        // Angular translate

        // Configure angular-translate to load static JSON files for each language
        $translateProvider.useStaticFilesLoader({
            prefix: 'i18n/',
            suffix: '.json'
        });

        // Tells angular-translate to use the English language
        $translateProvider.preferredLanguage('en');

        // Tells angular-translate to use the English language if translations are not available in current selected language
        $translateProvider.fallbackLanguage('en');
    })
```

On localhost development the strings keys are not replaced with correct translations. The event ```$translateChangeSuccess``` fires once but the event ```$translateLoadingSuccess```fires twice...

In production (where I have all partials compiled in JS code) the loading fires also twice but the strings are correctly replaced...

Can you help me finding the cause of this bug? I take a look at code but it's hard to read (it's too much compacted for me), maybe you can give me some clues about it...

Thanks!

**Comment by arthurgurov** [comment]
Still not fixed. I can see three requests for the same language file on release 2.6.1.

**Comment by arthurgurov** [comment]
Hey guys, do you plan to handle this issue?

**Comment by knalli** [comment]
@arthurgurov Sorry for the delay. I'm in doubt you are talking about the same issue. Anyway: Could you please make a demo with plnkr? You can use this template: http://plnkr.co/ljSwT7

**Comment by knalli** [comment]
Perhaps this one was improved with resolving #920 and #981.

**Comment by knalli** [comment]
I've prepared an example which works for me: http://plnkr.co/edit/J4aaFc?p=preview

If this do not work for you, please give us a hint!

**Comment by ramseyfeng** [comment]
Still not fixed. $translateLoadingSuccess will be fired twice in 2.18.1.
