### ISSUE TITLE
Use default app language strings as translationId's instead tokens like 'SOME_TEXT'

### ISSUE THREAD

**Issue by jamesandres** [angular-translate/angular-translate#35]
I don't even know if this one is possible. But I sure would love if it were!

My dream is to have the HTML of my pages to be written in the default site language (eg: English), then to only provide the alternate site language translation tables.  That is to say, I should not need to write out the English translation table, because it is right there in the initially loaded HTML.

Example 1.

```
<span translate>This is the easy example. This will work right now.</span>
```

Example 2.

```
<span translate values="{name: 'James'}">Hello {{name}}, alas this does not work right now.</span>
```

The advantages of this approach are:
- Theoretically, faster loading and easier web-crawler integration for the default site language
- Front-end / UI developers can more easily understand the HTML source code
- Reduced bugs and accidentally rendered 'TOKEN_TEXT'

Edit: Forgot to add the ideal translation table.

```
app.config(['$translateProvider', function ($translateProvider) {
  $translateProvider.translations('de_DE', {
    // I don't know German ;-)
    'This is the easy example. This will work right now.': 'Dies ist der einfache Beispiel. Dies wird jetzt arbeiten.',
    'Hello {{name}}, alas this does not work right now.': 'Hallo {{name}}, ach dies nicht gerade arbeiten.'
  });
}]);
```

Thoughts?

**Comment by megahertz** [comment]
If you like to use  'Human strings', you can try [mg-translate](https://github.com/megahertz/mg-translate)
