### ISSUE TITLE
allow $translate service to return objects & arrays

### ISSUE THREAD

**Issue by gruppjo** [angular-translate/angular-translate#352]
Hi,
I was wondering whether it's possible to not only 'translate' strings but also objects & arrays.

Here's what I mean:
I'm using a calendar, namely this one http://arshaw.com/fullcalendar/
Configuration happens in a controller using an object for configuration. Configuring the title format would look something like this:

```
titleFormat : {
     "month": "MMMM yyyy",
     "day": "ddd, d. MMM, yyyy"
}
```

now these formats should depend on the selected language. Therefore I hoped I could just write

```
titleFormat: $translate('TITLE_FORMAT');
```

and provide the appropriate config in my translation. Unfortunately this doesn't achieve what I was hoping. I thought I could bypass this by writing a custom interpolator, but that didn't seem to work either.

What do you think? - Is this something you might include in future releases, or is there another way to achieve this, which I just haven't figured out yet?

**Comment by brunomperes** [comment]
Is requesting an object possible/implemented?

I could find the object return on the docs, when requesting various translation IDs of string as an array, but not when the ID stores an object inside.

**Comment by tspaeth** [comment]
Well, if I understood you right: no, because we support hierachies/tree structures, so that

```
{"key1: 
  {"key1a":"foo",
   "key1b":"bar"
  }
}
```

will be approachable by
key1.key1a - so when or how should the translation module decide when to traverse and when to give back an object to your app?

**Comment by brunomperes** [comment]
Kinda of, I was trying to think of returning all translations in a namespace, for instance:
    {"key1": 
      {"key1a":"foo",
       "key1b":"barr"
       }
    }
so `key` would return the `key1` object

**Comment by maciej-gurban** [comment]
Did this go into development at any point? I was hoping to use nested object like PolyglotJS is using, to manage my translations easier (contain translations of one component's strings in one object). Here's an example from Polyglot's docs:

    polyglot.extend({
      "nav": {
        "hello": "Hello",
        "hello_name": "Hello, %{name}",
        "sidebar": {
          "welcome": "Welcome"
        }
      }
    });

    polyglot.t("nav.sidebar.welcome");
    => "Welcome

**Comment by Zemke** [comment]
I don’t see why this was closed. The array syntax to translate multiple keys is nothing like getting a whole translation object. I think the feature request is still valid, isn’t it?

**Comment by knalli** [comment]
This is a closed issue.

Latest reference and detailed answer is here: https://github.com/angular-translate/angular-translate/issues/1429#issuecomment-192717834

**Comment by gruppjo** [comment]
@Zemke, I think so too but apparently this is not a feature the owner are interested in.

**Comment by Zemke** [comment]
I see the point of focusing on the single purpose of this module. In the project I work in, we use it for something else.

We want to share the backend’s enumerations with the frontend and we generate a localization file for that which hosts JSON replicas of the Java enums that are used in the backend. Here it would be useful to have access on whole structures of data.
But I still see your point, that it’s not the problem you’re trying to solve with this module.

**Comment by bdurrer** [comment]
I got here because I wanted to put list of available formats of an datepicker into an array.
But the workaround is actually really easy enough: Just put the list of date formats into a single string, separate them with something (eg semicolon) and split them after loading.

`$scope.dateFormats = $translate.instant('datepicker.dateFormats').split(';');`

For lists you'll be repeating over them anyway, so you can just use `{{'myEnumNames.' + value | translate}}` inside the repeated part. I can't imagine all too many cases where the absence of this feature would be a big pain?

**Comment by knalli** [comment]
@bdurrer  et al 

We are providing a *translation* library, and neither a localization feature (like currency, date, number formats) nor settings registry. In your definition a translation is one string for another. It can contain variable content (placeholders), but do not have to. 
It is up to you to abuse the system, but do not blame us if it is not fitting your code. ;)

If you want to extend (well, I would likely still prefer the term "abuse") the library with these features, feel free to decorate the service. Either with an AJS decorate (via `$provide`) or do it with a classic wrapper service. Obviously doing this, you are in charge of all consequences of loading stuff, translation formatting, string security concern and data structure issues you will be faced.

A prior statement by made by me was at 7th march here.

I will lock this issue right now.
