### ISSUE TITLE
[2.0] $translate.uses doesn't exist

### ISSUE THREAD

**Issue by morgoth** [angular-translate/angular-translate#386]
It is not possible to call `uses` function on `$translate` service

``` js
$translate.uses
undefined
```

Are the docs outdated or is this a bug?
http://angular-translate.github.io/angular-translate/docs/en/#/api/pascalprecht.translate.$translate

**Comment by isaaclyman** [comment]
As of 2.15.1, it looks like `$translate.uses` has been replaced 1:1 with `$translate.use`.

**Comment by knalli** [comment]
uses() -> use() is a documented breaking change of *2.0.0*.
