### ISSUE TITLE
Message format pluralisation breaks variable replacement

### ISSUE THREAD

**Issue by mozey** [angular-translate/angular-translate#390]
I have a simple demo page that shows off angular-translate variable replacement. If I add a message format pluralisation example to the page the variable replacement breaks and I get the following error:

```
Error: [$interpolate:interr] Can't interpolate: {{'login' | translate:translationData}}
SyntaxError: Expected [0-9a-zA-Z$_] but "{" found.
```

See this plunk:
http://plnkr.co/edit/MKdqgfaVTWvM4vVnqnEx

Uncommenting this line will give the error above:

```
  $translateProvider.useMessageFormatInterpolation();
```

**Comment by varunis** [comment]
@PascalPrecht Thanks! Changing the variable from double {{}} to single {} fixed my problem.
