### ISSUE TITLE
ng-bind-html with translate

### ISSUE THREAD

**Issue by emadd** [angular-translate/angular-translate#409]
I'm fairly certain I've injected the correct dependencies for this, but I'm getting this error...

http://docs.angularjs.org/error/$interpolate/interr?p0=%7B%7BerrorMessage%20%7C%20translate%7D%7D&p1=TypeError:%20Cannot%20call%20method%20%27trim%27%20of%20undefined

for this code in my template...

```
<div id="warning" ng-show="warningMessage!=''" class="alert alert-warning alert-animation">
    <i class="fa fa-asterisk"></i>&nbsp;<span ng-bind-html="{{warningMessage | translate}}"></span>
    <button type="button" ng-click="warningMessage=''" class="close"><i class="fa fa-times"></i></button>
</div>
```

and the resulting html looks like this...

```
<div id="warning" ng-show="warningMessage!=''" class="alert alert-warning alert-animation" style="">
     <i class="fa fa-asterisk"></i>&nbsp;<span class="ng-binding" ng-bind-html="Your profile is currently not published.  &lt;a href=''&gt;Edit Your Profile&lt;/a&gt;"></span>
    <button type="button" ng-click="warningMessage=''" class="close"><i class="fa fa-times"></i></button>
</div>
```

**Comment by outilio** [comment]
Hi all,

I have a similar problem. In my project I used a JSON file for my translations e.q 
<code>
{
  "Next": "Weiter"
}
</code>

If I try to used it in my html part, this works:

<code>
<div>
   <span>{{'Customer' | translate}}</span>
</div>
</code>

My output is "Weiter".

If I try to use this, my output is in each case empty...
<code>
    <div ng-show="Next" class="alert alert-warning">
        <span ng-bind-html="Next | translate"></span>
    </div>
</code>


Have anyone an idea? 

Thanks a lot

**Comment by knalli** [comment]
`Next | translate` is a filter, what should `ng-bind-html` make this better?

**Comment by knalli** [comment]
Oops, discussion => 1362 My fault :(

**Comment by outilio** [comment]
I deleted my entry here. Thanks!

**Comment by kevinchevallier** [comment]
Hey, any chance we can write something like this?
```<span ng-bind-html="warningSpecificMessage || warningDefaultMessage | translate"></span> ```

**Comment by thiagog3** [comment]
@kevinchevallier I think it could help you:

ng-bind="((variable1 || variable2) | translate)"

**Comment by omarcresp** [comment]
<span ng-bind-html="'path.to.text.in.i18n.files' | translate"></span>  doesn't work well. This text is rendering the HTML tags :disappointed: 
(soory if i wrote bad, i speak spanish)
