### ISSUE TITLE
How test ngTranslate

### ISSUE THREAD

**Issue by firehist** [angular-translate/angular-translate#42]
Hey guys,

I have a problem and I'm pretty sure it doesn't come from ngTranslate but I'll try to use your xp.
When I set my configuration of $translateProvider 

``` javascript
.config(function myAppConfig($translateProvider, $routeProvider) {
    $routeProvider.otherwise({redirectTo: '/home'});

    $translateProvider.registerLoader({
        type: 'static-files',
        prefix: 'i18n/',
        suffix: '.json'
    });
    $translateProvider.uses('fr_FR');
})
```

When I run my test files, I get 

``` bash
Error: Unexpected request: GET i18n/fr_FR.json
No more request expected
```

Have you any idea why and how fix this ?

FYI I try ng-boilerplate project on a mac os x env.

Sorry for my bad english and thank you for your reading!

Happy coding!

**Comment by erezcohen** [comment]
Sorry - not meaning to open this as well - however this could be useful:
We took the approach of ignoring the translation loader in unit tests, rather than being forced to modify each of the spec files.
See a simple solution at http://stackoverflow.com/a/29474122/145599.

**Comment by ilkercat** [comment]
@ianmurrays worked for me! ty
