### ISSUE TITLE
Partial Loader failing when preferred language .json files are missing.

### ISSUE THREAD

**Issue by benpriebe** [angular-translate/angular-translate#422]
When I set the $translateProvider to use the partialLoader it crashes and burns when it can't find a file that matches the preferredLanguage rather than gracefully handling that scenario and using the fallbackLanguage.

e.g. 

```
$translateProvider.useLoader("$translatePartialLoader", {
    urlTemplate: "{part}.{lang}.json"
});

$translatePartialLoaderProvider.addPart("app/i18n/shared");

$translateProvider.preferredLanguage("en-AU");
$translateProvider.fallbackLanguage("en");
```

```
/app
    /i18n
        /shared.en.json
        ... missing shared.en-AU.json
```

I noticed that there may be a way to pass in a loadFailHandler for the $translatePartialLoader but can't figure out how to supply that handler and more importantly if that's the recommended way I should be handling this situation.

http://plnkr.co/edit/BlWaG27IbTPioKImLZiM?p=preview

**Comment by knalli** [comment]
@DWand  still open?

**Comment by DWand** [comment]
@knalli, I'd say this one can be closed.
