### ISSUE TITLE
registerAvailableLanguageKeys, can I register with wild card

### ISSUE THREAD

**Issue by newjs** [angular-translate/angular-translate#426]
for registerAvailableLanguageKeys, can i register a language with wildcard for language negotiation? 

<pre>
app.config(['$translateProvider', function ($translateProvider) {
  // add translation tables
  $translateProvider.translations('en_UK', translationsEN_UK)
  .translations('en', translationsEN)
  .translations('de', translationsDE)
  .translations('zh', translationsZH)
  .determinePreferredLanguage()
  .fallbackLanguage(['zh','en']);

  $translateProvider.registerAvailableLanguageKeys(['en', 'de','en_UK','zh'], {
    'en_*': 'en',
    'de_DE': 'de',
    'de_CH': 'de'
  })
</pre>

So when my browser returns en_US, I want that to fall back to en rather than my what defined in my fall back stack.

**Comment by 360disrupt** [comment]
Is it possible to use the wildcard in the first part as well?
```
 $translateProvider.registerAvailableLanguageKeys(['en_*','en'], {
    'en_*': 'en'
  })
```
Otherwise you need to register all available keys?
