### ISSUE TITLE
$translateProvider.determineLanguage does not work on Safari as expected

### ISSUE THREAD

**Issue by mohlendo** [angular-translate/angular-translate#431]
When I use `$translateProvider.determineLanguage` in combination with `$translateProvider.registerAvailableLanguageKeys`, I would expect that the language key `en_US` would match case-insensitive, but it doesn't. 
The following plunker shows that bug. On Safari, no matching language key is found and you see no translation. On Chrome it works as expected.

http://plnkr.co/edit/gFzzNh?p=preview

**Comment by knalli** [comment]
Closing this, we have the open PR (#755). That is still valid.

**Comment by knalli** [comment]
The PR was replaced with a feature named uniformLanguageTag. Preview available [here](http://angular-translate.github.io/docs-canary/#/api/pascalprecht.translate.$translateProvider#methods_uniformlanguagetag).
