### ISSUE TITLE
Error: $compile:multidir Multiple Directive Resource Contention

### ISSUE THREAD

**Issue by Francisc** [angular-translate/angular-translate#450]
Hello,

This error is thrown when translate directive is used inside the template of another directive.

This happens regardless of the priority set on the other directive.

Any idea why this happens?

**Comment by jokermt235** [comment]
> Well, then just put another element like a
> `<div>` around your current template and it works.

My error was about not closing directive right <tes-dir </test-dir> like that <test-dir></test-dir> fixed a problem ))
