### ISSUE TITLE
Consider rewriting angular-translate in ES6

### ISSUE THREAD

**Issue by PascalPrecht** [angular-translate/angular-translate#466]
I really would like to write some ES6 code and was wondering if it would make sense to write the angular-translate code in es6 and transpile it to es3 with traceur or so.

Any opinions on that?

**Comment by knalli** [comment]
Just for the records: Many things happen in the last year. I'm still for this, but there a several steps to go. I'm doing this for my own small angular plugin and I have noted the small things are "expensive".

**Comment by knalli** [comment]
Closing this. ES6+ will be requirement of a rewrite, if this will be.

**Comment by tommck** [comment]
take it a step further and just use TypeScript?
