### ISSUE TITLE
translate filter throws error on null translation key

### ISSUE THREAD

**Issue by totof3110** [angular-translate/angular-translate#468]
I have a translation key stored in a $scope variable which is initially null and is set to its real value during an AJAX call. On initial page load (while the key is null) the page throws:
```
Error: [$interpolate:interr] http://errors.angularjs.org/1.2.14/$interpolate/interr?p0=%7B%7Bdeclarer%20…nslate%7D%7D&p1=TypeError%3A%20Cannot%20call%20method%20'trim'%20of%20null
    at Error (native)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.14/angular.min.js:6:450
    at Object.p (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.14/angular.min.js:75:275)
    at h.$digest (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.14/angular.min.js:102:242)
    at h.$apply (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.14/angular.min.js:105:173)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.14/angular.min.js:115:253
    at e (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.14/angular.min.js:33:421)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.14/angular.min.js:37:77 
```
Which Angular explains as:

>Can't interpolate: {{declarer | translate}}
>TypeError: Cannot call method 'trim' of null

Is there a null check missing in the filter?

**Comment by paxal78** [comment]
Use case: i use grunt-angular-translate with option nullEmpty = true

So: i can put all translations.....run GRUNT and only when i change the NULL values i will see the translations... otherwise all my translation will be blank.... very annoying:)

In my case developer and translation are two different persons

**Comment by tspaeth** [comment]
hm. grunt-angular-translate... @firehist can you help?

**Comment by paxal78** [comment]
my proposal

```
 for (var j = 0, d = possibleLangKeys.length; j < d; j++) {
          var possibleLangKey = possibleLangKeys[j];
          if ($translationTable[possibleLangKey]) {
            if ($translationTable[possibleLangKey][translationId] === null) {
              result = translationId;
            } else if (typeof $translationTable[possibleLangKey][translationId] !== 'undefined') {
              result = determineTranslationInstant(translationId, interpolateParams, interpolationId);
            } else if ($notFoundIndicatorLeft || $notFoundIndicatorRight) {
              result = applyNotFoundIndicators(translationId);
            }
          }
          if (typeof result !== 'undefined') {
            break;
          }
        }

```
       
in detail

```
[....]if ($translationTable[possibleLangKey][translationId] === null) {
    result = translationId;
} [....]
```

**Comment by tspaeth** [comment]
@paxal78 anyway. You're requesting something from/for the grunt-angular-translate, right? 
Please file it here
https://github.com/angular-translate/grunt-angular-translate/issues

**Comment by paxal78** [comment]
no, grunt-angular-translate, is right.

**Comment by knalli** [comment]
@tspaeth  @paxal78  I'm confused. This is an issue.. for what? Not angular-translate itself, but grunt? Right?

**Comment by tspaeth** [comment]
As far as I got that: An issue in the grunt-angular-translate module/tool. Should be closed here after reading the last comment from paxal78!

**Comment by knalli** [comment]
Ok. I was not sure. *close*
