### ISSUE TITLE
Discussion: Develop/release flow

### ISSUE THREAD

**Issue by PascalPrecht** [angular-translate/angular-translate#471]
So there are a few things I wanna discuss with you guys, since a lot of things have changed in the past due to the switch to a separate organization. The code is getting complex and we have to work with several repositories rather than just one. At the same time we have to move forward and try to push angular-translate to the edge of technologies to be prepared for the future :).

So here are the points I wanna discuss with you and I would really like to hear your thoughts/ideas/opinions on them:
- Redesign build process
- Switching from grunt to gulp
- Switching from ngdocs to dgeni
- Automate build/release process
- Consider switching to ES6
- Package manager agnostic repos
## Redesign build process

The current build process is pretty straight forward. However, I think it needs some more love. We should talk about what tasks we really need and how to handle these processes when working with several repositories. This goes hand in hand with the second point.
## Switching from grunt to gulp

You might heard of it, I like it. Gulp is a stream based task runner, which makes build processes faster. There are already plenty plugins and they all do just one thing, which is great. I would like to rebuild our build processes with gulp and kick grunt.
## Switching from ngdocs to dgeni

The great @petebacondarwin is currently building a **very** flexible and extendable document generator called dgeni. It generates templates that represents our docs. Then there's a separate angular app that runs with these templates. We are currently sitting on grunt-ngdocs which did a great job but the following things speak against it:
- we probably switch to gulp, so the grunt plugin doesn't work for us anymore
- grunt-ngdocs is just the ngdoc generator pulled out of the angular source and hardcoded as grunt plugin. It's uses twitter bootstrap and feels kinda buggy in recent versions
## Automate build/release process

So we have several repositories now. We have the source repo, we have a repo for docs and there's a repo for each extension as bower package. We should talk about how to make releases as easy as possible because currently, updating the docs is a pain in the ass. Also pushing the latest source to the package repos is a repetitive task that could be automated. I need help on that.
## Consider switching to ES6

The angular core team does it and I think it's a good thing. I would like to build angular-translate in ES6 too, just to learn about the new syntax. We also don't have to rewrite it in the future, once es6 features land in browsers :)
## Package manager agnostic repos

There are several bower repositories for our extensions and the source itself. We can publish these packages as npm modules too, and there were already a few requests for it. I think we should do it, since it's a win win. But we should consider renaming the repos and make them package manager agnostic. With package manager agnostic I don't mean to remove everything that has too much detail about a package manager, but make them at least work with other package manager (talking npm and bower).

Okay, that's all I have team @angular-translate

**Comment by knalli** [comment]
:ghost: What's up?

**Comment by knalli** [comment]
We don't have and will probably not changing the process.
