### ISSUE TITLE
How to get translated string from $translate service synchronously

### ISSUE THREAD

**Issue by virtualit786** [angular-translate/angular-translate#473]
This is the common pattern to use $translate service.

$translate(translationId).then(function (translatedString) {
                    //Code to use translatedString
                });

But I have the requirement to call it synchronously on many places in the apps.

How would I get the translated string synchronously like for example

var translatedString = $translate(translationId);

**Comment by 9mm** [comment]
This should probably be added here I think: http://angular-translate.github.io/docs/#/guide/03_using-translate-service

I searched around for a good hour. Eventually found this github issue.

**Comment by soluml** [comment]
+1 to adding this to the guide.

**Comment by rodrigobranas** [comment]
+1 works better!

**Comment by mort3za** [comment]
Also we can use it this way: 
```
$filter("translate")("translation_id", {interpolations_params});
```

**Comment by steelx** [comment]
`$translate.instant` returns me `TrustedValueHolderType` instead of a string

**Comment by alejandroiglesias** [comment]
```
$filter("translate")("translation_id", {interpolations_params});
```
That also returns me a `TrustedValueHolderType` instead of a string. How can I fix it?

**Comment by styopdev** [comment]
@steelx @alejandroiglesias 
For getting value from `TrustedValueHolderType`  I used `$sce.valueOf` method
```javascript
var translation = $translate.instant(translationKey);
var translationText = $sce.valueOf(translation);
```

**Comment by arcelan** [comment]
In 2018, we also need this...

**Comment by narek-king** [comment]
@styopdev thank you

**Comment by shlensky** [comment]
In 2019, we also need this...

**Comment by ClausClaus** [comment]
In 9102, we also need this...

**Comment by palfaro91** [comment]
It's 2020, we also need this...
