### ISSUE TITLE
Cookies problem

### ISSUE THREAD

**Issue by miraage** [angular-translate/angular-translate#475]
So, I've added two files:

``` html
<script src="/js/angular-translate.js"></script>
<script src="/js/angular-translate-storage-cookie.js"></script>
```

Then tryied to init:

``` javascript
config.$inject = ['$translateProvider'];
function config($translateProvider) {
    $translateProvider
        .useUrlLoader('/app/crm/locales.json')
        .useCookieStorage()
        .preferredLanguage('en');
}
```

Getting error:
**Unknown provider: $cookieStoreProvider <- $cookieStore <- $translateCookieStorage <- $translate**

What I do wrong?

**Comment by zloy531** [comment]
Hello. Sorry, but I have same problem when use `$translateProvider.useLocalStorage();`:
`Uncaught Error: [$injector:unpr] Unknown provider: $translateLocalStorageProvider <- $translateLocalStorage <- $translate`
I'm include ngCookies:
`angular.module('starter', ['ionic', 'ngCookies', 'pascalprecht.translate'])` and of course add `<script src="lib/angular-cookies/angular-cookies.min.js"></script>`.
Where can be my error?

**Comment by DWand** [comment]
Hello, @zloy531. Can you show a [plunkr](http://plnkr.co/) or something like that?

**Comment by miraage** [comment]
@zloy531 you need to include [angular-translate-storage-local](https://github.com/angular-translate/bower-angular-translate-storage-local).

**Comment by knalli** [comment]
```
 Unknown provider: $translateLocalStorageProvider
```

is a general Angular JS error message meaning there is a missing component (named `$translateLocaleStorage`). 

I'd suggest to read the corresponding [chapter](http://angular-translate.github.io/docs/#/guide/10_storages). 

@zloy531  gives you actually the solution already.

**Comment by Fattouh92** [comment]
I had the same error, i included:
/angular-translate-storage-cookie/node_modules/angular-cookies/angular-cookies.min.js
and
/angular-translate-storage-cookie/angular-translate-storage-cookie.min.js
and it worked. downloaded from npm
