### ISSUE TITLE
Translation doesnt work in Cordova

### ISSUE THREAD

**Issue by davidrehakcz** [angular-translate/angular-translate#480]
Hi,
im developing a mobile application using Cordova apache framework and Angularjs. So far it works great, but today i got stucked with i18n. I have tested few things and ended up with this nice library. Unfortunately, the translation doesnt work when i deploy it to Android platform. Emulating it with ripple-emulator in browsers is just fine, translation works as expected. Have anyone faced similar problem and find a solution?
Thanks in advance.

**Comment by jclalala** [comment]
So we're also on Cordova and angular-translate works fine.

The problem using StaticFilesLoader is as @woodxxman indicated; that the context path of your Android Webview is different from your development environment.

E.g. Under localhost DEV web context,
prefix: '/locales/lang-' <-- would yield http://localhost/locales/lang-

Under your Android Webview context,
prefix: '/locales/lang-' <-- would yield file:///localhost/locales/lang-

So what you want to do is remove the leading '/' so your Android Webview would load,
file:///android_assets/www/locales/lang-

The above is assuming that your index.html is under file:///android_assets/www/

**Comment by knalli** [comment]
I'm not sure if that matches Cordova also, but as an Ionic (which uses Cordova under the hood) every developer should be aware of the different stages http://blog.ionic.io/handling-cors-issues-in-ionic/

**Comment by salvisb** [comment]
This was still relevant in 2016. :) Thanks @jclalala , that worked for me!

**Comment by ourarash** [comment]
Still relevant. In my case, it solved the problem with using ng-translate in ionic. Thanks @jclalala!

**Comment by dfblaze** [comment]
Still highly relevant in 2017 - thank you @jclalala!

**Comment by PYYuriy** [comment]
Hi I use **angular 2** and **ng2-translate**  have little bit another problem :)
 at first time when app run it translation work, but  when I try switch translation it get information from **file:///android_assets/www/index.html/i18/en.json** 
instead **file:///android_assets/www/i18/en.json**
I tried a lot of solution but no one help,
I try create custom loader but it doesn't work 
  getTranslation(lang: string): Observable<any> {
    return Observable.create(observer => {
      let xhr: XMLHttpRequest = new XMLHttpRequest();
      xhr.onreadystatechange = () => {
        if (xhr.readyState === 4) {
          if (xhr.status === 200) {
            observer.next(JSON.parse(xhr.response));
            console.log(xhr.response);
            observer.complete();
          } else {
            observer.error(xhr.response);
          }
        }
      };
      xhr.open('GET', `cdvfile://www/i18n/${lang}.json`, true);

    }).map(res => res.json());
}

does  any know how to solve that problem ?

**Comment by tspaeth** [comment]
@PYYuriy Please file issues on ng2-translate in their repository, this is the angular-translate module. Thanks.

**Comment by luckylooke** [comment]
For Ionic 2 project there is another solution I have mentioned here https://github.com/ngx-translate/core/issues/280#issuecomment-310741710

**Comment by phuwin** [comment]
In my case, when I inspect the phone with webview, it doesn't even load my json file. I checked network tab in the chrome inspector, no error about the .json file not loading... I am so confused now!!

**Comment by phuwin** [comment]
No luck with useStaticFilesLoader, I put the translations as angular constants and inject the translations into config (not the best way to do this but it works).
```
angular.module("app").constant("en",{
	"ADMIN":"Admin",
	"UPCOMING_EVENTS":"Upcoming Events"
})
```	
```
angular.module("app").config (function($ionicConfigProvider,$translateProvider,en,fi){
    var isApp = !document.URL.startsWith('http');
    if (isApp) document.addEventListener("deviceready", onDeviceReady, false);
    else {
      setUpLang();
    }
    function onDeviceReady() {
        console.log("onDeviceReady");
        setUpLang();
    }
    function setUpLang(){
        getLang(function(locale){
			locale = locale.split("-")[0];
			console.log(locale)
			$translateProvider.translations("en",en)
			$translateProvider.translations("fi",fi)
					.preferredLanguage(locale).fallbackLanguage('en').useSanitizeValueStrategy('escapeParameters'); 
			$translateProvider.use(locale)
		})
    }
    function getLang(callback){
      if (navigator.globalization) navigator.globalization.getLocaleName(
          function (locale) {
            if (typeof callback === "function") callback(locale.value);
          },
          function () {
            console.log("Something is wrong. Language is set to english")
            if (typeof callback === "function") callback("en");
          }
      ); else if (typeof callback === "function") callback("en");
    }
})
```

An addition critical is that in device runtime, for some reason angular-translate  doesn't use the preferred locale automatically (eventhough it works perfectly in web browser), I need to add `$translateProvider.use(locale)` after the configuration to make it work in my device

**Comment by knalli** [comment]
This issue is closed, so my answer is short: file new issues if something is new, but don't comment on closed/handled ones.

This is a plugin for AJS, a web developing framework using basic technologies like JS, HTML and maybe CSS. If your setup with loading files is working, we (angular-translate) cannot help you with your specific app. => #1787
