### ISSUE TITLE
Produce an error for missing interpolation arguments

### ISSUE THREAD

**Issue by JeroMiya** [angular-translate/angular-translate#502]
A common bug we've found is when a particular string translation value has interpolation arguments in it, but the code/filter/directive that references that translation id doesn't provide them, or there is a typo in the object that is passed in. Currently, angular-translate does not produce any sort of error when this happens. We'd like the option to fail fast and require all interpolation arguments referenced in the translation value to be specified explicitly, otherwise produce an error.

e.g:
```js
$translateProvider.translations('en', { greeting: 'hello {{name}}!' });

// later

// these promises should be rejected.
var shouldBeRejectedPromise = $translate('greeting', null);
var shouldAlsoBeRejectedPromise = $translate('greeting', { namee: 'oops! typo! but currently no way of knowing short of looking at the UI and the seeing that the string isn't right.' });
```

**Comment by knalli** [comment]
Closing this due inactivity.

In case of a contribution

* should not breaking existing code
* should be aware of other interpolation services (i.e. messageformat)
* perhaps opt-in
