### ISSUE TITLE
HTML escaped characters in translate filter

### ISSUE THREAD

**Issue by zajca** [angular-translate/angular-translate#506]
Hi,
I need nobreakingspace inside translated string and can't figure out how to do it.
if I have in string `&nbsp;` it not parsed in dom it's just string.
I tried unsafe filter and bind-html-unsafe both with same result.

**Comment by lcarva** [comment]
A little late, but if anyone comes across this, using unicode characters will get the job done. Instead of "&amp;nbsp;" use "\u00A0". This is particularly handy for attributes such as placeholder and title.

**Comment by niravparsana94** [comment]
How to remove '&nbsp;' from translated string. My original string doesn't have that.
See this [issue](https://forum.ionicframework.com/t/alertcontroller-word-splits-into-2-words-on-new-line/182353/2).
