### ISSUE TITLE
Translate cache for fast page loading

### ISSUE THREAD

**Issue by tamtakoe** [angular-translate/angular-translate#507]
It is possible use $translateCache as Angular $templateCache. It allow to create plugin like https://github.com/ericclemmons/grunt-angular-templates which can include translations into corresponding module (not only in config phase). It useful for project with lazy loading, when we can use $translatePartialLoader for loading .json for development and cache it .json by $translateCache into one compiled file for build for production.

In case with message format $templateCache can store compiled message format functions like https://github.com/blueimp/angular-localize

f.e. $translateCache.put('locals/en.json', {STR_ID: "String translation", ...})

**Comment by mischkl** [comment]
I guess this can be closed as it was added with [`b685601`](https://github.com/angular-translate/angular-translate/commit/b68560160ea51b07030b0cc0ebc4ece440546ad0)?

**Comment by knalli** [comment]
Yep, that's actually correct ;) Thank you.
