### ISSUE TITLE
$translate service then() callback does not fire for non preferredLanguage

### ISSUE THREAD

**Issue by jshado1** [angular-translate/angular-translate#523]
I set the default language in app.config via

```javascript
$translatePartialLoaderProvider.addPart('i18n');
		$translateProvider
			.useLoader('$translatePartialLoader', {
				urlTemplate: '/{lang}/{part}.json'
			})
			.preferredLanguage('en_US');
```

Then in a central controller, I update a string used for the Window's title:

```javascript
$translate.use( self.locale );
$rootScope.$on('$stateChangeStart', function updateWindowTitle( event , toState , toParams ) {
	$translate( stateTitle ).then(function( string ) {
		$rootScope.windowTitle = $rootScope.windowTitle.replace('{part1}', string);
	});
});
```

The above works fine when the value passed to `$translate.use()` equals the value set in `preferredLanguage()`. When it's different, the `then()` never fires (the translate directive and filter still work fine).

I verified this by changing the string in preferredLanguage() to 'fr_FR' and changed my app to french (fr_FR), and it worked. Changed my app back to english, broken again.

There appears to be a race condition because if I set a breakpoint on [promiseToWaitFor](https://github.com/angular-translate/angular-translate/blob/master/src/service/translate.js#L739) `var promise` and manually click play for every one, it works. But if there's no breakpoint or if I disable the breakpoint after the misbehaving has been handled, the `then()` does not fire.

Ideally I would like to forget about `$translate.uses()` altogether, and just dynamically set the value of `preferredLanguage()` based on the output of a service (which I've resorted to doing in that controller with `uses()`), but that is not possible within app.config because only providers (and app.values and app.constants) are injectable.

**Comment by robertochingon** [comment]
Hi, I have same problem.

**Comment by tspaeth** [comment]
@robertochingon "$translate.uses" <- are you still working on 1.x or is this a typo?
Just to make sure...

And then the question on your error: what's in line "location.js:76" ? Just the $translate('PAGE...) call?

**Comment by knalli** [comment]
I'm in doubt we can do something without breaking anything.

I've already added a note about renaming/enriching arguments with injected functions in #995
