### ISSUE TITLE
Inline templates do not trigger interplation on initial page load

### ISSUE THREAD

**Issue by techjacker** [angular-translate/angular-translate#536]
I'm using this [grunt plugin](https://www.npmjs.org/package/grunt-inline-angular-templates) to inline my templates, however when I do the first page displayed in my app is just blank text.

Once I trigger a different route then the translation happens fine.

Any ideas?

**Comment by psgganesh** [comment]
I use the same in  below way
```html
<ion-tab title="{{ 'coffee_title_label' | translate }}">
```
![image](https://cloud.githubusercontent.com/assets/2221525/11111044/eb9e81ca-8936-11e5-8714-c473b7739424.png)

But when it is 
```html
<ion-tab translate="coffee_title_label" title="{{ 'coffee_title_label' | translate }}">
```
![image](https://cloud.githubusercontent.com/assets/2221525/11111034/cdaa8790-8936-11e5-9408-043d322f0e02.png)

I referred the below plunkr example
http://mcgivery.com/internationalization-of-an-ionic-app-multilanguage-support/
