### ISSUE TITLE
problem using the angular translate binding inside an option element of input select in internet explorer 9

### ISSUE THREAD

**Issue by hagaih** [angular-translate/angular-translate#543]
![ie9problemwith translate binding inside input select inside a bootstrap ui modal](https://cloud.githubusercontent.com/assets/1837474/2875623/b1ca7c90-d421-11e3-88fb-245fa83a484b.JPG)
![ie9problemwith translate binding inside input select](https://cloud.githubusercontent.com/assets/1837474/2875628/c008c942-d421-11e3-86e4-77afcf23d68f.JPG)
I'm using the angular translate binding  in various places in my app and it works great in all browsers but when i'm using it inside an input select  i'm having problems with it in ie 9 since it not getting the translation and when i'm using it  the same way inside an bootstrap ui modal it causing the input select not to work att all.

here is an example of how i'm using it inside the modal template:
![html-select-in-modal-template](https://cloud.githubusercontent.com/assets/1837474/2875704/a4ab3510-d424-11e3-8ec1-d9b2fbfd6e31.JPG)

and in a regular view template i'm using it just like that:
![html-select-in-view-template](https://cloud.githubusercontent.com/assets/1837474/2875741/49b85d58-d425-11e3-8180-636b2b4c28f1.JPG)

looking forward for an help.
thanks hagai.

**Comment by knalli** [comment]
Closing due inactivity.

**Comment by rdukeshier** [comment]
I ran into this same issue on IE 10.  Here's the [plunk](http://plnkr.co/edit/M2dTqMRY44fJEo4Jtvyx?p=preview).  

It appears to only happen when inside a transcluded directive (ng-repeat in my example):
```
<div ng-repeat="item in vm.collection">
  <select ng-model="item">
    <option value="a">{{ 'valueA' | translate }}</option>
    <option value="b">{{ 'valueB' | translate }}</option>
    <option value="c">{{ 'valueC' | translate }}</option>
  </select>
</div>
```
Applying the translate filter in ng-options appears to be a viable workaround:
```
<div ng-repeat="item in vm.collection">
  <select ng-model="item" ng-options="option.value as option.translationId | translate for option in vm.options">
  </select>
</div>
```

**Comment by tspaeth** [comment]
Thanks for the plunk. 
Note to "testers": It's really only reproducible on the IE10 and IE9 and maybe below. Not in the Emulator modes for IE10/9... on IE11. For those don't having one: Grab it on http://modern.ie 

But anyway: I currently don't really have a useful fix in mind :-(
