### ISSUE TITLE
Static file loader / url loader are too rigid

### ISSUE THREAD

**Issue by Narretz** [angular-translate/angular-translate#546]
It appears to me that the structure imposed by static file loader / url loader is too rigid. If you think about it, both do basically the same, but have two different patterns that you absolutely must follow. It's no problem that the variable part of the url is the language tag, but sometimes the language tag in the app is not the same as in your endpoint, e.g. app is de-DE, but endpoint is only de.  Worse, url loader always appends &/?lang=<lang_tag> to the url, why is that? It's not good that the translation engine assumes so much about the architecture. (I know that you can simply specify your own parameter, but it's not very clean). It gets stranger, because the partial loader has another completely different way to specifiy the url, from which both static and url loader could benefit, but it's simply not available to them.

I think static / url loader could basically be amalgated into one loader, barring any technical obstacles. By default, they should use the template matching used in partialLoader. Additionally, the templateUrl should not only accept a string, but a function that has the current language as an argument and returns the finished url. This way, you can have arbitrary urls, for any language.

I know that you can build your own loaders, but this change would make angular-translate simpler and more powerful at the same time.

Thoughts?

**Comment by knalli** [comment]
Perhaps we rethink the loaders again for #995 , but for now -> closing due inactivity.

**Comment by elad** [comment]
Hi,

At the very least, is it possible to make the locale key an optional argument to `useUrlLoader`? So that if only one argument was provided, it will default to the existing behavior, but if there are two, it will behave similarly to `translations()`?

As in:

```
// Current behavior
$translateProvider.useUrlLoader('foo/bar.json');

// Explicitly specify locale
$translateProvider.useUrlLoader('en_US', 'foo/bar.json');
```

If that's okay with you, I'll submit a pull request for it. :)
