### ISSUE TITLE
Multiline strings

### ISSUE THREAD

**Issue by rockstardev** [angular-translate/angular-translate#554]
I have been searching through the docs for past 2+ hours, but I simply can't find information if there is any support for multiline strings.

So, is there? Ideally I would love if there would be an option to automatically replace \n with <br />, but just being able to get strings with \n would be OK too (I would look into writing filter that would replace \n with <br />

**Comment by islavi** [comment]
Regarding the same issue,
I have huge text that I want to translate (terms and condition).
I want to be able to format it in en.json like this:


`

"DESCRIPTION": [

          "<p>Lorem ipsum dolor sit ci nec.</p>",

          "<p>Quis tantas accumsaorreant. Ex eam assum facete.</p>",

          "<p>Discere honestat eu summo sanctus.</p>",

          "<p>Ex unum viris re periculis ex vel.</p>",

          "<p>Id duo dolore signifecing an pro.</p>"
 ]
`


Is there a way to use multiple lines?

**Comment by knalli** [comment]
@islavi Use a single ling/string (even concatenated), but no array of strings.

**Comment by ahayn465** [comment]
I feel as though I am missing something key here! In my translation json I have a key : value pair that contains a span ( or a link or some other markup) like so: 

"forgot" : {  "span" : "Here is some <span>text in a span</span>" }

in the template when I use the directive as mentioned above I get an empty paragraph tag:

<p translate="forgot.span"></p>

Do I need to bind this translate string to innerHtml? I am also looking to include links in my translate strings as outlined in this post: [https://github.com/ocombe/ng2-translate/issues/145](https://github.com/ocombe/ng2-translate/issues/145)

Any tips would be greatly appreciated!

**Comment by knalli** [comment]
@ahayn465  Please do not use already closed issues, especially if your topic has nothing to with the issue's one.

Please include/attach a proper demo, also I think your post is missing something?

Last one: Please have a look at our guide, in your case it is eventually best showed [here](https://angular-translate.github.io/docs/#/guide/19_security).
