### ISSUE TITLE
Provide API to list all languages that are configured by angular-translate

### ISSUE THREAD

**Issue by fischermatte** [angular-translate/angular-translate#566]
For implementing a language chooser, it would be nice to use ng-repeat to iterate over all available languages that are configured in angular translate. For this one need to have an api funcation that provides all configured languages.

Initiated through here: http://stackoverflow.com/questions/23659748/how-to-list-all-languages-that-are-loaded-by-angular-translate/

**Comment by davidbeijinho** [comment]
for me its not working I getting
TypeError: Object function (translationId, interpolateParams, interpolationId) { .... ..} has no method 'getAvailableLanguageKeys' 

I try
Once could just say something like:

$translateProvider.registerAvailableLanguageKeys(['en', 'fr', 'de', es']);
And later at runtime:

$translate.getAvailableLanguageKeys();
/// returns ['en', 'fr', 'de', 'es']

**Comment by tspaeth** [comment]
@davidbeijinho True. This functionality has not been implemented yet.

**Comment by davidbeijinho** [comment]
ok, thanks

**Comment by JobaDiniz** [comment]
Is this implemented? If no, why this issue is closed?

**Comment by tspaeth** [comment]
@JobaDiniz : Because #618 was to be the PR, but that one did not make it as it is. If you're interested in providing a PR - we're happy if you jump on - see #618 for remarks on current problems.

**Comment by cyberkatze** [comment]
+1

**Comment by fxck** [comment]
Yes, this would be useful.

**Comment by Aides359** [comment]
@knalli @PascalPrecht May I take it that with [`return $availableLanguageKeys;`](https://github.com/angular-translate/angular-translate/blob/master/src/service/translate.js#L895) I could use (apart from feeling really dirty with calling _register_ as a getter) `registerAvailableLanguageKeys()` to get the registered languages?

Edit: I just relaized that `registerAvailableLanguageKeys` is only available on the provider :\

Any updates on that issue?

**Comment by tspaeth** [comment]
@Aides359 Please don't commit on old, closed defects.

But anyway, since yesterday you can use

https://github.com/angular-translate/angular-translate/commit/3988af0

- see the release notes for 2.11.0

**Comment by kishmiryan-karlen** [comment]
@PascalPrecht I think this should be included in the documentation.
