### ISSUE TITLE
Translate attributes with translate directive

### ISSUE THREAD

**Issue by red-0ne** [angular-translate/angular-translate#568]
Actually, the only way to translate elements attributes is through the translate filter. Is there a particular reason to not having a directive for that?

`<any translate-attr-my-attr="'TRANSLATION_ID'"></any>` could be a great feature.

**Comment by sochka** [comment]
How do I translate an attribute only but not tag contents? See what I'm saying:

```
      <span
            translate translate-attr-title="CLONE_THIS_WIDGET">
        <i class="glyphicon fi-page-copy"></i>
      </span>
```

This replaces the inner content of `span` tag entirely , probably trying to translate it.

**Comment by armyofda12mnkeys** [comment]
Just curious, reading how attributes are added here... 
Can you set default values for the translation attributes via something like a 'translate-attr-default-placeholder' attribute like so:

<input type="text" ng-model="refine.selection" translate translate-attr-placeholder="refine.list.type" translate-attr-default-placeholder="Type here to refine the list" />
