### ISSUE TITLE
Plural Function not found for locale: pl 

### ISSUE THREAD

**Issue by tpluscode** [angular-translate/angular-translate#569]
Hi

I'm getting the above error when setting Polish locale. I don't understand where this is coming from. I tried using the plural format, but it also happens if I use the select format in my translation. Hence it seemingly comes out of nowhere...

Thanks,
Tom

**Comment by cazacugmihai** [comment]
If I have a site translated in 10 languages, I need to import each language when a page is accessed? Ex:

```
<script src="path/to/messageformat/locale/1st-lang.js"></script>
<script src="path/to/messageformat/locale/2nd-lang.js"></script>
<script src="path/to/messageformat/locale/3rd-lang.js"></script>
...
<script src="path/to/messageformat/locale/10th-lang.js"></script>
```

I thought that all I need to to is to import only the default language script (ex: 1st-lang.js), than the others will be loaded asynchronously (when user switch the language), by these helpers:

```
<script src="../bower_components/angular-translate/angular-translate.js"></script>
<script src="../bower_components/messageformat/messageformat.js"></script>
<script src="../bower_components/angular-translate-interpolation-messageformat/angular-translate-interpolation-messageformat.js"></script>
<script src="../bower_components/angular-translate-loader-url/angular-translate-loader-url.js"></script>
<script src="../bower_components/angular-translate-loader-static-files/angular-translate-loader-static-files.js"></script>
<script src="../bower_components/angular-translate-storage-cookie/angular-translate-storage-cookie.js"></script>
<script src="../bower_components/angular-translate-handler-log/angular-translate-handler-log.js"></script>
```

Thanks,
Mihai

**Comment by zymtx5g79k** [comment]
Is there any ideas?

**Comment by tspaeth** [comment]
Ideas on what?

**Comment by zymtx5g79k** [comment]
I can't find root of problem, seriously! It looks too difficult for me. Is there an example file with roles to get proper pluralization?
I have dictionary files.
**en.json**
```
{ "have": "You {count} {count, plural, one{time} few{songs} other{times}}" }
```
**cmn_TW.json**
```
{ "have": "You {count} {count, plural, one{time} few{songs} other{times}}" }
```
And translate provider.
**translate_provider**
```
function translate_provider($translateProvider) {
  var locale = 'en';
  $translateProvider
    .registerAvailableLanguageKeys(['en', 'cmn_TW'], {
      'en_US': 'en',
      'en_UK': 'en',
      'cmn_TW': 'cmn_TW'
  })
    .useMessageFormatInterpolation()
    .preferredLanguage('en')
    .fallbackLanguage('en')
    .useSanitizeValueStrategy('escape')
    .useLoader('translationLoader', { locale: locale })
    .use(locale);
}
```
I have error after call `$translate.use('cmn_TW');`
I can change language, save and reload page. It works with new language after reload page only ):

**Comment by zymtx5g79k** [comment]
Foubd! message-format/src/locales.js (https://github.com/format-message/message-format/blob/master/src/locales.js). Thanks all (:
