### ISSUE TITLE
Directive should not output translation key when it can't be found

### ISSUE THREAD

**Issue by bra1n** [angular-translate/angular-translate#588]
So, I've started working with angular-translate today (great project, really helpful!:)) and noticed the different ways to use it in a view template.
One such way is the following:
```
<header translate="header.title"></header>
```
Let's say I also use asynchronously load my translation files, and it seems that when the translations are still loading, it will output `header.title` while waiting for the translation, just as if I had written:
```
<header translate>header.title</header>
```
This is fine for the above scenario and I know that I can use translate-cloaked in order to (at least) hide it, if I wanted. But here is another way to achieve the same thing:
```
<header translate="header.title">Here's some header placeholder text</header>
```
What I would expect here is that while the translations are loading / not accessible, that the module would simply leave my placeholder text there, and in case of an error (ie because the language file doesn't exist) fail silently instead of spewing out the translation key and overwriting my readable placeholder. Is there a specific reason for this behaviour or something that I'm missing? Because I think it would make developing readable template code (with inline fallback-placeholders) a lot easier, especially when using namespaced translation keys that are not exactly user-friendly. :)

**Comment by aklauza** [comment]
Hi,

I am not sure what was the outcome for the initial issue. In the following code, is it possible to leave the text as is when header.title is not found?
```
<header translate="header.title">My title in my home language</header>
```
By default, this is not happening. From a user point of view, I believe it is better if the user sees "My title in my home language" than "header.title" in the browser. It is also the default behaviour that other i18n tools follow (like cakePhp i18n). I am not sure why $translate does replace text when there are no valid translations.

Thanks

**Comment by dietergeerts** [comment]
I think that default behavior is really good to pick up the parts that still need to be translated. But for what you want, it would be nice to have an options of a default value in case it's not found in the form of an extra attribute maybe?

**Comment by aklauza** [comment]
I don't think default behaviour should be with developer interests in mind, but user experience. There is  an `angular-translate-handler-log` specifically developed to log everything that is missing.

Regarding the default-value, I think there is something like that already implemented, and I don't think is a valid solution, as it clutters the code, and makes it "less HTML". My point is, why do I have to worry to add `translate-default` attributes everywhere when there is already a default text in the HTML that is being completely ignored?

**Comment by dietergeerts** [comment]
I get your point, though we use this differently. We just put our key on the place where the text will come, instead of some default value. We then provide translations files for both the default/fallback language and the others. It's easier and as the keys are all UPPERCASE, it's easy to identify where they are and see if everything is translated....

**Comment by knalli** [comment]
And this https://github.com/angular-translate/angular-translate/issues/588#issuecomment-45726733 is still valid.

> However, I do think that we could actually apply your expected behaviour, that when a translation is not found and there was content inside of an element, keep it.

We can introduce a global configuration setting for the directive which could do exactly this one. But we will not change the API (at least before a hypothetical 3.0). We like PRs!

**Comment by aklauza** [comment]
Ok, so I understand it is possible to introduce that config option and default it to false so it keeps doing exactly the same as always and it is still compatible with earlier versions. In this case, I would only have to change the flag to get my expected behaviour.

**Comment by knalli** [comment]
Link to #986

**Comment by knalli** [comment]
Closing as being dup. And a PR is welcome always.

**Comment by Muphet** [comment]
topic closed, problem not solved. got exactly same issue

**Comment by tspaeth** [comment]
@Muphet There is a link to #986 which is still open and this one was closed as duplicate. Please comment on the open defects if there is any additional information to be added. Thanks.
