### ISSUE TITLE
Put line breaks inside translatable string

### ISSUE THREAD

**Issue by suarezjulian** [angular-translate/angular-translate#595]
Hi, first of all thanks for this great library, I started using it a couple of days ago, and I like it very much so for.

I have a couple of translations that need line breaks on a translatable string. I've tried adding \n and </br>, but none seem to work, are they supposed to work? is there any quick way of doing this?

thanks

**Comment by hohwille** [comment]
Just as a feedback: using HTML markup is bad for security as it opens the door for injections. Allowing newlines would be safe when using in pre or verbatim tag.

**Comment by xiaolei** [comment]
`\n` will show as line break if you apply below style to the element:
`white-space: pre-wrap`

**Comment by elron** [comment]
I've created a pipe for this, I wrote an answer here: https://stackoverflow.com/questions/35999185/angular2-pipes-output-raw-html/51236958#51236958

**Comment by foluis** [comment]
> `\n` will show as line break if you apply below style to the element:
> `white-space: pre-wrap`

```
<div style="white-space: pre-line;">
     {{content}}
</div>
```
