### ISSUE TITLE
Teach angular-translate optional language info section

### ISSUE THREAD

**Issue by PascalPrecht** [angular-translate/angular-translate#604]
I would like to push https://github.com/angular-translate/angular-translate/pull/262 forward, maybe we can specify how things should work.

So the basic idea is to define a special namespace in a language file to store additional information, about the language itself like for example the language direction.

This could look like this:

``` json
{
  "__": {
    "direction": "rtl",
    "something": "else"
  },
  "ID": "foo bar"
  ...
  ..
}
```

The `$translate` service could then provide a method like `getLocaleInfo()` which returns that object (so we have to make sure that `__` is not flattened). I could also imagine that it expects an optional parameter to request specific information like `getLocaleInfo('direction')`.

Based on that there could be a `translate-locale-direction` (or sth.) that toggles a css class on its element depending on what `direction` is.

Any thoughts? @knalli @tspaeth

**Comment by knalli** [comment]
-> v3 maybe, but definitely not in v2.

Closed due #1671
