### ISSUE TITLE
Teach angular-translate pluggable fallback handler

### ISSUE THREAD

**Issue by PascalPrecht** [angular-translate/angular-translate#605]
Based on https://github.com/angular-translate/angular-translate/pull/330 this, we can introduce pluggable fallback handler.

I'd like to push this forward. The only thing I wanna add, is that we should make sure that `$translateProvider.fallbackLanguage()` still works. In case someone uses `.fallbackLanguage()` **and** `useFallbackHander('foo')`, the fallback handler would override `.fallbackLanguage()` (or at least, it's preferred).

Any thoughts on designing this one?

**Comment by knalli** [comment]
@DWand The extraction of the existing into a dedicated plugin would be possible addition for 3.0.0. What do you thing? Perhaps like the currently closed  #330 (yours), but based on the current code.

**Comment by DWand** [comment]
I still think that this is a nice and flexible feature.

But I'd like to avoid implementing it to the current architecture of the module. It is hard to predict the impact of such changes to 1818 lines of code. At least, I think, it affects translation "resolution" methods (`$translate()`, `instant()`), `refresh()` method and initial language loading.

**Comment by knalli** [comment]
Closing due #1671.

Already part of architecture proposals.
