### ISSUE TITLE
translate does not work with useStaticFilesLoader

### ISSUE THREAD

**Issue by bastoune** [angular-translate/angular-translate#606]
I want to use translation with angular and I followed this tutorial :
http://www.ng-newsletter.com/posts/angular-translate.html

I load those two files:

```
<script src="js/angular/angular-translate.min.js"></script>
<script src="js/angular/angular-translate-loader-static-files.min.js"></script>
```

**html**

```
{{ 'SORTBY' | translate }}
```

When I do the follow, translation works :

```
$translateProvider.translations('en', {
                SORTBY: 'sort by'
              })
              .translations('fr', {
                SORTBY: 'trier par'
              });
```

Now I want to do this :

```
$translateProvider.useStaticFilesLoader({
                prefix: '/languages/',
                suffix: '.json'
            });
```

I do well load the files as my console network shows me the GET success with the right content which is :

**en.json**

```
SORTBY: "Sort by"
```

**fr.json**

```
SORTBY: "Trier par"
```

It shows :

SORTBY

Do you have any idea ?

**Comment by Ferhnir** [comment]
Hi guys, thy that example not working in plunker?
http://plnkr.co/edit/c7LMLI?p=preview

**Comment by tspaeth** [comment]
@Ferhnir please don't comment on closed issues if reporting something new. Instead, open a new one. Thanks.
