### ISSUE TITLE
Storage Docs not clear on dependencies

### ISSUE THREAD

**Issue by JobaDiniz** [angular-translate/angular-translate#607]
I'd want to use local storage, so I opened the docs (http://angular-translate.github.io/docs/#/guide/10_storages) and it describes that local storage depends on cookie storage, so I downloaded both and added to my app.
However, the docs don't tell anything about ngCookie from angular. So, I had to actually download the angular-cookie, and then add it as a dependency module.

I think the docs could be more clear on that.

**Comment by knalli** [comment]
The docs has been updated.
