### ISSUE TITLE
Docs about error handling in the partial loader needed

### ISSUE THREAD

**Issue by DWand** [angular-translate/angular-translate#628]
According to the https://github.com/angular-translate/bower-angular-translate-loader-partial/issues/8 issue we have to add docs about an error handling in the partial loader. We don't have a word about it neither in the API reference nor in the Guide section of the documentation.

**Comment by DWand** [comment]
See #1005

**Comment by DWand** [comment]
Ping @knalli.

**Comment by knalli** [comment]
Ah, that was not the list. Possible for a 2.7.1, too. ;)
