### ISSUE TITLE
SecurityError: Dom Exception 18 is thrown when local storage/cookies are blocked in Safari on iOS 7.1.2

### ISSUE THREAD

**Issue by nbaronov** [angular-translate/angular-translate#629]
Hello,

Please note an unhandled  SecurityError exception is thrown, resulting in Angular crash, when storing something in local storage on Safari on iOS 7.1.2  with blocked cookies (Settings > Safari > Block Cookies > Always). I guess disabling cookies also disables local storage. With other two choices of block cookies setting ("From third parties and advertisers" and "Never") everything works fine.

The issue occurs on angular-translate-storage-local.js, line 25:

``` javascript
    var hasLocalStorageSupport = 'localStorage' in $window && $window.localStorage !== null;
```

and more specifically while accessing $window.localStorage to check if it is null.

I was able to fix this by moving access to $window.localStorage  inside the try block (lines 28-30)  like this:

``` javascript
    var hasLocalStorageSupport;
    try {
      hasLocalStorageSupport = 'localStorage' in $window && $window.localStorage !== null;
      var testKey = 'pascalprecht.translate.storageTest';
      $window.localStorage.setItem(testKey, 'foo');
      $window.localStorage.removeItem(testKey);
    } catch (e) {
      hasLocalStorageSupport = false;
    }
```

With above change the code never stores anything (since it can't), but at least Angular doesn't crash. I don't like silent failures like this one,  but I'm not sure how to handle this within angular-translate. Maybe an event should be emitted ...

Please let me know what do you think.

Please note this is a repost of closed angular-translate/bower-angular-translate-storage-local#4, requested by @PascalPrecht.

**Comment by JackieWYB** [comment]
After removing the block cookie settings from safari, works like a charm. thanks @nbaronov .
