### ISSUE TITLE
Specify browser requirements

### ISSUE THREAD

**Issue by knalli** [angular-translate/angular-translate#635]
As already happening in #627 und #630, we have to specify more clearly which browsers _must_ work and which ones _should_ work. If we drop a specific browser (group), we should have mention this in the change log.

**Comment by tspaeth** [comment]
Shall we have a further discussion on this or leave it as thrown in? 
The FF10 outerHTML issue just popped up in a project again... :-)

**Comment by knalli** [comment]
As already in #995 mentioned: we make as easy and define the support = AJS official ones.
