### ISSUE TITLE
Support for "namespaced elements"

### ISSUE THREAD

**Issue by spencerwi** [angular-translate/angular-translate#641]
First of all, great lib. I like how simple it is to use.

The one thing that does bug me a bit is when I have big/deep pages, having to use constantly retype long nested-namespace translation ids like this whenever I want to properly scope my translations using namespaces:

    DASHBOARD.TABS.CHEFREQUESTS.SEARCHMODAL.USETHISITEM

It'd be nicer if I could use a directive on an element to "pre-build" parts of that tree; so I'd have have something like this:

    <div translate-namespace="DASHBOARD">
        ....
        <div translate-namespace="TABS">
            ....
             <div translate-namespace="CHEFREQUESTS">
             ....
                 <div translate-namespace="SEARCHMODAL">
                     ....
                     <a class="btn" translate>USETHISITEM</a>
                     ....
                 </div>
                 ....
             </div>
             ....
        </div>
        ....
    </div>

That way, I don't have to constantly repeat giant long nested namespaces, but I can still namespace my translations to keep them scoped to specific uses.

**Comment by bcldvd** [comment]
+1

**Comment by knalli** [comment]
Landed already in canary.
