### ISSUE TITLE
overriding stored language via URL

### ISSUE THREAD

**Issue by epeleg** [angular-translate/angular-translate#667]
I had the following request:
To be able to provide a link to my site that will "force" a specific language based on the URL.

So I need  a clear what to define the order in what the language is resolve and in my case it should be:

1. If URL has language then use language extracted from URL [and store it] (should allow different schemata for embedding the language in the URL (e.g. - as sub domain, as path fragment, as query param or even just generally as a sub string)
2. If the language was previously stored use that language.
3. use some default language

I do understand that some people would prefer to switch 1 and 2 but I think having 1 as a higher priority is more easy to understand an use.
possibly there should be a way to specify if you want to use 1 before 2 or after if (or even have both - such as saying if I have "forceLang" query param in the URL it should be the strongest, then use stored value if exists then use "lang" query param from the URL and if none of those helps use "en".

I was trying to implement reading the language from the URL on my own but I had the following issue:

When using localStorage it would seem that by design it forces the language to what was already stored. So trying to just read the URL and use the language from it would cause double display (flicker) - first of the previously used language and then of the newly "used" language (parsed from the URL).

I could not drop the $localStorage because I DID want to to store the language from the URL.

Eventually what I did was to create a new angular-translate-storage-local-with-url-override.js uses the $localStorage as a dependency. on first request to read from $STORAGE_KEY it looks into the URL and if it finds any of my site's supported languages it would store that language using the $localStorage. 

This is the code it uses:
```js
angular.module('pascalprecht.translate').factory('$translateLocalWithURLOverrideStorage', [
  '$window',
  '$translateLocalStorage',
  '$STORAGE_KEY',
  function ($window, $translateLocalStorage,$STORAGE_KEY) {
	var store=$translateLocalStorage; 
	
	var readFromURLOnce=false;
    var localWidthURLOverrideStorageAdapter = function () {
    	if (readFromURLOnce) return store;
    	else return {
    		get:function(name) {
    			if ((readFromURLOnce==false) && (name == $STORAGE_KEY)) {
    				for ( locale in {'en_US':1,'ru_RU':1,'he_IL':1}) {
    					if (document.location.href.indexOf(locale)!=-1) {
    						//alert('overriding with' + locale);
    						readFromURLOnce=true;
    						store.set($STORAGE_KEY,locale);
    						break;
    					}
    				}
    			}
   				return store.get(name);
    		},
			set:function(name,value) {
				store.set(name,value);
				readFromURLOnce=true;
			}
    	};
    }();

    return localWidthURLOverrideStorageAdapter;
  }
]);
```
even though this works for me I know it is not written for general use...
a public solution might go along the lines of providing a clearer set of prioritized language resolvers      as I previously mentioned. or could be one of the following [which would help circumvent the current issue]:

Allowing a write only storage model so that the site can use something like this within it config:
```js
if (null!=(lang=extractLangFromURL())) {
        $translateProvider.useWriteOnlyLocalStorage();
        $translateProvider.use(lang);
}
else {
        $translateProvider.useLocalStorage();
}
```
[this has the disadvantage of having to include the JS files of both storage systems]

Allowing a language override to be passed to the storage model so that the site can use something like this within it config:
```js
if (null!=(lang=extractLangFromURL())) {
        $translateProvider.useLocalStorage(lang);
}
else {
        $translateProvider.useLocalStorage();
}
```
or have useLocalStorage also handle null gracefully and use:
```js
$translateProvider.useLocalStorage(extractLangFromURL());
```
or even allowing to provide a function that will look into the URL and determine if the language needs to be overridden.
```js
$translateProvider.useLocalStorage(extractLocalFromURL);
```
I hope this is clear enough.

**Comment by knalli** [comment]
Closed due inactivity.

The specific feature "overriding stored language via URL" can be done by the user/developer on its own aligned the corresponding configuration of angular-translate. We are not against a contribution in general, but I'm not seeing the benefit right now.
