### ISSUE TITLE
useStorage and promise

### ISSUE THREAD

**Issue by ojacquemart** [angular-translate/angular-translate#687]
I am trying to implement a custom storage like in the docs: http://angular-translate.github.io/docs/#/guide/11_custom-storages

In my app, the language is defined by a web service which returns user preferences.

What I tried to do: 

```
.factory('LangStorage', function($q) {
    return {
        get: function(name) {
            var defer = $q.defer();
            defer.resolve('en');

            return defer.promise;
        },
        set: function(name, value) {
        }
    }
})
```

It does not work. I have a http call to http://localhost:9001/assets/locale/[object%20Object].json
This is a draft to illustrate my use case. Instead of a handy promise, I call a rest api with restangular.

If the LangStorage#get returns a string, then it works.

So how can I use a promise to resolve the user language?
Or maybe, is there another way to do it?

Thanks in advance.

**Comment by juristr** [comment]
> The docs you're linking to are outdated.

@PascalPrecht Oh..didn't know, just found them on Google and they didn't seem to be obsolete (last edit on September 2014)

> So as already mentioned, asynchronous storage support is not given in angular-translate...

That's fine, there are other ways to do it. The only thing as mentioned are the docs that tend to mislead. Maybe they should be removed or at least place a notice with a link to the correct ones.

**Comment by knalli** [comment]
> Oh..didn't know, just found them on Google and they didn't seem to be obsolete (last edit on September 2014)

:( Lesson learned: Updating a wiki footer results into updating each wiki page on GitHub...

> Maybe they should be removed or at least place a notice with a link to the correct ones.
We should remove the articles which are outdated.. then they will disappear in the index.

**Comment by juristr** [comment]
> :( Lesson learned: Updating a wiki footer results into updating each wiki page on GitHub...

oh, I see.. :smile:

**Comment by knalli** [comment]
Adding a note for changing to promises in 3.0.0

Closing this, referencing by superior #995
