### ISSUE TITLE
Fallback, StaticLoader and FOUC-Prevention lead to wrong request

### ISSUE THREAD

**Issue by Hirse** [angular-translate/angular-translate#689]
After reading the Guide I have built a setup using the StaticFilesLoader.
To prevent FOUC, I defined `en` locale in JavaScript and plan to keep the other languages as json-files.
I am using `.determinePreferredLanguage()` to get the locale automatically and `.fallbackLanguage('en')` to use English if the determined language cannot be found.
```javascript
.config(['$translateProvider',function ($translateProvider) {
    $translateProvider
        .translations('en', {
            "title": "en_title",
        })
        .useStaticFilesLoader({
            prefix: 'strings-',
            suffix: '.json'
        })
        .fallbackLanguage('en')
        .determinePreferredLanguage();
}]);
```
Even though the english language is already defined, the StaticFilesLoader fires a request for `strings-en.json` regardless of the preferred language.
If the locale is en, the provided translations are used, but the request remains.
If the locale is one that I have as json, two requests are made and the json-translation is used.
If the locale is one that I don't provide, two requests are made - both fail - and the strings are left untranslated.

While the first two cases are just non-optimal, the third one is a real problem.

**Comment by knalli** [comment]
This is resolved in next release, dup #981 3be14df
