### ISSUE TITLE
support for markup inside translated strings

### ISSUE THREAD

**Issue by lanterndev** [angular-translate/angular-translate#69]
Sometimes you need to translate something like:

``` html
<p>If your download does not begin automatically, <a href="...">click here</a>.</p>
```

Or even just:

``` html
<p>Another translated string with just a <em>tiny</em> bit of markup inside it.</p>
```

Seems like a common use case but didn't see it documented, so I thought I'd open a ticket.

What's the best way to achieve this? You could divide the single translated string into three parts (e.g. `before_markup`, `inside_markup`, `after_markup`), but this doesn't scale to more nested markup:

``` html
<p>Then I asked, <q>Did you just say <cite><a href="..."><q>nested markup</q></a></cite>?</q></p>
```

In a case like this, it would be nice to include everything in the `<p>` element in a single translated string, and each translation would include the necessary contained markup. Is this possible?

`ng-bind-html` and `ng-bind-html-unsafe` can be used to include sanitized or unsanitized markup. Do they help? Ideally the angular-translate-injected markup could also support live angular behavior too:

``` html
<p>To open now, <a ng-click="handleOpen()">click here</a>.</p>
```

Is that possible?

Thanks for reading, and thanks for the great work on angular-translate!

**Comment by mikkark** [comment]
The original question was also about using links and actually I'm not able to get that to work. I have a situation where I would like to feed the href url from the scope using curly braces. I have a plunker here: http://plnkr.co/edit/8eArYIXlcpybRqfhwcsl?p=preview. This is probably more a question of understanding how Angular works.

**Comment by tspaeth** [comment]
As of the current version (please don't refer or use to 2.0.0 anymore as it is very old now), you can use it in the directive (your second example) this way:

```
<div translate="TESTING" translate-compile translate-values="{'redirectUrl':redirectUrl}"></div>
```
