### ISSUE TITLE
Interpolation in directive not working as expected

### ISSUE THREAD

**Issue by fredericsureau** [angular-translate/angular-translate#701]
Hi there ! Great work on angular-translate !

It seems that interpolation inside the translate directive does not work as expected when using dynamic values :
http://plnkr.co/edit/istRyNxQP0cLmv3b3ZdC?p=preview

According to documentation, it is supposed to work :
http://angular-translate.github.io/docs/#/guide/05_using-translate-directive

**Comment by mchambaud** [comment]
I have translations which do not work anymore in 2.6.0

#####Works
`{{ 'hello.world' | translate }}`

--

`<span translate="{{'hello'}}.world"></span>`

#####Does not work
`<span translate>{{'hello'}}.world</span>`

######Example

[Plunker](http://plnkr.co/edit/mKXQoNJqkd4GYaOAT366)

**Comment by tspaeth** [comment]
With 2.6 the second example at least works this way:

```
<span translate>{{message + '.world'}}</span>
```

**Comment by mchambaud** [comment]
Sure does, but why is the following broken in 2.6?

`<span translate>{{'hello'}}.world</span>`
