### ISSUE TITLE
Translate directive not working in SVG on Safari

### ISSUE THREAD

**Issue by creat-or** [angular-translate/angular-translate#717]
Hi!

I have the following problem: It seems that the translate directive is not working in Safari inside an SVG text element. In Chrome it works as expected. The filter works in Safari, too.

Demo: http://plnkr.co/edit/Hxz0XNTvmqI8Wz3MWqEB?p=preview

**Comment by pedrosanta** [comment]
Yep, got that issue too. Using the translate filter works though.

**Comment by Pumpuli** [comment]
This is still broken in IE. Reason is the same: https://github.com/angular-translate/angular-translate/blob/92bc9551279fc2f5bc7daaedebc87adede8b3713/src/directive/translate.js#L118 SVG elements don't have outerHTML. Or at least they didn't have, and that's still true in IE11.

**Comment by rcollette** [comment]
We're seeing that using data-translate directive does not work in Chrome either, despite the applied fix.

**Comment by Aides359** [comment]
From the linked SO post adding [this polyfill](http://stackoverflow.com/a/20559830/4068027)

```
Object.defineProperty(SVGElement.prototype, 'outerHTML', {
    get: function () {
        var $node, $temp;
        $temp = document.createElement('div');
        $node = this.cloneNode(true);
        $temp.appendChild($node);
        return $temp.innerHTML;
    },
    enumerable: false,
    configurable: true
});
```

seems to fix this.
