### ISSUE TITLE
Use fallbackLanguage when using determinePreferredLanguage

### ISSUE THREAD

**Issue by mrzepinski** [angular-translate/angular-translate#721]
When I use `determinePreferredLanguage` I would like to use `fallbackLanguage` or any other special defined fallback when determine methods retruns locale code which is not in my available langague keys.

@PascalPrecht is there any way to achive that?

For now I defined smth like this:

```
$translateProvider.useStaticFilesLoader({
    prefix: 'resources/translations/',
    suffix: '.json'
});
$translateProvider.useLocalStorage();
$translateProvider.useMissingTranslationHandlerLog();
$translateProvider.registerAvailableLanguageKeys(
    ['pl', 'en'],
    {
        'en*': 'en',
        'pl*': 'pl',
        '*': 'en' // must be last!
    }
);
$translateProvider.fallbackLanguage('en');
$translateProvider.determinePreferredLanguage();
```

and it works well, but it will be better to define it :)

**Comment by feefk** [comment]
Thanks a lot!!!

**Comment by tandibar** [comment]
Hi, this "fix" really helped me. I think it is counter intuitive that `determinePreferedLanguage` is able to return a locale which is not in defined available language keys.
Or is there a misunderstanding here? I wonder why this issue is closed.

**Comment by knalli** [comment]
A preferred language is the requested language one, but not an actual available or selected one.

**Comment by tandibar** [comment]
Ok, but if i call `determinePreferedLanguage()` it will internally set the language to the determined language, or am I wrong? It will at least set what is returned by `$translateProvider.preferredLanguage()`.

I had a problem with this code:
    $translateProvider
      // see: http://angular-translate.github.io/docs/#/guide/09_language-negotiation
      .registerAvailableLanguageKeys(['en', 'de'], {
        'en_US': 'en',
        'en_UK': 'en',
        'de_DE': 'de',
        'de_CH': 'de'
        })
      .determinePreferredLanguage();

      // interpolation for pluralization
      $translateProvider.addInterpolation('$translateMessageFormatInterpolation');

In a polish Browser the last line will fail with `Plural Function not found for locale: pl_PL` which leads me to the assumption that `determinePreferredLanguage()` is setting something internally. If I change the code to (as suggested by @mrzepinski):

    $translateProvider
    // see: http://angular-translate.github.io/docs/#/guide/09_language-negotiation
    .registerAvailableLanguageKeys(['en', 'de'], {
      'en_US': 'en',
      'en_UK': 'en',
      'de_DE': 'de',
      'de_CH': 'de',
      '*': 'en'
      })
    .fallbackLanguage('en')
    .determinePreferredLanguage();

    // interpolation for pluralization
    $translateProvider.addInterpolation('$translateMessageFormatInterpolation');

everything works fine. So in this case `determinePreferredLanguage()` will not return or set pl.

**Comment by 5night** [comment]
<img width="433" alt="screen shot 2017-03-21 at 6 18 26 pm" src="https://cloud.githubusercontent.com/assets/2508769/24142962/1f4328d4-0e63-11e7-8cb5-89db9d192e6a.png">

add ".fallbackLanguage("zh_CN");" in init.js fix this
