### ISSUE TITLE
Get a translation during config phase

### ISSUE THREAD

**Issue by johannesjo** [angular-translate/angular-translate#742]
Is there any way to access a translation inside a config block, e.g.:

```
   // does not work because there is no filter available
    .config(function (datepickerConfig, datepickerPopupConfig, $filter)
    {
        datepickerPopupConfig.clearText = $filter('translate')('CLEAR');
    })
```

**Comment by fedotxxl** [comment]
If you do really need translations inside config phase do following:

1. Configure angular-translate in `preload` module
2. Share `$translate` service (`window.$translate = $tranlate`)
3. In `run` method of `preload` module bootrap your main application (`angular.bootstrap(document, ["app"]);`)
4. In your application replace $translate module:  
   ````
.factory("$translate", function () {
        return window.$translate;
    })
   ````
5. `$translate` will be same for both applications. You can use `window.$translate` in your config phase (or share it other way)

This worked for me

**Comment by Sadi-1992** [comment]
hi, angular is a lot of new stuff for me. 
I have to translate the Name and description of a widget, too. But i dont really understand what i have to do. can u Show me your solution on an example? which files have i to modify? 

Im really confused.... heres my question on stackoverflow:
http://stackoverflow.com/questions/41018345/how-to-filtertranslate-config-widget-title-in-angular-blur-admin

**Comment by cronosreloaded** [comment]
You can use the filter right in the HTML:

 {{ datepickerPopupConfig.clearText | translate }}
