### ISSUE TITLE
how it works together with the angularjs-i18n datepicker

### ISSUE THREAD

**Issue by ericq** [angular-translate/angular-translate#749]
Hi,

Your component works great by itself. I have one question regarding how it works together with the datepicker from http://angular-ui.github.io/bootstrap/. The datepicker relies on the angularjs-i18n. After I used the angular-translate, everything else works expected except for the datepicker. 

Can you shed some light? either I need to find something different to replace the datepicker, or they can work together if I do it in the right way? 

/Eric

**Comment by sandeepthomas** [comment]
@ericq , can you explain how you integrated angular-translate with ui-datepicker? thanks
