### ISSUE TITLE
Default Text when key is not available

### ISSUE THREAD

**Issue by zaidchauhan** [angular-translate/angular-translate#761]
Hello,
`<span translate="SCREEN1_TITLE">Default Text</span>`

When 'SCREEN1_TITLE' is not available, it showing me SCREEN1_TITLE on screen. I like to see 'Default Text' on screen. How can i achieve this ?

**Comment by knalli** [comment]
landed as fcd6b3e

**Comment by gsaandy** [comment]
should be add support for `$translate.instant` ?

**Comment by tspaeth** [comment]
@gsaandy Please don't comment on very long, closed tickets. In case this feature doesn't work on instant, please open a new ticket within the system. Thanks.

**Comment by alphapilgrim** [comment]
@knalli were the docs ever updated for this? wanted to reference this for my team.

**Comment by knalli** [comment]
See here #1427 (Contribution welcome) :)
