### ISSUE TITLE
i18n by key-value scheme

### ISSUE THREAD

**Issue by hyzhak** [angular-translate/angular-translate#778]
I have RESTful API which return object and objects with i18n values inside, scheme look like that for each object:

```json
{
  "name": {
    "en-US": "name_in_english",
    "zh-TW": "name_in_traditional_chinese"
  },
  "address": {
    "en-US": "name_in_english",
    "ua-UA": "name_in_ukranian"
  }
}
```

I'm not sure that current implementation of *angular-translate* can deals with such structures. But what about to define what's comes inside of *translate* directive. If comes string - should works like it works right now, but if object with keys like locales comes - we should consider it like tiny dictionary and get right value by current language, sure with fallback and interpolation.

# Update
We have huge number of user generated objects and only few languages

**Comment by knalli** [comment]
Closing due inactivity.

I see here mainly two different topics:

# The proposal of unloading (partly refresh?) which can be done as a PR.
# Different kind of translations loading. Well: For this case everybody can build its own `customLoader`.
