### ISSUE TITLE
Tool request

### ISSUE THREAD

**Issue by frodefi** [angular-translate/angular-translate#783]
I have an app that I would like to translate. I use WebStorm and surround the text with angular-translate needed stuff. It would then be cool if there was a angular translate tool that could spit this for-translation-text out in a json file. And it could just use the text fragment as both the property and the value for the english (original) json file (which I could then just send for translation).

Maybe there is such a tool? If not, I hereby request it :) If I only had some more time myself...

**Comment by zygimantus** [comment]
So, is there a tool to do this?

**Comment by knalli** [comment]
We have no dedicated tool.

Have a look at  https://github.com/angular-translate/grunt-angular-translate for some build support.
