### ISSUE TITLE
Ionic popup title text can't be translated

### ISSUE THREAD

**Issue by jorool** [angular-translate/angular-translate#806]
Hello!

I'm building an Ionic app in portuguese and english.
angular-translate works fine in the all app, except in popup title text.
This code
`$ionicPopup.alert({
  title: "{{'INFORMATION' | translate }}",
  template: "{{'SEQUENCE_NUMBER_PRESENTATION_1' | translate }}"
});`
produces this when "pt-br" is selected
![image](https://cloud.githubusercontent.com/assets/939515/4891573/8080cb86-63a9-11e4-9d85-fe6aac52b5e2.png)
and this when "en" is selected
![image](https://cloud.githubusercontent.com/assets/939515/4891591/b800908c-63a9-11e4-9f86-abec7c9806f0.png)

Is this a possible bug?

**Comment by jacop85** [comment]
title: $filter('translate')('HELLO_WORLD'),

**Comment by apiening** [comment]
Thanks @jacop85, that works for me!

**Comment by amanthaIsuru** [comment]
Thanks @jacop85 . It also worked for me. You have to added it controller like this in my case

`.factory('AuthService', [ '$filter', '$http', '$base64','Session' ,'$state', '$location', 'ApplicationSettings', '$ionicPopup', 'USER_ROLES', '$rootScope',
 'refreshTextFields','$ionicLoading', function ($filter, $http, $base64,Session ,$state, $location,ApplicationSettings , $ionicPopup, USER_ROLES,  
  $rootScope , refreshTextFields,$ionicLoading, $$translate) {`

The order of the parameters does matter  i.e if you added the $filter at the end it will give some error like TypeError : blah blah

**Comment by oshitha123** [comment]
@knalli 

How can apply custom css class for $ionicPopup.alert

**Comment by SakthiSureshAnand** [comment]
could anyone please post a link which shows pure ionic app able to change the different language also I want to show some contents in "TAMIL" ..., in my app..,
