### ISSUE TITLE
translationId from an expression does not get updated correctly when it doesn't exist in translation data

### ISSUE THREAD

**Issue by mjamin** [angular-translate/angular-translate#807]
Consider the following:

    <span translate="{{foo}}"></span>

    foo = 'something thats not in the translation data';

If I subsequently change `foo` to something else, the directive still shows the original value and doesn't reflect the model changes.

I think this line is the culprit, but I don't have any idea what to do about it, or what the performance implications are if the unwatch were to be removed:

https://github.com/angular-translate/angular-translate/blob/d8a5060b2273f699fa75e32d7a73e5f62aab670c/src/directive/translate.js#L168

**Comment by knalli** [comment]
This demo shows it is working: http://plnkr.co/edit/5RxzDR1vWnTEg2bZBGN0?p=preview

Please reopen if this is still not working for you
