### ISSUE TITLE
Use bower-angular-translate-* with RequireJS

### ISSUE THREAD

**Issue by ti-dev** [angular-translate/angular-translate#817]
I am using angular-translate with RequireJS and it works fine. Now I want to integrate some of these bower packages which are all in the same way structured (use the module `pascalprecht.translate` and add a `factory`):
- angular-translate-cookie-local
- angular-translate-cookie-storage
- angular-translate-loader-url
- angular-translate-loader-static-files
- angular-translate-loader-partial
- angular-translate-interpolation-messageformat
- angular-translate-handler-log

But I am not able to use one of these, because I get errors and I do not know how to integrate it with RequireJS. In my `main.js` in paths and deps are all defined.

In my `app.js` I have

```
define(['angular', 'ngTranslate', 'ngTranslateMessageFormat'], function (angular) {
  return angular.module('myApp', ['pascalprecht.translate'])
});
```

So this seems to be okay, because I see that the ngTranslateMessageFormat JavaScript file is loaded correctly (head section of HTML).

But how to integrate it in here:

```
define(['app'], function (app) {
  app.config(['$translateProvider', function ($translateProvider) {
    // …
    $translateProvider.addInterpolation('$translateMessageFormatInterpolation');
  }]);
});
```

I get the error, `[$injector:modulerr] Failed to instantiate module myApp due to: ReferenceError: '$translateMessageFormatInterpolation' is undefined at Anonymous function (line with $translateProvider.addInterpolation('$translateMessageFormatInterpolation');) …`

How can I integrate these bower packages in ma AngularJS application using RequireJS?

**Comment by httpete** [comment]
messageformat.en is the problem here, relying on embarrasing globals. A wrapper will fix this

// utisl/MessageFormatWrapper.js
define([
    'messageFormat'
], function (MessageFormat) {
    // create a global variable
    window.MessageFormat = MessageFormat;

    // also return the module so it can be used in other AMD modules from here
    return MessageFormat;
});


and then:

        messageFormatEn: {
            deps: ['./utils/MessageFormatWrapper']
        },

**Comment by mnishihan** [comment]
@httpete You saved my day. I was banging my head for hours while trying to load locale files using requirejs along with messageformat and using the wrapper actually solved the issue.

**Comment by httpete** [comment]
Glad to help @mnishihan
