### ISSUE TITLE
Regression test fails against latest AJS 1.3.2

### ISSUE THREAD

**Issue by knalli** [angular-translate/angular-translate#822]
```
pascalprecht.translate $translateDirective (single-lang) passing translation id as content should return translation when used as an element FAILED
    Expected 'TRANSLATION_ID' to be 'foo'.
    @/home/travis/build/angular-translate/angular-translate/test/unit/directive/translate.spec.js:156:9

    Expected 'BLANK_VALUE' to be ''.
    @/home/travis/build/angular-translate/angular-translate/test/unit/directive/translate.spec.js:160:9
```

``` js
      it('should return translation when used as an element', function () {
        element =$compile('<translate>TRANSLATION_ID</translate>')($rootScope);
        $rootScope.$digest();
        expect(element.text()).toBe('foo');

        element = $compile('<translate>BLANK_VALUE</translate>')($rootScope);
        $rootScope.$digest();
        expect(element.text()).toBe('');
      });
```

(https://github.com/angular-translate/angular-translate/blob/ad14d88307160c5f86c3552d414d1d8a5174d2b1/test/unit/directive/translate.spec.js#L153-L161)

Failed starting with 1.3.2

(Example full log: https://travis-ci.org/angular-translate/angular-translate/jobs/41173721)

**Comment by viniciuspires** [comment]
So... is it working with 1.3?
I need to upgrade my application to Angular 1.3, and I just need this library to work... If this is working, is it possible to update the bower.json to accept Angular 1.3? I'm getting the following error: `ECONFLICT Unable to find suitable version for angular`

**Comment by knalli** [comment]
It works.

Just use bower's _resolution_ feature.

**Comment by viniciuspires** [comment]
Oooooh... That worked. 
I'd buy you a beer if I was on Germany now. lol

Thanks a lot!
