### ISSUE TITLE
Second load from failed (404) static files load reads from internal tables instead of retrying the actual file load

### ISSUE THREAD

**Issue by breakingco** [angular-translate/angular-translate#824]
http://plnkr.co/edit/309zz2RGQmtmDAoD8q21?p=preview

You load a file using static files loader, and if the file doesn't exist, it fails, gives a 404, and does not change the language (expected). However, if you load it again, angular-translate must have loaded the undefined result into internal translation tables, because pressing it for the second time will bypass the static files loader (can be confirmed by placing a console.error in that module's error function) and the keys will be loaded instead.

The desired behaviour should be that if there is a 404, the request to load a language should keep going through the static files loader until successfully loaded into angular-translate's internal table.

Cheers!

Daniel

**Comment by knalli** [comment]
As the latest activities here show, some additions has been made.

Closing this.
