### ISSUE TITLE
Change Loader method at runtime

### ISSUE THREAD

**Issue by sayacoub** [angular-translate/angular-translate#836]
Hi everyone!

I have a little problem with my project and angular translate. My app is composed of two parts, one that can be accessed by anybody, and the second that needs login in. 
I need to retrieve translation data from a distant server but this data can only be accessed once logged in. So I was wondering if it was possible to first create a custom loader that would contain the necessary data for my access-free pages, and once I'm logged in, I switch to the distant data.
I've tried to use the partial Loader but the problem is that the URL is use doesn't end in .json, so I don't see how I could switch between local files and the distant data.
I'm aware that it may not be the best way, but I haven't found the correct solution in the documentation.

Any help would greatly be appreciated!
Sami

**Comment by knalli** [comment]
Closing due inactivity. Additionally, we recommend using a custom loader. You can even re-use the existing ones.
