### ISSUE TITLE
Provide default translations that can be overridden

### ISSUE THREAD

**Issue by bjohnso5** [angular-translate/angular-translate#839]
Hi, I'm currently involved in building an application module that will be distributed as a shareable interface fragment for multiple consumers. 

Is it possible currently to provide a set of translations that can then be overridden (on a piecemeal basis) after .config blocks have run? For example, if I had a translation key for an error message, we'll call it "NAMESPACED-ERROR-MESSAGE-A", and I provided a translation for that key at config time, would it be possible for an upstream user of my module to override JUST that key in the translation table at run time? Basically, I'm wondering if there's a way to load additional translations without doing an all-or-nothing definition of translation keys.

I've reviewed the documentation available for the various translation loaders, and I've also considered a custom loader, but I haven't come to a solution that I think will work in practice.

**Comment by bjohnso5** [comment]
Sorry, just realized I hadn't responded to your last question. This issue can be closed, I worked around my issue (I realize it's kind of a specific niche case, and it makes no sense to include a general purpose way to achieve it in the library) by adding some preprocessing in my build pipeline that generates an angular module to add the translations in a config block. This makes it so that my default translations are available at bootstrapping time, and a consumer is free to call .translations() with overrides that are applied properly.

Thanks for your help, and sorry again for the neglect!

**Comment by josephfinlayson** [comment]
We're also looking at this for supporting translations for a customisable module, that can be extended for each client. It has a default translation set that can be customised for each particular client:

So the base set might include
LOGIN_MESSAGE: "Hello, and welcome.  Login!"

Client A would be happy with this, but client B might want the message:

LOGIN_MESSAGE: "Yo yo yo homie, you should login!"

Any suggestions on how to architect this. Currently fiddling around with constants, and _.extend(DefaultENTranslations, ClientENTranslations)

**Comment by josephfinlayson** [comment]
Ah, this is how I do it: 

http://plnkr.co/edit/9BLcwRqTu8SZNw68EHUR?p=preview
