### ISSUE TITLE
$translatePartialLoaderProvider: dynamic url template path

### ISSUE THREAD

**Issue by juristr** [angular-translate/angular-translate#845]
Hi,

I'm having a project structure like this:

```
 app/
  |-- app.js
  |-- module1/
       |-- module.js
       |-- ...
       |--locale-en.json
       |--locale-de.json
  |-- module2/
       |-- module.js
       |-- ...
       |--locale-en.json
       |--locale-de.json
```

So far so good. I created a translation configuration where I defined the path url template for the `$translatePartialLoader`. Something like this:

```javascript
$translateProvider.useLoader('$translatePartialLoader', {
   urlTemplate: './scripts/{part}/locale-{lang}.json'
});
```

This works great. The problem is this imposes a limit on the location where I can place "modules". Say I'd like to group related modules into a subfolder

```
 app/
  |-- app.js
  |-- module1/
       |-- module.js
       |-- ...
       |--locale-en.json
       |--locale-de.json
  |-- module2/
       |-- module.js
       |-- ...
       |--locale-en.json
       |--locale-de.json
 |-- common/
       |-- auth/
           |-- module.js
           |-- ...
           |--locale-en.json
           |--locale-de.json
       |-- widgets/
           |-- module.js
           |-- ...
           |--locale-en.json
           |--locale-de.json
```

In this case I'd have to dynamically adjust the template which - I suppose - is not possible. Is there any way to make angular translate work in such a setup?? Thx :smile:

**Comment by splintor** [comment]
We had a similar problem, with different files in different paths, but in our case, that language was the name of a directory with list of translation files, to the file paths have differences both before the language (various paths) and after the language (various filenames).
We are now looking into using the option to pass a function to `urlTemplate`, so we can return the needed path based on the `part` and `language`, but not using a single template.
https://github.com/angular-translate/angular-translate/blob/821bfa51eb2f920e0440fffe3dab19b4ea5e2a8e/src/service/loader-partial.js#L41 

https://github.com/angular-translate/angular-translate/commit/401204a
