### ISSUE TITLE
Translate filters don't resolve always (probably when static files take longer to load) in Angular 1.3

### ISSUE THREAD

**Issue by ritenv** [angular-translate/angular-translate#846]
We recently upgraded our app to Angular 1.3, and we're facing an issue where the translate filters will resolve only if the view is loaded after the language files are loaded. It is a single-page app with URL tracking, and all works well when we navigate from the first screen. 

If, however, we refresh the app from another screen, the filters seem to fail.

Anyone else face something like this? Any clues to resolve this?

Edit: The issue arises when filters are used within views.

**Comment by knalli** [comment]
still an issue?

**Comment by ritenv** [comment]
@knalli Unfortunately, we could not generate it on a plunk, but still face the same in our project. We managed by a workaround wherein we created a custom filter that calls $translate directly, as below:

	angular.module('concierge').filter('translater', [
	  '$translate',
	  function ($translate) {
	    var myFn = function(label) {
	        return $translate.instant(label);
	    };
	    myFn.$stateful = true;
	    return myFn;
	  }
	]);

**Comment by knalli** [comment]
Are you using AJS >= 2.4?

**Comment by ritenv** [comment]
Yeah, `"angular-translate": "~2.4.2"` and `"angular": "1.3.6"`

**Comment by knalli** [comment]
Then your filter is not doing anything more than ours.

**Comment by ritenv** [comment]
Yes, that's the confusion. Somehow this works.

**Comment by knalli** [comment]
Well. Unless there is  any other difference in the code, this is no magic. 

https://github.com/angular-translate/angular-translate/blob/3110a91735aa841d6b29338c6880364b3316ac28/src/filter/translate.js#L53-L67

Beside of that, your  filter missed scope/params..

**Comment by ritenv** [comment]
Cool, thanks @knalli for your intervention.
