### ISSUE TITLE
directive: element's text is not replaced by translation defined in attribute anymore

### ISSUE THREAD

**Issue by oemmes** [angular-translate/angular-translate#850]
Hi,

I wanted to upgrade to 2.5.0 today but the change 49cfef0f58dd8c8306e6c0d4c6e78854ff2bbd8b kept me from doing so.

I used to type an verbose label as an element's text and define the translation id in the translate attribute, e.g.
``<h2 translate="order.success.headline">Order completed</h2>``

With 2.4.x the element's text was _replaced_ with the translation as defined in the attribute.
Though with 2.5.0 that text is _prepended_ to the actual translation, resulting in (for a German translation):
``<h2 translate="order.success.headline">Order completed Bestellung abgeschlossen</h2>``

If there's an interpolation in the element's text the translation id from the attribute is not honored at all:
``<li translate="basketDetail.sections.{{::section.__key}}.title">{{::section.__key}}</li>``
with ``section.__key`` being "articleList" this results in:
``<li translate="basketDetail.sections.articleList.title">articleList</li>``

I would expect that the translation id from ``translate`` attribute should always take precedence over the (interpolated) element's text (as it was before).

When the 3 lines from the mentioned changeset are removed it works like before in my case.

**Comment by knalli** [comment]
Closing this. And noting that at least I'm (and the rest of the team go with me) planing to remove the feature which is causing this trouble. Closing this. See #995
