### ISSUE TITLE
$translate promises resolving with id value and undefined language on async loading init, when fallbackLanguage *and* preferredLanguage are set

### ISSUE THREAD

**Issue by pedrosanta** [angular-translate/angular-translate#855]
Hi there,

I came across an issue when we use the (async) static files loader, with storage and set up a fallback **and** preferred language.

When we load the page, having previously chosen a non-preferred language, some $translate promises on early init stage (like on ngRoute resolves) are resolved with the translation key, when the language is still undefined, and several 'translation not found' warnings are output to the console.

I've set up a Plunker with this behaviour here: http://plnkr.co/edit/6soPfAJx4PKGWpeJbyyx

If fallback or preferred call is commented on the module config, it works fine.

I couldn't really find out if these two are redundant or not, but even if if they are maybe they should play well along each other no? Or, in alternative, have a specific warning on the docs about this case or similar.

**Comment by knalli** [comment]
So far, I can verify this. Updated a little bit. http://plnkr.co/edit/vJw8luD6Fbp2OK2qXVZC?p=preview

Must be something internal, racing condition?

**Comment by knalli** [comment]
Two bugfixes are related with this one a13899f (#920) and 3be14df (#981). Matches with yours?

**Comment by knalli** [comment]
@pedrosanta  can you confirm the fix?

**Comment by knalli** [comment]
I'm sure this is a duplicate, so this have to be fixed.
