### ISSUE TITLE
Use $window instead of window

### ISSUE THREAD

**Issue by miraage** [angular-translate/angular-translate#856]
As Angular philosophy, `window` object should not be used directly. Use `$window` service instead.
[Example](https://github.com/angular-translate/angular-translate/blob/df3738119677b6834b2d47455bf35161c9b0c588/src/service/translate.js#L40)

**Comment by tspaeth** [comment]
There are only two occurences: That one mentioned by @miraage and one in 
storage-local.spec.js
I'll take a look...
