### ISSUE TITLE
Angular is not stated as dependency

### ISSUE THREAD

**Issue by Belelros** [angular-translate/angular-translate#858]
Hi here,

I've noticed that `angular-translate` hasn't Angular as a dependency but as a `devDependency` that means that it's not possible to build a correct dependency tree and it can lead to the odd situation of bower generators to put `angular-translate` before `angular` itself which, leads to `angular is not defined` errors.

Should I open a PR with this?

**Comment by knalli** [comment]
All bower repos have such a dependency starting with 2.6.0
