### ISSUE TITLE
Introducing supporting angular in all bower projects

### ISSUE THREAD

**Issue by knalli** [angular-translate/angular-translate#859]
At the moment, both `angular-translate` as well as `bower-angular-translate` do not contain a dependency to Angular JS (see #858). That's often no problem since most users do not start with `angular-translate`, therefore angular will be present already. Anyway, that should be fixed.

Furthermore, we (me..) had several discussion about the lack `angular-cookies` in the shim repository `bower-angular-translate-storage-cookie`. Starting with release 2.5.0, I've added `angular-cookies` already to fix this.

Last but not least, we should extend the supporting range to `">=1.2.26 <=1.4"`. This changes are required for

* the main repository (this here) for `angular` in `dependencies`
* the shim repo bower-angular-translate for `angular` in `dependencies`
* the shim repo bower-angular-translate-storage-cookie for `angular-cookies` in `dependencies`

--

I'm planning this for 2.6.

@angular-translate/core : Suggestions? Vetos? Ideas? Issues I have not thought about?

--

I've also prepared a [document](https://github.com/angular-translate/angular-translate/wiki/How-to-use-a-different-version-of-AngularJS-using-Bower) (useable as FAQ) explaining the dependency issues some devs have from time to time (not knowing managed dependencies).

Relates #858
Relates #832

**Comment by Belelros** [comment]
I agree with @knalli saying that AJS doesn't follow a strict semver pattern. Of course people can later on overwrite on their bower files to install whatever they choose but at least, `angular-translate` states that works with  "1.2 to 1.4"

I think this is a nice document and it covers everything I can think of.

**Comment by pedrosanta** [comment]
@knalli, @Belelros fair enough. ">=1.2 <=1.4" it is.

**Comment by knalli** [comment]
All bower repos starting 2.6 have such dependencies. I've also extended the angular-cookies dependency allowing the same version range.
