### ISSUE TITLE
Translate from array to ng-repeat in Json file.

### ISSUE THREAD

**Issue by Cfsattva** [angular-translate/angular-translate#861]
Hi!

I have this in a service:

function P(rId, clientName) {
  this.id = rId;
  this.name = clientName;
}

var array = [];
array.push(new P('current', 'Today'));
array.push(new P('week', 'This week'));
array.push(new P('month', 'This month'));
array.push(new P('all', 'All stats.'));

Then in a View I have an ng-repeat with: {{p.name}}

I have all my translations in a Json file. 

Is it possible to translate "Today, This week, This month and All stats" using Json file?

Thanks a lot!

**Comment by tspaeth** [comment]
Is there anything left to be answered or fixed?

**Comment by luizfilipe** [comment]
@Cfsattva you have doubt about the api? If yep, plz copy and paste the code thats simulates the problem....

**Comment by Cfsattva** [comment]
All good thanks! @luizfilipe

**Comment by tspaeth** [comment]
Okay. So... closing this one as I understood :-)
