### ISSUE TITLE
translationNotFoundIndicator doesn't work with translate filter on 2.5.2

### ISSUE THREAD

**Issue by snowball** [angular-translate/angular-translate#866]
My indicators are not appended to either side of the translation.  I'm using angular 1.2.27, I can recreate this issue here:

http://plnkr.co/edit/pz8Q2oOCbm8PGyRSQSpa?p=preview

**Comment by knalli** [comment]
fyi: #870 was merged/picked.

**Comment by knalli** [comment]
Is this closed by 870?
