### ISSUE TITLE
Issue with $translate service not rendering text from translationId

### ISSUE THREAD

**Issue by deanclkclk** [angular-translate/angular-translate#875]
Hey Guys:

I have my snippet on plunkr [here](http://plnkr.co/edit/9zUpitT2VqHcsy9UI6YJ). As noted, I have 2 json files being partially loaded. Within my controller, I am using the $translate service to retrieve my text but, it is not working. Only the key is being displayed.

**Comment by knalli** [comment]
@DWand  still open?

**Comment by DWand** [comment]
@knalli, I don't know. I don't remember what is going on here, but, based on the link to 306 issue, it is somehow related to the synchronization problem. I've updated my comment in the discussion about version 3.0.0 (https://github.com/angular-translate/angular-translate/issues/306#issuecomment-66763693)

**Comment by knalli** [comment]
@deanclkclk  I cannot find a suitable test case under your url.

Anyway: Could it be possible that this is similar to https://github.com/angular-translate/angular-translate/issues/920#issuecomment-92445094?

**Comment by knalli** [comment]
@deanclkclk can you confirm this bug is solved?

**Comment by deanclkclk** [comment]
@knalli issue is fixed. Thanks.

**Comment by knalli** [comment]
@deanclkclk great! thanks.
