### ISSUE TITLE
directive: incorect element body resolving

### ISSUE THREAD

**Issue by DOrlov77** [angular-translate/angular-translate#879]
If the element body has angular expression wraped by new lines - it will not be translated.
So 
```javascript
<div translate>
     {{ true ? 'Key1' : 'Key2'}}
</div>
```
Will display string "{{ true ? 'Key1' : 'Key2'}}"

But 
```javascript
<div translate>{{ true ? 'Key1' : 'Key2'}}</div>
```
will translate 'Key1' correctly.

**Comment by tspaeth** [comment]
Yeah, looks like a bug.

http://plnkr.co/edit/DF634EWQIUSyMkMWwx8N?p=preview

**Comment by knalli** [comment]
dup of #909 and will be resolved in next release
