### ISSUE TITLE
Support for precompiled MessageFormat translations

### ISSUE THREAD

**Issue by schmod** [angular-translate/angular-translate#880]
angular-translate's current integration with [messageformat.js](https://github.com/SlexAxton/messageformat.js) requires users to load the full MessageFormat runtime (including the underlying [PEG](http://pegjs.org/) parser), which ultimately adds up to ~51KiB uncompressed/unminified.

Additionally, angular-translate fully recompiles every MessageFormat expression whenever an interpolation parameter changes, but does not cache the compiled expression (only the final interpolated result).  Because MessageFormat strings compile into fairly simple/lightweight JavaScript functions, all subsequent interpolations of a given string should be extremely fast.

In essence, we are caching the computationally-inexpensive portion of the interpolation, and discarding the expensive part.  This isn't necessarily a huge issue if your interpolation parameters rarely/never change, but it's certainly something that could be improved upon.

***

Both of these issues point to the fact that the code necessary to parse/compile MessageFormat strings is large, slow, and not particularly well-suited for the browser.

messageformat.js acknowledges these drawbacks, and supports precompiling translation strings at build-time into pure JavaScript functions, which only depend on a [very small runtime component](https://github.com/SlexAxton/messageformat.js/blob/0.2.1/lib/messageformat.dev.js#L62).  

By precompiling the expressions, we can reduce the size of our browser-based dependencies, and improve runtime performance. There is an existing [cli utility](https://github.com/SlexAxton/messageformat.js#the-cli-compiler), and several [grunt](https://github.com/gushov/grunt-messageformat) [tasks](https://github.com/blueimp/grunt-locales) that can automate this precompilation process...

***

Ideally, angular-translate should be improved to support this more-efficient method of utilizing MessageFormat.  I believe that two (broad) changes are necessary to work toward this goal:

* Update the existing MessageFormat interpolator to cache compiled expressions, in addition to their final interpolated values.  (I think that there are good reasons for continuing to support runtime compilation)
* Create a new custom interpolator that can interact with precompiled MessageFormat translations.  

Given that the precompiled expressions are JavaScript functions, rather than strings, it may be necessary to make modifications to the caching layer and loaders, before we can properly support this. 

***

Before I dive in, and attempt to implement this, are there any thoughts about how this should be done (or if it should be done)?

**Comment by knalli** [comment]
We are not really in messageformat, so if you think this would be a great addition, we would welcome it.

> Update the existing MessageFormat interpolator to cache compiled expressions, in addition to their final interpolated values. (I think that there are good reasons for continuing to support runtime compilation)

Yes, that is really a good one. Cache on demand.

> Create a new custom interpolator that can interact with precompiled MessageFormat translations.

Given a pair of a special custom loader and this custom interpolator, this could work.
