### ISSUE TITLE
IE9 placeholder issue on language change

### ISSUE THREAD

**Issue by taheerahamed** [angular-translate/angular-translate#881]
Hi guys i am using the https://github.com/SparrowJang/angularjs-placeholder directive to show  placeholder in   IE9 . In my form details i am having the first name which is having the placeholder of  the Enter the first name in english and When i am changing the lang to another then the place holder is  not changing in IE9. In remaining browsers it is working fine  .

**Comment by knalli** [comment]
But this is not an issue for angular-translate?

**Comment by taheerahamed** [comment]
@knalli which means it is an issue of placeholder directive which i had included ?

**Comment by tspaeth** [comment]
We don't know about your implementation so we cannot answer anything here without any code example.

**Comment by tspaeth** [comment]
pinging @taheerahamed - We'd love to help, but without an example, it is hard to guess... :)
