### ISSUE TITLE
translate an array and do something when finished

### ISSUE THREAD

**Issue by pacuna** [angular-translate/angular-translate#882]
I'm having trouble understanding how to manage asynchronous responses when using the translation service.

For example, I'm translating this array, pushing the results into another array and concatenating the resulting translations:

```
    var translatedCategories = [];
    for(var i = 0; i < $scope.options.categories; i++){
      $translate($scope.options.categories[i]).then(function(result){
        translatedCategories.push(result)
      });
    }

    //this should happen when the for loop ends
    var categoriesString = translatedCategories.join();
```

What is the proper way to accomplish this?

Thanks in advance.

**Comment by tspaeth** [comment]
Hi!
If you take a look at least at the short API:

http://angular-translate.github.io/docs/#/api/pascalprecht.translate.$translate

There you'll see, that you can input $translate([ARRAY]).then... 

so yes - this is the right way you're doing, but you can skip the for loop then and just input your array.

**Comment by tspaeth** [comment]
Closed due to inactivity.
