### ISSUE TITLE
Wrong evaluation of {{ value + value }} when the 'escaped' sanitization is ON

### ISSUE THREAD

**Issue by felixmosh** [angular-translate/angular-translate#883]
When the sanitization is on 'escape' mode, evaluation of "Foo bar {{ value + value }}" (when value passed as parameter) should be "Foo bar 10".
But instead it`s "Foo bar 55".
The sanitize param function converts everything into String.

**Comment by knalli** [comment]
Could you please specify this a bit more? Which values do you have parameterized? A demo (plunkr/jsfiddle) is welcome!

**Comment by knalli** [comment]
PR was picked.
