### ISSUE TITLE
Can we use asynchronous loading to load ngLocale files ?

### ISSUE THREAD

**Issue by mathilde-pellerin** [angular-translate/angular-translate#885]
Hi,

quite all is in the title, but here some context : we start a new project in which we will handle i18n with ng-translate. In this project, we use ngLocale as well. Currently, we thought load ngLocale file manually depending to user locale. 
But we wonder if it is possible to load them using urlLoader or staticFileLoader ?

**Comment by tspaeth** [comment]
I don't get, what loading the ngLocale module has to do with angular-translate (not ng-translate btw!)? Could you explain that a bit more detailed?

**Comment by PascalPrecht** [comment]
>I don't get, what loading the ngLocale module has to do with angular-translate

@tspaeth Nobody asked for that, so please be kind and just answer the actual question:

>But we wonder if it is possible to load them using urlLoader or staticFileLoader ?

@mathilde-pellerin ngLocale files are not just plain JSON files but actual angular modules. So, even if you load them with angular-translate (which is indeed possible), the returning data from the server is not a format that angular-translate can work with. In addition to that, they both solve two different things, so in the end it's not what you want anyway.

**Comment by mathilde-pellerin** [comment]
@PascalPrecht Thanks for your answer, we will manage that manually then.

**Comment by christw92** [comment]
@PascalPrecht So how can we use localization (l10n) with angular-translate then? I found the [docs](https://angular-translate.github.io/docs/#/guide) saying something about l10n support but the docs seem to focus on the i18n part.

**Comment by knalli** [comment]
As our names indicates, we do only manage translating which is part of the internationalizing. But we don‘t localize. That’s already done by Angular-i18n and can be added dynamically with ngLocale.

**Comment by knalli** [comment]
You are right, that’s perhaps misleading. If you want, you can try a PR

**Comment by knalli** [comment]
Please follow discussion #1807
