### ISSUE TITLE
Translate directive and ngMessage not working

### ISSUE THREAD

**Issue by crisbeto** [angular-translate/angular-translate#886]
As mentioned in https://github.com/angular-translate/angular-translate/issues/702 the `translate` directive doesn't work when on the same element as https://docs.angularjs.org/api/ngMessages/directive/ngMessage. 

Here's a simple example that breaks:

```html
<form name="form">
    <input type="email" ng-model="email" ng-required="true" name="email" />

    <div ng-messages="form.email.$error">
        <div class="form-error" ng-message="required" translate="FIELD_REQUIRED"></div>
        <div class="form-error" ng-message="email" translate="EMAIL_INVALID"></div>
    </div>
</form>
```

I've been playing around with it a bit and it turns out that the error is caused because both the `translate` and `ngMessage` directive have the same priority(0). If we set the priority of `translate` lower, everything works as expected.
Here's a monkey patch that worked for me:

```javascript
angular.module('pascalprecht.translate').config(['$provide', function($provide) {
    $provide.decorator('translateDirective', ['$delegate', function($delegate){
        var directive = $delegate[0];

        directive.priority--;

        return $delegate;

    }]);
}]);
```

Note that I'm not sure what consequences reducing the priority might have, but from what I'm seeing it works fine. I've also tested with interpolation and `translate-values`.

**Comment by knalli** [comment]
I've added an additional option setter `$translateProvider.directivePriority(0)`.

Defaults to `0` just like AJS default.
