### ISSUE TITLE
static-files-loader: Where to put my language files?

### ISSUE THREAD

**Issue by manulitopetito** [angular-translate/angular-translate#887]
Hi!

First of all: Thanks for the great work!

I have one problem: When i export my language strings into a separate json file - where should I put it?
I tried the following:

    app/
    --js/
    ----i18n/
    ----------lang-de_DE.json
    ----app.js  // the implementation in the config file

    $translateProvider.useStaticFilesLoader({
      prefix: 'i18n/lang-',
      suffix: '.json'
    });

But unfortunately, it won't load. Could you help me out on this?

**Comment by DWand** [comment]
Hello, @manulitopetito. Try to write the `prefix` in a manner of absolute path from site root or make it relative to your page.

**Comment by jmayday** [comment]
So, combining my approach and @DWand hint, I would suggest do it like this:

app/
--assets/
----translations/
------de.json
------en.json
--js/
--app.js  // the implementation in the config file

$translateProvider
   .useStaticFilesLoader({
     prefix: 'app/assets/translations/',
     suffix: '.json'
   })
   .registerAvailableLanguageKeys(['en', 'de'], {
                       'en-us': 'en',
                       'en-uk': 'en',
                       'de-de': 'de',
                       'de-ch': 'de'
   });

**Comment by DWand** [comment]
Is this issue solved?

**Comment by jmayday** [comment]
Forgot to add - in my case staticFilesLoader works without any issues having it configured like I shown.
