### ISSUE TITLE
$translate service not working for partial loading with $translateMessageFormatInterpolation

### ISSUE THREAD

**Issue by mabouchalkha** [angular-translate/angular-translate#888]
hi there,

i'm using angular-translate and i think it's a powerful module for angular.

i have trouble to use  angular-translate with translatePartialLoader and translateMessageFormatInterpolation for my project. 

i think translatePartialLoader works well for me and i can see in my UI the language change when i call 
```
		header.changeLanguage = function changeLanguage (langKey) {
			$translate.use(langKey);
		};
```
but i have error in console like this

 ReferenceError: Locale fr could not be loaded: require is not defined
    at Function.MessageFormat.loadLocale (http://localhost:3444/vendor/messageformat/messageformat.js:48:20)
    at new MessageFormat (http://localhost:3444/vendor/messageformat/messageformat.js:37:23)
    at Object.$translateInterpolator.setLocale (http://localhost:3444/vendor/angular-translate-interpolation-messageformat/angular-translate-interpolation-messageformat.js:71:13)
    at http://localhost:3444/vendor/angular-translate/angular-translate.js:977:35
    at Object.forEach (http://localhost:3444/vendor/angular/angular.js:331:20)
    at useLanguage (http://localhost:3444/vendor/angular-translate/angular-translate.js:976:17)
    at langPromises.(anonymous function).loadAsync.then.$nextLang (http://localhost:3444/vendor/angular-translate/angular-translate.js:1524:13)
    at processQueue (http://localhost:3444/vendor/angular/angular.js:13170:27)
    at http://localhost:3444/vendor/angular/angular.js:13186:27
    at Scope.$eval (http://localhost:3444/vendor/angular/angular.js:14383:28)

the problem came from here this line ``` $mf = new MessageFormat(locale); ``` in angular-translate-interpolation-messageformat.js
```
  $translateInterpolator.setLocale = function (locale) {
    $mf = $cache.get(locale);
    if (!$mf) {
      $mf = new MessageFormat(locale);
      $cache.put(locale, $mf);
    }
  };
```

my service it's look like this

```
.config(['$translateProvider', '$translatePartialLoaderProvider', function($translateProvider, $translatePartialLoaderProvider) {

        $translatePartialLoaderProvider.addPart('dashboard');
        $translatePartialLoaderProvider.addPart('nav');
        $translatePartialLoaderProvider.addPart('header');
		  
        $translateProvider.useLoader('$translatePartialLoader', {
            urlTemplate: 'src/common/services/i18n/{part}/{lang}.json'
        });

		  $translateProvider.addInterpolation('$translateMessageFormatInterpolation');
        $translateProvider.preferredLanguage('en');
    }]);

.run(function ($rootScope, $translate, $state, $stateParams) {
		
		$rootScope.$state = $state;
		$rootScope.$stateParams = $stateParams;
		
		$rootScope.$on('$translatePartialLoaderStructureChanged', function () {
			$translate.refresh();
		});
	})
```

thank you I would appreciate any timely assistance.

**Comment by knalli** [comment]
> 
> ReferenceError: Locale fr could not be loaded: require is not defined
> at Function.MessageFormat.loadLocale

You should check your provided stacktrace.

**Comment by mabouchalkha** [comment]
i have to install require.js?

**Comment by knalli** [comment]
I don't know your code.. perhaps? 

Neither we are using `require` in angular-translate nor is the error happened in our code.

**Comment by mabouchalkha** [comment]
ok i found the solution
in the index.html we have to inculde 
```
/path/to/messageformat/locale/lang.js

```
thank you a lot

**Comment by bandara00007** [comment]
I got the same problem.Why are we again load the lang.js file from index , since we use static file loader?

**Comment by tspaeth** [comment]
Please don't comment on very old closed tickets as they're not worked on anymore. If there is an issue with angular-translate, please open a new ticket.

If you need general help, please use StackOverflow to have a broader audience as we're as a small team only able to fix bugs and introduce new features for the module here. Thanks.
