### ISSUE TITLE
Making angular-translate available as a Visual Studio NuGet package also?

### ISSUE THREAD

**Issue by epicbugs** [angular-translate/angular-translate#889]
First of all, thanks for your effort in creating Angular Translate and also for keeping it moving forward. The company I am working for is using it for a big government project and we really appreciate the features is provides.

As you might have guessed from the title, having Angular Translate available as a NuGet package would be a good thing for us. Some folks out there have already published earlier versions in the past but the last version available over at NuGet is as old as 2.1.0 (https://www.nuget.org/packages/AngularTranslate/). I already tried to encourage a maintainer of one of those repositories to update but to no avail as of yet.

~~Previous excess foam removed.~~

So my hope is that Angular Translate would claim a kind of an official channel over there too. Is there anything I can do to help you in making it happen?

**Comment by pascalberger** [comment]
+1. Would be nice to have an actively maintained and up to date NuGet Package. Also with an NuGet package dependent on the modular angular.core (or no dependency so that the user can choose) as already requested in #797

**Comment by knalli** [comment]
As already mentioned in #797, we are currently not able to provide this. Neither I'm willing to proceed with a developer-only-releasing solution (which actually does not work currently because I'm not working w/ windows and the mono solution is buggy for me), nor I have enough knowledge how to solve this automatically.

Right, any developer with "release permission" is able to make release publishing to npmjs.org, bower (actually GitHub) and GitHub itself. No other OS dependency, and no other tools than a `npm install` had included.

**Comment by pascalberger** [comment]
The author just updated the existing NuGet package to the latest version: https://www.nuget.org/packages/AngularTranslate/

**Comment by epicbugs** [comment]
I can confirm the package update and but it still has one small glitch. It appears that the `angular-translate-storage-cookie.js` file has somehow slipped through the cracks, so to speak.

The version of `angular-translate-storage-cookie.js` I got from NuGet on 20.01.2015 18:31 (GMT +02:00) contains the following header:

```javascript
/*!
 * angular-translate - v2.4.0 - 2014-09-22
 * http://github.com/PascalPrecht/angular-translate
 * Copyright (c) 2014 ; Licensed MIT
 */
```

When using the cookie storage option with that one, the updated Angular Translate package fails with `Uncaught Error: Couldn't use storage '$translateCookieStorage', missing get() or put() method!`.

Although I managed to fix it manually, I sent a message about it to the author of the package also, I hope he will find the time to fix it.

I also discovered that at least in our scenario when migrating from **2.1.0** to **2.5.2**, we had to register available languages with `$translateProvider.registerAvailableLanguageKeys();` during the configuration phase. Without it, there was only a beautiful white screen with `Uncaught TypeError: undefined is not a function		
angular-translate.js:182` written inside the console window.

Other than that, it's all good. Thank you very much!

**Comment by pascalberger** [comment]
`angular-translate-storage-cookie.js` is not part of the NuGet package. The [AngularTranslate](https://www.nuget.org/packages/AngularTranslate/) package only contains the core file (`angular-translate.js)`, the [AngularTranslate.LoaderUrl](https://www.nuget.org/packages/AngularTranslate.LoaderUrl/) additionally the `angular-translate-loader-url.js` file.

**Comment by epicbugs** [comment]
Aah, my mistake then, apologies. You're right, the cookie storage file is not a part of the [AngularTranslate](https://www.nuget.org/packages/AngularTranslate/) package. Nor does it presently seem to be a part of any other one, so go figure.

But whatever the case may be, the updated **2.5.2** package itself seems to be working and at least for me that's good enough. Hence, for the time being, the problem is solved. Thanks!
