### ISSUE TITLE
ajs translate 2.5.2 doesnt support ajs 1.3.x 's ng-strictDi  option - crashes apps

### ISSUE THREAD

**Issue by gtesslerge** [angular-translate/angular-translate#891]
Your fine app needs to support AJS's ng-strictDi  directive.

		try {
			angular.bootstrap (
				document,
				[ 'predixApp' ],
				{ strictDi: true }		// ajs1.3.x feature - needed for minification. GST
			);

 00108. Out anonymous function (): require ()  -- app.js
angular.js:63 Uncaught Error: [$injector:modulerr] Failed to instantiate module App due to:
Error: [$injector:modulerr] Failed to instantiate module controllers due to:
Error: [$injector:strictdi] function($translateProvider ) is not using explicit annotation and cannot be invoked in strict mode
http://errors.angularjs.org/1.3.9/$injector/strictdi?p0=function(%24translateProvider%20)
    at REGEX_STRING_REGEXP (http://localhost:9002/scripts/nonAngular/openSource/angular/angular-1.3.9/angular.js:63:12)

**Comment by tspaeth** [comment]
Could you give us a bit more details - e.g. setup a simple plnkr for your setup? As you can see - the normal minification of the angular-translate works as all services + controllers use the correct syntax. So we probably need to drill down a bit more on the setup.

**Comment by tspaeth** [comment]
pinging @gtesslerge

**Comment by knalli** [comment]
@gtesslerge : Could you please say which component is breaking the Strict DI mode?

Actually, this should be no issue. Regardless the fact we are building the artifacts with _ngmin_ (until and including 2.5.1) and _ng-annotate_ (since 2.5.2), even the source files should be written in explicit manner.

**Comment by knalli** [comment]
Closing this because I cannot see an issue. In fact I know at least one app with enabled strictDI and included angular-translate.
