### ISSUE TITLE
angular-translate & ui-router

### ISSUE THREAD

**Issue by njlg** [angular-translate/angular-translate#892]
I know people have mentioned this in other issues, but I've not seen a solution that works. I use the `$translate` service with separate language JSON files for most of my app. However, for sections that are largely static I would rather detect what language the user is using and load a specific template for that language.

Here is my example of the issue: http://plnkr.co/edit/UM9q4rBmCk8M6qZf41bC

This example works fine, until you refresh the page. If I commented out the `.useStaticFilesLoader()`, however, the app appears to work correctly. Any ideas on how to accomplish something like this?

**Comment by knalli** [comment]
@njlg , I'm not getting your issue. What is exactly your problem? I've tried your demo, but I'm not getting the point..

**Comment by njlg** [comment]
When using `useStaticFilesLoader()` in my example, `$translateProvider.use()` returns undefined until the static JSON file has been fetched from the server.

**Comment by knalli** [comment]
Correct. You cannot query for a language in the *constructor phase*  of a component (controller) when requests are still running.

Instead of

```js
  .controller('PrivacyCtrl', function($translate) {
    console.log('PrivacyCtrl using %s', $translate.use());
  })
```

you should use the event

```js
  .controller('PrivacyCtrl', function($translate, $rootScope) {
    $rootScope.$on('$translateChangeEnd', function ($event, data) {
      console.log('PrivacyCtrl using %s', data.language);
    });
  })
```

And instead of 

```js
    $stateProvider
      .state('privacy', {
        url: '/privacy',
        templateUrl: function() {
          var locale = 'en';
          
          // this is undefined when useStaticFilesLoader() is used
          var tmpLocale = $translateProvider.use();
          if(tmpLocale) {
            console.log('translateProvider is set to %s', tmpLocale);
            locale = tmpLocale;
          }

          return 'privacy.' + locale + '.html';
        },
        controller: 'PrivacyCtrl'
      });
```

you should use the instance not the provider (it is not doing something, only config)

```js
    $stateProvider
      .state('privacy', {
        url: '/privacy',
        templateProvider: function($translate, $stateParams) {
          var locale = 'en';
          
          // this is undefined when useStaticFilesLoader() is used
          var tmpLocale = $translate.use();
          if (tmpLocale) {
            console.log('translateProvider is set to %s', tmpLocale);
            locale = tmpLocale;
          }

          return 'privacy.' + locale + '.html';
        },
        controller: 'PrivacyCtrl'
      });
```

See in http://plnkr.co/edit/IcR5SOBJq4JwWlbZLEvH?p=preview
