### ISSUE TITLE
Html tags within translated strings

### ISSUE THREAD

**Issue by Cfsattva** [angular-translate/angular-translate#896]
Hey!

I translated some content in my Html page using translate directive:

```
<p class="text-center text-muted" translate="{{ 'TERMS' }}"></p>

<p class="text-center text-muted" translate="{{ 'ALREADY' }}"></p>
```
I received the translations from a .Json file:

en.json

```json
    {
      "TERMS": "<small>By clicking Register, you agree to the <a href=\"/#/terms\">terms &     conditions</a> and the <a href=\"/#/policy\">privacy policy.</a></small>",
    "ALREADY": "Already have an account? <a href=\"/#/login\">Sign in now</a>",
    }
```

is it possible to make this without putting the Html in the .Json file?

Thanks!

**Comment by knalli** [comment]
Ehm.. what?

Formally, I would recommend a look into GitHub's [Markdown Guide](https://guides.github.com/features/mastering-markdown/), because I'm not sure whether I got your unstyled code right or not.. 

So far: You can refer to expressions directly: `<p class="text-center text-muted" translate="TERMS"></p>` is fine!

What do you mean with HTML? Which one?

**Comment by knalli** [comment]
Well, I have edited you post because I can see your HTML only on the edit mode.

Okay. This is already the easiest way for (more) complex translations. In different languages you would have different markup positions, so this is fine.

**Comment by Cfsattva** [comment]
How can I do this whithout putting the html in the json file?

**Comment by Cfsattva** [comment]
Is it possible?

**Comment by PascalPrecht** [comment]
@Cfsattva So if you don't want to have any HTML in your JSON, but you need HTML in the end result, you need to make it the other way around. Which means, you put the needed tags in your document (as usual) and translate your translations there.

I think in the end there's no way around having tags in your translations considering how angular-translate works.

**Comment by knalli** [comment]
> Is it possible?

Use 

```html
<p class="text-center text-muted">
{{ 'ALREADY_LOGIN' | translate }} <a href="/#/login">{{ 'SIGNUP' | translate }}</a>
</p>
```

It's your turn.

**Comment by Cfsattva** [comment]
@PascalPrecht You are right, thanks!

@knalli Thanks man! Also works with directive:
```
<small><span translate="YET"></span><a href="/#/signup" translate="REGISTER"></a></small>
```

**Comment by Hirbod** [comment]
I've a better approch for this. (IMHO)

This is how I did it:
First, one global function

```js
 if (!String.prototype.format) {
    String.prototype.format = function() {
        var str = this.toString();
        if (!arguments.length)
            return str;
        var args = typeof arguments[0],
            args = (("string" == args || "number" == args) ? arguments : arguments[0]);
        for (arg in args)
            str = str.replace(RegExp("\\{" + arg + "\\}", "gi"), args[arg]);
        return str;
    }
}
```

2)  
```json 
MYKEY: "This is {link} redirects to {something}";
MYLINK: "LINK-TEXT";
SOMETHING: "SOMETHING";
```

```html
<ANY ng-bind-html="WHATEVER"></ANY>
```
Then just call a translate Promise inside of your controller, and then

```js
$scope.WHATEVER = myTranskey.format({link: '<a href="">'+anotherKey+'</a>', someting: "key/whatever" })

**Comment by tspaeth** [comment]
Closing this one as I think it is answered - feel free to reopen if I'm wrong.

**Comment by Cfsattva** [comment]
Yeah sorry! Thanks to all

**Comment by ozdemirr** [comment]
Hi @PascalPrecht and @knalli 
There are other situations. 
For example, let's think for an e-commerce website that supports 2 languages(Turkish and English)

We want to say "You can access your orders on orders page"

This is in HTML;

`<p>
You can access your order on <any ui-sref="customer.orders()">orders page</any> 
</p>`

But for Turkish;

``<p>
Siparişlerine <any ui-sref="customer.orders()">siparişlerim</any> sayfasından ulaşabilirsin 
</p>``
 
How to deal with it? another language structure makes harder.

**Comment by tspaeth** [comment]
@ozdemirr Please don't comment on closed, very old tickets to raise new topics.

In general, in your case, you'll have to recompile the blocks as they contain HTML and AngularJS-specific code, which is somehow the hardest way to get it really working. 
You could also split it to senseful blocks where needed, making the code a bit unreadable.

But what is the general issue with your example?
