### ISSUE TITLE
Translation help

### ISSUE THREAD

**Issue by tantommy** [angular-translate/angular-translate#897]
Hello,

I am having some issues with translating something within my directive.  Here is my directive definition below:
```
        return {
            restrict: 'E',
            scope: {
                model: '=ngModel',
                config: '=',
            },
            transclude: true,
            link: {
                pre: function ($scope, elem) {
                    $scope.vm = {
                            config: Config.get()
                        };
                    elem.removeAttr('name');
                }
```
A config object is created and I want to translate one of the properties on this object.  In the html, I can access this property like this: vm.config.label

If I want to translate the value of this how can I do it?  I've tried {{ 'vm.config.label' | translate }}
but that doesn't seem to work.  I've also tried {{ '{{vm.config.label}}' | translate }} but that definitely didn't work.

My html element looks like this:
```
      <label ng-bind=":: (vm.config.label)"</label>     // I want this to bind to the translated value.
```

**Comment by DWand** [comment]
Hello, @tantommy. I'm not sure that I understand you correctly. However... How can you print a value of the property in html? If it is something like `{{ vm.config.label }}`, then try to do this `{{ vm.config.label | translate }}`.

**Comment by tantommy** [comment]
Hi DWand,

Sorry if I wasn't clear.  To access this property to display on html, I would do this ```{{vm.config.label}}```, so yes you are correct.
I tried ```{{vm.config.label | translate}}``` but I do not get the translated version, just the regular ID.

It seems like it's not able to resolve the expression ```vm.config.label``` before running it through the translation filter.

**Comment by DWand** [comment]
http://plnkr.co/edit/0tHeFtKbvxAmWLTkIeG5?p=preview
