### ISSUE TITLE
Version 2.5.2 create a lot of watchers than Version 2.2.0

### ISSUE THREAD

**Issue by lovedota** [angular-translate/angular-translate#899]
Hi friends
- This is the code of Version 2.5.2. We can see **Ctrl1 Of Watchers: 3**
http://jsfiddle.net/lovedota/f4neo3rq/

- This is the code of Version 2.2.0 We can see **Ctrl1 Of Watchers: 1**
http://jsfiddle.net/lovedota/bq7jpm3w/

Is it a bug about performance here ? Please help !

**Comment by knalli** [comment]
Perhaps because the old 2.2 is not AJS 1.3 compatible; which means the filters will be treat being stateless.=

**Comment by tspaeth** [comment]
As knalli said ...  the filter has no watcher on it and therefore doesn't work with 1.3... so it is not a valid comparison of the watcher-amount. Check with AngularJS 1.2 and 2.2 for a valid comparison. 

Is there anything more to do or can we close it?

**Comment by lovedota** [comment]
@knalli  @tsaikd  Thanks !
