### ISSUE TITLE
Bug in $translatePartialLoader: Loading locale files which are pre-bundled

### ISSUE THREAD

**Issue by kumarharsh** [angular-translate/angular-translate#900]
I'm trying to internationalize my app using angular-translate, and I've made a few locale files broken up by modules like so:

```
|_/ i18n
|-- |_/  module1
|     |-- en.json
|     |-- de.json
|--|_/ module2
|     |-- en.json
|     |-- de.json
```

My locale files are structured such that the name of the module is the top-level key, like so:
```
{
  "module1": {
    "common": {
        ...
    }
    "modals": {
       ...
    }
  }
}
```
I've done this so that these files can then be concatenated without collisions, as I'll explain now...

Now, I'm bundling the English locale files with my app using **RequireJS**:

```js
define([
  'text!../../public/i18n/module1/en.json',
  'text!../../public/i18n/module2/en.json',
  ...
], function(_mod1Translations, _mod2Translations) {
  angular.module('plCommon')
    .config(['$translateProvider', function($translateProvider) {
        mod1Translations = JSON.parse(_mod1Translations) /* Requirejs loads those jsons as text */
        mod2Translations = JSON.parse(_mod2Translations)
        allTranslations = _.extend(mod1Translations, mod2Translations)

        /* Then I load the English translations by default */
        $translateProvider
          .translations('en', allTranslations)
          /* And use a partial loader for loading other translations if the locale is different */
          .useLoader('$translatePartialLoader', {
             urlTemplate: '/i18n/{part}/{lang}.json'
          })
          .preferredLanguage('en')
          .fallbackLanguage('en')
    })
})
```

And in my module `module1`, I define the part as so:
```
$translatePartialLoaderProvider.addPart('mod1')
```

Now, what happens is that the translations **are** already defined for English, as I can check by commenting out the `useLoader()` function. So, the bundling part is working correctly. But if I uncomment the `useLoader()` function, the `en.json` files are loaded separately too. I think this is a bug, although I could be wrong.

**Comment by DWand** [comment]
https://github.com/angular-translate/angular-translate/blob/master/src/service/translate.js#L1742

**Comment by tspaeth** [comment]
Isn't it just like all the things discussed already in #535 and the referred other tickets there?

**Comment by kumarharsh** [comment]
Ah well, I see what the cause is. I'll remove the fallbackLanguage part.
But this is not very clear in the docs, nor was I able to search that issue via the Github issues search...

The main point still remains... [this is a bug, right?](https://github.com/angular-translate/angular-translate/issues/535#issuecomment-46528064)

**Comment by knalli** [comment]
@DWand  still open?

**Comment by DWand** [comment]
@knalli, you ask me hard questions. Definitely, I had to provide a link to the specific state of the repository rather than the "master" branch :-(

I think, that this issue is still open. Look here: https://github.com/angular-translate/angular-translate/blob/a2ac7000f94bcee6dd8e206cab5d7cec3527dd25/src/service/translate.js#L1809-L1811

It looks like the fallback languages loading logic doesn't care about what languages are already present in the translation table.

**Comment by knalli** [comment]
@kumarharsh We had resolved this in  #981 -- can you please verify that one? Checkout Patched  http://plnkr.co/edit/qm09k1eP4cdIq5TK71ch?p=preview

**Comment by sscovil** [comment]
@knalli I think I'm experiencing the same issue, using `angular-translate-loader-partial`. I have a fallback language `foo` and a preferred language `bar`, where `foo` is included in the app and `bar` is in a json file. http://plnkr.co/edit/f9xSe9ic9zMCNmsc0Tkc?p=preview

I expect that it will use `foo` until `bar` is loaded, but instead it is trying to load `foo.json` and getting a 404...and falling back to `foo`, never attempting to load `bar`. Is this a bug? Or am I doing something wrong here?

Thanks in advance!

**Comment by knalli** [comment]
Yes -- `refresh()` will reload all stored translations.

**Comment by knalli** [comment]
(A proposal of me for v3 is an additional flag to avoid this.)

**Comment by knalli** [comment]
Closed due inactivity.

The original issue is about the partial loader's loader efficiency. If anyone make a enhancement contribution, it is very likely welcome.
