### ISSUE TITLE
It would be great if you could tell to determinePreferredLanguage to skip the country code

### ISSUE THREAD

**Issue by seblucas** [angular-translate/angular-translate#901]
On my French Windows 8.1 Desktop: 
 * Firefox give me fr
 * Chrome give me fr_FR

for the moment my translation files are only using the language code (en, fr, de, ...) and don't care about the country.

So without any modification my application work with Firefox and crash with Chrome (as soon as I use determinePreferredLanguage). It would be great if you can set a flag somewhere to only care about language name

I also saw #755, there are some good idea there too.

**Comment by tspaeth** [comment]
Couldn't - until someone has developed a pluggable mechanism - also http://angular-translate.github.io/docs/#/guide/09_language-negotiation help out with "registerAvailableLanguageKeys"?

**Comment by seblucas** [comment]
Thanks for the pointer I missed registerAvailableLanguageKeys.

Unfortunately, It isn't a silver bullet at all. A easier way (from my point of vue) would to probe available language by testing each static file (I use angular-translate-loader-static-files).  For example if the browser return fr_FR : 
 * Try to load localization_fr_FR.json
 * If the file is not found then strip the country and try to load localization_fr.json
 * if the file is not found load the default language : localization_en.json

I've never checked how static files are handled and if my proposition is feasible. If it is, would you accept a PR about it ?

Thanks for your answer.

**Comment by tspaeth** [comment]
The idea is good - but - Isn't it somehow another dynamic approach of a fallback mechanism? Instead of iterating through a defined stack, you'll try to be intelligent and risk 404 requests to the server for files that don't exist. To me - as the language code table is limited and probably your language support in the application also - it looks like putting up a short registerAvailable... setup in place sounds more stable and controllable.

And - please consider that the client based determination of the accepted languages is not 100% cross browser stable due to access limitations. We've had some discussions on that already some time ago.

**Comment by seblucas** [comment]
I agree with you. I'm just being lazy. 

My app has currently 18 language code. Each language can have 3 to 12 different country code so if I want to use registerAvailableLanguageKeys the list is going to be big ... really big.

For now my quick & dirty fix has been to : 
 * Copy paste getFirstBrowserLanguage (from angular-translate sources) inside my $translateProvider configuration
 * Add a new function getLocaleWithLanguageOnly that calls getFirstBrowserLanguage and strips the country code. If the language returned is empty, then it call a rest method to add a better guess.
 * call determinePreferredLanguage with my own function : 

```
$translateProvider.determinePreferredLanguage(getLocaleWithLanguageOnly);
```

But I'll have to add support for country code one day or another, so I seek a better solution. About the client based determination, I've read some discussions and I know that.

Anyway I'll say it's more my problem (and my laziness) so thanks again for your time and feel free to close this issue.

**Comment by knalli** [comment]
fyi: We have an outstanding PR #755. Due breaking changes, it was not merged yet into master. Perhaps it will land as opt-in only..

**Comment by seblucas** [comment]
Indeed, even if there are breaking changes, normalization is always good. I'll tweak my copy of getFirstBrowserLanguage to use this PR. Thanks for the information.

**Comment by tspaeth** [comment]
So, what if we do a feature-toggle for the "normalization" feature and rework the outstanding PR to be activated as an alternative or to activate a totally customized "plugin"?
That way we could keep compatibility as of now and open the module for further enhancements.
And AFAIK it's from the coding perspective not such a big deal?!
@knalli what do you think?

**Comment by knalli** [comment]
Prefer an opt-in (default false) for now, and in the next future major an opt-out (default true). Something like `$translateProvider.normalizeBrowserLanguageCodes(enabled)`.

**Comment by tspaeth** [comment]
(y)

**Comment by seblucas** [comment]
Agreed

**Comment by PascalPrecht** [comment]
>So without any modification my application work with Firefox and crash with Chrome (as soon as I use determinePreferredLanguage). It would be great if you can set a flag somewhere to only care about language name

@sebluca `determinePreferredLanguage(fn)` expects an optional function where `fn` is or mechanism to determine the preferred language. In other words, you can do so already without us introducing any new APIs.

**Comment by seblucas** [comment]
Yes I know, that what I already do, I explained here https://github.com/angular-translate/angular-translate/issues/901#issuecomment-73015377 .

I just wished for an integrated solution

**Comment by PascalPrecht** [comment]
@seblucas The only thing I can imagine is publishing a new additional module that introduces that function (which would be too much overhead for such a function prolly), rather than baking that right into source.

We need to stop adding features for personal use-case that are actually already supported by using the existing APIs.

**Comment by seblucas** [comment]
Thanks for your answer, I'll close this issue as we explained a lot of workaround in this issue.

Thanks again for your time, it's really appreciated.
