### ISSUE TITLE
Translate-attr - use in myDirective not working as I expected

### ISSUE THREAD

**Issue by ascholz81** [angular-translate/angular-translate#902]
I created a custom directive that consists of two input boxes with labels next to them.  I want to use the translate library to provide the labels for those input boxes.
myDirective does have an isolate scope.
<myDirective translate translate-attr-label1="myLabelTranslationKey" 
                      value="myModel.myValue" ></myDirective>

The first issue is that myDirective's isolated scope conflicts with the translate directives isolated scope and generates an angular error that two directives on the same element are requiring isolated scopes.

I have a fiddle created to display this issue.  http://jsfiddle.net/ascholz81/tym7tndn/
The second issue is the order that the link functions execute.
I did update the priority of both myDirective and translate.  myDirective = -1 and updated translate to 500 (just for kicks.)
myDirective compiled after translate, however the link function for translate executed after the link function for myDirective.  So, translate does work in translating and creating the correct attribute, but myDirective can't see it at the time its link function executes.

It would be nice to let the translate service work independently of my directive so my directive simply gets a text string for the label.

Thanks,
Adam

**Comment by david-hollifield** [comment]
I'm having a similar problem where my directive's scope is being "overridden" by translate's scope. My directive contains an input that uses translate and translate-attr-placeholder to show placeholder text. I have a directive binding for that input's text value using the "=" setting. When translate exists on the input control, that binding result ends up in translate's scope instead of the scope defined by the "=" setting.

**Comment by knalli** [comment]
At the moment the implementation of the directive defines its own scope. Regardless using `translate-attr` or not.

Personally, I would prefer to reduce the whole scope thing, but at the moment we have no time for that. If you have the opportunity and can make up a solution resolving the features without such a scope, please make a PR. It is very welcome.

**Comment by david-hollifield** [comment]
I resolved the problem by creating my own directive that works a little differently. You use it like so:

```
<input type="text"
           name="state"
           class="form-control"
           ng-model="region"
           placeholder="Payment_State"
           translate-attr="placeholder"
           required>
```

The directive has the list of attributes (separated by ';') to translate and each attribute contains the translate key. The directive is pretty simple, not as elegant, but won't destroy my scopes:

```
(function (module) {
    "use strict";

    module.directive("translateAttr", translateAttr);

    translateAttr.$inject = [
        "$filter",
        "$timeout"
    ];

    function translateAttr($filter, $timeout) {
        return {
            restrict: "A",
            link: link
        };

        function link($scope, $element, $attrs/*, controller*/) {
            var attrNames = $attrs.translateAttr.split(";"),
                translateKey,
                translateValue;

            _.each(attrNames, function (attrName) {
                attrName = _.trim(attrName);

                $timeout(function () {
                    translateKey = $element.attr(attrName);
                    translateValue = $filter("translate")(translateKey);

                    $element.attr(attrName, translateValue);
                }, 100);
            });
        }
    }
})(angular.module("app.directives"));
```
