### ISSUE TITLE
Can I mark $translate as "not ready until I say it is"?

### ISSUE THREAD

**Issue by tlycken** [angular-translate/angular-translate#904]
I have a use case where the preferred language shouldn't be set by the browser setting, but rather by a setting on the server. To accomplish this, I have something like this in my application config:

```javascript
var app = angular.module('myApp');
app.run(chooseLanguage);

chooseLanguage.$inject = ['$http', '$translate'];
function chooseLanguage($http, $translate) {
    $http.get('/api/localization/preferred-culture').success(function (language) {
        $translate.use(language);
    });
}
```

I've also defined a fallback language, using

```javascript
app.run(configure);
configure.$inject = ['$translateProvider']; // and a bunch of other stuff
function configure($translateProvider) {
    $translateProvider.useLoader('translationLoader', {}); // My own translation loader
    $translateProvider.fallbackLanguage('en-GB');

    // ...and configure other stuff
}
```

What happens when I load the page is that all resources that are translated through the `$translate` service (which, unfortunately, are quite a few) before the HTTP request returns, are translated into the fallback language even if the key exists in the preferred dictionary (since I haven't told angular-translate that I want that dictionary yet).

Is there some way I can tell the library that "hey, wait a minute; we're not ready configuring you until this promise resolves". It's completely OK to cloak all translated content until then, but I'd rather not block the JS thread waiting for an asynchronous call...

**Comment by DWand** [comment]
Hello, @tlycken. As far as I know, there are no such settings. But you can try:

* Generate a JS file on the server, which will set up a language during configuration phase instead of making an ajax request (I'd prefer this approach)
* Move language selection logic to the client
* Replace angular-translate's `run` method with your own (adds ability to start the module by yourself, but makes it harder to update the module)
* Maybe it is possible to control this stuff by a custom loader somehow

**Comment by knalli** [comment]
> Is there some way I can tell the library that

No. It is simple like that: asap the AngularJS is starting itself, all `config()`'s, all `run()`'s and so on will be invoked. Your suggestion would also result into an issue: what translation definition does you app have if your xhr would fail? No translations? Never? Maybe a (system) fallback is not a bad choice after fall.

Anyway: A global delay intercepted in a custom loader would be possible. At the moment we are not planning for such stuff.
