### ISSUE TITLE
Translating text within controller

### ISSUE THREAD

**Issue by sharanmunyal** [angular-translate/angular-translate#905]
The issue is regarding retrieving translated text from a JSON file which is asynchronously downloaded using angular-translate-loader-static-file package. I am looking to get value of LEFT_NAV.SEARCH_ALL_FILES in the following code. The only solution I can think of is using a $scope.$watch on as I have used here; but it is not a performant solution since we might have too many watches in the code. Due to asynchronous nature of file download, I see LEFT_NAV.SEARCH_ALL_FILES if I don't use the $watch. Can you help me with a better solution?

            controller: ['$scope', '$log', '$location', '$routeParams', '$filter',
            function ($scope, $log, $location, $routeParams, $filter) {
                $scope.query = '';
                if ($routeParams.queryString) {
                    $scope.query = $scope.escapeHTML(decodeURIComponent($scope.sanitizeQuery($routeParams.queryString)));
                }
                $scope.$watch(
                    function() {
                        return $filter('translate')('LEFT_NAV.SEARCH_ALL_FILES');
                    },
                    function (translatedValue) {
                        $scope.placeholder = translatedValue;
                    });
                // Click handler for clearing the search
                $scope.clearSearch = function () {
                    // Clear the query
                    $scope.query = '';
                    // Based on the current state, choose the view
                    $location.path('/mydocs');
                };
                $scope.search = function () {
                    if ($scope.query) {
                        $location.path("/search/" + encodeURIComponent($scope.sanitizeQuery($scope.query)));
                    }
                };
            }],
            template:
                '<div>' +
                '<form class="navbar-form" ng-submit="search()">' +
                    '<input type="text" placeholder={{placeholder}} ng-model="query" name="query" gb-focus-on="gbsearch"/>' +
                    '<a ng-click="search()"><i class="icon-search icon-large"></i></a>' +
                '</form>' +
                '</div>'

**Comment by tspaeth** [comment]
I see some minor issues here:
- there are no "quotes" around the placeholder expression -> will render invalid html
- is there a reason why you're using the filter approach instead of  $translate('LEFT_NAV.SEARCH_ALL_FILES')?
If you inject $translate into the controller and do
```
$translate('LEFT_NAV.SEARCH_ALL_FILES').then(function (data) {
  $scope.placeholder = data; 
});
```
what happens? (remark: it will not update on language change automatically - you have to watch that event probably)

**Comment by sharanmunyal** [comment]
yes. I just verified. It didn't update on using $translate('').then()

**Comment by tspaeth** [comment]
So - then you could watch on a translate change inside the directive. Or if it was working already with the filter - also okay :-).

**Comment by sharanmunyal** [comment]
sounds good. I will stick to the filter then. Thanks for the reply @tspaeth
