### ISSUE TITLE
Issues with partial loader

### ISSUE THREAD

**Issue by Lukec1** [angular-translate/angular-translate#906]
Hi,

I have wrote test web page which uses angularjs, angular-route and angular-translate(http://plnkr.co/edit/VfOuAKHp63dqaJ9QJxQH?p=preview). In this project i have problem with $translate.refresh(), it's working when i first call it in the same controller, but when i call it again, it doesn't change anything.

Thanks for any helpful information!

**Comment by tspaeth** [comment]
I don't see that issue with refresh there. I see more an issue on the translation key namings. You should NOT give the keys in the json files the same names always as they are all loaded into the same namespace in your case. Therefore overriding each other in some cases.

**Comment by Lukec1** [comment]
Many thanks!! I've lost many time to solve MY mistake :)

SOLVED!
