### ISSUE TITLE
useStaticFilesLoader allows browser to cache json files

### ISSUE THREAD

**Issue by vladsd** [angular-translate/angular-translate#908]
Different language files when loaded are cached by the browser unless one clears cache or forces file reload via url.

Browser should not be caching files or function to force refresh should be provided.

**Comment by knalli** [comment]
@vladsd Read the manual.

You have following options:

1. Provide additional `$http` parameters part of _loader options_.
2. Provide a (custom) _loader cache_.
3. Provide appropriate configuration in **your* server.

**Comment by vladsd** [comment]
Adding global config solves the issue:
// from http://stackoverflow.com/questions/16098430/angular-ie-caching-issue-for-http
app.config(['$httpProvider', function ($httpProvider) {
    //initialize get if not there
    if (!$httpProvider.defaults.headers.get) {
        $httpProvider.defaults.headers.get = {};
    }
    //disable IE ajax request caching
    //$httpProvider.defaults.headers.get['If-Modified-Since'] = '0';
    $httpProvider.defaults.headers.get['Cache-Control'] = 'no-cache';
    $httpProvider.defaults.headers.get['Pragma'] = 'no-cache';
}]);

**Comment by tspaeth** [comment]
I wouldn't advise to completely disable caching - why should you do that? This means that also static resources would never be cached plus all AJAX-calls with not-changing content.
From a perspective of data transfer limitation and delays this is really against all the principles... :)
