### ISSUE TITLE
Unconsistent behaviour with translate directive and translation ID to be partially interpolated

### ISSUE THREAD

**Issue by jljouannic** [angular-translate/angular-translate#909]
When the translation ID is to be partially interpolated before translation, the translation result is different on whether the translation ID is indicated in the translate attribute or in the body of the element to translate. Even in this last situation, the result is not the same if you put some new line or not before the translation ID.

You can check the different results in this plunk: http://plnkr.co/edit/roBQYzfFY99tA3n6c4tT?p=preview

**Comment by knalli** [comment]
Thank yo, can confirm this. I've mixed some versions: neither AJS 1.2 or an earlier translate 2.4.2 behave better.

**Comment by tspaeth** [comment]
related to #879 ?

**Comment by knalli** [comment]
coming in next
