### ISSUE TITLE
Translating integers

### ISSUE THREAD

**Issue by sharanmunyal** [angular-translate/angular-translate#911]
How do I translate integers? Do I need to precompute the values and store in the translation table? or can I leverage angular-translate in some way?

**Comment by DWand** [comment]
@sharanmunyal, hello. Can you how an example, please?

**Comment by sharanmunyal** [comment]
@DWand so I want to translate "Version 2 of 3". I am wondering how do I translate 2 or 3 to different languages?

**Comment by DWand** [comment]
You have to provide translation tables like this:

```
// en
{ "version" : "Version 2 of 3" }

// uk
{ "version": "Версія 2 з 3" }

// ru
{ "version": "Версия 2 из 3" }
```
Maybe there are some other ways to do this, but I don't know them.

**Comment by sharanmunyal** [comment]
Well I am looking for a way how we could translate the number. I agree I can always translate 'Version' and 'of' from the above string.

**Comment by DWand** [comment]
I'm not sure that I understand you right. But, maybe, you can also try to use something from the following to achieve the needed behavior:

* Links in translations: http://angular-translate.github.io/docs/#/guide/02_getting-started
* Variable replacement: http://angular-translate.github.io/docs/#/guide/06_variable-replacement
* Custom interpolators: http://angular-translate.github.io/docs/#/guide/15_custom-interpolators
* Add some filters to translations (not sure if it will work)

**Comment by knalli** [comment]
How we can "translate" numbers? A _number_ is - written the (western) arabic way - always the same.

Is there anything still open here?

**Comment by sharanmunyal** [comment]
I am not sure if I explained it correctly. The number 1 is written एक in my native language. I think I will have to precompute in the translation table and store it.

**Comment by robjames** [comment]
Yep, not sure this should be closed. 

I need to do the same as @sharanmunyal (but for Chinese). I guess i will have to add them all as keys?
