### ISSUE TITLE
Translations using ng-bind for a label only load after I refresh the page

### ISSUE THREAD

**Issue by tantommy** [angular-translate/angular-translate#912]
Here's the label part of the directives html:
```
        <div class="control-label">
            <label
                   ng-bind=":: vm.config.label | translate">
            </label>
        </div>
```
When I switch languages, this label doesn't automatically get translated.  I have to refresh the page before the translation goes through.  Is this usual behavior for angular-translate?

Just to give some context, these are form field labels being translated.  When I'm on the page, I have a drop down that selects different languages.  Once I select a different language anything that needs translating that is declared this way translates instantly:
```
<span>{{ 'TRANSLATION_ID | translate }}</span>
```

**Comment by knalli** [comment]
What do you mean with "I have to refresh the page"?

Anyway.. please make a demo i.e. with plunkr or jsfiddle so we can see what you mean.

**Comment by tantommy** [comment]
I have to hit the refresh button on my browser in order to see the translation take effect.
Here is a demo on plunkr:
http://plnkr.co/edit/2Fa9P2szD8dFgWUSS9So?p=preview

The an explanation is in the README but the tldr is:
switching languages using the dropdown does not work on the label. it only works after i refresh the page.

**Comment by tspaeth** [comment]
(I'm not sure if I got the problem / place right, but:)

Well, you're explicitly disabling the watchers / two way binding with the ":: " prefix in your email.directive.html - so how should the update work in that case?
If you remove this prefix, also your upper "E-Mail now in ..." will be updated.

**Comment by tantommy** [comment]
I realized this after messing with the demo.  The demo works fine if I take away the ":: " prefix, but in my project it's not doing the same thing.  There may be some other issues that I'm not seeing.  Thanks for the response though, we can close this for now.
