### ISSUE TITLE
How to mark HTML in dynamic value as safe?

### ISSUE THREAD

**Issue by szimek** [angular-translate/angular-translate#915]
Hi,

I've got the following code:
```javascript
$scope.translationKey = "KEY"
$scope.translationData =
    html: "<em>something</em>"
```

```html
<div translate="{{translationKey}}" translate-values="{{translationData}}"></div>
```

Is there any way to mark HTML in `$scope.translationData.html` as safe, so that it's not escaped?

**Comment by knalli** [comment]
Despite the corresponding chapter in the docs (http://angular-translate.github.io/docs/#/guide/19_security), you should use `<div translate="{{translationKey}}" translate-values="translationData"></div>` which is not a filter intercepting your scope data.

**Comment by szimek** [comment]
@knalli Thanks! Unfortunately, in my app I've got:
```
$translateProvider.useSanitizeValueStrategy('escaped');
```
and thus it doesn't work and still escapes HTML. It looks like it's going to be a default in the future, so is there a way to disable it in a specific place? Here's a Plunker that I used to check why it doesn't work http://plnkr.co/edit/4U2jcDN99Shyd5FIg2L4?p=preview

**Comment by knalli** [comment]
Three ways:

# Do not use ‚escaped‘  but ‚default‘.
# Implement an own strategy which would treat specific input as safe (like AJS 1.3 $sce)
# Combine the translation in you own controller/directive/service being sure no malicious input could be injected.

**Comment by szimek** [comment]
Went with the last option (no idea why I haven't thought about it sooner) and it works perfectly. Thanks!
