### ISSUE TITLE
Error when using use method

### ISSUE THREAD

**Issue by Purus** [angular-translate/angular-translate#916]
I am using the below code to change the language on the fly. 

```
$translate.use(langKey);
```

In the console I see the below error. But every functionality works fine without any issues. But still, this error troubles me.

```
 TypeError: undefined is not a function
    at D (angular-translate.min.js:6)
    at Function.$get.N.use (angular-translate.min.js:6)
    at Object.fn (index.controller.js:126)
```

**Comment by DWand** [comment]
Hello, @Purus. Can you show a plunker for your set up?

**Comment by knalli** [comment]
I would say you are using a very old version of angular-translate... ;)
