### ISSUE TITLE
precompiling html templates into $templateCache breaks translation

### ISSUE THREAD

**Issue by bcamp1973** [angular-translate/angular-translate#917]
during our build process we inject all html templates into the $templateCache to reduce server requests. for the most part it seems to work. however, we get seemingly random instances of broken translation...even on the same page some elements will translate while others will not. Anyone else seeing this?

![screen shot 2015-02-09 at 3 27 09 pm](https://cloud.githubusercontent.com/assets/27823/6117294/a2ad6e6c-b070-11e4-995c-c03ec35d1c9a.png)

**Comment by bcamp1973** [comment]
anyone?

**Comment by knalli** [comment]
Could you please make a standalone test case showing the problem? For example with plunkr, jsfiddle.

**Comment by uberspeck** [comment]
Here's a [plunkr](http://embed.plnkr.co/bbopDGo2ACbNEFOvkwKI/preview) of the issue I'm seeing. Anything using the directive translates, anything using the filter does not...

**Comment by tspaeth** [comment]
Well:
a) you should use the latest angular-translate and not 2.2.0
b) you should use the right keys "login.password" and not "password" 

Here is the working, updated plunker (I was to lazy to swap the loader to a current version - so I left it at 2.2.0 as it seems to work ok for this demo:

http://plnkr.co/edit/76oAY5y40BpFxCbi0WeR?p=preview

Any defects or issues left?

**Comment by bcamp1973** [comment]
looks like the update solved it, thanks!

**Comment by goliney** [comment]
@tspaeth Sir, you saved my day.

**Comment by tspaeth** [comment]
Huh, but thanks :smiley:
