### ISSUE TITLE
useStaticFilesLoader with fallbackLanguage

### ISSUE THREAD

**Issue by sharanmunyal** [angular-translate/angular-translate#920]
I have a usecase where if the translation table for a language is absent and hence cannot be downloaded using useSaticFilesLoader, I want to fallback to 'en'. However

$translateProvider
.useStaticFilesLoader({
prefix: SourceConstant.FILES + 'lang/strings_',
suffix: '.json'
})
.registerAvailableLanguageKeys(['en'], {
'en_US': 'en',
'en_UK': 'en'
})
.fallbackLanguage('en')
.determinePreferredLanguage();

This piece of code returns the translation ID instead of the english translation if table for the determined language is missing. Am I missing something ?

**Comment by DWand** [comment]
Does the loader load translations for English?
Can you create a plunker with your setup? This way it will be much easier to determine why you are facing the problem.

**Comment by tspaeth** [comment]
Hm. Aren't you only mapping everything to en - no matter if it was en_US or en_UK?

And for a fallbackLanguage - you should define another language than the one that will be mapped by the preferredLanguage.
Maybe that helps. Otherwise - please setup a short plunkr.

**Comment by sharanmunyal** [comment]
So I am setting my browser language to French and I don't have the 'fr' translation table. Instead of falling back to 'en', it shows me the translation ID. So there are two calls made. One for strings_en.json(this succeeds but remains unused) and one for strings_fr.json(this fails as expected).

**Comment by knalli** [comment]
@sharanmunyal  Can you please make a small test case. You can use this template: http://plnkr.co/BJJwHaHnVFOIVYQjGuM2

**Comment by sharanmunyal** [comment]
@knalli Here is the plnkr URL using the template you mentioned http://plnkr.co/K4Qz3vbGHDcD8SexvUEL. If you change your browser to use language say 'French' as the first option and open the index.html in Plnkr, it shows the key instead of downloading the English translation table and using the values from that.

**Comment by knalli** [comment]
@sharanmunyal  Thank you, that helps a lot! Big issue actually, fix applied in seconds and coming in next release!

**Comment by knalli** [comment]
Here is a patched version active: http://plnkr.co/edit/tC1BMScY804DEsKNTLE5?p=preview

**Comment by llopv** [comment]
I have the same problem, and the workaround right now is to call the `fallbackLanguage` after define the language:
```js
$translateProvider
...
.determinePreferredLanguage();
.fallbackLanguage('en')
```
If you want to test the issue, I have a demo:
```
git clone -b tranlate-issue --depth=1 https://github.com/llopv/angular-seed/
```
