### ISSUE TITLE
Documentation: grunt replace helper for FUOC issues

### ISSUE THREAD

**Issue by marcalj** [angular-translate/angular-translate#921]
Hi, I'm using the FUOC solution you mentioned on the [documentation](http://angular-translate.github.io/docs/#/guide/12_asynchronous-loading#asynchronous-loading_fouc---flash-of-untranslated-content).
To keep using JSON files but loading the fallback first in the code I've made a helper, and I want to know if you mind to include it in the docs.
I'm not using gulp, so no idea if it's also possible.

I'm using AngularJS with Yeoman setup.
Create ```./config/defaultI18n.js``` file:
```js
'use strict';

angular.module('services.defaultI18n', [])
    .constant('defaultI18n', {
        // jshint quotmark:true
        en: @@content
    });
```

Install [grunt-replace](https://github.com/outaTiME/grunt-replace) plugin and configure it like:
```js
replace: {
        defaultI18n: {
            options: {
                patterns: [{
                    match: 'content',
                    replacement: '<%= JSON.stringify(grunt.file.readJSON(\'./app/i18n/en.json\')) %>'
                }]
            },
            files: [{
                expand: true,
                flatten: true,
                src: ['./config/defaultI18n.js'],
                dest: '<%= yeoman.app %>/scripts/services/'
            }]
        }
    }
```

Put ```replace:defaultI18n``` job on ```serve```, ```test``` and ```build``` tasks (on the beginning).

Include it on ```index.html``` file:
```html
<script src="scripts/services/defaultI18n.js"></script>
```

Include the module in your app:
```js
angular
    .module('myApp', [
        'services.defaultI18n',
        ...
    ])
```

Configure ```$translateProvider```:
```js
    .config(function ($translateProvider, defaultI18n) {
        // Angular translate

        // Prevent FUOC pre loading english translations
        $translateProvider.translations('en', defaultI18n.en);

        // Configure angular-translate to load static JSON files for each language
        $translateProvider.useStaticFilesLoader({
            prefix: 'i18n/',
            suffix: '.json'
        });

        // Tells angular-translate to use the English language
        $translateProvider.preferredLanguage('en');

        // Tells angular-translate to use the English language if translations are not available in current selected language
        $translateProvider.fallbackLanguage('en');
    })
```

So now you can have all your translation JSON files in one place and keep using grunt's ```i18nextract``` task.

Bonus: Prefetch others translation files
```html
<head>
    ...
    <link rel="prefetch" href="i18n/es.json">
    ...
</head>
```

I hope I can help people with https://github.com/angular-translate/angular-translate/issues/535 issue.

Salut! (Cheers!)

**Comment by knalli** [comment]
@DWand  @tspaeth 

Could you make additions for the missing languages as well (see 0d5d494 it's only one line)?

* [ ] fr
* [ ] ru
* [ ] uk
* [ ] zh-cn ?
* [ ] zh-tw ?

**Comment by knalli** [comment]
@marcalj  Thank you.. I've added the link in the docs.

**Comment by DWand** [comment]
@knalli, I'll translate it to Ukrainian and Russian languages in something about 24-30 hours.

**Comment by tspaeth** [comment]
My chinese is too bad ;-)
And the french is too long ago to write a correct sentence...Sorry... 

But maybe @firehist can help out once?

**Comment by DWand** [comment]
@knalli, added in #1004

**Comment by marcalj** [comment]
:+1:

**Comment by knalli** [comment]
Closing this. Looks like we cannot provide synced translations for the missing ones..
