### ISSUE TITLE
Hability to use Java properties file format

### ISSUE THREAD

**Issue by jmaister** [angular-translate/angular-translate#924]
Java properties files parameters use numbered and single curly braces.

    INFO=Step {0} of {1}

Instead of:

    INFO=Step {{step}} of {{total}}

The arguments passing would be using an array:

    <span>{{'INFO' | translate:[data.step, data.total]}}</span>

It would help to reuse old/new resource files from Java applications with angular-translate on the client.

**Comment by DWand** [comment]
Hello, @jmaister.

1) To replace the JSON format with the Java properties file format you have to create a custom loader. This loader will request needed files from the server and convert them to JS objects. You can find more about custom loader here: http://angular-translate.github.io/docs/#/guide/13_custom-loaders

2) To replace default Angular's `{{ ... }}` with `{ ... }` you can to create a custom interpolation service. More information about the custom interpolators: http://angular-translate.github.io/docs/#/guide/15_custom-interpolators
Also, you might be interesting to read the chapter about the pluralization support: http://angular-translate.github.io/docs/#/guide/14_pluralization. The MessageFormat library, which is used to provide pluralization at the moment, does this replacement.

3) I'm not sure about arrays. Most probably, you can use them like you've shown above or in some similar way. Also you can try to use something like this: `<span>{{'INFO' | translate:'{0: data.step, 1: data.total}'}}</span>`.

**Comment by jmaister** [comment]
Thanks for the answer!
I'm going with the solution of creating a custom interpolator. It replaces {0}, {1}, ..., {n} with the values from the parameters.

About the parameters, I went with the array mode. It gets quite difficult to read the code on the template as it needs to create a map inside the curly braces inside the string... but it works too.

    
    <span>{{'INFO' | translate:'{0:'+status.step+', 1:'+ status.total+'}'}}</span>

    
    <span>{{'INFO' | translate:[status.step, status.step]}}</span>
