### ISSUE TITLE
Load common translations and then load module partials:

### ISSUE THREAD

**Issue by cmjonescm** [angular-translate/angular-translate#926]
What I want to do is load the translations for each module as the view is changed. For this I've used the partial loader and a resolve on the route. This works really nice! 

The problem I have is I also have platform, bash board and some common translations, which I would like to load upfront and to always be available! 

e.g.

/framework/client/i18n/en.json
/modules/instrument/common/client/i18n/en.json

/modules/instrument/tune/client/i18n/en.json
/modules/instrument/vacuum/client/i18n/ee.json
/modules/instrument/scopeMode/client/i18n/en.json
/modules/instrument/calibration/client/i18n/en.json

The first two are platform and common components which I would like to load, and as you can see they are also have different paths to the modules!

I did try loading the platform/common translations using $translateProvider.translations(), but once any partial load is performed the common stuff was no longer available!!

**Comment by DWand** [comment]
Hello, @cmjonescm.

You are right, there are no ways to set URL's with different structure in the partial loader. As a workaround you can try to name the part as something like: '../../framework'. The resulting URL of the part for the 'en' language key will look like this 'http://example.com/modules/instrument/../../framework/client/i18n/en.json'.

Also, don't try to use $translateProvider.translations() with the partial loader. All translations you've added this way will be lost once you call the $translate.refresh() method. To keep these built in translations you have to add them to the loader itself. It can be easily done by using the $translatePartialLoaderProvider.setPart() method. Such translations will last until you say the loader to delete them.
