### ISSUE TITLE
Determine Preferred Language when locale is coming from server

### ISSUE THREAD

**Issue by abdheshkumar** [angular-translate/angular-translate#927]
@PascalPrecht 
HI Pascal
1. I Want to use browser locale when user is not login, in this case page would serve index.html. For this i have used $translateProvider.determinePreferredLanguage() that would translate according to browser locale, it's working very well.

2. Once user login, then home.html page would serve and there want to use user's locale.

So there is any way to determine preferred language on the basis of user's locale that's coming from server.

(function() {
	'use strict'
	var mainApp = angular.module("mainApp", [ "ngResource", "ngCookies", "pascalprecht.translate" ]);
	mainApp.config(function( $translateProvider) {
		$translateProvider.useStaticFilesLoader({
			prefix : '/lang/',
			suffix : '.json'
		});
		$translateProvider.determinePreferredLanguage(function () {
                      // here I want to call rest api that would return user locale for example              {"status":200,"locale":"de_DE"} and then switch locale according to rest response

                 });
		$translateProvider.useCookieStorage();
	});
})();

**Comment by tspaeth** [comment]
You just have to write your own logic on processing the REST response and then call and set the stack correctly with
``
$translate.use(....)
```

**Comment by abdheshkumar** [comment]
Oh.!! Thanks for quick reply.
@tspaeth  I am not able call resource in $translateProvider.determinePreferredLanguage function.
how can i inject $resource or $http services in that function.?

**Comment by tspaeth** [comment]
If you take a look at the documentation at https://docs.angularjs.org/guide/module, you'll see that basically, it is (better : should not be) not possible to use services in the configuration / bootstrapping phase. There are modules like https://github.com/philippd/angular-deferred-bootstrap or https://github.com/rajeshsegu/angular-lazy-bootstrap that might help here. But that is out of scope for our module.

**Comment by knalli** [comment]
Well. The `$translate.use()` must be implemented in your `run()` or any other controller/service. You should define a static (unless you expose this one directly in the html) language id, in order the app can show you text until your custom language negotiation has been resolved. Actually a classic "language stored in server side session" scenario.
