### ISSUE TITLE
Avoid registerAvailableLanguageKeys()

### ISSUE THREAD

**Issue by canda** [angular-translate/angular-translate#932]
Is it possible to ask for the language omitting the country on the getPreferredLanguage() method?
I have a translation for english with code "en". I don't care if the user is from australia, new zeland or whatever, I want him to use english translation if english is his language. 
It would be nice not having to hardcode 
registerAvailableLanguageKeys(['en', 'de'], {
    'en_US': 'en',
    'en_UK': 'en',
    'en_AU': 'en',
    'en_BZ': 'en',
    'en_CA': 'en',
    'en_CB': 'en',
    [...]
  })

**Comment by tspaeth** [comment]
You can use a wildcard according to https://github.com/angular-translate/angular-translate/commit/6f0ae3bf6dd873534c9957b2cce398b290c92da7

Maybe it is missing in the docs, but that should work!

so just do a
```
'en_*': 'en'
```

**Comment by canda** [comment]
Great, thanks.
The Docs should be updated then
