### ISSUE TITLE
Link inheritance

### ISSUE THREAD

**Issue by kamituel** [angular-translate/angular-translate#933]
When there is a translation linking to the other (`@:`) in the fallback lang file, and this link is overriden in the preferred lang file - but the link target is not, angular-translate would use the value from the fallback language.

I guess I better show an example: http://jsfiddle.net/L0fju75b/. I would expect to see "MM/DD/YYYY", while I see "DD/MM/YYYY":

```
var m = angular.module('MyApp', ['pascalprecht.translate']);

m.controller("MyCtrl", function() {
});

m.config(function($translateProvider) {
    $translateProvider
    .translations('en', {
        "date format": "DD/MM/YYYY",
        "subpage": {
            "date format": "@:date format"
        }
    })
    .translations('en_US', {
        "date format": "MM/DD/YYYY"
    })
    .fallbackLanguage('en')
    .preferredLanguage('en_US');
});
```

For HTML:

```
<div ng-app="MyApp">
    <div ng-controller="MyCtrl">
        {{ "subpage.date format" | translate }}
    </div>
</div>
```

Is it a bug, or a design feature? It limits usefullness of links in the fallback scenario.

**Comment by tspaeth** [comment]
Currently, the application is designed to "follow the links" in the same language tables as the missing key. No mixing of translation tables on following links in case a key is not found.

**Comment by kamituel** [comment]
I see. Are there plans to have this kind of functionality? Otherwise I guess I will need to not include more translation keys in the prerred language file. That's a pity, because in my case those are two very similar files - `en` and `en_US`.

**Comment by tspaeth** [comment]
No, there are no plans. But feel free to hand in a PR on this.

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity.
