### ISSUE TITLE
Dynamic translation key

### ISSUE THREAD

**Issue by JKorf** [angular-translate/angular-translate#934]
Hello,

I was wondering if it is possible to dynamically retrieve a translation based on the value of a scope variable. In my application I use ui.router and automatically build a menu based on the registered states, where a state is defined as followed:

state: 'settings preferences',
config: {
	url: '/settings/preferences/',
        templateUrl: 'app/settings/preferences/preferences.settings.html',
	controller: 'PreferencesSettingsController',
	controllerAs: 'vm',
	title: 'Preferences settings'
}

Now the title should be translated, but I don't really see how I can do this. The title is shown on the page as a simple scope variable: 

<div class="page-title">{{vm.page}}</div>

Of course the page title can change depending on what page we are on. Please advice me on what the best way is to translate this.

**Comment by knalli** [comment]
`ui.router` has to be defined in the config phase, whereas no translations are available.

So, no you can't use this static `title`. You have to look for an alternative way, i.e. via an asynchronous title apply.

**Comment by DWand** [comment]
But you can use this field to store a translation key instead of the direct translation.
However, if I understand right, this will also require to write additional code either in controllers or directive. Something like this:
```js
angular.module('...').directive('title', [
'$rootScope', '$translate',
function titleDirectiveFn($rootScope, $translate) {
    return {
        restrict: 'E',
        link: function linkFn(scope, elem, attrs) {
            $rootScope.$on('$stateChangeSuccess', function (e, toState, toParams, fromState, fromParams) {
                $translate(toState.title)
                  .then(function successFn(title) {
                    elem.html(title);
                  }, function errorFn(translationID) {
                    // something happened, translation was not done
                  });
            });
        }
    };
}]);
```
