### ISSUE TITLE
Using $translate inside the controller returns {"$$state":{"status":0}}

### ISSUE THREAD

**Issue by tobika** [angular-translate/angular-translate#935]
Hi,
I would like to get some translated strings to use them directly in the js code.
But when I use:
`$translate('settings_CONFIRMDELETE');`
I always recieve a
`{"$$state":{"status":0}}`

Does anyone know why this happens?

Just to be clear, I use angular translate in the html markup via filters and it works just fine. So the module itself seems to be loaded. Also for information, I use the Ionic framework with angular 1.3

Thanks a lot.

**Comment by tspaeth** [comment]
Hi!

Could you setup a short Plunkr for your problem as a demo to outline the problem? I've never seen this in my projects here, so there might be some combination not working or so...

**Comment by DWand** [comment]
Hello, @tobika. The `$translate` service returns a promise. What do you get with the following code?

```js
$translate('settings_CONFIRMDELETE').when(function successFn(translation) {
  console.log('Translation successfully done:', translation);
}, function errorFn(translationId) {
  console.log('Translation failed:', translationId);
});
```

**Comment by tobika** [comment]
ups, thank you @DWand, when I use the promise everything works fine.

I was reading an old tutorial where $translate was a call without a promise. Just checked the official docs and everything is well explained there. Sorry for that.

In your code example I think you wanted to write `then` instead of `when`

Thanks for you fast response everybody.

**Comment by DWand** [comment]
@tobika, you are right. It was `then`. Sorry :-)
