### ISSUE TITLE
Is there support for escaping HTML.

### ISSUE THREAD

**Issue by itonics-tbeauvais** [angular-translate/angular-translate#938]
We have a few trivial cases where the translation of the tokens needs to be formatter with a little basic HTML.  

Right now the string 
```
{'drag_file' : "<p>Drag file here</p><p>or</p>"}
```
will output just that by default.

Is this bad practice or is there a way to escape basic HTML?

**Comment by antonsekatski** [comment]
You can use ```ngBindHtml``` directive:

```html
<div ng-bind-html="'TEST.NAMESPACE' | translate"></div>
```
Works like a charm.

**Comment by itonics-tbeauvais** [comment]
Interesting.. thanks! :)
