### ISSUE TITLE
Question: Is this not available as a Ruby gem?

### ISSUE THREAD

**Issue by kdsingharneja** [angular-translate/angular-translate#939]
Is this not available as a Ruby gem? If you are planning for it, then what is the ETA? 

thanks

**Comment by knalli** [comment]
No. Neither anyone has requested this, nor I'm not sure whether is useful. However, I'm not in Ruby development. 

Unless this would be easy step for releasing (I have no plan about requirements), I don't see this coming. 

But in general, PR and concepts are welcome.
