### ISSUE TITLE
Non-string translationId should be converted to string before calling trim

### ISSUE THREAD

**Issue by FarSeeing** [angular-translate/angular-translate#940]
Non-string `translationId` should be converted to string before calling `trim` polyfill.

Real life example: [angular-rangeslider](https://github.com/danielcrisp/angular-rangeslider) gives user ability to specify output filter, but always passes numbers to it and this causes error since `angular-translate` tries to call `replace` on these numbers.

**Comment by knalli** [comment]
Yes, this would be internal enhancement. Said this, everything other than a string is not supported by definition.

* https://github.com/angular-translate/angular-translate/blob/133463ab279b6852f1f5190c43e12b6dcefe41f4/src/directive/translate.js#L15
* https://github.com/angular-translate/angular-translate/blob/133463ab279b6852f1f5190c43e12b6dcefe41f4/src/filter/translate.js#L13

**Comment by FarSeeing** [comment]
But `null` and `undefined` values are supported?

**Comment by tspaeth** [comment]
In the filter (more precisely in the instant - translation function of the service), we have a check on if the key is null or undefined. In this case it returns the translationKey... (so in that case null or undefined).

**Comment by FarSeeing** [comment]
OK, close this issue, I will fix this on our side by adding custom filter-wrapper.
