### ISSUE TITLE
angular-translate and angular material design not playing together...

### ISSUE THREAD

**Issue by AntonTrapp** [angular-translate/angular-translate#941]
As I have no idea if it's a angular-tranlsate or material design bug (if later: https://github.com/angular/material/issues/1742). I can't use the 'translate' filter together with a input field and a placeholder (md-input-container), the placeholder is generated twice if I click into the field.

```
= f.email_field :email, placeholder: 'hugo', data: {'ng-model' => 'user.email', 'md-maxlength' => 250}
```
is working
```
= f.email_field :email, placeholder: '{{"model.user.email_placeholder" | translate}}', data: {'ng-model' => 'user.email', 'md-maxlength' => 250}
```
produces the ugly "I'm drunk design" with two placeholders.

**Comment by knalli** [comment]
That is not an issue with translate. I have found your Pen http://codepen.io/anon/pen/OPBxBe and it clearly uses only a filter. In filters, no DOM operations are involved.

Sorry.

**Comment by AntonTrapp** [comment]
Thanks for your answer, hope the material team will fix the issue. Btw. thanks for the good work and the support!

**Comment by epeleg** [comment]
Anton, where you able to resolve this?

**Comment by AntonTrapp** [comment]
Not using material any more, but I think I wrote a directive and did the translation manually and constructed the HTML with the translated text instead. (works like hardcoded)

**Comment by epeleg** [comment]
o.k., thanks.

**Comment by thanuzz** [comment]
I've created a workaround by extending the Angular Material Placeholder directive. I've created an overrule js file in my project with the following code:

```
(function () {
	'use strict'

    angular.module('app.core').config(['$provide', function ($provide) {
    	$provide.decorator('placeholderDirective', ['$delegate', '$translate', function ($delegate, $translate) {
    		var directive = $delegate[0];
			var link = directive.link;

			directive.compile = function () {
				return function (scope, element, attr, inputContainer) {
					link.apply(this, arguments);
					$translate(attr.placeholder).then((translation) => {
						inputContainer.element.find('label').text(translation);

						//Only uncomment following line if you're using static labels or md-no-float attribute
						//element.attr("placeholder", translation);
					});
    			};
    		};

    		return $delegate;
        }]);
    }]);

})(); 
```

The placeholder attribute's value should be the translation key:
```
<input ng-model="myProfile.phone" placeholder="myProfile.phoneNumber" type="tel"  />
```

The decorator injects the $translate service. In the extended link function the translate service is called with the placeholder value and with the result i overwrite the label contents. 
As said in the code comments only uncomment the 'element.attr' if you use 'md-no-float' attribute or static labels. 

Hope this helps!

**Comment by tothtibor9182** [comment]
Use this code below instead of <md-button> directive:
It will work as same as <md-button> directive:

    ```
<button class="md-button md-ink-ripple" type="button" ng-click="controller.doSth()">
       <div class="md-ripple-container" style translate="yes">CONTEXT</div>
</button>
```
