### ISSUE TITLE
useStaticFilesLoader with files-array

### ISSUE THREAD

**Issue by MagdaN** [angular-translate/angular-translate#943]
I try to use the StaticFileLoader with an array of files, as suggested in the docs, but this does not seem to work

```
$translateProvider.useStaticFilesLoader(
    files: [{
        prefix: 'locale-',
        suffix: '.json'
    }, {
        prefix: '/absolute/path/to/locale-',
        suffix: '.json'
    }, {
        prefix: 'another/path/to/locales/',
        suffix: ''
    }]
);
```

The files are not found.

**Comment by tspaeth** [comment]
Which angular-translate version are you using? There have been some fixes recently.

**Comment by MagdaN** [comment]
Yes, that was the problem, updated to the latest version and now it works! Thanks.
