### ISSUE TITLE
Make $stateful configurable

### ISSUE THREAD

**Issue by kentcdodds** [angular-translate/angular-translate#945]
On [this line](https://github.com/angular-translate/angular-translate/blob/master/src/filter/translate.js#L65) you have:

```javascript
translateFilter.$stateful = true;
```

I would love to be able to configure that via the `$translateProvider` because in my app, the language doesn't change on the fly, so my filters will be stateless. Right now I've built my own filter, but I would love to be able to use the built in one :-)

**Comment by kentcdodds** [comment]
Note, I suppose that I could use `{{:: SOME_ID | translate }}` and that would actually be better, but there are some cases where the `interpolateParams` will change, so I'd just like to avoid the `$stateful` filter :-) Thanks!

**Comment by knalli** [comment]
See dbd5be9

**Comment by kentcdodds** [comment]
@knalli, I think I'm confused. Not sure what that commit has to do with my request.

I should say that I decided to write my own filter for various reason, so I no longer really need this feature personally. I'll go ahead and close it. Feel free to implement if you want :-)
