### ISSUE TITLE
Event for translationFile loaded?

### ISSUE THREAD

**Issue by cskiwi** [angular-translate/angular-translate#947]
hi,

I was wondering if there was an event to listen for when the translation file is loaded because now it sets the value of the key instead of the translation file.

but if I set a timeout long enough, that the translation .json is loaded first then it works like it should, but  setting the timeout like that wouldn't work on computers with slow internet.

so something like this:
```javascript
$translation.staticfilesLoaded(function() {
    // set some manual translation places
});
```

Edit:
this is because, for placeholders for inputs you can't use the `{{ 'some.key' | translate }}` nor `translate=""` so I set them manual, unless there is a way to do this dynamically then it's ok :)

**Comment by tspaeth** [comment]
Did you take a look at the docs? Here is a list of the available events:
http://angular-translate.github.io/docs/#/guide/18_events

**Comment by cskiwi** [comment]
Hmm I looked at it, but didn't find any, even searched for 'event' on it, but no result. probably did something wrong. thx!

**Comment by cskiwi** [comment]
Where are these events getting called?

I mean then is it on $translate? or $rootscope?

**Comment by cskiwi** [comment]
Ignore this, I need to read better! :/
