### ISSUE TITLE
Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by johannesjo** [angular-translate/angular-translate#949]
```
TypeError: Cannot read property 'match' of undefined
    at Object.compile (http://localhost:9000/bower_components/angular-translate/angular-translate.js:1997:54)
```

This line:
```
 var translateValueExist = tElement[0].outerHTML.match(/translate-value-+/i);
```

Happens on-load with the translate being used as a directive (as attribute).

**Comment by tspaeth** [comment]
Do you have a Plunkr with an example and more details about the version / used browser(s)?

**Comment by johannesjo** [comment]
Turns out this was related to an incompatibility of v.2.5.1 with ngMessages. It works with v.2.6.1

**Comment by knalli** [comment]
Suggest this is a non standard HTML element.. at least we should avoid the NPE. Just in case..

**Comment by tspaeth** [comment]
outerHTML had some issues on FF10 as far as I remember and/or IE9.

**Comment by johannesjo** [comment]
Testing in chrome. Issue does not seem to be resolved also for 2.6.1.

**Comment by tspaeth** [comment]
So if you can't solve your issue with the mentioned scope problem - still - please provide a Plunker!

**Comment by johannesjo** [comment]
Setting the directive priority fixes the issue:
```
 $translateProvider.directivePriority(222);
```
