### ISSUE TITLE
fallbackLanguage causes inconsistent translate directive behaviour inside ng-if

### ISSUE THREAD

**Issue by pauljoey** [angular-translate/angular-translate#950]
This bug is pretty esoteric. Here's a plunkr:

http://plnkr.co/edit/8LUkdknBtwXGiwCpT6o6?p=preview

If your code calls

    $translateProvider.use('en');
    $translateProvider.fallbackLanguage('en');

And if you have 

    <div ng-if="true">
      <div translate="pass.translated">fail</div>
    </div>

Then the div will display a value of "fail" instead of the translated "pass.translated" string *provided that* pass.translated is a defined translation identifier. Removing `$translateProvider.fallbackLanguage('en');` fixes the problem. 

I believe that this is related to Issue #855.

Tested in:
angular-translate 2.5.2 and 2.6.1
angular 1.2.26, 1.2.28 and 1.3.14

**Comment by tspaeth** [comment]
Mh. Yeah. Indeed something is going wrong again on some ng-if etc. directives. There was a fix in #433 - maybe that doesn't trigger anymore.

**Comment by tspaeth** [comment]
One side issue is, that angular-translate now thinks that you want to translate the keys
"pass.translated" AND "fail" and in the case of the ng-if is doing some order differently.

Asking @knalli : besides what goes wrong in detail: How should we behave in these cases? Do you think it is anyhow valid to have a combination of  these?

```
<div translate="FOO">BAR</div>
```

**Comment by knalli** [comment]
Fixed in 657ed8a

**Comment by knalli** [comment]
http://plnkr.co/edit/yqfAwUSsC1ADsNRx0LSg?p=preview (patch AJS with logging)

**Comment by pauljoey** [comment]
Hey guys. Just wanted to round off this issue with a related clarification. 

Do you consider the following usage/behaviour to be officially supported by angular-translate or more of a out-of-spec behaviour that could change in the future? 

```html 
<div translate="">Default Content</div> 
```

Retains contents and outputs "Default Content"

We have several instances where we allow specification of either a string identifier OR a raw string and use that syntax (`<div translate="{{contentID}}">{{content}}</div>`) which currently does work as we like. We were wondering if you think that we could continue to rely on this behaviour.

@tspaeth @knalli

**Comment by knalli** [comment]
I'm not sure getting this right: http://plnkr.co/edit/YJs6KJw4xcwULS65k059?p=preview Both items 1 & 2 are equal: that's because internally both values of `translate` is an empty string.

**Comment by pauljoey** [comment]
Ah! So the answer is effectively "no" - this is not correct usage. It just appears to behave in the manner that we thought because there is no translation string defined for "Default Content".

Effectively, 

    <div translate="{{contentID}}">{{content}}</div>     

Is the same as:

    <div translate="{{contentID ? contentID : content}}"></div>
