### ISSUE TITLE
Upgrading from 2.4.0 til 2.6.1

### ISSUE THREAD

**Issue by gaui** [angular-translate/angular-translate#951]
I'm using AngularJS 1.3.8. When I upgrade from 2.4.0 to 2.6.1 I get this error:

    Uncaught Error: [$injector:unpr] Unknown provider: $translateCookieStorageProvider <- $translateCookieStorage <- $translateLocalStorage <- $translate

The only files I changed (upgraded) are:
- angular-translate.js
- angular-translate-storage-local.js

And yes, I have both included `pascalprecht.translate` and `ngCookie` module dependencies.

I tried commenting this line out, then it works FINE:

    $translateProvider.useLocalStorage();

 But I want localStorage module. Do you have any idea?

**Comment by knalli** [comment]
Well, actually this should be not a new thing. That's strange.

Anyway: the locale storage plugin requires itself the cookie storage plugin. That means you have to include this also. But that dependency is already present in 2.4.0.

So in your case you need at minimum

1. angular-translate.js
2. angular-translate-storage-local.js
3. angular-translate-storage-cookie.js

**Comment by gaui** [comment]
Yes thank you, `angular-translate-storage-cookie.js` was missing. Thank you.
