### ISSUE TITLE
Example doesn't work in guide/14_pluralization 

### ISSUE THREAD

**Issue by yoav-zibin** [angular-translate/angular-translate#952]
In
http://angular-translate.github.io/docs/#/guide/14_pluralization
the demo doesn't work, probably because these files are missing:
<script src="http://rawgithub.com/SlexAxton/messageformat.js/master/locale/de.js"></script>
    <script src="http://rawgithub.com/SlexAxton/messageformat.js/master/locale/fr.js"></script>

These are the errors I see:
http://rawgit.com/SlexAxton/messageformat.js/master/locale/de.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://rawgit.com/SlexAxton/messageformat.js/master/locale/fr.js Failed to load resource: the server responded with a status of 404 (Not Found)
angular.min.js:63 Error: Unknown provider: $$cookieReaderProvider <- $$cookieReader <- $cookies <- $cookieStore <- $translateCookieStorage <- $translateLocalStorage <- $translate
    at Error (native)
    at https://code.angularjs.org/1.1.5/angular.min.js:29:465
    at Object.c [as get] (https://code.angularjs.org/1.1.5/angular.min.js:27:142)
    at https://code.angularjs.org/1.1.5/angular.min.js:30:21
    at c (https://code.angularjs.org/1.1.5/angular.min.js:27:142)
    at Object.d [as invoke] (https://code.angularjs.org/1.1.5/angular.min.js:27:276)
    at https://code.angularjs.org/1.1.5/angular.min.js:30:39
    at c (https://code.angularjs.org/1.1.5/angular.min.js:27:142)
    at Object.d [as invoke] (https://code.angularjs.org/1.1.5/angular.min.js:27:276)
    at https://code.angularjs.org/1.1.5/angular.min.js:30:39 <div class="well doc-example-live animate-container" ng-embed-app="myApp" ng-set-html="index.html-15" ng-eval-javascript="script.js-14">
angular.min.js:63 Plural function for locale `en` could not be loaded <div class="well doc-example-live animate-container" ng-embed-app="myApp" ng-set-html="index.html-23" ng-eval-javascript="script.js-22">

**Comment by tspaeth** [comment]
Yeah, thanks. As we are including the latest one of the messageformat module, this isn't working anymore. We'll have to patch it with the next release.

**Comment by knalli** [comment]
@tspaeth  Check? If so -> Close.

**Comment by tspaeth** [comment]
In the meanwhile, the url to messageformat.js changed also... I'll provide another package on documentation anyway, also fixing some links to the repos etc. which still contained some old pointers to the old repo :)

**Comment by knalli** [comment]
=> Use always http://rawgit.com/ <http://rawgit.com/> production.

**Comment by knalli** [comment]
Will be fixed in next release.
