### ISSUE TITLE
Static files not going to fallback language

### ISSUE THREAD

**Issue by cskiwi** [angular-translate/angular-translate#953]
I'm using the following configuration:

```javascript
var language = (window.navigator.userLanguage || window.navigator.language).toLowerCase();

$translateProvider.useStaticFilesLoader({
    prefix: config.getValue("app.localization") + '/locale-',
    suffix: '.json'
});

$translateProvider.preferredLanguage(language);
$translateProvider.useCookieStorage();
$translateProvider.fallbackLanguage("en-us");
```

and when I go on my tablet that is set to en-gb it shows on all places en-gb, and not the text from the fallback language.

Any idea why this is not working?

**Comment by tspaeth** [comment]
Do you have translations for both languages?

From what I can read out of the code:
First you set your preferredLanguage to en-gb (as your tablet has en-gb), then the last setting is grabbed from the cookie store and then you define a fallback for the case where translations are missing.
So the texts from

"config.getValue(....)/locale-gb-en.json" will be picked first?!

**Comment by cskiwi** [comment]
I have translations for nl-be and en-us.

Does it matter in witch order the configs are?
in that case I'm trying to load them in the following order:

```
first check cookie storage for setting,
if no cookie, check devices lang
else fallback on en-us
```

**Comment by tspaeth** [comment]
Can you put up a short example plunker please? Otherwise it's hard to figure out the problematic details...

**Comment by cskiwi** [comment]
This here represents the issue:

http://plnkr.co/edit/fewCSr?p=preview

as you can see, the top ones aren't translated, while the bottom ones are correctly translated, but I would love to use the top translation method

**Comment by tspaeth** [comment]
See 

http://plnkr.co/edit/h7qUlY?p=preview

I pimped it a bit to be working. Some notes:

- preferredLanguage takes only valid language keys (in your case 'de_DE')
- you might need a registerAvailableLanguageKeys - section as the var "language" might just contain "de"
So if you now remove a key from one the de_DE file, the english text is shown here.

**Comment by mgurluk** [comment]
hello,
 <h1 translate>HEADLINE</h1>,    ok ve çalıyor ancak,
HEADLINE or {{HEADLINE}} or {{translate.HEADLINE}} Is it necessary to use the h1 tag that is not working outside?

**Comment by tspaeth** [comment]
@mgurluk Sorry, I don't understand your question. Could you detail it a bit, please? Thanks.

**Comment by knalli** [comment]
Any updates here?

**Comment by knalli** [comment]
Closed due inactivity. (Also looks like being resolved anyway.)
