### ISSUE TITLE
Using HTML data- attributes causes unexpected behavior with translate-attr-ATTR

### ISSUE THREAD

**Issue by brandonhesse** [angular-translate/angular-translate#954]
Here's a [plunkr](http://plnkr.co/edit/1ENkU58ZXMBfObT8ORlL?p=preview)

There's an odd issue, with attaching data- attributes and other prefixes cause the attribute generated by translate-attr-ATTR cause the attribute to have a little extra prefix.

I choose to use valid HTML5 standards in my code and it's quite difficult with an issue like this. For now, leaving data- off the front is a workaround, but it would be nice if I didn't have to leave non-valid HTML code in my webpage.

EDIT: Found the offending line in code.
https://github.com/angular-translate/angular-translate/blob/master/src/directive/translate.js#L260

**Comment by brandonhesse** [comment]
Is there any comments from developers on fixing this?

**Comment by knalli** [comment]
@brandonhesse, we will likely fix this in future (this is a bug). However, if you want to speed up the fix, please make a PR.

**Comment by knalli** [comment]
Thank you for reporting. Fixed in ee253bc.
