### ISSUE TITLE
useLocalStorage() doesn't work

### ISSUE THREAD

**Issue by wildwest-service** [angular-translate/angular-translate#955]
Nice to meet you, Mr.knalli.
I found an error.

(Please forgive me my lousy English...)

`useLocalStorage()` doesn't working in angular-translate's guide.
http://angular-translate.github.io/docs/#/guide/10_storages

![doc_storages](https://cloud.githubusercontent.com/assets/2679928/6613467/c031f1ba-c8d0-11e4-883e-42992583c007.png)

Maybe this is caused by angular-cookies.js.

I try used "angular-cookies.js v1.4.0-build.3869+sha.3b8163b", useLocalStorage() worked normally.
But used "v1.4.0-build.3870", it stopped with an error.

Thank you for being patient with my English.

**Comment by tspaeth** [comment]
Thanks for the report. You're right. We have to fix some of the examples as some dependencies have changed.

**Comment by knalli** [comment]
We have currently no support for 1.4 (actually: untested), but we will likely add support in the next weeks. At least all tests should work then.

Besides this, several issues are breaking the docs. Invalid nonstatic includes from rawgit, old AJS, and so on.

We are on it. Thank you!

**Comment by wildwest-service** [comment]
Mr.tspaeth and Mr.knalli

Thank you for fix :)

I'm impressed at quick responses!

**Comment by knalli** [comment]
Fixed in next release.
