### ISSUE TITLE
$translate.refresh on same key in file is acting weird.

### ISSUE THREAD

**Issue by wahidnory** [angular-translate/angular-translate#956]
Hi, 

I've started using the angular-translate package for a new website that I'm trying to make and I've come across some weird functionality (bug?). 

I'm using the partial loader to load different files and I've got it setup like this:

// Set the preferred language
`$translateProvider.useLoaderCache(true);`
`$translateProvider.useCookieStorage();`
`$translateProvider.preferredLanguage('nl_NL');`

`$translateProvider.useLoader('$translatePartialLoader',`
`{
  urlTemplate: '/translations/{lang}/{part}.json'
});`

After this I'm calling the refresh method on each controller for now to make the file load up.
Like so : 
`var part = 'home';` // or another page name
`$translatePartialLoader.addPart(part);`
`$translate.refresh();`

The translation files are build up like this:
home.json: 
{
	"PAGETITLE": "HomeTitle"
}

about.json
{
	"PAGETITLE": "AboutTitle"
}

How I translate inside the view:
`<h1> {{ 'PAGETITLE' | translate }} </h1>` or `<h1 translate="PAGETITLE"></h1>` (both have the same behaviour.

And this comes down to this problem:
So for example you start at About go to Home and back to About again. You'll have the home translation displayed on the About page title.

The solution to the problem is to to explicitly tell json that it's a different page like this: 
(with the translation `<h1> {{ 'about.PAGETITLE' | translate }} </h1>`)
{
	"about": {
		"PAGETITLE": "Inventaris"
	}
}

I think it doesn't overwrite the last key it found on the translation table and just keeps it. 

I've tried to find the issue in the code to try to fix it. But I'm new to the whole angular idea and found it quite difficult to make the proper adjustments. 

Thanks for the  read

**Comment by tspaeth** [comment]
Hi! 

As far as I know the implementation on partial loaders, I guess it is not meant to be a "cascade" for overloading the SAME translation keys and have a replacement to the "last loaded key". No - it concatenates the partial-files. Maybe this leads to duplicate keys even though. 
So your approach will not work as you expect.

But I guess @DWand might have some more hints / clearer view of what is possible and what not.

**Comment by knalli** [comment]
Partial loading is meant for name spaced translations. Overriding is not supported and we will not planning this.

One unique key in the application-wide scope.

The main deal is you are providing one central configuration and $translate is doing all the stuff for you. Except you are using _partial loading_ which allows to add (or remove) parts at a later point. But the main vision stays to use unique keys.

```html
<h1> {{ 'about.PAGETITLE' | translate }} </h1>
```

.. is the right one. :)

**Comment by wahidnory** [comment]
Thanks for the reply and the time to review this :)

**Comment by cilginbok** [comment]
Overriding would be very usefull when defining multilanguaged description or keywords with json files.
Does somebody have trick for this?
