### ISSUE TITLE
Namespace conflict / template views

### ISSUE THREAD

**Issue by cub** [angular-translate/angular-translate#957]
Hi,

In my app (local offline cordova based), there is multiple views - same structure, different text - like this : 
```html
<!-- [html] view template @ cards/card.view.html -->
<div class="card">
	<h1>{{ CARD.TITLE | translate }}</h1>
</div>
```
```javascript
// [json] i18n @ cards/card_0/en.json
{ "CARD_TITLE": "CARD #0" }
```
```javascript
// [json] i18n @ cards/card_1/en.json
{ "CARD_TITLE": "CARD #1" }
```
```javascript
// [js] controller, assuming routing /card/:idCard @ cards/card.controller.js
var translateParts = $translatePartialLoader.getRegisteredParts();
angular.forEach(translateParts, function (part) {
	$translatePartialLoader.deletePart(part);
});
$translatePartialLoader.addPart('cards/card_'+$routeParams.idCard);
```
To avoid conflict namespace of i18n, I use partial load and I force to unload previous json. I have read that we can't use array to filter by ID. Correct ? Or is there a better design in my case ?

**Comment by geemang2000** [comment]
I'm curious of this too. I have a JSON object namespace: appTypes with a list of Key / value pairs in it. 
In my page I have:
``` <td>{{item.settings.type | translate }}</td> ```

I want to translate against the appTypes namespace. Is there a way to do this ?

**Comment by knalli** [comment]
You always have to instrument a string for a filter in AJS... and that is not an angular-translate specific issue.

In your case you trying to translate the value of item.settings.type. But if you want to translate this as a key, you have to use a string.

**Comment by knalli** [comment]
Closing due inactivity.
