### ISSUE TITLE
Translation depth is limited

### ISSUE THREAD

**Issue by dietergeerts** [angular-translate/angular-translate#958]
When we add are translations, we need to have many 'namespaces' as of our different modules etc. This results in a high depth of translations. Translations that are at level 6 and further will not get translated. I assume that the codes checks until 5 dots and no further? This should be resolved as I think it can be done unlimited.

An example: APPOINTMENTS.FORM.NEW_APPOINTMENT.WORK_ACCIDENT.DATE.LABEL

**Comment by knalli** [comment]
No, we have no such limit: https://github.com/angular-translate/angular-translate/blob/a2ac7000f94bcee6dd8e206cab5d7cec3527dd25/src/service/translate.js#L237-L265

**Comment by tspaeth** [comment]
@dietergeerts what you could test if there is a length limit somewhere else if you do some key like a.b.c.d.e.f.g.h.i.j - does that work or even not?

**Comment by dietergeerts** [comment]
OMG! I'm sorry. I discovered why it didn't work! The translations json object was very big that I didn't noticed there was a duplicate key further in the file...
