### ISSUE TITLE
Testimonial as Requested

### ISSUE THREAD

**Issue by gylippus** [angular-translate/angular-translate#959]
@PascalPrecht as requested via email. Wanted to share the success we have had with this module. 

Once we received the translated text from our linguists, it took us 1 day to go from 1 language to 13 languages. 

Our app [Sworkit](http://sworkit.com) is available in iOS and Android using the Ionic Framework and Cordova. It was very easy to:
- Identity the user's normal language
- Set and store this as the default
- Update our HTML templates 
- Make use of $translate.instant within our controllers

We have seen dramatic increases in our international store rankings, international press, review ratings, international downloads, and feedback from users. 

We have even received suggestions from our users for linguistic changes they would recommend and we can instantly update our language file to have this ready to go for the next update. Each language has 632 ID phrases in use at the moment.

If you want to try it out, download the free version of our app and you can change the language in Settings from the Side Menu. 

If you or anyone in the community has any questions, please don't hesitate to ask. We couldn't have expanded into 12 new languages this easy without angular-translate. 

## Thank you for all of your hard work!

![Sworkit](http://s3.kkloud.com.s3.amazonaws.com/gett/8guoN382/sworkit_logo.png.client.x675.png)

**Comment by BrutalBrutus** [comment]
How did you find reliable linguists?

**Comment by gylippus** [comment]
@BrutalBrutus  For our initial huge set of translations we went with [Andovar](http://www.andovar.com/) They were really great to work with and provided a project manager, local linguists who had worked with apps, and we also needed a lot of studio quality audio produced as well. 

For updates with just a few phrases and even just our What's New sections, we have been using [Unbabel](http://unbabel.com/) who according to our users have been doing a great job. They only charge $0.03 per word and one of the coolest things is that they let you choose the tone of the translation, ie. formal, informal, friendly... and provide other notes to the linguists as well.

**Comment by knalli** [comment]
@gylippus I think Pascal had already done this, but from me also: Thank you! :dancers:

**Comment by tspaeth** [comment]
Thanks also from me and I guess there is nothing more to... erm... say here :smiley: 
closing therefore...
