### ISSUE TITLE
Preferred language doesn't work with useStaticFilesLoader?

### ISSUE THREAD

**Issue by 9mm** [angular-translate/angular-translate#961]
Hi,

Here is my current code, fairly straightforward:

```javascript
$translateProvider.useStaticFilesLoader({   
  prefix: '/static/languages/',             
  suffix: '.json'                           
});                                         
$translateProvider.preferredLanguage('en'); 
$translateProvider.useLocalStorage();
```

I also have `en.json` and `de.json`.

Inside `en.json` I have...

```json
{
  "HEADLINE"   : "Headline english",
  "INTRO_TEXT" : "Intro english"
}
```

However, when I load the app with a demo html snippet: `<p translate>HEADLINE</p>`, it doesn't translate. I've also tried several other methods like `<p translate="HEADLINE"></p>`, etc.

Does it not load the default json file of the preferred language? I noticed in your demo you make a redundant declaration... you define it inside `.config()` and also in the .json file. It seems to me you would only put it in the .json file and that's it.

http://jsfiddle.net/02o5ezz3/

**Comment by DWand** [comment]
Hello, @9mm. I don't understand what have you wanted to tell in the fiddle. But, however, any loader works fine with the `preferredLanguage` functionality. Are there any xhr calls shown in the browser's network tab?

**Comment by 9mm** [comment]
Hey, I guess the fiddle didn't work.

Yes, I see XHR for the *.json files.

What I'm trying to say is if you delete this part it stops working:

```
$translateProvider.translations('en', {
    "HEADLINE": "What an awesome module!",
    "PARAGRAPH": "Srsly!",
    "PASSED_AS_TEXT": "Hey there! I'm passed as text value!",
    "PASSED_AS_ATTRIBUTE": "I'm passed as attribute value, cool ha?",
    "PASSED_AS_INTERPOLATION": "Beginners! I'm interpolated!",
    "VARIABLE_REPLACEMENT": "Hi {{name}}",
    "BUTTON_LANG_DE": "german",
    "BUTTON_LANG_EN": "english"
  });
```

But that portion is already in the *.json file, so why do I have to include it again? 

Thanks!

**Comment by DWand** [comment]
This part of code is completely unnecessary if you use a loader.

The only reason why you may want to use `$translateProvider.translations` method together with the loader is to decrease the initial time which is taken by the module to show translations on the page. angular-translate loads files from the server only if they are not present yet. So if you guess that the user will use the `en` language, then you may provide it directly to the module. In this case if the user really uses the `en` language, then the module will not need to load translations.

If the code does not work without the section mentioned above then there is a bug somewhere. Either in angular-translate or in your code. I'll take a look at this thing in a couple of hours.

**Comment by 9mm** [comment]
Ok awesome. That's what I figured. Here's my complete code though copied and pasted, I'm pretty sure it's not a bug on my end, although maybe you can see something below.

**bower.json**

```json
    "angular-translate": "^2.6.1",
    "angular-translate-loader-static-files": "^2.6.1",
    "angular-translate-storage-local": "^2.6.1"
```

**config() block of app.js**

```
  // angular-translate

  $translateProvider.useStaticFilesLoader({
    prefix: '/static/languages/',
    suffix: '.json'
  });
  $translateProvider.preferredLanguage('en');
  $translateProvider.useLocalStorage();
```

**en.json**

```json
{
  "HEADLINE"   : "Headline english",
  "INTRO_TEXT" : "Intro english"
}
```

**test.html**

```html
<p translate>HEADLINE</p>
<p translate>INTRO_TEXT</p>
```

I can see the request to `en.json` returns successfully, and has the proper content type of `application/json`.

**Comment by DWand** [comment]
It looks like angular-translate works as expected: http://plnkr.co/VDgqwM1AWIldH9bta6ni

**Comment by 9mm** [comment]
That Plnkr you sent doesn't work?

**Comment by DWand** [comment]
@9mm, it works fine in Firefox 36.0.1

**Comment by DWand** [comment]
Okay, the problem is that raw.githubusercontent.com returns js files as text/plain. If you host this example with correct mime types, then it will work fine. I've just tested it in Firefox 36.0.1, Chrome 41.0.2272.89 m and IE 11.

**Comment by DWand** [comment]
I've fixed links to js files. Now this plunker works in all mentioned browsers well out of the box: http://plnkr.co/VDgqwM1AWIldH9bta6ni

**Comment by 9mm** [comment]
Do you have any ideas how I can debug this? I've checked every conceivable thing I can think of... my code is identical to yours. The translations just don't show. I can see the JSON files are dynamically being fetched, but the translation text doesnt change and just remains as the translation key. Is there a debug option or something?

**Comment by knalli** [comment]
> Okay, the problem is that raw.githubusercontent.com returns js files as text/plain. If you host this example with correct mime types, then it will work fine. I've just tested it in Firefox 36.0.1, Chrome 41.0.2272.89 m and IE 11.

You should not use this one, but http://rawgit.com/ which additionally teaches exactly what to do.

**Comment by 9mm** [comment]
Hey, I'm actually referring to the code of my original issue not the pastebin service. Locally I have the JSON files being served with the proper content type of `application/json`.

**Comment by knalli** [comment]
@9mm Well, it sounds like it is not identical ;)

I'm a bit confused. Do we have a running demo of your issue?

> Hey, I'm actually referring to the code of my original issue not the pastebin service. Locally I have the JSON files being served with the proper content type of application/json.

Well, actually this does not matter. (Should not.)

>  Is there a debug option or something?

This is JavaScript :) Said this, you still can inject yourself into the translate process and verify the steps..

**Comment by DWand** [comment]
@9mm

0.1) Ensure that the example works fine in your target browsers.
0.2) Ensure that the example works fine in your environment

1) Check that you have included all needed javascript files to your HTML
2) I'm not sure whether it is important, but check that all javascript files are added in correct order
3) Check that you have included all dependencies to your module
4) Check the configuration of the module (`$translateProvider.translations` is unnecessary if you use a loader)
5) Run the application
6) Check that all javascript files are successfully loaded
7) Check that the correct json file is successfully loaded
8) Check errors in the console

If there are no error, but the module still doesn't work, then there are at least two possible situations:
* there are some conflicts with other modules you are using
* there are some conflicts with different versions of angular and other dependencies

Also, you can easily debug javascript files with Firebug extension for Firefox, for example.

If nothing help you to solve the issue, then create a good demo which represents it. I recommend you to use http://plnkr.co/ instead of http://jsfiddle.net, because it provides an ability to create multiple files and emulate a directory structure.

**Comment by 9mm** [comment]
So I'm not sure what this means, but this is what I've narrowed down...

It appears to originate in `angular-translate-loader-static-files`.

```
    $q.all(promises).then(function (data) {
      var length = data.length,
          mergedData = {};

      for (var i = 0; i < length; i++) {
        for (var key in data[i]) {
          mergedData[key] = data[i][key];
        }
      }

      deferred.resolve(mergedData);
    }, function (data) {
      deferred.reject(data);
    });
```

In my case, `data` is a single object: `{0: {translations: 'show up here} }`.

If I make it say `data[0]` it works fine. I guess I'll just kind of try to dig in further, although I dont really know how another module could be interfering.

**Comment by 9mm** [comment]
I do have `angular-bluebird-promises` in my bower.json, however I thought if your library is injecting `$q` directly than it would use the correct `$q` and not the slightly modified one.

**Comment by 9mm** [comment]
I don't know what its from, but I wrote my own loader and just bypassed the issue.. Thanks!

**Comment by jgodi** [comment]
@9mm Could you share the custom loader by chance?

**Comment by 9mm** [comment]
@jgodi I bet you wrote that comment praying that I were still alive, but not hopeful for a reply. Today is you're lucky day, let me go dig it up.

**Comment by 9mm** [comment]
It's hard to tell what I changed on this code from the default loader I took it from (because they were in the same commit), but here it is in full:

**app.js**

    $translateProvider.useLoader('customTranslateLoader', {
        prefix: '/static/languages/',
        suffix: '.json'
      });
    $translateProvider.useLocalStorage();
    $translateProvider.preferredLanguage('en');

**client/app/translate/custom_loader.factory.js**

    // This custom factory for angular-translate solves the dilemma where
    // $q.all() returns an object instead of an array. We are modeling 
    // the 'angular-translate-loader-static-files' loader

    app.factory('customTranslateLoader', function ($http, $q) {

      return function (options) {

        if (!options || (!angular.isArray(options.files) && (!angular.isString(options.prefix) || !angular.isString(options.suffix)))) {
          throw new Error('Couldn\'t load static files, no files and prefix or suffix specified!');
        }
        
        if (!options.files) {
          options.files = [{
            prefix: options.prefix,
            suffix: options.suffix
          }];
        }

        var load = function (file) {
          if (!file || (!angular.isString(file.prefix) || !angular.isString(file.suffix))) {
            throw new Error('Couldn\'t load static file, no prefix or suffix specified!');
          }

          var deferred = $q.defer();

          $http(angular.extend({
            url: [
              file.prefix,
              options.key,
              file.suffix
            ].join(''),
            method: 'GET',
            params: ''
          }, options.$http)).success(function (data) {
            deferred.resolve(data);
          }).error(function (data) {
            deferred.reject(options.key);
          });

          return deferred.promise;
        };

        var deferred = $q.defer(),
            promises = [],
            length = options.files.length;

        for (var i = 0; i < length; i++) {
          promises.push(load({
            prefix: options.files[i].prefix,
            key: options.key,
            suffix: options.files[i].suffix
          }));
        }

        $q.all(promises).then(function (data) {
          data = [data[0]];
          var length = data.length,
              mergedData = {};

          for (var i = 0; i < length; i++) {
            for (var key in data[i]) {
              mergedData[key] = data[i][key];
            }
          }

          deferred.resolve(mergedData);
        }, function (data) {
          deferred.reject(data);
        });

        return deferred.promise;
      };
      
    });
