### ISSUE TITLE
Async / sync $translate

### ISSUE THREAD

**Issue by zoltanradics** [angular-translate/angular-translate#962]
Is there any possible way to use $translate in a $sync way? Async solution of $translate is quite good if i have to load translations from an external source but i have some special cases when i manage the translations and i want to use a "sync" version of $translate?

**Comment by DWand** [comment]
Yes, it is possible. You have to use the `instant` method. You can find a more detailed explanation here: http://angular-translate.github.io/docs/#/api/pascalprecht.translate.$translate

**Comment by zoltanradics** [comment]
Thakns. It works! That was i am looking for exactly.
