### ISSUE TITLE
Translation removing center align in Ionic header

### ISSUE THREAD

**Issue by jamesdef** [angular-translate/angular-translate#964]
In my Ionic app, I'm experiencing the following weird problem:

My header looks like this:
 ```
<ion-header-bar align-title="center" class="bar-positive">

  <h1 class="title"><i class='ion-home'></i> Home </h1>
  <div class="buttons">
    <a ui-sref="settings" nav-direction="forward" class="button button-clear"><i class="ion-gear-b"></i>{{ "settings" | translate  }}</a>
  </div>
</ion-header-bar>
```

which for some reason, makes the h1 title align to the right, and not being displayed entirely.
However, when changing to
 ```
    <a ui-sref="settings" nav-direction="forward" class="button button-clear"><i class="ion-gear-b"></i> Settings </a>

 ```

which is the very same output, since the translation for settings is "Settings", everything works fine.
What could be wrong here?

**Comment by knalli** [comment]
@jamesdef We do not support Ionic here. ;)

I would guess on the given code that the inner text of the elements flips with the inner html elements: flap between `<i>…</i> Text` and `Text <i>…</i>`. The rescue could be a helper `<span>`.
