### ISSUE TITLE
Custom sanitization strategy

### ISSUE THREAD

**Issue by hippich** [angular-translate/angular-translate#965]
I am aware of useSanitizeValueStrategy('escaped'), but in my case it is not appropriate. (one of problems it causes - it converts every param to string, which is not what expected)

Questions - is it possible and, if it is not, is it planned to add ability to define my own sanitize strategies?

**Comment by knalli** [comment]
The strategies are currently implicit part of `$translateDefaultInterpolation` and cannot be overridden. But you can define your own interpolator: http://angular-translate.github.io/docs/#/guide/15_custom-interpolators
