### ISSUE TITLE
Compatible version of messageformat and angular-translate-interpolation-message-format?

### ISSUE THREAD

**Issue by sharanmunyal** [angular-translate/angular-translate#966]
Hi,
     I am using angular-translate-interpolation-interpolation-message-format version 2.5.2 and messageformat.js version 0.1.7. As mentioned in the doc for angular-translate, I am downloading messageformat.js from here https://github.com/SlexAxton/messageformat.js. Also present on the page is the angular-translate-interpolation-message-format. I am also including the locale file for 'es' from here https://github.com/angular/angular.js/tree/master/src/ngLocale.

The following is the config I have for my application.

    .config(['$translateProvider', 'SourceConstant',
        function ($translateProvider, SourceConstant) {
            var langFilePath = {
                en: SourceConstant.FILES + 'lang/strings_en.json',
                es: SourceConstant.FILES + 'lang/strings_es.json'
            };
            $translateProvider
                .useStaticFilesLoader({
                    prefix: 'lang/strings_',
                    suffix: '.json'
                })
                .preferredLanguage('es')
                .addInterpolation('$translateMessageFormatInterpolation');
    }])

I am seeing an error: Uncaught Error: Plural Function not found for locale: es on the page.

Can someone point to my mistake? Are the two versions I mentioned above compatible?

**Comment by tspaeth** [comment]
Please have a look at #948
