### ISSUE TITLE
Guide code example mistake - #asynchronous-loading_using-a-cache

### ISSUE THREAD

**Issue by wallter** [angular-translate/angular-translate#968]
[`/guide/12_asynchronous-loading#asynchronous-loading_using-a-cache`](http://angular-translate.github.io/docs/#/guide/12_asynchronous-loading#asynchronous-loading_using-a-cache)

Uses `$translationProvider` instead of `$translateProvider`.

**Comment by knalli** [comment]
Thank you for reporting.
