### ISSUE TITLE
When staticFilesLoader loaded language returns 404, the translate directive shows locale key?

### ISSUE THREAD

**Issue by filidorwiese** [angular-translate/angular-translate#972]
Maybe I'm doing something wrong. When you define a fallback language I expected it to be used not only if a translation string can't be found, but also if the entire preferred language file can't be loaded (404). Instead it seems that the locale itself is returned for every translation on the page that's using the translate directive. Note that filters work as expected.

I've demonstrated the issue here: http://plnkr.co/edit/E21fXRHnYbUDOjm5wsma

Is this a bug?

**Comment by knalli** [comment]
Thank you for reporting. Yes, that is a bug.

**Comment by tspaeth** [comment]
Remark for development:
Happens only when defining preferredLanguage first and then the fallbacks.
Other way around: works fine...

**Comment by knalli** [comment]
@filidorwiese Please follow #920 and confirm that this is exactly your issue. I've attached in this issue a patched plunkr. Thank you!

**Comment by filidorwiese** [comment]
Thank you, it seems your patch did fix my issue.
