### ISSUE TITLE
$translateChangeSuccess event $emit instead of $broadcast?

### ISSUE THREAD

**Issue by vanthiyathevan** [angular-translate/angular-translate#973]
I've been trying to use the `$translateChangeSuccess` in a scope. but it is not getting invoked. Looking at the code [950 - translate.js](https://github.com/angular-translate/angular-translate/blob/master/src/service/translate.js#L950)
It is emitting instead of broadcasting the event. Is that right?

**Comment by DWand** [comment]
Hello, @vanthiyathevan. Yes, such behavior is expected. You can find more information about events here: http://angular-translate.github.io/docs/#/guide/18_events

**Comment by vanthiyathevan** [comment]
@DWand Thanks for the info.
