### ISSUE TITLE
Error: [$injector:unpr] Unknown provider: $translateStaticFilesLoaderProvider issue

### ISSUE THREAD

**Issue by ptrussart** [angular-translate/angular-translate#976]
Hello,

I'm trying to use the `$translateStaticFilesLoaderProvider` but I can't. I have an issue at my application loading (maybe linked to asynchronous loading ?)
 ```
Error: [$injector:unpr] Unknown provider: $translateStaticFilesLoaderProvider <- $translateStaticFilesLoader
http://errors.angularjs.org/1.3.15/$injector/unpr?p0=%24translateStaticFilesLoaderProvider%20%3C-%20%24translateStaticFilesLoader
    at REGEX_STRING_REGEXP (angular.js:63)
    at angular.js:4015
    at Object.getService [as get] (angular.js:4162)
    at angular.js:4020
    at Object.getService [as get] (angular.js:4162)
    at $get.loadAsync (angular-translate.js:1040)
    at Function.$get.$translate.use (angular-translate.js:1572)
    at angular-translate.js:38
    at Object.invoke (angular.js:4203)
    at angular.js:4025
```

I have installed the `$translateStaticFilesLoaderProvider` using `bower install angular-translate-loader-url` to install and I have the js files added in my project.
I have imported them in my index.html
```
...
<script src="bower_components/angular-translate/angular-translate.js"></script>
<script src="bower_components/angular-translate-loader-url/angular-translate-loader-url.js"></script>
...
```

I'm currently using AngularJS 1.3.15. Could it be the cause of the issue ?

Do you have any other ideas of what could cause this issue ?

**Comment by tspaeth** [comment]
Did you include the angular-translate-loader-static-files file also?

**Comment by ptrussart** [comment]
Ok that was the issue actually :)

I did not read the documentation well enough. 

Thanks a lot for this very quick answer.

**Comment by satmaramani** [comment]
@tspaeth Thanks Man
