### ISSUE TITLE
Translate-cloak incorrectly decloaks elements when using a fallback language option. 

### ISSUE THREAD

**Issue by Discmt** [angular-translate/angular-translate#978]
Setup partial loading, a fallback language, and try to use translate-cloak, and you should be able to see with ease that since the $translate service follows a different resolution path when a fallback language is an option, the cloak is often removed prematurely from the element, causing FOUC to appear.

**Comment by eekboom** [comment]
Why did you close this? I still have this problem even in 2.8.1.
As soon as I remove the call to "fallbackLanguage()" it works correctly.

**Comment by tspaeth** [comment]
Please open a new defect together with a plnkr demonstrating your setup. thanks.

**Comment by igler** [comment]
Having the same problem.
