### ISSUE TITLE
bundle translations into custom directives library

### ISSUE THREAD

**Issue by djindjic** [angular-translate/angular-translate#979]
sorry if this is duplicate. but I cant find it in docs and issues. Is it possible to make my directives lib translated without configuring client app about languages? It would be perfect if I could compile 3 different libs for 3 different languages and don't force clients to setup their applications to be multilanguage. For example, just include Italian build and use it in Italian's apps.

**Comment by dietergeerts** [comment]
Yes, we do this. With our gulp build, we set which language to choose and just inject the language json object into our javascript code. Once the app does it's config, we let that object being used by angular-translate.

**Comment by djindjic** [comment]
does your client app have angular-translate included and configured or you do this in directives lib?

**Comment by dietergeerts** [comment]
It has angular-translate included and configured.

**Comment by knalli** [comment]
Ehm.. did I got this right: You are looking for a tooling only translating a directive w/o _angular-translate_ in the result artifact? If yes: No, we only have  [grunt-angular-translate](https://github.com/angular-translate/grunt-angular-translate) which would not fit your need. If no: Please specify.

**Comment by djindjic** [comment]
Yes, something like that. I will try to change my app architecture.
Thanks!
