### ISSUE TITLE
Fallback to predefined language language results in 404 with async load

### ISSUE THREAD

**Issue by willi1s** [angular-translate/angular-translate#981]
Hi,

I have an app with one language built in:
`
$translateProvider.translations('en_GB', {
                        'LANGUAGE':                                       'Language'
});
`

And I want to load other languages asynchronously:
`                        $translateProvider.useStaticFilesLoader({
                                                  prefix: 'lang/',
                                                  suffix: '.json'
                                              });`

with any missing strings falling back to my built in language:
` $translateProvider.fallbackLanguage('en_GB')`

However, I get a 404 because when the translate service starts it attempts to asynchronously load the fallback language event though it is already loaded.

I do not want to specify the language internally and externally to my app. Can a fix be added to prevent loading the language if it already exists?

**Comment by knalli** [comment]
@willi1s  Do you mean having defined a _preferred language_ other than `en_GB` and a _fallback language_ as `en_GB` (which is prefilled already) results into a refetch? This constellation would look like a bug and not intended.

Otherwise please make a small test case, so we can avoid possible other issues.

**Comment by willi1s** [comment]
@knalli In fact even with the current _preferred language_ set to `en_GB` as request to refetch is still made.

I have created a [plnkr](http://plnkr.co/edit/CmrLoqQwHdP5LyXuF0n0) of the issue

I followed the call stack back into angular-translate and the code in question is below.
Note that if a fallback language is specified and we have a loaderFactory then *always* go and load the fallback language, maybe a simple check here to see if this language is pre-loaded?

```
      if ($loaderFactory) {

        // If at least one async loader is defined and there are no
        // (default) translations available we should try to load them.
        if (angular.equals($translationTable, {})) {
          $translate.use($translate.use());
        }

        // Also, if there are any fallback language registered, we start
        // loading them asynchronously as soon as we can.
        if ($fallbackLanguage && $fallbackLanguage.length) {
          var processAsyncResult = function (translation) {
            translations(translation.key, translation.table);
            $rootScope.$emit('$translateChangeEnd', { language: translation.key });
            return translation;
          };
          for (var i = 0, len = $fallbackLanguage.length; i < len; i++) {
            langPromises[$fallbackLanguage[i]] = loadAsync($fallbackLanguage[i]).then(processAsyncResult);
          }
        }
      }

      return $translate;
    }
```

I have worked around the issue for now by creating an empty en_GB.json file, but perhaps a fix to angular-translate would be better.

**Comment by tspaeth** [comment]
sounds so familiar... #535 / #900 look like they belong to the same "family" of errors.

**Comment by knalli** [comment]
Patched version: http://plnkr.co/edit/qm09k1eP4cdIq5TK71ch?p=preview

**Comment by knalli** [comment]
Issue fixed.. fallback languages have been loaded regardless their predefinition. Not so good.
