### ISSUE TITLE
messageformat.js 0.1.* strict mode volations

### ISSUE THREAD

**Issue by donataswix** [angular-translate/angular-translate#984]
Can we bump angular-translate-interpolation-messageformat's messageformat.js dependency to minor version 2 (~0.2.0)? Version ~0.1.0 cannot be used in *strict mode* as it's assigning to inexistent globals. 

P.S. I've tested it locally and it seems to work. It's unclear to me how to submit a pull request for version bump like this so it would get tested on travis.

**Comment by knalli** [comment]
@donataswix 

1. Fork.
2. Choose `canary` and branch, i.e. `update-messageformat-dep`
3. Update library in `bower.json` and commit this
4. Push this to your fork.
5. Create the PR via GitHub.

More details about this in our CONTRIBUTING.MD.

**Comment by donataswix** [comment]
@knalli I read that, but it's confusing because I don't understand how `bower.json` in https://github.com/angular-translate/bower-angular-translate-interpolation-messageformat gets generated? There is no `messageformat` dependency recorded in `bower.json` of angular-translate repo.

**Comment by knalli** [comment]
Ah, I get your point.

You should not touch the shadow repo, but only this here. However, the dependency angular-translate -> bower-angular-translate-messageformat is not ideal and should be corrected.

**Comment by donataswix** [comment]
Pardon my lack of knowledge, but as I understand there's nothing I can do to help right now?

**Comment by knalli** [comment]
Closing this.

@donataswix  You can easily use your own version of messageformat. If you think about the conflict bower will message you.. well, that is correct. It only complains the suggested version by our plugin and (probably) your version does not match. In this case, use the appropriate resolutions: http://stackoverflow.com/questions/16991128/how-to-resolve-bower-dependency-version-conflicts
