### ISSUE TITLE
translate attribute doesn' t work within a select dropdown, not sure why

### ISSUE THREAD

**Issue by armyofda12mnkeys** [angular-translate/angular-translate#989]
Hello,
Here is a jsfiddle showing angular-translate not working for some reason inside of a default option i use for a angular select dropdown. the first value should say '--Please Choose--' for english, or '--default:Please Choose--'  for french, but none show up at all.
(you can change the preferredLanguage to 'fr' to see my 2nd example)
http://jsfiddle.net/mje5yw9s/7/

Any ideas why?

**Comment by knalli** [comment]
At least there are only <option> elements within <select> element permitted, and within <option> elements only text content (no HTML).

1: https://developer.mozilla.org/de/docs/Web/HTML/Element/select <https://developer.mozilla.org/de/docs/Web/HTML/Element/select> (+optgroup)
2: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option <https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option>

Perhaps the browser treats / parses the tags not as you expected.

**Comment by armyofda12mnkeys** [comment]
Hey knali,

hah, doh I forgot about the tag itself being inside the <option> tag... 
I fixed and its working now:
http://jsfiddle.net/mje5yw9s/8/
Btw is there a way to supply a default translation text without a tag as thats what got me stuck trying to get the translation inside the option in the 1st place?

Basically is there an the equivalent of this:
<option value="" translate="PLEASECHOOSE" translate-default="--Please Choose--"></option>
into something like this (i couldn't find an example of how to do default text this way):
<option value="">{{'PLEASECHOOSE' | translate | translate-default('--Please Choose--') }}</option>

I only saw examples of {{'PLEASECHOOSE' | translate}} without default text.

Anyway, you can close this ticket after answering above.
Thanks for your help!,
Ari

**Comment by dietergeerts** [comment]
Why would you use defaults? Just provide translations in all languages, far better and easier to do.

**Comment by armyofda12mnkeys** [comment]
It would be dependent on the business entering the translations they want via an app which gets them into the database (which unfortunately they may slightly lag behind), and then those get served by our web service to many ajax-clients that pull those application-wide translations and questions for ~50 question questionnaires depending on the language they request. They aren't served via an easy JSON file we could update once since we'd have to update that and send that to potentionally many clients each time it gets updated (some clients even could use our web service and we wouldn't know about them).

But we as the programmers know the English text at least that is behind the programming change so just like we used to do in Spring we try to do the same in Angular.
In spring it was a similar tag which you could put in the text attribute: 
<spring:message code="height.inches.shortform" text="in."/>

**Comment by knalli** [comment]
No. Defaults are only possible in combination with directives. A filter is only a function returning a response (translation) for a given request (translationId). Even the parameters must be provided explicitly since AJS 1.3.

I fully understand your point. I would suggest a custom loader which merges both real and default translation into one combination.
