### ISSUE TITLE
Using Multiple Loaders

### ISSUE THREAD

**Issue by endamaco** [angular-translate/angular-translate#992]
It might be a useful feature to have the possibility to combine different loader.

For example I would like to use both the partial-loader in conjunction to a url-loader

**Comment by DWand** [comment]
Hello, @endamaco. `angular-translate` provides loaders for common use cases. But, obviously, it is impossible to cover all possible variations.

To solve your task you can create a custom loader. It may contain any additional logic you need. Don't be afraid, it is quite easy - you just have to implement one function.

You can find more information about loaders here:
http://angular-translate.github.io/docs/#/guide/13_custom-loaders
http://angular-translate.github.io/docs/#/guide/12_asynchronous-loading

Also, you can take any existing loader as an example.

**Comment by knalli** [comment]
@endamaco : Just like @DWand  already said: If you need more features within a loader, you can easily build your own. You can even re-use existing ones, since they are all documented and have a similar interface.
