### ISSUE TITLE
Define language code as parameter to translate filter

### ISSUE THREAD

**Issue by igorbljahhin** [angular-translate/angular-translate#994]
Hi!

I would like to ask to implement a bit unusual feature. Let me explain the background.

[Our website](http://saksa-eesti.ee/) is duolingual: its interface is in German and Estonian at the same time. We use angular-translate tool and all translations are stored in the single file. Estonian and German texts are separated by newline delimiter or by "|" symbol:

[en.json](http://saksa-eesti.ee/i18n/en.json):

    {
        "global": {
            "waiting": "Bitte warten...<br>Palun oota...",
            "placeholder": "Neues Passwort | Uus parool"
        }
    }

They are inserted into HTML as usual, using "translate" filter or translate directive.

I would like to separate translations to two files de.json and et.json. It would simplify the work of translators and we could use some fancy translations tools in the future. As far as I understand from the documentation we can't to pass the language code as the parameter to translate filter. Is it possible to implement this feature? My guess, that in our case we could use the parameter like this:

    <div class="header" translate="global.menu.help.header" translate-lang="de" /> | <div class="header" translate="global.menu.help.header" translate-lang="et" />

Thanks in advance!

Igor

**Comment by tspaeth** [comment]
Hi!
Thanks for your suggestion.

As you wrote, you would like to separate translations to two files as it is common practice. I would suggest to go that way. But also you write, that your existing page is already parsing. So how did you manage it? Extended the library so you would have a PR already in place?

But just my 2cents: I don't think that the core module of angular-translate should implement this exotic case. If there is enough request / demand for such a parser, it might make sense.

**Comment by igorbljahhin** [comment]
Hi, 
thanks for response.

Our existing HTML pages are not parsing, the translations are inserted as usual, like

    <h4 translate="global.waiting" />

shows the text in two languages at once

    Bitte warten...<br>Palun oota...

This special requirement is the reason why I could not split translation files into separate languages.

**Comment by knalli** [comment]
The concept of angular-translate for two different language sets is.. maintaining two language sets. That's simple.

If you really need such a specific special case, then you have to combine the result on your own. I don't see why we should implement such a special case as a general feature for common stuff.

Your self implementation can be started on different stages: Either on the server or as a custom loader which re-uses the existing loaders.. (i.e. 2x the static files loader).

**Comment by knalli** [comment]
hacky-hacky..

```js
angular.module('yourmodule').factory('$yourCustomLoader', function ($q, $translateStaticFilesLoader) {
  return function (options) {
    var deferred = $q.defer();
    $q.all([
      $translateStaticFilesLoader({prefix: 'lang/', key: 'en', suffix: '.json'}),
      $translateStaticFilesLoader({prefix: 'lang/', key: 'et', suffix: '.json'})
    ])
      .then(function (enTranslations, etTranslations) {
        // programmatically combine both language objects into one
        return result;
      })
    return deferred.promise;
  };
});
```
